### ISSUE TITLE
Bottom sheet text view height is increased after tapping `Generate` CTA

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#10022]
Ref: https://github.com/woocommerce/woocommerce-ios/pull/9597#pullrequestreview-1408549850

**Comment by jaclync** [comment]
I can't seem to reproduce this, @itsmeichigo can you confirm and close this if it's fixed on your end?

**Comment by itsmeichigo** [comment]
I can't reproduce it either, even with a really large font size. Closing this for now.
