### ISSUE TITLE
Login: Replace site credential login with web view login entirely.

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#10186]
From user reviews we received so far, there are a few issues with the current flow:
- Site credential login does not conform to security best practices. We ask users to enter credentials that we don't own.
- Cookie-nonce-based requests are very outdated.
- Site credential login has high chance for failures for sites with custom login/admin URL and/or security plugins. 
- The CTA for web view login in the error alert is not obvious to users, we got complaints regarding failures due to login URL but seems like they didn't try web view login.

Internal discussion: p1687772143505849-slack-C03L1NF1EA3

**Comment by itsmeichigo** [comment]
@pmusolino, could we send this ticket to Eagle just in case they can prioritize it?

**Comment by pmusolino** [comment]
@itsmeichigo I'll do it 👍 thanks for the ping!

**Comment by itsmeichigo** [comment]
Subtasks:

- [ ] Navigate to web view login with application password immediately when detecting that a site doesn't have Jetpack.
- [ ] Remove the entry point to the application password login in the login error alert of the authentication flow.
- [ ] Replace the CTA in the mismatched email error screen with a CTA to log in with application password. (Because handling Jetpack connection is currently requiring cookie-nonce authentication. We are supporting this step on the My Store screen already when the user logs in without Jetpack).

**Comment by HLFH** [comment]
>  Navigate to web view login with application password immediately when detecting that a site doesn't have Jetpack.

I would like to remove Jetpack as I only have to use it to connect the WooCommerce mobile app to my WooCommerce store.

**Comment by itsmeichigo** [comment]
@HLFH you can already log in to the app using site credentials or application passwords as long as you don't have Jetpack connected on your site.

**Comment by itsmeichigo** [comment]
Closing this due to insufficient metrics to back the motivation of the task. Internal discussion: p1695365235308839-slack-C013AAPA4G0.
