### ISSUE TITLE
A/B experiment: add product from a packaging photo

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#10180]
PT: pe5sF9-1H4-p2

### Yosemite layer

- [x] Add a new action `ProductAction.generateProductDetails` https://github.com/woocommerce/woocommerce-ios/pull/10183

### App layer

- [x] Create a new barebone screen & coordinator for adding a product from a packaging photo with a simple eligibility check for WPCOM stores https://github.com/woocommerce/woocommerce-ios/pull/10184
- [x] Update entry point https://github.com/woocommerce/woocommerce-ios/pull/10208
- [x] Integrate the media picker with the new screen https://github.com/woocommerce/woocommerce-ios/pull/10196
- [x] Scan text from the image, then generate product details https://github.com/woocommerce/woocommerce-ios/pull/10212
- [x] Show a list of selectable/editable scanned texts https://github.com/woocommerce/woocommerce-ios/pull/10220
- [x] Support name/description suggestion when the field is non-empty https://github.com/woocommerce/woocommerce-ios/pull/10225#issuecomment-1634522559
- [x] UI/UX updates:
  - [x] Add a Cancel/Dismiss CTA to the form so that it's dismissable in landscape mode https://github.com/woocommerce/woocommerce-ios/pull/10237
  - [x] Handle error from image scanning and API https://github.com/woocommerce/woocommerce-ios/pull/10238
  - [x] #10270
  - [x] #10269
  - [x] #10293
- [x] #10240
- [ ] Technical:
  - [x] Unit tests for `MediaPickingCoordinator` from https://github.com/woocommerce/woocommerce-ios/pull/10196
  - [x] Unit tests for `AddProductFromImageViewModel` from https://github.com/woocommerce/woocommerce-ios/pull/10196
  - [x] Extracting the logic for detecting text from an image into a separate class/struct that receives an `UIImage` and returns `[String]` (https://github.com/woocommerce/woocommerce-ios/pull/10212#pullrequestreview-1525560618) https://github.com/woocommerce/woocommerce-ios/pull/10227

### A/B experiment

Experiment proposal: pbxNRc-2MS-p2

- [x] Check A/B variant in the eligibility checker https://github.com/woocommerce/woocommerce-ios/pull/10253
- [x] Start the experiment in Abacus 21302-explat-experiment
- [x] Zendesk tag for eligible users #10290

### Known issues

- [x] When dragging to dismiss the media picker (device photo library or site media library), the image view is still loading. We can implement `UIAdaptivePresentationControllerDelegate` to change the view model's `imageState`. https://github.com/woocommerce/woocommerce-ios/pull/10236
- [ ] When tapping `Cancel` in the camera view, the image view is still loading https://github.com/woocommerce/woocommerce-ios/commit/a3efdb0649bb934d7624bf93495fe1a178984adf
- [ ] The multiline text field can have unexpectedly taller height after applying the suggested text
(Outdated since this entry point no longer triggers the new flow) Fix a bug where the media CTA from the product description AI modal doesn't do anything (probably because the coordinator is deallocated)
- [x] #10302

### Nice-to-haves

- [ ] In the Jetpack AI response, extract the JSON string from the response string in case there is any invalid text other than the JSON
- [ ] Test in iOS 15
- [ ] Enable flash by default when taking a photo with the camera (ref pe5sF9-1Es-p2#comment-2445)

**Comment by pmusolino** [comment]
Could we close this @itsmeichigo?

**Comment by itsmeichigo** [comment]
We didn't close this as there are still some nice-to-haves to be done. But we'll log them separately as needed.
