### ISSUE TITLE
Design enhancements for local announcements

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#10182]
Nice-to-have tasks from https://github.com/woocommerce/woocommerce-ios/issues/10021:

  - [ ] Improve large font / landscape layout by making the content scrollable
  - [ ] Animation improvements: p1688119318763379/1688072019.456769-slack-C0354HSNUJH

**Comment by itsmeichigo** [comment]
Closing because local announcement has been removed.
