### ISSUE TITLE
Unable to Add a New Note to the Order

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#10198]
Upon opening an order detail and selecting the "Add a new note" option, I am unable to input any text. It appears that the text field is non-selectable, preventing me from writing down the note.

**Comment by reginabally** [comment]
Another report in 6524309-zd-woothemes.

**Comment by igotdes** [comment]
Reported in:

- #6525521-zen
- #6522434-zen
- #6525182-zen
