### ISSUE TITLE
Unable to "Add a note" to Order

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#10215]
From an app review. Ref: p1689143231321609-slack-C03URUK5C

When attempting to add an order note to an Order via `Add a Note` (not `Add Customer Note`), the modal view that shows up to input further details is not selectable anymore, so no input can be entered.

| Header | Header |
|--------|--------|
| ![_230712_order_notes_disabled](https://github.com/woocommerce/woocommerce-ios/assets/3812076/ef88410f-803c-43f0-99f4-05def5f9da28) | ![simulator_screenshot_2D95CA99-7B3E-49FE-B8A2-848CB8A5D27E](https://github.com/woocommerce/woocommerce-ios/assets/3812076/2f45f8e7-7a56-45dd-8b17-a66fa9192fda) |

**Comment by itsmeichigo** [comment]
This seems to be a duplicate of #10198 😅

**Comment by iamgabrielma** [comment]
Thanks! Closing in favor of #10198, since that one has already been assigned.
