### ISSUE TITLE
Change AI generation endpoint

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#10214]
- [x] Start using `text-completion` instead of `jetpack-ai/completions` #10218
- [x] Add a link to the PT to track the costs per feature pe5sF9-1Do-p2#ai-usage-cost

**Comment by itsmeichigo** [comment]
@selanthiraiyan Can we close this ticket now?

**Comment by selanthiraiyan** [comment]
Thanks for checking, @itsmeichigo!

I must "Add a link to the PT to track the costs per feature" before closing this ticket. I will do that next week.

**Comment by selanthiraiyan** [comment]
Closing as I added cost dashboard links to PTs.
