### ISSUE TITLE
Order details: changes in visibility of the Billing Details section trigger an auto layout error

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#1021]
**Describe the bug**
Tapping the "Show billing" button in the Order Details screen triggers an auto layout error:

```
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x60000018d400 WooCommerce.TwoColumnSectionHeaderView:0x7f8bf052bcc0.trailingMargin == UIStackView:0x7f8bf0549b00.trailing   (active)>",
    "<NSLayoutConstraint:0x60000018e3a0 UIStackView:0x7f8bf0549b00.leading == WooCommerce.TwoColumnSectionHeaderView:0x7f8bf052bcc0.leadingMargin   (active)>",
    "<NSLayoutConstraint:0x60000018fc00 '_UITemporaryLayoutWidth' WooCommerce.TwoColumnSectionHeaderView:0x7f8bf052bcc0.width == 0   (active)>",
    "<NSLayoutConstraint:0x60000018fe80 'UIView-leftMargin-guide-constraint' H:|-(8)-[UILayoutGuide:0x600001bbc380'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':WooCommerce.TwoColumnSectionHeaderView:0x7f8bf052bcc0 )>",
    "<NSLayoutConstraint:0x60000018c870 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x600001bbc380'UIViewLayoutMarginsGuide']-(8)-|(LTR)   (active, names: '|':WooCommerce.TwoColumnSectionHeaderView:0x7f8bf052bcc0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60000018d400 WooCommerce.TwoColumnSectionHeaderView:0x7f8bf052bcc0.trailingMargin == UIStackView:0x7f8bf0549b00.trailing   (active)>
```

<img src = "https://user-images.githubusercontent.com/2722505/59240997-7d509100-8c38-11e9-933c-2ae0dd9c8b07.png" width="350"/>

**To Reproduce**
1. Build the app and run in the simulator
2. Go to an order Details screen
3. Click on 'Show billing'
4. Notice the autolayout error in the console

**Expected behavior**
Expansing and hiding the Billing Details section should not trigger any autolayout errors

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iOS Simulator
- iOS version: 
- WooCommerce iOS version: 2.0

**Comment by jaclync** [comment]
After some debugging and parsing the constraints, I believe these Auto Layout errors are caused by a temporary table view dimension of 0 in the early stage of the `UITableViewHeaderFooterView` layout cycle. Since the width and height of the `UITableViewHeaderFooterView` is zero initially, any constraints that leave non-zero spacing horizontally or vertically break the 0 width and height. I read some posts online to set these constraints with non-zero spacing to a lower priority like 999 (default is required 1000). But that seems a bit odd to me just getting around the errors/warnings at such edge timing.

I think this is a common Auto Layout issue. I'd like to check if there are more posts about this on Apple developer forum, will update later!

**Comment by mindgraffiti** [comment]
Apologies @ctarda and @jaclync that I didn't catch this sooner. Please halt all work on this ticket, as we have some new Order Details screen designs incoming that should make this problem obsolete.

**Comment by jaclync** [comment]
in any case, I did search this Auto Layout warning with `UITemporaryLayoutWidth = 0` issue on Apple developer forum, and I couldn't find any helpful information.
