### ISSUE TITLE
[Edit Order → Shipping] Shipping field name does update after saving

### ISSUE THREAD

**Issue by joe-keenan** [woocommerce/woocommerce-ios#10267]
Steps to reproduce:

* Create or edit and order
* Add a shipping cost
* Change the name of the shipping cost
* Save the shipping cost
* _The new name is not reflected in the Payments section_
  * This happens on both platforms – what is the expected behaviour?
* Edit the shipping cost to confirm that the new name is saved
* Close the shipping cost, and save the order
* _The new name is not reflected in the Payments section_
  * This happens on both platforms – what is the expected behaviour?
* Edit the order, and edit the shipping cost
* _**The new name has been erased**_
  * This only happens on iOS, Android remembers the name

https://user-images.githubusercontent.com/95003933/254769089-e1b0b80a-0d4e-49cb-a940-c66a727b07fc.MP4

**Comment by rachelmcr** [comment]
Closing as we've updated the way shipping is displayed/updated in an order, and I confirmed shipping details are saved/displayed as expected.
