### ISSUE TITLE
[IAP] Discrepancy in plan activation state when cancelling subscriptions

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#10289]
Context: 1689929860.372249&cid=C025A8VV728-slack-C025A8VV728/p1689930601011149

Cancelling an active subscription via the App Store seems to keep the wpcom subscription active at the moment, since no cancellation notification comes through when this happens, and we don’t know about an expiry until we receive the `EXPIRED` notification from Apple (which happens when the subscription actually expires).

> I cancelled it on apple’s side two weeks ago and I asked for a refund => the refund went through about 10 days ago.

> I also tried to cancel the original subscription (production) here <link to mobilepay order>. I moved the order to “cancelled state” but it still says I have an active subscription - any way how I can work around that? I mean, I also cancelled with Apple but they mentioned it’ll expire in August - I don’t see a way how to cancel it before that.

The same case can be seen while testing here: pdfdoF-3jx#comment-4526-p2

> I cancelled renewal. My site still is “Essential” because my subscription expires on August 6, at which point I’ll lose access. Do we have a way to distinguish whether a subscription renewal is set up? My guess is that it’s still showing as active because my subscription has not yet expired.

**Comment by joshheald** [comment]
@iamgabrielma This is expected behaviour, if I'm understanding you correctly. From cancellation, until their plan expires (at the end of the current billing interval), it's active.

It might be nice if we could show "not scheduled to renew" in wp-admin/the app, but that's a separate requirement and may not be possible, we'd need to check what StoreKit lets us find out.

If I'm understanding you correctly, I think we can close this ticket.

**Comment by iamgabrielma** [comment]
The plan remains active in WPCOM despite being cancelled and refunded via Apple though, so while there will be no further renewals since the subscription has been cancelled, the underlying product hasn't been cancelled despite the refund, and the site remains upgraded.

**Comment by iamgabrielma** [comment]
P2 with further details: pdfdoF-3tD-2

**Comment by iamgabrielma** [comment]
Resolved in MobilePay via `D117864`
