### ISSUE TITLE
Impossible to generate product description with AI: the button is disabled

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#10317]
If I try to create a new product, it's impossible to generate the description using AI since the button it's always disabled.

## Video

<img src="https://github.com/woocommerce/woocommerce-ios/assets/495617/e3f3e202-43f2-4c19-9d40-9c4b0e018fbe" width=300 />

**Comment by itsmeichigo** [comment]
This is not an issue, as both product title and keywords are now required for generating product description. We could use some enhancement regarding UX though - details to follow in the Slack discussion p1690326055300299-slack-C03L1NF1EA3.
