### ISSUE TITLE
Dashboard: Top Performers: tapping cell should present product detail screen

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1034]
I could not figure out why the tableview for the Top Performers isn't responding to taps. I added a `didSelectRowAt:` delegate method in the right place, to the correct VC, and got nothing. So I'm recording this as a separate task to be investigated shortly.

**Edit:** The top performers ProductTableViewCell is located inside of an XLTabPagerStrip control (the tabs that say Today, This Week, This Month, This Year in the Top Performers section). The tap gesture from the tab is eating the tap event for the cell, so `didSelectRowAt:` is never called. The tap gesture is private, so removing it isn't possible.

The only way I see to enable taps to cells is to either brute-force it (by finding the superview, finding the tap gestures, and override `cancelsTouchesInView:` by setting it to false) or work around it and either lay an invisible button over the top of the cell and capture a tap by adding a target to the invisible button. Or we can make only the image tappable.

**Comment by mindgraffiti** [comment]
@ctarda @jaclync what's your opinion on this? It's pretty hack-y because of the `XLTabPagerStrip`. WCAndroid allows the user to tap the cell and be navigated to the product details screen, so `won't do` isn't an option if we're going to keep parity with WCAndroid's functionality.

**Comment by ctarda** [comment]
@mindgraffiti @jaclync I am not sure this would be an actual solution, but it seems like we can attach a gesture to the horizontal scroll view (the `containerView` property in `ButtonBarPagerTabStripViewController`), that would give us the position of the tap. Maybe we could then forward it to the tableview somehow?

In `TopPerformersViewController`:

````
    func configureView() {
        let singleTap = UITapGestureRecognizer(target: self, action: #selector(taptaptap))
        containerView.addGestureRecognizer(singleTap)
        view.backgroundColor = StyleManager.tableViewBackgroundColor
        topBorder.backgroundColor = StyleManager.wooGreyBorder
        middleBorder.backgroundColor = StyleManager.wooGreyBorder
        headingLabel.applyFootnoteStyle()
        headingLabel.textColor = StyleManager.sectionTitleColor
        headingLabel.textInsets = Constants.headerLabelInsets
        headingLabel.text =  NSLocalizedString("Top Performers", comment: "Header label for Top Performers section of My Store tab.").uppercased()
    }

    @objc func taptaptap(gesture: UITapGestureRecognizer) {
        let touchPoint = gesture.location(in: containerView)

        print("touchPoint ==== ", touchPoint)
    }
````
