### ISSUE TITLE
Orders tab: the products API request always fails on pull-to-refresh

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#10359]
**Describe the bug**

After a new products API request was added to the orders tab pull-to-refresh https://github.com/woocommerce/woocommerce-ios/commit/5987290137ecd10220435aef702855236e99a02c, the request consistently failed with the following error:

```
{
	"error": "rest_invalid_param",
	"message": "Invalid parameter(s): page"
}
```

The reason is that [the page number is set to `0`](https://github.com/woocommerce/woocommerce-ios/blob/5d3ab7a2ddc6edd0716ed32b548eb4c3773a37ab/WooCommerce/Classes/ViewRelated/Orders/OrderListViewModel.swift#L246), while the page number in the API starts at `1` (`Remote.Default.firstPageNumber`).

**To Reproduce**

- Log in to a store if needed (self-hosted or WPCOM)
- Go to the Orders tab
- Pull-to-refresh --> when inspecting the API requests, an API request on `products` fails with a 400 error

**Expected behavior**

The API request should not fail.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: any
- WooCommerce iOS version: 14.7

**Comment by itsmeichigo** [comment]
Fixed in #10361
