### ISSUE TITLE
Move Close Account button further away from Log Out button

### ISSUE THREAD

**Issue by villanovachile** [woocommerce/woocommerce-ios#10398]
User report: 6616009-zd-a8c

A WooCommerce user uses the WooCommerce app for in person orders, and their reps need to log out and log in throughout the day.

In order to log out they need to go to Menu > Settings > Log Out. The problem on their end is that the "Close Account" button is right next to the "Log Out" button, which apparently has led to some accidental account closures:

![image](https://github.com/woocommerce/woocommerce-ios/assets/65082164/3897eef3-39dd-4d4b-a705-0122b8577d0b)

The user would like to request to move the Close Account button to somewhere that may be less prone to be tapped on accidentally.

**Comment by itsmeichigo** [comment]
Design: HyVloP5FipZzyPVenH2euI-fi-5127-65797
Slack discussion: p1692266552222669-slack-C03L1NF1EA3
Update: p1692342752106499-slack-C03L1NF1EA3
