### ISSUE TITLE
Add extensions product type to the product filter

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-ios#10418]
We want to include the extensions' product type in the product filter to increase the visibility of extensions' support in the app.

pe5pgL-2tE-p2

<img width="300" src="https://user-images.githubusercontent.com/8658164/225382934-95efd6d0-4ae6-4d21-aa19-cc78a7ef553d.png" />

**Comment by jaclync** [comment]
Implemented in https://github.com/woocommerce/woocommerce-ios/pull/10382, with additional tracking in https://github.com/woocommerce/woocommerce-ios/pull/10397. We can create some charts to understand more about the usage after 1-2 weeks of release.

**Comment by atorresveiga** [comment]
Marking this task as done 🎉
