### ISSUE TITLE
Dashboard: horizontal scrollers scroll in the wrong direction for RTL languages

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#1044]
As mentioned in the [comments here](https://wp.me/p5T066-TL-p2), the horizontal scrollers in the Dashboard present their content properly for RTL languages, but scroll in the opposite direction

**Comment by ctarda** [comment]
Those horizontal scrollers are provided by the Charts library, and are a UICollectionView

The way I worked around the fact that we do not own that code was by applying an affine transformation to flip the collection view, and the opposite transformation to the cells to render the texts in the right orientation.

This might just be a matter of changing the layout out scroll direction of the collection view as well for RTL languages.

**Comment by joshheald** [comment]
This still occurs, however is low priority and old, so I'm closing it now.
