### ISSUE TITLE
Settings: Extra Debugging

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1047]
Ref p77Llu-cbJ-p2

Much like WPiOS has the ability to do Extra Debugging, I'd like to change DDLogVerbose to be our level of extra debugging and DDLogDebug as the default level. Currently we are set to verbose by default.

See also: https://github.com/woocommerce/woocommerce-android/issues/1200 and #1019

**Comment by astralbodies** [comment]
Closing this for now as we haven't run into any situations where this is necessary.
