### ISSUE TITLE
`InAppPurchaseStoreTests` failing on iOS15: Using `SKTestSession` as dependency leads to flakiness

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#10474]
At the writing of this issue, we have disabled two tests due to `SKTestSession` not being reliable regarding clearing its default state, which causes tests to fail randomly:

```
test_user_is_entitled_to_product_returns_false_when_not_entitled()
test_user_is_entitled_to_product_returns_true_when_entitled()
```

Along with this, the whole suite of `InAppPurchaseStoreTests` fails if we run the test class on iOS15. These tests will not fail if are run separately though, which indicates there's a shared state that is not being cleared between runs when calling         `resetToDefaultState() `and `clearTransactions()`

This is no longer an issue if we run the suite under iOS16+, but worth noting since we're still supporting iOS15 at the moment.

### How to reproduce:
1. Load a simulator that uses iOS15, in my case I tested this with iPhone 13 iOS 15.0
2. Run the test suite for `InAppPurchaseStoreTests`. Observe how fails:
<img width="633" alt="Screenshot 2023-08-14 at 11 27 12" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/fd7eb701-9fcd-49f6-9274-967ec2d09c14">

3. Run the test separately, one by one. Observe how tests pass
4. Swift to an iOS16+ simulator, run the test suite again, observe how these pass.

**Comment by pmusolino** [comment]
@iamgabrielma do you think we can close this issue now that we support iOS16+?

**Comment by iamgabrielma** [comment]
Thanks for triaging, we can definitely close it!
