### ISSUE TITLE
(Non user facing) Multiple `EmptyListMessageWithActionView`s when attaching to superview

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1049]
**Describe the bug**
When searching for shipping providers in `ShipmentProvidersViewController`, we attach a new `EmptyListMessageWithActionView` to the main view to display that there is no shipping provider matching the search query. [`attach(to superview: UIView)`](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/ViewRelated/ReusableViews/EmptyListMessageWithActionView.swift#L44-L48) is called to attach this message+action view to superview. Because this function is called every time a search query has no results, it could be called multiple times and therefore multiple `EmptyListMessageWithActionView` could b in the view hierarchy (example in screenshot below with 2 `EmptyListMessageWithActionView`s).

**To Reproduce**
Prerequisites: the store has [Shipping Tracking extension](https://woocommerce.com/products/shipment-tracking/) installed and activated. Also the store should have at least one order.
- Go to 'Orders' tab
- Click on an order
- Click on 'Fulfill Order'
- Scroll down to '+ Add Tracking' (if you don't see this, make sure you have the [Shipping Tracking extension](https://woocommerce.com/products/shipment-tracking/) installed and activated)
- Click on 'Shipping provider' row
- Search for a shipping provider not in the list (e.g. `Fedox`) 

**Screenshots**
<img width="1280" alt="Screen Shot 2019-06-25 at 10 46 00 AM" src="https://user-images.githubusercontent.com/1945542/60122555-71de8900-9753-11e9-999d-7b99d493fa44.png">

**Expected behavior**
There should only be up to one `EmptyListMessageWithActionView` in the view hierarchy.

**Mobile Environment**
Please include:
- Device: any
- iOS version: any
- WooCommerce iOS version: any

**Comment by jaclync** [comment]
Personally I'd keep a reference to an optional `EmptyListMessageWithActionView`. Before calling [`attach(to superview: UIView)`](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/ViewRelated/ReusableViews/EmptyListMessageWithActionView.swift#L44-L48), remove the existing `EmptyListMessageWithActionView` from superview if it exists.

**Comment by shiki** [comment]
It might be better to migrate this to use [`EmptyStateViewController`](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/ViewRelated/ReusableViews/EmptyStateViewController/EmptyStateViewController.swift) instead and rely on child ViewController switching.
