### ISSUE TITLE
Nudge to set up WCPay

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#10556]
Update instructions and handling for WCPay setup from the onboarding task list.
Design: 7abnJ5szUDhwiczNwhcyW3-fi

Tasks:

- [x] #10570
  - [ ] Prioritize payment task over store launch and custom domain onboarding tasks.
  - [ ] Update wording for the onboarding task to "Manage payments seamlessly with WooPayments, free from setup or monthly fees."
  - [ ] Update link for onboarding task `wcPay` type - following pe5sF9-1VU-p2.
- [x] #10571
- [x] #10573 
- [x] #10587
- [x] #10588

**Comment by hichamboushaba** [comment]
@itsmeichigo should we close this task as completed now?

**Comment by itsmeichigo** [comment]
Sure, closing now!
