### ISSUE TITLE
Shipment tracking: empty line in "Shipping provider" cell before selected

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1056]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
- Launch the app with a store that has at least one order. Make sure there is no shipping provider selected before, otherwise you can reinstall the app to clear the history.
- Go to 'Orders' tab
- Tap on an order
- Tap "Fulfill order"
- Tap "Add Tracking" --> notice that there is an empty line for the shipping provider that is not yet selected

**Screenshots**

default font size | larger font size (not the largest)
--- | ---
![Simulator Screen Shot - iPhone SE - 2019-06-28 at 17 47 07](https://user-images.githubusercontent.com/1945542/60373506-6945b700-99ce-11e9-8720-b7d77fc546ca.png) | ![Simulator Screen Shot - iPhone SE - 2019-06-28 at 17 58 31](https://user-images.githubusercontent.com/1945542/60373507-6945b700-99ce-11e9-8652-d4caff60b8c8.png)

**Expected behavior**
The empty line looks a bit odd, especially with larger device font size.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: 12.2
- WooCommerce iOS version: 2.1

**Comment by ealeksandrov** [comment]
I think it was resolved by adding placeholder in 9e734221438ca2144f08e32d3fcb4140df424e64 (Part of https://github.com/woocommerce/woocommerce-ios/pull/1950)

regular | large
-- | --
![Simulator Screen Shot 1](https://user-images.githubusercontent.com/3132438/105376219-93973f00-5c1a-11eb-8076-c33be8825594.png)|![Simulator Screen Shot 2](https://user-images.githubusercontent.com/3132438/105376938-554e4f80-5c1b-11eb-99ee-192772fc5ed9.png)

**Comment by ealeksandrov** [comment]
Closing since with placeholder it looks fine now.
