### ISSUE TITLE
Add new screen for instructions before setup

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#10571]
<img width="239" alt="Screenshot 2023-08-30 at 8 26 51 AM" src="https://github.com/woocommerce/woocommerce-ios/assets/524475/d1ad867b-42ad-4930-8d90-bd4048d704a6">

- [ ] UI and navigation #10579
- [ ] Add URL for "Learn more" verifying your info page in Footer 83870f8fdd02b1c480d8b8b01268b2fe7b608568
- [ ] Dark mode asset for Woo Payments image

**Comment by itsmeichigo** [comment]
Closed by #10579
