### ISSUE TITLE
Fulfill Order: shipment tracking number is clipped for larger font sizes

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#1058]
Fixing #1055 made obvious that the shipment tracking number is also clipped for larger font sizes.

Steps to reproduce:
1. Navigate to the fulfilment screen for an order with shipment tracking.
2. Change the font size to use a larger size.
3. Notice the shipment tracking number clipped.

<img src="https://user-images.githubusercontent.com/2722505/60402618-a5db0380-9bc4-11e9-8b2d-1e56c9c6d04e.png" width="350"/>

**Comment by jaclync** [comment]
also worth fixing the shipping provider with a long name:

![Simulator Screen Shot - iPhone SE - 2019-07-01 at 09 39 53](https://user-images.githubusercontent.com/1945542/60441121-4d1b6300-9be4-11e9-9b09-957cf93e14b8.png)
