### ISSUE TITLE
Account creation: Integrate WPCom login without Authenticator library upon existing email

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#10590]
**Problem**
When a user enters the account creation flow and inputs an email that is associated with an existing WPCom account, we are sending the email to the authenticator library. This adds an extra step for the user to confirm their email before the login flow actually starts.

**Expectation**
We should navigate immediately to the password screen after an existing email is detected.

**Solution**
We can reuse the [in-house WPCom login flow](https://github.com/woocommerce/woocommerce-ios/tree/trunk/WooCommerce/Classes/ViewRelated/JetpackSetup/WPComLogin) implemented during the native Jetpack setup project.

**Comment by itsmeichigo** [comment]
Subtasks:

- [x] New coordinator for WPCom login.
- [ ] Unit test updates.
- [x] Security key support.
- [ ] Analytic updates.

Enhancements:
- [ ] Magic link flow to navigate to store creation automatically.
- [ ] Create use case in WPAuthenticator to reuse the security key logic instead of duplicating the code.
- [ ] Updates for JetpackSetupCoordinator to remove the duplicated code.

**Comment by itsmeichigo** [comment]
Closing as this is no longer part of our timeline.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
