### ISSUE TITLE
Change "WooCommerce Payments" wording

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#10621]
<img width="320" src="https://github.com/woocommerce/woocommerce-ios/assets/524475/d82b65c6-1b34-4b05-9812-78c5850a3046"/>

Reported during Kiwi beta testing
> Here it says WooCommerce Payments, but it should be WooPayments, and I think this is important since it’s the official product name.

Internal - p1693904207060199/1693904020.356639-slack-C03L1NF1EA3

**Comment by itsmeichigo** [comment]
Closing as this was handled in #10623.
