### ISSUE TITLE
Update order creation event properties to track extensions

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-ios#10706]
We want to track the usage of extensions through order creation. This task involves adding the `product_types` property to the order creation event. 

event: `ORDER_CREATE_BUTTON_TAPPED`
property `product_types` -> a string property containing all product types inside an order divided by ','
Example: `"product_types": "bundle, variable"`

**Comment by jaclync** [comment]
@atorresveiga just a note that in iOS we don't have the space after the comma separator, since the logic is shared with the previous event `order_products_loaded`'s `product_types` property.
