### ISSUE TITLE
[Orders with Coupons M7] Make discounts and coupons mutually exclusive

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#10838]

**Comment by joshheald** [comment]
@iamgabrielma Could you add some commentary on why we're making them mutually exclusive to this issue? It seems like the kind of thing which we'll end up coming back to and the answer isn't immediately obvious to me...

**Comment by iamgabrielma** [comment]
> Could you add some commentary on why we're making them mutually exclusive to this issue? It seems like the kind of thing which we'll end up coming back to and the answer isn't immediately obvious to me...

Apologies, I only saw this ping after closing the issue. 

I picked up the project on M6/M7, so I don't have the full context, but my understanding is that there's back-end limitations/problems to applying both order-wide coupons and single-product discounts to the same order (perhaps since both act as a negative fees?) 

This was decided around M3-M4 here: pdfdoF-2RK#comment-4554-p2 and designs were updated to reflect it, since was not initially accounted for.

> We discovered a backend issue when applying direct discounts while having active coupons. We plan to explore this further and come up with a plan for a fix. For now, we decided to disable adding discounts in case there are active coupons.

Pinging @samiuelson for more details.
