### ISSUE TITLE
On iPhone SE "Lost your password" hides input when logging in

### ISSUE THREAD

**Issue by grig-23** [woocommerce/woocommerce-ios#1087]
**Describe the bug**
On iPhone SE "Lost your password" hides input when logging in

**To Reproduce**
1. Attempt to log in on iPhone SE (possibly a simulator would work too?)
2. Go to the page where login credentials have to be entered

**Screenshots**

Screencast: https://cld.wthms.co/Qfs7Nu

**Expected behavior**
I'd expect to see what I'm writing

**Isolating the problem (mark completed items with an [x]):**
- [N/A] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [N/A] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone SE
- iOS version: 12.1.2
- WooCommerce iOS version: 2.1

**WordPress Environment**
<details>
N/A
</details>

**Comment by shiki** [comment]
As far as I can tell, this has been fixed. The screens are now also scrollable. 

<img src="https://user-images.githubusercontent.com/198826/126243613-b96489ba-a05e-4d2f-8571-5154eb5acdfb.png" width="300">
