### ISSUE TITLE
[Order Editing] Removing product from order via decreasing quantity fails to save correctly

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#10874]
When removing a product from an existing order (Order Editing flow) by tapping the `-` button, the product disappears correctly from the order being edited, but upon attempting to save the changes it would seem that these fail.

This was originally reported here https://github.com/woocommerce/woocommerce-ios/pull/10845#issuecomment-1749509699 while working on a related feature:

> One note post-review – it seems like if you edit an order and remove products (with the minus button) and tap done, further edits to that order always(?) fail:
> ⛔️ Error syncing order remotely: Dotcom Error: [woocommerce_rest_invalid_item_id] Order item ID provided is not associated with order.

Confirmed that this issue is currently in trunk, and as far as I tested it happens at least since 15.3 (is not part of the new component implementation):
![Simulator Screen Recording - iPhone 15 - 2023-10-06 at 11 14 15](https://github.com/woocommerce/woocommerce-ios/assets/3812076/fe0fe96c-fcbf-4058-a027-4dc599f4a75d)

Something interesting, the order seems to be updated when we check it from the Order List (see order 1337 in the screenshot). The order total = $0.00 , however when we open its details, the product seems to appear there. If then we tap on `+` to increase the quantity, we'll see the sync error: Error syncing order remotely: Dotcom Error: [woocommerce_rest_invalid_item_id] Order item ID provided is not associated with order.

| Order List | Order Detail |
|--------|--------|
| ![simulator_screenshot_E70E073A-1392-44B6-BFE5-95F43D40A935](https://github.com/woocommerce/woocommerce-ios/assets/3812076/2974236e-f2bc-41f2-aa44-c096ebe1f994) | ![simulator_screenshot_C6FD10E8-7938-4D4A-B401-70DDAD7B85A5](https://github.com/woocommerce/woocommerce-ios/assets/3812076/8ed281c0-f040-4dea-8074-684c4fee7620) |

**Comment by Ecarrion** [comment]
This seems to be working ok, as there is dedicated "remove product from order" CTA
