### ISSUE TITLE
Add badge to orders tab

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1089]
Updated - reducing scope to only add the bubble to the orders tab. Do not refactor the orders list or remove from dashboard for this task.

See: https://github.com/woocommerce/woocommerce-android/pull/1245

-----
Original:

As per recent designs, we should drop the "orders to fulfill" card from the Dashboard, and add a badge to the order list showing the number of unfilled orders. The design will change after discussing technical challenges in https://github.com/woocommerce/woocommerce-android/pull/1228/. Check there for decisions before beginning this task.

![bubble](https://user-images.githubusercontent.com/3903757/60836103-df96a600-a192-11e9-9380-d66671065f21.png)

**Comment by astralbodies** [comment]
Updated scope to only add the badge to the orders tab. A separate task will be required for the refactoring of the dashboard and orders list.
