### ISSUE TITLE
Order Details: Update Customer Information section

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1091]
Update the Customer Information section to follow the Refunds i3 design:

- [ ] Coordinate / check with Android - what is required to add a customer gravatar?
- [ ] Write separate task(s) if needed
- [ ] Update Customer Information section layout

<img width="460" alt="Screen Shot 2019-07-12 at 10 06 47 AM" src="https://user-images.githubusercontent.com/1062444/61138535-51216d80-a48d-11e9-927d-0e755d04811d.png">

**Comment by anitaa1990** [comment]
I started investigating the API needed to fetch the customer avatar information. More details on that [here](https://github.com/woocommerce/woocommerce-android/issues/1238)

**Comment by ctarda** [comment]
implemented in PR #1241
