### ISSUE TITLE
REST API: Support sites with disabled "Pretty Permalinks"

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-ios#10924]
Currently, sites with disabled ["Pretty Permalinks"](https://wordpress.org/documentation/article/customize-permalinks/#pretty-permalinks) don't work with the app, and specifically these are the features that don't work: 

1. Sign in using Application Passwords.
2. Jetpack installation/connection when adding a site from the site picker.  
 
The cause for this is that the JSON API endpoint is being hardcoded to `{siteUrl}/wp-json`, which doesn't work when the above option is disabled.
To fix this, the iOS app has to implement a logic to discover the URL similar to what Android is doing following the official documentation: https://developer.wordpress.org/rest-api/using-the-rest-api/discovery/

**Comment by itsmeichigo** [comment]
@hichamboushaba I'm looking into how to handle this on iOS. I'm curious when do you handle the discovery on Android - is it immediately before fetching application password URL? Do you persist the path somewhere?

There's another case where we are hardcoding the root path for all REST API endpoints. I assume you also handled the discovery before building the paths for REST requests. Since the discovery is async, I'm having trouble finding where to put it in this process. I'm curious to know how this was done on Android.

**Comment by hichamboushaba** [comment]
@itsmeichigo as discussed before p1669743451393799-slack-C046HDZL87J, the discovery in Android is [handled](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/09842f3637ea26e0f2f8bcff62b2511c13257a7f/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/site/SiteWPAPIRestClient.kt#L44) as part of the site fetching (fetching the root endpoint), which happens either after the Cookie Nonce login, or before opening the Application Passwords login page in case of WebView login.

Fetching the site results in persisting a `SiteModel` object that has a property `wpApiRestUrl`, this property is used also when constructing the REST API endpoints.

I think iOS has a different handling, which could make following the same harder, so what do you think about running the discovery twice, once during the fetch, and a second one after the login when you persist the site? if this doesn't make sense, please ignore my iOS newbie suggestions 😅

**Comment by itsmeichigo** [comment]
Thanks for the suggestions Hicham! I'll see what I can do with this.

**Comment by itsmeichigo** [comment]
@hichamboushaba I'm thinking instead of doing the complicated discovery, we should be able to hardcode the default path `?rest_route=` instead. From what I understand, sites with pretty permalinks all redirect to the default path eventually. I tested and that worked for me. WDYT about that?

**Comment by hichamboushaba** [comment]
> @hichamboushaba I'm thinking instead of doing the complicated discovery, we should be able to hardcode the default path ?rest_route= instead. From what I understand, sites with pretty permalinks all redirect to the default path eventually. I tested and that worked for me. WDYT about that?

Good idea ✨, I think this would work too @itsmeichigo.
