### ISSUE TITLE
Order Details: Update Order Notes

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1092]
Per the Refunds i3 designs, update Order Notes with the new layout:

<img width="276" alt="Screen Shot 2019-07-12 at 10 15 44 AM" src="https://user-images.githubusercontent.com/1062444/61139011-1c61e600-a48e-11e9-8d9e-54a7437db707.png">

**Comment by pmusolino** [comment]
Just an update. The design on i3 changed a little bit:
<img width="381" alt="Schermata 2019-08-21 alle 15 05 29" src="https://user-images.githubusercontent.com/495617/63434375-3eec0500-c425-11e9-90d0-74952e5bc15b.png">

**Comment by mindgraffiti** [comment]
Hey @pmusolino 👋 

That is a screenshot of the Android Order notes design. The one I put in the main description is for iOS.

**Comment by ctarda** [comment]
Implemented in PR #1226
