### ISSUE TITLE
Order Details: Add a new screen for Billing Information

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1093]
Per the Refunds i3 design, upon tapping the View Billing Information cell, navigate to the newly designed screen:

<img width="270" alt="Screen Shot 2019-07-12 at 10 17 45 AM" src="https://user-images.githubusercontent.com/1062444/61139176-782c6f00-a48e-11e9-858d-eefa10dab2c0.png">

**Comment by ctarda** [comment]
Implemented in PR #1241

**Comment by ctarda** [comment]
Reopening 😊

**Comment by ctarda** [comment]
Implemented in #1244
