### ISSUE TITLE
[Issue Refunds] Refund View

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1094]
Depends on #1487.

Add a new screen, Refunds, with a section for the items.

<img src="https://user-images.githubusercontent.com/198826/92661621-3f6a6e80-f2ba-11ea-8516-f76d3aa06088.png" width="320">

<img width="320" alt="Screen Shot 2019-07-12 at 10 24 28 AM" src="https://user-images.githubusercontent.com/1062444/61139622-47006e80-a48f-11e9-88f3-4c37b3ac14c8.png">
 
## Goals

- The screen is shown when tapping on the Refund button (#1487)
- “Select all” and “Select None” buttons work
- Manual entry of quantity

**Comment by Ecarrion** [comment]
Close as this has been split in several tasks
