### ISSUE TITLE
Store creation: Missing tracking when store creation starts from the signup flow

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#10964]
[Clone from https://github.com/woocommerce/woocommerce-android/issues/9967]

We rely on `site_picker_create_site_tapped` event as a starting point for creating flows related to store creation. This event is fired when tapping on “Create a new store” from the bottom sheet in site picker.

However, there is a case where the store creation flow is triggered but `site_picker_create_site_tapped` is not tracked: when a user signs up and gets navigated to the store creation flow. This means that any funnel that sets `site_picker_create_site_tapped` event as the starting point will miss out on all the new users signing up.

The solution is to create a new event that we ensure is tracked ALWAYS when triggering store creation flow, disregard of where is the store creation triggered from or which is the first step of the store creation.

Event name: `site_creation_flow_started`
Properties: `source`: `store_picker` | `prologue` (existing values for site creation)

**Comment by pachlava** [comment]
Adding a priority label to avoid this issue getting into the list for the MTTR metric.
See pdcxQM-2Su-p2
I'm setting `priority: low` since the bug is not user-facing. Correct me if I'm wrong.
