### ISSUE TITLE
Blaze Optimization: Update entry point from Product detail screen

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#10961]
<img width="500" alt="Screenshot 2023-10-19 at 10 49 23" src="https://github.com/woocommerce/woocommerce-ios/assets/266376/e97f66b3-aa18-4625-9258-b8e70ed7fd97">

- Remove option from dot menu
- Create "Promote with Blaze" button instead
- Handle navigation upon tapping the button:
  - If no campaign is available yet, show the intro screen.
  - Otherwise, navigate to campaign creation.

--- 
Subtasks

- [x] UI https://github.com/woocommerce/woocommerce-ios/pull/10970
- [x] Functionality https://github.com/woocommerce/woocommerce-ios/pull/11011
- [x] Tracking: add a new Blaze source `product_detail_promote_button` and track `blaze_entry_point_displayed` and `blaze_entry_point_tapped` https://github.com/woocommerce/woocommerce-ios/pull/11011

**Comment by selanthiraiyan** [comment]
Reopening to cover "Hide the promote button if there is an existing campaign for the product" subtask

**Comment by itsmeichigo** [comment]
Closing this task because the new subtask has been logged in #11305.
