### ISSUE TITLE
Refunds Step 2: Networking

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1097]
Ref. p99K0U-1n6-p2

Per the Refunds API Research, add endpoints and API requests to the Networking layer so that:

- [x] a full refund can be sent by OrderID
- [x] a partial refund can be sent by OrderID
- [x] the order details can be updated - get all current refunds by OrderID

Follow up with Android devs and add any extra endpoints or request functions they discovered.

**Comment by pmusolino** [comment]
@mindgraffiti just like android https://github.com/woocommerce/woocommerce-android/issues/1242,  the shipping-only refunds is not supported by the current API.
Can you also delete it from the iOS checklist? (I don't have the privileges to do it.)
Thanks!

**Comment by mindgraffiti** [comment]
@pmusolino deleted! Also assigned the ticket to you.
