### ISSUE TITLE
Wrong language when creating products with AI

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-ios#10987]
Sometimes when using a package photo that has keywords in English, the generated description is in different language.

<img src="https://github.com/woocommerce/woocommerce-ios/assets/1522856/405ce7a7-63b3-4e27-ba3b-692056a51bee" width="500" />

![15660_nestle-kitkat-chunky-caramel-43-5g-nejkafe-cz](https://github.com/woocommerce/woocommerce-ios/assets/1522856/3cd87b46-7d9a-47fe-9952-99caa639de9e)

**To test:**
1. Use the KitKat package photo above to generate name & description
2. Notice the generated text is not in English (the behavior is inconsistent, could take a few tries)

**Comment by selanthiraiyan** [comment]
Addressed this in https://github.com/woocommerce/woocommerce-ios/pull/11023 by sending a separate AI prompt request to identify language from scanned keywords.
