### ISSUE TITLE
[Orders with Coupons] Informational tooltip rendering incorrectly on empty order

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#10997]
Reported here: p1698051202366919/1698051169.929429-slack-C025A8VV728

When starting a new order, the informational tooltip in the coupon row renders by default, this is incorrect, since should only show when an order has product discounts and coupons become ineligible.

<img width="430" alt="Screenshot 2023-10-24 at 15 54 50" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/ffd4f074-a8fb-4df1-b6f0-056bdac4041a">

**Comment by pachlava** [comment]
Adding a priority label to avoid this issue getting into the list for the MTTR metric.
See pdcxQM-2Su-p2

I'm setting `priority: medium` since the issue with tooltip untimely display might affect a lot of users, but it's not breaking or blocking their workflow. Correct me if I'm wrong.

**Comment by iamgabrielma** [comment]
Thanks for the P2 link.

> I'm setting priority: medium since the issue with tooltip untimely display might affect a lot of users, but it's not breaking or blocking their workflow. Correct me if I'm wrong.

That's correct 👍
