### ISSUE TITLE
[TTPUK] About Tap to Pay on iPhone screen should not have Set Up button after first transaction

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#11009]
## Description
An oversight from #10945 – the CTA button for Set Up Tap to Pay should be removed from the About screen when we think the user has already set up the feature.

<img width="1040" alt="Designs showing Try Out TTP button in menu and no button on About screen" src="https://github.com/woocommerce/woocommerce-ios/assets/2472348/6b8241f1-a2fa-4114-ac09-973d5627c96c">

**Comment by pachlava** [comment]
Adding a priority label to avoid this issue getting into the list for the MTTR metric.
See pdcxQM-2Su-p2

I'm setting `priority: low` since the issue is about showing a link to `About` screen when it's not necessary. Correct me if I'm wrong.
