### ISSUE TITLE
[Orders with Coupons] `Price after discount` shows incorrectly if we have multiple items of the same type

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#11015]
Adding a discount to a product row with 1+ items will show `Price after discount` incorrectly, since this is only shown as "price of the product - discount" 

<img width=800 src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/c56cbdff-d826-4d53-8e0b-7104a8b4436a">

**Comment by pachlava** [comment]
Adding a priority label to better align with the rules for MTTR metric.
See pdcxQM-2Su-p2

I'm setting `priority: high` since the issue is about incorrect price display (costs-related). Correct me if I'm wrong.

**Comment by iamgabrielma** [comment]
I modified it to medium, since the total price calculation, and the price displayed both per-product, and and per-order would still be correct. This only affected the UI display on a specific product row when a merchant follows the following flow: Add product > add discount > increase quantity afterwards.
