### ISSUE TITLE
Login: Cannot connect Jetpack on the Account Mismatch error screen

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#11037]
**Description**

The Connect Jetpack button on the account mismatch screen doesn't work as expected.

**Steps to reproduce**

- Create a new JN site.
- Install and connect Jetpack using your primary WPCOM account.
- Create a new "Shop Manager" account from the wp-admin page. The email is from a different WPCOM account named Alias.
- Log out of the app if needed.
- On the prologue screen, enter the address of the JN site.
- Proceed to log in with the alias user WPCom account.
- The account mismatched error screen is displayed. Tap on the Connect Jetpack button.
- Enter the site credentials of the alias account.
- The site credential login screen is dismissed, you are stuck on the account mismatched screen.

https://github.com/woocommerce/woocommerce-ios/assets/5533851/61f8bf35-fd85-4b7a-8fd4-7fd80c18ebe4

**Comment by pachlava** [comment]
Adding a priority label to better align with the rules for MTTR metric.
See pdcxQM-2Su-p2

I'm setting `priority: high` since the issue blocks login workflow for a specific case. Correct me if I'm wrong.
