### ISSUE TITLE
Login: Handle application password callback when logging in from the mismatched email screen.

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#11033]
**Description**

When a user reaches the mismatched email screen and proceeds to connect their WPCom account with Jetpack, they are first asked to log in with their site credentials. This step can fail if they have any security measure enabled, forcing them to log in with an application password. We haven't handled the callback when the application password login completes to continue Jetpack connection.

Internal discussion: pdAuLa-ef-p2#comment-239.

**Comment by itsmeichigo** [comment]
Closing as we have no plan to handle this.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
