### ISSUE TITLE
Stats Step 3: Add scrubbing interaction to charts

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-ios#1106]
As part of the new stats improvements, we would need to tweak the interaction on the chart bars to update the stats. This involves adding a scrubbing interaction similar to the behaviour below.

<img width="300" src="https://user-images.githubusercontent.com/22608780/61261022-feea9000-a79d-11e9-9b24-567b273c6672.gif">

**Comment by jaclync** [comment]
Tasks:
- [ ] update site visit stats request params:
- "this week": quantity=7, unit=day, date=#{end_of_this_week}
- "this month": quantity=#{num_days_this_month}, unit=day, date=#{end_of_this_month}
- "this year": quanity=12, unit=month, date=#{end_of_this_year}
- [ ] enable scrubbing (looks like `dragEnabled=true` might work?)
- [ ] update data in date bar and visitor/store stats:

time range | date bar (`en` example) | visitor stats | store stats
-- | -- | -- | --
today | "Wednesday, Aug 21" --> "Wednesday, Aug 21 > 2am" | hide visitor stats (we don't have hourly visitor stats) | show `OrderStatsV4Interval.subtotals`'s `totalOrders` and `grossRevenue`
this week | "Aug 18-Aug 21" --> "Aug 21" | show `SiteVisitStatsItem.visitors` | show `OrderStatsV4Interval.subtotals`'s `totalOrders` and `grossRevenue`
this month | "August" --> "Aug 21" | show `SiteVisitStatsItem.visitors` | show `OrderStatsV4Interval.subtotals`'s `totalOrders` and `grossRevenue`
this year | "2019" --> "2019 > August" | show `SiteVisitStatsItem.visitors` | show `OrderStatsV4Interval.subtotals`'s `totalOrders` and `grossRevenue`
