### ISSUE TITLE
Product creation bottom sheet resizing UI glitch

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-ios#11072]
Add product bottom sheet displays some resizing glitching when opened

Reproduced on: 
- iPad Pro 11"
- iPad OS 16

https://github.com/woocommerce/woocommerce-ios/assets/2663464/28f0e9af-25e3-43cf-a1e9-de118699e74b

**Comment by itsmeichigo** [comment]
Also fixed by #11695
