### ISSUE TITLE
Blaze: Trigger campaign sync when merchants successfully creates campaign in webview

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#11084]
In the "Hide button in Product Form" PR (https://github.com/woocommerce/woocommerce-ios/pull/11082), this use case happens:

1. Merchant creates a campaign from the Product form, 
2. Merchant returns to Product form screen from Blaze webview, 
3. The Blaze button is still shown, even though there's a newly created campaign.

This is because there is no sync happening during the steps, and the hiding check only observes from Core Data. Only after the campaign list is updated elsewhere (from Dashboard or More menu), that the sync will happen.

A potential solution is:

Listen to an URL from web view when a campaign is created -> Send network request to reload campaigns -> Update core data -> Product detail screen listens to the core data and updates the promote button (props @selanthiraiyan)

Note that:
1. a sync request already also updates core data,
2. product detail screen already listens to core data

So for this task potentially just listening to URL to trigger sync campaign is needed.

**Comment by itsmeichigo** [comment]
Closing this issue as we no longer create campaigns in web view.
