### ISSUE TITLE
Blaze: Consider renaming `canPromoteWithBlaze` function and string in ProductFormViewModel

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#11083]
Opinion: Now that we have added an extra condition, what do you think about renaming this into `shouldShowPromoteWithBlaze`? I hope this is only about deciding the promote button's visibility.

_Originally posted by @selanthiraiyan in https://github.com/woocommerce/woocommerce-ios/pull/11082#discussion_r1381650850_

**Comment by JorgeMucientes** [comment]
@hafizrahman I haven't checked the code, but is this task only about renaming a function in the code? Do we need a GH for it? Do you think we can maybe close this?

**Comment by hafizrahman** [comment]
Yeah, it's been a while and I think it's okay as a wontfix. Closing it.
