### ISSUE TITLE
[Orders List: Filters] Status filter list shows “Pending” instead of “Pending payment”

### ISSUE THREAD

**Issue by joe-keenan** [woocommerce/woocommerce-ios#11174]
**Describe the bug**
The list of statuses inside the Filter menu in the Orders list has a status called “Pending”. This should be called “Pending payment”, to be consistent with the orders list, detail screens, and the web.

**To Reproduce**
1. Go to 'Orders'
2. Tap on 'Filter'
3. Tap on to 'Order Status'
4. See status “Pending”

**Screenshots**
| Filter list | Orders list | 
| --- | --- |
| ![AA1CE7A5-6620-4335-8DBA-EA5C49AC70DB_1_102_o](https://github.com/woocommerce/woocommerce-ios/assets/95003933/1cc6b684-de45-4bd7-8aaa-10d5a011360c) | ![60F1FC92-6526-4D05-A74C-B3D81F9A060B_1_102_o](https://github.com/woocommerce/woocommerce-ios/assets/95003933/9bd37eaf-6596-495a-9d71-e5f829ed2faa) |

**Expected behavior**
The status name should read “Pending payment”.

**Mobile Environment**
Please include:
- Device: iPhone 15 Pro
- iOS version: 17.2
- WooCommerce iOS version: 16.2.0.0

**Comment by rachelmcr** [comment]
I confirmed that this currently shows "Pending Payment":

![IMG_187DD66796BA-1](https://github.com/user-attachments/assets/effc349a-d0a4-4a2c-85b0-e2207183d3b5)

Closing as resolved.
