### ISSUE TITLE
Blaze: Incorrect Store Products Displayed in Blaze on iOS App after Switching Stores

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#11187]
**Description:**

I discovered an issue where products from the wrong store are being displayed in Blaze. This happens specifically after I switch from one store to another.

**Steps to Reproduce:**

1. Open the WooCommerce iOS app.
2. Try to create a Blaze campaign and observe the products available, they are related to the current store.
3. Switch from Store A to Store B.
4. Try to create a new Blaze campaign on Store B.
5. Notice that the products being displayed are from Store A instead of Store B.

**Expected Behavior:**

When switching stores, the products displayed in Blaze should correspond to the currently selected store.

**Workaround:**

Closing and reopening the app seems to fix the issue temporarily, with the correct products from Store B displayed in Blaze. However, the issue reoccurs when switching stores again.

**Demo**

<img src="https://github.com/woocommerce/woocommerce-ios/assets/495617/245306b7-45a6-4e07-9e50-b28ac76762e7" width=300 />

**Comment by itsmeichigo** [comment]
Fixed by #11081.

**Comment by itsmeichigo** [comment]
This issue can still be reproduced when starting campaign creation from My Store.

**Comment by pmusolino** [comment]
Closing this issue since it seems to have been fixed.
