### ISSUE TITLE
High CPU Usage in Dashboard on Xcode 15 and Xcode 14

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#11203]
**Problem**
When the app is built with Xcode 15, the CPU usage in the 'My Store' tab (`DashboardViewController`) spikes to 100%, resulting in an unresponsive UI. The same codebase, when compiled with Xcode 14, exhibits CPU usage at around 20%. This high CPU usage is unusual for a static view and suggests a potential underlying issue that impacts app performance.

**Investigations**
Through some debugging and profiling using Instruments, it appears there may be an infinite loop or an excessive number of UI updates occurring in the UI lifecycle, particularly in `DashboardViewController`. This was inferred based on the consistent high CPU usage and UI irresponsiveness.

Highlighted areas include:
- Callbacks from Core Animation (`CA::Display::DisplayLink::callback`)
- Repeated additions to view hierarchies (`_UIKitAddSubview`)
- Auto Layout constraints being repeatedly updated
- Reactive programming patterns using Combine that may be causing feedback loops

There is also a particular suspicion towards `StoreStatsAndTopPerformersViewController`, which contains asynchronous and reactive patterns, and the `syncStats` and related methods that may trigger multiple network calls.

**Next Steps**
A more in-depth investigation is required to find the exact cause. Potential steps could be:
- Reviewing Combine publishers and subscribers' chains for feedback loops
- Analyzing and optimizing Dispatch Groups in `StoreStatsAndTopPerformersViewController`
- Profiling methods in the `StoreStatsAndTopPerformersViewController` related to UI updates and network syncing

Any insights or suggestions would be greatly appreciated, as this issue seems to be affecting users' ability to interact with the dashboard effectively.

#### CPU usage in Xcode 14
<img width="308" alt="xcode 14-3 and iOS 16-4" src="https://github.com/woocommerce/woocommerce-ios/assets/495617/09d95b0c-1cff-404c-a5a9-dd56b6d9d58d">

#### CPU usage in Xcode 15
<img src="https://github.com/woocommerce/woocommerce-ios/assets/495617/b37046d5-7cbf-4978-b494-85b1af28ffed" width=300 />

#### Instruments tree
<img src="https://github.com/woocommerce/woocommerce-ios/assets/495617/471d8744-3dcc-4511-9abd-319e491dd037" width=300 />

**Comment by itsmeichigo** [comment]
The code around store stats is very complicated to track down performance issue. If we are dropping iOS 15, do you think we should consider refactoring this part of the app and using SwiftChart instead? I played with it in one of my last HACK week project (paNNhX-tA-p2), so I can try bringing that work to refactor the code in Dashboard. This sounds quite ambitious and risky TBH, but if you think it's worth it, I can take it as the challenge for the next HACK week.

**Comment by jaclync** [comment]
I was thinking about HACK Week and found this issue 👋 

Out of curiosity, I tried removing a subview at a time in the My store tab vertical stack to find the root cause. It looks like the culprit is the top performers view - the performance is back to normal after commenting out the top performers subview:

https://github.com/woocommerce/woocommerce-ios/blob/b94e3bf1b95a293945ba2f08541719d9ea34754f/WooCommerce/Classes/ViewRelated/Dashboard/Stats%20v4/StoreStatsAndTopPerformersPeriodViewController.swift#L235-L236

Before taking a deeper look and just a guess, it might be from the use of `SelfSizingHostingController` (workaround for dynamic height for SwiftUI view in UIKit).

**Comment by jaclync** [comment]
Update from a time-boxed look: it looks like the performance issue is from `shimmering` in `DashboardTopPerformersView` and `TopPerformersView`, but I haven't found a solution. I've tried moving `shimmering` and `redacted` to a lower level at `TopPerformersView`/`TopPerformersRow`, but it didn't work. There might be other reasons that cause `shimmering` to be expensive as `shimmering` is also used in other views in the dashboard.

**Comment by joshheald** [comment]
> I was thinking about HACK Week and found this issue 👋
> 
> Out of curiosity, I tried removing a subview at a time in the My store tab vertical stack to find the root cause. It looks like the culprit is the top performers view - the performance is back to normal after commenting out the top performers subview:
> 
> https://github.com/woocommerce/woocommerce-ios/blob/b94e3bf1b95a293945ba2f08541719d9ea34754f/WooCommerce/Classes/ViewRelated/Dashboard/Stats%20v4/StoreStatsAndTopPerformersPeriodViewController.swift#L235-L236
> 
> Before taking a deeper look and just a guess, it might be from the use of `SelfSizingHostingController` (workaround for dynamic height for SwiftUI view in UIKit).

This is a great find @jaclync. It also resolves the high memory usage crash on builds from Xcode 15.

**Comment by joshheald** [comment]
> Update from a time-boxed look: it looks like the performance issue is from `shimmering` in `DashboardTopPerformersView` and `TopPerformersView`, but I haven't found a solution. I've tried moving `shimmering` and `redacted` to a lower level at `TopPerformersView`/`TopPerformersRow`, but it didn't work. There might be other reasons that cause `shimmering` to be expensive as `shimmering` is also used in other views in the dashboard.

So, there are four of these views. The ones that are shimmering are those which aren't even on screen; the ones in the tabs we've not been to yet. If you go to each of the 4 stats tabs, they load, stop shimmering, and memory use settles.

One fix would be only to start shimmering when we actually appear and start loading...

Watch the little memory graph in this video for an example:

https://github.com/woocommerce/woocommerce-ios/assets/2472348/b1aea153-25ee-4669-8ffb-70e8bc73be87

It still seems strange to me that four shimmering views would make all these repeated allocations. I had a look at the package repo and [there's a new version which mentions iOS 17 issues](https://github.com/markiv/SwiftUI-Shimmer/releases/tag/1.4.0)

From my testing, updating to this fixes the memory issue. I'll put a PR up and we can each test it a bit...

**Comment by joshheald** [comment]
PR here: #11320
