### ISSUE TITLE
“Add a product” half-sheet has too much white space at the bottom

### ISSUE THREAD

**Issue by joe-keenan** [woocommerce/woocommerce-ios#11211]
The title says it all.

1. Go to 'Products'
2. Click on the plus icon to add a new product
3. The half-sheet that opens with “Create a product with AI” and “Add manually” has a large section of white space at the bottom.

![image](https://github.com/woocommerce/woocommerce-ios/assets/95003933/78d4605b-95e3-4ada-afa3-f0ed0a37644f)

The space just needs to be reduced to match the other half-sheets in the app.

Thanks!

**Mobile Environment**
- Device: iPhone 15 Pro
- iOS version: 17.2
- WooCommerce iOS version: 16.2.0.2

**Comment by itsmeichigo** [comment]
This can be fixed by applying the new design proposed here [p1701409134534599/1700008726.769739-slack-C0354HSNUJH]:


https://github.com/woocommerce/woocommerce-ios/assets/5533851/b259260d-9ecd-40c7-8941-1372db07256e

**Comment by itsmeichigo** [comment]
@joe-keenan With the changes made by @hafizrahman in #12273 do you think this issue can be closed yet?
