### ISSUE TITLE
Subscriptions: Hide "Shipping" option until one-time shipping feature is added.

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#11263]
We decide to hide the "Shipping" option until one-time shipping feature  is added, matching Android. (ref: p1700125686706349-slack-C03L1NF1EA3)

We will show the option again once #11178 is completed.

**Comment by selanthiraiyan** [comment]
Let us keep showing the "Shipping" section until we add the "one-time shipping" option.
