### ISSUE TITLE
Small UI glitch on big screen when generating product variations

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-ios#11317]
**Describe the bug**
Small UI glitch on big screen when generating product variations

**To Reproduce**
1. Add variable product
2. Add variable attributes and values
3. Click on "Generate variations"
4. See how the bottomsheet is resized and misplaced in the top left corner 

**Screenshots**

https://github.com/woocommerce/woocommerce-ios/assets/2663464/6b479c7d-ced8-49d3-8816-b2175f681419

**Mobile Environment**
Please include:
- Device: Ipad pro 11" 
- iOS version: iPadOS 16.1.1
- WooCommerce iOS version: `16.4`

**Comment by itsmeichigo** [comment]
Closed by #11695
