### ISSUE TITLE
Products: Improve the bottom sheet for product type selection

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#11361]
Currently, we have two separate bottom sheets when creating a new product if the user is eligible for product creation AI:

https://github.com/woocommerce/woocommerce-ios/assets/5533851/0ecc4d91-d4c6-4599-b3a9-c174b52a1139

We should enhance the experience by reuniting the options in one sheet with separators between product types:

https://github.com/woocommerce/woocommerce-ios/assets/5533851/35045074-af53-4a34-961d-043af0a322a1

Internal discussion: p1700008726769739-slack-C0354HSNUJH.

**Comment by hafizrahman** [comment]
Tasks: 
- [x] Show the manual product type creation options when "Add manually" is tapped https://github.com/woocommerce/woocommerce-ios/pull/11859
- [ ]  Redesign:  Use new heading "Create Product / select product type"), and split list of product type creation options into sub-lists (Standard, Subscription, Others). Also reduce space under "Add manually" option (see https://github.com/woocommerce/woocommerce-ios/issues/11211)
