### ISSUE TITLE
Spike: Can the Reviews tab be populated with all reviews?

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-ios#1139]
Now that the last tab in the app now only contains product review notifications, it seems confusing that we don't show _all_ product reviews. Can we use the API to populate this view, while also supporting populating it using notifications? Here are some points to consider:
 
- [ ] Populate the tab with the reviews API
- [ ] Somehow still understand which ones are active for notifications to properly send back the "has seen" event back to notifications.
- [ ] Continue to support showing the "unread" product reviews in this tab - the confusing point here would be that old product reviews the user has not seen will not be marked as unseen because they are no longer mentioned in the notifications response.

**Comment by AmandaRiu** [comment]
Related Android ticket: https://github.com/woocommerce/woocommerce-android/issues/1300

**Comment by mindgraffiti** [comment]
Ref. p99K0U-1wy-p2. 

Most of the answers are here, we just need a short outline of the implementation details for iOS.
