### ISSUE TITLE
[Product details] Option to change product to subscription type appears when Subscriptions extension not active

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#11459]
Even if my store doesn't have the Subscriptions extension installed or active, I see the option in product details to change the product to a subscription type:

<img src="https://private-user-images.githubusercontent.com/8658164/290522180-5ed9d910-f305-4f3d-8c3b-75d3da1fbeb9.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NTg0OTUsIm5iZiI6MTcwMjU1ODE5NSwicGF0aCI6Ii84NjU4MTY0LzI5MDUyMjE4MC01ZWQ5ZDkxMC1mMzA1LTRmM2QtOGMzYi03NWQzZGExZmJlYjkuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDEyNDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZmJmZmM0ZjUxYzNlNmYxMzUzMDc4NDQxYWE5NTkxNTNlZTg5Y2FmOGZlYzNjZWY1NDI3MDAyMTA0NWJkY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2PDtq1IwlpNddc7VPrThhMyJi_ANNAJUeK-rml2eazg" width="300px">

If I choose a subscription type there, it changes what I see in the form to the expected subscription fields. But if I try to save my changes, I get an error in the app logs and on screen:

> ⛔️ Error updating Product: unknown(error: Yosemite.AnyError(error: Dotcom Error: [rest_invalid_param] Invalid parameter(s): type))

<img src="https://private-user-images.githubusercontent.com/8658164/290522544-976ee6d7-fa61-4281-86c5-9a1bb5190f31.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NTg1MTIsIm5iZiI6MTcwMjU1ODIxMiwicGF0aCI6Ii84NjU4MTY0LzI5MDUyMjU0NC05NzZlZTZkNy1mYTYxLTQyODEtODZjNS05YTFiYjUxOTBmMzEuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTRUMTI1MDEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGNlYTExM2IzMDg3MTU5NTRhNThmOTIyM2E5MGUzNmM3ZDlmYzU0ZTU1Njk5MGEzZGM3OWRhYjc0YjliMjJlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0n_MBATg1KE2dLMNuwdC5-J3n0CoOzQWDSmBoGRCiu4" width="300px">

**Comment by itsmeichigo** [comment]
@rachelmcr I cannot see your screenshots in the description. Can you still reproduce this issue? I tried with a few stores without subscription extension but cannot see the option in the product creation sheet.

**Comment by rachelmcr** [comment]
Not sure why the screenshots are broken, but I confirmed the issue still exists in WCiOS 19.0.0.2 (TestFlight). Note that the option only appears when changing the product type in product details, not in the product creation sheet when you first start to create a new product.

Here are new screenshots:

New product (no issue)|Product details (subscription options shown)|Product details error
-|-|-
![IMG_3650](https://github.com/woocommerce/woocommerce-ios/assets/8658164/2d314bae-7ca3-4617-9651-f980a44b7344)|![IMG_3651](https://github.com/woocommerce/woocommerce-ios/assets/8658164/36d3af94-ad71-4b9c-9505-ae54a5b7a628)|![IMG_3652](https://github.com/woocommerce/woocommerce-ios/assets/8658164/facc3354-0d00-4e48-8f4e-693286633400)

Steps:

1. Select a store **without** the Subscriptions extension.
2. Create a new product with any product type.
3. In the product details, tap the "Product type" row.
4. Notice that the product types include "Simple subscription product" and "Variable subscription product" even though the store does not support those types.
5. Select either subscription product type and confirm the change.
6. Tap "Publish" to publish the product, and notice there is an error.
