### ISSUE TITLE
Blaze: Hide Product form promote button if there's active campaign

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#11562]
> I just realized that the Promote with Blaze button is still visible after creating a campaign successfully. We should hide that button

_Originally posted by @itsmeichigo in https://github.com/woocommerce/woocommerce-ios/pull/11552#pullrequestreview-1796838382_

**Comment by itsmeichigo** [comment]
@hafizrahman I see that you picked up this issue. Just wanna leave a note that you might need to wait until the API for campaign creation is done to confirm any fix. The reason is that we need a new campaign to be created to test that the button is hidden.

**Comment by pmusolino** [comment]
Android issue: https://github.com/woocommerce/woocommerce-android/issues/11756
