### ISSUE TITLE
Documentation: a "handbook" page for GitHub norms

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1158]
There are a lot of things that Woo iOS does differently compared to WPiOS. These GitHub behaviors and expectations need to be made explicit. 

- [ ] add a new page, Handbook.md (name it however seems best)

Some of the things we do on Woo:
- assign 1 or more reviewers to a PR
- add yourself as the assignee
- add any relevant labels
- add to the project board
- add the correct milestone
- only 1 reviewer is needed in order to merge a PR
- more than 1 reviewer can be added, especially when it doesn't matter who reviews that particular code
- merge all the commits of a PR into develop (WPiOS asks devs to Squash Commits, we do the opposite)
- a "comment" review means there are non-blocking changes to be made. Make your changes and then merge the PR, no second review necessary. GitHub may complain and you may have to use your Admin powers to override and merge. That's perfectly acceptable to us.
- nits are *always* optional. If you feel a change is truly necessary, do not mark it as a nit out of politeness.
- it's okay to have PRs that are dependent on each other and point to branches that are not develop. Sometimes features need this. We work in layers and they tend to stack on top of each other naturally.
- Hound polices our line length (160 characters or less), but we make exceptions for Localizations. Localizations cannot use the triple-quoted text that Swift is capable of, due to limitations with translation scripts. iirc, triple-quote text will break GlotPress. So we keep them all one line and ignore Hound.
- add any other insights you've found that should be here

**Comment by astralbodies** [comment]
Most of this is covered in the current documentation; closing!
