### ISSUE TITLE
Blaze campaign creation scrollable form

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#11587]
<img width="199" alt="image" src="https://github.com/woocommerce/woocommerce-ios/assets/5533851/ac49373e-43be-4f91-a12c-9a5270674367">

**Comment by selanthiraiyan** [comment]
@itsmeichigo  FYI, a design decision was made to have skeleton loading on this screen. mBhyoV7OPhFnOugxLy6SMS-fi-2307:50904#656514841
