### ISSUE TITLE
UI animation oddness when loading the IAP upgrade screen

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#11611]
I was unable to replicate this issue, opening issue for reference in case keeps coming up:

There's a case where the IAP plan upgrade screen shows some animation oddness, this seems to happen when it's initially presented and while is loading the plan information, once the load finishes then the issue is resolved:

https://github.com/woocommerce/woocommerce-ios/assets/3812076/de4279dd-065e-415d-b00d-91741de1d2e3

Reported on: p1702665864540549-slack-C025A8VV728
Tested on iPhone 14 Pro Max with iOS 17.2.1

```
- It feels like it takes quite a while to load in the text and pricing info
- While it's waiting to load in, the placeholders move up and down in a scrolling motion
- After the upgrade screen has loaded, the navigation bar elements still do the scrolling motion
```

**Comment by bozidarsevo** [comment]
I feel like I wound a cause of the glitch/problem, it is `.shimmering(active: isLoading)` modifier (in `OwnerUpgradesView.swift`). I will debug more and try to find the fix.
