### ISSUE TITLE
Improvements to Italian Localisation

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#1161]
There are some improvements and some fix to do in the Italian Localisation.
At the moment I discovered two cases to be fixed, but I suggest a complete check of the localization.

1) There is a bad translation on the Italian language: when I open a product from an order, the top left button on navigation bar show “Respinto” in Italian, but it’s a simple “Close” button, then the right term is “Chiudi”. Respinto means “Rejected” or “Failed”. I noticed that this string it’s used wrong everywhere inside the app.
![IMG_5089](https://user-images.githubusercontent.com/495617/62465093-6a68c180-b78e-11e9-935b-995a5f22eebc.jpg)

2) There are other strings that are not translated or bad translated (for example inside the order there is the Detail button, that is translated “Detagli” in Italian, but the correct word is “Dettagli”.
![IMG_5088](https://user-images.githubusercontent.com/495617/62465104-6e94df00-b78e-11e9-90fc-8b27202af8ca.jpg)

**Comment by mindgraffiti** [comment]
Ref. p77Llu-bLz-p2

**Comment by mindgraffiti** [comment]
@pmusolino Our translations are done via GlotPress. The WCiOS GlotPress project is [here](https://translate.wordpress.com/projects/woocommerce%2Fwoocommerce-ios/). [Italian translation here](https://translate.wordpress.com/projects/woocommerce%2Fwoocommerce-ios/it/default/). I think you should be able to make direct edits to translations there.

**Comment by pmusolino** [comment]
Hi @mindgraffiti! 
I checked all the Italian translation, and I sent new suggestions for some strings. 👍

**Comment by mindgraffiti** [comment]
Approved the new translations for both. Fix expected to appear in build 2.6

**Comment by pmusolino** [comment]
I confirm that this problem has been solved. Tested on v.3.2. It's ok!
