### ISSUE TITLE
Strings half localized

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#1164]
## I discovered two strings that are half localized, in two different languages at the same time. This problem affects all localisations.

1) I encountered on order detail a string that is half localized. `Payment of 80,00€ received via Bonifico bancario` it’s half in English and half in Italian.
2) Another string with the same problem it's inside notifications panel, on a new order. (see attachment screenshots).
The bug's always present, in any language.

## How to solve:
1) About the first case, I noticed that in the English Localizable.strings there are two sentences 
```
/* Payment of <currency symbol><payment total> received via (payment method title) */
"Payment of \(subject.totalValue) received via \(order.paymentMethodTitle)" = "Payment of \(subject.totalValue) received via \(order.paymentMethodTitle)";

/* Payment of <currency symbol><payment total> received via (payment method title) */
"Payment of \(totalValue) received via \(order.paymentMethodTitle)" = "Payment of \(totalValue) received via \(order.paymentMethodTitle)";
```

But in other Localizable files (any language) the first sentence it's not present.

2) The second case is managed from the server that sends the content of the push notification, but it's not localized.

## Screenshots:
![IMG_5090](https://user-images.githubusercontent.com/495617/62532828-9abf6700-b845-11e9-884c-48158b0d13b2.jpg)
![IMG_5091](https://user-images.githubusercontent.com/495617/62532834-9d21c100-b845-11e9-86d1-afdcce5e2661.jpg)

## Mobile Environment
- Device: Any iOS device (also simulator)
- iOS version: All iOS versions
- WooCommerce iOS version: 2.3

**Comment by mindgraffiti** [comment]
@jtreanor could the first case be a problem with our localization script? The payment received string hasn't been modified for quite a while. (Ignore the second one, it's a server-side issue)

**Comment by mindgraffiti** [comment]
Nevermind @jtreanor, I figured it out. Looks like I used string interpolation somewhere in the code for the first problem listed above.

**Comment by jtreanor** [comment]
Ah, that makes sense. Let me know if there is anything else I can help with here @mindgraffiti.

**Comment by mindgraffiti** [comment]
**Issue 1:** find the localized string in the code (probably in OrderDetailsViewModel) and ensure it's not using string interpolation. Use the `String.localizeStringWithFormat()` method instead. 

Ref. p77Llu-bLz-p2

**Issue 2:** afaik, the server-side push notifications have never been localized. Part of completing this ticket should include finding where to file "Localization missing in push notifications" bug.

**Comment by mindgraffiti** [comment]
*Issue 1* should be solved during the implementation of #1090

**Comment by mindgraffiti** [comment]
**Issue 2:** The API request is: 

```
https://public-api.wordpress.com/rest/v1.1/notifications?fields=id%2Cnote_hash&number=100
```

If it is localized, I bet it's based on the user's WordPress settings.

**Comment by mindgraffiti** [comment]
Ref. p99K0U-1Fc-p2
