### ISSUE TITLE
[Tablet Orders] Add max width to order details

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#11677]
As per designs, we will add a max-width limit to the Order Details view when shown in a split view with the order list.

6kkCwI9VOEYcidp6UT5bln-fi-192%3A26916

![Image](https://github.com/woocommerce/woocommerce-ios/assets/2472348/a6eacc6a-29e8-4e54-9b51-0defa6686ca8)

**Comment by iamgabrielma** [comment]
Adding discussion link for reference: p1703737115125139-slack-C0354HSNUJH

**Comment by jaclync** [comment]
Today I saw this behavior in the latest trunk and thought it was a bug at first 😅 it reminded me of how some apps don't have the tablet version and just load the app in phone width with blank margins. I understand the reasoning now from the Slack reference, just wonder if Shopify / Square etc. that have lots of POS users do this maybe with some UX research/feedback.
