### ISSUE TITLE
[Tablet Orders] Ensure an order is selected when rotation brings order details into view for the first time

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#11675]
In horizontally-regular size classes (mostly iPad), we automatically select the first order in the order list when shown in the UISplitViewController.

However, if the order list is initially shown in a horizontally compact mode, which is then changes from to horizontally regular before an order is selected, we don't auto-select the first order, and show an empty state in the details view instead.

It would be better if we select the first order in the list in this scenario.

To reproduce:

1. Set the `splitViewInOrdersTab` feature flag to `true`
2. Launch the app on an iPad, or Pro Max/Plus sized iPhone.
3. If on iPad, use the OS multitasking control (`...`) to put the app in a split view where it has a horizontally compact size class. Usually this is 50% of the screen or less, but that might not hold on a 12.9" iPad. 
4. On a large iPhone, have the phone in portrait.
5. Open the `Orders` tab
6. Rotate the phone, or expand the iPad multitasking view to a regular size class
7. Observe that the details view is shown, but shows the empty state instead of the first order in the list.

We can probably fix this with a call to `OrderListViewController.checkSelectedItem()` in some delegate method...

**Comment by jaclync** [comment]
In trunk, I noticed that on iPhone compact size (iOS 17.0 iPhone 15 simulator portrait mode), the first order is selected by default when the `splitViewInOrdersTab` feature flag is on. The order list is shown when the feature flag is off. Is this expected for compact horizontal size class?

**Comment by joshheald** [comment]
@jaclync No, that's not expected in compact. 

I thought I fixed that already, so I'll check why it's still doing it.

**Comment by joshheald** [comment]
@jaclync I can't repro this on `trunk`. 

Here's what I've tried:
iOS 16.7.2 on my iPhone 13 Pro device – portrait and landscape
iOS 17.2.1 on my iPhone 15 Pro Max device – portrait only
iOS 17.0 on an iPhone 15 simulator – portrait and landscape

The Order List is shown in all cases for me.

Are you sure you were using latest `trunk`? It was only fixed last week, so if you were on an old branch, perhaps that's the reason...

Video in which my wife wishes for a snow day...

https://github.com/woocommerce/woocommerce-ios/assets/2472348/023550a2-d134-472a-b449-e8b765906142

**Comment by jaclync** [comment]
> Are you sure you were using latest `trunk`? It was only fixed last week, so if you were on an old branch, perhaps that's the reason...

Yup, I was on the latest trunk with commits from yesterday. Did you have the `splitViewInOrdersTab` feature flag enabled? It works fine with the feature flag disabled as the default in debug and release builds. I'm having trouble building on a physical phone now (attaching app to the device forever), will share the result when I'm able to. I'm on Xcode 15.0.1 if that matters.

> Video in which my wife wishes for a snow day...

Haha I thought snow is usually not preferred (except for snow sports and during the holidays), though I haven't lived somewhere that snows 😆

**Comment by jaclync** [comment]
Screencast on iPhone 15 iOS 17.0 simulator from Xcode 15.0.1:


https://github.com/woocommerce/woocommerce-ios/assets/1945542/9ad8d9ad-c78d-4be2-a0b9-708d570e9dd0

**Comment by joshheald** [comment]
> Yup, I was on the latest trunk with commits from yesterday. Did you have the `splitViewInOrdersTab` feature flag enabled?

Yes, definitely had the flag enabled. 

I was using Xcode 15.1 because that's what's on CI. I've tried Xcode 15 just in case too, but no difference. I don't have 15.0.1, but I'm installing it now in case it's just in builds from that point release.

I've checked a bunch of times, and had one possible sighting of it... but I've tried about 30 times now and I think I just brushed the trackpad at the wrong time – it happened a few seconds after the Order List loaded, unlike in your video.

Does it happen for all stores with your simulator, @jaclync?

@iamgabrielma @bozidarsevo please could you see whether you can reproduce this?

This is the only slightly suspect code I've found:
https://github.com/woocommerce/woocommerce-ios/blob/3236bdd7a2842004c46e782a5624fbfddca04a4a/WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift#L270

```
viewModel.snapshot.sink { [weak self] snapshot in
            guard let self = self else { return }
            self.dataSource.apply(snapshot)

            if self.isSplitViewInOrdersTabEnabled, self.splitViewController?.isCollapsed == false {
                self.checkSelectedItem()
            }

        }.store(in: &cancellables)
```

The view model could perhaps call that block before `splitViewController` knows whether it's collapsed or not (i.e. before the tab is shown.) I couldn't make that happen, and I checked the unwrapped `nil == false` logic, which is sound.

> Haha I thought snow is usually not preferred (except for snow sports and during the holidays), though I haven't lived somewhere that snows 😆

She's a teacher 😅

**Comment by bozidarsevo** [comment]
> you can reproduce this?

I am trying to follow steps to reproduce it but I am not sure if I am doing it correctly:

![Simulator Screen Recording - iPad Pro (11-inch) (4th generation) - 2024-01-16 at 16 16 03](https://github.com/woocommerce/woocommerce-ios/assets/6242034/346d438c-3087-4fb2-88a4-1c140d8a9ce0)

**Comment by joshheald** [comment]
> I am trying to follow steps to reproduce it but I am not sure if I am doing it correctly:

For clarity: I meant "can you repro the issue that @jaclync's found on iPhone in portrait", not whether you can repro the parent issue. A bit confusing for us to discuss two bugs on the same ticket, though they are related. 

Which were you aiming for here?

Your screen recording shows correct behaviour if you'd previously opened the Orders tab (and therefore selected an order.) If you _hadn't_ opened the orders tab, it should show the order _list_ when you shrink the app.

To repro the parent ticket issue: 
1. Launch the app in slideover or a small multi-tasking Split View
2. Open the Orders tab
3. Make the app full screen.

You'll see the orders list with the empty state next to it, when it should select the first order in the list.

**Comment by jaclync** [comment]
Sorry for discussing a side issue and causing some confusion, I will open a separate issue shortly but posting here to keep the discussion in one place.

> Does it happen for all stores with your simulator, @jaclync?

Yes, all stores that have at least one order.

Just tested more with Xcode 15.0.1/Xcode 15.1/Xcode 15.2, results:
- iPhone 13 Pro device, iOS 17.1: issue persists
- iPhone 15 simulator, iOS 17.0.1: issue persists
- iPhone 15 simulator, iOS 17.2: ✅ 

The code you shared was helpful. Upon setting a breakpoint on `OrderListViewController.checkSelectedItem` in the devices that I can reproduce, the problematic caller is from `viewWillAppear`:

https://github.com/woocommerce/woocommerce-ios/blob/3236bdd7a2842004c46e782a5624fbfddca04a4a/WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift#L202-L207

`UISplitViewController.isCollapsed` is `false` in `viewWillAppear` in the devices that I can repro the issue. It's possible that in certain iOS versions, `UISplitViewController.isCollapsed` isn't ready in `viewWillAppear`. There's a [similar topic in SO](https://stackoverflow.com/questions/44336916/why-sometimes-iscollapsed-of-uisplitviewcontroller-is-false-on-iphone-portrait), where the `isCollapsed` value is only correct after the first `viewDidLayoutSubviews`. However, it's odd that @joshheald cannot reproduce on iOS 17.0 iPhone 15 simulator.

**Comment by jaclync** [comment]
▶️  Moving the discussion about the side issue to https://github.com/woocommerce/woocommerce-ios/issues/11709
