### ISSUE TITLE
Orders tab: order is pre-selected when switching to the orders tab for the first time in some iPhone devices on iOS 17.0/17.1

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#11709]
**Describe the bug**

In some iPhone devices on iOS 17.0/17.1 where split view is not available, order details are shown instead of the order list.

**To Reproduce**

- In code, enable the `splitViewInOrdersTab` feature flag in `DefaultFeatureFlagService` (returning `true`)
- Launch the app in iOS 17.0.1 or 17.1 simulator/device
- Switch to a store with at least one order, if needed
- Go to the orders tab --> notice that order details are shown instead of the order list

**Screenshots**

https://github.com/woocommerce/woocommerce-ios/assets/1945542/9ad8d9ad-c78d-4be2-a0b9-708d570e9dd0

**Expected behavior**

The order list should be shown when the split view is unavailable in the UI.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13 pro 
- iOS version: iOS 17.1
- WooCommerce iOS version: 16.9

(also iPhone 15 iOS 17.0.1 simulator)

**Comment by jaclync** [comment]
Hi @iamgabrielma @bozidarsevo, can you try if you can reproduce this issue if you get a chance?

**Comment by jaclync** [comment]
If anyone can reproduce this, here's the PR: https://github.com/woocommerce/woocommerce-ios/pull/11710

**Comment by iamgabrielma** [comment]
I wasn't able to reproduce this either 😞 (Xcode 15.0). Tried with:
- iPhone 13 - iOS 17.0
- iPhone 14 - iOS 16.4
- iPhone 15 - iOS 17.0

**Comment by jaclync** [comment]
If I'm the only one who can reproduce this issue, it might be something from my machine 😅 If @bozidarsevo gets a chance to test the repro steps and cannot repro this, then I'm leaning towards to closing this. I'll also check if I can reproduce this from an installable build on my iOS 17.1 device.

**Comment by joshheald** [comment]
> If @bozidarsevo gets a chance to test the repro steps and cannot repro this, then I'm leaning towards to closing this.

@jaclync I disagree... I think there's something to it, and the fix in #11710 will make it less likely to happen to users. It's the kind of issue people will find annoying, but maybe not annoying enough to actually tell us about, so I'd really like to minimise the chance of it happening.

Since your PR can also be used to fix #11675, I think we should go for it (with the suggestions I made.)
