### ISSUE TITLE
Orders tab: placeholder cells are plain without animated ghost content - a potential regression

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#11701]
**Describe the bug**

In the orders tab, when it's in the loading state, the placeholder cells don't have the animated ghost content anymore like in production.
After testing commits in trunk, it seems to happen after https://github.com/woocommerce/woocommerce-ios/pull/11621 regardless of the `splitViewInOrdersTab` feature flag value.

**To Reproduce**
- Launch the app
- Go to the orders tab --> notice that in the loading state, the cells don't animate with the ghost content

**Screenshots**

production | trunk
-- | --
<img src="https://github.com/woocommerce/woocommerce-ios/assets/1945542/c5311019-5a32-4294-8fe3-fbee4148047d" width="300" /> | <img src="https://github.com/woocommerce/woocommerce-ios/assets/1945542/961f8733-3676-45b9-ab38-883853aadde3" width="300" />
<img src="https://github.com/woocommerce/woocommerce-ios/assets/1945542/a8a4df5a-c679-4a35-bda8-365b4a5bb0f2" width="300" /> | <img src="https://github.com/woocommerce/woocommerce-ios/assets/1945542/08310501-e35d-427d-a7bb-cd7bca0d7457" width="300" />

https://github.com/woocommerce/woocommerce-ios/assets/1945542/cf3d4984-eece-4ada-afef-3459fb17ccc9

**Expected behavior**

In the loading state, the cells should animate with ghost content.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: iOS 17
- WooCommerce iOS version: 16.9

**Comment by jaclync** [comment]
cc @iamgabrielma @joshheald a potential regression in 16.9 but I don't think it's blocking the release. Feel free to add this to the tablet support project and Corvid can help look into this too.

**Comment by joshheald** [comment]
Good spot. I suspect it'll be the timing of setting the cell configuration, which resets the views, IIRC.

Adding to M2

**Comment by bozidarsevo** [comment]
I don't know if it is connected but I am looking at: `(cell as? GhostableView)?.ghostAnimationWillStart()` in `GhostTableViewHandler.swift` and I do not see any class conforming to `GhostableView`, is that something from before or our cells need to conform to it?

**Comment by bozidarsevo** [comment]
Could it be that `enumerateGhostableLeafViews` is providing wrong leaf views and because of that it appears that the whole cell is ghost?

**Comment by joshheald** [comment]
Could be... I don't know how that all works.

One change which _might_ be to blame is that the table view cells nested a little deeper with the change to UISplitViewController. We wrapped them in a new TabContainerController, and then there's the SplitViewController, and a wrapper for that which co-ordinates the two views. Perhaps it only traverses the view hierarchy a certain number of layers?

Perhaps you could rule that out by checking whether they ghost correctly when the feature flag is set to `false`.
