### ISSUE TITLE
[Tablet Orders] Hide `+` and `scan` buttons for add product on the Order Summary when shown in a side-by-side view.

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#11747]
Figma: 6kkCwI9VOEYcidp6UT5bln-fi-192_25891

<img width="217" alt="Screenshot 2024-01-22 at 15 39 49" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/4c031fd3-7e76-48aa-96bb-a84afc92cce9">

**Comment by joshheald** [comment]
The add button gets hidden already. 

The scan button needs to be "moved" to the product selector header... but it would probably be easier to hide the scan button on the order summary, then show one on the product selector header, based on the `presentationState` environment key or some other context for how they're being displayed.

Remember that this needs to update for different size classes, not device types, so sometimes they still need to be shown on iPad (I'm renaming the issue to avoid confusion.)
