### ISSUE TITLE
Login: check for `isJetpackActive` && `isJetpackConnected`

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1177]
**Describe the bug**
Ref. p99K0U-1yp-p2. In addition to our basic check `hasJetpack`, we need to be more stringent and check if the site has the Jetpack plugin activated and that it has successfully connected. 

**To Reproduce**
1. Have a site where Jetpack has been added, but isn't currently active. Alternatively: disable Jetpack on an active test site.
2. Test the login flow. Even though Jetpack is not activated, it will allow logging in.
3. Activate the Jetpack plugin, but disconnect it from the site. Go to Jetpack > Dashboard > Connections box, and click the "Manage site connection" link. Disconnect Jetpack by clicking the "Disconnect" button. 
4. The login flow allows the user to log in.

**Screenshots**

**How to disconnect Jetpack, a visual guide:**
![disconnect-jetpack](https://user-images.githubusercontent.com/1062444/62951633-e4f99880-bdaf-11e9-8006-310203f56bd0.png)

**Expected behavior**
A user should only be allowed to log in when all three cases are true: `hasJetpack && isJetpackConnected && isJetpackActive`

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: any 
- WooCommerce iOS version: 2.5

**Comment by shiki** [comment]
Looks like we already do this here: https://github.com/woocommerce/woocommerce-ios/blob/9d37fbf1f679933d5e81917acc3171f6276f8bef/WooCommerce/Classes/Extensions/WordPressComSiteInfo%2BWoo.swift#L5-L11
