### ISSUE TITLE
[Order List] Scan barcode button is only announced as "Button" in voiceover

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#11792]

**Comment by bozidarsevo** [comment]
@joshheald is "Scan product barcode" enough/good?
I see that on product screen the button has this setup:
```
button.accessibilityLabel = NSLocalizedString("Scan products", comment: "Scan Products")
button.accessibilityHint = NSLocalizedString(
            "Scans barcodes that are associated with a product SKU for stock management.",
            comment: "VoiceOver accessibility hint, informing the user the button can be used to scan products."
        )
```

**Comment by joshheald** [comment]
> @joshheald is "Scan product barcode" enough/good? I see that on product screen the button has this setup:
> 
> ```
> button.accessibilityLabel = NSLocalizedString("Scan products", comment: "Scan Products")
> button.accessibilityHint = NSLocalizedString(
>             "Scans barcodes that are associated with a product SKU for stock management.",
>             comment: "VoiceOver accessibility hint, informing the user the button can be used to scan products."
>         )
> ```

"Scan product" or "Scan barcode" would be fine. With A11y labels and hints, it's important to be concise, similar to labels/text buttons in a UI.

The `hint` from the Product screen looks too long to me. If it's needed (it probably isn't), it could just be "Used for stock management"
