### ISSUE TITLE
[Tablet Orders] Order list column shows order details

### ISSUE THREAD

**Issue by lmischner** [woocommerce/woocommerce-ios#11794]
**Describe the bug**
In the new side-by-side layout on tablets, I can get into a state where both columns (usually taken up by orders list on one side, order details on the other) both show order details.

**To Reproduce**
1. Start splitview with the Woo app open to the orders tab
2. Either by changing real estate the Woo app gets or by being in portrait orientation (or both), get the Woo app to a state where it only shows order details
3. Use the arrow buttons in the header to navigate to another order
4. Close split view
5. Note behavior

**Screenshots**

https://github.com/woocommerce/woocommerce-ios/assets/103850310/61e2a04d-f946-469c-b6e2-db7646e74d56

**Expected behavior**
The orders list should not be over taken by roder details

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPad Air
- iOS version: iPadOS 17.1
- WooCommerce iOS version: built from PR 11731

**Comment by joshheald** [comment]
The first time you do this, you can still tap the back button in the LHS pane to go back to the list... but it's also possible (if you tap the up/down arrows in the LHS pane instead) to lose the Order List entirely.

**Comment by bozidarsevo** [comment]
~~This is connected to https://github.com/woocommerce/woocommerce-ios/issues/11752 and should be fixed with https://github.com/woocommerce/woocommerce-ios/pull/11753. I will double check and test 👍~~

**Comment by iamgabrielma** [comment]
The issue seems to be with the usage of `replaceTopViewController` in the [OrderDetailViewController.loadOrder(with index: Int)](https://github.com/woocommerce/woocommerce-ios/blob/trunk/WooCommerce/Classes/ViewRelated/Orders/Order%20Details/OrderDetailsViewController.swift#L203C10-L203C36) function. This replaces the top view controller of the view controllers stack, which happens to be the `WooCommerce.WooTabNavigationController` when the split view is collapsed. We need to target the specific navigation controller we'll be pushing the view to in this case.

I did a quick experiment to test this and seems to fix the issue, but needs further testing:

```diff
    func loadOrder(with index: Int) {
        let splitViewNavigationController = splitViewController?.viewControllers.first as? UINavigationController
        let usingNavigationController = isSplitViewInOrdersTabEnabled ? splitViewNavigationController : navigationController

        guard let usingNavigationController = usingNavigationController else {
            return
        }

        let orderDetailsViewController = OrderDetailsViewController(viewModels: viewModels, currentIndex: index)
-      usingNavigationController.replaceTopViewController(with: orderDetailsViewController, animated: false) 
+        guard let splitViewController = splitViewController else {
+           return
+       }
+       if splitViewController.isCollapsed {
+            navigationController?.replaceTopViewController(with: orderDetailsViewController, animated: false)
+        } else {
+            usingNavigationController.replaceTopViewController(with: orderDetailsViewController, animated: false)
+        }
    }
```

![Simulator Screen Recording - iPad Pro (12 9-inch) (6th generation) - 2024-01-26 at 11 36 56](https://github.com/woocommerce/woocommerce-ios/assets/3812076/445350dc-c623-4f15-a6d6-936ec9cdc910)

**Comment by jaclync** [comment]
I came to the same conclusion as @iamgabrielma for this issue, where `replaceTopViewController` is on the order list's navigation controller and not the secondary view's navigation controller. Updating https://github.com/woocommerce/woocommerce-ios/blob/98a17f93778443ec01ce53895008656de438d9a0/WooCommerce/Classes/ViewRelated/Orders/Order%20Details/OrderDetailsViewController.swift#L204 to

```swift
let splitViewNavigationController = splitViewController?.viewController(for: .secondary) as? UINavigationController
```
fixes it. But as in Gabriel's screencast above, the subsequent order details have a large title in the navigation bar.

I'm looking into pulling the order details presentation logic from `OrderDetailsViewController`, I think it's cleaner decoupling split view logic in individual view controllers and this way we can sync the selected order/index path states in the order list.
