### ISSUE TITLE
Stats v4 API: stale data issue workaround

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1183]
As of writing, the revenue stats data from v4 API are cached for an uncertain amount of time if all the parameters are the same. To get around this issue on the client side, we can set a random value to the `per_page` param that is originally used for the maximum number of intervals (but not needed if `after` and `before` params are set correctly).

There is a chance, that the random number stays the same, but the probability should be low when the random param is the same for multiple times. If this proves to be an issue, we could update to a more robust approach like remembering the last random param value and incrementing each time. For now, let's use a simple approach and hopefully this issue will be fixed soon.

Thanks to Android for this workaround!

**Comment by jaclync** [comment]
reopening this issue to remove the hack

**Comment by jaclync** [comment]
this issue was fixed in WC Admin 0.20.0, but the adoption of 0.20.0+ is still around 5%. Let's revisit the data in a month or so. Keeping this issue in the milestone so that it doesn't get lost

**Comment by jaclync** [comment]
checked the data today, and the number of stores 0.20.0+ is about 35% now.

**Comment by shiki** [comment]
Jaclyn ran another query today and it looks more than 58.13% stores have 0.20.0+ now.

**Comment by joshbetz** [comment]
> this issue was fixed in WC Admin 0.20.0

@jaclync Am I understanding correctly that this is fixed on the API side?

**Comment by jaclync** [comment]
> Am I understanding correctly that this is fixed on the API side?

Yup! Here's the reference p99K0U-1BO-p2#comment-3865 and WC Admin has merged to core since then.

We can probably test removing the `per_page` param and check if the order stats are working correctly after placing some orders, then close this issue. I'll do this if I have some spare time this sprint. The upcoming Home Screen project still uses this endpoint.

**Comment by astralbodies** [comment]
@jaclync Now that the Home Screen Update project has mostly shipped, is this relevant any longer?

**Comment by jaclync** [comment]
The workaround from https://github.com/woocommerce/woocommerce-ios/pull/1184 is still in the repo. I just checked the data and tested without the workaround that shouldn't be needed since 0.20.0 about 2 years ago:

- Around 6.4% of the stores still use WC Admin version lower than 0.20.0 as of Jan 2022
- WC Admin was included in core since [WC 4.0](https://developer.woocommerce.com/2020/03/10/woocommerce-4-0-is-here/)
- The stats are updated as in WC Admin in core without the workaround

Given the above, I'm going to open a PR to remove the workaround 🙂
