### ISSUE TITLE
Collect payment button brings you to order details instead of order collection options

### ISSUE THREAD

**Issue by lmischner** [woocommerce/woocommerce-ios#11854]
**Describe the bug**
New with Woo 17.1, if I tap "collect payment" for an order, instead of being brought to the payment options screen, I'm brought to order details where I have to tap "collect payment" again.

**To Reproduce**
1. In an order, tap collect payment
2. Note behavior

**Screenshots**

https://github.com/woocommerce/woocommerce-ios/assets/103850310/0a20ae09-b5af-4a2a-8662-f9ab5fedf45e

**Expected behavior**
Tapping "collect payment" should bring hte user to payment options (Cash, card reader, etc.)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 15 pro
- iOS version: 17.2.1
- WooCommerce iOS version: 17.1 (I could NOT reproduce on 17.0 versions)

**Comment by joshheald** [comment]
Fixed in #11864
