### ISSUE TITLE
[Tablet Orders] Collect Payment from Order Creation doesn't work in 17.1 beta

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#11863]
## Repro

1. Launch the app
2. Go to the Orders tab
3. Tap `+`
4. Add a product
5. Tap `Collect Payment`

### Expected result
The Payment Method screen should be shown over the Order Details.

### Actual result
Observe that the Order Details screen is shown

**Comment by malinajirka** [comment]
Looks like a duplicate of https://github.com/woocommerce/woocommerce-ios/issues/11854. I've updated the PR to close both issues.

**Comment by joshheald** [comment]
Fixed in #11864
