### ISSUE TITLE
[Tablet Orders] Sync removal for variations

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#11932]
From: https://github.com/woocommerce/woocommerce-ios/pull/11917#issuecomment-1931232443

>  If we delete variations while the "variations view" is open, selections are not updated, which may cause the order to get out of sync as we keep adding/removing products.

![Simulator Screen Recording - iPad Pro (12 9-inch) (6th generation) - 2024-02-07 at 10 30 39](https://github.com/woocommerce/woocommerce-ios/assets/3812076/64e666ca-f517-4033-a038-e645c5b953a9)

**Comment by joshheald** [comment]
Sorry! I realised this after making the pr then forgot to fix it while I did other stuff.

I was planning to do it the same way: expose a `removeSelection` function on the product variation VM, then call it with the variation ID when the remove button is tapped.
