### ISSUE TITLE
iOS 13: Reviews > review cell selected > stars label has a white background 

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1196]
**Describe the bug**
The star ratings label has a white background instead of a clear background.

**To Reproduce**
1. Go to Reviews tab
2. Click on any review cell
3. While in selected state, note the different label backgrounds

**Screenshots**
<img src="https://user-images.githubusercontent.com/1062444/63300198-47193880-c29d-11e9-8a45-e86d5dbfefb3.png" width="350" />

**Expected behavior**
The stars rating label should have a clear background color.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: iOS 13.0
- WooCommerce iOS version: 2.6 // latest from develop

**Comment by pmusolino** [comment]
It seems solved in develop.

Device: simulator
iOS version: iOS 13.1

![Simulator Screen Shot - iPhone 11 Pro - 2019-10-30 at 12 44 53](https://user-images.githubusercontent.com/495617/67855743-50cbe180-fb13-11e9-893d-ae8bdbcf0536.png)
