### ISSUE TITLE
[Stats: Custom Range] API integration to get visitor stats with custom range

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#11972]

**Comment by selanthiraiyan** [comment]
Unassigning as I am focusing on Blaze tasks for now.

**Comment by itsmeichigo** [comment]
I don't think we need to add any new implementation as the existing code works already with a defined time range.

**Comment by selanthiraiyan** [comment]
Thanks, @itsmeichigo. I will close this issue.

**Comment by selanthiraiyan** [comment]
@hafizrahman Just noticed that you are assigned to this issue. Please feel free to reopen if you see the need. Thank you!

**Comment by hafizrahman** [comment]
Ah right, this should've been closed last week after the Slack discussion with Huong.
