### ISSUE TITLE
Products tab: swiping the product cell deselects the cell

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#11987]
This issue is based on the changes in https://github.com/woocommerce/woocommerce-ios/pull/11913.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by bozidarsevo** [comment]
This looks like it is not happening anymore?
