### ISSUE TITLE
Blaze: Upload campaign image

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#11984]
We need to upload the Blaze campaign image before submitting a create campaign request. 

- We can upload the image right before submitting the campaign.
- Regarding errors, I think we can use the same error screen pattern that we use for showing Blaze campaign creation errors. We can change the error message.
- We can retry one time before showing an error if the image upload fails, as the media uploads could fail often.

Tasks
- [x] Media Action to retrieve Media using product image's ID #12001
- [ ] Upload images and handle error #12006

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
