### ISSUE TITLE
Blaze: Set target URL and URL params

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#11986]
We have to set the `targetURL` and `urlParams` for the Blaze campaign [here](https://github.com/woocommerce/woocommerce-ios/blob/5939b691f5de27323e3686f3c7c79091110cbb23/WooCommerce/Classes/ViewRelated/Blaze/CampaignCreation/BlazeCampaignCreationFormViewModel.swift#L194-L195).

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
