### ISSUE TITLE
[Better Errors] Add Orders Error Tracking

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#11988]
Name | Properties | When
---- | ---- | ----
*_orders_list_automatic_timeout_retry |   | When the app automatically retries an order timeout request
*_orders_list_top_banner_troubleshoot_tapped |   | When the user taps the troubleshoot button from the top banner
*_connectivity_tool_request_response | success: (true/false) <br/> type:(internet/wp_com/site/jetpack_tunnel) <br/> time_taken | when the connectivity tool finishes loading a request
*_connectivity_tool_read_more_tapped |   | When the user taps the read more button from a connectivity tool card
*_connectivity_tool_contact_support_tapped |   | When the user taps the contact support button from the connectivity tool

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
