### ISSUE TITLE
[Better Errors] Add Site Credential Tracking

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#11989]
Name | Properties | When
---- | ---- | ----
*_login_site_credentials_invalid_login_page_detected |   | When the app detects that there is an invalid login page and can't log in natively
*_login_site_credentials_app_password_explanation_dismissed |   | When the user chooses to tap back on the app passwords explanation screen
*_login_site_credentials_app_password_explanation_contact_support_tapped |   | When the user chooses to contact support on the app passwords explanation screen
*_login_site_credentials_app_password_explanation_continue_button_tapped |   | When the user chooses to continue to log in with app passwords on the app password explanation screen.
*_login_site_credentials_app_password_login_exit_confirmation |   | When the user tries to exit the app password login page without approving the app password first
*_login_site_credentials_app_password_login_dismissed |   | When the user exists the app passwords login page after confirmation

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
