### ISSUE TITLE
"Custom range" tab graph

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#11980]
In #11975, the `.custom` enum case is added on `StatsTimeRangeV4`. Adding this enum case required multiple changes in different places. Most of the changes revolve adding temporary changes to unblock development.

We still need to check and update the todo items listed in that PR as needed, to ensure that the graph is displayed correctly depending on the selected date range.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
