### ISSUE TITLE
[Better Errors] Connectivity tool suggestions & resolution

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#11995]
## NOTE Define error messages and share them with the other platform

----

After the connectivity tool has finished running let's offer some suggestions to the user so they can continue their trouble shoot journey.

## No Internet connection

- [ ] Tell them to check they have an active internet connection

## Can't reach wpcom servers 

- [ ] Show some sort of internal error message
- [ ] Show contact support button

## Can't reach direct site

- [ ] Tell them to contact their host

## Can't reach the site via the jetpack tunnel

- [ ] Offer jetpack troubleshoot guide
- [ ] Tell them to contact their host

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
