### ISSUE TITLE
[Better Errors] Connectivity Tool Mock Up

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#11993]
- Experiment with a UI that serves as a connectivity tool where we will fire requests to different servers to help the users diagnose connectivity problems

- Add a place to add suggestions depending on the results of the requests.
- 
<img width="420" alt="Screenshot 2024-02-17 at 6 05 55 PM" src="https://github.com/woocommerce/woocommerce-ios/assets/562080/724c33dd-0c43-4f65-91c4-3cb42e5a5fcd">

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
