### ISSUE TITLE
[Better Errors] App Passwords Explanation Mock Up

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#11996]
We need to come up with a UI/UX to explain.

- [ ] Why we couldn't log in to your site
- [ ] How to approve application passwords
- [ ] Buttons to contact support and to continue with the app password login

![Image](https://github.com/woocommerce/woocommerce-ios/assets/562080/3c13fdfa-df5d-4604-b76a-5e05ce95f92d)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
