### ISSUE TITLE
[Better Errors] Segment Order list timeout errors

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#11990]
When loading the orders, the apps do not differentiate timeout errors from other types of errors.

# Tasks

- [ ] Add the necessary code to differentiate timeout errors to be able to act on them on the UI Layer later.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
