### ISSUE TITLE
[Better Errors] Detect login error and redirect to app password explanations

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#11999]
## Tasks

When logging into a self-hosted site.

- [ ] Detect when an error has happened and redirect the user automatically to the app password explanation screen.

### Identified errors

- 4xx would need its proper error message, as it means that the user customized their login page.

- 200, here we need to perform some additional checks, we need to check for the presence of a div with the id [login_error](https://href.li/?https://github.com/WordPress/WordPress/blob/34662ac6d6bd2646b24adddb3959525e24fdbb6f/wp-login.php#L253) in the received HTML:

    - If it’s there, then this means that it’s probably an authentication issue, we can even present the message we got as the error directly without putting our own, which would be clearer to our users.

    - If it’s not, then we can’t really confirm that it’s an authentication issue, so we should have a meaningful error message to let the user know that we can’t support their website now, and that we are working on it.

### Generic Errors

- [ ] Confirm which generic errors we track, and come up with a general error message.

# NOTE: Share strings with the other platforms

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
