### ISSUE TITLE
[Better Errors] Connectivity Tool logic

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#11994]
The connectivity tool should be able to measure

- [ ] Internet connectivity
- [ ] Reaching WP Servers
- [ ] Reaching self-hosted site (if available)
- [ ] Reaching the site via jetpack tunnel (if available)

Additionally:

- [ ] Requests responses should be logged to app logs (times, error codes, etc)

---

**More Details coming soon**

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
