### ISSUE TITLE
[Better Errors] Show error when leaving app password approval flow

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#12000]
## Tasks

- [ ] Detect when a user wants to leave the app password login web page before approving app passwords and ask for confirmation about it.

# Note: Define strings and share it with the other platform

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
