### ISSUE TITLE
Finishing bulk update deselects all cells but detail stays open

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#12002]
![Image](https://github.com/woocommerce/woocommerce-ios/assets/6242034/41f4f61d-715c-4c0f-bc24-ceefb3e4a297)

Do we want to keep track of previously selected product and select it back after bulk update is done, or should we remove the detail screen?

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
