### ISSUE TITLE
Custom range API call integration: make sure sync (when tab created), re-sync (when tab is switched to), and pull-to-refresh fetch the correct data

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#12014]
To follow the UI PR on https://github.com/woocommerce/woocommerce-ios/pull/11977:

There are three main ways the custom range stats data is grabbed via API:

1. During initial tab creation `createCustomRangeTab()`.
2. During switching from a different tab, into the Custom Range tab. This is handled `observeSelectedTimeRangeIndex()`. Currently, the API call here returns error.
3. During pull-to-refresh.

We need to check and ensure everything works correctly here.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by hafizrahman** [comment]
This is already working correctly for three cases in my check today. The various PRs we did in-between likely fixed it.
