### ISSUE TITLE
[Tablet Orders] Load product selector configuration based on size class

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12012]
The current `OrderFormPresentationWrapper` only checks for feature flag when deciding which view we should render: Either the `AdaptiveModalContainer` if the feature flag is enabled, or the `OrderForm` if it's disabled

If the `AdaptiveModalContainer` is rendered, we always pass in the product selector configuration for split views, which will cause issues when the presented view is not a split view. eg: a regular iPhone in portrait mode will use a configuration intended for split views.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by iamgabrielma** [comment]
Closed via https://github.com/woocommerce/woocommerce-ios/pull/12004
