### ISSUE TITLE
Blaze: Campaign creation fails to start from the leaderboard on My Store

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12015]
**Describe the bug**
When tapping on the most popular product list on My Store, the product detail screen is displayed. Tapping on the Promote button on the detail screen dismiss it, but the campaign creation flow cannot be presented.

**To Reproduce**
1. Place an order to your test store.
2. Log in to that store on the app and open the My Store tab.
3. Select any product on the product leaderboard and tap Promote on the presented detail screen.
4. Notice that the product detail screen is dismissed but the campaign creation flow is not presented.

**Screenshots**

https://github.com/woocommerce/woocommerce-ios/assets/5533851/05bfad27-55bd-4c13-9c6a-5140ee701298

**Expected behavior**
The campaign creation flow should be presented without any issue.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
