### ISSUE TITLE
Update product row background color to have different colors in selected/deselected states in dark mode

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12031]
Let's follow the design in the orders tab.

dark | light
-- | --
<img src="https://github.com/woocommerce/woocommerce-ios/assets/1945542/bfa0dfcb-6313-46b7-93e4-488fa5b84297" width="300" /> | <img src="https://github.com/woocommerce/woocommerce-ios/assets/1945542/f8de591b-29c9-4790-99bb-92b134ac4b7f" width="300" />

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
