### ISSUE TITLE
[Analytics Hub] Add storage layer support for customizing Analytics Hub (card selection and order)

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#12038]
Need to save in storage:

* The analytics card (name/type)
* Whether it is enabled (selected to display in Analytics Hub)
* Its order in the list of cards

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by rachelmcr** [comment]
I'm thinking about storing these in a plist file using `AppSettingsStore`, similar to `StoredProductSettings` and `StoredOrderSettings`, rather than using Core Data for this. That will match how we're handling these other local app settings, and we can still make the settings store-specific so merchants with multiple stores can customize different sets of analytics if they need.
