### ISSUE TITLE
Bulk edit product multi-selection UI does not reflect selected items. Deselection not working.

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12041]
peaMlT-r4-p2

- Selection checkmark is only shown for the first item
- Deselection doesn't work

![Simulator Screen Recording - iPhone 15 Plus - 2024-02-19 at 09 59 05](https://github.com/woocommerce/woocommerce-ios/assets/3812076/62f338d9-4b54-4dfb-aaf4-06121d2d9149)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
