### ISSUE TITLE
Products tab auto-selection issues

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12045]
- When there's a filter applied to the product list, the selected product in the secondary view might not be in the product list

(This is mostly reproducible in app launch, where the store has more products than the filtered list)

https://github.com/woocommerce/woocommerce-ios/assets/1945542/c20e1965-d53c-48a7-9ae4-32dc01e5ec2b

- When switching to a different store for the first time, the first product isn't selected

https://github.com/woocommerce/woocommerce-ios/assets/1945542/6b3e4f96-ef2c-42d2-baa5-aa8a86ec5a59

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
