### ISSUE TITLE
[Tablet Orders] Design tweaks

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12057]
From review https://github.com/woocommerce/woocommerce-ios/pull/12033#pullrequestreview-1891221396
- [x] Remove `ProductSelectorView` divider between header and list:
⚠️ This seems to be added by default with SwiftUI navigation on iOS16+. Needs more research.
- [x] Add `ProductSelectorView` divider between header and list
- [x] Segmented control is truncated
We can use `.segmented` vs `.menu` built-in types based on size class & screen width
- [x] Adjust header in split view
- [x] `SearchBar` iPhone unnecessary padding and truncation
- [x] Scan button using wrong tint on dark mode

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
