### ISSUE TITLE
Handle the scenario when the product in the secondary view product form is changed elsewhere (e.g. product search modal)

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12072]
While a product form is shown in the secondary view, there could be multiple scenarios for the same product to be updated remotely in the app and make the product outdated in the product form:

- After searching for a product, editing then saving it
- Bulk updating products in the product list (status and price for now)
- Orders tab > order details > Products section, then go back to the Products tab

In this case, two issues arise:

- The product in the secondary view becomes outdated

We can choose to deprioritize this as it's pretty unlikely users would go somewhere else just to update the same product. But it's not a good UX and it'd be nice to notify about the product being outdated with CTAs to refresh or keep editing with a warning. We can observe the product by using `ResultsController`. Alternatively, from testing the Shopify app, the product form state is synced in all product form UI. This probably requires more work to keep track of the product form state in a centralized place and provide it to any product form initialization.

- (Done) The selected row in the product list can be changed to a different index path depending on the sorting criteria. For example, if the user changes the product name and the product list is sorted by name, the selected row can go offscreen (this isn't an issue in the orders tab because there's no way for the user to change the order in the order list)

✅  Based on the changes in https://github.com/woocommerce/woocommerce-ios/pull/11913, the selected product in the product list should be scrolled to be visible after the product is updated in the storage layer.

These issues don't exist without a split view layout because the product form is always fullscreen (the tab bar is covered as well).

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by jaclync** [comment]
Won't be needed once we implement #12260.

**Comment by jaclync** [comment]
Now that product search works similarly to the product list with the product form shown in the secondary column, this issue can be closed.
