### ISSUE TITLE
Test & potentially fix the external triggers that show a product form (deep links, tapping on the AI product creation modal)

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#12074]
Sources that I've (@jaclync) found so far:

- Spotlight https://github.com/woocommerce/woocommerce-ios/pull/9082
- Add product onboarding task in the My store tab (if it hasn't been completed yet)
- AI product creation modal

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by bozidarsevo** [comment]
> * Add product onboarding task in the My store tab (if it hasn't been completed yet)

What would we expect for this use case?
Currently full size screen is shown over the **My store** tab. Do we want to change it to go to **Products** tab and do the product creation flow? @jaclync

**Comment by jaclync** [comment]
> > * Add product onboarding task in the My store tab (if it hasn't been completed yet)
> 
> What would we expect for this use case? Currently full size screen is shown over the **My store** tab. Do we want to change it to go to **Products** tab and do the product creation flow?

Good question! Changing the navigation to the products tab might be out of scope because it's the pre-existing behavior 🤔 Since it'd be the first product that the merchant is creating, I think it's fine to stay in the My store tab so that they can continue to the next onboarding task once the product is created. Just knowing this onboarding task product creation flow works without issues from the tablet changes is good.

**Comment by bozidarsevo** [comment]
> * Add product onboarding task in the My store tab (if it hasn't been completed yet)

Works!

![Simulator Screen Recording - iPad Pro (11-inch) (4th generation) - 2024-02-23 at 12 54 37](https://github.com/woocommerce/woocommerce-ios/assets/6242034/4c704e9c-d13e-49dd-8f6b-9424d2e53f9c)

**Comment by bozidarsevo** [comment]
> * AI product creation modal

Works!

![Simulator Screen Recording - iPad Pro (11-inch) (4th generation) - 2024-02-23 at 12 58 22](https://github.com/woocommerce/woocommerce-ios/assets/6242034/b01bd273-7751-400f-a266-77a6ddb3c82e)

**Comment by bozidarsevo** [comment]
> * Spotlight [[HACK Week] Spotlight activities #9082](https://github.com/woocommerce/woocommerce-ios/pull/9082)

tested on my iPad and all the cases work correctly!
