### ISSUE TITLE
[Pre-existing bug] Products tab: infinite scroll stops working after deleting a product from the list

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12073]
**Describe the bug**

The products tab supports infinite scroll where scrolling toward the bottom of the list triggers sync for the next page. However, after deleting a product from the list, the infinite scroll stops working (no spinner and no new data is loaded).

🗒️ This is likely caused by the limitation of `SyncingCoordinator` where the data size needs to match the multitude of the response page size. We can try replacing it with `PaginationTracker` as in https://github.com/woocommerce/woocommerce-ios/issues/2738.

**To Reproduce**

Prerequisite: the store has more than 25 products (the default page size in the API requests)

- Go to the products tab
- Remove any filters if needed
- Tap on a product, then tap ellipsis menu > Delete
- Confirm the deletion --> the product should be deleted successfully
- After the product deletion is complete, scroll to the bottom of the list --> notice that no spinner is shown at the bottom for the infinite scroll

**Screenshots**

https://github.com/woocommerce/woocommerce-ios/assets/1945542/64c7566d-4d12-4107-952a-f6e0784d0705

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: iOS 17
- WooCommerce iOS version: 17.4

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
