### ISSUE TITLE
[Analytics Hub] Handle Sessions card when customizing the Analytics Hub on a store not using Jetpack Stats

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#12075]
Because of the changes we made for https://github.com/woocommerce/woocommerce-ios/issues/10338, we always hide the Sessions card in some cases:

* Non-Jetpack stores (no Jetpack connection)
* JCP stores
* Stores where Jetpack stats are disabled and the user isn't an admin

In those cases, we shouldn't include Sessions in the list of cards that can be enabled/disabled in the Analytics Hub (since it won't be shown).

Alternately, we could include it but make sure the card is shown with an explanation about why it doesn't show any metrics and how that can be changed (e.g. activating Jetpack or asking an admin to activate Jetpack Stats).

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
