### ISSUE TITLE
Show a confirmation alert when the secondary view product form has unsaved changes and a different product is tapped in the product list

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12086]
Pointed out by @joshheald in https://github.com/woocommerce/woocommerce-ios/pull/12060#pullrequestreview-1895395756

cc @kidinov about implementing this in Android

## Why

When the merchant has some unsaved changes in the product form in the secondary column, they can tap on a different product row in the primary column when the split view is shown, intentionally or not. To prevent the frustrating scenario when the selection of a different product isn't intentional, we'd like to show a confirmation alert for the merchant to confirm whether to discard the unsaved changes or not before it's replaced by the newly selected product.

## Testing steps

Prerequisite: the device/simulator allows switching between expanded and collapsed states like a tablet

### Existing product

- In code, enable `splitViewInProductsTab` feature flag in `DefaultFeatureFlagService`
- Launch the app
- Go to the products tab
- Tap on a product
- In the product form in the secondary view, make some changes to the product like the name --> `Save` CTA should be shown
- Tap on a different product in the product list --> notice that the product form is replaced right away, without any confirmation UI

### New product

- Launch the app
- Go to the products tab
- Tap on + to create a product
- In the product form in the secondary view, make some changes to the product like the name
- Tap on a different product in the product list --> notice that the product form is replaced right away, without any confirmation UI

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
