### ISSUE TITLE
[Tablet Products] M1 Analytics

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12105]
Ref: pfoUAQ-j0-p2

Add a new property horizontal_size_class (compact/regular) to the following events to track the split view usage:

- main_tab_products_selected (when the user selects the products tab)
- main_tab_products_reselected(when the user reselects the products tab)
- product_list_product_tapped (when the user taps on a product row in the products tab)
- product_list_add_product_button_tapped (when the user taps the + icon in the products tab to create a product)
- product_detail_loaded (when the product details form is shown to the user)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
