### ISSUE TITLE
Blaze campaign edit view is shown in split view without any secondary view when split view is enabled

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12104]
Steps to repro:

Prerequisites: the device/simulator supports split view. feature flag is enabled. the store has products eligible for Blaze (store has Jetpack connection).

- Go to the products tab
- Tap `Promote with Blaze`
- Tap `Edit ad` --> notice the form is in split view with an empty view in the secondary view

Expected:

The edit form shouldn't be in split view.

https://github.com/woocommerce/woocommerce-ios/assets/1945542/b5a9a7b2-2940-46e0-a445-63c7a40dd35d

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
