### ISSUE TITLE
Confirmation alert is shown at an odd location when the product form is at a subpage

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12114]
From https://github.com/woocommerce/woocommerce-ios/pull/12103:

If the alert is triggered when the product form is on a subpage (not the root view in the navigation stack), the alert is shown in an odd location

<img src="https://github.com/woocommerce/woocommerce-ios/assets/1945542/6b37b142-3d0d-4b99-a1fe-eff9b1313236" width="500" />

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
