### ISSUE TITLE
[Pre-existing bug] Product form: swiping back or tapping on back button when there are unsaved changes does not trigger a confirmation alert

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#12118]
From https://github.com/woocommerce/woocommerce-ios/pull/12103

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by bozidarsevo** [comment]
@jaclync which back button? Back buttons when editing description and other data?

**Comment by jaclync** [comment]
> @jaclync which back button? Back buttons when editing description and other data?

The back button in the navigation bar, example:


https://github.com/woocommerce/woocommerce-ios/assets/1945542/6fdc4f62-3168-4a80-b2ba-1cc44e6ba63c

**Comment by bozidarsevo** [comment]
> > @jaclync which back button? Back buttons when editing description and other data?
> 
> The back button in the navigation bar, example:
> 
>  Simulator.Screen.Recording.-.iPhone.15.-.2024-02-29.at.14.33.12.mp4

Looks like it is working, but we cannot test it in simulator - https://github.com/woocommerce/woocommerce-ios/blob/0f6788a60aea3c45817278eeb91d47bfc56ff464/WooCommerce/Classes/Extensions/UINavigationController%2BWoo.swift#L61

https://github.com/woocommerce/woocommerce-ios/assets/6242034/76e46696-a5fb-4f20-814f-56702bdc3314

**Comment by bozidarsevo** [comment]
> > > @jaclync which back button? Back buttons when editing description and other data?
> > 
> > 
> > The back button in the navigation bar, example:
> > Simulator.Screen.Recording.-.iPhone.15.-.2024-02-29.at.14.33.12.mp4
> 
> Looks like it is working, but we cannot test it in simulator -
> 
> https://github.com/woocommerce/woocommerce-ios/blob/0f6788a60aea3c45817278eeb91d47bfc56ff464/WooCommerce/Classes/Extensions/UINavigationController%2BWoo.swift#L61
> 
>  RPReplay_Final1709213659.MP4

but it looks like the swipe gesture does not trigger the alert.

**Comment by bozidarsevo** [comment]
Closing this since UIKit code is not working properly, as docummented
