### ISSUE TITLE
[Tablet Orders] Unsaved changes in modal-on-modal product selector are not cleared when selector is closed

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#12135]
## Repro

1. Enable the `sideBySideViewForOrderForm` feature flag
2. Launch the app and navigate to the Orders tab. 
3. Tap `+`
4. Ensure the app is not in `sideBySide` mode, i.e. use a portrait phone, or a narrow split view/slideover on iPad
5. Tap `Add Products`
6. Add some products, but then tap `Close`. Observe that the products are not added to the order (correct behaviour)
7. Tap `Add Products` again
8. Observe that the products are still selected when the selector is shown (incorrect behaviour)
9. Tap `Select n products`
10. Observe that the products are _not_ added to the order
11. Tap `Add Products` again
12. Deselect the products
13. Tap `Done`
14. Observe that then the products _are_ added to the order (despite being deselected.)

## Discussion
Primarily, we need to reset the ProductSelectorViewController when the modal is dismissed. This happens with the flag off.

Secondarily, I think we should move from a `toggle` method, to one where we send the selection state through when it changes.

On Android, the entire selection list is sent, and this may also be helpful for improvements to `immediate` handling of selection sync.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
