### ISSUE TITLE
[Analytics Hub] Show empty state message when no analytics card can be displayed

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#12131]
When a custom time range is selected, the Sessions card isn't shown (because we can't get those stats for custom time ranges).

If the Sessions card is the only selected/enabled card, then when the merchant chooses a custom date range they'll see an empty screen. We should show an empty state message in that scenario:

<img src="https://github.com/woocommerce/woocommerce-ios/assets/8658164/ccf5c2d7-0492-416d-a8b6-4b499284ee65" width="300px">

Discussion: p1708606044423369-slack-C02KUCFCSFP

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
