### ISSUE TITLE
[Tablet Orders] End-of-M3 UI discrepancies

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12146]
There are a number of discrepancies between the proposed design and the current implementation.

Some we decided to not pursue specifically, either due to prioritizing feature work, or due to its added complexity. While others are not really part of the tablet support project. Tested with commit https://github.com/woocommerce/woocommerce-ios/commit/a28476adf90c7792dad289408be0b3d61285cd3d

These are non-blockers for releasing M3.

- [ ] The `My Store` icon, and the colour/tint of the bottom tab icons is different:
<img width="594" alt="Screenshot 2024-02-29 at 15 55 24" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/4f9f09fc-16a6-49a0-8044-d55896ca7009">

--------------

- [ ] The proposed `OrderStatus` component is a dropdown, while the current component is a modal view. Tracked here: https://github.com/woocommerce/woocommerce-ios/issues/12145
<img width="1301" alt="Screenshot 2024-02-29 at 16 07 56" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/36b8ff60-1e3e-4be0-8937-dcc2060ae275">

--------------

- [ ] The search bar shows a microphone icon that infers we can search by using dictation/speech, for accessibility purposes. This is not currently implemented anywhere in the app, and is outside of the scope of this project. Perhaps a good project for HACK week?
<img width="582" alt="Screenshot 2024-02-29 at 16 10 31" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/faa1d885-f450-45c9-a11d-b07efecfad8e">

--------------

- [ ] The `Clear selection` button is entirely hidden on tablets when no products are selected. We show it greyed out for consistency with the iPhone view:

<img width="517" alt="Screenshot 2024-02-29 at 16 17 23" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/a1bfd2a9-40d7-4dc5-94f8-886a542c909b">

--------------

- [ ] Some differences in the Order Summary:
* The greyed-out "Save" button in tablet implies that empty orders cannot be created. This goes against core behaviour, or what can be done on iPhone.
* Row capitalization is different, and seems to go against the capitalization guidelines?
* Title: "New Order" (implemented) vs "Order Summary" (proposed iPad) vs "Create Order" (proposed iPhone). Ideally, we should be consistent and choose one.
* Action button: "Create" vs "Save". This is different in iPhone and tablet. As above, ideally we should be consistent and choose one.
* Row: "Add customer note" vs "Add Note".

| [Design] Empty Order | [Design] Order with items | Implementation |
|--------|--------|--------|
| <img width="257" alt="Screenshot 2024-02-29 at 16 19 39" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/fbd394d6-cf90-453c-b8b0-3265622f0364">|<img width="244" alt="Screenshot 2024-02-29 at 16 20 53" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/873630f2-39bf-49cd-9924-0233c0d6167e">|<img width="261" alt="Screenshot 2024-02-29 at 16 24 10" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/93e9fae6-56b3-4c81-aeaa-c4bb9ccd13a3">|

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
All covered in other issues, or not required for the project as unintended design differences.
