### ISSUE TITLE
[Tablet support] Set max height to the Blaze image view so that the image doesn't look overly large on tablets

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#12141]
created from PR comment https://github.com/woocommerce/woocommerce-ios/pull/12106#pullrequestreview-1908082141

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
