### ISSUE TITLE
Missing stats for custom date ranges

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12142]
## Problem
When I select a time range for a custom range tab, the start date of the stats is one day later. As in the screencast below, I picked Feb 1-8 - but I got only stats for Feb 2-8:

https://github.com/woocommerce/woocommerce-ios/assets/5533851/0beafb12-352e-469e-be1d-b6596ee89bba

## Expectation
For a custom date range, we want to consider all the stats included from the start date to the end date.

## Potential causes:
In `OrderStatsRemoteV4`, we are setting the start date to the `after` param in the fetching request:

https://github.com/woocommerce/woocommerce-ios/blob/a28476adf90c7792dad289408be0b3d61285cd3d/Networking/Networking/Remote/OrderStatsRemoteV4.swift#L31-L43

This causes the API to return only results for the days after the start date. 

## Potential solution: 

- Adjust `earliestDateToInclude` to one day before
- Update the `quantity` param to be the difference between the start date and end date, plus one extra day to include both dates in the stats.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
