### ISSUE TITLE
[Tablet Orders] Order List: UI updates

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12149]
From design review to the Order List component: 6kkCwI9VOEYcidp6UT5bln-fi-1108_27535

* Missing divider line between header and order list
<img width="664" alt="Screenshot 2024-02-29 at 19 19 18" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/b8a048e1-0d39-4347-8d56-07b59007ad17">

* "No order selected" new background ( note the missing navigation bar ) 

| Before | After |
|--------|--------|
| <img width="510" alt="Screenshot 2024-02-29 at 19 20 15" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/931ff02d-4271-42ac-bea6-36eb47dd7832"> | <img width="526" alt="Screenshot 2024-02-29 at 19 22 00" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/2b9037d4-37c1-48a0-8fc9-9b62081b41c5"> |

* Selected product row has no top and bottom borders

<img width="638" alt="Screenshot 2024-02-29 at 19 22 42" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/c789416b-a6e3-482c-b492-690f3c0a0f51">

* Update selected colour: `Woo Purple 0` / `#F2EDFF`

<img width="389" alt="Screenshot 2024-02-29 at 19 23 44" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/306b865d-4958-4145-bf83-c98dc74859a5">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
> Update selected colour: Woo Purple 0 / #F2EDFF

The colour definition for shade0 is different in the app, compared to Figma, so we should check the rest of them too. Changing it might break screenshots etc. 6kkCwI9VOEYcidp6UT5bln-fi-1108:27839#719647552

**Comment by joshheald** [comment]
Note that the empty state changes, particularly removing the nav bar, are low priority as it's rarely seen.

If they're easy, we'll do them now, otherwise they will be split out.
