### ISSUE TITLE
Add margin or max width to product form and the subpages

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12144]
From Joe's design feedback pfoUAQ-iv-p2#comment-227:

> On Orders, I advised that we should add margins to the order details area, to reduce the amount of space between label and data in the table views. I think we should apply this consistently on products, too.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
