### ISSUE TITLE
[Order List] Nudged product row -sometimes- doesn't return to original position

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12151]
I wasn't able to replicate it purposefully, but sometimes when we load the order list, the nudged product row doesn't return to its original position:

<img width="322" alt="Screenshot 2024-02-29 at 19 41 24" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/e53996d2-027a-4140-99ac-d17721299662">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by pmusolino** [comment]
It happened also to me, I was going to open the same issue! 
Release: 17.6

<img src="https://github.com/woocommerce/woocommerce-ios/assets/495617/61740f46-d593-43cb-843a-af52d421fd90" width=300 />

**Comment by Ecarrion** [comment]
closed in favor of #14025
