### ISSUE TITLE
[Tablet Orders] Create Order: UI updates

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12155]
From 6kkCwI9VOEYcidp6UT5bln-fi-1108_27535

* ✅ Barcode button doesn’t do anything: Expected for this iteration, has been removed.
* ✅ Reduce gap size
* [x] TODO: Missing divider lines
* [x] TODO: 
  * ✅56pt high buttons. 
  * ✅ No gap between buttons. 
  * ✅ 8pt space above and below button groups - even groups of one (top and bottom of section).

<img width="905" alt="Screenshot 2024-02-29 at 19 58 39" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/3cbc9dbf-6977-414d-89da-28e60fe0fea1">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
