### ISSUE TITLE
[Tablet Orders] Make `X` button `Cancel`

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#12168]
The `x` button to close the Order Creation/Editing screen would be more obvious as a `Cancel` button – we should change it to the word.

![Image](https://github.com/woocommerce/woocommerce-ios/assets/2472348/f219c30f-e1d4-49d3-97f1-f8005dba7752)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
