### ISSUE TITLE
[Analytics Hub] Add UI for Gift Cards card

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#12165]
We need to add the UI for an analytics card for the Gift Cards extension. This card should retrieve its data from the new endpoint added in https://github.com/woocommerce/woocommerce-ios/issues/12163.

This card should only be visible in the Analytics Hub for stores with the Gift Cards extension active. (Stores without the extension will see it in the Customize Analytics screen but it can't be enabled.)

## Content

- Card title: Gift Cards
- Metrics:
   - Used (number of gift cards)
   - Net amount ($ amount)
- Percent change from previous period for each metric
- Chart with interval data for each metric
- "See Report" button linking to relevant report in a webview (`path` parameter in URL is `%2Fanalytics%2Fgift-cards`)

## Design

![Image](https://github.com/woocommerce/woocommerce-android/assets/8658164/40e93b0b-305d-426e-b428-79361146c33e)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
