### ISSUE TITLE
[Analytics Hub] Update Customize screen to include Gift Cards row

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#12166]
Add the Gift Cards card to the Customize Analytics screen:

* If the extension is not active on the store, show an "Explore" row with a link to the extension on woo.com (similar to product type filter on Products tab) and no controls to enabled or reorder the card.
* If the extension is active on the store, include controls like the core analytics cards.

![Image](https://github.com/woocommerce/woocommerce-android/assets/8658164/6b0faa31-5f88-4023-922a-be58637fe4a2)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
