### ISSUE TITLE
[Analytics Hub] Update Customize screen to include Product Bundles row

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#12161]
Add the Bundles card to the Customize Analytics screen:

* If the extension is not active on the store, show an "Explore" row with a link to the extension on woo.com (similar to product type filter on Products tab) and no controls to enabled or reorder the card.
* If the extension is active on the store, include controls like the core analytics cards.

![Image](https://github.com/woocommerce/woocommerce-android/assets/8658164/0e7f97f0-380b-43e2-87bd-c92da77170cb)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
