### ISSUE TITLE
Zendesk update - migrate from 2.3 -> 3.0.1

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1216]
There are two parts to the Zendesk update:
1. Migrate to 3.0 (merge to develop)
2. Create a feature branch and point to beta releases

This ticket is a prerequisite to support future builds of our project. 

- [x] update Zendesk in the podfile
- [x] migrate from Zendesk version 2.3 SDK to 3.0 (there are breaking changes)

**Comment by ctarda** [comment]
Moving to done. The future branch pointing to beta releases is implemented in PR #1231
