### ISSUE TITLE
[Tablet Orders] Improve search experience

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#12170]
The search in split view order list/order details opens in a modal... which is strange.

It would be better if it worked wholly in the context of the split view controller, ideally. Search controllers can be tricksy, and that might take a while, so as a fallback we will instead improve it by having the results open in the split view, keeping the search is in the modal.

6kkCwI9VOEYcidp6UT5bln-fi-1108:29264#719679246

![Design comments](https://github.com/woocommerce/woocommerce-ios/assets/2472348/e8ee8151-70d4-41b6-93cd-68518d866ea2)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
