### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12178]
Event name | Properties | Triggers
--- | --- | --- 
*_dashboard_stats_custom_range_add_button_tapped |  | When the user taps the button to add a custom range
*_dashboard_stats_custom_range_confirmed | is_editing: true / false | When the user confirms a date range for a custom range tab
*_dashboard_stats_custom_range_tab_selected |  | When the user selects the custom range tab of Dashboard stats.
*_dashboard_stats_custom_range_edit_button_tapped |  | When the user taps the button to edit the date range on the custom range tab of Dashboard stats.
*_dashboard_stats_custom_range_interacted |  | When the user taps on the chart on custom range to see metrics for specific periods.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
