### ISSUE TITLE
Product form > shipping: show shipping settings table view in readable width like in price/inventory settings

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12180]
![Image](https://github.com/woocommerce/woocommerce-ios/assets/1945542/fe36cf52-d441-4545-a654-0327d9143b88)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
