### ISSUE TITLE
Provide site credentials login option from WP.com email screen as fallback

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-ios#12183]
During login flow in the email input screen, add a fallback option:

`Log in with site credentials` 

To let users log in with site credentials instead of WP.com email and password.

<img width="300"  src="https://github.com/woocommerce/woocommerce-android/assets/2663464/f7174dd3-551f-4e01-a419-6aed94836b7f">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by ignacyhologa** [comment]
I am also having issues with login to my self hosted woocommerce in ios app. It does not let me enter my site credentials. Instead it prompts only for the wp.com credentials and requires jetpack. It worked previously.

**Comment by pmusolino** [comment]
This should be fixed now, I'm not able to replicate the issue anymore, so closing it.
