### ISSUE TITLE
Orders filter auto-resetting

### ISSUE THREAD

**Issue by elibud** [woocommerce/woocommerce-ios#1218]
**Describe the bug**
The Orders filter is being reset after completing an order.

**To Reproduce**
1. Go to the orders list.
2. Filter by failed.
3. Chose a failed order.
4. Edit it and mark it as completed.
5. Go back to the orders list.
6. The filter seems to reset to All.

**Screenshots**
I have a video, but I'm afraid it may contain some private information, DM me and I can send it over.

**Expected behavior**
I expected my previously selected filter to remain applied. Also, shouldn't' there be a tick indicating what filter is the one currently being applied?

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: iOS 13 beta 6
- WooCommerce iOS version: 2.4.0.1

**Comment by mindgraffiti** [comment]
This bug needs fixed by whomever is claiming the Order List redesign tasks.

**Comment by mindgraffiti** [comment]
>Also, shouldn't' there be a tick indicating what filter is the one currently being applied?

@elibud since we're using an action sheet, there isn't a place to put a tick mark. It does list the chosen filter in the nav bar title, though:

<img src="https://user-images.githubusercontent.com/1062444/66578873-7c296500-eb41-11e9-85b7-b1181a4f1ea7.png" width="350" />

**Comment by elibud** [comment]
Got it, thanks @mindgraffiti.

**Comment by jaclync** [comment]
> Also, shouldn't' there be a tick indicating what filter is the one currently being applied?

How aoubt adding a checkmark to the action name? An example using "✓" (`U+2713`):

<img src="https://user-images.githubusercontent.com/1945542/66804396-ea609400-ef54-11e9-849c-0ae71e15bacc.png" width="350" />

(also checking with @kyleaparker )

**Comment by kyleaparker** [comment]
>How about adding a checkmark to the action name? An example using "✓" (U+2713):

It looks odd to use a check mark in an action sheet, I'm not I've seen this done anywhere. I think if we moved towards a view like this it would make more sense: 

![IMG_86CA30DD2B78-1](https://user-images.githubusercontent.com/712873/66853850-36f4a100-ef4e-11e9-9a5d-bdba3b9a974b.jpeg)

**Comment by mindgraffiti** [comment]
Oh that looks like our Shipment Tracking Provider view controller. Like when you select from the list of shipping providers. (Sorry, I can't share a screenshot right now.)

**Comment by jaclync** [comment]
We do have the edit Order status screen with the checkmark as the accessory view:

![Simulator Screen Shot - iPhone 8 - 2019-10-16 at 08 27 27]()

<img src="https://user-images.githubusercontent.com/1945542/66878955-d8333400-efee-11e9-9495-01a5ddc1b5c0.png" width="350" />

> It looks odd to use a check mark in an action sheet, I'm not I've seen this done anywhere.

yea usually the action sheet isn't used for picking an option from a list on iOS, I just saw the check mark from a list on GitHub assignees, but it's web 😄

<img width="338" alt="Screen Shot 2019-10-16 at 8 23 51 AM" src="https://user-images.githubusercontent.com/1945542/66879207-c69e5c00-efef-11e9-88dd-2713388e44ed.png">

**Comment by kyleaparker** [comment]
>We do have the edit Order status screen with the checkmark as the accessory view:

**Comment by kyleaparker** [comment]
>We do have the edit Order status screen with the checkmark as the accessory view:

Yea exactly. I'm not sure this is something we need to worry about changing right now since the orders screen is going to be changing soon anyway
