### ISSUE TITLE
Reviews: Review age is incorrect 

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12194]
A lot of PRs have been failing today due to the unit tests `testAgeCalculationsReturnLast7DaysAgeForAlmostSevenFullDays` and `testAgeCalculationsReturnLastOlderForMoreThanSevenFullDays`. The reason is not due to the flaky tests, but the incorrect [implementation](https://github.com/woocommerce/woocommerce-ios/blob/1cc04aca84d327db6234b57374adf324d481ed44/WooCommerce/Classes/Model/ReviewAge.swift#L27-L55) that checks for month/week differences by calendar instead of day count.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
