### ISSUE TITLE
Display the exact selected date range and granularity

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12206]
Currently we are displaying only the date range available in the data returned from the revenue stats endpoint.

To better match the behavior with wp-admin, we should display the exact selected date range on the UI. Also, for better clarity, we should also display the selected granularity below the date range.

![custom range on wp-admin](https://github.com/woocommerce/woocommerce-ios/assets/5533851/7fa53e13-bf7e-4c71-abc7-efc6a8764c82)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
