### ISSUE TITLE
Visitor stats cannot be loaded for quarterly granularity

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#12205]
The visitor stats endpoint `/stats/visits/` do not support returning quarterly granularity, so when in Custom Range the granularity is set to quarterly, it won't return the right data. This will make selecting individual value in the chart return the wrong/empty value for long custom range where the granularity is quarterly.

To simplify things, we decide that we should update things this way:

- if the date range is < 3 years, set granularity to monthly
- if the date range is >= 3 years, set granularity to yearly

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
