### ISSUE TITLE
[Tablet Orders] Prevent editing products on completed (or otherwise uneditable) orders

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#12200]
Prior to M3 of Project Lily Pad, `Completed` orders could not be edited. This behaviour should be maintained, but it's only enforced on the client. It's implemented by disabling the `+ Add product` buttons, and quantity/remove controls on the product card in the Edit Order screen.

With M3 of Lily Pad, the product selector is always active on iPads and iPhones in horizontally regular contexts. It doesn't get disabled, so it's possible to add and remove products by making changes in the selector.

The safest approach would be to disable changes in the selector itself, as that would communicate to the merchant that they can't make these changes before they do anything... however the lock icon is less obvious in this context.

## Repro
1. Enable the `sideBySideViewForOrderForm` feature flag
2. Launch the app on an iPad or large iPhone in landscape
3. Tap the `Orders` tab, and select a `Completed` order
4. Tap `Edit`
5. Change the selection in the product selector
6. Tap `Recalculate`, then `Done`.
7. Observe that the order has been changed, even though it was previously paid for.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
