### ISSUE TITLE
[Design review] Products tab: divider updates

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12212]
Design ref: w3JBReW1UJesCf02sj43kR-fi-1894_11886

- [ ] Add a divider between the table view and the sort/filter bar
- [ ] Remove the divider beneath the navigation bar title (I don't seem to see this in my testing)

![Image](https://github.com/woocommerce/woocommerce-ios/assets/1945542/6cf8aa30-31b8-444a-8117-80ae12858db1)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by bozidarsevo** [comment]
The bottom one shows only when scrolled. Should we add the explicit one for that case or leave it like it is:

![Image](https://github.com/woocommerce/woocommerce-ios/assets/6242034/78752b93-0421-4f49-bf78-2db805f7da57)
