### ISSUE TITLE
[Design review] Orders/products tab: update selected row background color

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12211]
Design ref: w3JBReW1UJesCf02sj43kR-fi-1894_11886

![Image](https://github.com/woocommerce/woocommerce-ios/assets/1945542/3a5c13ee-f0ba-4632-823d-895f95b004fe)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
