### ISSUE TITLE
[Design review] Show "Product" in the product form navigation bar title

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12213]
Design ref: w3JBReW1UJesCf02sj43kR-fi-1894_11886

![Image](https://github.com/woocommerce/woocommerce-ios/assets/1945542/413f89bc-225a-4ef6-8a7f-c2a07fe2eabc)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
