### ISSUE TITLE
[Analytics Hub] When percent change is 0%, the text is not visible in dark mode

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#12229]
**Describe the bug**
When using a dark theme and the data is 0%, the value is not readable.

h/t @atorresveiga for finding the issue! (Related: pe5pgL-4wy-p2#comment-3820)

**Screenshots**

![image](https://github.com/woocommerce/woocommerce-ios/assets/8658164/5f738b2c-fd38-458a-bb55-b119c8c0b951)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
