### ISSUE TITLE
[Analytics Hub] Refactor hub/card view models

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#12233]
Goal: Make the Analytics Hub easier to extend (adding new cards) and simplify the hub view model logic.

Basic plan: Create separate view models for each card (with relevant unit tests), to separate their constants and properties from the hub view model.

* Create one or more protocols to replace the current view models:
   * Defining the properties needed to create the card views
* Create individual view models for each card:
   * Conforming to the relevant protocol.
   * Initialized with the stats and time range data it relies on, with tests for how that data is parsed.
   * Including methods to redact the card (for a loading state) and to update the card with new data.

---

Broader plan: Use additional protocols to decouple the specifics of each card (e.g. which cards need which types of stats data, which cards need a time range) from the hub view model. This way, the hub view model wouldn't need to manage fetching and updating data, updating the time range, and redacting each card view model individually. It could make those changes for all the card view models that require them.

* Create a protocol for all cards used in the Analytics Hub:
   * `redact()` method for the loading state.
* Create additional protocols for card view models that have different types of stats data, and for card view models that use a time range:
   * Properties for the stats data and time range they require
   * Method to update the card data (metrics) based on new stats
   * Method to update the card data (report link) based on new time range
* Conform the individual card view models to the appropriate protocols for updating their stats data and time range.
* In the Analytics Hub view model, fetch stats data and update cards based on conformance to the cards' stats data protocols:
   * Create an array of card view models (e.g. `enabledCardViewModels`) using the order loaded from card settings.
   * In `switchToLoadingState(_:)`, pass in the array of view models and use their `redact()` method.
   * In `retrieveData(for:)`, pass in the array of view models and use the stats data protocols to determine what data needs to be fetched and update the view models afterwards.
   * When `enabledCards` is updated, update `enabledCardViewModels` with the correct set of view models in the expected order.
   * When the selected time range is updated, update each view model in `enabledCardViewModels` with the new time range.
* In the Analytics Hub view, pass in `enabledCardViewModels` (instead of `enabledCards`) to create each view model.

Challenges:

* Currently, the Products card relies on two separate view models that load separate data and are redacted separately. We would need to change how that card is constructed, for example:
   * Create a products card view model that contains its component view models (stats and item sold).
   * Conform the new view model to the required protocols, and call the component view model methods as needed (to update stats data and time range).
   * Update the products card view to accept the new view model.
* The Jetpack Stats CTA card is still a special case and is handled differently. This would probably need to move into a separate sessions view that decides whether to show the CTA or the regular sessions card.

For now, the basic refactoring is probably sufficient to make the hub view model more focused and easier to read/work with. Adding new cards still requires a significant amount of careful checks to make sure the card is handled correctly throughout the hub view model, but the effort may not be worth the payoff at this point.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
I'll go ahead and close this as done for now, with the basic refactoring complete.

We can revisit the broader plan later on if we want to do further refactoring.
