### ISSUE TITLE
What's New Announcement: Layout bug and crash when opening from Settings

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12234]
When testing a new announcement on an iPhone 15 simulator, I found these issues:
- The icons are not aligned with the top of the title.
- The app crashes when I open announcement from settings.

<img src="https://github.com/woocommerce/woocommerce-ios/assets/5533851/2c2824ae-9337-463e-8bcf-d5a7d0345506" width=320 />

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
