### ISSUE TITLE
Update public documentation on "How to connect your store"

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#12248]
Update the public documentation related to "how to connect your store", since it's outdated and it doesn't include how to connect the store with application passwords. -> https://woo.com/document/woocommerce-ios/#connect-to-your-store

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by JorgeMucientes** [comment]
The [docs](https://woocommerce.com/document/woocommerce-ios/#connect-to-your-store) now have a section explaining the site credentials login. Seem like this issue is resolved now. Closing.
