### ISSUE TITLE
Login: Invalid site address can still be directed to email login

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12244]
**Describe the bug**
When entering an invalid site address, I can still be directed to the email login screen. When I navigate back, the site address is autofilled as wordpress.com/blog.

**To Reproduce**
1. Log out of the app if needed.
2. On the prologue screen, select Log In.
3. Enter an invalid site address ending with `wpcomstaging.com` or `wordpress.com`.
4. Notice that you can still reach the email login screen.
5. Navigate back, notice that the site address is wordpress.com/blog.

**Screenshots**

https://github.com/woocommerce/woocommerce-ios/assets/5533851/b7e576cf-7737-42f5-aed6-cc0f41117a9b

**Expected behavior**
The invalid site address screen should be displayed instead.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
