### ISSUE TITLE
[Design review] Products tab: update product search to show product list in the primary column and product form in the secondary column

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12260]
Ref: Joe's comment pfoUAQ-iv-p2#comment-227 / w3JBReW1UJesCf02sj43kR-fi-1894_11886

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
