### ISSUE TITLE
Align "Delete" Button Wording Across iOS and Android Platforms

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#12271]
### Description
There is an inconsistency in the wording used for the action related to deleting or trashing a product in the mobile app on different platforms.

### Details
- On iOS, the button says “Delete” and the alert asks if the user wants to “move this product to the trash” with the action labeled as “Move to Trash.”
- On Android, the button says “Trash product.”

This inconsistency might lead to user confusion and a lack of coherence in the user experience across platforms.

### Change
Align the wording to stay consistent with the backend and across both platforms. The term “Move to Trash” is the one currently used on Android.

### Screenshot
<img src="https://github.com/woocommerce/woocommerce-ios/assets/495617/5f14cb33-a286-4c77-bfe9-a5dc56638233" width=300 />

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
