### ISSUE TITLE
UI issues on tablet

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12280]
While working on #12258, I found a couple of UI issues on tablets:

1. The store name screen has a split view:

<img src="https://github.com/woocommerce/woocommerce-ios/assets/5533851/2d50e626-5b1a-4ee3-a03a-0106657bc2b3" width=320 />

2. The popover on the coupon edit screen can be updated to point from the ellipsis button:

<img src="https://github.com/woocommerce/woocommerce-ios/assets/5533851/ee5154e1-b5fe-4066-9a54-c2026ef919d5" width=320 />

3. The coupon type sheet layout is breaking:

<img src="https://github.com/woocommerce/woocommerce-ios/assets/5533851/c67a9d5b-54f7-46c1-a65f-5100c7125463" width=320 />

4. Blaze Add parameter screen shows split view:

<img src="https://github.com/woocommerce/woocommerce-ios/assets/5533851/c5e02f8e-0b49-4426-aee2-77468ba8cde1" width=320 />

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
