### ISSUE TITLE
Product Form: Extra title on the product form causes the navigation bar to be cluttering in small screens

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12289]
**Describe the bug**
The title "Product" seems to be visible since the introduce of the split view on the Products tab. This makes the navigation bar cluttering on small screens.

**To Reproduce**
1. Log in to the app.
2. Switch to the Products tab.
3. Click the "+" button and select a product type.
4. Notice the title "Product" title standing quite closed to the buttons "Preview" and "Publish".

**Screenshots**
<img src="https://github.com/woocommerce/woocommerce-ios/assets/5533851/e06104cd-3648-4840-ad8c-3cbb272af6be" width=320 />

**Expected behavior**
The title should be hidden at least in compact horizontal size classes.

cc @jaclync and @bor0 since you might be working on this feature.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by jaclync** [comment]
This was a change from https://github.com/woocommerce/woocommerce-ios/issues/12213, and Joe's comment (ref in the issue) mentioned that it's fine to apply to both tablet and phone formats. Tagging @joe-keenan to confirm this.

**Comment by joe-keenan** [comment]
Oh dear, good catch, @itsmeichigo. 

I forgot we had that many actions in the nav bar when I gave my tablet feedback.

We’ve got enough space for a title on tablet, but we definitely don’t on phones. Can we please remove it again on phones?

Sorry about the oversight.

**Comment by bozidarsevo** [comment]
@jaclync is it ok if I take this?

**Comment by jaclync** [comment]
> @jaclync is it ok if I take this?

Of course, go for it 👍
