### ISSUE TITLE
Hub Menu: outdated navigation

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12282]
Since we dropped support for iOS 15, we've got a lot of warnings for the deprecated API of `NavigationLink` with `isActive`, especially in Hub Menu.

We should fix the warnings to avoid unexpected behaviors when the API is no longer supported.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
