### ISSUE TITLE
[Better Errors] App Passwords Explanation Design adjustment

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#12299]
[Figma](https://www.figma.com/file/w3JBReW1UJesCf02sj43kR/Joe%E2%80%99s-Scratchpad?type=design&node-id=1938-6274&mode=design&t=MIBV1Bf3J9XDB2CV-0)

## UI

![Image](https://github.com/woocommerce/woocommerce-ios/assets/562080/6f80b086-8262-4e91-8e1a-3c3523afc41e)

## Tasks

- [ ] Update UI to new designs
- [ ] Update tutorial image
- [ ] Update texts

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
