### ISSUE TITLE
[Hub Menu] Customers: Expand `WCAnalyticsCustomer` model

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#12297]
Task: Expand `WCAnalyticsCustomer` model to include all customer fields required for the new Customers section.

We currently only decode and store the following fields when fetching wc-analytics customers:

* `user_id`
* `username`
* `name`
* `email`

We should add support for the following fields as well, so we can display more customer details:

* `id` (`user_id` is 0 for non-registered customers)
* `date_registered_gmt` - can be `null`
* `date_last_active_gmt` - should always have a value
* `orders_count` - can be 0
* `total_spend` - can be 0
* `avg_order_value` - can be 0
* `country` - can be empty string
* `city` - can be empty string
* `state` - can be empty string
* `postcode` - can be empty string

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
