### ISSUE TITLE
[Hub Menu] Customers: Update remote endpoint behavior for fetching wc-analytics customer data

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#12296]
Task: Update `WCAnalyticsCustomerRemote` to support requesting customers for the Customers section:

* Currently we hard-code the `orderby` parameter to always sort the customers by `name` and the `order` parameter to sort them in ascending order. We want to be able to sort them by the last active date (with the latest first), but retain the current ordering where it's already being used.
* Currently we hard-code the `filter_empty` parameter to always filter out empty emails. We want to be able to include those customers, but retain the current filtering behavior where it's already being used.

Current parameters:

* `orderby`: `name`
* `order`: `asc`
* `filter_empty`: `email`

Parameters for customer section:

* `orderby`: `date_last_active`
* `order`: `desc`
* No `filter_empty` parameter

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
