### ISSUE TITLE
[Analytics Hub] Show Sessions card with explanatory message when custom date range is selected

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#12295]
When a custom date range is selected, we should display the session card with an alternative message inside it:

> **Session data unavailable**
> Session analytics rely on unique visitor counts not available for custom date ranges.

See design (on the right):

![image](https://github.com/woocommerce/woocommerce-ios/assets/8658164/4c7a4e92-27f8-4c32-a8ba-410e1776f080)

In the interest of time, if that isn't possible/takes too much to implement: When a custom date range is selected and the sessions card is the only selected card in the analytics hub, we can hide the sessions card and show an empty state (above, left).

Discussion: pe5pgL-4FA-p2#comment-3837

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
