### ISSUE TITLE
Notifications: tapping a new order push notification goes to Reviews tab instead of Orders tab

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1230]
**Describe the bug**
Now that the notifications tab is refactored to the reviews tab, let's navigate the app to the orders tab when tapping on a new order notification.

**To Reproduce**
1. Place an order for the store currently logged in
2. Tap into the new order push notification --> right now it goes to Reviews tab

**Expected behavior**
the app should go to Orders tab

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: 12.2/13 beta 
- WooCommerce iOS version: 2.6

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by zwiesman31** [comment]
User also reported in 2475620-zen
