### ISSUE TITLE
[Hub Menu] Customers: Add new storage entity for `WCAnalyticsCustomer`

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#12309]
We have a single `Storage.Customer` entity that currently reflects customer data retrieved from both `Networking.Customer` and `Networking.WCAnalyticsCustomer`. However, it is essentially a reflection of the [WooCommerce customer properties](https://woocommerce.github.io/woocommerce-rest-api-docs/#customer-properties) for registered customer users:

* user ID
* name
* username
* email
* billing address
* shipping address

Currently, we're using the wc-analytics endpoints and to search customers and return lightweight information about customers (name, username, email), mapping that data from the `Networking.WCAnalyticsCustomer` model to `Storage.Customer` in a way that makes it fit the `Networking.Customer` model. This is done for the purpose of then retrieving specific `Networking.Customer` entities (e.g. to get their billing/shipping address), so it makes sense to combine the data in a single storage entity.

However, we now want to expand the `Networking.WCAnalyticsCustomer` model to add support for more of the fields retrieved from wc-analytics, so we can display a Customers section like in wp-admin. Given that we want different customer data and we want to diverge from the existing `Customer` storage and networking model, and we want to include customers that we aren't currently using elsewhere (i.e. unregistered customers without email addresses) it makes sense to store these as a separate storage entity for use independent of `Storage.Customer`.

To that end, we should create a new storage entity for `WCAnalyticsCustomer` reflecting all the fields in that networking model (including the fields added in https://github.com/woocommerce/woocommerce-ios/issues/12297).

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
