### ISSUE TITLE
Blaze: Changes to Add/View Payment methods

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12303]
- Replace the add payment form URL.
- We implement a logic similar to what we have in Shipping Labels to auto-dismiss the WebView when a payment method is added.
- When the webview is dismissed, reload payment methods from the Blaze endpoint, then show the payment method list, and wait for the user to select a payment method.

Internal - p1710256482532449/1710173714.420789-slack-C03L1NF1EA3

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
