### ISSUE TITLE
My Store Analytics: Update the See More button style

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12300]
Joe suggested on Slack [p1710812842434369/1709651270.092029-slack-C0354HSNUJH] that we should update the See More button to be more friendly:

![image](https://github.com/woocommerce/woocommerce-ios/assets/5533851/36985e80-dc90-4a60-9ef0-cecb2781d47f)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by itsmeichigo** [comment]
Closing as the button has been updated as part of Dynamic Dashboard project.
