### ISSUE TITLE
Blaze: Add new field `budget` to campaign model

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12301]
New update to the campaign model [peeHDf-2fw-p2#comment-1934]:

> Also we’re launching “evergreen campaigns” now (campaigns that run without end date) so we want to extend our budgeting options. If you still have possibility to make changes do you mind to change total_budget field to budget that looks like this:

```
{
    ...
    "budget": {
        "mode": "total", // "total" or "daily"
        "amount": 230.00,
        "currency": "USD"
    }
    ...
}
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
