### ISSUE TITLE
[Hub Menu] Customers: Add UI for Customers screen with customer list

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#12316]
We need to add a Customers screen showing a searchable customers list, for use in the Hub menu.

We should be able to reuse UI from the customer list in order creation. A few notes:

* We want to load results from `WCAnalyticsCustomer` objects in storage, including unregistered users.
* We want to fetch customers from remote and can show a loading view if we don't have any locally stored data, or a spinner in the top right if we're loading new data in the background.
* We want to sort the list by last active date.
* If we don't have a name for the customer, we can use the name `Guest`.

![image](https://github.com/woocommerce/woocommerce-ios/assets/8658164/4934f005-e8dc-4bac-b863-cfc7d680aa1d)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
