### ISSUE TITLE
[REST API] Add support for WordPress.com account creation as part of Jetpack Setup

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-ios#12310]
Currently, in the Jetpack Setup flow, we don't support creating new accounts, which is counter-intuitive, as users who are installing Jetpack for the first time will most likely need to create a new account.

Using tracks, we can confirm this: currently, the login step is one of the biggest drops in the Jetpack Setup, as only 22% are able to finish it. From the failures, we can see that `UNKOWN_USER` is responsible for the biggest part of the cases.

###### Relevant internal discussion p1710847254725509-slack-C03L1NF1EA3

```[tasklist]
### Tasks
- [ ] #14420
- [ ] #14419
- [ ] #14421
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14468
- [x] Enable feature flag
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
