### ISSUE TITLE
Update prologue screen to remove Woo Express signup

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12324]
- Make the “Log in” button primary CTA
- Re-word the “Create a new store” button to "Starting a new store?" and make it a link button to open https://woo.com/hosting-solutions/.
- Update the Prologue's text to "From your first sale to millions in revenue, Woo is with you. See why merchants trust us to power 3.4 million online stores."
- Use the event `login_prologue_starting_a_new_store_tapped` when "Starting a new store" is tapped instead of `login_prologue_create_site_tapped`.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
