### ISSUE TITLE
Update the order > product search keyboard to use a "Done" button rather than "Return"

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12326]
From p91TBi-b2h-p2#comment-11888

> The keyboard currently does have a Done and a Return buttons (depending the type of keyboard that’s used on what view, the one above uses Return). Perhaps the Done is clearer since it’s also using a different system colour and does actually imply that we’re done
> a blue “Done” is much clearer. I think “Return” makes more sense for multi-line fields.

<img width="730" alt="Screenshot 2024-03-20 at 14 22 24" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/257e0611-0a45-432c-817f-57fa1794ae08">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
