### ISSUE TITLE
Product templates not working

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#12338]
**Describe the bug**
We provide the option to new stores to create template products. This appears to not be working correctly. The product is created but without any template.

**To Reproduce**
1. Login into a store with less than 3 products
2. Create a product and choose a physical template
3. See that an empty product is created.

**Screenshots**

https://github.com/woocommerce/woocommerce-ios/assets/562080/4d88bbf1-ed83-4506-8409-9656506f3649

**Expected behavior**

The product created should be filled with template data.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by itsmeichigo** [comment]
@Ecarrion I quickly looked into this and found that the endpoint `wc-admin/onboarding/tasks/create_product_from_template` no longer creates a product with template data. Is it worth it to raise this in a CUW post or hide the entry point to product templates while we figure out how to fix this?

**Comment by Ecarrion** [comment]
> @Ecarrion I quickly looked into this and found that the endpoint `wc-admin/onboarding/tasks/create_product_from_template` no longer creates a product with template data. Is it worth it to raise this in a CUW post or hide the entry point to product templates while we figure out how to fix this?

Hi @itsmeichigo, there is a CUW post for this issue. peaMlT-uG-p2

At the time we decided to leave this to be worked as a backlog issue. 

Regarding the feature, I think we should analyze its usage and possibly delete it if it isn't widely used. cc @toupper @pmusolino

**Comment by rachelmcr** [comment]
> Regarding the feature, I think we should analyze its usage and possibly delete it if it isn't widely used.

I checked and the template option is chosen with about the same frequency as the manual option (the `type` property on the `woocommerceios_add_product_creation_type_selected` event). Given that, it'd be good to check if there's a straightforward way to get this working again before removing it.

**Comment by rachelmcr** [comment]
Ah, the sample data in the product templates was intentionally removed in https://github.com/woocommerce/woocommerce/pull/38343. If we want to reinstate it to support template product data in the apps, we'll need to have a discussion with the core web team to coordinate that.

For now, it might make sense to just remove it to avoid confusion, since the behavior when selecting either template or manual product creation is now essentially the same.
