### ISSUE TITLE
[Hub Menu] Customers: Add UI to display customer details

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#12334]
Tapping on a customer should open a detail view.

Note: This screen is read-only for now. We can show an email icon next to the customer’s email address, which allows the merchant to contact them (like in order details).

![image](https://github.com/woocommerce/woocommerce-ios/assets/8658164/71ce08c3-c79a-420d-bb59-98871610d9b4)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
