### ISSUE TITLE
Undo Notice Not Displayed on iPad Simulator After Trashing Order

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#12335]
An issue was found during the review of PR #12317 where the undo notice does not appear on the iPad simulator after an order is moved to the trash.

### Steps to Reproduce
1. Run the app on the iPad simulator.
2. Go to the Order Detail page and move an order to the trash.
3. Observe that the undo notice is not displayed.

### Expected Behavior
An undo notice should be displayed allowing the user to restore the order from the trash.

### Video
https://github.com/woocommerce/woocommerce-ios/assets/524475/ec09eb45-fca9-4a99-af95-67272ce054bc

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by bozidarsevo** [comment]
Problem is that self is nil when `self?.displayOrderTrashUndoNotice` is being called. I will work on it now to either present it on the list of orders or the child screen
