### ISSUE TITLE
Cash Orders with empty Payment Method

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-ios#12347]
**Describe the bug**
The mobile apps leave the `payment_method` and `payment_method_title` fields empty when the payment is collected in cash.

I checked the code, and the app updates only the status of the order to Completed, leaving the `payment_method` and `payment_method_title` fields empty.

**To Reproduce**
1. Create an order in the app
2. Open detail of the order
3. Tap on 'Collect Payment'
4. Select Cash
5. Confirm
6. Notice the order is marked as completed, but the payment_method and payment_method_title are empty (not visible on the UI in the app

**Screenshots**
<img src="https://github.com/woocommerce/woocommerce-android/assets/2261188/b6a14e14-9f25-4b8e-904d-58e2c6301008" width="150" />

**Expected behavior**

<img src="https://github.com/woocommerce/woocommerce-android/assets/2261188/dcb3a4ff-46f4-46e4-bd95-30ded7444a11" width="150" />

**Proposal**
When the user selects Cash on the Payment Selection screen, the apps should update:

- `status` to `completed`
- `payment_method` to `cod`
- `payment_method_title` to `Pay in Person` (This could get tricky, since this title is customizable – .../wp-admin/admin.php?page=wc-settings&tab=checkout&section=cod. However, AFAICT the end-customers won’t see this value. I believe setting it to Pay in Person should be a good enough MVP.)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
