### ISSUE TITLE
[Hub Menu] Customers: Add analytics

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#12346]
We have an existing event `hub_menu_option_tapped` that will track when an item in the hub menu is tapped. We should ensure the `customers` option is tracked when Customers is tapped.

Other events to track:

* When the customer list is loaded: `customers_hub_loaded`
* If the customer list fails to load: `customers_hub_load_failed`
* When the customer list is searched: `customers_hub_customer_search`
   * Custom prop: `filter` with the selected search filter
* When a customer is tapped to open customer details: `customers_hub_customer_detail_open`
   * Custom prop: `registered` with whether the selected customer is registered (bool)
   * Custom prop: `has_email` with whether the selected customer has an email address (bool)
* When a customer is contacted via customer details:
   * Email menu opened: `customers_hub_customer_detail_email_menu_tapped`
   * Send email tapped: `customers_hub_customer_detail_email_option_tapped`
   * Copy email tapped: `customers_hub_customer_detail_email_copy_option_tapped`

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
