### ISSUE TITLE
Dynamic Dashboard

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-ios#12357]
```[tasklist]
### UI
- [ ] Task
```

```[tasklist]
### Backend
- [ ] Task
```
```[tasklist]
### Miscellaneous
- [ ] Add feature flag
- [ ] Feature announcement
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by itsmeichigo** [comment]
Oops I didn't know this was already created! Closing in favor of #12403.
