### ISSUE TITLE
Blaze: entry points should be visible only to users with `admin` role

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#12371]
It seems that Blaze entry points in the iOS app, are visible also to users who don't have the `admin` role in WooCommerce.
If you try to login in a store, with the "store manager" role, you can see that all the entry points are visible.

**Expected behavior**
Blaze should be hidden for users without the `admin` role. This current behavior it has been implemented on Android.

**Extra**
I also noticed a strange behavior.
If you login with a user with the `store manager` role, the appearance of the Blaze section in the "My store" tab is different. The button "Show all campaigns" is hidden.

| Admin role             |  Store Manager role |
:-------------------------:|:-------------------------:
![simulator_screenshot_1D422F0F-720C-4028-812E-6D9EE83E8B6C](https://github.com/woocommerce/woocommerce-ios/assets/495617/177239d0-22cd-468e-8b3e-2e1054fbee4c)  |  ![Simulator Screenshot - iPhone 15 Pro Max - 2024-03-26 at 18 07 42](https://github.com/woocommerce/woocommerce-ios/assets/495617/806b4f1c-ba9f-4578-a468-5ac3f9f5b140)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by itsmeichigo** [comment]
@pmusolino I can no longer reproduce this issue. Can you check again to see if it still happens to your store/account?

**Comment by pmusolino** [comment]
Closing it, I am no longer able to reproduce this issue either.
