### ISSUE TITLE
My Store Analytics: Incorrect visitor stats for 2-day date range.

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12397]
**Description**

Hicham found an issue with the current logic of treating the 2-day range as one:

> While working on updating the visitor’s count to use the summary stats endpoint for a better accuracy, I came upon an issue with our logic for calculating granularities.
For now, we assume that a range with 2 days (in the picker) is equivalent to a single day, while in reality, it’s not, both days are inclusive:
In Android, this is obvious, as the date range is [built](https://github.com/woocommerce/woocommerce-android/blob/3f409aace2e432c3ca6aef45007c22b1efdb7493/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/ranges/data/CustomRangeData.kt#L32-L36) in a way where the start date is at the begining of the day, and the end date is at the end of the day, which means two days of difference (and not one).
In iOS, this is less obvious, as the date range will still have only a day of difference between the end and the start, but before making the API call, we use the extensions [earliestDate](https://github.com/woocommerce/woocommerce-ios/blob/7d5fd4b9a83f5754a18ca3f959dd7cba89dfa1db/WooCommerce/Classes/ViewRelated/Dashboard/Stats%20v4/StatsTimeRangeV4%2BUI.swift#L68) and [latestDate](https://github.com/woocommerce/woocommerce-ios/blob/7d5fd4b9a83f5754a18ca3f959dd7cba89dfa1db/WooCommerce/Classes/ViewRelated/Dashboard/Stats%20v4/StatsTimeRangeV4%2BUI.swift#L48) to set the start to the beginning of day, and end to the end of day, which makes things equivalent to how Android behave.
Now this causes an issue when it comes to the visitor’s count, as we [decided](p1709800424149309/1709727324.356419-slack-C03L1NF1EA3) to show the count when a single day is selected, but when two days are selected, and because we assume it’s equivalent to a single day, we still show the count, but it’s a wrong count.

**Expectation**

We can just adjust the conditions of calculating the granularities to be as follow:
- hour when the range is 1 day or less.
- day when the range is between 1 and 28 days.
- … rest unchanged
Then hide the total visitor’s count for ranges of 2 days or more.
This change will also require modifying the date picker in iOS to allow selecting two same dates, I mean relaxing this [condition](https://github.com/woocommerce/woocommerce-ios/blob/7d5fd4b9a83f5754a18ca3f959dd7cba89dfa1db/WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI%20Components/RangedDatePicker.swift#L121-L124) to be less or equal.

Internal ref: p1711724047631339-slack-C03L1NF1EA3.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
