### ISSUE TITLE
Remove the onboarding task “Name your store”.

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12395]
<img src="https://github.com/woocommerce/woocommerce-ios/assets/524475/5afa48e7-b9e5-45b3-81f0-0b054313e28c" width="320"/>

Internal - p1711979433435969/1711976056.883349-slack-C03L1NF1EA3

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
