### ISSUE TITLE
Hide the "Subscriptions" screen for free trial sites.

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12390]
<img src="https://github.com/woocommerce/woocommerce-ios/assets/524475/fc1b23ec-a25b-4385-bdd5-887c0a6ecfa4" width="320"/>

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
