### ISSUE TITLE
Update prologue text

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12396]
On the prologue screen we have this text "Start with our 15-day free trial, no credit card needed. Join 3.4M stores thriving with Woo, from first sale to millions"

This should be replaced with "From your first sale to millions in revenue, Woo is with you. See why merchants trust us to power 3.4 million online stores".

Source: pe5sF9-2w9-p2#comment-3512

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
