### ISSUE TITLE
Make sure IAP users are still able to manage their subscriptions.

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#12393]
This is specifically for active sites.

Additional note:

- IAP purchase for upgrading Free trial site is removed on #12377 
- IAP purchase for expired ecommerce plan site should be removed, as per #12392

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by hafizrahman** [comment]
This is all good as far as I can check, we do not delete management for existing IAP users
