### ISSUE TITLE
Handling for expired WPCom sites

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#12392]
Slack conversation: p1711594560528569-slack-C03L1NF1EA3 

In `StorePickerViewController`, there is a function `displayExpiredWPComPlanAlert()` which includes plan purchase functionality for an expired plan WPCom site. Ideally we match the behavior in Android where that kind of site is not included inside the Site Picker, thus avoiding having to display the alert, and preventing users from repurchasing either from IAP or web.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by selanthiraiyan** [comment]
I think altering the behaviour of store picker is out of scope for this project. So, I added a simpler solution of changing the alert view in #12406

Internal discussion - p1712052066222499/1712027364.219649-slack-C03L1NF1EA3
