### ISSUE TITLE
Remove the logic of adding the “launch your store” task for free trial sites

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12394]
<img src="https://github.com/woocommerce/woocommerce-ios/assets/524475/c96738c0-6e18-4af4-ad7e-48435a778979" width="320"/>

Internal - p1711979433435969/1711976056.883349-slack-C03L1NF1EA3

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
