### ISSUE TITLE
New enum for dashboard cards and update dashboard controller accordingly

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12411]
Add a new enum for dashboard cards and create a SwiftUI version of the dashboard view controller to manage the UI more easily.

Checklist for dashboard view:

- [ ] Store name
- [ ] Tab bar item
- [ ] Share store
- [ ] Store stats and top performers
- [ ] Store onboarding
- [ ] Blaze
- [ ] Pull-to-refresh
- [ ] Top banner for error syncing
- [ ] JITM
- [ ] Bottom Jetpack benefit banner
- [ ] Announcements
- [ ] Web view sheet
- [ ] Store plan banner
- [ ] Privacy banner

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
