### ISSUE TITLE
Subscription status section disappears once an order is marked as completed, despite subscription being active

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12410]
Order status and subscription status should be somewhat independent once payment has been collected and a subscription is active. However, when we switch the order status to `Completed` in the app, the `Subscription Status` section disappears:

| Processing Order with active subs | Completed Order with active subs |
|--------|--------|
| ![simulator_screenshot_F7C6514F-5B86-4DB1-8E36-4769996759C3](https://github.com/woocommerce/woocommerce-ios/assets/3812076/0020aa84-9ec7-4dfd-9987-314a9ce88181) | ![simulator_screenshot_B287CDD8-F335-4DC5-96A2-21A9F38B3B05](https://github.com/woocommerce/woocommerce-ios/assets/3812076/4ff33c2c-943c-4aca-bdd5-597e21769099) | 

We should keep the section since we need to keep informing of the subscription status independently of the order.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
@iamgabrielma Are you sure the subscriptions section isn't there? I checked and couldn't reproduce this, and in your second screenshot (completed order) I'd expect to see the subscriptions section lower down on the screen.

The subscriptions are synced when all the order data is synced (in `OrderDetailsViewModel.syncEverything()`) so I'm not sure what steps would make it not appear, unless the remote request for the subscription data failed.

**Comment by iamgabrielma** [comment]
Thanks for testing this @rachelmcr . I cannot seem to replicate it either now that I try with a new order, so most likely was my mistake when testing these through the web and app:

- When I check the original order I created for the 2nd screenshot (`2466`) in wp-admin  I cannot see any subscription relationship attached to it.
- The order attribution origin is `mobile app`, so if I attempted to process the subscription through it it wouldn't work (expected, since we do not support them yet)

I'll close this one for the time being and keep an eye on it, I'll also add an item to test this behaviour once subscription support is added.
