### ISSUE TITLE
[Login] Enable site credentials login

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12428]
#### Problem 

> We’ve had numerous issues where users have their store connected to Jetpack, but can’t log in, because they do not own/have the WP.com credentials needed to log in to the Jetpack connected site. However, sometimes they do have the wp-admin credentials at hand, so this change enables them to use their site’s credentials as a login fallback:

Internal - pe5sF9-2zh-p2#comment-3519
Android issue - https://github.com/woocommerce/woocommerce-android/issues/10989

#### Fix

Allow users to login into a store using their wporg site credentials even if their store is connected to Jetpack.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
