### ISSUE TITLE
Migration back to woocommerce.com

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#12430]
**Description**
It has been decided to migrate back from woo.com to woocommerce.com. For this reason, we should update the URLs in the app to point to the new domain, rather than go through the redirect.

More info here: peaMlT-w5
Old PR: https://github.com/woocommerce/woocommerce-ios/pull/11182

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
