### ISSUE TITLE
[SiOC 3] Order details: Update product rows to display subscription details

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12441]
Suggested design vs current implementation:

<img width="1034" alt="20240424 subs section design vs app" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/557fbe0c-e6d8-436d-82a3-7cc88d339d6b">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
