### ISSUE TITLE
Code Cleanup for WooExpress signup

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#12442]
A non-exhaustive list of part of the code that could be deleted as part of this task.

```[tasklist]
### Tasks
- [ ] Functionality code related to store creation flow from prologue
- [ ] Code related to `onUpgradePlan` in `StoreOnboardingCoordinator`
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
