### ISSUE TITLE
Rewrite Store Stats card in SwiftUI following new design

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12465]
<img width="498" alt="image" src="https://github.com/woocommerce/woocommerce-ios/assets/5533851/046f00e6-406f-4242-9bce-bb9bbdd5b079">

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
