### ISSUE TITLE
Save and retrieve dashboard card orders

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12461]
> Saving and retrieving cards with local storage should be straightforward, but there are some complications around switching from user defaults for the onboarding and Blaze cards. If you have some time tomorrow, I'd really appreciate your help with that.

> We might want to retrieve the setting from user defaults the first time and not save any update to user defaults again if the user hides either of the cards.

- [ ] Store and retrieve dashboard order from AppSettings #12480
- [ ] Remove Store Setup List" from "Settings" to avoid conflicts #12480

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
