### ISSUE TITLE
[Blaze] Inform/Validate expected image size

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12463]
Currently, Blaze Ads supports images of 500 x 500px. If the image is larger, the backend will center-crop it to make it 500x500px. But if the image is smaller, then apparently, we get an error.

Error response
```
Error creating Blaze campaign: Sorry, there was an issue with the server. Please try again later. (Error code: 422). Response: {"message":"Validation failed","details":{"main_image":{"message":"Insufficient image size for cropping"}}}
```

Internal - p1712592228577439-slack-C6H8C3G23

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
