### ISSUE TITLE
New Billing Information screen: analytics event no longer needed

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#1246]
Since on iOS, the new Billing Information is in a separated screen, and no longer within a cascade menu (unlike Android), one of these events is no longer needed.

```
order_detail_customer_info_show_billing_tapped
order_detail_customer_info_hide_billing_tapped
```

In particular, I'm talking about the event `order_detail_customer_info_hide_billing_tapped `. This event no longer makes sense to be sent, since information is grouped in a new screen. 

The event `order_detail_customer_info_show_billing_tapped` will continue to be sent when a user taps on the button which opens the new billing information screen.

I proposed this changes in this PR: https://github.com/woocommerce/woocommerce-ios/pull/1244

### There are the differences on Billing Information between iOS and Android. iOS before this iteration, was like Android.

| iOS             |  Android |
:-------------------------:|:-------------------------:
![63865993-d36cdf00-c9b2-11e9-8d9e-e39d24e393d0](https://user-images.githubusercontent.com/495617/63927323-bf29f000-ca4d-11e9-9bfe-6b08f2afca45.png) | ![63597540-f9af0b00-c5bd-11e9-975c-e51b8b5870a0](https://user-images.githubusercontent.com/495617/63927332-c4873a80-ca4d-11e9-94ba-b38c775ad501.gif)

**Comment by ctarda** [comment]
Implemented in #1244
