### ISSUE TITLE
[Product Creation AI] Use `response_format` parameter to receive JSON

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12462]
### Problem

For the Product creation AI feature, we expect a JSON response from the `text-completion` endpoint. Sometimes, we receive an invalid JSON response. 

### Solution

Send `json_object` as a value for the `response_format` parameter to always receive JSON response. 

Internal - p1712673057952299/1712665486.827879-slack-C03L1NF1EA3

Tasks
- [x] Use response format parameter while generating product name and description in package flow #12466
- [ ] Use response format parameter while generating product details in AI flow https://github.com/woocommerce/woocommerce-ios/pull/13146

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
