### ISSUE TITLE
[Subscriptions in Order Creation 3] Handle zero case

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12471]
Follow-up from https://github.com/woocommerce/woocommerce-ios/pull/12447#pullrequestreview-1993198642

Update:

> Nil, empty, zero: Is possible to enter 0 in some of the fields (like signup fees) and we'll have a response that the subscription now contains a fee, despite the fee being zero and not applicable. The same for empty values, we may get non-nil empty values that we cannot use. By checking how core deals with it, they just seem to not show it at all if are zero, so we could take the same approach.

We want to handle the empty and zero cases in a way that does not display in the UI, only values >0 should show sign up fees.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
