### ISSUE TITLE
Unable to Reset Activity Log from Help Section

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#12478]
When navigating to the "Help" section of the application and selecting "View Application log," there is an issue with the "Reset Activity log" button. Upon tapping the button, it only displays an arrow on the right side but fails to perform any action. The expected behavior of clearing the log files does not occur, and the log files remain unchanged.

After some investigations, it seems that the action deletes only the "archived" logs, which means all the previous days, but not the current day. So, if it's the first time a user opens the app, they will not see any effect by pressing the button, and also we don't ask to delete only archived logs, we should delete all the logs.

### Steps to Reproduce

1. Open the application.
2. Go to the "Help" section.
3. Tap on "View Application log."
4. Press the "Reset Activity log" button.

### Expected Behavior

When the "Reset Activity log" button is pressed, all the current log files (including the current day) should be cleared, and the activity log should be reset.

### Video

<img src="https://github.com/woocommerce/woocommerce-ios/assets/495617/dffe0c51-fb4e-4618-9882-76bafbac617a" width=300 />

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by pmusolino** [comment]
Noticed also that the current version of CocoaLumberjack library is 3.7.4, while the last version available right now is 3.8.5.
