### ISSUE TITLE
Update layout for Blaze card

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#12488]

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by hafizrahman** [comment]
New change needed:

<img width="583" alt="Screenshot 2024-04-29 at 09 20 13" src="https://github.com/woocommerce/woocommerce-ios/assets/266376/eabc1771-9a8c-4278-b25d-b0ce576c7f2c">
