### ISSUE TITLE
Reset Stored products when switching stores

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#1248]
We reset a bunch of locally cached content when users either log out of switch store, on `StorePickerCoordinator.logOutOfCurrentStore`, like stats and orders.

However, we do not reset Products.

- [ ] Dispatch `ProductAction.resetStoredProducts` when switching stores, to reset the local Product cache

**Comment by mindgraffiti** [comment]
Closing. GH automation fail
