### ISSUE TITLE
Typo in System Status Report generated by the app

### ISSUE THREAD

**Issue by AashikP** [woocommerce/woocommerce-ios#12482]
**Describe the bug**
`WordPress addresss (URL):` should be `WordPress address (URL):` [here](https://github.com/woocommerce/woocommerce-ios/blob/80451ed5f41bc5803e43f68ecf1ea51ac854b5ae/WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/SystemStatusReport/SystemStatusReportViewModel.swift#L54)

**To Reproduce**
1. Submit a Support request from the App
2. Find `WordPress addresss (URL):` instead of `WordPress address (URL):` in Zendesk

**Screenshots**

<img width="299" alt="image" src="https://github.com/woocommerce/woocommerce-ios/assets/17475174/f7641ea4-f3b3-498b-be6a-4a751b2e6706">

**Expected behavior**
Fix the typo.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
N/A

**Additional Details**

_Example ticket:_ 8039541-zen

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
