### ISSUE TITLE
Implement ALIterativeMigrator

### ISSUE THREAD

**Issue by jleandroperez** [woocommerce/woocommerce-ios#125]
### Details:
In WPiOS we've experienced, a while ago, a huge issue related to Core Data Migrations, which involved users coming from older DB schemas (N - 2 at least). More about this issue [here](https://github.com/wordpress-mobile/WordPress-iOS/issues/2357).

The solution consisted on implementing [ALIterativeMigrator](https://github.com/noahmiller/IterativeMigration).

- Analyze if the latest CoreData Stack *needs* this kind of process
- If not, analyze if there's a newer tool that does the same thing
- And... if not... just implement ALIterativeMigrator (which has a quite old codebase!).

**Comment by astralbodies** [comment]
Closed by f3e4ac7
