### ISSUE TITLE
Introduce Order details fetching logic

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-ios#12502]
From the Orders list screen, when the user selects one of the orders there, we should be able to present the details for that giving order.

This task should introduce the Order Details fetching logic, which allows the user to scroll and navigate through the order data.

Depending on the fetch strategy used in the Orders list (list summary for performance), the required data for the Order details might be limited, requiring additional data fetching. If that's not the case, close and ignore this task.

![Image](https://github.com/woocommerce/woocommerce-android/assets/5920403/1ee6a1d6-e204-4e60-925a-fd21b348ac4c)

```[tasklist]
### Tasks
- [x] Fetch all order data
- [x] Update the Order Details screen with the sections introduced in #12501
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by Ecarrion** [comment]
Closing as this did not required any extra data fetching
