### ISSUE TITLE
Introduce Order list fetching logic

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-ios#12500]
From the My Store screen, when the user clicks the `View all orders` button, we should be able to present an Order list displaying all orders from that given store.

This task should introduce the Order List fetching logic, allowing the user to scroll and navigate between the store order data.

Data fetching can be done by requesting it from the phone app or using the watch network to request it when possible.

![Image](https://github.com/woocommerce/woocommerce-android/assets/5920403/32d5ef9a-379d-4684-85e5-cdae17afa0ac)

```[tasklist]
### Tasks
- [x] Update and present the Orders data to the Orders list
- [x] Format the incoming Orders data for presentation (e.g. Creation date, Totals currency)
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
