### ISSUE TITLE
Add Share store card

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#12508]
![Screenshot 2024-04-18 at 19 45 45](https://github.com/woocommerce/woocommerce-ios/assets/266376/18307035-ccd6-450b-9bdb-ec94f4f9c30c)

Shown on new store.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by hafizrahman** [comment]
Remaining tasks (see p1714012612110229/1713795116.897069-slack-C03L1NF1EA3)
- for performance and top performers card, when not available, set as unavailable in Customize
- for blaze and onboarding card, when not available, hide them
- take into account locally saved card setting when updating card availability above
 
-
