### ISSUE TITLE
Increase tap target to entire row when showing "Explore" button for inactive extensions

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#12509]
In the Analytics Hub customize screen and the Products tab product type filter, we show an "Explore" button if a supported extension is not active on the store.

Currently, only the button itself is interactive. We'd like to increase the tap target to the entire row.

Discussion: pe5pgL-4wy-p2#comment-3903

Analytics Hub|Products tab filter
-|-
![image](https://github.com/woocommerce/woocommerce-ios/assets/8658164/23ea1d89-c34a-4e27-8f27-8e97c3f43aec)|![image](https://github.com/woocommerce/woocommerce-ios/assets/8658164/31708abc-db4d-4699-a935-2a415b11ae81)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
