### ISSUE TITLE
[Subscriptions in Order Creation 3] Handle on sale pricing

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12516]
Incorrect price shown (regular price) when collapsible cards, and product selector.

From testing: pdfdoF-4Un-p2#comment-6090

<img width="591" alt="Screenshot 2024-04-19 at 08 53 45" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/53980431-7201-43e4-9b57-d0fbe9fc5af7">

This is already handled in the Products tab by showing both regular and sale price:
<img width=450 src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/9b28bbab-ab64-4a9d-84b7-f33e376feb37"/>

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
Handled via product cards update.
