### ISSUE TITLE
Update header for the Dashboard screen

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12517]
<img width="541" alt="image" src="https://github.com/woocommerce/woocommerce-ios/assets/5533851/b17c7026-3cf6-4fbe-b956-9f834e50bee0">

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
