### ISSUE TITLE
Card title should not shimmer during loading state

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#12511]
During pull-to-refresh on dashboard, notice how the "Store Setup" title of the old design card remains visible during loading animation. Meanwhile, the new cards add shimmer to the titles, too.

I think it's better if the new cards keep showing the title: it gives better clarity to the users what items are currently loading, and in a sense help them not feel "lost" with the UI change.

https://github.com/woocommerce/woocommerce-ios/assets/266376/a749409b-cbd1-4254-b6b3-2fdbd7bbdec0

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
