### ISSUE TITLE
Remove unavailable cards from Customize screen

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12526]
Unavailable cards should be hidden from Customize screen following this thread: pe5sF9-2DL-p2#comment-3573.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by hafizrahman** [comment]
Updated tasks (see p1714012612110229/1713795116.897069-slack-C03L1NF1EA3)
- for performance and top performers card, when not available, set as unavailable in Customize
- for blaze and onboarding card, when not available, hide them
- take into account locally saved card setting when updating card availability above
