### ISSUE TITLE
Update UI for custom range

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12525]
- Show date range as a button to open the date picker.
- Rename "Custom Range" text to "Custom".
- Show selected date on top of the revenue (center-aligned).

<img width="307" alt="image" src="https://github.com/woocommerce/woocommerce-ios/assets/5533851/ccda0917-eac7-4c46-96bf-01cf2523bb48">

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
