### ISSUE TITLE
Blaze i3 Quick Enhancements

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12539]
Clone of Android issue - https://github.com/woocommerce/woocommerce-android/issues/11321

After the user flow review session, a lot of good feedback came up. Full context here: pe5sF9-2Bb-p2

This issue summarizes a list of small changes that can be applied to the flow and that might have a significant impact. 
Bigger effort changes have been added to other GH issues and will be deferred to Blaze i4 Project. 

The small task added to this GHG issue can be tackled bit by bit while we work on other projects. We don't plan to allocate specific team effort for these as they should be 1h-2h changes at most. 

```[tasklist]
### Quick Enhancements
- [x] Intro screen small changes: Remove purple flames, explain what the $5 USD budget is (daily,weekly,total, etc)
- [x] Preview Screen: Add a new copy below the budget section: `Audience`.
- [x] Preview Screen: Add a label on the ad preview specifying if the used content for the ad was generated by AI. Hide this label as soon as the user edits the content manually
- [x] Small redesign to the Blaze view inside My Store tab: Thd2rdNU8zSaLkyKZGsOSn-fi-77_29558 This will be tackled as part of the dynamic dashboard project
- [x] Align Blaze statuses in all platforms. Both iOS and Android should have the exact same statuses as the web displays.
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by pmusolino** [comment]
> My Store Blaze view with campaigns: Hide the `Show All` button if there's only one Blaze campaign created. User can click on the campaign row item if they want to open the one and only existing campaign.

Removed this task, since it was already implemented.
