### ISSUE TITLE
Fix issue displaying values on the store stat chart's x-axis legend for custom range

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12531]
We are using a fixed value 5 for store stat chart's `xAxisStrideCount` when the time range is custom range. This doesn't work when there are not enough values to display, and the chart will not show extra values:

<img src="https://github.com/woocommerce/woocommerce-ios/assets/5533851/a3a3347b-2ceb-4c53-9617-8a562abb58f6" width=320 />

The solution should be to calculate the number of items to be displayed based on the day difference and granularity, and if the result is larger than 5, we display 5 items.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
