### ISSUE TITLE
Update UI tests for dynamic dashboard 

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12530]
Currently we're disabling 2 UI tests: `test_load_stats_screen` and `test_view_detailed_chart_stats` due to the change of the UI on the dashboard.

We can try to update the tests to verify the behavior of the Performance card when switching between time ranges and tapping on the chart. The idea is to compensate for the disabled tests for now.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
