### ISSUE TITLE
Analytics view does not allow one day "range" 

### ISSUE THREAD

**Issue by rossanafmenezes** [woocommerce/woocommerce-ios#12532]
**Describe the bug**
If you go to the app stats, select the custom range option and choose the start and end date to be the same (use-case would be to check the stats for one specific day only that it's not the current date) you get an error saying `invalid date range` 

**To Reproduce**
1. In the my store tab go to the custom range option for the stats
2. Select the same date for start and end date, let's say April 15th
3. See the error

**Screenshots**
If applicable, add screenshots to help explain your problem
.
| iOS | Android |
| ---- | ---- |
| <img src="https://github.com/woocommerce/woocommerce-ios/assets/30724184/7e124661-d19d-4d52-b522-0464b3f0d412" width="350"/> | <img src="https://github.com/woocommerce/woocommerce-ios/assets/30724184/f1350953-8ba3-4a93-b8bb-13e2dfec661a" width="350"/> |

**Expected behavior**

Just like the Android app, I would expect to be possible to select a one-day range

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by rossanafmenezes** [comment]
Closing as this has been fixed on 18.3
