### ISSUE TITLE
Allow hidden analytics cards (in the case of site with no orders) to be enabled and customized

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#12535]
In the case where the "Share Your Store" card is shown, analytics cards are hidden.

However, we want to allow those cards to be visible and can be enabled in the Customisation screen.

When they are enabled, they will be shown using the empty state.

![image](https://github.com/woocommerce/woocommerce-ios/assets/266376/55da3fea-d298-49bd-ba25-625479e3a56b)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by hafizrahman** [comment]
For now, we decided to go with this solution:

> when the store has no orders, mark the performance cards as unavailable, and replace them with the "share your store" card, the performance cards won't be available to add until the site has some orders, which also matches the current behavior today where the empty view replaces the stats and top performers sections.

(convo: p1713856584270409/1713795116.897069-slack-C03L1NF1EA3)

This behavior already exists in #12521, so we can close this for now.
