### ISSUE TITLE
Update the ellipsis button behavior to open the Customize screen

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12548]
Internal - p1713495594539859-slack-C03L1NF1EA3

To prevent the user from dismissing all cards from the dashboard using the ellipsis menu of a card we decided to present the customization screen from the ellipsis menu. This change also makes the customization screen more discoverable.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
