### ISSUE TITLE
Menu: collect payment quick action or deeplink opens an empty view

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12542]
**Describe the bug**

If the merchant is not in Menu > Payments, tapping on a collect payment quick action or deeplink opens an empty view instead of the order form with a custom amount modal.

**To Reproduce**

- Open the app
- Log in to a store if needed
- Tap on `Collect payment` quick action (long press on the app icon) or a deeplink like `http://woo.com/mobile/payments/collect-payment` --> notice that an empty view is shown instead of the order form

**Screenshots**

https://github.com/woocommerce/woocommerce-ios/assets/1945542/7a5b23fc-bed9-4812-a9e8-350e19bb380d

**Expected behavior**

Order form should be shown with the custom amount modal, like tapping Menu > Payments > Collect Payment.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: iOS 17
- WooCommerce iOS version: 18.3

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
