### ISSUE TITLE
[Order Creation] Scanning a barcode for a product variation's parent product adds it to the order

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#12566]
When you scan a barcode for a parent product, it gets added to the order – not a variation.

Parent products of variations can't be directly purchased via the web, or in the apps using order creation.

Tapping the parent product in order creation the app opens the variation selector, and allows you to select a variation.

I'm not aware of any valid case for adding a parent product to an order.

On Android, we show a notice to alert users that this isn't possible.
![Screenshot_20240424-151136~2](https://github.com/woocommerce/woocommerce-ios/assets/2472348/89d81c60-9af7-48e8-8971-9023f1e13db6)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
