### ISSUE TITLE
[Order Creation] Barcode scan button on Order List can get stuck as a spinner

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#12568]
## Repro
1. Launch the app
2. Tap Orders
3. Tap scan
4. Scan a barcode linked to a product
5. Cancel the order creation which is shown
6. Observe that the barcode button sometimes still shows a spinner, when it should return to a button.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
