### ISSUE TITLE
[Order Creation] Sometimes scanning a variation's barcode adds it to the order without the right image or full details

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#12567]
## Repro
1. Delete the app from your phone (to ensure the data store is empty)
2. Launch the app and log in to a store with variations, already linked to a barcode you can scan
3. Tap the orders tab
4. Tap the barcode button
5. Scan the barcode
6. Observe that the variation is added, but sometimes does not show the correct image or full details in the subtitle.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
I've retested this, and can't actually reproduce it.

I think I was confused because of some product setup issues, where the wrong images were set for some variations I was scanning.

Closing as not needed.
