### ISSUE TITLE
[Subscriptions in Order Creation 3] Update sign-up fees when quantity > 1

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12564]
Raised on p1714040401021719-slack-C025A8VV728

Sign-up fees are not multiplied by the subscription quantity, they're aded only once to the order per product. We can duplicate the price x quantity design here:

<img width="414" alt="Screenshot 2024-04-25 at 19 09 26" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/48beed85-2700-47af-8261-f2547cf59a4b">

This is computed on `CollapsibleProductRowCardViewModel.subscriptionConditionsSignupFee`, and rendered in `CollapsibleProductRowCard`View. We can use the same approach as with subscription prices:

```
        // Multiply price per unit by the currently selected quantity
        let quantity = stepperViewModel.quantity
        guard let decimalPrice = currencyFormatter.convertToDecimal(pricePerUnit)?.decimalValue,
              let stringTotal = currencyFormatter.formatHumanReadableAmount(decimalPrice * quantity) else {
            return nil
        }

        let formattedPrice = currencyFormatter.formatAmount(stringTotal)
        return formattedPrice
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
