### ISSUE TITLE
UI to support shipping method selection

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-ios#12578]
This task is to update the current UI of how we add shipping lines to an order.

We should:

- [x] Create a new Select shipping method screen
- [x] Update the current Add shipping screen to  match the new style of the amount and name fields
- [x] Update the current Add shipping screen to add the method field
- [x] When pressing the method field navigate to the Select shipping method
- [x] When selecting  a shipping method in the Select shipping method screen navigate back to the Add shipping screen and update the Method field with the selected shipping method
- [x] When the Add Shipping button is pressed, then navigate back to the Create/Edit order screen and add that shipping line to the order
- [x] Sync and load available shipping methods from remote/storage (connect UI with Yosemite changes)
- [x] Verify that the [order_shipping_method_add](https://href.li/?https://mc.a8c.com/tracks/events/event.php?eventname=woocommerceios_order_shipping_method_add) is triggered when a shipping line is added to the order

![Image](https://github.com/woocommerce/woocommerce-android/assets/18119390/72347205-9aeb-4601-90fb-c94cbd14b2bc)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
