### ISSUE TITLE
UI for the new Shipping survey

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-ios#12585]
This task is to display the new shipping survey

Guidelines:
* Show the banner above the total section – but we should auto-close the total section when the “Add shipping” sheet is shown.
* Use this banner styling (font sizes, spacing, corner radius, colors, etc.): 

Portrait|Landscape/Tablet
-|-
![Image](https://github.com/woocommerce/woocommerce-ios/assets/8658164/85180cad-1bad-498c-95df-e8018578092d)|![Image](https://github.com/woocommerce/woocommerce-ios/assets/8658164/38ea5ca8-e9f4-4693-8c28-bfcdc90084a1)

Shipping banner (content):

![Image](https://github.com/woocommerce/woocommerce-ios/assets/8658164/d5c6ba8c-c775-4a89-9a08-dbbedcd7080d)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
