### ISSUE TITLE
Add shipping methods tracks

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-ios#12580]
#### Primary metrics

- [ ] Update `order_shipping_method_add`. Update the event with the custom property `shipping_method` containing the id of the selected shipping method in lowercase (`ups`|`flat_rate`|`free_shipping`…)

#### Secondary metrics

- [ ] Add `order_shipping_method_selected`. Add the new analytics event that should be triggered every time a merchant selects a new shipping method. This event will contain a custom property `shipping_method` with the id of the selected shipping method in lowercase (`ups`|`flat_rate`|`free_shipping`…)
- [ ] Add the `order_add_shipping_tapped`. Add the new analytics event that should be triggered every time a merchant taps on the add shipping button.

More context about the events pe5pgL-4Za-p2#comment-3977

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
