### ISSUE TITLE
UI to display multiple shipping lines Order Create/Edit

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-ios#12581]
This task is about to updating the UI to being able to display multiple shipping lines.

We should:

- [x] Display the order's shipping lines in a list inside the shipping card
- [x] Add a pencil icon at the end edge of the list item to indicate that the item is editable. Pressing on the item should navigate to the Shipping screen with the selected shipping values.
- [x] Add a shipping total section to the expandable order total section with the displaying the total shipping cost (sum of each individual shipping line)

![Image](https://github.com/woocommerce/woocommerce-android/assets/18119390/ba2b44c2-b132-4ca0-a1a3-e0796f919a84)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
@atorresveiga should we be using this design in the order create/edit form? (This matches the newer styling for products and custom amounts.)

From this discussion: p1714441191340599/1714158814.179029-slack-C02KUCFCSFP

![Image](https://github.com/woocommerce/woocommerce-ios/assets/8658164/9c245805-7712-4a79-b888-1d9c795eb6ea)

**Comment by rachelmcr** [comment]
Answered my own question. :) I confirmed we're using the second design in the Android implementation (https://github.com/woocommerce/woocommerce-android/pull/11571) so I'll go ahead with the same on iOS.

**Comment by rachelmcr** [comment]
Closing this task as done. I will handle the navigation to the Shipping screen as part of https://github.com/woocommerce/woocommerce-ios/issues/12583, so I can be sure to open and edit the right shipping line.
