### ISSUE TITLE
Add shipping methods tracks M2

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-ios#12584]
- [ ] Update the event `order_creation_success`. Update the event to include the custom property `shipping_lines_count` to track the number of shipping lines within that order
- [ ] Update the event `order_shipping_method_add`. Update the event to include the custom property `shipping_lines_count` to track the number of shipping lines within that order
- [ ] Add a new event `order_details_shipping_methods_shown`. Update the event to include the custom property `shipping_lines_count` to track the number of shipping lines within that order

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
