### ISSUE TITLE
Privacy banner has extra empty space on iPad

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#12603]
**Description**

Content in the privacy banner is pushed to the top so there is a lot of empty space in the banner itself

**Screenshots**

![image](https://github.com/woocommerce/woocommerce-ios/assets/6242034/5d0b4873-b235-404f-a53b-ef79ae306b88)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
