### ISSUE TITLE
Add feedback banner for rating the app

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12600]
- Check with local storage if the banner should be displayed using `AppGeneralAction.loadFeedbackVisibility` (following the logic [here](https://github.com/woocommerce/woocommerce-ios/blob/trunk/WooCommerce/Classes/ViewRelated/Dashboard/Stats%20v4/StoreStatsAndTopPerformersPeriodViewModel.swift))
- Display the banner if needed in the 2nd place on the dashboard.
- Rebuild the banner or embed `InAppFeedbackCardViewController` depending on complexity.

Internal - p1714408022255559/1712135440.001229-slack-C03L1NF1EA3

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
