### ISSUE TITLE
[Migrate simple payments] Payments > About TTP: update copy & align text

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12608]
Ref p1714383172408719-slack-C06C3CZFHGD

For the existing About Tap To Pay screen:

<img src="https://github.com/woocommerce/woocommerce-ios/assets/1945542/8c210613-6d32-4b35-bef8-d1915c078a22" width="300" />

We'd like to:

- Update the first point to remove "or collect a payment"
- Align the main text and the footer

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
