### ISSUE TITLE
Log available memory upon receiving memory warning

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12606]
> we can use [os_proc_available_memory](https://href.li/?https://developer.apple.com/documentation/os/3191911-os_proc_available_memory) to track the amount of memory available to our app, and we can do it when we receive a memory warning, e.g. in [applicationDidReceiveMemoryWarning](https://href.li/?https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623063-applicationdidreceivememorywarni), ideally with the currently displayed view. That way we could know if we are actually getting memory issues, where, and how much memory we still have available. We can iterate in the future to add more information. 

Internal - peaMlT-zd-p2#comment-1388

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
