### ISSUE TITLE
Order form: quantity badge text in the product card is not very readable in dark mode

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12628]
**Describe the bug**

When in dark mode, the quantity text in the product card isn't very legible in dark gray.

**To Reproduce**

- Turn the device to dark mode if needed
- Go to the orders tab
- Tap on an order with at least one product > Edit, or create an order and add at least one product --> the text in the quantity badge isn't legible

**Screenshots**

<img src="https://github.com/woocommerce/woocommerce-ios/assets/1945542/2ca9b6e2-a3eb-40ce-911f-e28d76343c1b" width="300" />

**Expected behavior**

The quantity text should have enough contrast against the background color to be readable.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: iOS 17
- WooCommerce iOS version: 18.4

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
