### ISSUE TITLE
Create a collapsable view similar to the product card in order form, and show it when tapping on the `Add Customer` CTA or when some customer details are already set

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12623]
- [x] Extract the collapsible card from product card to be reusable in the order form https://github.com/woocommerce/woocommerce-ios/pull/12627
- [x] Create a collapsible customer card https://github.com/woocommerce/woocommerce-ios/pull/12650

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
