### ISSUE TITLE
[Blaze] AI suggestion generation fails for atomic sites

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12638]
### Problem
For atomic stores during Blaze campaign creation the suggestions for ad tagline and description doesn't work. 

It happens because `https://public-api.wordpress.com/wpcom/v2/sites/155791504/wordads/dsp/api/v1.1/suggestions` endpoint returns the following error for an atomic site. 

```
{
  "message": "Unexpected Server Error",
  "errorMessage": "AxiosError: Request failed with status code 500"
}
```

### Possible solution
Switch to `https://public-api.wordpress.com/wpcom/v2/sites/123/wordads/dsp/api/v1/templates/advise/campaign/urn:wpcom:post:1234:123` for generating AI suggestions.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by selanthiraiyan** [comment]
I have started an internal discussion to check whether we can switch to the new `advise` endpoint. 

Internal - p1714635882048799-slack-C069RG07W6S

**Comment by selanthiraiyan** [comment]
The AI suggestion generation failed because of unusual product title and description content. For example, one post had zeroes and ones as product description. For that product both `v1.1/suggestions` and `v1/templates/advise` endpoints failed. 

Also, the backend team confirmed that the mobile team should continue using the `v1.1` endpoint. 

Internal - p1714995359472079/1714635882.048799-slack-C069RG07W6S
