### ISSUE TITLE
Scrolling Issue Causes View to Bump to Top in Menu

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#12640]
On large devices, such as the iPhone Pro Max (but I believe it happens on every device), when scrolling down in the menu, the view unexpectedly jumps back to the top after half a second. This "bump" to the top of the view disrupts a little bit the user experience.

**Steps to Reproduce**
1. Open the app and tap on the Menu.
2. Scroll down on the menu.

**Expected Behavior**
The view should scroll smoothly, and the position should remain consistent after the user stops scrolling.

**Video**
<img src="https://github.com/woocommerce/woocommerce-ios/assets/495617/d2cdd670-db2e-486e-a184-05dfc5766e9d" width=300 />

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
