### ISSUE TITLE
Users Unable to Upload Product Images on iOS App if the store is private

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#12646]
**Problem**

We have been alerted to an issue where users are experiencing difficulties when attempting to upload product images through the Android app. On the Android side, the issue was identified as a problem with private sites blocking image uploads (see peaMlT-zw) even with the correct bearer token. Users were not informed of this limitation, leading to confusion and frustration. This happens just on WP.com sites, since on self-hosted store it's not possible to put a store in the "private" state.

**Impact**

Reports have surfaced both in app reviews and comments on GitHub for Android, highlighting the problem:

- "Great app overall, but image uploading from the device isn't working. Please address this. Even after the recent update, the issue persists, and notifications are also non-functional despite Jetpack being configured correctly." - App Review
- "Image uploads from the device still aren't possible on the app. Kindly resolve this." - App Review
- Several comments on GitHub Issue https://github.com/woocommerce/woocommerce-android/issues/10329 also mention similar problems.

**Next Step**

Given the parallel issue that was identified and resolved on the Android platform, I investigated this, and the iOS app faces a similar problem. We need to apply a fix similar to the one applied on Android here https://github.com/woocommerce/woocommerce-android/pull/11383

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
Have we confirmed with the systems team that this is the expected behavior? It sounds like changes to how media is being served from WordPress.com (p58i-gPS-p2) might have caused this as an unintended side effect, and it could be something we could resolve with them.

**Comment by pmusolino** [comment]
@rachelmcr After conducting some investigations and performing several tests, it appears that there is a potential method to visualize the images. However, this method requires cookie authentication and I'm uncertain if it's feasible with external libraries. I attempted to use the standard authentication method we employ for the REST API (by passing the `Authorization` token in the header), but it proved ineffective for this particular scenario. You can find more details here (we discussed this some days ago): C03L1NF1EA3/p1716899439315909
