### ISSUE TITLE
Crash when opening Help & Support

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12656]
**Steps to reproduce**
- Log in to the app.
- Switch to Menu tab > Settings > Help & Support.
- The app crashes.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by itsmeichigo** [comment]
Fixed in #12657
