### ISSUE TITLE
Integrate `GET wc-analytics/reports/coupons` endpoint

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12659]
<img src="https://github.com/woocommerce/woocommerce-ios/assets/524475/be106bbf-8ee6-4164-b85c-b17a4f91d86c" width="320">

Integrate `GET wc-analytics/reports/coupons` API to fetch information for the above coupons card

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
