### ISSUE TITLE
Dynamic Dashboard: Top Performers header area for custom range

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#12667]
Top performers header area for custom range needs to be made consistent with the Performance card:

- Has to say "Custom" instead of "Custom range"
- Date text needs to have a purple color instead of black
- Needs pencil icon
- Needs to be tappable to edit the range

Compare the two cards below:

<img src="https://github.com/woocommerce/woocommerce-ios/assets/266376/e0bbf3b0-7fcd-43ae-bf31-67d092bfe8d6" width="42%">

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
