### ISSUE TITLE
Date Mismatch in Performance Card of Dynamic Dashboard

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#12689]
I've encountered a date discrepancy issue within the performance card of the Dynamic Dashboard. When I use the custom range date picker to select a specific date, for example, the 15th of April, the date displayed on the card incorrectly shows the 16th of April. This seems to be a timezone-related problem, as I am currently in the GMT+2 timezone. The selected date should accurately reflect the date chosen in the picker, regardless of the user's local timezone. 
| Picker            |  Performance card |
:-------------------------:|:-------------------------:
![Simulator Screenshot - iPhone 15 Pro - 2024-05-08 at 13 11 31](https://github.com/woocommerce/woocommerce-ios/assets/495617/c23e4b5d-3a59-46fa-8065-b0c32b368bb4) | ![Simulator Screenshot - iPhone 15 Pro - 2024-05-08 at 13 10 49](https://github.com/woocommerce/woocommerce-ios/assets/495617/489c2c9b-40bb-4abd-9b40-f7a02ce7fec9)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by itsmeichigo** [comment]
@pmusolino I cannot reproduce this issue. Are you still seeing it? If yes, please also share the timezone of your test site that you have the problem with.

**Comment by pmusolino** [comment]
I'm not able to reproduce the issue anymore too. Closing it for the moment
