### ISSUE TITLE
Dynamic Dashboard: Improve performance for Performance card

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12680]
In `StorePerformanceViewModel` we are keeping `chartViewModel` a computed variable and access this from the SwiftUI view a few times, causing the view model to be initialized again a lot of times when rendering the card.

A log added to the chart view model's initializer can show that the view model is created 90-100 times upon the first rendering, and this continues to be increased when interacting with the chart.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
