### ISSUE TITLE
Handle WCAdmin availability errors and show custom error

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12698]
>  WCAdmin availability and impact on cards

> We will need to use many endpoints from the wc-admin module of Core, as we know the module can be disabled, and that’s why in the stats card, we have a special state for when it’s not available (we show the text Make sure you are running the latest version of WooCommerce on your site and that you have WooCommerce Admin activated.).
Should we have something similar for the other cards, or is the generic error state fine for this?

Handle the errors -> show a custom error when WooCommerce Analytics is disabled

Internal - p1715339779338609-slack-C03L1NF1EA3

- [x] Coupons card - Show content unavailable view #12755
- [x] Stock card #12803 
- [ ] Other cards consuming `wc-analytics` endpoint

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by itsmeichigo** [comment]
@selanthiraiyan AFAIK only stock card and coupon card uses `wc-analytics` endpoints. Are there any other cards? If not, please feel free to close this issue, thanks!
