### ISSUE TITLE
[Woo POS] UI: CurrencyFormatter usage

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12705]
UI-wise, we can start applying the different currencies via the existing `CurrencyFormatter`. While most of it is already in WooFoundation, there's some code and dependencies scattered through different frameworks. At the moment:

- WooFoundation: `CurrencyFormatter`
- WooFoundation: `CurrencySettings`
- WooFoundation: `CurrencyCode`
- WooFoundation: `CurrencyPosition` 
- Yosemite: `Order+CurrencyFormattedValues`
- WooCommerce: `CurrencyFormatterTests`

Regarding tests, should we duplicate those in the POS framework as well? I'm not quite sure the WooFoundation framework needs its own testing target for the moment but if we end splitting the `pos` then it could be the case.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by jaclync** [comment]
This task seems to be affected by the uncertainty of keeping POS in a framework pfoUAQ-EF-p2#comment-517.

**Comment by iamgabrielma** [comment]
Closed via #12819
