### ISSUE TITLE
[Woo POS] UI: Single source for semantic colours

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12702]
Ref: TfaZ4LUkEwEGrxfnEFzvJj-fi-6_1657

Ideally let's apply the colors from a common extension to `Color`, as we do through WooFoundation now for WooCommerce through `Color.withColorStudio()`.

From the current wireframes, we can use:
- Background: `rgba(11, 146, 213, 1)`
- Foreground: `rgba(89, 181, 227, 1)`
- Fields `rgba(142, 208, 240, 1)`
- Text `.white`

Let's keep in mind that all of those will have a dark mode counterpart as well.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
Done via https://github.com/woocommerce/woocommerce-ios/pull/12714
