### ISSUE TITLE
[Woo POS] UI: Product cards and product rows

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12706]
Ref: TfaZ4LUkEwEGrxfnEFzvJj-fi-6_1657

- **Product cards:** should contain product name, plus button, dynamic quantity.
- **Product rows:** should contain product name, remove button.

<img width="349" alt="Screenshot 2024-05-13 at 11 12 25" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/f8a67b50-37b9-4d60-8ebe-c579db0b621e">

Tying them together through a common simple observable on a shared view model could be part of this PR as well, or tackled separately.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
