### ISSUE TITLE
[Woo POS] UI/Navigation: Root navigation, exit POS mode, and handle app's main tab visibility

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12704]
The experimental entry point for POS currently works as a full-screen modal overlay, if we remove the modal behaviour, we inherit the app's top and bottom navigation.

A minimal navigation should tackle:
- POS dashboard shouldn't be a full-screen modal overlay (perhaps?)
- Add an exit POS button and behaviour
- Toggle bottom app's bar visibility (my home, orders, products, menu) on enter/exit POS mode.
- A root navigation stack or path for all subviews and navigation states

Additionally, from [a review](https://github.com/woocommerce/woocommerce-ios/pull/12700#discussion_r1598121899) on a different issue:

> it's tricky in push navigation when we can't easily hide the tab bar like in UIKit (the design prototype seems to use modal presentation for now but we can update it later). The only other potential workaround I found is [this SO answer](https://stackoverflow.com/a/65058993/9185596), but I haven't tried it and we can revisit the workarounds when we're more sure about the UX.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by jaclync** [comment]
> POS dashboard shouldn't be a full-screen modal overlay

Does this mean that the POS dashboard should be presented in pushed navigation instead of a modal, while still being fullscreen? At first I thought we didn't want this view to be fullscreen, so just clarifying.

---

Also it looks like it's implemented in https://github.com/woocommerce/woocommerce-ios/pull/12700?

**Comment by iamgabrielma** [comment]
> Does this mean that the POS dashboard should be presented in pushed navigation instead of a modal, while still being fullscreen? At first I thought we didn't want this view to be fullscreen, so just clarifying.

That's my understanding: The POS dashboard should have no reference to the WooCommerce app navigation, the only connection through navigation should be the entry point and the "Exit POS" button, and should be full-screen from what I see on the wireframes (so no common top or bottom navigation). 

> Also it looks like it's implemented in https://github.com/woocommerce/woocommerce-ios/pull/12700?

Yeah, I'm not sure if there are better solutions of what I propose on that PR. Ideally after that we could use a `NavigationPath` since has type-erasure and we only need the destination views to be hashable for it to work, or a `NavigationStack`

**Comment by iamgabrielma** [comment]
Closing as part of https://github.com/woocommerce/woocommerce-ios/pull/12700
