### ISSUE TITLE
New cards availability. Suggestion card and "Edit" button dot

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12708]
> Default visibility [p1715271583741779-slack-C03L1NF1EA3]:
Let’s keep M1 cards as default and M2 cards as disabled after login/new installs.
Make new cards discoverable by adding a dot to the Edit button and an extra card at the bottom for the suggestion. We can use UserDefaults (iOS) and Preferences (Android) to display the suggestion only once.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by hafizrahman** [comment]
I made #12860 forgetting that this already existed 🤦🏼  Closing this just because the PR already has branch and message mentioning that other issue. Sorry!
