### ISSUE TITLE
Top 3 active coupons card UI

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12716]
<img width="300" alt="image" src="https://github.com/woocommerce/woocommerce-ios/assets/524475/e04ddfc1-b4d3-49b9-a19c-1959af99705e">

- [x] First iteration of Most Active coupons card UI work. #12733
- [ ] Empty view when there are no active coupons. 
- [x] Coupon detail popup has a "More" (Ellipsis) menu. Test that it works as expected.  #12733

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
