### ISSUE TITLE
[Login] Consider sending Referer header when getting Application Specific passwords

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#12713]
Mentioned in an [iOS app review](https://link.reviewbot.io/review/HlqDp-aom) as a possible cause that prevented a user from logging in.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by pmusolino** [comment]
Closing this because of this peaMlT-Dw#comment-1599
