### ISSUE TITLE
[Woo POS] Basic communication between Product List and Cart

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12721]
Ref: TfaZ4LUkEwEGrxfnEFzvJj-fi-6_1657

Tapping the "+" on the individual product cards within the `ProductList` should add products to the `Cart`, while tapping the "x" on the Cart rows should remove these from the `Cart`.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
