### ISSUE TITLE
Dashboard: Improving the logic of detecting if a site has orders

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12739]
Quoting @hichamboushaba from an internal thread p1715164179010139-slack-C03L1NF1EA3

#### Problem

 Currently, to detect if a site has orders or not following this (at least in Android):
1. We check how many orders we have in the DB, and if we have a non-zero count, we decide that the site has orders.
1. If we don’t have cached orders, we fetch the order’s count from the API.

This logic has a side effect, that for stores with orders, and before fetching the order list, we have a “flicker” in the dashboard caused by showing the “Share Store” card then hiding it after the API call (point 2), see the video for understanding what I mean.

https://github.com/woocommerce/woocommerce-ios/assets/524475/dea780bf-8e4a-4c6f-965d-bf9f0852562c

#### Solution
The new logic I suggest:
1. Start with cached order’s count, and if it’s != 0, then use it directly.
1. If there are no cached orders, check the cached value of order status options we get from the above endpoint, and if it’s not empty, then sum the total of all its values*.
1. If there are no cached values, then revert to fetching the order’s count from the API using the existing logic that we use now.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by itsmeichigo** [comment]
@selanthiraiyan since we cannot use Storage for checking orders on the store, do you think we should close this issue?

**Comment by selanthiraiyan** [comment]
Closing this as in iOS we always check the remote instead of local storage to check for order availability. More info here https://github.com/woocommerce/woocommerce-ios/pull/12873.
