### ISSUE TITLE
iPad Login Page: Instruction Image Overly Large

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#12732]
On the iPad version of the app, during the login process where users use site credentials, the instructional image displayed is disproportionately large. This issue not only affects the aesthetic appeal of the page but it looks buggy given the resolution of the image itself.

## Expected behavior

The image should fit well within the designated area, maintaining functionality and design integrity.

<img src="https://github.com/woocommerce/woocommerce-ios/assets/495617/b60796f7-9288-4ae4-a353-c2ba0072e72b" width=300 />

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
