### ISSUE TITLE
When checking for saved cards settings, take into account card ordering also

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#12743]
To replicate issue:

1. start app
2. Edit dashboar, then enable and put an m2 card at the top (e.g: inbox or review), save
3. restart app
4. notice that the m2 card from point 2 is enabled but shown at the bottom, after the m1 cards.

Expected:
the m2 card should stay where it was before restarting.

The fix should be added in `updateDashboardCards()` in `DashboardViewModel`

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
