### ISSUE TITLE
UI work without final designs - Exploration

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12746]
How can we unblock ourselves without having designs? Is it worth sharing a post with our options? 

Can we perhaps start creating tasks for implementing barebones - empty VM, navigation controller, structure for a new theme, etc?

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
Published pdfdoF-4YX-p2
