### ISSUE TITLE
[Woo POS] Explore and add checks for non-supported device/size-class combinations

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12744]
Ref: p91TBi-bdN-p2#comment-12100

> In iOS, if the app detects a compact [horizontal size class](https://href.li/?https://developer.apple.com/documentation/swiftui/environmentvalues/horizontalsizeclass) in the POS mode, we can show a “not supported” screen to inform them to change the split screen state to get back to a regular horizontal size class.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
Closed in favour of https://github.com/woocommerce/woocommerce-ios/issues/13251
