### ISSUE TITLE
Top 3 products with low stock card UI

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12754]
<img width="423" alt="image" src="https://github.com/woocommerce/woocommerce-ios/assets/5533851/98273128-f009-4185-8ea7-df7dbbc646b2">

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
