### ISSUE TITLE
[Woo POS] Mechanism to handle quantities Product List <-> Cart

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12750]
Currently the "quantity" element in the `ProductCardView` is just a placeholder and does not update when products are added/removed from the cart:

 <img width="644" alt="Screenshot 2024-05-16 at 10 30 37" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/9018e755-71da-4a19-94e2-ecbcc083a490">

We need a mechanism to handle that, from the initial designs:
* Tapping the `+` should both increase the quantity number and make a new row appear in the `Cart` view
* Removing products from the cart should also update the quantity

Additionally we should also add some sort of fake "stock" property to the Product model for the moment, so it disallows to add more products than available in stock to the cart. This could represent the `Yosemite.Product` for the time being `stockQuantity` property.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
P2: p91TBi-bcW-p2#comment-12123
