### ISSUE TITLE
WooCommerce app widget displays only the dollar as the currency

### ISSUE THREAD

**Issue by cl0udres** [woocommerce/woocommerce-ios#12757]
Good morning, I would like to point out that on iOS (iOS 17.5, but it was the same on iOS 17.4 and 17.3 as well), when using the WooCommerce app widget, the amounts are displayed exclusively in dollars, despite being correctly set to euros.

I would like to clarify that the website is running WooCommerce version 8.4.0

![IMG_5870](https://github.com/woocommerce/woocommerce-ios/assets/65299629/1fa5cc7e-68aa-4a78-8ebe-630e16870edf)

![IMG_5871](https://github.com/woocommerce/woocommerce-ios/assets/65299629/f915cc3a-c60e-4d79-90ec-2b4af431f6be)

Furthermore, the same completed orders appear in euros on the app (and obviously on the website too).

![IMG_5872](https://github.com/woocommerce/woocommerce-ios/assets/65299629/bb1e231e-c37d-4de1-9f8a-f22306377b6a)

This issue has been ongoing for months, and I really hope it can be resolved soon.

Before posting here, I started a thread on a Facebook group, and the same problem was reported by another person (screenshot attached).

![Screenshot-2024-05-16-alle-14 44 48](https://github.com/woocommerce/woocommerce-ios/assets/65299629/b9cea4f1-e97b-44ce-a12a-b7ea1ceaa731)

Thank you.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by cl0udres** [comment]
Why does nobody care? Are there no users from Europe using WooCommerce?

**Comment by cl0udres** [comment]
The issue was resolved with version 19.5. Hallelujah!
