### ISSUE TITLE
Change "anonymous" to "Someone" as author for reviews that do now have an author name

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#1276]
During the review of PR #1257 we realised that there is a case when the review might contain an empty author name. We render "Anonymous" as review name in that case, but we should change it to "Someone" to match Android

**Comment by jaclync** [comment]
Looks like it's showing `Someone` on `develop` now 😄 maybe the server populates this? feel free to close this issue

![Simulator Screen Shot - iPhone Xs - 2019-09-09 at 11 22 11](https://user-images.githubusercontent.com/1945542/64501497-2e2c0200-d2f4-11e9-9746-36e1f680418c.png)
