### ISSUE TITLE
[Woo POS] Checkout flow view re-org

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12764]
The proposed checkout flow at the moment would involve moving from View A (Order List + Cart) to View B (Cart + Totals)

<img width="363" alt="Screenshot 2024-05-17 at 08 54 28" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/4fb4d3c7-721a-4d03-b2a9-c027bc3a488e">

<img width="394" alt="Screenshot 2024-05-17 at 08 55 52" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/aa5bab9c-5e6b-49ea-89f6-420f0a200419">

- The existing Cart view is kept in memory, but is re-rendered in the LHS
- A new `Totals` view is rendered in the RHS: https://github.com/woocommerce/woocommerce-ios/issues/12763

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
