### ISSUE TITLE
[Woo POS] Totals view

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12763]
After tapping in checkout, we'll have a "Totals" view with some sort of accumulated data and the payment buttons:

<img width="395" alt="Screenshot 2024-05-17 at 08 57 33" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/4ddedeea-2061-48fd-9a58-32bc7540e116">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
Keeping this open since the linked PRs are only to render the view and show some data, but nothing final yet.

**Comment by iamgabrielma** [comment]
Closing this generic issue in favour of more granular ones. Done! Ref: p1718879893536099-slack-C070SJRA8DP
