### ISSUE TITLE
Unit tests for optimized API calls

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12782]
Write unit tests to ensure that optimized API calls are executed as expected. 

https://github.com/woocommerce/woocommerce-ios/pull/12775#pullrequestreview-2065291370

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by selanthiraiyan** [comment]
Unassigning to work on https://github.com/woocommerce/woocommerce-ios/issues/12855

**Comment by itsmeichigo** [comment]
@selanthiraiyan do you think we need more unit tests for this? I didn't add any for checking optimization, not sure what else we should write 🤔

**Comment by selanthiraiyan** [comment]
I think the tests that you added are enough. I will close this issue. 👍
