### ISSUE TITLE
Privacy settings screen missing navigation bar

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12784]
**Describe the bug**
When opening privacy settings from the privacy bottom sheet from the dashboard screen, the screen is missing the navigation bar so the only way to navigate back is to double tap the Menu tab at the bottom.

**To Reproduce**
1. Log out of the app if needed, then log in to a store.
2. When the privacy bottom sheet shows up on the dashboard screen, tap Open settings.
3. Notice that the Privacy Settings screen has no navigation bar.

**Screenshots**
<img src="https://github.com/woocommerce/woocommerce-ios/assets/5533851/1572e8f1-3243-4d26-b16f-765bce3bb3ad" width=320 />

**Expected behavior**
The screen should have a navigation bar with a back button to navigate back.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
