### ISSUE TITLE
[Woo POS] Implement entry point conditions

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12780]
Following Android: https://github.com/woocommerce/woocommerce-android/pull/11513

- tablet device
- USD currency
- US store location
- Woo Payments plugin enabled and user setup complete
- Feature switch enabled

```[tasklist]
### Tasks
- [x] Implement the Android conditions above https://github.com/woocommerce/woocommerce-ios/pull/12783
- [x] Wait for the decision on the WCPay onboarding state condition, and maybe others p91TBi-beb-p2#comment-12127. Include unit tests
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by jaclync** [comment]
From p91TBi-beb-p2#comment-12134, we're good with the checks in the issue that were implemented in https://github.com/woocommerce/woocommerce-ios/pull/12783. Will add some basic test cases before closing this issue.

**Comment by jaclync** [comment]
The latest official decision for the entry point conditions p91TBi-bje-p2, which is what I implemented but I'll also follow the post about the WooPayments issue in case it affects the onboarding check p91TBi-bje-p2#comment-12234.
