### ISSUE TITLE
Payments -> Collect Payment Flow is Broken

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-ios#12790]
**Describe the bug**
Card Payment always fails when access from the "More -> Payments -> Collect Payment" flow.

**To Reproduce**
1. Go to More.
2. Click on Payments.
3. Click on Collect Payment.
4. Enter a custom amount.
5. Proceed to checkout.
6. Select 'Card Reader'.
7. Notice the payment fails.

**Expected behavior**
The payment succeeds.

This issue is present at least on 18.3-18.5 and probably in the more recent versions as well.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by malinajirka** [comment]
CUW peaMlT-Ec-p2
