### ISSUE TITLE
Polish table footer spinner view with plain table view style

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1281]
We use `FooterSpinnerView` for table views with infinite scroll, but these table views all have `grouped` style. The table view of the product list view controller on Products tab has `plain` style, and the spinner doesn't look nice without margin at the bottom and takes space when the spinner is hidden. This issue will:

- add some margin to spinner when animating
- remove table footer view height when the spinner is not shown/animating

**Comment by loremattei** [comment]
Hey! I'm moving this to 2.8 since 2.7 has been cut. Please, if you want this PR to make it to 2.7, feel free to move it back, target the release branch and ping me to build a new beta.

**Comment by jaclync** [comment]
Fixed in https://github.com/woocommerce/woocommerce-ios/pull/1285
