### ISSUE TITLE
Menu > Payments > Payment Provider: when both Stripe and Woo Payments are installed, "Confirm Payment Method" CTA doesn't seem reactive

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12818]
**Describe the bug**

**To Reproduce**

Prerequisites: the site has both Stripe and Woo Payments plugins installed

- Go to the Menu tab > Payments --> there should be a row `Payment Provider` to select a payment gateway
- Select a different value
- Tap `Confirm Payment Method` --> notice that there's no visual feedback, though after navigating away and back, the selected payment gateway stays (i.e. it works, just no visual feedback)

**Screenshots**

https://github.com/woocommerce/woocommerce-ios/assets/1945542/4faad91c-4b92-4531-9167-bc06ccdd3e8b

**Expected behavior**

Showing a success notice, and/or navigating back to the Payments menu would provide some feedback to the merchant.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPad 10th gen
- iOS version: iOS 17.2
- WooCommerce iOS version: 18.7

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
@jaclync I'm picking this issue to explore payment provider selection-related code and fix this low-priority ux issue in the process.
