### ISSUE TITLE
[Woo POS] M2 Empty: Product list

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12815]
Ref: p1716432162915869-slack-C070SJRA8DP

![Design screenshot of empty product list](https://github.com/user-attachments/assets/d085ed35-e84a-43a9-8d0a-4c6216e32dfb)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
@iamgabrielma I'm moving this to in-progress based on your PR above, but move it back if that's wrong

**Comment by iamgabrielma** [comment]
That sounds good, thanks!
