### ISSUE TITLE
[Login] Support Physical Security Keys

### ISSUE THREAD

**Issue by toupper** [woocommerce/woocommerce-ios#12838]
Docs:

https://developer.apple.com/documentation/authenticationservices/public-private_key_authentication/supporting_security_key_authentication_using_physical_keys/

More Context:

peaMlT-Fd-p2#comment-1595

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by Ecarrion** [comment]
@toupper Do we still want to work on this?

**Comment by toupper** [comment]
@Ecarrion As we didn't have any more requests about this one lately, let's close it for now and re-open it in the future in case of need.
