### ISSUE TITLE
Collect Payment/Card Reader and Apple Pay

### ISSUE THREAD

**Issue by jerseygirlapiary** [woocommerce/woocommerce-ios#12835]
You have a glitch/bug or instructions aren't clear about how to use new Collect Payment feature instead of Fast Payment.  Get an "unknown error message."

**To Reproduce**
Go to Payments/Collect Payment and Add a Custom Amount and enter an amount and then tap on Add Custom Amount once that completes we're left with Collect Payment at the bottom.

Now tap Collect Payment and it creates a new order and prompts for payment.  At that point selecting the card reader or Apple Pay gives the unknown error.

Now if we go to our Orders and tap on the pending order that failed and tap Collect Payment everything works as expected.

**Expected behavior**
We've been dealing with support for over 2 weeks to get this resolved.  We expect that once we initially create the new Custom Amount the Collect Payment button would work.  Didn't think about checking if it would work from the Orders/pending until today when I couldn't figure out when doing test Apple Pay payments always work but not through Collect Payments.

**Mobile Environment**
Please include:
- Device: iPhone SE and iPhone 15
- iOS version: 17.5.1
- WooCommerce iOS version: 8.9.1

Lisa

```[tasklist]
### Tasks
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by jerseygirlapiary** [comment]
Are you asking me to change labels?  I don't see how I can do that.  Edit doesn't seem to let me change labels.

**Comment by malinajirka** [comment]
Thanks so much for the report and sorry for not following up earlier. This issue is fixed now -> closing.
