### ISSUE TITLE
Improve Subscription Order Details

### ISSUE THREAD

**Issue by zwiesman31** [woocommerce/woocommerce-ios#1284]
**Is your feature request related to a problem? Please describe.**
Normally, [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/?aff=10486&cid=1131038) orders include a `Related Orders` section so the Store Admin can see more information about the subscription: 

![https://cld.wthms.co/LJiDV5](https://cld.wthms.co/LJiDV5+)
Image link: https://cld.wthms.co/LJiDV5

The app does not include that information, so it's hard to manage subscriptions.

**Describe the solution you'd like**
A way to bring the `Related Orders` information into the app.

**Describe alternatives you've considered**
A link to the individual order in the WP Admin so the user can click that link for more info (if needed).

**Additional context**
Since we now own [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/?aff=10486&cid=1131038), I feel that we should look to include order functionality for it instead of thinking about this as an `enhancement`.

**Comment by AmandaRiu** [comment]
Hi there! The WooCommerce subscriptions plugin is not currently supported in the Woo Mobile apps, but that doesn't mean we won't add it in the future! Please go to [this link](https://ideas.woocommerce.com/forums/133476-woocommerce?category_id=84283) to either up-vote it on the ideas board, or to add the request. Thank you for using the Woo Mobile app!

**Comment by AmandaRiu** [comment]
Oh wait, my apologies, I just realized this was opened internally <3 - reopening.

**Comment by astralbodies** [comment]
@zwiesman31 Do you mind making sure this feature suggestion is logged on ideas.woocommerce.com?

**Comment by shiki** [comment]
This is being considered and we'll split out the work into separate issues when the designs and planning have completed. For now, I will close this feature request to clean up the backlog.
