### ISSUE TITLE
[Woo POS] Product Selection: Inject products from app layer

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12840]
Reference: p1716783308516069-slack-C070SJRA8DP

> Using a simplified model for POSProduct seems good, we do not need all the details from Yosemite.Product and we can just convert the models from one to another before DI them into the POS dashboard/entry point. I'll use the same pattern to fetch products from storage but keep everything in the WooCommerce layer, so POS only has to know that will be provided with an array [POSProduct], and not where this data comes from, or how was generated.

> Product Selection - Cart: the output is an observable “cart” entity that has a list of items with the product ID & quantity. From Joe’s video walkthrough, product search & filtering are likely included so we can add them to this part of the data layer when the feature list is announced

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
