### ISSUE TITLE
[Woo POS] Revert stock constraint on product cards

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12841]
Reference: p91TBi-bcW-p2#comment-12191

> the current order creation in the apps allows you to put items which are out of stock into your orders. So I believe from the technical perspective, we can easily allow users to add as many items to the order as they like.

The limitation is only set from the customer POV when attempting to go through a web checkout flow, from the merchant POV we can still create orders in the backend no matter the stock level.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
