### ISSUE TITLE
Dynamic Dashboard: Apply order filter -> Empty order list -> Disabled dashboard cards

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12857]
Reported here - https://github.com/woocommerce/woocommerce-ios/pull/12851#pullrequestreview-2083987978

Steps to reproduce:
- On the Orders tab, select a filter that results in an empty order list.
- Switch to the dashboard - notice that the stats cards and order card are now unavailable, and the share store card is displayed.

Filter order list | Dashboard gets affected
--- | ---
<img src="https://github.com/woocommerce/woocommerce-ios/assets/5533851/0f2afcaa-ca70-45af-8d54-e4b18dc4e91c" width=320 /> | <img src="https://github.com/woocommerce/woocommerce-ios/assets/5533851/6ef5412c-ad59-4d25-9b6e-ce11a2422675" width=320 />

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
