### ISSUE TITLE
[Shipping Lines] Order not updated when new shipping line is added with no selected method

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#12853]
If the shipping line is a new shipping line (doesn't have an `id`) , instead of using the empty string value `""` that is the `N/A` `methodId` value we need to send a space `" "`  otherwise, the API fails to update the order.

Discussion: p1716899773707789-slack-C02KUCFCSFP

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
