### ISSUE TITLE
Dashboard: Load `6` coupon reports to handle deleted coupons case

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12855]
> Hide the deleted coupons: And to keep the card useful, we can reduce the chance of having less than three coupons by loading 6 coupons instead of 3 from the report endpoint, then match it to coupons from /wc/v3/coupons and exclude the deleted ones, then limit the number of results to 3 at the end. This is still not bullet proof, but getting a report with more than 3 deleted coupons will be a very edge case.

Internal - p1716911637747699-slack-C03L1NF1EA3

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
