### ISSUE TITLE
[Blaze] Track error details in `blaze_campaign_creation_failed` event

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12859]
### Issue

We are not tracking the error details like error code and error description when a Blaze campaign creation fails. 

### Fix

Track the error details along with the `blaze_campaign_creation_failed` tracking event. Pass the error to the event [here](https://github.com/woocommerce/woocommerce-ios/blob/trunk/WooCommerce/Classes/Analytics/WooAnalyticsEvent%2BBlaze.swift#L182-L184)

Internal - pe5sF9-2GE-p2#comment-3643

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
