### ISSUE TITLE
Add notice about the availability of new M2 cards

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#12860]
> Default visibility [p1715271583741779-slack-C03L1NF1EA3]:
> Let’s keep M1 cards as default and M2 cards as disabled after login/new installs.
> Make new cards discoverable by adding a dot to the Edit button and an extra card at the bottom for the suggestion. We > can use UserDefaults (iOS) and Preferences (Android) to display the suggestion only once.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by hafizrahman** [comment]
The decision from the Slack conversation is to compare existing saved cards and check if it already has the new cards. If not, show the notice (in the form of dot badge and a temporary card).

Once a user opens the Customize screen, remove the notice.
