### ISSUE TITLE
[Woo POS] Rename InPersonPaymentsViewModel

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#12863]
This is to help reduce confusion – `InPersonPaymentsViewModel` is an onboarding view model, specifically, and should be renamed to `CardPresentPaymentsOnboardingViewModel`, IMO.

In-person does not necessarily mean card-present, and onboarding is only for card-present.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by jaclync** [comment]
@joshheald One very trivial check, do you think it's better to name things `CardPresentPayments*` or `CardPresentPayment*` (plural or not)? Originally, I was going with `CardPresentPayments*` first as suggested in the issue description in https://github.com/woocommerce/woocommerce-ios/pull/12881 while I saw a mix of both naming in the code base with some newer ones using the plural form. In your protocol PR https://github.com/woocommerce/woocommerce-ios/pull/12875, you went with the singular style. I plan to update the renaming PR to use the singular form to be consistent.

**Comment by joshheald** [comment]
> @joshheald One very trivial check, do you think it's better to name things `CardPresentPayments*` or `CardPresentPayment*` (plural or not)? Originally, I was going with `CardPresentPayments*` first as suggested in the issue description in #12881 while I saw a mix of both naming in the code base with some newer ones using the plural form. In your protocol PR #12875, you went with the singular style. I plan to update the renaming PR to use the singular form to be consistent.

Hmm.

Consistency is good... but in this case, I initially thought `CardPresentPaymentsOnboardingViewModel` works better. Not because it's plural, but because it's possessive plural: i.e. "Card Present Payments' Onboarding View Model", or the onboarding view model belonging to card present payments.

That said, you could still argue that it's the "Onboarding to let you take a Card Present Payment".

I'd say add the s, but I don't mind too much.

We could update the facade to be plural too – it's a facade for taking multiple payments, after all.
