### ISSUE TITLE
[Woo POS] Create Card Present Payment Façade

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#12862]
Define protocol – inputs and outputs

Should be capable of
- Handling onboarding during connection
- Connecting to a reader
- Disconnecting a reader
- Collecting payment for an Order (specifically)
- Returning events to be shown in some UI (not specific to the designs)
- Cancelling a payment
- Cancelling an unused payment intent

Define data structures/protocols for passing events and results

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
