### ISSUE TITLE
[Woo POS] Create Payment Adaptor

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#12867]
Initially, this should include:
- Creating the `CardPresentPaymentPreflightController`
- Creating the `CollectOrderPaymentUseCase`
- Propagating alerts to the common publisher by implementing `CardPresentPaymentAlertsPresenting`
- Calling `collectPayment` for the order passed in

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by joshheald** [comment]
> Looking at `CollectOrderPaymentUseCase`, it looks like we just need these properties from `Yosemite.Order`:
> 
> - total
> - currency
> - datePaid
> - orderID
> - siteID (this we don't need to get from the order)
> - billingAddress
> 
> And in `OrderAction.retrieveOrder`, what's needed from the input `Yosemite.Order` is just the siteID and orderID. We could potentially just pass in an order ID and keep a `Yosemite.Order` after `checkOrderIsStillEligibleForPayment` unless the order properties above are needed before `OrderAction.retrieveOrder` is called.

_Originally posted by @jaclync in https://github.com/woocommerce/woocommerce-ios/pull/12875#discussion_r1619979208_

Let's do this when we implement the collect payment adaptor
