### ISSUE TITLE
[Woo POS] Move product data provider to Yosemite

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12879]
Suggested by @jaclync as part of a different review, and the conversation here Ref: p1716958602470079/1716913986.223809-slack-CGPNUU63E . The work of moving the product data provider to Yosemite can be tackled independently of deciding if we use StateObject or ObservableObject for the observable model.

> "how about having this provider (and POSProduct or equivalent) in Yosemite (can create a POS folder there as if it were a "POS data layer framework"), potentially in a protocol with func providePointOfSaleProducts() -> [POSProduct] and maybe other preview helpers, where the POS folder only knows about the protocol? Then the product provider implementation is DI'ed to PointOfSaleEntryPointView to the view model. This would separate the POS implementation details from the app/its POS folder, like the usage of Core Data through ResultsController (which is already in Yosemite)."

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
