### ISSUE TITLE
Dynamic Dashboard: Crash when loading Stock card

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12871]
**Describe the bug**
Sometimes, the stock card can crash when loading data. More about the stack trace below.

**To Reproduce**
1. Enable the feature flag for dynamic dashboard M2.
2. Enable the Stock card on the dashboard screen.
3. Switch between different statuses.
4. Not very frequently but you may encounter a crash.

**Screenshots**
N/A

**Expected behavior**
No crash happening when loading data for the stock card.

```
Thread 14 Crashed:
0   libobjc.A.dylib               	       0x18005f014 objc_msgSend + 20
1   libswiftCore.dylib            	       0x193021e98 Dictionary._Variant.setValue(_:forKey:) + 88
2   libswiftCore.dylib            	       0x192fe4fec Dictionary.subscript.setter + 296
3   WooCommerce                   	       0x1044ded5c closure #2 in closure #2 in ProductStockDashboardCardViewModel.fetchAndSaveReportsToMemory(for:) + 580 (ProductStockDashboardCardViewModel.swift:172)
4   WooCommerce                   	       0x1044e0535 partial apply for closure #2 in closure #2 in ProductStockDashboardCardViewModel.fetchAndSaveReportsToMemory(for:) + 1
5   libswift_Concurrency.dylib    	       0x209a030cd completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*) + 1
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
