### ISSUE TITLE
[Woo POS] Update entry point eligibility condition to use Woo 6.6+

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12878]
Reference: pfoUAQ-Iw-p2#comment-606

> The “auto-draft” status is WC 6.3+, and there are other payment-related properties that are WC 6.6+ – likely [is_editable and needs_payment properties in an order](https://href.li/?https://github.com/woocommerce/woocommerce-ios/blob/1faf9cf1421c14d867a9a6e3997d9c319ec09cd3/Networking/Networking/Model/Order.swift#L216-L218) from my search in the code. We will also consider adding it as a condition in the eligibility checks. [WC 6.6 was released](https://href.li/?https://developer.woocommerce.com/2022/06/14/woocommerce-6-6-released/) almost 2 years ago on June 14, 2022

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
