### ISSUE TITLE
Dynamic Dashboard: Fix disabled unit tests

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#12880]
> Some unit tests which relied upon reading hasOrders value from storage need to be disabled. This is because mocking the network calls is not straight forwards due to the mixed use of Combine + Detached async Tasks. We decided to tackle fixing the unit tests later as this is a critical issue affecting the orders list and dashboard.

The tests were disabled in https://github.com/woocommerce/woocommerce-ios/pull/12873

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
