### ISSUE TITLE
[Woo POS] Split CardPresetPaymentsModalViewModel into protocols, and typealias the combinations.

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#12893]
Yes, it's related to that. Perhaps we could split it to three things:
- content
- UIKit actions
- generic actions (which we'll use)

Then we could have a typealias for the first and third of these, which is what we'll require here, but still fulfil that with the `CardPresentPaymentsModalViewModel`.

The other option is to transform the `CardPresentPaymentsModalViewModel` to a new model which we add here as well, but that has the problem of the semantic meaning of the various titles being unclear.

_Originally posted by @joshheald in https://github.com/woocommerce/woocommerce-ios/pull/12875#discussion_r1620736540_

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
