### ISSUE TITLE
[Woo POS] Resolve currency formatter injection duplicate

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12918]
Continuation from https://github.com/woocommerce/woocommerce-ios/pull/12882

> just checking, can we already remove currencySettings here, or is it still needed for other POS use cases and we plan to remove it in the future?

Also commented on https://github.com/woocommerce/woocommerce-ios/pull/12882#discussion_r1621778958

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
