### ISSUE TITLE
[Woo POS] Remove Yosemite dependency when are only needed for previews

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12917]
Continuation of https://github.com/woocommerce/woocommerce-ios/pull/12882

Most SwiftUI previews have an unnecessary dependency of Yosemite, we should refactor this to remove the import if is not needed for the View itself.

Shared as well on PR feedback:

* https://github.com/woocommerce/woocommerce-ios/pull/12882#discussion_r1621790010

> since this seems to be used only for SwiftUI previews within DEBUG, how about moving this to the app layer within DEBUG?

* https://github.com/woocommerce/woocommerce-ios/pull/12882#discussion_r1621802516
> Now that we have a protocol POSItemProvider andPOSItem and this is just for SwiftUI previews, how about creating another implementation of POSItemProvider & POSItem within DEBUG in the app layer to provide mock items for previews?

* https://github.com/woocommerce/woocommerce-ios/pull/12882#discussion_r1621814388
> ❓ POSProduct's public use seems to be for SwiftUI previews in the app layer, maybe we can create a separate implementation of POSItem for previews within DEBUG and name it like POSPreviewItem/POSItemForPreview (I'm not good at naming things)? In that case, POSProduct can probably be internal within Yosemite.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
