### ISSUE TITLE
[Woo POS] Integrate the adaptors/facade to Connect Reader button

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#12916]
In order:

- [x] Integrate with the existing UI https://github.com/woocommerce/woocommerce-ios/pull/12921
~- [ ] (Probably worth a separate issue) Update the connect reader entry point based on the MVP design~
~- [ ] Integrate with the MVP design~

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by joshheald** [comment]
Closing this as done by above PRs, remaining tasks split to #12917
