### ISSUE TITLE
[Woo POS] Switching stores

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12919]
Continuation from  https://github.com/woocommerce/woocommerce-ios/pull/12882

There are several actors at play that we need to confirm work as expected for providing the correct products when a merchant switches stores or perform a similar operation that might change the state of the underlying data:
- The choice of `StateObject` vs `ObservableObject` for the initial data providing.
- The location of this initialization and its lifecycle, currently happens on `HubMenu`, which may affect the site ID used (or not) when switching sites if doesn't happen at the right moment.

Feedback question: https://github.com/woocommerce/woocommerce-ios/pull/12882#discussion_r1621794722

> is the siteID from ServiceLocator instead of HubMenuViewModel.siteID because of the issue in p1717043548835669/1716913986.223809-slack-CGPNUU63E where the HubMenuViewModel.siteID isn't accurate after switching stores? I think if HubMenuViewModel.siteID is indeed inaccurate, it's worth creating
an issue as it might cause other issues within the Menu.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
Update: At this point there's no plan in the short term to move vm initialisation somewhere else, and switching stores works correctly by loading data appropriately.
