### ISSUE TITLE
Calculating Totals - Exploration

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#12937]
Explore and summarize our options. 

Try to answer questions like:
- Are there existing endpoints which could help us with calculating taxes locally?
- We could calculate taxes locally or queue requests without blocking the UI or .. - what are our options? What are pros and cons of these options?
- ....
p1715182718640169-slack-C070SJRA8DP

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by jaclync** [comment]
👋  Just a note that from the team meeting last week, I started fully focusing on the [card reader connection flow](https://github.com/orgs/woocommerce/projects/247/views/6?sliceBy%5Bvalue%5D=iOS+%F0%9F%8D%8E) with Josh. For the WIP branch in the handoff post pfoUAQ-Iw-p2, some changes are required based on the decisions we made last week pfoUAQ-Iw-p2#comment-606.

**Comment by iamgabrielma** [comment]
Marking this as completed for M1.
