### ISSUE TITLE
Add site URL field to support request form

### ISSUE THREAD

**Issue by rossanafmenezes** [woocommerce/woocommerce-ios#12935]
Context: p1717151459632829-slack-C6H8C3G23
We are starting the project to integrate AI responses to some of the Woo Mobile tickets and one of the things we were discussing was the possibility of adding an extra field in the Support request form prompting the user to provide the address of the site they need help with, because a lot of times they have multiple sites and are not looking for help with the site they have open in the store when they access the support form. Other times they are not logged in and don't provide the site address. This would help decrease the number of interactions and make sure we save time by running tests on the right site.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
