### ISSUE TITLE
[Order Form] Design updates

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#12934]
## Shipping feedback prompt

The shipping feedback prompt needs updates based on design feedback:

- [x] Purple or grey background in dark mode
- [x] Icon next to link

![Image](https://github.com/woocommerce/woocommerce-ios/assets/8658164/003332fe-79dd-4397-90fc-be28f3cecd6e)

Discussion: p1717471031345379/1714123907.485049-slack-C02KUCFCSFP

---
## Order form

There are also additional tweaks for the order form:

- [ ] Reduce the amount of space taken up by the chevron/arrow at the top of the "Order total" bottom sheet
- [ ] Make the entire "Order total" section tappable to open the totals

![Image](https://github.com/woocommerce/woocommerce-ios/assets/8658164/3ad8c1b1-9b17-4452-a118-d5581edcfc72)

Discussion: p1717400944729439/1714123907.485049-slack-C02KUCFCSFP

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
