### ISSUE TITLE
[Woo POS] M2: Integrate Facade/Adaptors with Collect Payment button

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#12942]
The button should collect payment for an order, and be available when we've created that order from the cart.

After payment completes, we should show the payment result, and then clear the screen ready for the next transaction.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by jaclync** [comment]
Just to see if it's ready to work on, is this issue/task to integrate when the order creation is ready from the order totals project pffQ75-tR-p2?

**Comment by joshheald** [comment]
Yep, that's right 😊

**Comment by joshheald** [comment]
Note that this is kind of done... but I've left the task here to make sure the button's behaviour actually matches designs
