### ISSUE TITLE
Watch: Improve how dependencies are stored

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#12950]
## Description

Dependencies are stored using a custom dictionary encoding and decoding. This is quite cumbersome and error-prone.

https://github.com/woocommerce/woocommerce-ios/blob/2b72e5e13a34ed72b3c749429eaebc57c85f004d/WooCommerce/Classes/System/WatchDependencies.swift#L98-L114

## Tasks

- [ ] Make the watch dependencies conform to `Codable` so we can reuse the encoding/decoding as a storage mechanism.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
