### ISSUE TITLE
Watch: Improve refresh strategy

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#12953]
## Description

Currently, we refresh the `MyStoreView` every time the view appears and `OrdersListView` when the app is initialized.

We should improve the fetching strategy to keep the data up to date without having to fetch stuff all the time.

## Tasks

- [x] Refresh data when the app comes from the foreground.
- [x] Do not show the redacted state when the app is refreshing its data. We should only show it the first time.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
