### ISSUE TITLE
[Woo POS] Product selection & Cart view i3 navigation update

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12965]
Design reference: p91TBi-bls-p2

<img width="1187" alt="Screenshot 2024-06-05 at 15 08 16" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/1340b66e-7c01-45cd-b643-bec66a0a451e">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
Done as part of a different issue.
