### ISSUE TITLE
[Woo POS] Show reader connection state in UI

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#12969]
Ref: https://github.com/woocommerce/woocommerce-ios/pull/12909#discussion_r1624242472

In the latest payment service, we're only emitting card reader connection events from invoking `connectReader`. If the merchant disconnects the reader manually after a successful connection, the service should also trigger a disconnection event to ensure the connection status UI is accurate.

Additionally, connections initiated via the collectPayment action should show in the UI.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
