### ISSUE TITLE
[Woo POS] Cart view: Dynamic item counter

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12979]
From i3, we add a dynamic item counter to the top. This should handle pluralization.

<img width="452" alt="Screenshot 2024-06-06 at 15 10 55" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/da3aa8ad-82ad-48df-abbd-b52a24e472a4">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
Closed via #12999
