### ISSUE TITLE
[Woo POS] Update navigation bar (i3)

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12978]
As part of i3 p91TBi-bls-p2 we need to: 
* Move the navigation bar to the bottom
* Remove `history` button
* Update button design

<img width="908" alt="Screenshot 2024-06-06 at 15 08 03" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/66cc95a3-8139-4d55-9383-40cee801757c">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
Completed as part of a different task
