### ISSUE TITLE
[Woo POS] Support for product categories

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12977]
From i3 iteration: p91TBi-bls-p2#comment-12293

<img width="828" alt="Screenshot 2024-06-06 at 15 03 43" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/12357224-70c3-49ee-ba4d-b555e802badf">

Some thoughts:
* Test for truncation on product names and categories
* Display 1 category + hint for more
* Check in which cases we have subcategories
* Ideally let's keep this property nullable or specific to `POSProduct`, since `POSItem` doesn't need it

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
