### ISSUE TITLE
Dynamic Dashboard: Feedback card should break buttons to two lines if the labels are too long

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12974]
**Problem**
The My Store feedback card’s button text is wrapping on the default text size, which doesn’t look very good.

**Screenshot**
![2E0457F2-31C1-43BD-968A-AF6F490F3B8F_4_5005_c](https://github.com/woocommerce/woocommerce-ios/assets/5533851/9a368e5f-6c74-4937-9cb3-81f67c5da66a)

**Expectation**
Ideally, the buttons would wrap to two lines if the button text doesn’t fit on one line.

![CleanShot 2024-06-06 at 11 31 33@2x](https://github.com/woocommerce/woocommerce-ios/assets/5533851/d921e9f4-5159-4eb5-b94b-95544be2d2e4)

Internal discussion: p1717639278465559-slack-C03L1NF1EA3.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by itsmeichigo** [comment]
Closed by #12981
