### ISSUE TITLE
Blaze: Incorrect order for items in campaign list

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#12975]
**Describe the bug**
When a store has campaign IDs from 9999 to 10000, the campaign list displays the item with ID 9999 first even though it's older.

**Steps to reproduce**
- Log in to a store with more than 9 campaigns.
- Create a new campaign.
- Notice that the latest campaign is not at the top of the list.

**Expected behavior**
Latest items should be displayed at the top of the list

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
