### ISSUE TITLE
[Woo POS] Prepare connected reader for payment when order is created or updated

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#12972]
The MVP design includes automatic preparation of the card reader when the `TotalsView` is shown.

If a reader is connected, we should get it ready to collect the payment as soon as the Order is created or updated.

This will need some care though – we should clean up any unused Payment Intents (PI), which may occur in the following scenarios:
- When the Order is updated, as the total will change (unless we can reuse the PI in this case)
- If the POS transaction is cancelled
- If the Order is paid for using cash or another payment method.

If a reader is not connected, the function should just return early (and shouldn't even be called, really.)

The function should be "silent" in that it doesn't pop up any modal UI, at least not before the shopper taps their card. It can and should still show in-line UI. For the most part, this will be covered by the early return, but specialised alert view models may be helpful here too, as planned in #12868 for some events.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
