### ISSUE TITLE
Stats v3 has extra footer space below Top Performers

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1297]
**Describe the bug**
When a user views their Dashboard and looks at the Top Performers section, there is extra scroll space at the bottom.

**To Reproduce**
1. Have a store with Stats v3 turned on (this is currently the default - v4 only happens if you have wc-admin installed)
2. Visit the My store tab.
3. Scroll down to the Top Performers section.
4. See extra spacing.

**Screenshots**
<img src="https://user-images.githubusercontent.com/1062444/65539647-768c1800-decf-11e9-8f7d-f70dbf33a56d.png" width="350" />

**Expected behavior**
No additional spacing appears

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: any 
- WooCommerce iOS version: 2.7

**Comment by pmusolino** [comment]
In v.3.2 it was fixed.
I'm closing the issue for now.

![Simulator Screen Shot - iPhone 11 Pro - 2019-12-12 at 16 55 41](https://user-images.githubusercontent.com/495617/70727624-41d67280-1d00-11ea-94d6-fe5063950778.png)
