### ISSUE TITLE
[Woo POS] Integrate connect reader with M1 design

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#12971]
Split from #12916 

- [x] Update toolbar and the connect reader entry point based on the M1 wireframes design https://github.com/woocommerce/woocommerce-ios/pull/13000
- [x] Update toolbar and the connect reader entry point based on the M1 high-fidelity design
- [x] Integrate with the MVP design (Update: not needed for M1)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by jaclync** [comment]
Reopening as there are more design changes from the recent hifi design p91TBi-bot-p2.
