### ISSUE TITLE
[WOO POS] Calculate Totals

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#12983]
- Run the totals calculations that we can show in the totals view.
- Add different states: calculating, calculated, missing...

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by bozidarsevo** [comment]
Final totals will be calculated with https://github.com/woocommerce/woocommerce-ios/issues/13021
