### ISSUE TITLE
[Analytics] Unexpected drop in used_analytics event

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#12988]
There's an unexpected drop in the `used_analytics` Tracks event on iOS, suggesting a problem with how that event is being tracked. The drop starts around the 18.5 release/18.6 beta.

Related discussion: peaMlT-Gt-p2

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
Closing as this issue was resolved in #12995
