### ISSUE TITLE
[Woo POS] Collapsed cart view when empty

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#12980]
From i3, the cart starts in a greyed-out state which is not completely visible, just becoming visible when an operator adds products to the cart:
<img width="801" alt="Screenshot 2024-06-06 at 15 19 02" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/d4562096-d6da-4166-81b2-9827a3b225fc">

Logging this issue so we can explore this behaviour. Something to take into account is localization, since may cut-off or expand the ideal cart width.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
Latest:

<img width="891" alt="Screenshot 2024-06-17 at 09 50 24" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/f3ad022a-ce37-4798-b0c9-002f943570a3">
