### ISSUE TITLE
Watch: Troubleshoot connection

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#12993]
## Test Plan Notes

> The watch didn’t connect/authenticate until I restarted the phone app. This was true regardless of whether I had previously relaunched the phone app (even if I hadn’t just logged in there).

> The first time, I installed the phone app from the installable build > installed the watch app and saw the error screen > logged in on the phone > opened the watch app and saw the error screen > closed and relaunched the phone app > watch app connected and started the Stats screen.

> The second time, I installed the phone from TestFlight > logged in on the phone > installed the watch app > opened the watch app and saw the error screen. Holding the watch near the phone didn’t do anything until I closed and relaunched the phone app; then the Stats screen opened right away.

> The third time, I uninstalled the watch app and then reinstalled it. I had already relaunched the phone app previously after logging in and had it open in the background on the phone. When I opened the watch app, I saw the error message but still had to close and relaunch the phone app for the watch app to connect.

## Task

- [x] Investigate if there are ways to troubleshoot the connection without having to restart the app.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
