### ISSUE TITLE
Watch: Fix UI in smaller screens

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#12992]
# Description

The watch app does not render well in smaller watches.

# Task

- [ ] Go through all app screens and make sure they look good in smaller screens.

. | . | . | 
---- | --- | ----
![Image](https://github.com/woocommerce/woocommerce-ios/assets/562080/4b6f6700-4fc0-4a29-86a7-25e79cdd624d) | ![Image](https://github.com/woocommerce/woocommerce-ios/assets/562080/f9d3875b-b514-43d7-8ea9-db075b8de21c) | ![Image](https://github.com/woocommerce/woocommerce-ios/assets/562080/711b282f-7818-41fb-a7aa-51b47acbd723)
![Image](https://github.com/woocommerce/woocommerce-ios/assets/562080/5bf7de39-cf19-47d0-a71a-ab0f33e462a2) | ![Image](https://github.com/woocommerce/woocommerce-ios/assets/562080/66777c0c-38c3-4b74-8e0e-706f3ecd2b8c) | ![Image](https://github.com/woocommerce/woocommerce-ios/assets/562080/4e07987e-2df4-4af4-b24f-d0da7235e7fe)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
