### ISSUE TITLE
Watch: Design Adjustments

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#12991]
## Description

Perform the following design adjustments 

### Loading & Error States

![Image](https://github.com/woocommerce/woocommerce-ios/assets/562080/6738169d-c269-48d5-ba10-c8a5a692f512)

## Order Details

![Image](https://github.com/woocommerce/woocommerce-ios/assets/562080/8a9bfd87-d281-42d8-a395-657c6d500ab3)

- Right align the time over the order number (May not be possible)
- Use a light tint background behind the back chevron (May not be possible)
- Move the product count numbers up so that the number is on the same text baseline as the name

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
