### ISSUE TITLE
[Woo POS] Connecting to reader is stuck after the first time

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#13004]
Steps to repro:

- launch app
- collect payment or connect reader in POS successfully
- disconnect reader in Payments menu
- connect reader in POS

Connection works in Menu > Payments > Manage Card Reader.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by jaclync** [comment]
After some debugging, it looks like it's from `getFoundKnownReader` being non-nil when connecting after the first time in POS. This value is `nil` in other flows like in Menu > Payments > Manage Card Reader. Internally, it emits `showAlert(CardPresentModalConnectingFailed)` and `showAlert(CardPresentModalConnectingToReader)` at the same time and the later one (connecting state) ends up being shown and the UI appears stuck.

I'll look deeper into why `getFoundKnownReader` is different. Perhaps it's time to share the connection controller to have consistent connection behavior.
