### ISSUE TITLE
Missing `Private` tag on product items

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-ios#13013]
In the product list tab, when a product is set to private, the tag `Private` is missing: 
![Screenshot 2024-06-07 at 15 57 43](https://github.com/woocommerce/woocommerce-ios/assets/2663464/be6db879-673a-41a7-8c9d-2089d3f7077f)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
