### ISSUE TITLE
Add `isNotEmpty` to Collection and String extension as the negation of `isEmpty`

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1301]
Sounds like adding `isNotEmpty` to at least `Array` has been discussed in Swift for a few times like [in this post](https://forums.swift.org/t/isnotempty-on-array/15228), but not something they plan on adding to core Swift.

In the code base, we have been using `!var.isEmpty` and `var.isEmpty == false` as the negation of `var.isEmpty`. It would read more nicely with `var.isNotEmpty`. We could potentially add an extension to Collection and String for `var isNotEmpty: Bool { return !isEmpty }` and replace the exisitng usage of the `isEmpty` negation.

**Comment by leonardodamato** [comment]
Hello. Can I tackle it? Should I create in on "Woocommerce/Classes/Extensions/Array+Helpers.swift" and "Strings+Helpers.swift"?

**Comment by shiki** [comment]
Closed by #1783. Thank you, @leonardodamato!
