### ISSUE TITLE
[Woo POS] Update POS alert design to match the existing app

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#13016]
As the card present payment alerts presented in POS are a new SwiftUI view instead of the UIKit modal controller in the `app` use cases, we want to match the SwiftUI view design to the UIKit version.

- [x] Update design in basic alert view https://github.com/woocommerce/woocommerce-ios/pull/13017
- [x] Update reader list design https://github.com/woocommerce/woocommerce-ios/pull/13019
- [x] Use custom progress indicator `IndefiniteCircularProgressViewStyle`

---

Update: the following subtask is a duplicate of a [draft task](https://github.com/orgs/woocommerce/projects/247/views/6?sliceBy%5Bvalue%5D=iOS+%F0%9F%8D%8E&filterQuery=sub-project%3A%22Card+Reader+Flows%22&pane=issue&itemId=65321986) with a solution https://github.com/woocommerce/woocommerce-ios/pull/13017#issuecomment-2158138005, removing it from the task list.
- Update sheet size ([potential solution](https://stackoverflow.com/questions/60967872/swiftui-sheet-modals-with-custom-size-on-ipad) - ZStack or UIKit formSheet) TfaZ4LUkEwEGrxfnEFzvJj?node-id=963-63913#833377472

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by jaclync** [comment]
Reopening for other subtasks.
