### ISSUE TITLE
[HACK Week] Enhancements to Customers in Hub menu

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#13023]
For HACK Week, I'm working on enhancements to the Customers section in the Hub menu. These were identified as possible future enhancements after the initial release in https://github.com/woocommerce/woocommerce-ios/pull/12349, and are listed in no particular order:

- [x] For registered customers, we could fetch their billing and shipping details from `/wp-json/wc/v3/customers/<id>` and insert them into the customer details view. This would give merchants additional ways to contact their customers (address and phone). (We should include the ability to copy these details and use the phone number to call the customer, similar to in order details.)
- [ ] We could allow merchants to sort the customer list by different fields.
- [ ] We could add support for more advanced search in the customer list (like on the web).
- [ ] We could add support for editing customer details, for registered customers.
- [ ] We could add general Customer analytics. We can query `wc-analytics/reports/customers/stats` to get stats about the store’s customers: # of customers, Average # of orders, Average lifetime spend, Average order value.
- [ ] We could navigate from the customer details to a list of the customer's orders, e.g. a filtered list of orders on the Orders tab.
- [x] Could we navigate from the customer details to a new order, with the customer pre-filled in the order form? That could offer a quick way to start a new order for that customer.

Discussion: pe5pgL-4L1-p2

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
Closing this as I've reached the end of my hack week, although the remaining ideas could be picked up in the future. Related: pe5pgL-5an-p2
