### ISSUE TITLE
[Woo POS] M2 Add modal presentation for connection alerts

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#13042]
The goal is to update the modal sheet size to match the existing app and to allow future customization. SwiftUI sheet doesn't have an easy way to customize its size.

Check Josh's previous experiment: https://github.com/woocommerce/woocommerce-ios/pull/13017#issuecomment-2158138005

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
