### ISSUE TITLE
Blaze: Site connected with Jetpack Connection Package plugin should not get Blaze feature

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#13057]
From @JorgeMucientes 

> Blaze on Jetpack CP sites should always be hidden. Currently the Blaze DSP requires a Jetpack full sync to work. So Jetpack CP sites are excluded from Blaze.

p1718363441062859/1718026968.514799-slack-C6H8C3G23

pe5sF9-2JW-p2#comment-3667

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
