### ISSUE TITLE
[Woo POS] products not showing in POS if not loaded in the app in general

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#13068]
## How to reproduce

- do a clean install of the app
- do not go to Products tab, go to POS first
- check that no products are shown in the list of products
- now go to Products tab and load the products
- go back to POS
- products are show in POS also

## Expected
- products should be shown in POS regardless if they are loaded or not

## How to fix
- fetch products in POS if there are none to make sure we show some if there are products for that merchant

## Screenshots

![Image](https://github.com/woocommerce/woocommerce-ios/assets/6242034/45fbc283-f354-4e30-9562-abf660975364)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by bozidarsevo** [comment]
@iamgabrielma could you take a look at this at some point? not a high priority for now, but an interesting case

**Comment by iamgabrielma** [comment]
Thanks for reporting! I believe this comes from the `POSProductProvider` just fetching products that can already be found in storage, but if storage is empty when the POS is loaded directly, then there's nothing to fetch.

This is also somewhat related to p91TBi-bot-p2#comment-12357 and how we'll sync products that are added via web after POS has been already loaded.

I'll take a look next on what we generally do for synching those, at first glance it seems we need to add a bit of support around `ProductActioncheckIfStoreHasProducts`, `ProductAction.retrieveProducts` and/or `ProductAction.synchronizeProducts`
