### ISSUE TITLE
[Woo POS] Update cart's product cards (hifi i1)

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13067]
Ref: p91TBi-bot-p2

<img width="892" alt="Screenshot 2024-06-17 at 13 24 48" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/e0064576-f25b-42b3-a160-96433b454abb">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
Done via https://github.com/woocommerce/woocommerce-ios/pull/13069 and https://github.com/woocommerce/woocommerce-ios/issues/13067
