### ISSUE TITLE
[Woo POS] Update product's list product cards (hifi i1)

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13066]
Ref: p91TBi-bot-p2

<img width="784" alt="Screenshot 2024-06-17 at 13 22 58" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/5defcd4a-70a2-4790-9a57-820571b9c476">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
Done via https://github.com/woocommerce/woocommerce-ios/issues/13067
