### ISSUE TITLE
Add date range checks for Blaze campaigns

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-ios#13075]
When creating campaigns from the mobile apps users may run into this issue: 
```
{
  "message": "Validation failed",
  "details": {
    "start_date": {
      "message": "Campaign start date or end date is outside the accepted range"
    },
    "end_date": {
      "message": "Campaign start date or end date is outside the accepted range"
    }
  }
}
```
This happens when campaigns do not meet one of the following criteria:
- A regular campaign can’t run for more than 28 days (end-start <= 28)
- Also can’t run less than a day (end-start >=1)
- Start date needs to be inside the accepted range that is max 60 days from today (internally, we validate 61 to simplify the logic related to timezones)

We currently have checks in place that handle the first 2 point. However we do not have any checks to ensure campaigns are not scheduled more than 60 days in advance. Add the missing check to satisfy the prior 3 points and avoid users facing generic errors when creating a Blaze campaign.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
