### ISSUE TITLE
[Woo POS] Implement card reader update SwiftUI views

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13070]
In #13062 we added SwiftUI views and view models for all the regular connection events, but skipped upgrade views to keep the PR small.

`required` updates are the most commonly applied type, and happen during reader connection. We have no way to know whether they will happen before a connection attempt, so we can't gate the POS experience to exclude them.

We should implement the upgrade progress views, and specific upgrade error views, to match the existing designs.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
