### ISSUE TITLE
[Woo POS] Merge `CardPresentPaymentEvent.showReaderList` event into `show` event, with associated eventdetails.

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13072]
We currently have a separate `CardPresentPaymentEvent` for showing multiple found readers, a detail inherited from the existing implementation, where it was done becaues `CardPresentModalViewModel` was getting overloaded with too many different alerts showing with the same interface and view.

Now that we've adapted the alert provider and alert presenter, we don't have the same issue in the new implementation: each message from the service is sent with its own type name, and `CardPresentPayentEventDetails` struct. Callers can convert that to a specific view and view model pair, so there's no overuse of a single view for multiple types.

We should therefore tidy up our `CardPresentPaymentEvent` enum, and bring the `showReaderList` in line with the other reader connection events – after all, it will be shown in the same way, as a modal during the flow.

- [ ] Add `multipleReadersFound` to `CardPresentPaymentEventDetails`, complete with reader IDs and the selection handler.
- [ ] Add the new case to the set of `PointOfSaleCardPresentPaymentEventPresentationStyle.alert` events
- [ ] Add a view and view model for showing the reader list
- [ ] Present the new view/viewModel when the relevant event is received

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
