### ISSUE TITLE
Dynamic Dashboard: Missing event for when My Store screen is loaded

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#13089]
**Description**
We currently don't track when the My Store (dashboard) screen is loaded. This event is necessary to track the performance of the screen.

Internal discussion: p1718782056971189-slack-C03L1NF1EA3.

**Expectation**
Add a new event `dashboard_loaded` when the view is loaded.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
