### ISSUE TITLE
[Order Creation] Customer list fails to load if `date_last_active_gmt` returns `null`

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#13092]
**Describe the bug**
As reported in Slack:

> I have one of my sites where I get an error if I try to add an existing customer to an order. The customer list loads fine if I go More Menu > Customers it loads fine. The issue is just from the order creation.

Logs include this parsing error for `Array<WCAnalyticsCustomer>`:

```
"Cannot get unkeyed decoding container -- found null value instead"
"Swift.DecodingError.valueNotFound(Foundation.Date, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: \"data\", intValue: nil), _JSONKey(stringValue: \"Index 12\", intValue: 12), CodingKeys(stringValue: \"date_last_active_gmt\", intValue: nil)]
```

It turns out that `date_last_active_gmt` can be `null`, for example with a manually added customer, which we didn't anticipate in the `WCAnalyticsCustomer` model.

Report: p1718798574530569-slack-C6H8C3G23 h/t @rossanafmenezes

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
While looking at the code for this endpoint I found [where this date is retrieved](https://github.com/woocommerce/woocommerce/blob/3ea4df2055a6d9b542b7f4618206e6a2c83b4d37/plugins/woocommerce/src/Admin/API/Reports/Customers/Controller.php#L155) and realized that the `wc_rest_prepare_date_response` function it uses always has [a chance of providing a `null` date value](https://github.com/woocommerce/woocommerce/blob/3ea4df2055a6d9b542b7f4618206e6a2c83b4d37/plugins/woocommerce/includes/wc-rest-functions.php#L33-L35). We should probably be prepared for any date to be potentially `null` in that case.
