### ISSUE TITLE
Increase orders badge size

### ISSUE THREAD

**Issue by kyleaparker** [woocommerce/woocommerce-ios#1309]
**Describe the bug**
The size of the orders badge needs to be increased

**Screenshots**

<img width="844" alt="Untitled 2019-09-27 11-37-38" src="https://user-images.githubusercontent.com/712873/65782297-5e103d80-e11b-11e9-88c1-06f5cd0e56bd.png">
<img width="1406" alt="Untitled 2019-09-27 11-38-09" src="https://user-images.githubusercontent.com/712873/65782301-5fda0100-e11b-11e9-964a-72c8708b525c.png">

**Comment by jaclync** [comment]
Make sure it also fixes https://github.com/woocommerce/woocommerce-ios/issues/1283
