### ISSUE TITLE
iPad support for Dashboard cards screen

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13093]
This came up as a HACK week idea. 

![image](https://github.com/woocommerce/woocommerce-ios/assets/524475/cbe4e603-df38-4a2c-b8fe-4cc6b2fe3d86)

- Making the dashboard cards iPad-compatible will make it easy to view information from multiple dashboard cards at the same time. i.e. Two/Three columns of cards based on the configuration.
- We should also take into account the font sizes to avoid making it too narrow for big sizes.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by JorgeMucientes** [comment]
Closing as this was implemented here already: https://github.com/woocommerce/woocommerce-ios/issues/13988
