### ISSUE TITLE
[Woo POS] Add WC version 6.6+ check to entry point conditions

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#13096]
As in p91TBi-bje-p2:

> Update 6/5/2024 - WooCommerce version is 6.6+ (pfoUAQ-Iw-p2#comment-608)

We are adding a new check on WC version 6.6+ to the POS eligibility checker.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by jaclync** [comment]
Oops, just noticed that the same task was already created https://github.com/woocommerce/woocommerce-ios/issues/12878. Closing.
