### ISSUE TITLE
Update prompt to generate 3 options

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13108]
- Define and refine a prompt. The prompt should provide three options for name and description.
- Validate that this doesn't break other parts of the product creation response.
- Add a new struct similar to `AIProduct`. (This struct will have options to store 3 variations of name and description)
- Update the Yosemite layer and add action to generate the above new struct. 
- Expect to receive fewer than 3 options and parse it. (Error cases)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
