### ISSUE TITLE
Merge “Add your product name” and “About your product” screens

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13106]
- [x] Remove the progress bar at the top of the screen. https://github.com/woocommerce/woocommerce-ios/pull/13225
- [x] Title and label changes. https://github.com/woocommerce/woocommerce-ios/pull/13225

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
