### ISSUE TITLE
UI for switching between 3 options.

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13109]
- UI to switch between the 3 options.
- UI for "Undo edits" when applicable.

<img width="387" alt="image" src="https://github.com/woocommerce/woocommerce-ios/assets/524475/24272567-5572-4e4e-a1ec-3c5b64abc4d5">

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
