### ISSUE TITLE
Logic for improving seed prompt

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13111]
![image](https://github.com/woocommerce/woocommerce-ios/assets/524475/e95770db-17a1-4ac0-80d3-0725438dbeae)

1. Send the user-entered keywords to AI and display guidance text.

- Define and refine a prompt.
- Send the user-entered keywords and get an AI response.
- Display the received guidance text. (UI work)
- Throttle the network requests. (Filter duplicate texts, wait 2 or 3 seconds for users to finish typing)
- Handle error cases. (We can silently ignore the errors as we will send another request once the user types again.)
- Handle edge cases such as empty text field.

2. Progress bar with color

- This will be entirely local with no AI intervention.
- Define rules for changing the color of the progress bar. (Red: 1-5 words. Yellow: 6-15 words. Green: 16+ words)
- Define rules for the length of the progress bar.
- UI work

Internal - p1719205329811609-slack-C03L1NF1EA3

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by pmusolino** [comment]
Extra decisions here C03L1NF1EA3/p1720512584126239
