### ISSUE TITLE
[Woo POS] Disable navigation away from POS (back to cart, exit POS, etc.) when payment starts (after tapping card)

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#13115]
Ref: p1718735528906309/1718734994.548519-slack-C070SJRA8DP

> When the payment actually starts, i.e. the merchant taps their card, we probably want to disable navigation away, especially back to the cart. The existing code assumes that's handled by modal presentation, but we'll need to block/unblock separately based on the events that are emitted from the facade.

Note that the i2 designs have the cart portion slide off screen when the card is tapped, and don't include a back button.

Cancelling the payment should (perhaps) restore the cart portion and associated "add more" button.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
