### ISSUE TITLE
[Mobile Payments] Cancelling a reader connection prevents future connections

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13122]
### Pre-existing cancellation issue
I discovered a pre-existing issue with cancelling a reader connection, which impacts testing this change. The issue is with the underlying code, and can be recreated from the settings screen as well

1. Go to Menu > Payments > Manage Card Reader
2. Tap `Connect card reader`
3. Tap `Cancel` on the alert asking if you want to connect a particular reader
4. Tap `Connect card reader` again
5. Tap `Connect` on the reader connection alert
6. Observe that it stays stuck on the `Connecting to reader` screen forever

The issue predates POS – I have recreated it as far back as version 18.0 of the app, so it's probably existed for a very long time.

_Originally posted by @joshheald in https://github.com/woocommerce/woocommerce-ios/pull/13100#pullrequestreview-2135255822_

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
