### ISSUE TITLE
[Woo POS] update payment and processing view design

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#13120]

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by joshheald** [comment]
@bozidarsevo Will this include anything to prevent people going back to edit the cart after they tap their card?

If not, or if you're not anticipating getting to it soon, I'll do something basic to implement that tomorrow as it will make it much easier for us to test payments...

**Comment by bozidarsevo** [comment]
> @bozidarsevo Will this include anything to prevent people going back to edit the cart after they tap their card?
> 
> If not, or if you're not anticipating getting to it soon, I'll do something basic to implement that tomorrow as it will make it much easier for us to test payments...

I was thinking just doing the UI part, according to the designs.

**Comment by joshheald** [comment]
OK, I'll do something towards it on #13115, but I'll just set `disabled` modifiers on the buttons. With your UI changes, the buttons shouldn't even be visible in those states, but that might be a bit later on.
