### ISSUE TITLE
[Woo POS] Disable CTA to go back to product selector when order is being synced

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#13127]
First discovered in https://github.com/woocommerce/woocommerce-ios/pull/13100#pullrequestreview-2135255822, caused by the reason in the expanded technical details in p91TBi-btJ-p2#comment-12385.

## Describe the bug

When checking out with an updated cart before the previous order sync result comes back like when the network is slower, the order total could become inconsistent with what's in the cart UI. This is a high-priority issue to fix before M1.

## Steps to repro:

It's easier to reproduce when simulating the network condition with a slow connection, like in device Settings > Developer > Network Link Conditioner, enable it with a slower network condition like "Edge").

Prerequisite: the store is eligible for POS and the feature switch is enabled in Menu > Settings > Experimental Features > POS

* Launch app
* Go to Menu > Point of Sale
* Add an item to cart, tap Checkout, then quickly tap Add More, add another item to cart, tap Checkout --> the subtotal in the cart and the total in the totals UI become inconsistent. Try repeating a few times quickly if you can't repro this the first time

## Example screenshot

![Image](https://github.com/woocommerce/woocommerce-ios/assets/1945542/855da45c-7f8f-4002-a477-e392fb4a4e78)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by jaclync** [comment]
## The fix

As discussed and decision reached in pfoUAQ-Mv-p2#comment-667, we're going to disable the CTA to go back to the product selector screen to prevent this issue from happening. After MVP, we can consider a proper fix as suggested in the post.

We can defer this after we've updated the design to replace the `Add More` CTA with a back button:

current | M1 design
-- | --
<img src="https://github.com/woocommerce/woocommerce-ios/assets/1945542/855da45c-7f8f-4002-a477-e392fb4a4e78" width="500" /> | <img width="500" alt="Screenshot 2024-07-03 at 1 42 09 PM" src="https://github.com/woocommerce/woocommerce-ios/assets/1945542/993ad2b4-6a4a-428d-9f9b-93d29b9176da">
