### ISSUE TITLE
[Mobile Payments] Reader connection attempts after an error may never complete

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13123]
1. Launch the app
2. Navigate to `Menu > Payments > Manage Card Reader`
3. Tap `Connect Card Reader`
4. Tap `Connect to reader` to start the connection to a reader, then immediately turn the reader off
5. When you're shown the error, tap `Cancel`
6. Tap `Connect to reader` again
7. Leaving your reader off, tap `Connect` on the known-reader alert
8. Observe that you're shown Connecting to reader and it never goes away.

Note that it shouldn't even offer you the reader to connect to the second time around, because it's switched off.

https://github.com/woocommerce/woocommerce-ios/assets/2472348/a085d210-0e23-454f-9e42-a1c935813d9b

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
