### ISSUE TITLE
Show cached content by default on the dashboard

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#13136]
# Task

- [ ] Update app to show cached content for the dashboard as soon as the app loads.
- [ ] Make sure the redacted state is only shown when fetching data for the first time.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by Ecarrion** [comment]
closed and replaced by

- #13369
- #13370
- #13371
- #13372
- #13373
- #13374
- #13375
- #13376
- #13377
