### ISSUE TITLE
Update Dashboard Data 

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#13130]
# Task

- [ ] Periodically update the data needed for the dashboard as a background task.
- [ ] When opening the app, update the dashboard data if it hasn't been updated in the background recently.

## Background Update Periodicity

- Defined by the system

## Foreground Update Trigger

- Update if the data hasn't been updated in 30 minutes.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by Ecarrion** [comment]
closed and replaced by

- #13369
- #13370
- #13371
- #13372
- #13373
- #13374
- #13375
- #13376
- #13377
