### ISSUE TITLE
Show last updated timestamp on the dashboard

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#13134]
# Task

- [ ] Update UI to a timestamp of when the data was last updated.

## TODO

- [ ] Define UI Mock up

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by Ecarrion** [comment]
closed and replaced by

- #13369
- #13370
- #13371
- #13372
- #13373
- #13374
- #13375
- #13376
- #13377
