### ISSUE TITLE
Update Order List Data

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#13131]
# Task

- [x] Periodically update the data needed for the orders list as a background task.
- [x] When opening the app update the orders list data if it hasn't been updated in the background recently.

## Background Update Periodicity

- Defined by the system

## Foreground Update Trigger

- Update if the data hasn't been updated in 30 minutes.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
