### ISSUE TITLE
Update the last 5 new orders Data

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#13132]
# Task

- [ ] Periodically update the data for the last 5 orders as a background task.

## Background Update Periodicity

- Defined by the system

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by Ecarrion** [comment]
Closing this as it is probably not needed.
