### ISSUE TITLE
[Woo POS] M2 UI: Enter POS mode loading screen

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13143]
When we enter in POS mode, there's a delay while we wait for the data back from network. We need to implement a loading screen (or set of loading screens) while we wait for the POS mode to load.

![Image](https://github.com/user-attachments/assets/d2d49590-1aed-4018-a7cd-18c2f17c866c)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
