### ISSUE TITLE
Dynamic Dashboard: Handle CoreData failure with grace on dashboard cards

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#13153]
**Problem**
On the dashboard screen, we use CoreData to fetch cached data for cards like Peformance, Top Performers, Blaze, and Reviews. When there's an issue with CoreData access, the app will crash repeatedly causing a bad experience for users.

**Expectation**
We could handle the failures with grace by failing silently and depend on remote data entirely in these cases.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by itsmeichigo** [comment]
Closing since the issue seems to stop happening after version 19.0.0.3.
