### ISSUE TITLE
Add tracks events

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#13155]
### For this project, the following events should be added:

- [x] `*_background_data_synced` params: time_taken

- [x] `*_background_data_sync_error` params: error

- [x] `*_push_notification_order_background_synced` params: time_taken

- [x] `*_push_notification_order_background_sync_error` params: error

- [x] `*_background_updates_disabled`

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
