### ISSUE TITLE
Spike: Attempt to fetch notifications only of type comment

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#1316]
During the review of #1298 we noticed that we might find ourselves with a list of Product Reviews fetched from the reviews endpoint, but we might not have the notifications corresponding to some of those reviews.

Visually, this manifests in Product Review that are not marked as read when tapping "mark all as read" in the reviews tab

The reason for that seems to be that when we fetch notifications, we fetch all kinds of notifications associated to the WordPress account,, not only those corresponding to store reviews.

**Comment by shiki** [comment]
@ctarda Do you think this is something we should still do or can we close this for now?

**Comment by ctarda** [comment]
@shiki I think we can close this for now. Closing!
