### ISSUE TITLE
[Product Creation with AI] Change create product with AI button subtitle

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13160]
Update "Create a product with AI" buttons subtitle

| Current | Expected |
|--------|--------|
| <img src="https://github.com/woocommerce/woocommerce-ios/assets/524475/90772817-5ff3-43a9-9559-fb3e6aa858d0" width="244" > | <img width="244" alt="image" src="https://github.com/woocommerce/woocommerce-ios/assets/524475/ca41d9a6-e972-4435-9dfb-870a1bbceeb4"> |

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
