### ISSUE TITLE
[Woo POS] Handle failures from `capture_terminal_payment` gracefully

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13162]
> [We need to better handle] an error on the response from the `capture_terminal_payment` request to WooPayments at the end of the flow. This could happen even if the capture was successful, especially in poor network conditions. 
> 
> In that case we should quietly refresh the order and see whether it's been paid, but if we get repeated errors from the order endpoint, the merchant could go back and try again. They might start a new transaction, which would make it hard to prevent double charges.
> 
> It would _probably_ fail to take the payment, because if the orders endpoint is facing issues, they're not going to get that far... but we need the merchant to understand the risks and that they need to be sure whether or not the merchant has been charged. @joe-keenan has this on his list (though I now realise I didn't see it in the error designs yesterday.) 

 _Originally posted by @joshheald in [#13128](https://github.com/woocommerce/woocommerce-ios/issues/13128#issuecomment-2190897297)_

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
