### ISSUE TITLE
[Woo POS] M2 Update connection alerts to match the new designs

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#13175]
Update the connection controllers to match the new designs, as below:

![Image](https://github.com/user-attachments/assets/854f94ab-8523-4b9a-a4f0-58a512339ee9)

Note that we don't have assets for the connection error states yet – we'll continue to use the existing app images until we do.

A previous implementation as an example is in `BasicCardPresentPaymentAlert` in the PR https://github.com/woocommerce/woocommerce-ios/pull/13017/files before the generic alerts approach was implemented. Let's try avoiding many optional UI elements if we are reusing some SwiftUI components among views.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
