### ISSUE TITLE
Support opening inventory settings for product with non-integer stock quantity

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13184]
There has been a change regarding the REST API product schema to allow stock_quantity to be non-integer https://github.com/woocommerce/woocommerce/pull/48541.

The change introduces an issue in iOS where products (or product variations) with non-integer quantities disallow tapping on the inventory options row.

More context: peaMlT-HN-p2

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
