### ISSUE TITLE
[GLA Analytics] Add UI for Google Campaigns analytics card

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#13186]
In the first milestone, we need to add a new analytics card to display the Total Spend analytics:

* Title: `Google Campaigns`
* Metric: Total Sales for all campaigns (amount and percent change)
* List:
   * Left column title: `Campaigns`
   * Right column title: `Total Sales`
   * List items: Name of the campaign with subtitle displaying the spend amount per campaign (`Spend: $123`), and total spend per campaign in the right column
* See report: Link to the "Programs" web report for the selected date range, `/wp-admin/admin.php?page=wc-admin&reportKey=programs&path=%2Fgoogle%2Freports`

![Image](https://github.com/woocommerce/woocommerce-ios/assets/8658164/432541aa-950b-4d91-87be-72c6bbe9a657)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
