### ISSUE TITLE
Enable Inbox Notes, and hide/show CTA based on a new feature flag

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#13196]
Based on this: `C01SFMVEYAK/p1718898707646219?thread_ts=1717413205.477189&cid=C01SFMVEYAK`

Android issue: https://github.com/woocommerce/woocommerce-android/issues/11845

We should, in a single PR just to not merge something that will be partially completed:
- [x] Enable the Inbox Notes, currently hidden under a local feature flag.
- [x] Introduce a new local feature flag called `showInboxCTA`, `true` by default, that display the call to action in the inbox note card. If the feature flag is `false`, the Inbox Notes Cards will not display the Call to Action.
- [x] This solution should work for both Dynamic Dashboard and Inbox menu.

| Inbox Notes in Dynamic Dashboard             |  Inbox Notes under Menu |
:-------------------------:|:-------------------------:
![Simulator Screenshot - iPhone 15 Pro Max - 2024-06-28 at 14 14 10](https://github.com/woocommerce/woocommerce-android/assets/495617/0f79332a-f6c4-438b-90b9-b901744768d9) | ![Simulator Screenshot - iPhone 15 Pro Max - 2024-06-28 at 14 14 20](https://github.com/woocommerce/woocommerce-android/assets/495617/f2608d2c-ceb5-4df7-9d78-d69ab26514af)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
