### ISSUE TITLE
Improved Stats: Revenue always shows USD currency symbol

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1319]
**Describe the bug**

Store stats should show Revenue in the store's set currency.

This works as expected in the old store stats, but in the improved store stats the currency is always shown as USD.

**To Reproduce**
0. Ensure the WooCommerce Admin plugin is installed on your site (for improved stats).
1. Go to `/wp-admin/admin.php?page=wc-settings` in your site's dashboard.
2. Set your currency to a non-USD currency.
3. In the app, go to Settings > Beta Features and disable improved stats.
4. Go to My store and confirm that under "Revenue" in your store stats you see the non-USD currency symbol you selected.
5. Go to Settings > Beta Features and enable improved stats.
6. Go to My store and note that "Revenue" is now shown in USD.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/66037584-d99d3080-e507-11e9-82f5-705039c9a5c9.png" width="50%">

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active. [Note: And WooCommerce Admin, which is required for improved stats.]
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.1
- WooCommerce iOS version: 2.7.0.1 (TestFlight beta)

Originally reported by an anonymous TestFlight beta tester.

**Comment by mindgraffiti** [comment]
@jaclync this is fixed as of build v.3.2.0.1, but I did not close the ticket in case you found something else that needs adjusted to the Revenue stat.

<img src="https://user-images.githubusercontent.com/1062444/70467979-dab08800-1a8b-11ea-9507-d3149cce5b38.png" width="350" />

**Comment by jaclync** [comment]
looks like this issue wasn't closed before by the PR because it was targeting the release 2.7 branch instead of `develop`. just retested and the currency is showing correctly after relaunching the app, closing now
