### ISSUE TITLE
[GLA Analytics] Add Yosemite support for Google Listings & Ads analytics

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#13203]
We need to add support in `GoogleAdsStore` to request a store's campaign analytics from remote.

Considerations:

* We need to fetch all the campaign data, since the totals only include the data from the campaigns in the current page.
* If we fetch multiple pages of data, we need to sum the totals from each page to get the actual totals.
* For now we only need two totals metrics: sales and spend. However, in the next milestone we'll want all the totals, and since we have to fetch all the campaign data (not just the top campaigns for the current metric) we might as well fetch all the metrics by default so we have all the data we need at once. Then we can manipulate it locally for display.
* We currently don't cache the stats data used in the Analytics Hub.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
