### ISSUE TITLE
[Woo POS] Mock`CartViewModel`

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13207]
From review:

> In SwiftUI preview, we could also pass a constant value like passing Just< PointOfSaleDashboardViewModel.OrderStage >(.building) to CartViewModel(orderStage:). We can potentially have two previews, one for each order stage case.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
@iamgabrielma do you think it's required for M2 or can we close it / move it from the milestone? We have `MockCartViewModel` now used in tests. Do you think we should create something similar for previews as well?

**Comment by iamgabrielma** [comment]
> We have MockCartViewModel now used in tests. Do you think we should create something similar for previews as well?

Nice! I don't think it's necessary right now to have another one for previews: Since `MockCartViewModel` currently sits in the testing target and we use it for tests there accordingly, and the previews can use `CartViewModel()` directly without any other dependencies needed, we could leave it as it is until we actually need to make a specific one for previews. I'll close this issue!
