### ISSUE TITLE
Web view for campaign creation and success check

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#13218]
Check if site already has campaigns. If yes, show dashboard screen: /wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fdashboard.

Otherwise, start campaign creation flow:
- Entry point: wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fdashboard&subpath=%2Fcampaigns%2Fcreate
- Successful redirect page: /wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fdashboard&campaign=saved

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
