### ISSUE TITLE
[Woo POS] Remove product data fetch when going back to edit ongoing order

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13216]
Since https://github.com/woocommerce/woocommerce-ios/pull/13188#discussion_r1658059617 , if a merchant goes back to edit their current order, then we're syncing the up-to-date product data from the remote via `populatePointOfSaleItems()`

It shouldn't be necessary to force a data refreshed at this point, and we can keep the item list as it is, while the merchant can still pull to refresh the list to force a refresh on demand if needed.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
