### ISSUE TITLE
Xcode 11. Dark mode and notification cells

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#1322]
Building `release/2.7` with Xcode 11 has some interesting effects in the cells rendering notifications when the device is set to dark mode

<img src="https://user-images.githubusercontent.com/2722505/66042578-1aec0b00-e51d-11e9-8c2e-8a9d87b381f9.png" width="350"/>

Supporting Dark Mode for the Reviews tab is out of scope of this ticket. This issue is only to make sure that the app is usable on devices running dark mode when built using Xcode 11

**Comment by mindgraffiti** [comment]
Closing, fixed in #1323
