### ISSUE TITLE
[GLA Analytics] Fetch and display data on Google Campaigns analytics card

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#13222]
We need to fetch and display data on the Google Campaigns analytics card:

1. Check the Google Ads connection, and hide the card if the status is not `connected`.
2. Request the `sales` and `spend` data for the current and previous period:
   * Display the current Total Sales amount and percent change from the previous period.
   * Display a list of the top five campaigns (based on sales) with their sales and spend data.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
