### ISSUE TITLE
[Woo POS] M2 If there are no cart changes, checkout should not trigger an order sync API request

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#13236]
On the totals screen, if the merchant goes back to the product selector and then checks out again without making any changes to the cart, skipping the API request could be a performance improvement.

I'd suggest adding an early return to the order sync implementation to return the same order if the cart items stay the same (note that line items are aggregated for the same item in the order API request, whereas the cart items are all with quantity 1. Also, it's worth checking the item's price because the price could change after each product API sync).

https://github.com/woocommerce/woocommerce-ios/blob/64c579a6d5f8e038cd149638667ae60714403f65/Yosemite/Yosemite/Tools/POS/POSOrderService.swift#L112-L115

## Testing steps

Prerequisite: the store is eligible for POS and the feature switch is enabled in Menu > Settings > Experimental Features > POS
* Launch app
* Go to Menu > Point of Sale
* Add an item to the cart
* Tap `Checkout`
* Tap `Add More` to go back to the product selector
* Without changing anything, tap `Checkout` --> currently, the order is synced again even though there are no changes to the cart. In this case, we should skip order sync API request and continue to payment collection

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
