### ISSUE TITLE
[Woo POS] M2: Handle product edge cases

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13243]
The current limitation is to use simple physical products only, but there's some other criteria within simple products that we should test and take into account. For example:
- Products without price should be non eligible
<img width="811" alt="Screenshot 2024-07-04 at 14 20 59" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/f661096c-0b8e-490e-bb56-6472464e1708">

* What price we'll be showing when a product has:
  * price
  * regularPrice
  * salePrice
* What if `purchasable` is false? Should be eligible or not?
* `soldIndividually`? Part of a bundle? etc, ...

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
P2: pdfdoF-5d5-p2

**Comment by joshheald** [comment]
Is this done with #13503 @iamgabrielma ? I don't think it is, but they're in the same area so wanted to check.

**Comment by iamgabrielma** [comment]
Thanks for following up. I'll close this one: The main changes regarding eligibility were done on https://github.com/woocommerce/woocommerce-ios/pull/13503, and https://github.com/woocommerce/woocommerce-ios/pull/13522. The remaining item for the different prices has been logged as low priority on https://github.com/woocommerce/woocommerce-ios/issues/13502
