### ISSUE TITLE
View to display the selected product image.

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13246]
<img width="322" alt="image" src="https://github.com/woocommerce/woocommerce-ios/assets/524475/6173aa4c-8239-4a6b-902c-2c2d295e57b3">

- Pass selected package photo to preview screen
- Display package photo in preview screen.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
