### ISSUE TITLE
[GLA Analytics] Tracks events (M1)

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#13248]
There are no new tracks events for M1, but we should confirm:

* If the merchants taps "See report" we track `analytics_hub_view_full_report_tapped`, and the custom prop `report` has value `googleCampaigns`.
* If the merchant customizes the analytics hub, we track `analytics_hub_settings_saved`, and the custom props `enabled_cards` and `disabled_cards` with `googleCampaigns` included with the expected property (depending on whether it is enabled or disabled).

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
Confirmed both tracks events are recorded as expected. 👍
