### ISSUE TITLE
Xcode 11. Dark mode and Order cells

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#1324]
Building `release/2.7` with Xcode 11 has some interesting effects in the cells rendering orders when the device is set to dark mode
<img src="https://user-images.githubusercontent.com/2722505/66043384-47088b80-e51f-11e9-810a-1201a345c681.png" width="350"/>

Fully supporting Dark Mode for the Orders tab is out of scope of this ticket. This issue is only to make sure that the app is usable on devices running dark mode when built using Xcode 11.

**Comment by pmusolino** [comment]
On release 3.0 I'm no more able to replicate this issue. 

![Simulator Screen Shot - iPhone 11 Pro - 2019-11-11 at 15 40 13](https://user-images.githubusercontent.com/495617/68595397-a8fece00-0499-11ea-81d6-1223fb2e03a2.png)
