### ISSUE TITLE
Xcode 11. Dark mode and Order Details

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#1325]
The Order Details screen is not legible when the building using the public release of Xcode 11.

<img src="https://user-images.githubusercontent.com/2722505/66043879-9dc29500-e520-11e9-9dd7-758ab9feb669.png" width="350"/>

The scope of the ticket is just to make sure that this screen is legible on Dark Mode, not fully supporting it.

**Comment by mindgraffiti** [comment]
Closing. Fixed in #1329. (GH automation fail)
