### ISSUE TITLE
Add text field for short description

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13254]
- Add a text field for short description
- Move package photo view below name and description section

Internal - p1720140316203299/1720090796.407329-slack-C03L1NF1EA3

| Full screen | Short description field area  |
|--------|--------|
| ![image](https://github.com/woocommerce/woocommerce-ios/assets/524475/6260ca4d-6bed-4a78-94a2-d34a7ee07137) | ![image](https://github.com/woocommerce/woocommerce-ios/assets/524475/41d6e4d8-f8e7-49ba-ae8b-6a876da59319) |

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
