### ISSUE TITLE
Remove the package flow and related code.

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13266]
Listing the code that needs to be removed. This is not a definitive list and please remove other code if applicable. 
- `AIToneVoiceView`
- `AddProductFeaturesView` and `AddProductFeaturesViewModel` #13106
- `LegacyProductDetailPreviewView` and view model
- Remove `aboutProduct` case from `AddProductWithAIStep` enum
- Package flow related view and view models
- `AddProductNameWithAIView`

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
