### ISSUE TITLE
[Woo POS] M2: Present "Reader disconnected" initial modal when needed

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13264]
p91TBi-bzd-p2

<img width="688" alt="Screenshot 2024-07-08 at 09 34 26" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/2de5b5bc-6ba0-40b5-be4c-9a17ee442d90">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
Pretty sure this is out of the designs now
