### ISSUE TITLE
[Woo POS] M2: Adjust cart items for long product names and localization and update design

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13262]
We have to test and find a common way to resolve product names that are too long to fit available space, localization, and prices too long for the row. Along with review: https://github.com/woocommerce/woocommerce-ios/pull/13241#discussion_r1665300612

> the button is pushing the labels and not allowing them to be in one line.
<img width="360" alt="Screenshot 2024-07-08 at 08 40 53" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/068ceb0e-af27-459f-ab8e-6ea48a7f88ad">

New design:

![Image](https://github.com/user-attachments/assets/b9145d7a-d490-4fe9-bde2-e950483327df)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
