### ISSUE TITLE
[Woo POS]: inline message not reset, showing payment successful when doing new transaction

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#13275]
When we successfully finish a payment and try to do another transaction, for a brief moment we see the "Payment successful" message.

As @staskus mentioned in https://github.com/woocommerce/woocommerce-ios/pull/13166#discussion_r1668699240, likely `cardPresentPaymentInlineMessage` is not reset.

https://github.com/woocommerce/woocommerce-ios/assets/4062343/c4a9568d-70ec-43d3-b941-88e2c8f04439

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
