### ISSUE TITLE
[Woo POS] M2: Exit POS modal presentation

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13278]
From M2 design proposal:

<img width="500" alt="Screenshot 2024-07-09 at 16 30 42" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/3e6d357a-df11-4bcc-b4e2-95b8edd2d44b">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
