### ISSUE TITLE
[Barcode Scanner] Update icons to SF Symbols

### ISSUE THREAD

**Issue by joe-keenan** [woocommerce/woocommerce-ios#13271]
**Describe the bug**
As part of an effort to improve consistency across the app, we should be using SF Symbols for all icons. The barcode scanner icon is old and needs to be updated. 

**Screenshots**
| **Current** | **New** |
|--------|--------|
| ![iOS - Orders - Old](https://github.com/woocommerce/woocommerce-ios/assets/95003933/e96741ca-12cd-4c2b-b3e2-08493e7128af)  | ![iOS - Orders - New](https://github.com/woocommerce/woocommerce-ios/assets/95003933/23db52b6-2947-4db6-ba69-b69dfa7525ad)  |
| ![iOS - Products - Old](https://github.com/woocommerce/woocommerce-ios/assets/95003933/fdb63ebc-2aec-4819-b427-39f3325d4226) | ![iOS - Products - New](https://github.com/woocommerce/woocommerce-ios/assets/95003933/3a026596-907a-460d-98d1-61cf3abe6908) |
| ![iOS - New order - Old](https://github.com/woocommerce/woocommerce-ios/assets/95003933/3c730fc6-158b-43be-9ed6-ccefdd2fce60) | ![iOS - New order - New](https://github.com/woocommerce/woocommerce-ios/assets/95003933/f9fe8b28-16dc-4613-ac54-b5da82cc7f70) | 

**Expected behavior**
Update the current barcode icon to use the SF Symbols one on the Orders List, Products List, and Create Order screens.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
