### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#13273]
Event | Trigger | Properties
-- | -- | --
googleads_entry_point_displayed | When the Google for Woo entry point is shown to the user. | source
googleads_entry_point_tapped | When the Google for Woo entry point is tapped by the user and opens to campaign creation. | source, type, has_campaigns
googleads_flow_started | When the Google for Woo webview is first loaded. | source
googleads_flow_canceled | When the Google for Woo webview is dismissed without completing the flow. | source
googleads_campaign_creation_success | When the Google for Woo webview is automatically dismissed after completing the creation | source
googleads_flow_error | When the Google for Woo webview returns an error. | source

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
