### ISSUE TITLE
[GLA Analytics] Add UI for Google Campaigns metrics menu

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#13279]
We need to add the UI for a menu to select the metric to display on the card:

* Row with the label `Metric` and the selected metric on the left, and an icon to open the menu on the right.
* Menu has a list of all available metrics, with a checkmark next to the selected metric.
* Tapping a new metric reloads the card data for the newly selected metric.

Metric menu (closed)|Metric menu (open)
-|-
![Image](https://github.com/woocommerce/woocommerce-ios/assets/8658164/1e55477f-d2a5-4dc5-8d30-6dcc0fed4286)|![Image](https://github.com/woocommerce/woocommerce-ios/assets/8658164/04d38586-4663-4282-866e-b480c2f6e5d8)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
