### ISSUE TITLE
[Woo POS] M2: Update `ItemSelector` to switch between different internal states

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13276]
In M1 we just needed to handle loading/loaded via a simple `isSyncingItems` boolean. For M2 we want to handle further states and potential errors, for example:

```
enum LoadingState {
  case loading // During fetch & reload
  case loaded(hasItems: Bool) // After completion, could be no items or non eligible items
  case error // Other errors
}
```

`loaded` and `error` could be specialized as well, or use associated values, whatever seems better.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
