### ISSUE TITLE
[Orders List] Fix text wrapping on name field

### ISSUE THREAD

**Issue by joe-keenan** [woocommerce/woocommerce-ios#13272]
**Describe the bug**
The name field on the main orders list is often wrapping to two lines. My guess is that the forced spacing between the left and right content is too large.

**Screenshots**
| **Current** | **New** |
|--------|--------|
| ![iOS - Orders List Row - Old](https://github.com/woocommerce/woocommerce-ios/assets/95003933/8bdcee2e-c467-43e6-9512-a93c74ed7311) |  ![iOS - Orders List Row - New](https://github.com/woocommerce/woocommerce-ios/assets/95003933/03b4f4b1-778b-40e1-ba13-381cda1cc75c) | 

**Expected behavior**
Names should only wrap when they are long enough that the text gets close to the order value on the right. There should still be at least a 16pt gap between text and value.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
