### ISSUE TITLE
Reduce requests upon generating details again.

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13287]
When the user taps the "Generate Again" button.
Check the possibility of skipping sending network requests for synching tags and categories. 

<img src="https://github.com/woocommerce/woocommerce-ios/assets/524475/c8b85ae5-7003-44cf-99b0-1482c0d630ff" width="320"/>

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
