### ISSUE TITLE
Product creation with AI: Media picker popover not fully visible in iPad

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#13291]
The popover doesn't display all the content on iPad. It'd be nice if it points to the ellipsis button too.

<img src="https://github.com/woocommerce/woocommerce-ios/assets/5533851/63852381-ee9b-4ed1-a0ea-11f1b6fd84b1" width=320 />

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
