### ISSUE TITLE
[Woo POS] Expand Unit test coverage for PointOfSaleDashboardViewModel

### ISSUE THREAD

**Issue by soundsokay** [woocommerce/woocommerce-ios#13306]
Follow-up to [issue 13210](https://github.com/woocommerce/woocommerce-ios/issues/13210), builds on the initial tests to add coverage, particularly for code added in #13270.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
