### ISSUE TITLE
[Woo POS] M2: Remove duplication on `populate` vs `reload`

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13307]
From review: https://github.com/woocommerce/woocommerce-ios/pull/13298#discussion_r1673552488

The implementations for `reload()` vs `populate()` that can be collapsed into one. Something that shouldn't be shared is the "loading" view when the model is on loading state, as we want the initial loading to enter in POS mode to be different than the loading because the data is being refreshed.

We should also improve unit test coverage and triangulate more cases where possible (eg: 0 products, 100 products, 100+ products, etc, ... )

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
