### ISSUE TITLE
Product Creation AI v2 M1: Define tracking events

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13300]
Define tracking events for M1 work. (If needed, create test funnels to ensure project success can be measured.)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by selanthiraiyan** [comment]
Tracking events defined at pffQ75-yr-p2#metrics
