### ISSUE TITLE
[Woo POS] M2: Remove cart collapse behaviour

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13318]
While in M1 we were collapsing the cart when empty, for M2 we want to display the cart at all times:

<img width="805" alt="Screenshot 2024-07-15 at 11 11 45" src="https://github.com/user-attachments/assets/657d971f-b1b7-4466-90a1-0285d9ee4223">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
