### ISSUE TITLE
[Woo POS] M2: Simple products only banner

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13317]
<img width="805" alt="Screenshot 2024-07-15 at 10 56 58" src="https://github.com/user-attachments/assets/fedf2455-241d-40b8-9c69-97d28b2b2efe">

<img width="808" alt="Screenshot 2024-07-15 at 11 02 21" src="https://github.com/user-attachments/assets/f3cebc6e-3190-46aa-a595-19286d786efb">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
