### ISSUE TITLE
Xcode 11 + Dark mode: Settings

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1332]
The table view cells on the Settings screen & many of the screens from the Settings appear to have Dark mode issues. This issue fixes all the screens on and from Settings

![IMG_7354](https://user-images.githubusercontent.com/1945542/66099489-b5118900-e5d9-11e9-8f07-c8ade9bcc52b.PNG)
![IMG_7355](https://user-images.githubusercontent.com/1945542/66099490-b5118900-e5d9-11e9-8962-1a674547ba87.PNG)
![IMG_7356](https://user-images.githubusercontent.com/1945542/66099492-b5aa1f80-e5d9-11e9-8508-6e1f4d19e01c.PNG)
![IMG_7357](https://user-images.githubusercontent.com/1945542/66099493-b5aa1f80-e5d9-11e9-85a9-2207e9d2b26c.PNG)

**Comment by mindgraffiti** [comment]
Closing, fixed in #1337. @astralbodies how do I fix the automation that used to close our tickets?

**Comment by astralbodies** [comment]
I believe GitHub only closes the issue when the target branch for a PR is the mainline (`develop` in our case).

**Comment by mindgraffiti** [comment]
Ohhh. That makes so much more sense. All the open issues were targeting the 2.7 release branch.
