### ISSUE TITLE
Inbox: Remove plugin check for eligibility checker

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#13322]
Previously in the eligibility checker for Inbox, we were checking version for the Woo plugin assuming there would be a change to filter inbox.

In #13214 we enable the Inbox feature flag but didn't remove the Woo plugin check. This check is now redundant and should be removed so that the eligibility check can be synchronous.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
