### ISSUE TITLE
[Woo POS] M2: Floating control for menu and reader status

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#13338]
p91TBi-bHy-p2

![Image](https://github.com/user-attachments/assets/ee8fb253-a0aa-4254-a857-5099f8f5c66b)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
