### ISSUE TITLE
[Woo POS] M2: Payment success UI update

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#13344]
![Image](https://github.com/user-attachments/assets/d5846031-5275-4822-828b-c776c9efc66d)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by backwardstruck** [comment]
Linking the related Android GH issue and PR:

https://github.com/woocommerce/woocommerce-android/issues/11828

https://github.com/woocommerce/woocommerce-android/pull/12165

FYI @bozidarsevo the decision was made in [this](https://docs.google.com/document/d/10JKyruY8xHMMTV3RRGlPkVeTh-wiVMtzSaN-lgIN6DU/edit?usp=sharing) meeting to leave the New Order button in white for now. It may be changed later.
