### ISSUE TITLE
[Blaze] Validate product URL

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13347]
#### Problem 
Currently, we don't validate that a product has a non-empty `permalink` value to be able to create a Blaze campaign.

Internal - p1721133938444799/1721099021.821499-slack-C01PKMY9T1S

The following happens when a product has an empty string as a `permalink` value. Notice that the campaign is submitted with an empty product URL.

https://github.com/user-attachments/assets/12d19763-3d02-4804-8151-30ecaef9d6b9

#### Reason

I think the product URL becomes empty when the decoding fails due to some unexpected reasons, as mentioned [here](https://github.com/woocommerce/woocommerce-ios/blob/trunk/Networking/Networking/Model/Product/Product.swift#L349-L359). 

#### Solution

Validate that `productURL` is not an empty string [here](https://github.com/woocommerce/woocommerce-ios/blob/trunk/WooCommerce/Classes/ViewRelated/Blaze/CampaignCreation/BlazeCampaignCreationFormViewModel.swift#L133-L136)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by JorgeMucientes** [comment]
We don't apply any transformations/decoding to the product `permalink` in Android. So this field should never be null when opening the Blaze campaign creation flow. I don't think we need to add extra check to ensure the field is null.
