### ISSUE TITLE
[GLA Analytics] Tracks events (M2)

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#13349]
Add the following event:

* When a new metric is selected, track the `analytics_hub_card_metric_selected` event.
   * Custom prop: `card` with the name of the card (`googleCampaigns`) — For now it will always be `googleCampaigns`, but in the future we can add a metrics menu to other cards and track their selections with the same event.
   * Custom prop: `selected_metric` with the selected metric (e.g. `sales` or `spend`).

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
