### ISSUE TITLE
[Woo POS] M2: Card reader connection UI improvements

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13353]
Ref: pdcxQM-3PY-p2#comment-3046

> Not sure if UI issues are known, the buttons on the reader-related screens are not looking great

<img width="446" alt="Screenshot 2024-07-17 at 09 13 14" src="https://github.com/user-attachments/assets/e52fb777-429d-4b4a-a84d-d543c2e94ca7">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
Already covered by #13175
