### ISSUE TITLE
[Blaze] Select destination URL when product URL is empty

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13355]
Originally raised during a PR review https://github.com/woocommerce/woocommerce-ios/pull/13351#pullrequestreview-2181859166

Sometimes a product can have a empty `permanlink` due to some unexpected reasons, as mentioned [here](https://github.com/woocommerce/woocommerce-ios/blob/trunk/Networking/Networking/Model/Product/Product.swift#L349-L359).

Allow the user to select or type a custom product URL. 

<img src="https://github.com/user-attachments/assets/dbba3c4f-e37d-41aa-8471-8d5b4b6f853f" width=320 />

Explore any of the following options

- Display a screen with a text field where the user can paste a URL.
- Display a web view pointing to the site home. The user can navigate to the page they want and tap Done to select the URL of that page.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by itsmeichigo** [comment]
Another (and simpler) option as suggested by @hichamboushaba in p1722281016526459/1722280392.435889-slack-C03L1NF1EA3: 

> [...] the URL that we get by default when permalinks are disabled, which is in this form: {site_url}?post_type=product&p={product_id}, this URL works generally in all cases, so it should also work when the permalink is not available for any reason

We can update `Product.swift` to use this URL form when decoding the `permalink` fails.
