### ISSUE TITLE
[Woo POS] M2: Simple products only modal

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13357]
Continuation of https://github.com/woocommerce/woocommerce-ios/issues/13317 , the designs show a different banner once the first one has been dismissed. This modal will appear when the merchant taps `?` 

<img width="1164" alt="Screenshot 2024-07-17 at 12 53 26" src="https://github.com/user-attachments/assets/3def2d1e-0e43-46eb-a839-b44593f640e5">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
