### ISSUE TITLE
[GLA Analytics] Add logic for displaying call to action

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#13368]
We should display the Google Campaigns call to action, instead of the analytics card, when:

* The extension is installed and active on the store.
* The Google Ads account is connected (`status` field from `GET /wc/gla/ads/connection` has value `connected`).
* There are no campaign analytics for the selected period.

Note: We can use the second check to determine if the extension is installed and active; if it isn't, it will return a 404.

We should also confirm this is the same criteria used for displaying the new campaign creation flow. We don't want to show the call to action if the merchant does not qualify to create a new campaign.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
We can use `GoogleAdsEligibilityChecker` for checking if the store is eligible for creating a new campaign:

* `isSiteEligible(siteID:)` checks all of the requirements for campaign creation (e.g. the feature flag is enabled, the plugin is the correct version).
