### ISSUE TITLE
[Woo POS] M2: Use full-screen on product list error/empty load

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13360]
When product list fails to load or errors out, we should hide other view components that are permanently shown, for example the `CartView` or the `HeaderBanner`: 

![Image](https://github.com/user-attachments/assets/2f3594b3-29fc-4a06-a18e-55793ecabf4b)
<img width="514" alt="Screenshot 2024-07-17 at 13 23 57" src="https://github.com/user-attachments/assets/fd02d1ba-22b8-460a-9f04-b0ff4475ee7c">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
