### ISSUE TITLE
Google Ads: Detect campaign creation success after setup

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#13363]
When a store has just set up for Google Ads, the first time campaign creation is opened, there page displays 3 steps for setup. After campaign creation completes, there callback URL contains param `guide=campaign-creation-success` instead of `campaign=saved`.

We should update the completion detection to include the special case.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
