### ISSUE TITLE
Update Dashboard Data Conditionally

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#13377]
### After changes in the dasboards cards habe been applied

- #13369
- #13370 
- #13371 
- #13372 
- #13373 
- #13374 
- #13375 
- #13376 

### We need to 

- [x] Update dashboard data automatically when the apps comes into the foreground if the last sync data is **older than 30 minutes ago**. Similar to how orders list works. #13131

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
