### ISSUE TITLE
[Application Passwords] Add ability to manage product passwords

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#13387]
In WooCommerce 8.1, the REST API has been [improved](https://github.com/woocommerce/woocommerce/pull/39438) by adding a new field for the `products` response to allow managing the visibility password, this will allow the mobile apps to support this feature when the site is accessed using Application Passwords.

Android issue: https://github.com/woocommerce/woocommerce-android/issues/9801

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
