### ISSUE TITLE
[Woo POS] M2: Criteria for POS Simple Physical Products

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-ios#13394]
We need to narrow down the criteria for what constitutes a "Simple Physical Product" in our POS system. This is crucial for usability and consistency across platforms.

Criteria:

Product type | simple
-- | --
Product status | published
Product price | Regular/Sale
Purchasable | true/false (We wouldn’t limit here)
Virtual | false
Downloadable | false
Sold individually | nil

For more context: pdfdoF-5d5-p2

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
Just checking @AnirudhBhat , I believe the low priority tag is not for the simple physical products criteria as a whole, but specifically for the distinction between regular/sale prices shared here? pdfdoF-5d5-p2#comment-6255

**Comment by AnirudhBhat** [comment]
That's correct @iamgabrielma. Thanks for pointing this out! I've created another ticket for formatting price display here: https://github.com/woocommerce/woocommerce-ios/issues/13502
