### ISSUE TITLE
Xcode 11 + Dark mode: adding a note

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#1340]
The screen to add a note is not legible when building using the public release of Xcode 11.
<img src="https://user-images.githubusercontent.com/2722505/66153394-b6fc3c00-e61b-11e9-8e9a-60af5b11d2b9.png" width="350"/>

**Comment by mindgraffiti** [comment]
GH automation is broken. Closing, as this was fixed in #1341
