### ISSUE TITLE
[Woo POS] M2: Get Support - open from menu

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#13401]
As a first step we should open Support screen from the app.
Next step would be to use a custom POS flag for the support.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by samiuelson** [comment]
As [discussed](https://a8c.slack.com/archives/C070SJRA8DP/p1723543907924359?thread_ts=1723445526.122729&cid=C070SJRA8DP), let's send a Zendesk support request with a new tag `origin:point-of-sale`

On Zendesk it should be visible here:
![Image](https://github.com/user-attachments/assets/e68fd050-baee-45b4-b94a-93d5d540d8d4)
