### ISSUE TITLE
[Woo POS] M2: Fonts and Dynamic Type on POS

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#13426]
1. Define consistent Type styles to match designs: p1722253485425949-slack-C070SJRA8DP
2. Make sure fonts support dynamic type and scale when default accessibility values are scaled
3. Replace existing usage of title, body, and detail fonts within POS
5. Create additional issues for views that require special handling of dynamic type (e.g Product Images increasing in size when increasing dynamic type)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by backwardstruck** [comment]
I think this issue is iOS only right?

**Comment by staskus** [comment]
@backwardstruck yes, it's for our internal improvements. You may not have any issues with this on Android.
