### ISSUE TITLE
Xcode 11 + Dark mode: Order Details product cell SKU text isn't visible 

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1342]
The SKU text has the same color as the background:

normal | highlighted
-- | --
![Simulator Screen Shot - iPhone Xʀ - 2019-10-04 at 09 24 22](https://user-images.githubusercontent.com/1945542/66174976-44767500-e68a-11e9-8970-f76e60585e3f.png) | ![Simulator Screen Shot - iPhone Xʀ - 2019-10-04 at 09 24 24](https://user-images.githubusercontent.com/1945542/66174977-44767500-e68a-11e9-91cc-417ddd9175c7.png)

**Comment by mindgraffiti** [comment]
Completed in #1343. GitHub's automation appears broken again.
