### ISSUE TITLE
[Woo POS] M2 Error: Reader not connected in Checkout

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13431]
![Image](https://github.com/user-attachments/assets/64ca45bc-c1b6-4e51-b7f0-487162c39292)

- UI
- Connect the reader
- Start payment process when reader is connected

The payment preparation process should start whether the small floating button is used, or the large purple button.

This should only happen when we're actually on the Checkout screen. 

Note – if it proves difficult to correctly implement this automatic payment preparation, we can show the `Collect Payment` button in this case instead. Don't spend a long time on making that work!

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
Related to #12942 – we can probably close both of these at the same time...
