### ISSUE TITLE
[Woo POS] Using `Connect your reader` floating button on the Checkout screen prevents collect payment

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13445]
## Description

If you go to the POS checkout screen without a reader connected, and tap the floating `Connect your reader` button, the `Collect payment` button is removed and payment is not possible until you go back to product selection, and forward again.

This is because when a reader's connected, we expect this screen to automatically start the payment, but it only does that each time we move to this screen.

If the reader gets connected while the checkout screen is shown, we should continue to show the `Collect Payment` button.

https://github.com/user-attachments/assets/81c9a814-4122-4b56-bc3a-9461fc4770c0

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
Closed in favour of #13431
