### ISSUE TITLE
[Woo POS] M2: Cart and payment state transitions

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13444]
Related tasks: https://github.com/woocommerce/woocommerce-ios/issues/13346, https://github.com/woocommerce/woocommerce-ios/issues/13343
Designs: TfaZ4LUkEwEGrxfnEFzvJj-fi-2530_20890
Animation: p91TBi-bHy-p2

- Cart View sliding to the left side
- ~~ ~~Card icon in 'Tap, Swipe, Insert view' animating~~ ~~ (Out of scope for now)
- Card icon in 'Tap, Swipe, Insert view' transitioning to seamlessly 'Payment Processing view'
- 'Payment Processing view' only centering after it appears
- ~~ ~~Card icon in 'Payment Processing view' animating~~ ~~ (Out of scope for now)

https://github.com/user-attachments/assets/3aa5dafd-0ca5-46f5-93a8-c272af0c52c1

https://github.com/user-attachments/assets/198c5277-2353-4bc1-b4a6-8e813ead0c27

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
