### ISSUE TITLE
[Woo POS] Use SF symbols for icons, not images

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13458]
## Description
I've noticed some icons we're using are added as images, but could be used as SF symbols – e.g.

`arrow.uturn.backward` for the arrow in on the New Transaction button:

![Image](https://github.com/user-attachments/assets/34cb5e21-9488-450c-ae2f-c199774eaf39)

`rectangle.portrait.and.arrow.forward` for the Exit POS button

![Image](https://github.com/user-attachments/assets/ebd06fac-02ce-4ecd-a78b-062761fb4b54)

Same for dismissing products banner, getting support, removing an item from the cart. Check the images in the POS folder for any icon-like images, remove and replace at the callsites.

Using SF symbols removes code, and makes sure the images are appropriate for both LTR and RTL locales.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
The SFSymbol for the CartView's back button has been handled here: https://github.com/woocommerce/woocommerce-ios/pull/13631
