### ISSUE TITLE
[Woo POS] Use separate views for different payment states

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13451]
During M1 we implemented `POSCardPresentPaymentMessageView` that was reused by many different payment states. However, each state differs slightly in fonts, images, and loading indicators, making unnecessaraly `POSCardPresentPaymentMessageView`  complex.

Related discussions
- https://github.com/woocommerce/woocommerce-ios/pull/13166#pullrequestreview-2146185753
- https://github.com/woocommerce/woocommerce-ios/pull/13443#pullrequestreview-2205373485

**Solution**

Use small simple views for each of the payment states. Share view constants such as fonts, sizes, and spacing if necessary.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
