### ISSUE TITLE
[Woo POS] M2: Add Connection Complete state for standalone card reader connections

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13470]
When connecting using the floating "connect your reader" button, there isn't an obvious success state, which is a little jarring.

We should add this state, but ideally it shouldn't be shown when the connection is done using the `Collect Payment` button shown on the checkout when the reader isn't connected – because that goes directly into the payment collection flow.

![Image](https://github.com/user-attachments/assets/c5fd42ab-8907-45da-be8d-b755e61f119c)

It will also need a dismiss button, and it might be nice if it would disappear after a few seconds of no interaction.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
