### ISSUE TITLE
[Woo POS] M2: Dark mode support

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13471]
Dark mode does not work at the moment in POS.

Our colours are defined with light-mode only RGB values, and our images don't have dark mode variations either.

A few fonts are using semantic system colours, so they change from black to white when entering dark mode, but that just means they aren't visible any more on their white backgrounds.

Before we go much further, we should update our colours to fix this...

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
