### ISSUE TITLE
[Woo POS] M2 Error: Loading totals

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13478]
Show error when order total calculation fails.
Discussion: TfaZ4LUkEwEGrxfnEFzvJj-fi-2530_16015#878692852 

![Image](https://github.com/user-attachments/assets/ab1cee6a-3f70-4253-9c2b-05ded60d9c9c)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
