### ISSUE TITLE
[Woo POS] M2 Errors: Payment failed

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13481]
Implement UI for Payment Failures:
- paymentError
- paymentErrorNonRetryable

![Image](https://github.com/user-attachments/assets/1c6471e2-18e1-451e-83b1-1371470532f4)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
