### ISSUE TITLE
[Woo POS] M2: Hide POS Mode for ineligible users

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13483]
The 'Point of Sale Mode' menu row should not be visible for users who are not eligible for beta. Add remote feature flag to POS eligibility criteria.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
Closed via https://github.com/woocommerce/woocommerce-ios/pull/13815 and https://github.com/woocommerce/woocommerce-ios/pull/13839
