### ISSUE TITLE
[Woo POS] M2 Error: Loading products

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13480]
![Image](https://github.com/user-attachments/assets/c93c2a7f-40ec-41b7-a318-8b6ac814daa4)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
Possibly related: https://github.com/woocommerce/woocommerce-ios/issues/13360

**Comment by iamgabrielma** [comment]
Thanks for the crosslink! I'll start the work on https://github.com/woocommerce/woocommerce-ios/issues/13360 today/tomorrow, so I'll assign myself to this one as well @staskus since we're dealing with similar logic.
