### ISSUE TITLE
Watch: Add Sentry support

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#13497]
# Description

Add Sentry crash logging support to the Woo Watch App

# Context

- Installation seems quite straightforward. I followed this [guide](https://href.li/?https://docs.sentry.io/platforms/apple/guides/watchos/).
- We may need to spend a day sharing all the custom configurations that we have on the watch app target.
- We also need to make sure that our Exceptions Catches dashboards are properly capturing the watch app events.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
