### ISSUE TITLE
Dynamic Dashboard: Missing tracking events for custom range of Analytics dashboard cards

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#13499]
**Problem**
When switching to dynamic dashboard, we missed most of the tracking events for the custom range project [pe5sF9-2r1-p2].

**Expectation**
All tracking events should be restored to track performance for custom ranges.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
