### ISSUE TITLE
[Woo POS] Possible to come back from checkout when payment is processed

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13495]
POS allows one to come back from the checkout screen while in "Tap, swipe, insert" state. However, if we press back and at the same time payment starts being processed, POS gets stuck in the wrong state.

I'm not sure if it should be solved from View Model site or from the Services side. However, I expect that after we call `cancelPayment`, the previous payment should no longer affect the POS state. 

https://github.com/user-attachments/assets/ac54d32f-0daa-42ee-97e1-8eef696b5b23

It could be related to https://github.com/orgs/woocommerce/projects/247/views/7?sliceBy%5Bvalue%5D=iOS+%F0%9F%8D%8E&pane=issue&itemId=73045105

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
