### ISSUE TITLE
[Login] Starting a new store button does not work

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13515]
## Description

The `Starting a new store?` button on the app's first screen does not do anything.

Previously, it opened a web view to show the merchants options. This was removed in #13379 

Restoring the following code in `AuthenticationManager` appears to fix the issue:

    func showSiteCreationGuide(in navigationController: UINavigationController) {
        analytics.track(event: .StoreCreation.loginPrologueStartingANewStoreTapped())
        
        guard let url = try? AuthenticationConstants.hostingURL.asURL() else {
            return
        }
        let webView = SFSafariViewController(url: url)
        navigationController.present(webView, animated: true)
    }

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
