### ISSUE TITLE
[Woo POS] Darker background for half-screen error views

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13549]
Some views, mainly 'Reader Disconnected' and `Error checking order` should have a darker background.

We cannot set a background color to message view, since `TotalsView` display `readerMessageView` with padding and different centering. One idea is to restructure TotalsView so cardReaderView would be placed inside a larger container, which would touch the leading, trailing, and top sides. When required, we can change the color of this container, otherwise cardReaderView placement would be unaffected.

| Error checking order | Reader Disconnected |
|---------|---------|
| ![Image](https://github.com/user-attachments/assets/9ec3f5dc-0bff-44c3-88e2-46a82ae1c22d) | ![Image](https://github.com/user-attachments/assets/42af86ac-2401-4cd7-a78b-c77bb679dca5) |

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
