### ISSUE TITLE
Creating a shipping label UI

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-ios#13550]
```[tasklist]
### UI Elements
- [x] Collapsible items section
- [x] Hazmat section (no navigation for now)
- [x] Add a package button (no navigation for now)
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14041
- [ ] https://github.com/woocommerce/woocommerce-ios/issues/14044
```

![Image](https://github.com/user-attachments/assets/a18cd04b-6dd7-492c-ba89-511f9366d64b)

Some considerations from design:

> - We’ll use the existing entry point for now. I’ll revise the shipping labels section in Order Details in M4.
> - Addresses will not be editable for now. Those designs will be in M2.
> - It’s not 100% clear from the image, but I’m proposing an adjustment to the details sheet: I think it should go full screen. This is what other apps do with similar sheets, and it feels more confident than the semi-screen version we use in order creation right now. There will always be enough content in the label order details to justify it, too (in order details, the totals section can sometimes be relatively short).
The options at the bottom should be fixed, and the rest should be scrollable. I’ve proposed how they could be side-stacked in landscape format in Figma.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
