### ISSUE TITLE
Adding a package UI

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-ios#13551]
![Image](https://github.com/user-attachments/assets/de39b1f1-9e55-4d11-ac87-f3dce083f7fd)

![Image](https://github.com/user-attachments/assets/58a9be32-3920-456b-9158-25a7c72937fd)

Design considerations:

> - This is almost the same as what’s on the web.
> - By opening it in a sheet, we can let the lists run long without using accordions (which are always awkward on mobile and rarely used anymore).
> - Saving a package template will match the web quite closely.
This isn’t on the web, but providing a quiet way to remove saved packages feels natural.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
We also need to add the UI for the selected package and shipment weight on the main shipping label screen:

![Image](https://github.com/user-attachments/assets/a9322454-6962-4c35-9c78-55cda7b253ae)

**Comment by bozidarsevo** [comment]
There might be some minor tweaks here and there to when we add networking calls, but I am closing this since the UI is here.
