### ISSUE TITLE
After purchasing a shipping label UI

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-ios#13557]
![Image](https://github.com/user-attachments/assets/c04b8642-6011-4a86-8a2d-5625693f8734)

Design considerations:

> - After purchasing, you’re no longer “creating a shipping label,” and I think the screen title should reflect this. This deviates from order creation, but I don’t think it feels unexpected.
> - As mentioned earlier, let’s keep the order details screen the same for now – with one exception: Change the text on the button and have it navigate to the success screen.

❗ We will work on the updated order details screen on M4

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
