### ISSUE TITLE
System Status Report in Help menu during logged out state is not usable

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#13560]
System Status Report requires authentication, so it should be removed from Help menu during login.

To replicate:

1. log out of the app if you haven't,
2. tap Log in,
3. tap "Help" on top right,
4. notice System Status Report is shown but not responsive when tapped.

![image](https://github.com/user-attachments/assets/5dc14f17-7900-4d59-ad5e-7214825d36df)

h/t @rachelmcr for the report.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
