### ISSUE TITLE
Web view: Blank screen with no loading indicator while authenticating

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13561]
Identified in an iOS quality walkthrough - Internal - p91TBi-bPj-p2

#### Problem
Authenticated webviews: Anywhere we use authenticated webviews, I can end up on a blank screen that lasts while things are loading in the background (with no loading indicator or any other indication that things are happening). This can last a very long time (e.g. ~1 minute), I believe while the authentication is done in the background.

| Header | Header |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/5b23e687-2ef0-41d4-ae4c-a830ad5ebb7f) | ![image](https://github.com/user-attachments/assets/0e1b9c40-4382-45fd-9b68-a5fc0567ee06) | 

#### Expected behaviour

Add a loading indicator while authenticating the web view

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
