### ISSUE TITLE
Subscriptions: "Report Subscription Issue" button not working

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13564]
Identified in an iOS quality walkthrough - Internal - p91TBi-bPj-p2

#### Issue
Subscriptions: The “Report Subscription Issue” button is unresponsive when tapped. (Only visible for Jetpack-connected stores.)

<img src="https://github.com/user-attachments/assets/6963b216-5092-4b16-9897-1e3881f90129" width="320"/>

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
