### ISSUE TITLE
[Woo POS] Handle simulated product list network error in `POSProductProvider`

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13565]
From https://github.com/woocommerce/woocommerce-ios/pull/13532#issuecomment-2283197623

If fetching products from the remote in Yosemite fails, we'll get an empty list of products rather than an error. This seems to be due to the initial handling of `func providePointOfSaleItems() async throws -> [POSItem]` , where no errors are thrown, but only an empty array is returned:

```
        } catch {
            DDLogError("No POS items")
            return []
        }
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
