### ISSUE TITLE
Settings -> Help & Support: SSR error on store without Jetpack

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13563]
Identified in an iOS quality walkthrough - Internal - p91TBi-bPj-p2

#### Problem
Settings -> Help & Support: When I try to open the System Status Report on a store without Jetpack I get an error. The logs show a JSON decoding error. (This could be a site-specific issue, but this was tested on a brand new Jurassic Ninja site with no other plugins.)

<img src="https://github.com/user-attachments/assets/7f693f31-a655-4f48-9536-943981b318c7" width="320"/>

#### Expected behaviour

The SSR should be loaded correctly.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
