### ISSUE TITLE
Settings -> Store Name: Error while editing store name

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13562]
Identified in an iOS quality walkthrough - Internal - p91TBi-bPj-p2

#### Problem
Settings -> Store Name: When I edit the store name on a store without Jetpack I get an error, even though the change was saved remotely. (The logs show an unknown_blog error from the Dotcom API, suggesting it either shouldn’t be allowed for non-Jetpack stores or should use a different route.)

<img src="https://github.com/user-attachments/assets/22a47d3c-c170-4438-ad8c-eac92084e85a" width="320"/>

#### Expected behaviour

Avoid showing the error as the store name is updated correctly in remote.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
