### ISSUE TITLE
[Orders] Order push notification always opens most recent order

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#13573]
**Describe the bug**

When I receive multiple push notifications for new orders, tapping on a notification always opens the most recent order (not necessarily the order corresponding to the notification I tapped on).

This works as expected for review push notifications, and for order push notifications on Android, so there might be something we can borrow from those implementations to open the correct order.

**To Reproduce**
1. Confirm push notifications are enabled for the app and background the app.
2. On the web, create at least two new orders.
3. On the device, tap the older push notification.
4. Notice the order details open for the most recent order, not the order corresponding to the notification that was tapped.

**Screenshots**

In this screencast I tapped the second notification but it opened the order corresponding to the first notification, instead:

https://github.com/user-attachments/assets/396e6217-3fb2-4636-8d1e-5de7f8bf22a8

**Expected behavior**

I expect that tapping on a push notification will always open the corresponding order.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by bozidarsevo** [comment]
I have been debugging now with couple of notifications for my store and what I have found out is that the payload for all notifications have the same noteID, in my case I got **8114417821** in all cases. 

I have put breakpoint in `func handleUserResponseToNotification(_ response: UNNotificationResponse) async {` in `PushNotificationsManager.swift` and debugged from there.

Could you try the same and see if the noteID is same? And what does that noteID represent?

**Comment by rachelmcr** [comment]
I confirmed the same behavior. As I understand it, the note ID is reused because of how the API works. As Ernesto mentioned in p91TBi-bPj-p2#comment-12796:

>  the [WPCom API](https://href.li/?https://developer.wordpress.com/docs/api/1/get/notifications/) reuses the notification object and only stores the last notification for each store and type.

But I noticed that the payload for review notifications includes the `post_id` and `comment_id`, which allows us to connect the notification with the related review on the store (which is stored as a custom comment type). I wonder if this could be improved with a backend change to include the order's `post_id` (since an order is a custom post type) in the payload, too.

Also, when I tested on Android I recall that we opened the correct order from the notification, so I wonder if there's something more we can do to track the related order. 🤔

**Comment by bozidarsevo** [comment]
> I confirmed the same behavior. As I understand it, the note ID is reused because of how the API works. As Ernesto mentioned in p91TBi-bPj-p2#comment-12796:
> 
> > the [WPCom API](https://href.li/?https://developer.wordpress.com/docs/api/1/get/notifications/) reuses the notification object and only stores the last notification for each store and type.
> 
> But I noticed that the payload for review notifications includes the `post_id` and `comment_id`, which allows us to connect the notification with the related review on the store (which is stored as a custom comment type). I wonder if this could be improved with a backend change to include the order's `post_id` (since an order is a custom post type) in the payload, too.
> 
> Also, when I tested on Android I recall that we opened the correct order from the notification, so I wonder if there's something more we can do to track the related order. 🤔

Cool, I will investigate more!

**Comment by bozidarsevo** [comment]
This is the payload of the push notification for new order:

```
📱 Push Notification Received: 
[AnyHashable("aps"): {
    alert =     {
        body = "New order for $1.00 on Indie Melon";
        title = "You have a new order! \Ud83c\Udf89";
    };
    badge = 1;
    category = "store_order";
    "content-available" = 1;
    "mutable-content" = 1;
    sound = "o.caf";
    "thread-id" = "215063064 - store_order";
}, AnyHashable("blog_id"): 215063064, AnyHashable("blog"): 215063064, AnyHashable("type"): store_order, AnyHashable("note_id"): 8114417821]
```

```
📱 Push Notification Received: 
[AnyHashable("aps"): {
    alert =     {
        body = "New order for $3.00 on Indie Melon";
        title = "You have a new order! \Ud83c\Udf89";
    };
    badge = 1;
    category = "store_order";
    "content-available" = 1;
    "mutable-content" = 1;
    sound = "o.caf";
    "thread-id" = "215063064 - store_order";
}, AnyHashable("type"): store_order, AnyHashable("note_id"): 8114417821, AnyHashable("blog"): 215063064, AnyHashable("blog_id"): 215063064]
```

Maybe somebody from Android could post the payload they get so we can see if they get more info in the payload?

**Comment by bozidarsevo** [comment]
pe5pgL-5xn-p2

**Comment by bozidarsevo** [comment]
**TODO**:
- extract **note_full_data** from the payload
- if needed mark the notification as **read**
- check fetching notifications on the watch
- check fetching notifications on the app extension
- check fetching notifications as background updates

**Comment by bozidarsevo** [comment]
As discussed related to this and the merged PR https://github.com/woocommerce/woocommerce-ios/pull/13734 we will do few more things in separate PRs:

- [Mark order notification read if needed on watch app and notification extension](https://github.com/woocommerce/woocommerce-ios/issues/13873)
- [Add MarkORderAsReadUseCase tests](https://github.com/woocommerce/woocommerce-ios/issues/13851)
- [Adopt new way of getting notification data in PushNotificationBackgroundSynchronizer](https://github.com/woocommerce/woocommerce-ios/issues/13852)
