### ISSUE TITLE
[Products] No discard confirmation when exiting product details

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#13571]
**Describe the bug**

There is no discard confirmation if I exit the product details with unsaved changes. My changes are just discarded with no warning. (Tested on device.)

**To Reproduce**

1. Go to the Products tab.
2. Create a new product or select an existing product.
3. Add or change product details.
4. Tap the back button to exit the product details and notice there is no confirmation before the changes are discarded.

**Screenshots**

https://github.com/user-attachments/assets/04f28108-1802-47af-90c7-079dd352326e

**Expected behavior**

I expect a discard confirmation dialog if there are unsaved changes to the product.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
This and #13574 probably have the same underlying cause. They both rely on the `UIAlertController` extension `presentDiscardChangesActionSheet(viewController:onDiscard:onCancel:)`, and it looks like the discard confirmation isn't working wherever that helper is used.

**Comment by rachelmcr** [comment]
I'm a bit stuck on this. The [helper that presents the discard confirmation](https://github.com/woocommerce/woocommerce-ios/blob/53399544f7c6eb1dd5e6c7425e2fc5ea452cae0c/WooCommerce/Classes/Extensions/UIAlertController%2BHelpers.swift#L10) should be called when there are unsaved changes, in the VC's [`shouldPopOnBackButton()` override](https://github.com/woocommerce/woocommerce-ios/blob/53399544f7c6eb1dd5e6c7425e2fc5ea452cae0c/WooCommerce/Classes/ViewRelated/Products/Edit%20Product/ProductFormViewController.swift#L216). This comes from our [`UINavigationBarBackButtonHandler` extension](https://github.com/woocommerce/woocommerce-ios/blob/53399544f7c6eb1dd5e6c7425e2fc5ea452cae0c/WooCommerce/Classes/Extensions/UINavigationController%2BWoo.swift#L52), which is used in our [`UINavigationBarDelegate` implementation of `navigationBar(_:shouldPop:)`](https://github.com/woocommerce/woocommerce-ios/blob/53399544f7c6eb1dd5e6c7425e2fc5ea452cae0c/WooCommerce/Classes/Extensions/UINavigationController%2BWoo.swift#L63).

I confirmed that we correctly detect the unsaved changes in the product form, but that `shouldPopOnBackButton()` method is never called. Unfortunately, as documented on the delegate method, `navigationBar(_:shouldPop:)` isn't called in the simulator or Xcode builds on device. It's only called with release builds, which leaves me at a bit of a loss in terms of debugging it.

**Comment by bozidarsevo** [comment]
I remember that @jaclync fixed similar/same issue https://github.com/woocommerce/woocommerce-ios/issues/12086 I will check and see if they are related.

**Comment by bozidarsevo** [comment]
**Just to update**: I have a working fix that I want to test a bit more before creating a PR!
