### ISSUE TITLE
Unknown error setting IPP when WooCommerce Payments is not installed

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13570]
Reported here: p91TBi-bPj-p2

> Menu -> Payments: On a store without Jetpack or the WooCommerce Payments extension, I see the message “In-Person Payments setup in incomplete.” That leads to a prompt to install WooCommerce Payments, but tapping the install button fails immediately with an error screen. (Same occurs when selecting “Set Up Tap to Pay on iPhone.”)

<img width="806" alt="Screenshot 2024-08-12 at 17 03 14" src="https://github.com/user-attachments/assets/657fb73e-3882-4011-9255-b9f8a288b336">

## To Reproduce
I wasn't able to reproduce it, except if we force the failure when attempting to install the plugin:

1. On a fresh store with no Jetpack or WooCommerce payments, set the store location to US
2. In the app, go to Menu > Payments
3. Observe the "In-Person Payments setup in incomplete" onboarding notice
4. Tap, then tap on "Install WooCommerce Payments"
5. Set a breakpoint or intercept the request, here the call to `installCardPresentPlugin()` should return a failure
6. Observe the `InPersonPaymentsUnavailable` screen

## Possible cause

The cause seems to happen when receiving a failure from `CardPresentPaymentsOnboardingUseCase.installCardPresentPlugin`, since they initially land on the "plugin not installed" case, then tap the button to install the plugin, and then it fails. 

The failure sets the state specifically to be `genericError`, which is the only default case in `CardPresentPaymentsOnboardingView` when we load different views based on `CardPresentPaymentOnboardingState`

<img width="1247" alt="Screenshot 2024-08-12 at 17 34 46" src="https://github.com/user-attachments/assets/cae83e86-0f62-497d-ad11-71d0cf7e2648">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
It looks like there's a new `status` string that we get from `wc/v3/payments/accounts`, which gets translated to `.unknown`. The new string is `pending_verification`, and seems to refer to Deposits: Pending verification.

Example response:
```
{
  "data": {
    "is_live": false,
    "has_pending_requirements": false,
    "has_overdue_requirements": false,
    "current_deadline": null,
    "status": "pending_verification",
    "statement_descriptor": "INTERESTING HORNET",
    "store_currencies": {
      "default": "usd",
      "supported": [
        "usd"
      ]
    },
    "country": "US",
    "card_present_eligible": false,
    "test_mode": true
  }
}
```

**Comment by joshheald** [comment]
> It looks like there's a new `status` string that we get from `wc/v3/payments/accounts`, which gets translated to `.unknown`. The new string is `pending_verification`, and seems to refer to Deposits: Pending verification.

This is actually a separate issue – #13581 created to deal with it.
