### ISSUE TITLE
[Products] Can't edit a product after finding it with the barcode scanner

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#13572]
**Describe the bug**

When I use the barcode scanner on the products list, I can only open a read-only view of the product; I can’t edit it.

**To Reproduce**
1. Go to Products tab.
2. Select the barcode scanner.
3. Scan a product barcode (for a product that already uses that barcode as the SKU).
4. Select `View Product Details`.
5. Notice the product details are shown in read-only mode and can't be edited.

**Screenshots**

Product tab (scanned product)|Product details (read-only)
-|-
![IMG_0DDD41D317EE-1](https://github.com/user-attachments/assets/f6bdae8c-ea23-4bb8-88e2-3d551cbdf473)|![IMG_0DDD41D317EE-2](https://github.com/user-attachments/assets/09269247-d9ca-4a2a-956f-78529d519d17)

**Expected behavior**

I expect to be able to edit the product details.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
This is intentional for now, because of the impact it would have on the first screen shown after scanning the product (quick inventory screen). From the PR where it was implemented (https://github.com/woocommerce/woocommerce-ios/pull/11414):

> For now, the details screens are read-only, which means that the users cannot edit the details there. Doing that would require syncing the product changes in the quick inventory screen, which might be complex for now. We can iterate in the future to achieve this.

Closing this issue as this is the intended behavior and requires additional work to support editing.
