### ISSUE TITLE
[Order details] Receipt print button unresponsive after first tap

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#13575]
**Describe the bug**

When I tap “Share Receipt,” the print icon only works once. If I close the print dialog (either by tapping Cancel or by tapping the share icon and sharing the receipt in another way) the print icon becomes unresponsive.

**To Reproduce**
1. Go to the Orders tab.
2. Select an order that has been paid for.
3. Tap `See Receipt`.
4. Tap the printer icon on the receipt.
5. Tap `Cancel` or select the share icon and share the receipt.
6. Tap the printer icon on the receipt again, and notice that nothing happens.

**Screenshots**

https://github.com/user-attachments/assets/2f4d1460-b035-475c-8a4b-90ec8670126a

**Expected behavior**

I expect the print button to always work when it is visible and active. I should be able to print an order receipt as many times as I want.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
