### ISSUE TITLE
[Order form] No discard confirmation when exiting order creation without saving

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#13574]
**Describe the bug**

While creating a new order, there is no discard confirmation if I exit the order form with unsaved changes. My changes are just discarded with no warning. (Tested on device.)

**To Reproduce**
1. Go to the Orders tab.
2. Add a new order.
3. In the order form, add some details to the order.
4. Tap the Cancel button and notice it closes and discards the order with no discard confirmation.

**Screenshots**

https://github.com/user-attachments/assets/dbb8f921-7137-4108-9ede-0ef41e3fb7a6

**Expected behavior**

I expect a discard confirmation dialog if there are unsaved order details in the order form.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
It looks like this is different from the issue with product details, because the "Cancel" button on the order form now bypasses the back button discard confirmation. We need to ensure we're triggering a confirmation alert on the cancel button itself.

**Comment by rachelmcr** [comment]
This looks like it just needs an update to the `OrderForm` dismiss handler. That closes the form with a custom button instead of the default back button, so we need to do a similar check for `viewModel.canBeDismissed` and present the discard changes action sheet there.
