### ISSUE TITLE
[Mobile Payments] Add support for `pending_verification` WooPayments status

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13581]
It looks like there's a new `status` string that we get from `wc/v3/payments/accounts`, which gets translated to `.unknown`. The new string is `pending_verification`, and seems to refer to Deposits: Pending verification.

Example response:
```
{
  "data": {
    "is_live": false,
    "has_pending_requirements": false,
    "has_overdue_requirements": false,
    "current_deadline": null,
    "status": "pending_verification",
    "statement_descriptor": "INTERESTING HORNET",
    "store_currencies": {
      "default": "usd",
      "supported": [
        "usd"
      ]
    },
    "country": "US",
    "card_present_eligible": false,
    "test_mode": true
  }
}
```

_Originally posted by @joshheald in https://github.com/woocommerce/woocommerce-ios/issues/13570#issuecomment-2283804779_

> pending_verification means that deposits are pending, but payments are good to go :+1: as you shown in the image from WP Admin.
> so yes, you should probably allow payments for this status
– Oleksandr Aratovskyi p1723552588888969/1723542700.176059-slack-C01BPL3ALGP

Web payments enabled logic: https://github.com/Automattic/woocommerce-payments/blob/788d5715640edcde2435c02ef808141778aee22e/client/components/account-status/index.js#L104-L104

We can fix this by treating `pending_verification` as `enabled`.

## Repro

1. Create a new Jurassic Ninja site – include WooCommerce, WooPayments, and WooPayments Dev Tools
2. Link the site with your Jetpack user
3. Add a US address in WooCommerce settings
4. Activate WooPayments
5. Go through the onboarding steps in WP-Admin > Payments > Activate
6. Launch the app and switch to your new site
7. Go to `Menu > Payments`
8. Tap the `Continue` button in the onboarding notice that shows
9. Observe that you're shown a generic `Unable to verify` onboarding error (after skipping anything skippable)

Expectation – you should be able to take payments without seeing the onboarding error
![generic onboarding error](https://github.com/user-attachments/assets/ad794a05-ac42-408e-b8ec-c074577c150a)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
