### ISSUE TITLE
[Mobile Payments] TTP try a payment doesn't progress after payment collected

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13596]
## Description

While testing other IPP issues, I've found that the TTP try a payment flow doesn't completely work.

After tapping a card, the `Preparing payment` message remains on screen, even though payment is successfully taken. The success message is not shown, and the user has to force quit the app.

This only affects the `Try a payment` $0.50 test payment flow from the Payment Menu, not normal payments, but it's a bad first impression.

## Repro
1. Go to the payments menu
2. Tap `Set up (or try out) Tap to Pay on iPhone`
3. Go through the flow and tap a card
4. Observe that the payment dialog does not show success, but wait a few seconds. You should get the new order notification.
5. Force quit and reopen the app
6. Go to the orders tab
7. Observe that the test payment had been successful

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
This is an iOS 17-only bug
