### ISSUE TITLE
System status report: Title appears then disappears

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#13592]
**Describe the bug**
When navigating to system status report from Help & Support, the view's title flickers then disappears.

**To Reproduce**
1. Log in to the app
2. Switch to Hub Menu
3. Select Settings > Help & Support > System status report
4. Notice that the view's title appears then disappears

**Screenshots**

https://github.com/user-attachments/assets/526d8e51-9d6e-4b24-a8aa-3264705c12a4

**Expected behavior**
The view title should stay fixed.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
