### ISSUE TITLE
[Mobile Payments] Contact Support in IPP Onboarding doesn't work on iOS 17

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13599]
## Repro

1. Launch the app on iOS 17
2. Ensure your store is not passing IPP onboarding, or fake it
3. Navigate to `Menu > Payments`
4. Wait for the notice to appear about setup not being complete
5. Tap `Continue`
6. Tap `Contact Support` on the onboarding screen which shows
7. Observe that nothing happens.

The same is true when opening the onboarding screen via the Set up Tap to Pay on iPhone flow

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
