### ISSUE TITLE
[Mobile Payments] Decline reasons are not decoded

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13595]
## Description

During development on #13578, I found that all `UnderlyingError.paymentDeclinedByPaymentProcessorAPI(declineReason:)` errors are decoded with the default `DeclineReason.unknown`.

This is because [when we check the user info from the error](https://github.com/woocommerce/woocommerce-ios/blob/2d21789c5f74db0ee7d6b224efb42e768961e5a1/Hardware/Hardware/CardReader/StripeCardReader/UnderlyingError%2BStripe.swift#L76), we use an incorrect key to fetch the decline info.

We use `stripeAPIDeclineCode`, but Stripe use `com.stripe-terminal:StripeAPIDeclineCode`.

This should be checked in case there's a better way to get the key in future.

## Impact
This means that in decline situations, merchants will have received less detailed instructions on what to do next and what caused the error. However, for all declines, the approach is to try again and they were invited to do that.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
