### ISSUE TITLE
Fulfill order: images are skewed

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1360]
Use the correct aspect ratio when displaying images in the Fulfill Order screen.

<img src="https://user-images.githubusercontent.com/1062444/66579807-02927680-eb43-11e9-9d47-a5d4de90076e.png" width="350" />

**Comment by pmusolino** [comment]
Since the PR https://github.com/woocommerce/woocommerce-ios/pull/1407 fixed the same problem on Order Detail, not on Fulfill order, I'm reopening this issue.
