### ISSUE TITLE
Order Detail: Add shipping method to the shipping details section

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-ios#1362]
As discussed, it would be nice to add the shipping method of an order in the Order Detail and Order Fulfillment screen.

Ref. p99K0U-1IW-p2

<img width="438" src="https://user-images.githubusercontent.com/22608780/66629177-a1d86c00-ec1e-11e9-9bf2-ae117a2de4c2.png">

**Comment by jaclync** [comment]
The technical implementation like where to get the shipping method from the API is in Anitaa's detailed research: p99K0U-1IW-p2#comment-3792

And the design link and the screenshots when there are multiple shipping methods are in Kylea's comment: p99K0U-1IW-p2#comment-4080 - we show this warning row when there are more than one shipping methods
