### ISSUE TITLE
Login: Site credential login button is displayed when entering a WPCom site address

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#13622]
**Describe the bug**
When entering a WPCom site address, the site credential login button is displayed

**To Reproduce**
1. Log out of the app if needed.
2. On the prologue screen select Log in.
3. Enter the address of a WPCom site.
4. Notice that there's an option for site credential login.

**Screenshots**
<img src="https://github.com/user-attachments/assets/ba25b9b0-181a-4f78-9ce1-f1d9f76bb523" width=320 />

**Expected behavior**
Site credential login button should only be available for self-hosted sites.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
