### ISSUE TITLE
[Woo POS] Dynamic type improvements

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13627]
Increase dynamic type to the largest size, test the behavior, and make the improvements.

The extra large sizes are important for some users, and I don't think we should prevent them from increasing the font size. Instead, we should react to the larger sizes with adaptive layouts for some of our views:

The balance on the product rows feels wrong there, and we could improve it by making them taller, and putting the price and name on two rows. Possibly deemphasising the image as well.

Similarly, the Cart header should be split over 3 lines (Title, number of products, clear button)

These are polish points which I think we should ticket, not neccesarily do now. It would be better not to limit the font size even when unpolished – users can choose the size they want.

### Product list and rows
![Simulator Screenshot - iPad Air 11-inch (M2) - 2024-08-15 at 14 55 01](https://github.com/user-attachments/assets/6c842a43-f7d7-400d-948a-b51efa21a263)

#### Considerations for larger font sizes:
- Make rows taller
- Put prices and names in two rows
- Do not increase image size

### Cart list and rows

![Simulator Screenshot - iPad Air 11-inch (M2) - 2024-08-15 at 14 55 05](https://github.com/user-attachments/assets/61ffb903-8c1d-49c2-94e8-8e67a20234e0)

#### Considerations for larger font sizes:
- Split card header into 3 lines: title, number of products, and clear button
- Make rows taller
- Do not increase image size

### Card Reader Views

![Simulator Screenshot - iPad Air 11-inch (M2) - 2024-08-15 at 14 55 54](https://github.com/user-attachments/assets/192f7446-8418-4a08-84e3-0f6461758120)
![Simulator Screenshot - iPad Air 11-inch (M2) - 2024-08-15 at 14 55 14](https://github.com/user-attachments/assets/4d18699d-19be-43d9-bf41-c3706ef2b043)

#### Considerations for larger font sizes:

- Wrapping the text
- Scroll view
- Removing an image
- Prioritize always showing totals

### Product Modal

![image](https://github.com/user-attachments/assets/3272f90e-ce01-4b7d-b9f9-6e37f33fb162)

#### Considerations for larger font sizes:

- Wrapping the text
- Scroll view

### Full Screen Message Views

![image](https://github.com/user-attachments/assets/0788d79e-3d3f-41b1-8318-551e0ca42171)
![image](https://github.com/user-attachments/assets/3abd06e5-a01e-4c86-9904-b1d7ed7b00af)

#### Considerations for larger font sizes:

- Wrapping the text
- Scroll view
- Limited padding
- Removing an image

### Floating Bar Button

<img width="610" alt="image" src="https://github.com/user-attachments/assets/b2a58ac0-8925-4970-8ab2-57659627c0cc">

#### Considerations for larger font sizes:
- Increase in size when font size increases

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
