### ISSUE TITLE
[Woo POS] Offline banner

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13634]
Show an offline banner reading `No internet connection` to inform the user that connectivity is lost.

![Image of error screen showing the offline banner at the top centre](https://github.com/user-attachments/assets/ec538150-86c2-426b-b3bf-d3188f1f8496)

This should show as an overlay on all screens.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
