### ISSUE TITLE
[Woo POS] Cart can become invisible after payment error

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13637]
> [...] I found it pretty easy to reproduce this flow specifically when restarting the payment. It's a case where we allow coming back without properly canceling the flow or dealing with TotalsViewModel affecting the dashboard state. Could be a separate bug:
> 
> https://github.com/user-attachments/assets/b23a88be-2ca4-426c-baf9-8f51fe67691b
> 
> _Originally posted by @staskus in https://github.com/woocommerce/woocommerce-ios/pull/13628#pullrequestreview-2241011629_

This is a pre-existing issue, so I've split it out of the PR

## Repro steps:
1. Launch the app and go to POS
2. Add an error amount to the cart (e.g. ending in `.01`)
3. Go through to checkout
4. Tap `Try another payment method` or `Go back to checkout`
5. Tap back on the checkout
6. Observe that (sometimes) the cart gets hidden and only the products list shows.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
No longer reproducible after improvements made in https://github.com/woocommerce/woocommerce-ios/pull/13631
