### ISSUE TITLE
IPP in UK and Canada Displays Unknown Error on Incorrect PIN entry

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-ios#13632]
**Describe the bug**
When the user enters an incorrect pin number or if we use `x.55` test amount in test mode, the app displays `The payment was declined for an unknown reason`.

**To Reproduce**
1. Go Order List
2. Start the order creation flow
3. Enter custom amount ending with x.55 (eg. 1.55)
4. Collect payment using a card reader
5. Notice the payment fails with an unknown error

**Screenshots**

![IMG_E5FB3CCD322F-1](https://github.com/user-attachments/assets/c41579e3-d9e4-424c-83fb-1852a5dcd1f6)

**Expected behavior**
The app should inform the user that an incorrect PIN was entered - something like `Incorrect PIN entered. Please try again`.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by malinajirka** [comment]
@joshheald @staskus Could one of you please look into this? I noticed the behavior [is consistent with Android](https://github.com/woocommerce/woocommerce-android/issues/12350), but seems like something we forgot to update as we expanded to UK/CA (in the US this is not necessary, since the M2 reader doesn't have a keyboard).

**Comment by joshheald** [comment]
@malinajirka can you send me the commit hash for the build you were using? I think we fixed this yesterday in #13606 

We had used an incorrect key to get Stripe's decline code, so we always used the generic default... so it's unlikely to be the same issue on Android.

**Comment by malinajirka** [comment]
I retested the flow on this PR and it works as expected! Thanks 🙇!
