### ISSUE TITLE
[Payments] App freezes after taking TTP test payment

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#13643]
**Describe the bug**

After taking a TTP test payment on my phone, the app froze on the "Getting ready to collect payment" screen. Tapping anywhere on the screen didn't do anything.

This is likely an issue specific to iOS 18. I observed it while smoke testing the 19.9 release build on the iOS 18 beta on my phone.

**To Reproduce**
1. Go to the Menu tab.
2. Open the Payments section.
3. Tap "Try Out Tap to Pay on iPhone" and follow the prompts to set up TTP.
4. When you see the "Would you like to try a payment" screen, tap "Try a Payment."
5. Tap "Take Payment" on the payment form.
6. Choose "Tap to Pay on iPhone" as the payment method.
7. Tap your card to complete the test payment.
8. After the payment is accepted, notice that the app returns to the "Getting ready to collect payment" screen and is unresponsive.

**Screenshots**

https://github.com/user-attachments/assets/05920cc7-35ec-4609-b845-89ef2ac1c587

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
I also tested taking a payment (both card reader and TTP) with a regular order, and in both cases it worked as expected. (Note: I also confirmed I tested with an account set to USD, and the store is set to USD.)

**Comment by joshheald** [comment]
We made a fix to the Try out TTP flow in 20.0 – #13600. It might also fix this, but it wouldn't have been in the 19.9 build used for smoke testing.

@rachelmcr sorry to ask more of you on this, but could you check it on the 20.0 testflight build when you have a moment? I only have 2 TTP-capable test devices and I don't want to be left without an iOS 16 one while we still support that OS.

**Comment by joshheald** [comment]
Seeing the video, I'm fairly confident it's the same issue (it wouldn't load for me at first.)

**Comment by rachelmcr** [comment]
Ah, yep, looks like it was the same issue! I tried again with the 20.0 TestFlight build on iOS 18 and it worked this time. 👍 

Closing this issue as resolved.
