### ISSUE TITLE
[Dashboard] Can't open product detail for variations in dashboard Stock card

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#13641]
**Describe the bug**

In the Dashboard Stock card, when a variation is displayed in the list (for variable products where stock is managed per variation), tapping the variation opens an error screen instead of the variation detail.

**To Reproduce**

Prerequisite: Make sure you have at least one variable product with a variation that is low stock, no stock, or on backorder.

1. Go to the My store dashboard.
2. Enable the Stock card.
3. Select the stock status that matches the variation in the prerequisite.
4. Tap the variation in the list.
5. Notice a "Loading Product" sheet opens with an error.

**Screenshots**

Stock card|Loading Product
-|-
![IMG_FA7021CF42EE-1](https://github.com/user-attachments/assets/b47589da-f421-4e75-aee3-d02f24da4c46)|![IMG_FA7021CF42EE-2](https://github.com/user-attachments/assets/91f305fb-67f2-4c3d-a3a2-901d6239a7d8)

**Expected behavior**

I expect either the variable parent product or (ideally) the variation detail to open.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
