### ISSUE TITLE
Custom Amount input field is occasionally not responsive

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13646]
**Describe the bug**

Custom Amount input field is occasionally not responsive. The view must be dismissed and reopened so that the input field can react to keyboard events.  p1723799304801539-slack-C025A8VV728 

It likely happens due to custom `BindableTextField` we use and the timing of `becomeFirstResponder` calls which also produces this error:

> [Modifying state during view update, this will cause undefined behavior." in UIViewRepresentable](https://stackoverflow.com/questions/71914728/warning-modifying-state-during-view-update-this-will-cause-undefined-behavior)

**To Reproduce**
1. Go to Orders
2. "+"
3. Add Custom Amount
4. Try to input amount
5. Repeat 3-4 a few times and notice that sometimes input doesn't work

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: 
- iOS version: 
- WooCommerce iOS version: 

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
