### ISSUE TITLE
[Inbox] Inbox always shows empty state, even if dashboard and web show inbox messages

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#13644]
**Describe the bug**

When I go to Menu > Inbox, I always see the empty state "Congrats, you've read everything!" message. Sometimes I see a flash of inbox messages on that screen before it switches to the empty state.

However, when I view the Inbox card in the app dashboard or on my web WooCommerce dashboard, I see messages there.

**To Reproduce**
1. Go to the My store dashboard tab.
2. Enable the Inbox card and confirm you have messages there.
3. Go to the Menu tab.
4. Open the Inbox section.
5. Notice it tries to load the inbox and then displays the empty state message.

**Screenshots**

https://github.com/user-attachments/assets/ef2b250f-9d12-416e-8c08-418c158010cf

**Mobile Environment**
Please include:
- Device: iPhone 
- iOS version: 18 beta
- WooCommerce iOS version: 19.0.0.1 release build (on TestFlight)

I also see the same behavior when testing with a simulator running iOS 17.5 on `trunk`.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
