### ISSUE TITLE
[Crash] Crash on iOS 18 when tapping the Menu tab

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#13640]
**Describe the bug**

The app crashes on a device with the iOS 18 beta after installing/connecting Jetpack (while logged in to a store that wasn't previously connected via Jetpack) and then tapping the Menu tab.

**To Reproduce**
1. Log in to the app with a WooCommerce store without Jetpack.
2. Follow the prompt to install and connect Jetpack.
3. After Jetpack is installed, tap the Menu tab in the bottom tab bar.
4. Result: Crash.

Here's the start of the crash details (full details available in Xcode crashes or TestFlight crashes in App Store Connect - I didn't see it reported in Sentry):

```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: SIGNAL 6 Abort trap: 6
Terminating Process: WooCommerce [7884]

Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	0x18e8ad08c __exceptionPreprocess + 164 (NSException.m:249)
1   libobjc.A.dylib               	0x18bbaf2e4 objc_exception_throw + 88 (objc-exception.mm:356)
2   Foundation                    	0x18dc7e15c -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 288 (NSException.m:252)
3   UIKitCore                     	0x191a6d3e0 -[UITabBarController _viewControllerForTabBarItem:] + 432 (UITabBarController.m:3964)
4   UIKitCore                     	0x191a6d48c -[UITabBarController _tabBarItemClicked:] + 32 (UITabBarController.m:3975)
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
It looks like I triggered the same crash with another flow:

1. Switch stores in the app.
2. After the dashboard for the new store loads, tap the Menu tab.
