### ISSUE TITLE
Partial swipe back gesture from product details removes the content

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#13651]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

While working on #13571 I noticed an issue with swipe back gesture on products detail. It appears to be broken, or to be more specific it produces a problematic state of the app.

**To Reproduce**
Steps to reproduce the behavior (on iPhone):
1. Go to Products tab
2. Click on one of the product to open its details
3. Use the swipe back gesture partially, start it but do not finish it.
4. You will see that no content is shown on Products tab

**Screenshots**

https://github.com/user-attachments/assets/51aefbdd-4339-4d63-92e5-41aa590a92ce

**Expected behavior**
It is expected that if the swipe back is not fully completed that the product details would still be on the screen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 15 Pro simulator
- iOS version: 17.2
- WooCommerce iOS version: 20.0.0.0

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
