### ISSUE TITLE
Product is not removed from order when it's the only one

### ISSUE THREAD

**Issue by toupper** [woocommerce/woocommerce-ios#13664]
**Describe the bug**
When the order has just one product, removing that product from the order has no effect on the order details. The Order total is updated though, showing $0

**To Reproduce**
1. Go to Orders
2. Tap on + to create a new order.
3. Add a product.
4. Tap on Create
5. Tap on Edit
6. Remove the product and tap on Done
7. The order still contains that product (wrong)
8. Go back and enter again in the order
9. The product is still there
10. Tap on Edit. The product is still there.

**Screenshots**

https://github.com/user-attachments/assets/c64221e3-6f79-4dcb-9907-7d43993e81d8

**Expected behavior**
The product should be removed from the order right away.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
I confirmed the issue, and also confirmed that the backend is working correctly. The API returns the order with no line items, and the order on the web (in wp-admin) shows no items in the order.

When I exit the order details and pull to refresh the order list, the order updates as expected to show no items in the order. So it looks like the order details are being cached and not refreshed correctly after the order is edited to remove the last product.
