### ISSUE TITLE
[Hub Menu] Empty titles in Reviews and Coupons screens during navigation

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13676]
Reported during a PR review [here](https://github.com/woocommerce/woocommerce-ios/pull/13671#pullrequestreview-2250128032)

#### Problem

<img src="https://github.com/user-attachments/assets/9598ef51-3bfb-4865-be74-796063a36280" width=320 /><img src="https://github.com/user-attachments/assets/f801396b-73d2-4f04-8743-2a72b872f6ae" width=320 />

There's a minor issue with the navigation title missing on the Review list and Coupon list when navigated from the hub menu. This doesn't happen consistently, so can be reproducible by navigating back and forth with these screens. This might have something to do with the title being set in the wrapped UIViewController - I suppose setting titles on the SwiftUI component might fix it.

#### Expected behaviour

The titles should not be empty for the Reviews and Coupons list screens.

**Comment by itsmeichigo** [comment]
I timebox 2 hours this morning trying to fix this but it's almost impossible to fix this without rewriting the view controllers of Reviews and Coupons to SwiftUI, which is risky and time-consuming.
