### ISSUE TITLE
[Woo POS] Design tweaks: Simple products banner

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13687]
* Padding missing around the Simple Products banner.
* `Learn more` on Simple Products banner should be styled as a link.
<img width="1161" alt="Screenshot 2024-08-22 at 11 55 07" src="https://github.com/user-attachments/assets/85d34ff4-fd8f-45c6-9c16-98c92854bb8d">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
