### ISSUE TITLE
[Woo POS] Design tweaks: Add missing shadows to Cart headers

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13689]
* Cart header should shadow over list items when they are scrolled underneath.

Ref: TfaZ4LUkEwEGrxfnEFzvJj-fi-2967_79332

<img width="309" alt="Screenshot 2024-08-22 at 14 09 38" src="https://github.com/user-attachments/assets/fc85c52a-de43-45ba-b433-7ea3eff97b6b">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
Extracted #13732 as per discussion p1724641861816649/1724411752.310989-slack-C070SJRA8DP
