### ISSUE TITLE
[Woo POS] Design tweaks: Item selection and cart

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13686]
* Products and Cart headings should be aligned.
* The i icon should be aligned to the right
<img width="1203" alt="Screenshot 2024-08-22 at 11 43 20" src="https://github.com/user-attachments/assets/5f282138-6668-41a8-a45a-c03ef838c02f">

* Additional space between `<` and `Cart` header
<img width="812" alt="Screenshot 2024-08-22 at 11 45 52" src="https://github.com/user-attachments/assets/d0f65cbd-3bac-4ecb-9720-a6e727b613b1">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
