### ISSUE TITLE
Google Ads: Missing entry point for eligible stores

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#13698]
**Describe the bug**
Entry point to Google Ads is missing.

**To Reproduce**
1. Log in to a store eligibile for Google Ads on the app.
2. Navigate to the Menu tab.
3. Notice that the Google Ads entry point is missing.

**Screenshots**
<img src="https://github.com/user-attachments/assets/f43fbc9a-1b7e-4bc2-8cb5-76138242cadb" width=320 />

**Expected behavior**
The entry point should be available for eligible stores.

**Cause**
We were checking for `google-listings-and-ads/google-listings-and-ads.php` in the `plugin` field in SSR to get the matching plugin. However, the plugins are now sent with `/srv/htdocs/wp-content/plugins/` prefix, so the check fails.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by itsmeichigo** [comment]
Closing this issue as the API change is being reverted [peaMlT-PG-p2].
