### ISSUE TITLE
[Woo POS] Add missing POSFontStyle to Text

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13691]
All our `Text` elements should have `.font` with `POSFontStyle` set. Missing usage:

- PointOfSaleCardPresentPaymentScanningForReadersView
- PointOfSaleCardPresentPaymentScanningForReadersFailedView
- PointOfSaleCardPresentPaymentBluetoothRequiredAlertView
- PointOfSaleCardPresentPaymentConnectingToReaderView
- PointOfSaleCardPresentPaymentConnectingFailedView
- PointOfSaleCardPresentPaymentConnectingFailedNonRetryableView
- PointOfSaleCardPresentPaymentConnectingFailedUpdatePostalCodeView
- PointOfSaleCardPresentPaymentConnectingFailedChargeReaderView
- PointOfSaleCardPresentPaymentFoundReaderView
- PointOfSaleCardPresentPaymentConnectingFailedUpdateAddressView
- PointOfSaleCardPresentPaymentRequiredReaderUpdateInProgressView
- PointOfSaleCardPresentPaymentOptionalReaderUpdateInProgressView
- PointOfSaleCardPresentPaymentReaderUpdateCompletionView
- PointOfSaleCardPresentPaymentReaderUpdateFailedView
- PointOfSaleCardPresentPaymentConnectionSuccessAlertView
- PointOfSaleCardPresentPaymentReaderUpdateFailedNonRetryableView
- PointOfSaleCardPresentPaymentReaderUpdateFailedLowBatteryView
- ReaderConnectedView
- PointOfSaleDashboardView Text(totalsViewModel.cardPresentPaymentEvent.temporaryEventDescription)
-

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
Linked to #13731
