### ISSUE TITLE
[Woo POS] Design Tweaks: Lighter background behind modal

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13705]
| Design | App |
|--------|-----|
| ![Image](https://github.com/user-attachments/assets/47d64bfa-b585-494e-9239-3b7d692054f1) | ![Image](https://github.com/user-attachments/assets/124d4abf-4b26-47a3-bb0b-cb60b1eb384a) |

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
Thanks for noticing, I'll change this one after I make the other modal changes I'm working on currently.
