### ISSUE TITLE
[Woo POS] Design Tweaks: Missing close button from products modal

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13703]
| Design | App |
|--------|-----|
| ![Image](https://github.com/user-attachments/assets/47d64bfa-b585-494e-9239-3b7d692054f1) | ![Image](https://github.com/user-attachments/assets/124d4abf-4b26-47a3-bb0b-cb60b1eb384a) |

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
This one was agreed that we would omit it, because the OK button closes the modal anyway: TfaZ4LUkEwEGrxfnEFzvJj-fi-2530_19409#904961251
