### ISSUE TITLE
[Woo POS] Design Tweaks: Centering of views

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13701]
1. Product error and empty views are not properly centered

| Design | App |
|--------|-----|
| ![image](https://github.com/user-attachments/assets/5b6a884b-ecf9-4adb-99ae-a14637721506) | ![image](https://github.com/user-attachments/assets/6c222781-d9f9-42c0-ac4d-2a64985931c9) |

| Design                        | App                           |
|-------------------------------|-------------------------------|
| ![image](https://github.com/user-attachments/assets/e8a7615e-3475-47e8-af26-abcd24c49fab) | ![Simulator Screenshot - iPad Air 11-inch (M2) - 2024-08-22 at 14 29 07](https://github.com/user-attachments/assets/b8f216f0-56b9-46e2-9ab9-fd2b091ed706) |

2. Cart placeholder is not centered according to designs

| Design                        | App                           |
|-------------------------------|-------------------------------|
| ![Image](https://github.com/user-attachments/assets/02016dc2-ebb4-4a80-a960-095997cd8116) | ![Image](https://github.com/user-attachments/assets/d78652af-d161-49e0-a818-1fcc961930f2) |

3. Payment views

| Design                        | App                           |
|-------------------------------|-------------------------------|
| ![Image](https://github.com/user-attachments/assets/4ca8b300-4fb3-4e38-af4b-5520c9f7a8c1) | ![Image](https://github.com/user-attachments/assets/5a3e1817-e834-4edb-869e-63a9611d9d33) |

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
Good spot
