### ISSUE TITLE
[Woo POS] Add missing transitions

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13700]
A list of missing transitions in POS.

Time-box a specific amount of time and tackle as many as possible. I suggest prioritizing them by how often they are likely to be encountered. 

Lower priority transitions will be handled here https://github.com/woocommerce/woocommerce-ios/issues/13721

#### Higher priority:
1. Products & Cart
2. Happy Path Payment
3. Reader Connection
4. Unhappy Path Payment

## Happy Path

p91TBi-bHy-p2

#### Reader connection
- [ ] ‘Connect reader’ modal fade-in [3:44]
- [ ] ‘Connect reader’ transition between states: fade in and icons transition into a new place with animation [3:46]

#### Products & Cart

- https://github.com/woocommerce/woocommerce-ios/issues/13747

#### Payment
- [x] ‘Check out’ slide out Product list, slide Cart to side, slide-in Totals [4:32]
- [x] ‘Totals Text Fields’ transition from shimmering to loaded state [4:34]
- [x] ‘Totals Text Fields’ moves down when ‘’Checking order’ appears [4:36]
- [x] ‘Checking Order’ -> ‘Preparing for payment’ -> ‘Tap Swipe’ fade between transitions [4:37]
- [x] ‘Tap Swipe Card’ -> ‘Processing payment’ transition [5:29]
- [x] ‘Processing payment’ -> ‘Payment successful’ [5:35]  transition

## Unhappy Path

- https://github.com/woocommerce/woocommerce-ios/issues/13735

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
