### ISSUE TITLE
[Woo POS] Update UI for card reader connection modals

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13731]
Improvements to the design of the card reader connection screens, shown in a modal during reader connection.

- [x] New image for errors (requested: p1724660697349469-slack-C0354HSNUJH)
- [x] New image for low battery errors (requested: p1724660697349469-slack-C0354HSNUJH)
- [x] #13691 
- [x] Use POS button styles
- [x] Ensure modal is correct size
- [x] Change title/subtitle of Found reader
- [x] Replace cancel button with `x-mark`
- [x] Move all text below images
- [ ] ~Spacer between text and buttons~
- [x] Scroll where required
- [x] Update multiple readers view to have sensible background etc

Designs: TfaZ4LUkEwEGrxfnEFzvJj-fi-4354_119342
![Screenshot of some 5 examples of connection modals in designs](https://github.com/user-attachments/assets/5274c532-cd8e-4c32-82ef-aeb15b5ab249)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
