### ISSUE TITLE
Orders badge not refreshed after switching stores

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1373]
**Describe the bug**
The badge with the number of processing orders on the Orders tab does not refresh after switching stores.

**To Reproduce**
Prerequisites: having at least two stores, one with <= 9 orders with processing status, and the other with > 9 of them.
1. Launch the app logged in to one store, observe the Orders badge
2. Go to Settings and switch to the other store as in the prerequisites
3. Observe the Orders badge

expected: the Orders badge should be consistent with the store
actual: the Orders badge stays the same as the first store

**Comment by astralbodies** [comment]
Hey @pmusolino I'm reopening this issue because it seems switching to a store with no orders to process isn't clearing the badge. If I switch between stores with orders to process, then the count updates. 

cc: @shiki since you're working around that code sort of right now. 😄

**Comment by pmusolino** [comment]
Fixed here https://github.com/woocommerce/woocommerce-ios/pull/1858
