### ISSUE TITLE
[Woo POS] Add missing transitions: Unhappy payment path

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13735]
Parent task: #13700

p91TBi-bHy-p2

#### Payment
- [x] ‘Couldn’t load totals’ fade in [4:10]
- [x] ‘Error checking orders’ fade in and totals move down [4:32]
- [x] ‘Reader not connected’ fades in and totals move down [5:12]
- [x] ‘Processing payment’ -> ‘Payment Failed’ transition [5:51]
- [x] ‘’Payment Failed’ -> ‘’Tap, swipe, or insert card’ transition [6:44]

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
