### ISSUE TITLE
[Woo POS] Add missing transitions to product and cart views

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13747]
Parent task: #13700

p91TBi-bHy-p2

#### Products & Cart
- [x] ‘Product added to cart’ fade in: fade in a row and separately fade in row content more slowly [4:15]
- [x] Consider updating "Check out" animation when Cart moves from right to left. Sometimes subviews are not animating together

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
