### ISSUE TITLE
Adding product to order does not always reduces stock

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#13759]
**Describe the bug**

The `9.3.0-beta-1` core release automatically updates a product stock when editing an order. On iOS there is an edge case where the product stock is not reduced.

- Creates an order with a product, reduces product stock ✅ 
- Updates order to remove the product, increases stock ✅ 
- Updates order to add the product again, does not reduce stock ❌
- Updates order to increase the product quantity. reduces stock ✅ 

Note: Android does not have this problem so we must be doing something different between platforms.

**Screenshots**

https://github.com/user-attachments/assets/a85ae708-2378-4264-8af6-4c551bd52f4d

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by Ecarrion** [comment]
Closed in favor of https://github.com/woocommerce/woocommerce/issues/51024
