### ISSUE TITLE
Blaze: Update tracking for evergreen campaigns

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#13762]
Add a new property campaign_type : start_end | evergreen to the following existing events:

_blaze_creation_edit_budget_save_tapped
_blaze_creation_edit_budget_set_duration_applied
_blaze_creation_confirm_details_tapped
_blaze_campaign_creation_success

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
