### ISSUE TITLE
[Products] Decimal separator added to price when store uses "Left with space" currency position setting

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#13767]
**Describe the bug**

When a store uses the "Left with space" currency position setting, the app adds an incorrect decimal separator while editing product prices.

When we [format the regular price for the product](https://github.com/woocommerce/woocommerce-ios/blob/14675cafe15421267f96031c8b9203e113a18b0c/WooCommerce/Classes/ViewRelated/Products/Edit%20Product/Edit%20Price/Product%2BPriceSettingsViewModels.swift#L23) we add a non-breaking space (with this currency position setting) and then when we format the new price input we [convert that non-breaking space into a decimal separator](https://github.com/woocommerce/woocommerce-ios/blob/14675cafe15421267f96031c8b9203e113a18b0c/WooCommerce/Classes/Tools/UnitInputFormatter/PriceInputFormatter.swift#L52).

h/t @rossanafmenezes for the report! (ref: p1724774360226269-slack-C6H8C3G23)

**To Reproduce**
1. Set your store **currency position** setting to "Left with space" (in WooCommerce > Settings > Currency options > Currency position).
2. Set the **number of decimals** setting to 0.
3. Close and relaunch the app (to ensure the latest currency settings are used).
4. Go to the Products tab.
5. Select a product and open its Price settings.
6. In the price field, edit the price (e.g. add or remove a number).
7. Notice a decimal separator appears to the left of the entered price.

**Screenshots**

https://github.com/user-attachments/assets/fd703d14-dc42-4d7b-8bd1-76923c32599f

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
