### ISSUE TITLE
Show budget field on Blaze dashboard card

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#13760]
As suggested by Jorge in an internal thread [p1724749992137369-slack-C03L1NF1EA3]:

> With the updated design for Blaze Campaign item where we display 2 stats: CTR and budget. [...] Imho displaying the budget there would be useful too.

We should show the budget field on the dashboard card:

![image](https://github.com/user-attachments/assets/981391fe-187a-4f64-8342-0fa012b35a51)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
