### ISSUE TITLE
Blaze: When a campaign is canceled, the status is not immediately updated.

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#13795]
To repro:

1. Go to a Product, then **Promote with Blaze**,
2. Create the campaign,
3. Go to **Menu > Blaze**, confirm that the campaign is listed with "In Moderation" status,
4. Tap the campaign to show **Campaign Details** sheet,
5. Scroll down, tap **Cancel Campaign**,
6. Confirm the cancellation,
7. Tap "Done" in the sheet,
8. Blaze campaigns list is now shown.
9. Note that the campaign status is still "In Moderation". **Expected status: Canceled**.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
