### ISSUE TITLE
[Woo POS] Smoothly animate the processing progress view

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13800]
> Does the payment view usually chop like that for you or does it only appear in the video, @joshheald ?
> 
> <img width="814" alt="image" src="https://github.com/user-attachments/assets/baedbfff-54cb-4af4-b545-5fcb665f935a">
> 
> _Originally posted by @staskus in https://github.com/woocommerce/woocommerce-ios/issues/13789#issuecomment-2320278891_

This was first introduced with the animation for Processing Payment waves:  #13753

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
@joshheald , I wonder if it's related to my suggestion to disable transition on insertion:

> .transition(.asymmetric(insertion: .identity, removal: .opacity))

**Comment by joshheald** [comment]
> @joshheald , I wonder if it's related to my suggestion to disable transition on insertion:
> 
> > .transition(.asymmetric(insertion: .identity, removal: .opacity))

I was trying to give them the same `id(_:)`, but that's not enough. I suspect it's because I've used `ProgressView`, but I'm surprised neither of us noticed it on that PR.

Removing the asymmetric transition doesn't fix it though.

Next step is to try to synchronise the `progress` value for the two views, or just use a plain animating view.

**Comment by staskus** [comment]
> I was trying to give them the same id(_:), but that's not enough. I suspect it's because I've used ProgressView, but I'm surprised neither of us noticed it on that PR.

I guess because all of it depends on timing. I still used a simulated card reader when testing the PR. If there's enough time for the animation to complete before processing payment ("Please wait..") starts, then there's no glitch. One option to try is to shorten the animation `totalsFieldsHideAnimationDelay`. Although that's not a bulletproof fix.

**Comment by joshheald** [comment]
Ah, so you think it's the transition between 
1. `tap/swipe/insert`, 
2. `remove card`, and 
3. `processing` 

...happening too fast for `2` to finish animating in, so the next animation glitches? Makes sense...

I'll try shortening the animations to start with. Beyond that the options are a bit limited – making the processing view mutable with different labels could work, but serving those changes with the design of the card payment service would be quite difficult.

I sort of want each message to stay on screen for a minimum amount of time, an artificial delay or something... but that's bound to make other parts of the flow confusing.

**Comment by joshheald** [comment]
It does work better when you insert the card than when you tap, because each state lasts longer.

`totalsFieldsHideAnimationDelay = 0.4` appears to fix it fully on my hardware. But I don't love it!

Throttling payment events for a second works – it leaves `Remove Card` for a second before moving to `Processing Payment`, but it makes other parts less responsive – e.g. when you tap `Connect to Reader` to confirm a connection, it doesn't move to the `Connecting` state for a second, so you can tap the button again... which means we get two connection attempts, one of which causes an error to flash up.

What we really want is a combination of throttle and buffer... [which lead me to this beauty of an SO answer.](https://stackoverflow.com/a/59386819/1679697)

Using `buffer` and `pace` on the payment event publisher in totals view, and sharing it between all the consumers of the payment events, works really well. 

You can pace the events to 1s and still have the animations work right at 0.8s. It's a bit nicer having the messages all stay on screen for at least 1s, too, it just makes the process seem a little calmer and less flickery.

However... I don't love the idea of just dumping 250 lines of StackOverflow code into the app in one go. I'll keep it in an experimental branch and try to review it properly as and when we get time.

For now, 0.4s transitions will have to do.
