### ISSUE TITLE
[Woo POS] Simple products banner disappears on pull to refresh

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13818]
Pull to refresh on the product list while the Simple Products banner is showing temporarily hides the banner:

https://github.com/user-attachments/assets/2872249a-aa02-49f0-869c-f14e7cccae5a

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
Duplicate of #13865
