### ISSUE TITLE
Orders badge: move y position up a bit when space is allowed

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1381]
A followup from https://github.com/woocommerce/woocommerce-ios/pull/1366 - we can potentially check the height of the `UITabBar` and use the current y offset for height <= 32, and move the y offset up for a bit if the height is taller (check the Orders-Badge-Fixes Figma file).

**Comment by mindgraffiti** [comment]
The order badge has been moved to using the default property instead of a custom control. This bug is no longer applicable :)
