### ISSUE TITLE
Coupons: Title is set to `Reviews` rather than `Coupons`

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13837]
Under Menu > Coupons, the navigation title is set to `Reviews`:

<img width="497" alt="Screenshot 2024-09-04 at 12 12 10" src="https://github.com/user-attachments/assets/1cbb775d-8367-4cb2-87cc-712765b9a685">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
Fixed via https://github.com/woocommerce/woocommerce-ios/pull/13836
