### ISSUE TITLE
Show editor for HTML fields

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#13831]

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by hichamboushaba** [comment]
@hafizrahman should we mark this as done?

**Comment by hafizrahman** [comment]
Solved in https://github.com/woocommerce/woocommerce-ios/pull/13925
