### ISSUE TITLE
[Woo POS] Improvement: Remove experimental toggle flag

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13838]
From p1725337084101939-slack-C070SJRA8DP

> Now that the remote feature flag is accessible . Should we also remove the "experimental feature" POS toggle from Menu > Settings for simplicity? This was added so we could start to work on the POS right away, but since we can whitelist specific accounts we could just rely on this + a general feature flag set to localDev/alpha

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
