### ISSUE TITLE
Blaze: Separate states for the schedule sheet and budget settings screen

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#13844]
During beta testing [p1725280274586889/1725280085.228949-slack-C03L1NF1EA3], Irfan found the issue: 

> When I switch the “Specify the duration” and tap “Cancel,” the budget screen is affected.

Expected: the budget screen is updated only upon tapping Apply button

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
