### ISSUE TITLE
Add new / update custom field UI

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#13841]

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by hafizrahman** [comment]
Add new custom field UI added in https://github.com/woocommerce/woocommerce-ios/pull/14175
Update custom field UI added in https://github.com/woocommerce/woocommerce-ios/pull/13863
