### ISSUE TITLE
[Woo POS] Connection to Reader fails with 2 payment providers and using POS immediately after login

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13842]
**Describe the bug**

Connection to Reader fails with 2 payment providers and using POS immediately after login. It's only reproducible after completing onboarding, logging out, and logging in.

I think the issue is with onboarding not being complete and the WooPayments option selected. However, Point Of Sale option is still shown and Payments menu doesn't indicate any onboarding steps that are not completed.

**To Reproduce**

Configure the site with two payment providers:
- Stripe
- WooPayments

Before starting:
- Complete onboarding and log out

1. Login
2. Menu
3. Select the Point Of Sale option
4. Tap Card Reader
5. Notice nothing happens

Workaround 1:
1. Select Payments
2. Notice no prompt to finish onboarding
3. Select Payment Provider
4. Select WooPayments

Workaround 2:
1. Kill and relaunch the app
2. Notice no POS option
3. Select Payments
4. Finish the setup by selecting WooPayments

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPad Air 11 Inch M2
- iOS version: 17.5
- WooCommerce iOS version: 

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
