### ISSUE TITLE
[TTP] Improvement: Check for location services earlier through the setup/payment flow

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13857]
Ref: p1725392267682619-slack-C025A8VV728

> Something I think is worth improving thought is that, once TTP is setup, we allow to fully attempt to process a TTP payment before checking if location services is enabled, only to discover after a payment failure that this was disabled later on.

> So this is allowed: Setup TTP > allow location services > then disable location services again > try a payment and tap the card >  then finally receive the error message from the API that wasn't possible to process it.

> We could perform this location check earlier in the process during the payment attempt flow

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
@staskus Again, this is basically the same thing as #13885 and #13985, and has links to the TTP project too, so I've assigned you.

**Comment by staskus** [comment]
Closing, it will be done in the scope of https://github.com/woocommerce/woocommerce-ios/issues/14168
