### ISSUE TITLE
Add MarkOrderAsReadUseCase tests

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#13851]
After getting feedback in https://github.com/woocommerce/woocommerce-ios/pull/13734#pullrequestreview-2278795310 I tried adding the tests but it would need more changes to be able to test it so it is best to do it as a separate PR

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
