### ISSUE TITLE
Keyboard not showing immediately when adding a new category for a product

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#13860]
When adding a category for the product it would be nice if the text field would be active immeditaly with keyboard shown as we do with some other fields.

![IMG_2900](https://github.com/user-attachments/assets/3a43b446-d240-44cb-af14-c4ae793867bf)

We need to tap the text field, it would be great if it was already a first responder (in focus):

![IMG_2901](https://github.com/user-attachments/assets/a50ea6e7-a051-412b-9e68-cf2a43a5ac29)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
