### ISSUE TITLE
Applied coupon showing just in bottom details sheet

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#13861]
I applied the coupon on an order and it shows in the details bottom sheet but I would expect it to show also where the “Add Coupon” is.

<img src="https://github.com/user-attachments/assets/73088cd7-c08e-4e4f-9990-5ed913670bc5" width="250px" />

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by toupper** [comment]
Closing the issue as this was an intended design decision to keep the order buttons area as clean as possible

**Comment by toupper** [comment]
Confirmed from @joe-keenan that this should be indeed improved. We can take the Shipping section as reference and review with Joe if necessary. pe5pgL-5G4-p2#comment-4489

**Comment by iamgabrielma** [comment]
Completed via https://github.com/woocommerce/woocommerce-ios/pull/14107. Closing!
