### ISSUE TITLE
Blaze: Format the click-through rates on the detail card to human-readable format

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#13864]
Now | Expected
--- | ---
<img src="https://github.com/user-attachments/assets/38c75120-4504-40aa-a482-716ad9ed632f" width=320 /> | <img src="https://github.com/user-attachments/assets/d99ddbaf-9492-45d7-969b-62e84b28650d" width=320 />

Note: we should also collapse the content to a vertical stack when the text is too long to avoid cutoff.

Internal thread: p1725547339131059-slack-C03L1NF1EA3

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
