### ISSUE TITLE
[Woo POS] Keep simple products banner visible while pull-to-refresh

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13865]
Ref: p91TBi-c45-p2#comment-13036

https://github.com/user-attachments/assets/aad43c9e-2b38-46a2-9c18-11586d1cb5a4

> When the “Show simple products only” banner is visible and pull to refresh happens, we hide the banner and show the exclamation mark icon for some reason. Not sure if it’s a bug or not, but it feels off

This seems to happen because one of the checks for the banner to display is state.isLoaded , but during sync after pull-to-refresh is not loaded but loading.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
See also #13878, as it might be easiest to fix both at the same time
