### ISSUE TITLE
[Woo POS] Wrap product name in cards to two lines

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13875]
## Description
We show enough for a few words at the 100% default Dynamic Type size, but only ever one line. I think it looks OK, but we could always give it two or three lines before truncating…
The product list and checkout show a similar amount of text, but cart view on the product list shows less because of the x remove button.
It’s a judgement call, but perhaps we should allow these to wrap to two lines, and increase the row height?

p91TBi-c11-p2#comment-12959

![image](https://github.com/user-attachments/assets/a3097162-60b8-44d6-ab6d-ece9039804a1)
![image](https://github.com/user-attachments/assets/388369b1-e1ff-4315-9003-302ddf207fe5)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
