### ISSUE TITLE
Mark order notification read if needed on watch app and notification extension

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#13873]
As a continuation on https://github.com/woocommerce/woocommerce-ios/pull/13734 we need to add marking order notification as read on Watch app and in notification extension in a same logic as we do in the app.
Because it needs a bit more code changes we did not do it in https://github.com/woocommerce/woocommerce-ios/pull/13734 but will do in separate PR(s).

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
