### ISSUE TITLE
[Woo POS] Close reader connection modals immediately on cancel

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13879]
## Description
Some of the connection modals have an `x` to cancel the connection and close the modal.

These currently take a few seconds to close the modal, because cancelling takes time and we don't want merchants to start a new connection while it's going on.

It would be better if we could dismiss immediately, then disable the `connect` button until the cancellation completes.

In theory, this could benefit IPP as well, which has the same issue on its cancellation buttons, but it may be too complex/risky to do it at that level.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
