### ISSUE TITLE
[Woo POS] Ensure that the simple payments banner doesn't block scrolling the product list at large dynamic type sizes

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13878]
## Description

> When using large text (I used the largest available) for the first time, user can’t scroll through the list of products because of the ℹ️ message about Simple Products only, which is fixed on top of the products list:
> ![CleanShot 2024-09-06 at 16 38 14@2x](https://github.com/user-attachments/assets/737e14a2-40ed-41e9-bf44-95dc9eb90e71)

Putting the banner inside the list’s scrollview might fix both this, and the issue where it disappears temporarily on pull to refresh. (#13865)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
