### ISSUE TITLE
Login process: wrong button status when I enter my site address

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#1387]
When I try to add a new self-hosted website into the app, and I press the right bottom button `Next`, the button becomes white (not tappable) and I don't get any visual feedback or loader that something it's working under the hood.

| Screen during the loading process           |  Initial screen with a correct (not tappable) button status |
:-------------------------:|:-------------------------:
![Simulator Screen Shot - iPhone 11 Pro - 2019-10-22 at 11 46 41](https://user-images.githubusercontent.com/495617/67276136-55b1e500-f4c4-11e9-965b-d3cce981b0cb.png) | ![Simulator Screen Shot - iPhone 11 Pro - 2019-10-22 at 11 59 53](https://user-images.githubusercontent.com/495617/67276130-50ed3100-f4c4-11e9-9425-c64317584c4f.png)

I also believe that giving an indication of loading could be useful for the user at this stage (I myself believed that the process had stopped).

**Comment by mindgraffiti** [comment]
Same issue as https://github.com/wordpress-mobile/WordPress-iOS/issues/12547

**Comment by mindgraffiti** [comment]
Issue was addressed during Authenticator dark mode fixes. Thank you @jaclync !

<img src="https://user-images.githubusercontent.com/1062444/72106678-67ea3500-32f5-11ea-80f0-4b0c69f714f7.PNG" width="350" />
