### ISSUE TITLE
Login using passwordless WPCOM account doesn't work

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13886]
While smoke testing build `20.2.0.2` I noticed that login using passwordless WPCOM doesn't work. 

p1725852559212019-slack-C03L1NF1EA3 

#### Steps I followed
* Created a passwordless login WPCOM account.
* Connected a JN site’s Jetpack with the above WPCOM account
* Logged into mobile Gmail using the passwordless account’s email. 
* Logged into mobile Safari using the passwordless WPCOM account.
* Tried to login from Woo mobile app.
* The app opens and stays on the “Open mail” screen. 

#### Video recording

https://github.com/user-attachments/assets/fdc34fa0-7c5b-47f7-b147-e8bfebb8fa53

#### Expected behaviour
The app should logic after opening the link from the email.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by pmusolino** [comment]
More: peaMlT-SZ
