### ISSUE TITLE
Xcode 11 + dark mode: regression on background colors of some cells in OrderDetails screen

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#1389]
#2438744-zen

Seems that in the release 2.8 of the app there was a regression on OrderDetails screen when the dark mode is enabled.

Related PR: https://github.com/woocommerce/woocommerce-ios/pull/1329

**Screenshots**
![image0](https://user-images.githubusercontent.com/495617/67297081-b273c680-f4e9-11e9-883b-983cb3d46d36.png)

**Mobile Environment**
- Device: iPhone X
- iOS version: 13
- WooCommerce iOS version: 2.8

**Comment by rachelmcr** [comment]
I see similar issues when I tap from the OrderDetails screen to edit the order status, or view the Billing Information or Product Details:

<img src="https://user-images.githubusercontent.com/8658164/68472144-c15fb600-0217-11ea-9dac-a1bf0161ac52.png" width="50%">

<img src="https://user-images.githubusercontent.com/8658164/68472146-c3c21000-0217-11ea-8aef-a7e4c84018cd.png" width="50%">

<img src="https://user-images.githubusercontent.com/8658164/68472168-d0deff00-0217-11ea-840a-c997935d6586.png" width="50%">

**Comment by jaclync** [comment]
Moved the related issues in @rachelmcr's comment to a new issue: https://github.com/woocommerce/woocommerce-ios/issues/1447
