### ISSUE TITLE
[Woo POS] Increase size of connection modals at 100% slightly to avoid clipping

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13890]
The reader connection modals slightly clip the text (scrolling works) at 100% on the "Found reader" modal.

We can slightly increase the modal size, and/or decrease the padding for the buttons, to improve this.

Context: TfaZ4LUkEwEGrxfnEFzvJj-fi-4650_22621 TfaZ4LUkEwEGrxfnEFzvJj-fi-4650_22626

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
