### ISSUE TITLE
Product Selector shows incorrect title for single selection mode

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#13902]
**Describe the bug**
Reported by Hicham in an internal thread [p1725903622524529-slack-C03L1NF1EA3]:

> I found a very minor bug with the product selector, the header saying “1 product selected” goes into an inconsistent state when coming back then selecting a different product (it thinks that more than one product is selected), check the video for more details

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
