### ISSUE TITLE
[Woo POS] Tapping on background should close a modal

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13912]
## Description
Where possible, POS modals should be dismissable by tapping on the background.
Context: TfaZ4LUkEwEGrxfnEFzvJj-fi-4665_22725

## Locations
- Simple Products dialog
- Exit POS confirmation
- Cancellable reader connection modals (note that cancellation needs more robust handling before we do this)
- Reader connection success

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
