### ISSUE TITLE
[Woo POS] Floating Button Updates

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13916]
https://github.com/woocommerce/woocommerce-ios/issues/13859

### Floating Button
- [x] Floating button padding in all the states TfaZ4LUkEwEGrxfnEFzvJj-fi-4646_21885 TfaZ4LUkEwEGrxfnEFzvJj-fi-4650_22606 TfaZ4LUkEwEGrxfnEFzvJj-fi-4650_22611
- [x] Floating button shadow TfaZ4LUkEwEGrxfnEFzvJj-fi-4650_22252
- [x] [Animation] Fade-in color changes TfaZ4LUkEwEGrxfnEFzvJj-fi-4665_22745
- [x] Show disabled state clearly on reader disconnect button in success view TfaZ4LUkEwEGrxfnEFzvJj-fi-4665_22801

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
