### ISSUE TITLE
[Woo POS] Cart images load with a delay

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13915]
Potential approach. Ref: p1725963011089909/1725938613.801719-slack-C070SJRA8DP

> We use ProductImageThumbnail which internally uses [KFImage](https://github.com/onevcat/Kingfisher/tree/master), which has many convenient features, including caching.
If we have the same image URL for both the product list and cart list, I think playing around [with caching settings](https://github.com/onevcat/Kingfisher/tree/master?tab=readme-ov-file#a-more-advanced-example) could be enough to make sure the same image is loaded in both cases. If URLs for larger and smaller images are different, I think KFImage would also allow prefetch images in a view model. We wouldn’t need to pass UIImage or Data from view model, Kingfisher caches images using url internally. (edited)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
