### ISSUE TITLE
[Orders] Badge count missing on orders tab icon after switching stores

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#13919]
**Describe the bug**

I expect to see a badge on the Orders tab icon in the main tab bar, showing the number of orders with the `processing` status. After switching stores, that badge no longer appears even after pulling to refresh the order list.

**To Reproduce**
1. Build and run the app.
2. Open the Orders tab and confirm there are orders with the `processing` status, and a badge appears on the Orders icon with the count.
3. Go to the hub menu and switch stores.
4. Notice that no badge appears above the Orders icon in the tab bar, even if you visit the Orders tab and pull to refresh the list.

**Screenshots**

Expected|After switching stores
-|-
![IMG_4216](https://github.com/user-attachments/assets/44eb7e7a-376e-4fca-8317-2c7a3eaf6879)|![IMG_E11265768E43-1](https://github.com/user-attachments/assets/d62cb95e-37a8-4551-ac7f-ce9dbf1335f6)

**App details**

I noticed this while testing in the 20.3 beta but I confirmed the same issue exists at least in the 20.2 release so it isn't a brand new issue. I'm not sure how long it has been around.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by bozidarsevo** [comment]
Looks like it was fixed in the meantime:

![Image](https://github.com/user-attachments/assets/217ecc97-588d-4161-84cc-2023a4d1bad4)
