### ISSUE TITLE
[WooPOS] iPadOS 18 support - hide a new tab bar

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13938]
Xcode 16 SDK + iPadOS 18 support: hide a new tab bar and fix the bottom spacing for POS

![Image](https://github.com/user-attachments/assets/5da06c87-7ce1-405d-af25-39a51a6cb768)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by staskus** [comment]
It was addressed in https://github.com/woocommerce/woocommerce-ios/pull/14136. A proper fix will require a larger project [peaMlT-SO-p2](https://href.li/?https://wp.me/peaMlT-SO)
