### ISSUE TITLE
Blaze: Update layout for the loading and error states of the objective picker

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#13942]
The contents are currently pushed to the center of the screen:

<img src="https://github.com/user-attachments/assets/3cb241f6-18b9-4ae1-a688-9e0ef5da700e" width=320 />
<img src="https://github.com/user-attachments/assets/d09a51bc-a63f-431c-bd89-99ed48702eb5" width=320 />

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
