### ISSUE TITLE
[Order Creation] Amount field is not highlighted while adding "Shipping"

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13956]
#### Issue

While creating an order, the "Amount" field in the "Shipping" screen is not highlighted. 

Internal - pe5sF9-38F-p2

#### Screenshot

https://github.com/user-attachments/assets/e8e91409-6a12-4969-8868-94c0563ed158

#### Expected behaviour
Tapping on the "Amount" field should show the cursor on the Amount field or highlight it in some other manner.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
Just a note that this is not specific to the Shipping screen — it's true of all screens using the `FormattableAmountTextField` view, which hides the input text field and shows the amount as a text label instead (https://github.com/woocommerce/woocommerce-ios/pull/5805).

**Comment by Ecarrion** [comment]
> Just a note that this is not specific to the Shipping screen

True, the same happens on the custom amount screen.
