### ISSUE TITLE
Xcode 16 Support: Update ViewInspector dependency to run unit tests

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13951]
**Describe the bug**

Unit Test target doesn't run on Xcode 16 due to `the compiler is unable to type-check this expression in reasonable time` error.

This is an issue with [ViewInspector](https://github.com/nalexn/ViewInspector/issues/307) package. 

**To Reproduce**
1. Open Xcode 16
2. Try to run Unit Test target

**Screenshots**

![image](https://github.com/user-attachments/assets/619c1690-7ad5-4002-a903-910b530a9665)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
