### ISSUE TITLE
[Widget] Widget doesn't show any info and shows empty black screen

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13954]
#### Issue

The stats widget is empty. 

#### Screenshots

<img src="https://github.com/user-attachments/assets/afdedb06-1026-41ed-a28b-4caddaa3b196" width="320"/>

https://github.com/user-attachments/assets/19c0e833-e7b0-4ab2-aae2-9884a38cd360

#### Test information
- JN site connected with Jetpack
- iPhone 13 Pro Max running iOS 18.0
- Woo build - `20.3.0.1` from TestFlight

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by Ecarrion** [comment]
Tested the `20.3.0.1` testflight build with an iPhone 15 Pro running iOS `17.6.1` and seems to be working correctly.

![Screenshot 2024-09-13 at 9 49 28 AM](https://github.com/user-attachments/assets/df738e64-e6a0-4241-b80b-dc9afaee3efc)


I'll move this to `waiting` and will test next week when iOS 18 comes out!

**Comment by Ecarrion** [comment]
@selanthiraiyan Tested this with the newly released iOS 18 and seems to be working ok for me.

Could you please re-test it with the official release?

![Screenshot 2024-09-16 at 2 47 54 PM](https://github.com/user-attachments/assets/46425c62-c3db-4810-b9b6-4d2d704072df)

**Comment by selanthiraiyan** [comment]
Thanks for looking into this, Ernesto! 

Yes, the widget works with the official 1OS 18 release. I think we can close the issue. 

<img src="https://github.com/user-attachments/assets/b9f0ea96-b6ce-4c45-9be7-060544932215" width="320"/>

**Comment by toupper** [comment]
This ticket might be related 8748662-zd-a8c
