### ISSUE TITLE
[Woo POS] If order total too high, need to exit POS to recover

### ISSUE THREAD

**Issue by lmischner** [woocommerce/woocommerce-ios#13966]
**Describe the bug**
There's an error that "the payment can not be processed by the payment processor" when the due payment total is too high. In that case, the user can only go back and modify the order if they fully exit POS, since that recalculation happens on the checkout screen. 

**To Reproduce**
1. (I'm not sure the actual limit), but in the Woo DM Swag store, add the 'coffee chat with Beau' product
2. Go to checkout
3. If card reader isn't connected yet, connect card reader
4. Note the error 
5. Try to recover
6. Keep trying
7. Note you can't without exiting POS

**Screenshots**
In this workflow, I try both "try payment again" and "go back to checkout", as well as trying to quickly tap the back arrow in the card, but no luck :( 

https://github.com/user-attachments/assets/997f7929-995f-40ce-9131-843d5c8b0ed3

**Expected behavior**
User should be able to both know how to fix the error (can we give some indication that the payment totla is too high?) and fix it without leaving POS

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPad Air
- iOS version: iPadOS 17.1
- WooCommerce iOS version: TestFlight 20.3

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by lmischner** [comment]
If we opt not to fix this before the DM, we should change the dollar amount on the Coffee Chat with Beau product, or we'll get this same issue reported a lot 😆
