### ISSUE TITLE
Xcode 11 + Dark mode: glitch on My store screen when view loads content

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#1396]
There is a glitch when dark mode is enabled on "My Store" screen.

When the view is refreshed, you can see a dark line, which disappears when the bottom content is loaded. 

**To Reproduce**
1. Go to a tab, different from "My store"
2. Click on "My store" tab
3. When the view is loading, you can see the glitch.

**Screenshots**
![loading error](https://user-images.githubusercontent.com/495617/67499549-973bbf00-f681-11e9-91da-6fb31a7d3f08.gif)

**Mobile Environment**
Please include:
- Device: iPhone X
- iOS version: 13
- WooCommerce iOS version: 2.8

**Comment by jaclync** [comment]
Is this the same as this issue? https://github.com/woocommerce/woocommerce-ios/issues/1334 - it's fixed in 2.9 and the latest `develop` :)

**Comment by pmusolino** [comment]
> Is this the same as this issue? #1334 - it's fixed in 2.9 and the latest `develop` :)

From the description seems the same, but from the screenshot, the location seems different. In my case the ghost view it's located between the first and the second cell, in your case, it's under the header "Top performers".

**Comment by jaclync** [comment]
do you still see this issue from the latest `develop`?

**Comment by pmusolino** [comment]
I'm not able to login into the app at the moment, after Xcode 11 migration. I'll check it asap

**Comment by pmusolino** [comment]
I confirm that the glitch is no longer present.
