### ISSUE TITLE
Text Fields display a different value than originally added when store and device settings differ

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13961]
**Describe the bug**

Edit Discount View displays a different discount than originally added when store and device settings differ

Context: pdfdoF-5mQ-p2
Related PR: https://github.com/woocommerce/woocommerce-ios/pull/13854

## Analysis

The issue is a broken PriceFieldFormatter.formatAmount method. The easiest way to reproduce the issue is just to paste “1,000.40” into the input field and see it turn into "1". This method is created to sanitize the user input when it is entered. When the user inputs either 10,0 or 10.0, it assumes it's a decimal separator, and turns it into a decimal separator set in store settings.

        // Removes any unwanted character & makes sure to use the store decimal separator
        let sanitized = amount
            .replacingOccurrences(of: deviceDecimalSeparator, with: storeDecimalSeparator)
            .filter { $0.isNumber || "\($0)" == storeDecimalSeparator }

When I input 1,000.40 it is "sanitized" into 1.000.4 rather than into 1000.4. Subsequent conversions turn 1.000.4 into $1.00. It requires the device locale to have , a decimal separator to have this issue. For example, my one.

We essentially want to support input with both store and device settings and interpret it in “the most correct way possible”. Relying solely on Decimal(string is also not possible since it accepts input using the device locale. If the formatted store string has different separators than the device locale, it will fail as well. We cannot restrict the input since the iOS decimal keyboard shows a decimal separator based on the device’s locale. However, when the user pastes into the field or uses iPad the number can also be in the store locale.

A few approaches are tried are almost correct but I can always find a combination to break it. I found Android has put more restrictions on the input field. I think a reasonable compromise when device settings != store settings is to:

1. Assume user input is in device settings but sanitize and format the text field in store settings. Use a formatter that clearly describes in code to prioritize device settings over store settings when interpreting the value
2. A limitation is that pasting a value formatted in store settings may not work as expected
Assume the formatted amount is in store settings. Therefore, use a different formatter when re-opening the discounts view, that prioritizes store settings over device settings when interpreting the value.

It’s all messy, to say the least. One of the options we could choose within the app is to always use device settings over store settings when formatting amounts and only do necessary conversions to store settings at the API level.

**To Reproduce**
1. Configure store and device to have different locales (I tested US for store and LT for a device). Store locale should have a thousand separator that would match a decimal separator on a device
2. Orders
3. New
4. Add product
5. Add discount on a product larger than a thousand - 1000.42
6. Save
7. Edit the discount
8. Notice the value is set to $1.00

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: 
- iOS version: 
- WooCommerce iOS version: 

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
The same issue also appears for cash payments.
