### ISSUE TITLE
[Woo POS] Cart view design updates

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13970]
- TfaZ4LUkEwEGrxfnEFzvJj-fi-4650_22586 ✅ -> commented on  TfaZ4LUkEwEGrxfnEFzvJj-fi-4650_22586#950216468 for details
- TfaZ4LUkEwEGrxfnEFzvJj-fi-4665_22735 ✅

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
