### ISSUE TITLE
[Mobile Payments] Improvement: show specific error details in the UI for more Stripe error codes

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#13978]
## Description

In `UnderlyingError+Stripe`, we decode some of Stripe's errors into an enum which we can use to log, track, and present error information to merchants.

These are decoded from Stripe's `SCPErrors.ErrorCode` enum/integer codes, but we don't decode every one of these, and many are likely to have been added over time.

We should update the StripeTerminal dependency, then decode as many of these that make sense to show to merchants, adding relevant user-facing strings to be translated in the `UnderlyingError.errorDescription` property. These will be shown to users in error messages, and logged correctly.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
