### ISSUE TITLE
Display attached coupons in Order Creation (same as shipping)

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-ios#13971]
I applied the coupon on an order and it shows in the details bottom sheet but I would expect it to show also where the “Add Coupon” is.

<img src="https://github.com/user-attachments/assets/73088cd7-c08e-4e4f-9990-5ed913670bc5" width="250px" />

We can take the Shipping section as reference and review with Joe if necessary. pe5pgL-5G4-p2#comment-4489

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
