### ISSUE TITLE
[Woo POS] Too large order total leads to getting stuck in payment error state

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#13980]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

Adding a super expensive product leads to a payment failure which doesn't allow to come back to order view.

**To Reproduce**
1. Add an item worth $1000000
2. Connect the reader
3. Check out
4. Notice an error appear
5. No matter which option is chosen, "Checking Order" loads and fails again and again without a way to come back to the menu

**Videos**

https://github.com/user-attachments/assets/8c6f600d-0e6f-4103-83dc-0012291b9371

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: 
- iOS version: 
- WooCommerce iOS version: 

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
Duplicate of https://github.com/woocommerce/woocommerce-ios/issues/13966
