### ISSUE TITLE
Unit Tests: `CurrencySettingTests` fail on first run

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1398]
**Describe the bug**
The `testInitWithIndividualParameters` unit test in `CurrencySettingsTests` fails on the first run only. Any subsequent runs are fine. 

**To Reproduce**
This happens most often when I switch to a branch that's not mine, I have to run `bundle install`, followed by `bundle exec pod install`. After I install pods, I use Cmd + B to build, and then I run the unit tests. Getting Xcode in this specific state has been difficult to reproduce.

**Steps to reproduce the behavior:**
Unknown. Whatever requirement causes `bundle install` to be needed, sets the environment in the state that causes the unit test to fail. Deleting derived data doesn't seem to be enough. Cleaning the project doesn't trigger the unit test to fail either.

**Screenshots**

**Expected behavior**
I _think_ this is happening because `CurrencySettings` is a singleton, and the setUp() and teardDown() methods aren't impelmented.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: 
- iOS version: 
- WooCommerce iOS version: 

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by mindgraffiti** [comment]
I think I have a fix to this, if I can figure out how to reproduce the problem consistently.

**Comment by ctarda** [comment]
It is happening for me as well, and I can reproduce it every time I switch branches. The first run fails, the second (sometimes it's the third) passes

**Comment by ctarda** [comment]
@mindgraffiti since it seems to fail consistently for me, would you mind pushing a branch that I could test?

**Comment by mindgraffiti** [comment]
@ctarda yes, of course: https://github.com/woocommerce/woocommerce-ios/pull/1404. I ran out of time last week to write up the PR.

**Comment by ctarda** [comment]
Reopening. As noticed by @pmusolino on the review of #1406 it seems like the tests might be still failing on first run, right after checking out a branch

**Comment by mindgraffiti** [comment]
Do you think the local variables are still part of the problem? The unit test originally stopped failing after I moved them to be global variables and cleared them out in the teardown method. Maybe I should have kept that in my original PR.

**Comment by ctarda** [comment]
I am not sure. First, I re-opened this but I made a mistake, as what Paolo noticed is a different set of tests failing. But I guess, as Jaclyn mentioned in #1409 , these two look like they might be related
