### ISSUE TITLE
[Mobile Payments] TTP connection error upon fresh installation

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-ios#13984]
**Describe the bug**
Upon fresh installation, TTP displayed the “Connecting to my account” screen indefinitely, followed by the Stripe screen for tap-to-pay. After completing the payment, it navigated back to the same “Connecting to my account” screen. This issue occurs every time on a fresh install

https://github.com/user-attachments/assets/e4115b89-e5b5-4fd9-822c-aa7a3a12e92f

**To Reproduce**
1. Freshly install WooCommerce iOS app
2. Navigate to payments settings (more menu -> Payments)
3. Try to collect payment with TTP
4. TTP gets stuck on `Connecting to my account` screen

**Expected behavior**
TTP should connect to my account successfully and proceed ahead with the payment collection screens.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
This was fixed in #14017 – I've confirmed it works as expected today as well.
