### ISSUE TITLE
Missing tab bar name of Dashboard compiling the app with Xcode 16 on iOS 18 on iPad

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#13989]
When compiling the app with Xcode 16 for iOS 18 on an iPad, the tab bar name for the Dashboard is missing. This issue affects the user interface and usability of the app, as users are unable to see the label for the Dashboard tab, which can lead to confusion and a poor user experience.

#### Steps to Reproduce:
1. Open the project in Xcode 16.
2. Compile and run the app on an iPad simulator running iOS 18.
3. Observe that the tab bar on top, have the missing Dashboard name "My store".

#### Screenshot

<img src="https://github.com/user-attachments/assets/536fe041-4a01-4ee3-ae54-3bc6bf203192" width=300 />

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
@pmusolino,  I'm assigning this to myself right now in the scope of [iPadOS 18 Tab Support](https://github.com/woocommerce/woocommerce-ios/issues/13910). 

There are more issues, such as missing buttons to create or search Products or Orders. I may find even more while digging deeper.

**Comment by staskus** [comment]
It was addressed in https://github.com/woocommerce/woocommerce-ios/pull/14136. A proper fix will require a larger project peaMlT-SO-p2
