### ISSUE TITLE
[Mobile Payments] Incorrect bluetooth permission error while connecting to a reader upon fresh installation

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-ios#13987]
**Describe the bug**
When attempting to connect to a card reader from the Payment Hub menu with Bluetooth turned off, the app prompts the user to enable Bluetooth. If the user denies the request, an incorrect ‘Payment Failed’ error message appears. However, on subsequent attempts, the correct error message is shown. This issue seems to occur only on a fresh installation.

**To Reproduce**
1. Freshly install the WooCommerce iOS app
2. Navigate to payments settings (more menu -> payments)
3. Click on "Manage card reader"
4. Ensure bluetooth is turned off
5. Try connecting to the card reader
6. When asked for bluetooth permission, deny it
7. Observe the error message says payment failed instead of bluetooth permission missing.

https://github.com/user-attachments/assets/9a6af1ea-e0ee-4182-8c84-c166e3917ee8

**Expected behavior**
Error message should clearly indicate that the bluetooth permission must be granted to connect to a reader.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
