### ISSUE TITLE
Dashboard: Update layout to support large screens

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#13988]
Currently, the dashboard screen is spread out the whole screen which is not the best experience on large screens:

<img src="https://github.com/user-attachments/assets/facf9d94-92a0-4deb-86a1-3c75c6a1fdea" width=320 />

Showing the cards in two columns would make it more intuitive for large devices.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by selanthiraiyan** [comment]
This might be the same as https://github.com/woocommerce/woocommerce-ios/issues/13093

**Comment by itsmeichigo** [comment]
Thanks @selanthiraiyan, I was trying to find the issue but could not find it 😅
