### ISSUE TITLE
[Mobile Payments] TTP asks location permission after initiating the payment instead of before.

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-ios#13985]
**Describe the bug**
I found it odd that iOS prompts for location permission after the card is tapped, rather than before initiating the payment for TTP. Stripe’s payment screen gives the impression that the transaction is nearly complete, but when it redirects back to the WooCommerce app, the transaction fails if location services are off, prompting users to enable location. It would save time if merchants were asked to turn on location up front when the transaction starts.

**To Reproduce**
1. Navigate to any pending order eligible for TTP
2. Ensure location is off on your phone
3. Try collecting the payment
4. Payment initiates and Stripe's screen is shown to tap the card on the phone
5. After tapping the card, location not turned on error is shown!

**Expected behavior**
Location permission must ideally be asked before initiating the payment.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
@staskus I've assigned you here because you're assigned on #13885, and these have essentially the same cause/potential fix. Feel free to undo if you disagree of course!

**Comment by staskus** [comment]
It will be addressed in https://github.com/woocommerce/woocommerce-ios/issues/14168
