### ISSUE TITLE
Concurrency issue in BlazeLocalNotificationScheduler

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#14011]
**Describe the bug**
When enabling Core Data concurrency debug, I encountered an error in `DefaultBlazeLocalNotificationScheduler.scheduleNoCampaignReminder`.

**Screenshots**
<img width="950" alt="image" src="https://github.com/user-attachments/assets/57e65f23-fc3f-4b6e-ae4b-5d433bbb2d08">

**Expected behavior**
There should be no concurrency issue with `DefaultBlazeLocalNotificationScheduler`.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
