### ISSUE TITLE
Update rounded corner and background design in Support Form and Custom Fields Editor.

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#14028]
Since there are rounded corners on the overlay, the background view should have rounded corners as well. If you look closely, the background view is currently showing underneath which doesn't look nice.

<img width="134" alt="image" src="https://github.com/user-attachments/assets/bf99f566-b73a-45d5-8451-fd7432f3a9ce">

Same comment for the other fields.

_Originally posted by @itsmeichigo in https://github.com/woocommerce/woocommerce-ios/pull/13925#discussion_r1772993944_

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by hafizrahman** [comment]
Issue in `SupportForm`:
<img width="438" alt="Screenshot 2024-09-24 at 18 55 18" src="https://github.com/user-attachments/assets/38616410-8add-4381-a5de-5abc70a55e1d">
