### ISSUE TITLE
Orders: Reveal animation is glitchy 

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#14025]
# Description

- Open the app and navigate to the orders tab
- Pull to refresh
- See the first order row glitch due to the reveal animation

![IMG_1453](https://github.com/user-attachments/assets/63255fb7-d742-4e80-a4a5-95c9db9b720a)

Question: Should we consider removing the swipe to reveal animation?

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by atorresveiga** [comment]
> Should we consider removing the swipe to reveal animation?

@Ecarrion, we removed that animation on Android a long time ago

**Comment by rachelmcr** [comment]
Also reported here: https://github.com/woocommerce/woocommerce-ios/issues/12151

**Comment by Ecarrion** [comment]
> we removed that animation on Android a long time ago

Then, I think we should delete it. Do you agree @toupper?

**Comment by toupper** [comment]
> Then, I think we should delete it. Do you agree @toupper?

I agree indeed. We can do it with this issue
