### ISSUE TITLE
[Shipping labels] View order details bottom sheet

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#14044]
Part of #13550.

Notes:
* Addresses will not be editable for now. Those designs will be in M2.
* The options at the bottom should be fixed, and the rest should be scrollable.
* See internal discussion about the side-stacked bottom options in landscape: pe5pgL-5rm-p2#comment-4574

Collapsed|Expanded|Landscape
-|-|-
![ShippingLabels-BottomSheet](https://github.com/user-attachments/assets/beaabf40-14d9-419d-9b85-61d68c2ca033)|![ShippingLabels-BottomSheet-Expanded](https://github.com/user-attachments/assets/fad0f7ba-787d-4938-85c0-6e7be7ca73e3)|![ShippingLabels-BottomSheet-Landscape](https://github.com/user-attachments/assets/0861c1ad-eecf-4710-9ad8-9835638fed2c)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
We're removing the label paper size dropdown from this screen, per the discussion in pe5pgL-5rm-p2#comment-4584.
