### ISSUE TITLE
My Store: Top performers card missing divider line above "View all store analytics"

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#14042]
The top performers card is shown without a divider line above "View all store analytics" button. Compare this to the "Performance" card above it that does have the line. Other cards also have this line.

![2024-09-25 17 59 50](https://github.com/user-attachments/assets/c257c2ec-85c8-4c01-805b-174caf3f9e26)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
