### ISSUE TITLE
Update Core Data Stack following WP/JP

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#14054]
- Make the background context independent of the view context.
- Add new helper methods for enforcing writing in background context.
- Mark old access to writerDerivedStorage and saveDerivedStorage as deprecated.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
