### ISSUE TITLE
[Woo POS] Update colors for the payment success screen

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-ios#14063]
[TfaZ4LUkEwEGrxfnEFzvJj-fi-5193_40913](https://href.li/?https://www.figma.com/file/TfaZ4LUkEwEGrxfnEFzvJj/?node-id=5193-40913)

Also:

* Change the color of the "reader connected" green circle too
* Change text on the POS entry point to Accept payments at your physical store

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
