### ISSUE TITLE
Edge cases

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#14066]
This issue collects the various edge cases that needs to be handled in various places related to Custom Fields. The list is based on the technical documentation in pe5sF9-33t-p2

### List screen
- [x] Save button needs to be enabled only if new changes (edits, addition, deletion) are detected.
- [x] Show "discard changes" dialog if new changes are detected and merchants tap "Back" button. #14230 
- [x] Saving banner: expand content by default on Portrait mode, hide in Landscape https://github.com/woocommerce/woocommerce-ios/pull/14249

### Custom field deletion
- [x] After a custom field is deleted (from the option in Editor screen), the List screen should show "Undo" notice to cancel it. https://github.com/woocommerce/woocommerce-ios/pull/14177

### Editor screen
- [x] API doesn't allow adding a new field with existing key. When creating a new custom field, check local storage for all existing keys. If duplicates are found, show alert that field with the same key can't be added in the app, but can be done in wp-admin. No checking is needed for editing existing key. https://github.com/woocommerce/woocommerce-ios/pull/14235

### Product details
- [x] If product already has custom fields, Custom Fields row should be shown directly. If not, the option should be listed in the details bottom sheet instead (Android ref: https://github.com/woocommerce/woocommerce-android/pull/12682)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
