### ISSUE TITLE
[Mobile Payments] Try out Tap to Pay doesn't work from the About TTP screen

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#14078]
## Description
When attempting to set up/try out tap to pay from the `About Tap to Pay` screen, the try out step doesn't work. 

It just spins for a moment then stops. This button is only supposed to show until you have at least one TTP payment on that site/device.

This is a secondary access point for trying out the TTP functionality, and may be superseded by planned work for improving the flows.

## Repro
1. Delete the app from your phone to clear the saved TTP transaction state
2. Log in to a TTP-eligible site
3. Navigate to Menu > Payments > About Tap to Pay on iPhone
4. Tap `Set up Tap to Pay on iPhone`
5. Go through the set up process
6. Tap `Try a Payment`
7. Observe that the spinner shows for a moment and nothing else happens.

## Screenshots

https://github.com/user-attachments/assets/ea421e89-57a5-4999-9d7c-40d0f2b60505

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by malinajirka** [comment]
@staskus This look like a screen we are going to update - considering this is a broken flow, we should fix it. At the same time, if we plan to remove this entry point in the near future, it might not make sense. Wdyt is the best next step here?

**Comment by staskus** [comment]
@malinajirka we will have to keep this entry point due to Apple requirements. We need to have an entry point from About (Education) views. I will add this bug to the project backlog.
