### ISSUE TITLE
[Barcode] Wrong product scanned

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#14076]
# Context

Found a strange issue while scanning a barcode, the site I used to create barcodes had some ads/demo barcodes, I scanned them by mistake and the app created an order with an item that does not have an SKU set.

Demo Barcode | Product with No SKU
---- | ----
<img width="644" alt="Screenshot 2024-09-27 at 4 45 38 PM" src="https://github.com/user-attachments/assets/b5858363-fd14-4e84-b88d-9a563ba977e6"> | ![IMG_1488](https://github.com/user-attachments/assets/d1bcd6b9-c327-41d0-ad98-ae5663ae8afb)

# Steps

- Go to the orders list
- Tap the scan barcode button at the top leading margins
- Scan the demo barcode image
- See that the incorrect product is being added

# Environment

**Build:** Testflight 20.5.0.1
**Device:** iPhone 15 Pro

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
