### ISSUE TITLE
Platform parity: Disallow for discounts bigger than the price of the product

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#14080]
Ref: pdfdoF-5pQ-p2#comment-6507

When adding a product discount via the `+ Add discount` button, in iOS we allow for negative amounts via discounts bigger than the product price, while Android disallows this and presents a `Discount cannot be greater than the price inline error message` :

<img width="356" alt="Screenshot 2024-10-01 at 09 11 09" src="https://github.com/user-attachments/assets/853da313-f464-47d1-a91f-0170e2b5cc36">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
