### ISSUE TITLE
Order details: Update how applied coupons are displayed

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#14097]
Ref: pe5pgL-5G4-p2#comment-4599
Related: https://github.com/woocommerce/woocommerce-ios/issues/13861
Android: https://github.com/woocommerce/woocommerce-android/pull/12737

Now:
<img width="484" alt="Screenshot 2024-10-03 at 11 22 43" src="https://github.com/user-attachments/assets/d2c7e00a-a28b-482e-8656-f221b3f8ea1e">

Intended:
<img width="446" alt="Screenshot 2024-10-03 at 11 22 57" src="https://github.com/user-attachments/assets/1f6a88e0-46a6-49f2-b10a-66e5a806d644">

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
