### ISSUE TITLE
Optimize storage usage for product-related stores

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#14091]
- Move write operations to the background.
- Replace the deprecated access to `writerDerivedStorage` with the new method `performAndSave`.
- Look out for fetch requests in for loops and replace them with a single fetch request for list or get the items from relationships with parent objects.

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-ios/pull/14139
- [ ] https://github.com/woocommerce/woocommerce-ios/pull/14145
- [ ] #14151
- [ ] #14511
- [ ] #14520
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by itsmeichigo** [comment]
Closing since all tasks are done.
