### ISSUE TITLE
Cannot upload product image

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#14105]
**Describe the bug**

Uploading images for products does not work. It ends with an error:

```
<> Mapping Error: keyNotFound(CodingKeys(stringValue: "ID", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "media", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"ID\", intValue: nil) (\"ID\").", underlyingError: nil))
```

Happens on both the device and the simulator. Tested on 2a8925b85521bc6d429e87d98f2882ebf6d160fd. 

**To Reproduce**
1. Create a new product. 
2. Upload an image.

**Screenshots**

https://github.com/user-attachments/assets/5df4d775-f0fa-448e-acee-2da34cf53a26

**Expected behavior**

Image upload should be successful. :) 

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 15 Pro Simulator
- iOS version: 17.0
- WooCommerce iOS version: 2a8925b85521bc6d429e87d98f2882ebf6d160fd

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by selanthiraiyan** [comment]
Internal - peaMlT-Wu-p2

**Comment by JorgeMucientes** [comment]
@selanthiraiyan @itsmeichigo going to close this. After reading the Slack convo: p1728139321219389-slack-C6H8C3G23 it seems this was failing due to a plugin active to disable XML RPC on the site. There's further discussion about a possible endpoint migration for uploading media, but that should tackled in a different GH issue. 
If there's anything a missed feel free to reopen
