### ISSUE TITLE
Orders are not loaded

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-ios#14106]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
We got a few tickets reporting that order are not loading since last update

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by selanthiraiyan** [comment]
Internal - peaMlT-Wz-p2
