### ISSUE TITLE
Product AI creation fails frequently

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-ios#14115]
Product AI creation fails frequently, and the cause is that OpenAI is returning the JSON code wrapped in a Markdown code block:
"```json ....  ```"

This is actually an expected behavior of the API, and was happening for quite some time, but now it seems to be happening more frequently, see: https://community.openai.com/t/why-do-some-responses-message-content-start-with-json/573289

###### Copied from https://github.com/woocommerce/woocommerce-android/issues/12768

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
