### ISSUE TITLE
Order List: 9+ overlaps on landscape mode on iPhone 11 pro

### ISSUE THREAD

**Issue by suyogyashukla** [woocommerce/woocommerce-ios#1411]
**Describe the bug**

On iPhone 11 pro, the "9+" badge overlaps the word "Orders" when in the landscape mode.

**To Reproduce**

- Make sure you have more than 9 orders with status "Processing"
- Switch to landscape mode.

**Screenshots**

![IMG_0831](https://user-images.githubusercontent.com/8658164/67939440-74e9fa00-fbc9-11e9-96b6-feb774fc3e6d.png)

**Mobile Environment**
Please include:
- Device: iPhone 11 pro
- iOS version: 13.2
- WooCommerce iOS version: WooCommerce beta (2.9.0.1)

**Comment by mindgraffiti** [comment]
This was fixed in build 3.3.
