### ISSUE TITLE
Fix warnings regarding transformable attributes in Xcode 16

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#14129]
Internal discussion: p1727806784260639-slack-CGPNUU63E

We can update the custom type of transformable attributes to NSArray instead of Swift array. This would mitigate the warnings regarding Objective-C types that Core Data has to handle.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
