### ISSUE TITLE
[Watch app] opening order shows yellow warning icon

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#14127]
**Describe the bug**

When opening an order in the watchOS app the order details are shown for a split second, after that the yellow warning icon is shown.

**To Reproduce**
1. Open Woo watchOS app
2. Scroll to order list
3. Tap on any of the orders in the list
4. See the warning icon

**Screenshots**

https://github.com/user-attachments/assets/d389127e-ff2f-4549-a241-debf62440145

**Expected behavior**

Order details should show (without that warning icon).

**Mobile Environment**
Please include:
- Device: Apple Watch Series 10
- watchOS version: watchOS 11.0.1 (22R361)
- WooCommerce iOS version: 20.6 (tested also with 20.5)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
