### ISSUE TITLE
Optimize storage usage in remaining stores

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#14122]
Since we marked `writerDerivedStorage` and `saveIfNeeded` as deprecated in `StorageManagerType`, we should remove references to these in the stores and use the new `performAndSave` method instead. The new method ensures that all write operations are handled in a single operation queue (first come first serve).

Extra: Look out for fetch requests made in for loops and optimize those by fetching a list of items or getting items from the relationships with the already fetched object.

- [x] #14530 
- [x] #14532 
- [x] #14548 
- [x] #14552 
- [x] #14559 
- [x] #14560 
- [x] #14566 
- [x] #14567 
- [x] #14568 
- [x] #14569 
- [x] #14570 
- [x] #14572 
- [x] #14574 
- [x] #14575 
- [x] #14576
- [x] #14577

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
