### ISSUE TITLE
[Shipping labels] Show shipping rate selection UI and purchase button after package is added

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#14143]
After adding a package, we reveal the shipping service section and the disabled purchase button (previously hidden to reduce distractions and save space). We should also scroll to the selected package at this point.

New behavior after a package is selected:

- [x] Shipping service section is displayed.
- [x] Purchase button is displayed (disabled) when bottom sheet is collapsed.

New behavior after a shipping rate is selected:

- [x] Purchase button is enabled.
- [x] Purchase button includes total label cost.
- [x] Bottom sheet shows rate details (separate lines for base rate + any signature options selected).

![Image](https://github.com/user-attachments/assets/7c5cbe18-43d8-4621-8ed9-9a0149fefa73)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
