### ISSUE TITLE
[Woo POS - payments onboarding] Show payments onboarding from existing design

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#14148]
- When payments onboarding is required when connecting to a reader, show onboarding with the existing design in `CardPresentPaymentsOnboardingView`/`CardPresentPaymentsOnboardingViewModel`
- When payments onboarding is required, ensure it navigates back to the reader connection upon completion within POS
- Test onboarding completion from various onboarding states

Potential related issue:
https://github.com/woocommerce/woocommerce-ios/issues/12924

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by jaclync** [comment]
Closed by https://github.com/woocommerce/woocommerce-ios/pull/14185.
