### ISSUE TITLE
[Shipping labels] Add tab UI for switching between shipping carriers

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#14141]
We need to add the UI to switch between shipping carriers when selecting a shipping rate, e.g. switching between USPS and DHL Express:

![Image](https://github.com/user-attachments/assets/dc3fd6de-9a3a-47e0-8f77-d99533ad8d75)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
