### ISSUE TITLE
Product List: update sorting

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1415]
Right now it's sorted by [last modified date](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/ViewRelated/Products/ProductsViewController.swift#L238), and from our Product meeting we are updating the order to be the same as in core:

1. publish date
2. last modified date

**Comment by pmusolino** [comment]
:wave:  Jaclyn! 

I noticed while testing product list that now products are sorted by last modified date, but the last modified is at the end of the list. So if I edit a product, and I go back, I expect to find it on top of the list.
So if we sort by publish date, we risk losing the product that we edited. Right?
Maybe the good order can be sorted by the last modified date (descending), where if the parameter is not available we can use the publish date. Sounds good to you?

**Comment by jaclync** [comment]
Thanks for testing and confirming!

> So if I edit a product, and I go back, I expect to find it on top of the list.

I agree with you, I'm also used to seeing the last edited items at the top of the list. On the other hand, the users are most likely used to the default order on wp-admin, which I believe is by the publish date.

In the future, we can consider adding more sorting options including the last modified date after we get more feedback from the users. For this release, let's make the order consistent with the web!

**Comment by pmusolino** [comment]
After some discussions, we decided to go for the same order used by Android, where they sort products by Title.
