### ISSUE TITLE
[TTPReq] TTP Awareness moment modal

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#14158]
Designs: pdfdoF-5KF-p2
Flows: pdfdoF-5GF-p2

## Description

1. Display an awareness modal once when an eligible user opens the app. Avoid showing it immediately after logging in to prevent overwhelming the user with too much new information. Instead, wait until the next app launch. Eligibility for this modal should be determined similarly to how the TTP badge visibility is managed on tabs and in the Payments menu.
2. Put the functionality under the feature flag
3. Enable Now button should close this modal and open Set up Tap to Pay flow.
4. Learn More button should close this modal and open About Tap to Pay flow.
5. Before JITM was used on the first launch, update the existing JITM to put the cap on the app version.

## Designs

Find the latest designs pdfdoF-5KF-p2 

![Image](https://github.com/user-attachments/assets/a4c1367e-252b-49c5-bad7-b26439a7d7e8)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
