### ISSUE TITLE
[TTPReq] Send receipts after succeeded or failed payments

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#14163]
PT: p7bje6-6ob-p2
Test scenarios: p91TBi-csN-p2
API task: https://github.com/woocommerce/woocommerce-ios/issues/14326
Designs & Copy: pdfdoF-5KF-p2
Flows: pdfdoF-5GF-p2

## Description

Allow customer receipts to be sent after successful and failed payments.

1. Integrate new Woo 9.5 changes to send receipts after failed payment
2. Integrate 'Send Receipt' option within existing APIs
3. Try integrating existing UI to select customers / add new customer details
4. Call a new API https://github.com/woocommerce/woocommerce-ios/issues/14326 to send receipt to updated customer details
5. https://github.com/woocommerce/woocommerce-ios/issues/6358
Do not send a receipt to the same user twice. Test if receipts are always sent after successful or failed payments when the customer is attached. If that's the case, consider showing `Send Receipt` option only when there's no customer attached (See https://github.com/woocommerce/woocommerce-ios/issues/6358 and Android implementation).

## Design

| Image 1 | Image 2 |
| ------- | ------- |
| ![Image 1](https://github.com/user-attachments/assets/26dd3241-4748-4de5-b2b5-4f11ddc20f3a) | ![Image 2](https://github.com/user-attachments/assets/95f77c88-2cad-477b-be5b-ce23f0a95883) |

#### Email sent message

<img src="https://github.com/user-attachments/assets/d5c4f3d0-de89-4ce7-ba25-de44e98b7c30" alt="Image" width="250"/>

## User Flow

![Image](https://github.com/user-attachments/assets/f1809292-bb9e-469a-8c1d-11c4582ef011)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
