### ISSUE TITLE
[TTPReq] Location pre-alert screen

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#14168]
Designs: pdfdoF-5KF-p2
Flows: pdfdoF-5GF-p2
Related issue: https://github.com/woocommerce/woocommerce-ios/issues/13857 & https://github.com/woocommerce/woocommerce-ios/issues/13885

## Description

If location services are required for your app to accept payment, provide communication to the user during
onboarding on why location services are necessary with a [pre-alert screen](https://developer.apple.com/design/human-interface-guidelines/privacy#Pre-alert-screens).

At the moment, we show a location-permission view without a pre-alert screen.

<img src="https://github.com/user-attachments/assets/7befeca6-2e1e-4479-8b65-8f02c6cad8f1" width="200">

## Solution

Show a location-pre alert every time we make a connection and the location is not permitted. (pdfdoF-5GF-p2#comment-6801)

## Designs
<img src="https://github.com/user-attachments/assets/a78935c3-aa6a-4fdc-a3d9-42567f57b2f8" width="300" alt="Image">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
Take issues such as these https://github.com/woocommerce/woocommerce-ios/issues/13987 in the consideration as well
