### ISSUE TITLE
[TTPCA] Update StripeTerminalSDK to at least 3.6.0 to support Interac

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#14167]
Discussion: pdfdoF-5fq-p2#comment-6644

## Description

> To support Interac in Canada, the minimum required SDK version is 3.6.0.

https://docs.stripe.com/terminal/payments/setup-reader/tap-to-pay?platform=ios#get-started

We currently support 3.3.1

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
# 3.9.0 2024-09-03

Adds support for [Interac refunds](https://docs.stripe.com/terminal/payments/regional?integration-country=CA#refund-an-interac-payment) on the Tap to Pay simulated reader.

**Comment by joshheald** [comment]
This issue has been moved to Linear: https://linear.app/a8c/issue/WOOMOB-3678/ttpca-update-stripeterminalsdk-to-at-least-360-to-support-interac
