### ISSUE TITLE
[Woo POS - payments onboarding] Support actions like Contact Support and showing URL

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#14176]
In some of the payments onboarding modals, the Contact Support & Learn more actions are no-op in POS (example below). These actions are supported for the onboarding flow in other parts of the app like in Menu tab > Payments > Continue setup, and order creation > IPP.

![Image](https://github.com/user-attachments/assets/1d1e8854-877a-4f3d-89b5-6fe186cc78b0)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
