### ISSUE TITLE
[TTPReq] Fallback payment method and 'Offline PIN' handling

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#14171]
Designs: pdfdoF-5KF-p2
Flows: pdfdoF-5GF-p2

## Description

To meet fallback payment requirements, we can extend the payment failure modal to include an option for selecting another payment method. This would close the failure modal and show the checkout view. [Human Interface Guidelines](https://href.li/?https://developer.apple.com/design/human-interface-guidelines/tap-to-pay-on-iphone#Displaying-results) allow reusing the checkout screen for displaying fallback payment options.

## Solution

1. After TTP payment fails with `offline_pin_required` error, add an additional button to `Try Another Payment Method`
2. For `offline_pin` errors, make sure the error message indicates the reason for the failure

## More Details

To properly support fallback payment methods in all markets (especially UK) we need to fulfill these requirements:

1. All merchants must be set up with at least one (1) accepted alternative payment method so that all
transactions can be completed in person
2. Ensure the app provides a seamless transition between the Tap to Pay on iPhone UI and the accepted
alternative payment method provided for the merchant. 

## Design and User Flows

| Existing Modal | Flow |
| --- | --- |
| ![Image 1](https://github.com/user-attachments/assets/4b3dd086-1577-4bc4-9030-55fe7ee5075a) | ![Image 2](https://github.com/user-attachments/assets/c349a18e-341d-4eba-90ac-e0d0d2a42766) |

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
