### ISSUE TITLE
[TTP] Update messaging and documentation for lowest supported iOS version

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#14190]
Tap to Pay on iPhone requires an iPhone XS or later running:
- iOS 16.7 or later in the United States, Australia, and the United Kingdom. 

## Tasks

1. Update messaging within the app
2. Update [the documentation](https://woocommerce.com/document/woopayments/in-person-payments/tap-to-pay-iphone/)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
