### ISSUE TITLE
Add/Edit Products: main screen - add tappable Product description table view cell

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1420]
- Create a table view cell for the Product description
  - non-empty text: @kyleaparker what would the font / text color be in this case?
  - placeholder state below

empty text / placeholder | existing text
-- | --
<img width="221" alt="Screen Shot 2019-11-04 at 2 55 32 PM" src="https://user-images.githubusercontent.com/1945542/68103836-5a8a8600-ff13-11e9-863f-5d99381a7200.png"> | <img width="221" alt="Screen Shot 2019-11-13 at 9 23 52 AM" src="https://user-images.githubusercontent.com/1945542/68724764-5dfacd00-05f7-11ea-843d-6895ab91cc68.png">

- Extract the text content of the first HTML element from the Product description: we could use the helper in `String+HTML.swift` (it's time consuming, might be worth calling it in the background), or the [WPiOS version](https://github.com/wordpress-mobile/WordPress-iOS-Shared/blob/bdfa2075e1331db720907e794cbc375e1db4dc46/WordPressShared/Core/Utility/NSString%2BHelpers.m#L243) (make sure to test on different Products/sites)

**Comment by kyleaparker** [comment]
>non-empty text: @kyleaparker what would the font / text color be in this case?

it should use the iOS default placeholder text colour
