### ISSUE TITLE
[iPadOS18] Popovers are no longer presented from the source view (Add Product / Coupons details)

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#14204]
Popover modals are no longer presented from the source view on iPadOS18 built with Xcode 16. 

Related context: p91TBi-c9Y-p2

## Steps to reproduce

1. Build Woo app on iPad with iOS 18 with Xcode 16
2. Open Products tab
3. Tap "+" to add a product
4. Notice the modal appears at the center of the screen instead of from the "+" icon

## Investigation

The functionality is driven by `BottomSheetViewController` 

```
public func show(from presenting: UIViewController,
                     sourceView: UIView? = nil,
                     sourceBarButtonItem: UIBarButtonItem? = nil,
                     arrowDirections: UIPopoverArrowDirection = .any)
```

Although `popoverPresentationController?.barButtonItem = sourceBarButtonItem` is correctly set, it no longer works on iPadOS18.

### After (iPadOS18 + Xcode 16)

https://github.com/user-attachments/assets/c901e170-c8e7-4de4-83cc-99188b7b4e28

### Before

https://github.com/user-attachments/assets/87bdc78c-2396-4ee6-8ae0-509c0af8f8bc

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by staskus** [comment]
Caused by a workaround https://github.com/woocommerce/woocommerce-ios/pull/14136. Closing as won't-do, at least for now.
