### ISSUE TITLE
[Woo POS] Separation between initial page fetch vs subsequent page fetch vs pull-to-refresh

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#14203]
At the moment we call populatePointOfSaleItems() both when the view first appears, as well as in subsequent fetches for pagination, so right now fetching the 1st page correctly is a bit of a side-effect of the internal function count and relies that we start on 0. 

Ideally we should pass the page into the function as a parameter and keep it stateless.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
