### ISSUE TITLE
[Woo POS - payments onboarding] Use `posModal` instead of `sheet` for onboarding modal

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#14209]
More context and info from Josh on how to make the onboarding view compatible with `posModal`: https://github.com/woocommerce/woocommerce-ios/pull/14185#issuecomment-2434784549

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
