### ISSUE TITLE
Google Ads: Decoding campaigns fails if `country` is nil

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#14212]
**Describe the bug**
Looks like `country` is optional for `GoogleAdsCampaign`. User in ticket 8933727-zen reported that they could not load the Google Ads card and the app logs show that parsing fails due to `country` being nil.

**Expected behavior**
Make `country` optional to fix this issue.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by hafizrahman** [comment]
In Android the value is already optional so it should be OK there:

https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/5dfbbc993d2472f6aad2b9f357021506ecfe7152/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/google/WCGoogleAdsCampaign.kt#L11
