### ISSUE TITLE
Add/Edit Products: edit shipping settings

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1422]
Subtasks (feel free to create separate issues):

<img width="246" alt="Screen Shot 2019-11-04 at 4 03 25 PM" src="https://user-images.githubusercontent.com/1945542/68106460-af7eca00-ff1c-11e9-9b70-2aa20c45014f.png">

## Weight/dimension unit
- #1507 

## Product shipping class
- [x] Storage layer: create `ProductShippingClass` entity that corresponds to the API doc: https://woocommerce.github.io/woocommerce-rest-api-docs/#product-shipping-classes https://github.com/woocommerce/woocommerce-ios/pull/1538
- [x] Networking layer: retrieve all Product shipping classes: https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-shipping-classes https://github.com/woocommerce/woocommerce-ios/pull/1539
- [x] Yosemite layer: add `ProductAction` to retrieve all Product shipping classes https://github.com/woocommerce/woocommerce-ios/pull/1539

## Edit shipping settings screen
- [ ] Create a blank view controller with "Shipping" navbar title
- [ ] Create a table view cell for editing a shipping setting inline (dimension/weight)
- [ ] Validate value for each shipping setting
- [ ] Fetch the `Product`'s shipping class, if `product.shippingClass` and `product.shippingclassID` are non-nil

## Update Product shipping settings
- [ ] `ProductUpdater`: update Product's `dimensions` and `shippingClass` slug
- [ ] Update tests to include the shipping settings

## Shipping class picker
- [x] generic list picker UI https://github.com/woocommerce/woocommerce-ios/issues/1526
- [x] Retrieve all available shipping classes via Yosemite
- [ ] Preselect the current shipping class by `Product`'s `shippingClassID`

@kyleaparker is the design for picking a shipping class the same as in the stock status:
<img width="250" alt="Screen Shot 2019-11-04 at 3 58 21 PM" src="https://user-images.githubusercontent.com/1945542/68106268-0506a700-ff1c-11e9-97a3-09ca8f6518e1.png">

**Comment by kyleaparker** [comment]
>@kyleaparker is the design for picking a shipping class the same as in the stock status:

Yes it will be the same 👍
