### ISSUE TITLE
Add/Edit Products: edit price settings

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1423]
<img width="247" alt="Screen Shot 2019-11-04 at 5 27 28 PM" src="https://user-images.githubusercontent.com/1945542/68111427-0fc83880-ff2a-11e9-96a7-aa6d1f51c90b.png">

## Edit price settings screen
- [x] Create a blank view controller with "Price" navbar title, and a table view with grouped style and a data source with 3 sections: price, schedule sale, and tax
- [x] Create a table view cell for editing a price field with the site currency setting (DI'ed via `CurrencySettings`
  - Validate and format value for the price with basic logic
- [x] Create a reusable table view cell for a key-value pair (like `ProductSettingValueCell`) that looks like:
<img width="242" alt="Screen Shot 2019-11-04 at 5 38 44 PM" src="https://user-images.githubusercontent.com/1945542/68111410-076ffd80-ff2a-11e9-8daa-4729d1451fa4.png">

## Update Product price settings
- [x] Yosemite/Networking layer: we could save each field separately, or all together in view controller's `viewWillDisappear`

API field | type | notes
-- | -- | --
regular_price | string | Product regular price.
sale_price | string | Product sale price.
date_on_sale_from | date-time | Start date of sale price, in the site's timezone.
date_on_sale_from_gmt | date-time | Start date of sale price, as GMT.
date_on_sale_to | date-time | End date of sale price, in the site's timezone.
date_on_sale_to_gmt | date-time | End date of sale price, as GMT.
tax_status | string | Tax status. Options: taxable, shipping and none. Default is taxable.
tax_class | string | Tax class.

## Schedule sale
- [x] Show the toggle to turn on/off the sale schedule using `SwitchTableViewCell`
- [x] Create a table view cell that shows a title and a date text field with `UIDatePicker` as its input view
- [x] Show the editable from and to dates on the edit screen, and save the dates via `ProductStore` on change

<img width="241" alt="Screen Shot 2019-11-04 at 5 44 16 PM" src="https://user-images.githubusercontent.com/1945542/68111710-c0363c80-ff2a-11e9-8964-5d8623fc7396.png">

## Tax Classes
- [x] Storage layer: create `TaxClass` entity based on the API doc: https://woocommerce.github.io/woocommerce-rest-api-docs/#tax-classes
  - Belongs to a `Product` entity
- [x] Networking layer: retrieve all tax classes: https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-tax-classes
- [x] Yosemite layer: add a `ProductAction` to retrieve all tax classes
- [x] Add a table view cell entry to show the existing tax class

## Tax class picker
- [x] Create a new view controller that shows a list of tax classes via Yosemite
- [x] Preselect the current tax class

## Tax status
- [x] Create an enum with these options: taxable, shipping and none. Default is taxable
- [x] Add a table view cell entry to show the existing tax status

## Tax status picker
- [x] Create a new view controller that shows a list of tax status options
- [x] Preselect the current tax status

<img width="247" alt="Screen Shot 2019-11-04 at 5 27 13 PM" src="https://user-images.githubusercontent.com/1945542/68110682-66cd0e00-ff28-11e9-8e7b-ebf3a828b3d6.png">

**Comment by pmusolino** [comment]
The date picker has the same UI of "Add Tracking"?
<img width="385" alt="Schermata 2019-11-28 alle 17 10 24" src="https://user-images.githubusercontent.com/495617/69820716-0d43c080-1202-11ea-839b-d40bd527cd91.png">

**Comment by pmusolino** [comment]
@jaclync I noticed that some fields like `date_on_sale_from_gmt` are included only in the `ProductVariation` model and that other fields like `date_on_sale_from` don't exist.
In my opinion, it's ok to have only one field, since it makes sense for me to show to the user the date picker in local time, and we do under the hood the conversion in GMT. 

What does not come back to me: will this screen serve in some way also to manage the price of the variants?
I guess not, and I think I need to add the missing fields to the product model.

**Comment by jaclync** [comment]
sorry for the late response!

> The date picker has the same UI of "Add Tracking"?

I think showing the date picker as the text field/view's `inputView` would be easier to implement and consistent with other apps

**Comment by jaclync** [comment]
> I noticed that some fields like date_on_sale_from_gmt are included only in the ProductVariation model and that other fields like date_on_sale_from don't exist.
In my opinion, it's ok to have only one field, since it makes sense for me to show to the user the date picker in local time, and we do under the hood the conversion in GMT.
> What does not come back to me: will this screen serve in some way also to manage the price of the variants?
> I guess not, and I think I need to add the missing fields to the product model.

yes, we'd have to add the `date_on_sale_from/to_gmt` fields to `Product` similar to `ProductVariation` (issue here https://github.com/woocommerce/woocommerce-ios/issues/1505)

also, we'd show the same Edit Price Settings UI for a variation (`ProductVariation`) when we get to implement Variable Products (in a later milestone). I think we could create a protocol like `PriceEditable` that both `Product` and `ProductVariation` implement with the properties that can be edited on this screen. what do you think?
