### ISSUE TITLE
[Product] Use `wp/v2` endpoint for uploading images

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#14232]
### Problem

We currently use `rest/v1.1/sites/\(siteID)/media/new` endpoint to upload images. This doesn't work when XMLRPC is disabled on the site.

### Proposed solution

Start using `wp/v2/sites/\(siteID)/media` endpoint to upload images. This endpoint works even when XMLRPC is disabled. 

Internal -  p1728974476767139/1728139321.219389-slack-C6H8C3G23
Internal - p91TBi-6OX-p2

Android - https://github.com/woocommerce/woocommerce-android/issues/12836

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
