### ISSUE TITLE
Add/Edit Products: edit inventory settings

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1424]
Manage stock at product level off | Manage stock at product level on 
-- | --
<img width="248" alt="Screen Shot 2019-11-04 at 5 53 11 PM" src="https://user-images.githubusercontent.com/1945542/68112355-16f04600-ff2c-11e9-874e-38e1e57f89e3.png"> | <img width="250" alt="Screen Shot 2019-11-04 at 6 22 53 PM" src="https://user-images.githubusercontent.com/1945542/68114288-98e26e00-ff30-11e9-90f3-470a558ed478.png">

Note: I think the last quantity field in "Manage stock at product level on" can be ignored

## API

Added the following fields to the Product encoding: https://github.com/woocommerce/woocommerce-ios/pull/1654
- [x] SKU
- [x] Manage stock at product level
- [x] Limit one per order

### Manage stock at product level off
- [x] Stock status

API field | type | notes
-- | -- | --
stock_status | string | Controls the stock status of the product. Options: instock, outofstock, onbackorder. Default is instock.

### Manage stock at product level on

- [x] Stock quantity
- [x] Backorders setting

API field | type | notes
-- | -- | --
stock_quantity | integer | Stock quantity.
backorders | string | If managing stock, this controls if backorders are allowed. Options: no, notify and yes. Default is no.

### Error handling

- [x] handle error when the SKU is invalid or duplicated: deferring to https://github.com/woocommerce/woocommerce-ios/issues/1652

### Data validation
https://github.com/woocommerce/woocommerce-ios/pull/1690
- [x] Stock quantity should be an integer
- [x] Validte the SKU field locally against other existing Product SKUs

## Edit inventory settings screen
- [x] Create a blank view controller with "Inventory" navbar title, and a table view with grouped style and a data source with 3 sections: SKU, manage stock, and order limit
- [x] Create a table view cell for editing SKU field (the UI looks different from other editable fields, thus creating a separate class) https://github.com/woocommerce/woocommerce-ios/pull/1657
- [x] Show the editable SKU field
- [x] Create a table view cell for editing a field without any unit (or reuse the one from weight/dimension in shipping settings https://github.com/woocommerce/woocommerce-ios/issues/1422 without unit)
- [x] Show the "Limit one per order" setting using `SwitchTableViewCell`

## Manage stock section
- [x] Show the "Manage stock" at product level toggle using `SwitchTableViewCell`
- [x] If "Manage stock" is on, show the following fields:
  - Stock quantity: editable field without unit

## Stock status picker
- [x] Create a new view controller that shows a list of stock status options
- [x] Preselect the current stock status

<img width="248" alt="Screen Shot 2019-11-04 at 5 53 26 PM" src="https://user-images.githubusercontent.com/1945542/68112357-1788dc80-ff2c-11e9-8658-07a4722a2c95.png">

## Backorders setting picker
- [x] Create a new view controller that shows a list of backorders setting options
- [x] Preselect the current backorders setting

**Comment by mindgraffiti** [comment]
Issue marked as done. Closing.
