### ISSUE TITLE
[Shipping labels] Update order details button to open shipping label

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#14242]
In order details, if the order has shipping labels, update the text to navigate to the label view (behind the feature flag):

* Before: "View Shipment Details"
* After: "View purchased shipping label"

When the button is tapped, it should navigate to the new screen, prefilled with the label details.

![Image](https://github.com/user-attachments/assets/20187856-f9e7-4a6e-887b-43921f976440)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
