### ISSUE TITLE
[Shipping labels] Integrate post-purchase UI component into main shipping label screen

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#14241]
If a shipping label exists (after purchasing or when viewing an existing label):

* Display post-purchase UI component at the top of the main Woo Shipping label screen.
* Change the navigation title to "View Shipping Label."
* Update the dismiss button to "Close" (instead of "Cancel").

![Image](https://github.com/user-attachments/assets/f91d7023-69b4-4d18-9265-3d34436da4c6)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
