### ISSUE TITLE
[Shipping labels] Add shipping label post-purchase UI

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#14240]
Create a UI component for the shipping label post-purchase UI (no navigation for now):

![Image](https://github.com/user-attachments/assets/9d344be6-e07c-4121-a523-ac6875d06e8b)

A couple design tweaks:

* No checkmark icon next to the "ready to print" text
* Update colors to green instead of purple (see Figma designs in M3 for colors)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
