### ISSUE TITLE
[Woo POS] Pagination UI improvement: Update animation on pull-to-refresh

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#14251]
From review on https://github.com/woocommerce/woocommerce-ios/pull/14226#pullrequestreview-2401010336

> during pull-to-refresh, the product list view along with its scroll indicator seems to move around

https://github.com/user-attachments/assets/e3354e15-2e8c-4897-a738-b079799a64f6

This most likely comes from not considering any specific animation when the state changes to `.loading`,  as now we're just performing an easeInOut for `.isInitialLoading` on `PointOfSaleDashboardView`: 

```
.animation(.easeInOut, value: viewModel.isInitialLoading)
```

> The spinner is overlapping with the fading non-simple products notice briefly

Since the banner is temporary and seems to be going away with the new design iteration, let's keep this in the backlog for now.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
