### ISSUE TITLE
[Woo POS - payments onboarding] Analytics

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#14253]
Ref: pffQ75-Z9-p2#metrics

When tapping on the POS entry point in the Menu tab (hub_menu_option_tapped Tracks event or a new event when we have a more formal analytics plan), we can add a new event property like woo_payments_onboarding to track the onboarding state.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
