### ISSUE TITLE
Not using `k` for less strong currencies?

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/woocommerce-ios#1425]
**Is your feature request related to a problem? Please describe.**

To get more familiar with WooCommerce in all its aspects, I'm helping a friend with her WooCommerce store. When getting in a recent order, I noticed that the order said `R1,0k` rather than the actual amount of `R1,049`. 

While I understand this makes a lot of sense for a strong currency like the USD or EUR, it feels very odd seeing this is ZAR (about 1/15th of the USD). 

Asking some South African designers what their gut feeling is on this. @garymurray @garethallison 

![Mobile screenshot](https://cld.wthms.co/mTGPVP+)
Link to image here: https://cld.wthms.co/mTGPVP.

**Describe the solution you'd like**

If Gary and Gareth have the same gut feeling, I'm wondering if we could change the `K` mention by 1 digit.

**Comment by garymurray** [comment]
I few comments/thoughts from my side:

- I tend to only use *k* when abbreviating whole numbers - i.e R1k, R2k, in the case of R1500 I would rather use R1500 vs R1,5k
- The use of *k* itself is more slang afaik or is it considered normal now?
- If we do need to shorten the actual numbers there due to spacek - could that abbreviation not start after 10,000 instead of 1,000 as a general rule

**Comment by jobthomas** [comment]
Yup, from a ZAR perspective, seeing 10k if the order was 10,049 makes more sense than the above example.

**Comment by garethallison** [comment]
> I tend to only use k when abbreviating whole numbers - i.e R1k, R2k, in the case of R1500 I would rather use R1500 vs R1,5k
Agree with this.

**Comment by mindgraffiti** [comment]
Hi @jobthomas @garymurray @garethallison  👋 

This has been a challenge from the beginning. I raised the issue in p99K0U-SE-p2 and we opened tickets (#584 and https://github.com/woocommerce/woocommerce-android/issues/671) to research this problem. 

During a team meeting, the conclusion that we came to is that there aren't any good frameworks available and abbreviating the numeric values is not going to work for localization. What we really need is to unfurl the numbers and display their full values in the correct formats. That requires a significant amount of design thinking. @kyleaparker I can't find the task on our Road Map nor on Feature Backlog in Monday.com. Is displaying the full amounts still part of the plan?

**Comment by kyleaparker** [comment]
It seems on this specific screen we should be able to show the unabbreviated amount as it is, and just wrap the text on the left if it's a long number. We can also use a slightly smaller text size for the amount. The difficulties are really on the stats screen where we have three numbers side by side, but this screen seems more straightforward.

**Comment by jobthomas** [comment]
FWIW, when I was in Vietnam 2 years ago, there it _was_ quite common to use the `k` because the currency isn't very strong.

**Comment by shiki** [comment]
Hi everyone! As of 3.6 (https://github.com/woocommerce/woocommerce-ios/pull/1789), we are no longer abbreviating these values so this should no longer be an issue. 

I'll close this ticket but please let me know if I missed anything and it should be reopened.
