### ISSUE TITLE
[Custom Fields] Allow differentiating between JSON fields and String fields that contain JSON content

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-ios#14271]
Currently, the iOS implementation differs from how Android and Core behave: both Android and Core will allow editing JSON values that are wrapped as Strings, something like:

```json
{
   "id": 1,
   "key": "key",
   "value": "{\"key\":\"value\"}"
}
```

But for iOS, and given that we don't differentiate between the different forms of MetaData values, the above will be exactly the same as if we received:

```json
{
   "id": 1,
   "key": "key",
   "value": {"key":"value"}
}
```

This means that the String fields that contain JSON are not editable on the iOS app.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
