### ISSUE TITLE
Deposits: "Pending funds" miss-aligned when using an iPad on landscape mode

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#14281]
Reported on pdfdoF-5jz-p2

> Deposits: Pending funds seems to be miss-aligned to the center when using an iPad on landscape mode. Should it be pushed to the right border, close to the chevron? The latest [design revision] only includes designs for iPhone so it’s unclear what should be the final UI

![Image](https://github.com/user-attachments/assets/2b7bc94b-cbbd-4147-96b5-8a30277b5c38)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
I would suggest we push the contents closer together in this case – it doesn't make the same sense to give them half the space when it's as wide as this.

However, we should probably also find a way to show all the information in the summary view when it's this large – there's little reason to collapse the content and have this much whitespace.

**Comment by staskus** [comment]
@iamgabrielma, @joshheald. I looked into this and I'm not sure it's worth the time investing in it.

True, in a horizontal orientation on iPad there's lots of empty space. However, even if we push both text containers closer, we will still remain with lots of empty space.

I think the reason for this is that we don't use a split view in Menu. That would be an established iPad practice. That would leave all the items on the menu always visible while keeping the content views smaller in width. Given we will eventually switch to the split views on iPad, I think issues such as these will be automatically handled. Let me know what you think.
