### ISSUE TITLE
[Woo Payments] Onboarding authentication issues when providing business information

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#14303]
## Description

In beta testing for 21.0, I found that I wasn't able to complete WooPayments onboarding in the app's webviews.

## Repro

1. Create a new Jurassic Ninja site with Woo, WooPayments, and WooPayments Dev Tools
2. Set the country for the site
3. Log in to the site with app credentials in the app
4. Go to `Menu > Payments > Continue setup`
5. Activate WooPayments
6. On the next onboarding screen, use the CTA to open the webview for WP-Admin > Payments
7. Use the webview's CTAs to link the site to your WPCom account
8. Continue with payments onboarding
9. Tap the CTAs in the webview to enter the business details
10. Observe that you're shown an error: `An error occurred while authenticating your account, please try again`
11. Observe that you reach an un-ending spinner.

I also tried logging out, and logging back in with the WPCom account, but the webview still isn't able to complete onboarding.

When I try on the web, even on Mobile Safari, tapping the button opens a modal or new tab that allows me to complete onboarding fully.

This doesn't appear to affect the previous version of the iOS app, prior to #14252 

## Screenshots
https://github.com/user-attachments/assets/d511d263-a8fd-4772-b990-3c12a4d37846

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by rachelmcr** [comment]
Closing as fixed in https://github.com/woocommerce/woocommerce-ios/pull/14310.
