### ISSUE TITLE
Tap to Pay on iPhone Unavailable even if iOS is 18.0

### ISSUE THREAD

**Issue by toupper** [woocommerce/woocommerce-ios#14301]
When trying to collect a payment via Tap to Pay on iPhone, I get an alert notifying me that the feature is unavailable and advising me to upgrade the OS. My device OS version is iOS 18.0. See screenshot:

<img src="https://github.com/user-attachments/assets/4eace120-efb8-4557-9636-d412412c9ed2" width="375">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
Tested on:
- 18.0.0 
- 18.0.1
- 18.1

and not reproduced so far.

**Comment by staskus** [comment]
No longer reproducible after iOS update. Created a follow up task of another issue found during testing: https://github.com/woocommerce/woocommerce-ios/issues/14311
