### ISSUE TITLE
[Woo POS - payments onboarding] Select payment provider state: background color does not match the POS modal

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#14318]
**Describe the bug**

The background color of the "select payment provider" view does not match the POS modal. This view is shared in other parts of the app like IPP, payments menu, and refund. We want to ensure regression testing is performed.

**To Reproduce**

Prerequisites: the store has both WooPayments and Stripe Extension installed & activated.

- Go to the Menu tab
- Tap `Point of Sale Mode`
- Tap `Connect your reader` --> after loading, a "select payment provider" modal should be shown. notice that the background color doesn't match the POS modal

**Screenshots**

light | dark
-- | --
<img src="https://github.com/user-attachments/assets/47fb40a9-b273-430e-bf1a-13e0604c2986" width="300" /> | <img src="https://github.com/user-attachments/assets/41f2b72a-c6d7-4f0b-b373-4a2bf6526780" width="300" />

**Expected behavior**

The background color of the onboarding view should match the POS modal.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: any
- WooCommerce iOS version: 21.0

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
