### ISSUE TITLE
[TTPReq] Integrate Education steps after Terms and Conditions are accepted

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#14327]
Designs & Copy: pdfdoF-5KF-p2
Flows: pdfdoF-5GF-p2

## Description

Integrate Education steps after Terms and Conditions are accepted both in:
- `Set up Tap to Pay` flow
- Payment flow

We need to provide merchant education right after the Terms and Conditions are accepted. The [Stripe SDK notifies us when the Terms and Conditions are accepted](https://href.li/?https://github.com/stripe/stripe-terminal-ios/blob/master/PublicHeaders/SCPLocalMobileReaderDelegate.h#L107C9-L107C49) and, at the same time, completes the connection to the built-in TTP reader and downloads any necessary configuration. Apple requires a progress indicator to be shown if merchants finish the education steps before the configuration is completed.

The payment flow should display the same “Set up Tap to Pay” process as when it is initiated through the Payments menu. **The key difference is at the end of the flow: after the preparation and configuration are completed, the flow should pause and not proceed until the merchant education is also completed**.

## Details

- Leverage [localMobileReaderDidAcceptTermsOfService](https://github.com/stripe/stripe-terminal-ios/blob/master/PublicHeaders/SCPLocalMobileReaderDelegate.h#L107C9-L107C49) event within `SCPLocalMobileReaderDelegate` that we currently don’t use
- Integrate within `BuiltInCardReaderConnectionController`
- Consider adding associated types to existing states to indicate the appearance of education or ,if necessary, creation of a new state.

Current flow

```
1. Set up Tap to Pay on iPhone tapped
    1. BuiltInCardReaderConnectionController.state = initializing 
    2. .state= preparingForSearch
    3. .state = beginSearch
    4. .state = searching
2. Checking Device alert is shown
    1. state = .connectToReader
    2. onConnectToReader action connect dispatch (line 403)
3. Preparing iPhone alert is shown
4. Native location alert is shown
5. Terms and Conditions alert is shown
6. Accept is tapped
    1. localMobileReaderDidAcceptTermsOfService called
    2. (optional) state = updating
    3. returnSuccess state = idle
    4. Setup complete
```

### Setup

![Image](https://github.com/user-attachments/assets/bd57a324-0db5-47c3-aa1f-e5972eb327c9)

### Payment

![Image](https://github.com/user-attachments/assets/0db4c0ba-5133-450a-ae89-fb4de0ba3497)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
