### ISSUE TITLE
Image caching improvements

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1432]
Now that we're implementing Product management, images become more visible on the Products tab and also in each Product (read-only and edit version). Right now, we can use `UIImageView+Networking` to load an image on an `UIImageView` and `WPImageSource` to download an image from a URL. However, they don't cache the images on disk so the placeholder image is shown on each cell reuse and table/collection view load.

There are popular libraries like [`SDWebImage`](https://github.com/SDWebImage/SDWebImage), but let's consider implementing a lightweight version that suits our usage first. A possible implementation could be like this, but it might have some missing features: https://medium.com/swift2go/swiftbits-caching-images-9de11d034924

**Comment by pmusolino** [comment]
On my experience [Kingfisher](https://github.com/onevcat/Kingfisher) is the best option on Swift.
Lightweight, very customizable, easily replaceable in the future (not invasive).

**Comment by pmusolino** [comment]
I noticed that `UIImageView+Networking` actually is using cache. Maybe exposing a method to fetch an image directly from the cache will be ideal. What do you think about that?

**Comment by jaclync** [comment]
> I noticed that UIImageView+Networking actually is using cache. Maybe exposing a method to fetch an image directly from the cache will be ideal. What do you think about that?

**Comment by jaclync** [comment]
> I noticed that UIImageView+Networking actually is using cache. Maybe exposing a method to fetch an image directly from the cache will be ideal. What do you think about that?

This would be ideal! It might also be great to check with WPiOS teams since it's in the shared library.

I remember the UIImageView+Networking caching was a bit different from the `SDWebImage` library I used before. For example, the images on the Products tab are using UIImageView+Networking and they seem to get downloaded (not shown immediately) on every app launch. Maybe the cache isn't persisted so it's reset on every app launch? Not sure if it's possible to persist the image cache?

**Comment by jaclync** [comment]
Also, not sure if it's easy to implement, it'd be nice to have some cache expiration and/or size limit handling so that the older images are removed from the storage after some time or when the images are taking up the storage (it's a feature in both Kingfisher and SDWebImage)

**Comment by pmusolino** [comment]
Thank you @jaclync for clarifying these aspects. I'm going to do a P2 post about that with my vision and asking feedbacks 😉
