### ISSUE TITLE
[Mobile Payments] Errors for empty Store Address/Postcode aren't shown when using site credentials

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#14333]
## Description

A user opened a ticket because they couldn't connect their card reader, they just got a generic error when they tried. There were no useful errors in the app or backend logs.

Underlying errors should have been logged, but we found that call was missing from the StripeCardReaderService `fetchDefaultLocationID` failure path. That should be fixed.

We determined that they were logged in using site credentials, and when trying to connect a reader on their site we found that there was indeed an error when calling `fetchDefaultLocationID`.

```
error	Networking.NetworkError	unacceptableStatusCode
Sorry, there was an issue with the server. Please try again later. (Error code: 500). Response: {"code":"store_address_is_incomplete","message":"https:\/\/{SITE_URL_REMOVED}\/wp-admin\/admin.php?page=wc-settings&tab=general","data":null}
```

This error is expected to be transformed to a `CardReaderConfigError.incompleteStoreAddress`, but that is gated by a check for the error type – it only works for `DotcomError`, not `NetworkError`, and because we're using site credentials, we'll always get a `NetworkError` here.

## Repro

1. Remove the Store Address or Postcode in WPAdmin settings.
2. Launch the app and log in to the site **using site credentials**, not Jetpack
3. Attempt to connect a card reader
4. Observe that you're shown a generic error

Expectation: you should see a specific error telling you to update the store address or postcode.

## Suggested remedies
1. Decode the expected error for both `NetworkError` and `DotcomError`.
2. Fix missing `UnderlyingError` logging in `StripeCardReaderService`.
3. Check for other `DotcomError` specific use and log tickets as needed.
4. Start team discussion about logging all API errors in the Network layer.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
