### ISSUE TITLE
Validate that Blaze campaign images are square

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#14339]
Clone of Android issue - https://github.com/woocommerce/woocommerce-android/issues/12879

Blaze campaign ads support square images only. We currently only check that the image meets some size requirements, but we don't enforce it to be square. 

- We can either show an error if the image is not a square
- Or automatically crop the image to square and display the cropped image in the Ad preview. If the user is ok with that, let them proceed with creating the campaign.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by JorgeMucientes** [comment]
Image cropping is handled in the backend side, so closing for now.
