### ISSUE TITLE
[Woo POS - payments onboarding] Test the onboarding flow when both WooPayments and Stripe Extension are active and choosing the Stripe Extension

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-ios#14342]

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by jaclync** [comment]
Tested as part of the test plan pdfdoF-5MC-p2, closing this issue.
