### ISSUE TITLE
Update Zendesk SDK

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#14356]
We need to update the Zendesk SDK now that we're using Xcode 16, to resolve errors uploading the IPA to App Store Connect. The current SDK includes bitcode that can't be used in a release with Xcode 16.

The [latest version of the Zendesk SDK (9.0.0)](https://developer.zendesk.com/documentation/classic-web-widget-sdks/support-sdk/ios/release_notes/#900) includes a fix for this.

Discussion: p1731064973991099-slack-CC7L49W13

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by AliSoftware** [comment]
In the meantime, we've applied a workaround in https://github.com/woocommerce/woocommerce-ios/pull/14358.

Make sure you revert that workaround PR once you update the Zendesk SDK to a newer version that includes the fix, to clean up after ourselves (as that workaround would be a no-op after the update and useless to keep around, even if harmless).

**Comment by toupper** [comment]
Done in https://github.com/woocommerce/woocommerce-ios/pull/14360
