### ISSUE TITLE
[Woo POS] Stores not in the supported country (the US) can still access POS

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#14367]
**Describe the bug**

Stores not set in the US can still see the POS entry point in the Menu tab.

**To Reproduce**
- In wp-admin WC settings, set the country to be not in the US while the currency is USD
- In the app, go the Menu --> notice that shortly, the POS row still appears
- Tap on `Connect your reader` --> an error about the country not supported is shown

**Screenshots**

https://github.com/user-attachments/assets/f55bd9fc-e200-41d0-9e11-2c1056093d62

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any iPad
- iOS version: any 
- WooCommerce iOS version: 21.1

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
