### ISSUE TITLE
[Shipping labels] Integrate requests for label rates in UI layer

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#14393]
We need to integrate the new Networking/Yosemite support for shipping labels into the UI layer.

We should request the shipping label rates:

* After a package is selected/added to the shipment.
* After the total package weight is updated (with a 1-2 second delay/debounce).

The result should be used to populate the shipping service section.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
