### ISSUE TITLE
[Woo POS] Consider re-adding property for `shouldShowClearCartButton` to aggregate model or `CartView`

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#14405]
> I'll keep it in mind and perhaps we can add it back at the end.... But for the time being I'm trying to get in the mindset of simply relying on the raw state we care about in the view as much as possible, without wrapping it up in extra functions and tests.
> 
> `posModel.cart.isNotEmpty && cartViewModel.canDeleteItemsFromCart` is already quite simple, and the `canDelete` bit is a wrapper around the current order stage (it needs to be `building`.) So I'm working towards it using those state items directly, and then we don't need to rely on combine flows to set flags, as we have here. 
> 
> That paves the way for us to try `@Observable` rather than `ObservableObject`, and has the potential to be more performant, as only changes to `orderStage` or `cart.isNotEmpty` would trigger this view being redrawn, rather than any change to `posModel` or `viewModel`, as happens with published properties on observable objects.

_Originally posted by @joshheald in https://github.com/woocommerce/woocommerce-ios/pull/14400#discussion_r1840086571_

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
