### ISSUE TITLE
[Woo POS] Define the cart item to scroll to in one place only

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#14404]
>                     .onChange(of: cartViewModel.itemToScrollToWhenCartUpdated?.id) { _ in
>                         if viewModel.orderStage == .building,
>                            let itemToScrollTo = cartViewModel.itemToScrollToWhenCartUpdated?.id {
>                     .onChange(of: posModel.cart.first?.id) { itemToScrollTo in
> 
> No change, this is the same logic. We add items to the top of the cart and scroll there.
> 
> It could perhaps be improved though; this means that we have the definition of where items are added in two places; the `insert` call, and here. I'll make a ticket to look at better ways in future.
> 

_Originally posted by @joshheald in https://github.com/woocommerce/woocommerce-ios/pull/14400#discussion_r1840093304_

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
I tried to improve this using:

```
.onChange(of: posModel.cart, { oldCart, newCart in
                guard posModel.orderStage == .building,
                      let itemToScrollTo = viewHelper.findNewItem(old: oldCart, new: newCart) else {
                    return
                }
                withAnimation {
                    proxy.scrollTo(itemToScrollTo)
                }
```

Which would make the cart scroll to any item newly added to the cart, no matter where it is.

Unfortunately, SwiftUI can't handle this, it takes too long to typecheck, probably because the various types of item make it too difficult.
