### ISSUE TITLE
[Woo POS] In dark mode, the cart header becomes not readable when scrolling up items in the cart

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#14414]
**Describe the bug**

Only an issue in dark mode: when the items in the cart becomes scrollable, the cart header turns white after scrolling up the list.

**To Reproduce**

Prerequisite: the store is eligible for POS, and has at least one purchasable product

- Go to Menu > Point of Sale Mode
- Switch to dark mode
- Add at least one product to the cart so that the list becomes scrollable (doesn't have to fill the height, just one item makes the list scrollable)
- Scroll up the items in the cart --> notice that the cart header changes color and the text is barely readable

**Screenshots**

https://github.com/user-attachments/assets/12ccfb8b-7fbb-47c3-9b8e-08959c5c32ea

**Expected behavior**

The cart header background color should stay the same when scrolling the list.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPad Pro 11in 3rd gen
- iOS version: iOS 17.5.1 device / iOS 18.0 sim
- WooCommerce iOS version: 20.9

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
Nice catch, thanks for raising it 👍
