### ISSUE TITLE
Fulfill Order: Product cell has no bottom padding when there is only one line of text

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1441]
When the Product cell only shows one line of text (like when the Product has no SKU), there is no space at the bottom of the cell:

![Simulator Screen Shot - iPhone SE - 2019-11-08 at 12 35 07](https://user-images.githubusercontent.com/1945542/68450112-c840f580-0224-11ea-9f6b-69b865281b28.png)

**Comment by pmusolino** [comment]
Similar issue: https://github.com/woocommerce/woocommerce-ios/issues/1359

**Comment by jaclync** [comment]
ohh closing this since this is the same as #1359
