### ISSUE TITLE
[Shipping labels] Add yosemite support for label purchase

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#14424]
We need to add support in `WooShippingAction` and `WooShippingStore` for a label purchase.

We don't need to store the response; we'll use it to poll for the label purchase status and then return the purchased label directly. See `ShippingLabelStore` for an example.

For now, we can stub out any logic around polling the status of the label purchase. This will be handled as part of #14053.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
