### ISSUE TITLE
Missing images in media library

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-ios#14432]
**Describe the bug**
Some images are not showing up in the media library when the user attempts to update a product image. I have been able to replicate the issue on my site. It seems to be related to the application password login as all images show up when I login using WordPress.com account, however, some images are missing when I login using application passwords. This issue is NOT reproducible in the Android app so there seems to be some inconsistency between the platforms.

**To Reproduce**
1. Login with application password flow
2. Try to upload a new image for one of the products
3. Select WP Media Library
4. Notice some images that are accessible in wpadmin do not appear in the app at all.

**Expected behavior**
All images available in the wp media library should be available in the mobile app.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13 mini
- iOS version: 17.6.1
- WooCommerce iOS version: 9.4

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by malinajirka** [comment]
CUW peaMlT-10b-p2

**Comment by hafizrahman** [comment]
Upon further investigation, in application password mode, Media Library consistently loads only 10 images.
