### ISSUE TITLE
'Send Feedback' option opens a non-existent page

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#14430]
**Describe the bug**
'Send Feedback' option opens a non-existent site

**To Reproduce**
1. Menu
2. Settings
3. Send Feedback
4. Notice 'Page not Found' error

![Image](https://github.com/user-attachments/assets/557b3d5f-a2c4-4b90-8394-499ba0137a4d)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPad M2 
- iOS version: 18.1
- WooCommerce iOS version: 21.1.0.1

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
I checked and the survey was still active but the survey URL had been changed. I don't see any discussion in Slack/p2 about changing the URL so I changed it back to the expected URL and it's working now!

**Comment by staskus** [comment]
@rachelmcr thanks!
