### ISSUE TITLE
[Performance Dashboard Card] Performance Card not showing cached Visitors and Conversion value if timestamp is fresh

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#14436]
Inside `StorePerformanceViewModel.reloadDataIfNeeded()`, which handles the data loading,  the logic is:
- load cached content first
- If the data is relatively new, skip fetching data from remote
- else, start fetching data.

Meanwhile, the viewmodel has the `siteVisitStatMode` property, which decides whether to show or hide the visit stats:

https://github.com/woocommerce/woocommerce-ios/blob/cac1fca1cb771f750171cfc41800f473085e8f94/WooCommerce/Classes/ViewRelated/Dashboard/StoreStats/StorePerformanceViewModel.swift#L36

This property is checked inside `StorePerfomanceView` whether to redact or show the data:

https://github.com/woocommerce/woocommerce-ios/blob/cac1fca1cb771f750171cfc41800f473085e8f94/WooCommerce/Classes/ViewRelated/Dashboard/StoreStats/StorePerformanceView.swift#L214-L225

Back in `reloadDataIfNeeded()`, the value of `siteVisitStatMode` is only updated if remote fetching is being done:

https://github.com/woocommerce/woocommerce-ios/blob/cac1fca1cb771f750171cfc41800f473085e8f94/WooCommerce/Classes/ViewRelated/Dashboard/StoreStats/StorePerformanceViewModel.swift#L179-L188

This created an edge case issue: 

if the app starts and loads visit data from cache, and the timestamp is fresh enough to skip remote fetching, then the cached data is available but redacted:

<img src="https://github.com/user-attachments/assets/9a70738b-617a-4abf-aa25-72f3301fc84a" width="42%">

The timestamp check is 30 minutes, so within this time, there's a possibility the data is not shown:

https://github.com/woocommerce/woocommerce-ios/blob/6448eef3dfc36dcdde49ce021fab45cbff42b4c5/WooCommerce/Classes/Tools/BackgroundTasks/DashboardTimestampStore.swift#L94

This can be replicated by doing so:

1. Have a demo site with a newly completed Order within this month, so stats can appear
2. Start app,
3. Enable Performance card, and set range to This Month. 
4. Wait until data appears properly (Orders, Visitors, and Conversion), then quickly build the app again in Xcode.
5. This will start the app again. Check how Visitors and Conversions value in Performance card are now redacted.

**Expected:** Visitors and Conversion values should be shown when cached data is available and remote fetching is not done.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
