### ISSUE TITLE
[REST API] Jetpack Setup: wordpress.com authentication flow doesn't start when the current user is passwordless and already Jetpack connected

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-ios#14469]
When trying to handle the Jetpack setup, and the wp-admin account used for signing in was already Jetpack Connected using a passwordless WordPress.com account, the wordpress.com authentication flow doesn't start, it stays stuck on the benefits screen.

To reproduce:

1. Use a Jetpack self-hosted website.
2. Make sure the user is connected to Jetpack using a passwordless account.
3. Open the app, and sign in using site credentials.
4. Open the jetpack setup from the dashboard.
5. Notice the issue.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
