### ISSUE TITLE
[Woo POS] [Cash & Receipts] Handle error on send receipt failure after successful payment

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#14464]

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
Some more context from [review](https://github.com/woocommerce/woocommerce-ios/pull/14481#discussion_r1865814501):

> Probably not; we need to be really careful not to give the impression that the payent has failed, when actually only sending the receipt has.

> Potentially this would be a good place for the view to handle the thrown errors somehow; then we can more easily display the error in-line with the receipt call that they relate to. This would probably need a specific view that can handle them, rather than the default button.

> In the IPP version of this, the button turns into a spinner while it's sending, then a check mark when it's done. Equally, it could show the error and a retry button if it fails.
