### ISSUE TITLE
[Woo POS] [Cash & Receipts] Prompt alert when Woo/WCPay versions are no correct

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#14465]
> I personally wouldn’t change eligibility criteria for the POS entry point for this project. I would show the button and show a snackbar/toast when the user clicks it “Please update Woo/WCPay to version xyz”.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
