### ISSUE TITLE
[Woo POS] [Cash & Receipts] View for sending receipt after payment

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#14461]
After tapping the "Receipt" button we present a view that enables the merchant to input an email to be sent:

![Image](https://github.com/user-attachments/assets/242260af-6ed8-4e60-9861-b618c0349743)

- Email is not optional, as it's the only choice.
- There is no sharing
- Email should be validated
- Once sending is completed successfully, start a new order.
- Can be dismissed by tapping `x`. This could either bring us back to "payment successful" view, or "start a new order" flow.
- Handle success/error on sending email

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
