### ISSUE TITLE
[REST API] Jetpack Setup: Magic Link flow opens the site picker if the app was closed before clicking it.

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-ios#14470]
During the Jetpack Setup, if we use magic link, the flow will open the site picker instead of continuing the setup if the app was closed before clicking on the link.

To reproduce:

1. Open the app and sign in using site credentials.
2. Start Jetpack Setup.
3. Use Magic Link.
4. When the magic link is sent, force close the app.
5. Click on the magic link in the email.
6. Notice that the app opened the site picker.

##### Identified in https://github.com/woocommerce/woocommerce-ios/pull/14431#pullrequestreview-2441757332

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
