### ISSUE TITLE
[Shipping labels] Update collapsed bottom sheet UI in landscape

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#14472]
We have a couple design enhancements for the collapsed bottom sheet in landscape orientation:

* Add the "Mark order complete" toggle next to the button (same as the expanded bottom sheet layout)
* Update the toggle copy to align with web: "After purchasing a label, mark this order as complete and notify the customer"

Example layout:

![Image](https://github.com/user-attachments/assets/76eefbc4-6100-4b84-85b0-bb65e945454a)

Internal ref: p1732055886685969-slack-C02KUCFCSFP

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
