### ISSUE TITLE
[Woo POS] [Cash & Receipts] New UI for sending receipt (full-screen)

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#14480]
Success case. 
- What happens while the email is being sent? Is there any loading screen/indicator to show here?
- Are we showing the user something after receipt is sent successfully ?
- Focus on the keyboard when entering the receipt form

Be sure to handle UX for multiple attempts (spinners, button disabled while loading, ... )

>  multiple taps on Send result in multiple emailed receipts. It also could do with a spinner state so that the user can tell their action is being handled.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
