### ISSUE TITLE
Aztec editor: new line issue

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1448]
There are a few issues related to a new line at the end of the text.

- There is always a "\n" inserted at the end of a Product's `description` field in the API response. We might want to remove the last newline (`\n`) when initializing the content of the editor. Otherwise, there is always a new line at the end in the app while it is not in the web editor. This would potentially fix the issue from [this comment](https://github.com/woocommerce/woocommerce-ios/pull/1440#issuecomment-552238267):
<img src="https://user-images.githubusercontent.com/2722505/68551344-f9990b80-0446-11ea-837f-55fbc0d1c381.png" width="350"/>

- When selecting all the text from the EOF new line, the new line is included. It seems to be the behavior in the Apple Notes app as well. Maybe we can find some workaround to either highlight the new line or exclude the new line where the cursor is. Screenshot from [this comment](https://github.com/woocommerce/woocommerce-ios/pull/1440#pullrequestreview-314142260):
![bug 1](https://user-images.githubusercontent.com/495617/68473470-587e3b00-0223-11ea-8f01-60f6d5250146.gif)

**Comment by pmusolino** [comment]
I did some investigation on this, but I wasn't able to find a solution without editing the text (which it's something we shouldn't do since we will edit the original content).
@jaclync since you have more experience than me on working with Aztec, do you have any suggestions? 🤷‍♂

**Comment by jaclync** [comment]
I don't think I've seen configurations to remove the trailing spaces, and yea it's not ideal to modify the content just to get around the extra newline. it looks like the newline is actually removed in the product page description on the store website, I'd say we skip this issue for [M1](https://github.com/woocommerce/woocommerce-ios/projects/9) or close this. what do you think @pmusolino ?

**Comment by pmusolino** [comment]
I agree with you @jaclync, after all, I see that all apps behave this way, and it doesn't make much sense to remove the spaces that exist. I believe we can close this issue unless it's something we really want to pursue.
