### ISSUE TITLE
[Woo POS] Extract services from Aggregate Model

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#14495]
The aggregate model has risks of getting too large, and just having the cross-cutting concerns too poorly defined within it. By extracting services, we can make the unavoidable cross-cutting concerns clearer, and add a little friction to adding new ones.

- [x] #14496
- [x] #14503
- [ ] Extract cart service
- [x] #14508

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
The cart code is too small to be worth extracting into a controller at the moment; we can consider that in future.
