### ISSUE TITLE
Remove First TTP usage survey

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-ios#14504]
Remove this survey https://automattic.survey.fm/woo-app-%E2%80%93-first-ttp-survey and the related code from the app.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
@malinajirka, I will remove it from the code but the surveys themselves can only be deleted after some time, or I shouldn't delete them?

**Comment by malinajirka** [comment]
Thanks @staskus, I'd personally keep them for now, they might still be useful for the POS related decisions.
