### ISSUE TITLE
[Woo POS] When checking out, skip order remote sync when there are no changes in the cart

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#14509]
As an optimization for the order sync in `POSOrderService`, we can skip the order update API request if the cart items are the same as before.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by jaclync** [comment]
Already done in https://github.com/woocommerce/woocommerce-ios/issues/13236, closing this.
