### ISSUE TITLE
[Woo POS] Extract payment service from Aggregate Model

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#14503]

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by joshheald** [comment]
This isn't practical without changes to the underlying payment service, so I'm going to close it as won't-do for now. If there's time later, we'll come back to it, but it's bigger than expected.

I think we would need to change the payment service to take the order and return it with errors and other retry opportunities, to avoid having to keep a second copy of the order in the (supposedly stateless) payment service.
