### ISSUE TITLE
Product: Error message is displayed when clearing all tags even though saving succeeds

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#14513]
**Describe the bug**
When clearing all tags for a product, there's always an alert displayed saying the creation fails even though the saving succeeds.

**To Reproduce**
1. Log in to a store.
2. Create a new product or select an existing product. 
3. Add at least one tag to the product and save changes if the product doesn't have any tag yet.
4. Reopen the tag list for the same product, clear all tags and tap Save.
5. Notice that an error alert is displayed.
6. Check the network request using Proxyman or Charles and confirm that the save request is completed without any error.

**Screenshots**
https://github.com/user-attachments/assets/7d47591a-2467-4488-bdad-a64e6bd6a9d8

**Expected behavior**
The error alert should not be displayed because the request did not fail.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
