### ISSUE TITLE
Selected package and shipment weight UI

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#14522]
We need to add the UI for the selected package and shipment weight on the main shipping label screen.

Entering a new shipment weight should trigger a new request for shipping services (label rates) after 1-2 seconds.

Design:

![Image](https://github.com/user-attachments/assets/1a559fe0-799e-4620-acf3-189f106c2dbd)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
Before this task is closed, the selected package view should be updated to handle:

- [ ] Custom package without a name (maybe show `Custom Package` in place of the name field, instead of a blank space)
- [ ] Package with empty weight (either show 0 weight or hide weight description)
