### ISSUE TITLE
[Shipping labels] Integrate print label action into UI layer in Woo Shipping flow

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#14538]
In `WooShippingPostPurchaseView`, we need to print the label when the print button is tapped. This should:

* Dispatch the action to fetch the label data from remote for the selected paper size.
* Present the system print controller with the fetched data.

We might be able to reuse some or all of the logic in `PrintShippingLabelCoordinator` for this.

Note: Per the discussion in Slack (p1732618862774319-slack-C02KUCFCSFP) we are not using the default paper size set in the store; that will be implemented in a later milestone. For now we only need to handle the paper size selected in the UI.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
