### ISSUE TITLE
Make CoreDataManager thread-safe

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#14533]
When checking an issue with screenshot testing [p1732623939631369-slack-C03L1NF1EA3], @hichamboushaba found that the way we instantiate `persistentContainer` is not thread-safe as we can create it when accessing both `viewStorage` and `writerDerivedStorage`, which are in different threads. 

For safety, the `persistentContainer` should be kept a constant in `CoreDataManager`.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
