### ISSUE TITLE
[Media] Use `wp/v2` endpoint for loading WP media library and updating Product ID

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#14550]
### Problem

We currently use `rest/v1.1` endpoints for the following two remote calls. This doesn't work when XMLRPC is disabled on the site.

1. To [load media from WP media library](https://github.com/woocommerce/woocommerce-ios/blob/272ae28b6124962d8f94a685e6493c0046be4674/Yosemite/Yosemite/Stores/MediaStore.swift#L104-L121)
1. To [link the product with the media ID](https://github.com/woocommerce/woocommerce-ios/blob/272ae28b6124962d8f94a685e6493c0046be4674/Yosemite/Yosemite/Stores/MediaStore.swift#L226-L232)

Related issue - https://github.com/woocommerce/woocommerce-ios/issues/14232

### Proposed solution

Start using `wp/v2` endpoint to load images from media library. This endpoint works even when XMLRPC is disabled. 

Internal -  p1732776777296839/1732776754.769469-slack-C03L1NF1EA3

### TODO 

After finishing the above work and releasing it to users.

- [x] Announce to Happiness team once we longer need XMLRPC for Media.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
