### ISSUE TITLE
[Woo POS] Improve Hashable and Equatable conformance for OrderSyncProductInput.ProductType

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#14563]
These need work, and tests. At the moment, they're only used for grouping the OrderItems correctly, using the dictionary functions, in `createGroupedOrderSyncProductInputs`. I'll tackle this in the variations project.

_Originally posted by @joshheald in https://github.com/woocommerce/woocommerce-ios/pull/14562#discussion_r1863724016_

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
