### ISSUE TITLE
Free shipping accepts shipping amount

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#14584]
While testing https://github.com/woocommerce/woocommerce-ios/pull/14568 I just realized that selecting Free Shipping still allows to input an amount, which doesn't make much sense. 

I have not tested what's the core behaviour here, just logging it for now.

![Image](https://github.com/user-attachments/assets/3a0c9471-8aaf-4419-a6c1-fe9dc426d093)
![Image](https://github.com/user-attachments/assets/2b59f1aa-54ff-4c0e-b656-0fa659ea1f37)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
This matches the core behavior:

![Image](https://github.com/user-attachments/assets/e3b54822-1641-481d-8829-bf6b506b485f)

I'll close this since I don't think we should diverge from core on this, but feel free to reopen if there's something more to consider here.
