### ISSUE TITLE
Star/unstar predefined package (use backend)

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#14598]
- Use `WooShippingAction.createPackage` to star predefined package and processing response.
- Missing ability to unstar a package, this will be done with the delete action from https://github.com/woocommerce/woocommerce-ios/issues/14589 when it is done

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
