### ISSUE TITLE
[Woo POS] [Cash & Receipts] Encapsulate and move receipt-related logic outside the aggregate model

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#14609]
Follow-up from https://github.com/woocommerce/woocommerce-ios/pull/14587#discussion_r1869507087 and p1733995434442479-slack-C070SJRA8DP

Thoughts:
- Receipt eligibility should be out of the aggregate model
- Since we're manipulating the order and relying on that order state, the core logic probably wants to go on the order controller, but not necessarily in the order service. The order controller could have both order service and receipts service, these should be simple and stateless.
- Views shouldn't have controllers
- We're currently limited by the API, which forces us to perform requests to send the receipt: the endpoint accepts an orderID and a siteID, but no string for the recipient email, as core uses the email that has already been added to the order, which in our case (POS) is none, so we need both APIs. Ideally we should need only one request by passing the email only.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
