### ISSUE TITLE
[TTPReq] Education: Move important information from About to Education

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-ios#14608]
### Description

'About Tap to Pay on iPhone' view contains more than a description and a short tutorial but also helpful information on the limitations of the specific market.

Include it in the first Education step.

![Image](https://github.com/user-attachments/assets/4d04e0e2-b52f-476a-a9bf-4d43f0339f67)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
