### ISSUE TITLE
[Notification] Track local notification interactions

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#14614]
### Issue

In https://github.com/woocommerce/woocommerce-ios/pull/12443, we accidentally removed the code for tracking local notification tapped and dismissed events were accidentally removed while removing code related to Free Trial local notification and survey. [Deleted tracking code](https://github.com/woocommerce/woocommerce-ios/pull/12443/files#diff-bb0251a65b8ec92e260becd00dbedeb98da47c93a0bd6d78a427c7f427768d48L426-L434) 

### Solution

Add back the tracking code to start tracking those events. Refer code from [here](https://github.com/woocommerce/woocommerce-ios/pull/12443/files#diff-bb0251a65b8ec92e260becd00dbedeb98da47c93a0bd6d78a427c7f427768d48).

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
