### ISSUE TITLE
Google Ads: Hub menu item always redirects to campaign creation

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#14631]
**Describe the bug**
As the title suggests, the hub menu entry point always redirects to campaign creation regardless of whether the store has existing campaigns.

**To Reproduce**
1. Log in to a test store eligible for Google Ads.
2. Tap on the entry point of Google Ads in the hub menu.
3. If the store doesn't have any campaign yet, create one.
4. Otherwise, confirm that campaign creation is still displayed even though there are existing campaigns.

**Expected behavior**
The hub menu entry point should redirect to the campaign list if the store has any campaigns.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
