### ISSUE TITLE
Reviews: Review still highlighted after marked as read

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#14640]
**Describe the bug**
When selecting an unread review and navigating back to the list, the review is still highlighted.

**To Reproduce**
1. Go to Menu tab > Reviews
2. Tap on an unread review
3. Navigate back to the list
4. Notice that the review is still highlighted. The highlight only goes away after reloading the list.

**Screenshots**
https://github.com/user-attachments/assets/0239193f-2299-4e8f-ac1e-c809b4f40cbf

**Expected behavior**
The highlight should be removed after reading reviews.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
