### ISSUE TITLE
Ensure consistent ordering of carrier packages

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#14656]
Currently the Add Packages view does not order the carriers or packages list consistently. We should set the ordering so that when the package options are the same, the tabs and list ordering is also consistent each time the view is opened.

Example from opening the view a few times:

First|Second|Third
-|-|-
![Image](https://github.com/user-attachments/assets/b99888cd-e29e-4878-8886-9919135d3420)|![Image](https://github.com/user-attachments/assets/7cd36992-0c4b-4316-8258-2dd511391d9f)|![Image](https://github.com/user-attachments/assets/2d12c008-46f6-4c9e-96ca-b5eae3a6e3f8)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by bozidarsevo** [comment]
If we define the order of carriers (e.g., USPS, DHL) on the client side, any changes to the order would require updating all clients (web, iOS, and Android) to ensure consistency. Additionally, when new carriers are added, we would need to synchronize the updates across all clients to maintain the same order.

In my opinion, the backend should handle the ordering of carriers and consistently return them in the desired order. This approach ensures that clients simply display the data as received, without needing to manipulate the order themselves.

By shifting the ordering logic to the backend, we gain flexibility for the **future**. For example, we can update the order (e.g., prioritize a new carrier, move another to the end, etc.) for all clients by simply updating the backend, without requiring changes to the client applications.

**Comment by rachelmcr** [comment]
I'm not as concerned about cross-platform consistency in the ordering as I am about consistent ordering within the app, since it felt confusing to have the options change places each time I viewed them. I don't have a strong preference between either a local solution or updating the backend. Either way, we can use this issue to track the task.

**Comment by bozidarsevo** [comment]
After looking at the response from the backend, we will need to "force" the order on the clients since backend returns the carriers list as a dictionary (carrier id is the key) and not as an array. :/
