### ISSUE TITLE
Check existing entities for non-optional attributes without default values

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#14662]
When  `NSManagedObject` instance is deleted and the context is saved but the object is still accessible in memory - Core Data would infer values for the equivalent Swift properties. In the case of non-optional ones without default values, the inferred values depend on their types:

- `String` -> empty string
- Numeric types -> 0
- `Data` -> empty data

In other cases, substituted values cannot be inferred: `Date`, `UUID`, `URI`. In these cases, attempting to access a non-substituted property would lead to a crash similar to #14312.

We need to check for instances of the special types and make those property optional to avoid crashes.

Reference: https://holko.pl/2017/09/18/surprising-non-optional-nsmanaged/

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
