### ISSUE TITLE
Bug: Double loading indicator on saved package list

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#14668]
@rachelmcr noticed a double loading indicator on the saved package list. I think it's because we've added a `ProgressView()` to the view but the `refreshable` view modifier also adds its own loading indicator:

https://github.com/user-attachments/assets/b45a8e2c-e3d8-4866-a22c-2d437ee85ca1

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
