### ISSUE TITLE
Bug: Switching store doesn't work like expected

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#1466]
If you try to change the store from Settings, but you don't press continue after choosing it, you will see that the default store of the app changed, and the store name in settings is the old one (as long as you don't change screen).
This bug can be reproduced systematically.

### To Reproduce
1) Make sure you have more than one store on your account.
2) Go to Settings
3) Press Switch Store
4) Tap on a store, and press Dismiss (not continue)
5) You will see that the store tapped is now configured in all the app, and the selected store, as long as you don't change the screen, is the old one.

### Screenshots
![switch store bug](https://user-images.githubusercontent.com/495617/68790985-ae4e4b00-0648-11ea-872c-01e1f3dc8ce3.gif)

### Mobile Environment
- Device: Simulator
- iOS version: iOS 13.1
- Woo app version: 2.9 & 3.0

**Comment by pmusolino** [comment]
It seems a problem related only to iOS 13, since `viewWillAppear()` is never called, and the controller is unable to refresh data.

**Comment by shiki** [comment]
I can confirm that this is still valid. Tapping Dismiss changes the store. 🤯

**Comment by pmusolino** [comment]
This is no more valid since we dropped iOS 13 support. Closing it 👍
