### ISSUE TITLE
[Woo POS] [Variable Products] Networking layer support for fetching variations for POS with Swift concurrency

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#14685]
Networking layer changes to load variations with async/await.

From the [WC variations API doc](https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-product-variations), it doesn't look like we can only load purchasable variations like the products list endpoint. We can filter purchasable variations in the Yosemite layer.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
