### ISSUE TITLE
[Woo POS] [Variable Products] Present POS as the root of a new view instead of a view pushed to the Menu tab navigation stack

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#14683]
Ref: pdfdoF-61P-p2

In order to sho variations for a variable product in the item selector panel using `NavigationStack`, the POS view cannot be nested in the Menu tab's `NavigationStack` anymore. The POS view will be presented as the root of a new view, instead of being pushed to the Menu tab's navigation stack.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by jaclync** [comment]
Closing this - as discussed in p1734358649875949/1734331128.921509-slack-C070SJRA8DP, we probably want to explore a better transition that feels more like a "mode switch" in the future. For the variable products project, we're good with the default `fullScreenCover` (the only fullscreen presentation SwiftUI modifier for now) presentation from bottom to top.
