### ISSUE TITLE
[Woo POS] [Variable Products] Add sub list hierarchy to the items controller

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#14698]
## Description

Follows on from [#14693](https://github.com/woocommerce/woocommerce-ios/issues/14693).

In this ticket, we're looking to add support for sublists of items to the state.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by jaclync** [comment]
I'm guessing this is where we start fetching variations, like with the variation provider `posVariationProvider: PointOfSaleVariationServiceProtocol`. Just a note that we want to filter out some variable products / variations on the client side:
- Products level: filter out variable products with 0 variations
- Variations level:
  - Filter out variations with "any" attribute pdfdoF-5WW-p2 - this I'm not sure why, clarifying in pdfdoF-5WW-p2#comment-7154
  - Filter out variations that are virtual or downloadable ([Android ref](https://github.com/woocommerce/woocommerce-android/blob/71e0fae1e6d9b4a904a640e634a1055b147fcf45/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/variations/WooPosVariationsViewModel.kt#L87))
  - Filter out non-purchasable variations (I came up with this one, we can remove it if it doesn't make sense. [Android checks if the price is null](https://github.com/woocommerce/woocommerce-android/blob/71e0fae1e6d9b4a904a640e634a1055b147fcf45/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/items/variations/WooPosVariationsViewModel.kt#L121))
