### ISSUE TITLE
[Woo POS] [Variable Products] Add POSItem enum to replace POSDisplayable protocol and contain various product types

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#14692]
## Description

We currently use a `POSDisplayableItem` protocol, which contains the product-related fields needed to display a simple product in the UI. 

The original intention was to change the requirements for that protocol to a `@ViewBuilder var rowView: some View`, which could be used to show the appropriate UI for an item in the POS. However, it's become clear that would require the use of a Protocol Associated Type (PAT) which makes it impractical to use the `POSDisplayableItem`s in a heterogenous array, which is crucial. It also makes it difficult to use Equatable, Identifiable, Hashable, and other similar conformances.

We will only ever support a limited number of product types, so it's not worth the trade-offs needed to make this fully generic.

After experimentation, we've decided to replace the protocol with a `POSItem` enum, which may have associated values that conform to generic protocols for other parts of their behaviour.

```
enum POSItem: Equatable, Hashable, Identifiable {
    case simpleProduct(POSOrderableItem)
    /// Initially, only the above is required. For variable products we'll add:
    case parentProduct(POSParentItem)
    case variation(POSOrderableItem)
    /// In the future, we may add more types:
    case groupedProduct(POSParentItem)
    case subscriptionProduct(POSOrderableItem)
    case cartDiscount(POSFeeItem)
    case customAmount(POSFeeItem)
    case coupon(POSCoupon)
}
```

The `ItemList` will show these, from an array of `POSItem`s from the state. To display a row, it will switch over the Item, and draw the appropriate item, probably using an extension on POSItem to do that. The associated values should have anything that's needed to display and add the item to an order, if appropriate, or show child items.

This ticket is just covering the work to convert to the new enum.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
