### ISSUE TITLE
Bug: custom package weight sometimes as box_weight sometimes as boxWeight

### ISSUE THREAD

**Issue by bozidarsevo** [woocommerce/woocommerce-ios#14725]
Looks like that the endpoint for creating custom package returns the weight as `boxWeight` and general endpoint for getting packages returns custom packages with weight as `box_weight` so we need to handle both cases since we use same struct for both responses

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
