### ISSUE TITLE
[Shipping labels] Scroll to selected package in add package view

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#14734]
Raised in https://github.com/woocommerce/woocommerce-ios/pull/14713#pullrequestreview-2515349657:

> Would it be possible to scroll to selected package when we edit selected package?
> 
> In this example I select a starred/saved carrier package and when I go to edit it, the saved list is showed but that selected package is not visible.

https://github.com/user-attachments/assets/3ee13387-16c3-4a2b-8bd0-e7eedf951d21

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
