### ISSUE TITLE
Settings: Settings screen does not update/refresh after switching stores

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1480]
**Describe the bug**

After switching store, the Settings screen is not updated. The most obvious issue is that it still shows the previous store address. A smaller issue is that if one store uses WC Admin and the other doesn't, the Beta Features cell (currently used for the v4 stats) isn't added/removed as needed.

**To Reproduce**
1. Log in to the app using an account with multiple stores.
2. Go to the Settings screen and confirm you see the correct information for the site.
3. Tap "Switch Store."
4. Select another store and tap Continue.
5. Note that you are taken back to the Settings screen and the address under Selected Store is unchanged, even though a notice appears confirming you switched sites.
6. Tap the Back arrow in the top left.
7. Open Settings again and note that the address under Selected Store has updated to the correct address.

**Screenshots**

Screencast here: https://cloudup.com/coVgmzXpGml

**Expected behavior**

The Settings screen should immediately update to the new store's information after selecting the store and tapping "Continue."

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.2
- WooCommerce iOS version: 3.0.0.0 (TestFlight beta)

**Comment by pmusolino** [comment]
Related issue: https://github.com/woocommerce/woocommerce-ios/issues/1466
