### ISSUE TITLE
Order Details: Product quantity pushed off screen if product name has en dashes

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1482]
**Describe the bug**

If a product name has en dashes (`–`) the name isn't wrapped correctly. Instead, it pushes the product quantity off screen (partially or fully) or replaces the quantity with an ellipsis so it can't be read correctly.

**To Reproduce**
1. Create a product with an en dash in the name (e.g. `Long Product Name – with dashes`)
2. Create an order for that product, with a large quantity (e.g. 15 items).
3. Go to Orders in the app.
4. Select the Order Detail for that order.
5. See how the quantity does not appear correctly in the product list.

**Screenshots**

In each screenshot, the quantity for all products in the order is 15.

<img src="https://user-images.githubusercontent.com/8658164/68961230-d2856580-07c9-11ea-8d88-9d91f8057236.png" width="50%">
<img src="https://user-images.githubusercontent.com/8658164/68961233-d3b69280-07c9-11ea-8aab-f915ff6d0e39.png" width="50%">
<img src="https://user-images.githubusercontent.com/8658164/68961453-5a6b6f80-07ca-11ea-8027-76083584401e.png" width="50%">

**Expected behavior**

I expect the text to wrap so that the quantity is always fully visible on screen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.2
- WooCommerce iOS version: 3.0.0.0

Originally reported by a beta tester:
- Device: iPhone 11 Pro
- iOS version: 13.2.2
- WooCommerce iOS version: 3.0.0.0

**Comment by melindahelt** [comment]
This display is slightly different, but reported by a user with an iPhone X with the quantity partially cut off.

![](https://d.pr/i/AmtGiL+)Image Link: https://d.pr/i/AmtGiL
