### ISSUE TITLE
[Issue Refunds] Add the first "refund by amount" page

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1488]
<img src="https://user-images.githubusercontent.com/1062444/69063675-8b25f180-09e2-11ea-938f-88050be8b5b0.png" />

<img width="409" alt="Screen Shot 2019-11-18 at 9 23 26 AM" src="https://user-images.githubusercontent.com/1062444/69065289-228c4400-09e5-11ea-9901-3178771b8c60.png">

- [ ] Connect the "issue refund" button so it navigates to the new page
- [ ] Add the UI
- [ ] Don't allow the user to input an amount higher than the net total (order total or current total - existing refunds)
- [ ] Add localized placeholder text
- [ ] Ensure the correct currency symbol is displayed and appears on the L or R, depending on their site settings.
- [ ] Tapping the refund amount field presents a numeric keypad
- [ ] Numeric input follows the same behavior observed on Square

**Comment by Ecarrion** [comment]
Moving this to `maybe` as it's not yet live on Android

**Comment by shiki** [comment]
Based on @Ecarrion's discovery in p91TBi-3hR-p2#comment-1762, this is disabled in Core. I'll just close this issue for now. 

> What was disabled in core was “refund by amount” to the total order, not to a specific item. This is still disabled today.
