### ISSUE TITLE
Dark mode: cell style in shipment tracking screens

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1499]
**Describe the bug**
In Shipment Tracking screens, when you have dark mode enabled some cells are dark.

**To Reproduce**
1. Open the Orders tab on a store with the Shipment Tracking extension.
2. Select a new order.
3. On the Order Details screen, go to "Optional Tracking Information" and select "Add Tracking."
4. Note that the placeholder text in the "Tracking number" cell is too light to read.
5. Tap on "Date shipped" and note that the spinner is dark.
6. Tap on "Shipping provider" and note that the Search cell is dark.

**Screenshots**

Tracking number placeholder:

<img src="https://user-images.githubusercontent.com/8658164/69262675-cd565b00-0bbb-11ea-826e-2899238864e7.png" width="50%">

Shipping provider search:

<img src="https://user-images.githubusercontent.com/8658164/69262686-d1827880-0bbb-11ea-86b2-c7294fda76ec.png" width="50%">

Date shipped spinner:

<img src="https://user-images.githubusercontent.com/8658164/69262706-d6472c80-0bbb-11ea-86a3-12ef8235b095.png" width="50%">

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS in dark mode
- iOS version: 13.2.3
- WooCommerce iOS version: 3.1.0.0 beta

**Comment by mindgraffiti** [comment]
Fixed during dark mode bug fixes in v3.3. Thanks @jaclync 😀 

<img src="https://user-images.githubusercontent.com/1062444/72107373-cc59c400-32f6-11ea-88ed-629da8c8b735.PNG" width="350" />

<img src="https://user-images.githubusercontent.com/1062444/72107374-cc59c400-32f6-11ea-84a3-58612059ef4f.PNG" width="350" />

<img src="https://user-images.githubusercontent.com/1062444/72107375-cc59c400-32f6-11ea-896f-a71638b764c2.PNG" width="350" />
