### ISSUE TITLE
Add sale start/end dates to Product

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1505]
## Storage layer
- [x] Schema change: add sale start/end date attributes to `Product` entity

## UI
- [x] Show the sale period on the Price settings row in Add/Edit Product main screen

**Comment by pmusolino** [comment]
Related to https://github.com/woocommerce/woocommerce-ios/issues/1423

**Comment by pmusolino** [comment]
UI: Show the sale period on the Price settings row in Add/Edit Product main screen
![Schermata 2019-12-05 alle 11 38 56](https://user-images.githubusercontent.com/495617/70228000-e03c6400-1753-11ea-8956-dd63200ffaca.png)
