### ISSUE TITLE
Zendesk: limit log size to 64k characters

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-ios#1509]
When any Support request is created, we automatically take the current app log and populate Zendesk’s `System Status Report` field with it. If the log is big enough, it will exceed the field limit. This will cause any request to fail. We should add some logic to truncate that file to 64k characters.

This has already been caught and fixed in this WPiOS ticket: https://github.com/wordpress-mobile/WordPress-iOS/issues/12297

**Comment by mindgraffiti** [comment]
Thanks for the heads up!

**Comment by jaclync** [comment]
closing now, PR didn't close this issue because it was targeting release 3.5
