### ISSUE TITLE
Zendesk > My Tickets navigation title should be white

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1513]
Research the My Tickets view controller and determine if we have customization options to change the navigation bar title back to white. If this is not customizable, contact Zendesk Support and get a bug ticket filed against their SDK.

<img src="https://user-images.githubusercontent.com/1062444/69377551-2254a880-0c72-11ea-8ea8-6ccd0679ae08.png" width="350" />

---

Update: 2020-09-18 More reproduction steps can be found in #1793.

**Comment by mindgraffiti** [comment]
Filed a support request with Zendesk. We're following the "Adding Tickets" [instructions](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/requests#adding-tickets) just fine. "[Customizing the look](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/customize_the_look)" claims:

>Some colors in the Support SDK UI are inherited from your app, like the navigation bar.

But it appears that Zendesk is overriding the nav bar title color internally. Setting or configuring the nav bar that pushes the Ticket list view controller onto the stack does nothing.

**Comment by mindgraffiti** [comment]
Research this for possible solutions: https://support.zendesk.com/hc/en-us/community/posts/204607658-Change-navigation-bar-color-in-iOS-SDK

**Comment by shiki** [comment]
This is probably related to #1793

**Comment by ealeksandrov** [comment]
Now normal navbar style doesn't interfere with Zendesk SDK, but there is a problem in dark mode:

light|dark
--|--
![Simulator Screen Shot](https://user-images.githubusercontent.com/3132438/132506032-5842fc54-c530-48f8-9f72-3c81888c65d0.png)|![Simulator Screen Shot](https://user-images.githubusercontent.com/3132438/132506430-ccc258b7-ff63-4e58-bc46-272572cb8a94.png)

**Comment by mindgraffiti** [comment]
Welcome to the pain and sadness that is Zendesk 😖 . But in all seriousness, good luck. Zendesk's APIs are terrible when attempting styling.

**Comment by dorisdarw** [comment]
This is still not solved... I am still having this issue.

**Comment by iamgabrielma** [comment]
Closing, no longer an issue as we use a native UI since pe5pgL-2cg-p2 and “My Tickets” section doesn't exist anymore.
