### ISSUE TITLE
Stats v4 chart responds to scrubbing while pull to refresh being activated

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-ios#1517]
**Describe the bug**
When pulling to refresh the chart still responds to touches which makes for a funky interaction.

**To Reproduce**
1. Go to v4 stats screen.
2. Start pulling to refresh over the graph.
3. Notice the time/date label changes with movement and the visitor stats label disappears.

**Screenshots**
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-22 at 09 49 38](https://user-images.githubusercontent.com/373903/69440345-4960b800-0d0e-11ea-88c7-bc8808fc32e3.png)

**Expected behavior**
When the pull to refresh gesture recognizer has captured the gesture, disable interactions on the chart.

**Mobile Environment**
Please include:
- Device: iOS Simulator - 11 Pro Max
- iOS version: 13.1
- WooCommerce iOS version: develop

**Comment by astralbodies** [comment]
Ignore the dark mode errors 😄

**Comment by joshheald** [comment]
Can no longer reproduce this on iOS 14 or 15, on simulator or device.
