### ISSUE TITLE
Product Variations: the separator on the bottom cell disappears when spinner is visible

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1519]
From https://github.com/woocommerce/woocommerce-ios/pull/1510:

<img src="https://user-images.githubusercontent.com/495617/69444625-0542d700-0d51-11ea-99a9-694cc55a993a.gif" height="500" />

This seems to happen on certain types of simulators/devices, as it didn't happen on the iPhone 8 iOS 13.1 simulator

**Comment by shiki** [comment]
It looks like our UI have changed and this issue is no longer valid. 

https://user-images.githubusercontent.com/198826/104079080-71df9600-51de-11eb-8a17-8206866b8b7e.mp4
