### ISSUE TITLE
Settings: enable experimental features after logout generate a wrong status

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#1532]
It seems that after making logout, and closing the app, when a user tries to log in, can see the old toggle still enabled, but without the feature enabled.

## Steps to reproduce the behavior
1) Go in settings, and enable an experimental feature, like Products.
2) Logout from the app.
3) Close the app
4) Reopen the app
5) Go into settings -> Experimental features
6) You can see the toggle is still ON, but the feature is not enabled.
7) Close the app. Relaunch it. You will see the toggle ON, and the feature enabled.

## Screenshot
<img src="https://user-images.githubusercontent.com/495617/69727315-95529900-1122-11ea-9493-9a8af1524095.png" width="300" />

## Mobile Environment
- Device: Simulator
- iOS version: iOS 13.2.2

**Comment by rachelmcr** [comment]
I came across this today during beta testing (with TestFlight beta 3.2.0.1). I saw the same results with the steps above, although I also noticed that if I close and relaunch the app the Products section is enabled.

**Comment by pmusolino** [comment]
I was also able to replicate your problem @rachelmcr 
I updated the issue description.

**Comment by jaclync** [comment]
closing manually since the PR wasn't targeting `develop`
