### ISSUE TITLE
Dark Mode: Order list filter has dark text on dark background

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1535]
**Describe the bug**

In dark mode, the order status filter has dark background (coming from iOS) with text color which doesn’t have much contrast with the dark background.

h/t @anant1811 for the report

**To Reproduce**
1. Enable dark mode on your device.
2. Open the Orders tab.
3. Tap the filter icon in the top right.

**Screenshots**

![image](https://user-images.githubusercontent.com/8658164/69866125-28164380-129b-11ea-9ac6-b856f26da166.png)

**Expected behavior**

Ideally this wouldn't be in dark mode until dark mode is fully supported in the app, but at least it should have a legible text color.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XR
- iOS version: 13.1.3
- WooCommerce iOS version: 3.1.0.1 beta

**Comment by jaclync** [comment]
after the Dark Mode support in 3.2, this seems fixed:

dark | light
-- | --
![Simulator Screen Shot - iPhone SE - 2019-12-03 at 15 00 43](https://user-images.githubusercontent.com/1945542/70027735-c24cf300-15dd-11ea-8e11-fff9287ff32e.png) | ![Simulator Screen Shot - iPhone SE - 2019-12-03 at 15 01 26](https://user-images.githubusercontent.com/1945542/70027752-caa52e00-15dd-11ea-84a9-3e8a4aaabf2c.png)

@rachelmcr  feel free to close this issue now or after verifying in the release 3.2 TestFlight build :)
