### ISSUE TITLE
Order List "Ghost" boxes showing default text from XIB while pulsing

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-ios#1541]
**Describe the bug**
When the ghost boxes are pulsing during an initial data load the text from the XIB is visible in the box rather than them being blank and with an offset background color.

**To Reproduce**
1. Log out of the app.
2. Log into the app.
3. Select a site with orders on the server to download.
4. Switch to the orders tab. Ghost with text in the fields is visible briefly.

**Screenshots**
I forced the controller to show the ghost cells every time I refreshed and I snagged a screenshot:

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-28 at 15 00 52](https://user-images.githubusercontent.com/373903/69968037-36ed3800-14df-11ea-88ac-e75988b7bb61.png)

**Expected behavior**
The ghost labels should be empty or at least the foreground match the background color. Not sure what broke and when so I don't know the right solution to fix it.

**Mobile Environment**
Please include:
- Device: iPhone 11 Pro Max Simulator
- iOS version: 11.2?
- WooCommerce iOS version: develop (3.2)

**Comment by jaclync** [comment]
closing manually since the PR was not targeting `develop`
