### ISSUE TITLE
Order Details: Is possible for the additional custom checkout fields to be displayed within order details on the WooCommerce iOS app? 

### ISSUE THREAD

**Issue by RpZ79** [woocommerce/woocommerce-ios#1563]
Is possible for the additional custom checkout fields to be displayed within order details on the WooCommerce iOS app?

Thanks

**Comment by mindgraffiti** [comment]
Hi @RpZ79!

It would be great if you could add this idea to our WooCommerce Mobile Apps Ideas Board, which is where we collect future app improvements. You can add a new idea there and/or vote for any of the existing ones:
http://ideas.woocommerce.com/forums/133476-woocommerce?category_id=84283
