### ISSUE TITLE
Stats: Selected bar in stats chart shows dark text on dark background

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1566]
**Describe the bug**

With the older stats feature (not improved stats), the stats bar chart shows the bars in pink. Selecting a bar makes it dark pink. The details that pop up above the bar also have a dark pink background, with black text, making it hard to read.

**To Reproduce**
1. Make sure improved stats is not enabled (under Settings > Experimental Features disable the "Improved stats" toggle).
2. On the My store tab, select a bar in the stats bar chart.
3. Notice the text is hard to read.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/70230528-6f477d00-1750-11ea-98d0-e5bc4922a22e.png" width="50%">

The text looks ok with the dark mode colors:

<img src="https://user-images.githubusercontent.com/8658164/70230571-87b79780-1750-11ea-8af8-909139250e8e.png" width="50%">

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.2.3
- WooCommerce iOS version: 3.2.0.1

Originally reported by a TestFlight beta tester.

**Comment by rachelmcr** [comment]
Here's how that bar chart looks in the current app store version (3.1.1.0), for reference:

<img src="https://user-images.githubusercontent.com/8658164/70230786-014f8580-1751-11ea-8412-0b75e4058774.png" width="50%">

**Comment by jaclync** [comment]
should be fixed by https://github.com/woocommerce/woocommerce-ios/pull/1571
