### ISSUE TITLE
Order List: Color-coded labels for order status

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1567]
**Is your feature request related to a problem? Please describe.**

A TestFlight beta tester noted that the new color scheme in version 3.2 uses the same color for all order statuses in the order list, making them indistinguishable when glancing at/skimming the list. 

Right now, it seems that only the "Refunded" status has a different color:

<img src="https://user-images.githubusercontent.com/8658164/70231503-593abc00-1752-11ea-920c-e57db6c9e5cb.png" width="50%">

**Describe the solution you'd like**

Something similar to the old color scheme with different colors for different order status would make it easier to see at a glance.

**Additional context**

Here's how the labels are color coded in the current app store version (3.1.1.0):

<img src="https://user-images.githubusercontent.com/8658164/70231583-86876a00-1752-11ea-8778-cb9c727af54f.png" width="50%">

**Comment by mindgraffiti** [comment]
Fixed in v3.3 ✅ 
(Possibly during dark mode color changes?) 

<img src="https://user-images.githubusercontent.com/1062444/72107571-35d9d280-32f7-11ea-877e-db6c27671240.PNG" width="350" />
