### ISSUE TITLE
Product List: Paging is not alphabetical, so some products are missing from list on first load

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1569]
**Describe the bug**

The app loads 25 products at a time. The product list is ordered alphabetically, but the paging doesn't seem to be alphabetical, so the first 25 products to be loaded may not be the first 25 products alphabetically.

As a result, some products are missing from the list on first load and only appear after scrolling down. (Even though when you scroll, they are inserted in alphabetical order instead of appearing at the bottom of the product list.)

**To Reproduce**
1. Ensure your store has more than 25 products.
2. Start by logging out of the app and logging in again (to ensure no product data is cached).
3. Enable the Products section under Settings > Experimental Features.
4. Go to the Products tab. Note that not all items appear in the list.
5. Scroll down until more products load. Note that items are loaded but they aren't loaded in alphabetical order so they appear throughout the product list instead of at the bottom.

**Screenshots**

Product list on first load:

<img src="https://user-images.githubusercontent.com/8658164/70255230-548bfd00-177e-11ea-990b-6fa5a4e0e396.png" width="50%">

First API request: `/rest/v1.1/jetpack-blogs/137210602/rest-api/?json=true&path=/wc/v3/products%26_method%3Dget%26context%3Dview%26page%3D1%26per_page%3D25`

Product list after scrolling down and back up again (note the three products that didn't appear before):

<img src="https://user-images.githubusercontent.com/8658164/70255250-5d7cce80-177e-11ea-8d90-9b20dcbdedaa.png" width="50%">

Second API request after scrolling: `/rest/v1.1/jetpack-blogs/137210602/rest-api/?json=true&path=/wc/v3/products%26_method%3Dget%26per_page%3D25%26context%3Dview%26page%3D2`

**Expected behavior**

I expect the products to be requested in the same order they are displayed (alphabetically) so that scrolling down loads more products at the bottom of the list.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.2.3
- WooCommerce iOS version: 3.2.0.1

**Comment by rachelmcr** [comment]
We should be able to fix this by adding `&orderby=title&order=asc` to the request, so that we request the products in alphabetical order by title (instead of descending order by date, which is the default).

cc @jaclync @pmusolino

**Comment by jaclync** [comment]
wow thank you @rachelmcr for the params before I go search for the API doc! I tested the path in Postman and I can make the fix next Monday. Does it sound reasonable for making it to release 3.2 branch?

**Comment by rachelmcr** [comment]
Yep, Monday would be great! Thank you :)

**Comment by jaclync** [comment]
Closing the issue, the PR wasn't targeting `develop` before
