### ISSUE TITLE
Products: Deleted products aren't removed from product list

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1574]
**Describe the bug**

When I delete a product from my store, and pull to refresh the product list in the app, the deleted product isn't removed from the list.

**To Reproduce**
1. In the app, enable the Products experimental feature.
2. Open the Products tab to load your products list.
3. In WP Admin on the web, go to Products and delete a product from your store.
4. In the app, pull to refresh the products list. The deleted product is still there.
5. Optional: Add a new product to your store and then pull to refresh the products list. The new product is listed but the deleted product is still there.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.2.3
- WooCommerce iOS version: 3.2.0.1

**Comment by pmusolino** [comment]
closing manually, the PR wasn't targeting `develop`
