### ISSUE TITLE
Product List: Wrong message shown with empty search results

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1583]
**Describe the bug**

When a product search returns no results, it currently says "No products yet."

Kylea confirmed that per the designs this message should say "No Products found" when there are no search results.

**To Reproduce**
1. Go to the Products section (enabled under Settings > Experimental Features if needed).
2. Select the search icon.
3. Enter a search that has no results.
4. Note what message is shown when there are no search results.

**Screenshots**

![image](https://user-images.githubusercontent.com/8658164/70434124-42aaa280-1a7b-11ea-8cf6-6a2a7bc3aed2.png)

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.2.3
- WooCommerce iOS version: 3.2.0.1

cc @jaclync

**Comment by astralbodies** [comment]
@jaclync Is this closed now?

**Comment by jaclync** [comment]
ah yes, the issue wasn't closed by the PR because it wasn't targeting `develop`. closing
