### ISSUE TITLE
Product List: Use disclosure indicators for each product in the list

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1599]
**Is your feature request related to a problem? Please describe.**

Raised in beta testing:

> Should there be arrows here to show I can tap through?

![image](https://user-images.githubusercontent.com/8658164/70524329-d2fcec00-1b3c-11ea-8b6c-b266f4df77c4.png)

**Describe the solution you'd like**

From @kyleaparker:

> I don’t think the arrows are _necessary_ but also wouldn’t hurt to add them 🙂

From @astralbodies:

> I’d agree that disclosure indicators on iOS would be the right hint for them being tappable.

**Additional context**

Beta tested with 3.2 TestFlight beta
Internal ref: p5T066-16F-p2/#comment-3979

**Comment by astralbodies** [comment]
Thanks for logging this @rachelmcr and @pmusolino for a quick implementation!
