### ISSUE TITLE
Orders tab: research using `tabbaritem.badgeValue`

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1601]
**Is your feature request related to a problem? Please describe.**
We use a custom solution. We've had numerous PRs trying to position the badge, adjust the font size, and modify the color. The border and border width have also been a problem.

**Describe the solution you'd like**
I would like to research and find out: Why we aren't using `tabbaritem.badgeValue` for the new order count on the Orders tab? It's marked as a [Legacy Customization](https://developer.apple.com/documentation/uikit/uitabbaritem/legacy_customizations) by Apple, but that is not the same as deprecating the API. When checking Xcode's API documentation, the `badgeValue` is marked as available since iOS 2.0, but (importantly) is not marked as deprecated.

**Describe alternatives you've considered**
We are using an alternative right now. 

**Additional context**
I have put together a draft PR that can be tested for the proposed changes. Here are some quick example screenshots using the `UITabBarItem`'s `badgeValue` property on iPhone 11 Pro Max:

<img src="https://user-images.githubusercontent.com/1062444/70554152-3d645b00-1b42-11ea-8512-c640d79dc132.png" width="350" />

<img src="https://user-images.githubusercontent.com/1062444/70554175-481ef000-1b42-11ea-8c27-e604963226d9.png" width="600" />

cc: @ctarda and @kyleaparker, who also worked on the orders tab badge

**Comment by pmusolino** [comment]
This is interesting, and I think that potentially, this can solve also this issue https://github.com/woocommerce/woocommerce-ios/issues/1576
