### ISSUE TITLE
Mitigate 5-second timeout issue with Jetpack tunnel requests

### ISSUE THREAD

**Issue by aforcier** [woocommerce/woocommerce-ios#161]
The requests to the Jetpack tunnel have a 5 second timeout, which is occasionally tripped for certain endpoints (/product/s especially) and/or when multiple requests are made at once. Where possible we should account for this, identifying the timeout error retrying (where the request is safe) or verifying the server state in case it's not.

Android counterpart: https://github.com/woocommerce/woocommerce-android/issues/204

**Comment by shiki** [comment]
@astralbodies Considering that the timeout is now 30 seconds (p91TBi-2vx-p2), do you think we should close this issue?

**Comment by astralbodies** [comment]
Thanks @shiki - I'm closing this for now. The proxy is now 30 seconds long which should help us out a great deal. In fact it's been like that since April 2019 and I haven't seen a ton of reports of failed requests.
