### ISSUE TITLE
Checking for v4 revenue stats availability should check for v0.23 of the WooCommerce Admin plugin

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-ios#1611]
In #1609 we implemented a hotfix to handle breaking changes in the v0.23 release of the WooCommerce Admin plugin, but I believe we're not taking the plugin version into account when we check if the v4 revenue stats are available.

Related to this, if the v4 stats aren't available we show a message stating, "We have reverted to the old stats. To use the beta stats, please activate the WooCommerce Admin plugin with version 0.22 or higher." We just change that to 0.23.

**Comment by shiki** [comment]
This was already achieved in #2467.
