### ISSUE TITLE
Order Details: Undo after fulfilling the order requires a pull to refresh

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1614]
**Describe the bug**

If you fulfill an order and then undo it, the status changes from `Completed` to `Processing` immediately, but the "Begin Fulfillment" button doesn't reappear until you pull to refresh the screen.

This feels like a minor issue but the inconsistency between elements on the screen made me notice it.

**To Reproduce**

1. Open an order in the app.
2. Select "Begin Fulfillment."
3. Select "Mark Order Complete."
4. On the "Order marked as fulfilled" notice, select "Undo."
5. Notice that the status changes from `Completed` to `Processing` but the Product section doesn't change.
6. Pull to refresh the screen and notice that the "Begin Fulfillment" button reappears.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/70717151-afc17080-1ce5-11ea-8c66-0394ec046f6f.gif" width="50%">

**Expected behavior**

I expect everything on that screen to refresh at the same time after performing the Undo action.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.2.3
- WooCommerce iOS version: 3.2.0.3 beta

**Comment by rachelmcr** [comment]
I should also note that I'm fairly sure this isn't new behavior, only that I didn't see it until now.

**Comment by pmusolino** [comment]
Fixed and closing it manually (since we merged the fix in the branch release 3.2.1)
