### ISSUE TITLE
Order Details: New order note doesn't appear until pull to refresh

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1615]
**Describe the bug**

If you add a new order note in the app, it doesn't appear in the Order Notes section until you pull to refresh the screen.

**To Reproduce**

1. Open an order in the app.
2. Scroll down to "Order Notes" and select "Add a note."
3. Enter some text in the note and tap "Add" to finish.
4. Notice that the note does not appear in the Order Notes section.
5. Pull to refresh and notice that the note appears.

**Expected behavior**

I expect the note to appear right away after I add it to the order.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.2.3
- WooCommerce iOS version: 3.2.0.3 beta (although I doubt it is new in this release)

**Comment by pmusolino** [comment]
Fixed and closing it manually (since we merged the fix in the branch release 3.2.1)
