### ISSUE TITLE
Order Notes > Add a Note: note icon doesn't change colors

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1618]
**Describe the bug**
Order Notes > Add a Note. When activating the "Email note to customer" switch, it used to change the note icon in the "Write Note" text area from gray to blue. 

**To Reproduce**
1. Orders tab > Choose an Order > scroll down to Order Notes > Add a Note
2. Turn on "email note to customer option"

**Screenshots**
<img src="https://user-images.githubusercontent.com/1062444/70739171-dbd7f400-1cdb-11ea-9de7-457b01253393.jpg" width="350" />

**Expected behavior**
The note icon should change to the brand color (`.primary`)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: 13.0+ 
- WooCommerce iOS version: 3.2.0.3

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by leonardodamato** [comment]
I am doing that

**Comment by pmusolino** [comment]
Thanks for taking care of it @leonardodamato 👍
