### ISSUE TITLE
Reviews badge appears on the Products tab if turning on the Products tab earlier in the same app session

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1639]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
- Make sure the Products tab is not visible before launching the app
- Launch the app
- Go to Settings > Experimental Features and turn on the Products tab
- On web, leave a review to a Product
- Back in the app, wait for the badge dot to appear --> it appears on the Products tab instead of the Reviews tab

**Screenshots**
![IMG_9730](https://user-images.githubusercontent.com/1945542/71058839-08888180-219c-11ea-9fdf-28bb1abd5b69.PNG)

**Expected behavior**
The badge for new reviews should appear on the Reviews tab.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XR
- iOS version: 13.3
- WooCommerce iOS version: 3.3

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by shiki** [comment]
@pmusolino @jaclync Do you think this is still a problem? The Products tab is always visible now. Should we close this?

**Comment by pmusolino** [comment]
This is no more an issue from my tests 👍 I'm going to close it.
