### ISSUE TITLE
Product Details: "View product" cuts off when dynamic text is large

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1643]
**Describe the bug**
The "View product" cell cuts off the text in the largest dynamic text setting.

**To Reproduce**
0. In the My Store > Settings > Experimental Features, turn on Products.
1. Settings > Accessibility > Display & Text Size > Larger Text. Turn it on and move the size to the largest setting.
2. Navigate back to the Woo app. 
3. Go to Products > Choose a product to view the Product Details. Scroll down to the "View product" cell. 
4. See screenshot

**Screenshots**
<img src="https://user-images.githubusercontent.com/1062444/71103836-6c9d4c80-2180-11ea-83aa-356370bd913b.PNG" width="350" />

**Expected behavior**
The "View products" text wraps in the cell 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: any 
- WooCommerce iOS version: v3.3.0

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by shiki** [comment]
It looks like this is now fixed. 

<img src="https://user-images.githubusercontent.com/198826/76570320-b7c2b500-647a-11ea-85de-03b372d58886.png" width="320">
