### ISSUE TITLE
Update empty state in shipping classes screen (paginated list view)

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1653]
From the feedback here: https://github.com/woocommerce/woocommerce-ios/pull/1633#pullrequestreview-334824485

Let's add the illustration when there no shipping classes to select from. The current screen looks like:
<img src="https://user-images.githubusercontent.com/1062444/71200705-29191000-225e-11ea-8889-244cca5409e0.png" width="350" />

@kyleaparker do you think we can use the empty products illustration is good for the empty shipping classes screen?
<img width="405" alt="Screen Shot 2019-12-19 at 12 50 01 PM" src="https://user-images.githubusercontent.com/1062444/71200736-3504d200-225e-11ea-8da9-2f18063fe074.png">

**Comment by kyleaparker** [comment]
We can probably use the gridicons-shipping icon for this screen instead
