### ISSUE TITLE
Edit Product: analytics

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1675]
More to be added

thanks @anitaa1990 for defining the events ahead of iOS! (https://github.com/woocommerce/woocommerce-android/pull/1638)

event name | trigger | properties
-- | -- | --
PRODUCT_DETAIL_UPDATE_BUTTON_TAPPED | User tapped on the Update menu button in the Product Detail screen. | n/a
PRODUCT_DETAIL_UPDATE_SUCCESS | The request submitted to update a product to the API was successful. | n/a
PRODUCT_DETAIL_UPDATE_ERROR | The request submitted to update a product to the API has failed. | n/a
product_detail_view_product_name_tapped | User tapped on the product name field in the Product Detail screen | n/a
product_detail_view_product_description_tapped | User tapped on the product description field in the Product Detail screen. | n/a
product_detail_view_price_settings_tapped | User tapped on the price settings row in the Product Detail screen | n/a
product_detail_view_shipping_settings_tapped | User tapped on the shipping settings row in the Product Detail screen | n/a
product_detail_view_inventory_settings_tapped | User tapped on the inventory settings row in the Product Detail screen | n/a
product_name_done_button_tapped | User tapped on the Done menu button in the edit product name screen | `has_changed_data`: a boolean that indicates whether the user has changed the product name
aztec_editor_done_button_tapped | User tapped on the Done menu button in the Aztec editor screen. | n/a
product_description_done_button_tapped | User tapped on the Done menu button in the Aztec editor screen. | `has_changed_data`: a boolean that indicates whether the user has changed the product description
product_price_settings_done_button_tapped | User tapped on the Done menu button in the product price settings screen | `has_changed_data`: a boolean that indicates whether the user has changed any fields on the screen
product_shipping_settings_done_button_tapped | User tapped on the Done menu button in the product shipping settings screen | `has_changed_data`: a boolean that indicates whether the user has changed any fields on the screen
product_inventory_settings_done_button_tapped | User tapped on the Done menu button in the product inventory settings screen | `has_changed_data`: a boolean that indicates whether the user has changed any fields on the screen

**Comment by pmusolino** [comment]
Do we need to add also some events when a user open some settings screens, like Edit Price, Edit Shipping, Edit Inventory, etc...?

**Comment by jaclync** [comment]
Other events (also updated the issue description):

event name | trigger
-- | --
product_detail_view_product_name_tapped | User tapped on the product name field in the Product Detail screen
product_detail_view_price_settings_tapped | User tapped on the price settings row in the Product Detail screen
product_detail_view_shipping_settings_tapped | User tapped on the shipping settings row in the Product Detail screen
product_detail_view_inventory_settings_tapped | User tapped on the inventory settings row in the Product Detail screen
product_name_done_button_tapped | User tapped on the Done menu button in the edit product name screen
product_price_settings_done_button_tapped | User tapped on the Done menu button in the product price settings screen
product_shipping_settings_done_button_tapped | User tapped on the Done menu button in the product shipping settings screen
product_inventory_settings_done_button_tapped | User tapped on the Done menu button in the product inventory settings screen

**Comment by pmusolino** [comment]
Thanks for updating it @jaclync!
