### ISSUE TITLE
Edit Products: update WIP banner message

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1678]
Since Edit Product only supports simple Products for release 1, let's update the message of the WIP banner to notify users about the features in release 1 and that we are working on support for other Product types

**Comment by pmusolino** [comment]
What is expected to show the new message? I wasn't able to find more information on this 😃

**Comment by astralbodies** [comment]
Hey @kyleaparker what were your thoughts around this banner for when we go live with M1? We may also make M1 features available for a sprint or two behind the switch for early adopters to experiment with before we turn it on for everyone.

**Comment by kyleaparker** [comment]
If we are planning to launch the currently read only list + read only product details to everyone, we will update the current message to: 

Title: Work in progress!
Body: We’re hard at work on this new Products section, so you may see some changes as we add more features 🚀

For the M1 which will be behind the switch, we will modify the above message to be: 

Title: Limited editing available
Body: We’ve added editing functionality to simple products. Keep an eye out for editing on other product types soon

We will also want to update the copy on the products switch (in settings) to read: 

Title: Product editing
Body: Test out the new product editing functionality as we get ready to launch

cc @Garance91540
