### ISSUE TITLE
Wrong button position in Login flow on small screen devices

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#1680]
On small screens, like on iPhone 5s, the **Next** button in the login flow goes under another button **Enter the address of the Wordpress** (which is truncated) when the keyboard is opened.

## To Reproduce
1) Launch the app on a small screen device (like iPhone 5s)
2) Try to log in with your wordpress.com account
3) When you try to type your email address, you can see the overlapping buttons.

## Screenshots
![Simulator Screen Shot - iPhone 5s - 2019-12-30 at 11 18 16](https://user-images.githubusercontent.com/495617/71578131-3607f000-2af7-11ea-9c66-6d94ea1d5e4c.png)

## Mobile Environment
- Device: iPhone 5S
- iOS version: 12.2
- WooCommerce iOS version: 3.3

**Comment by itsmeichigo** [comment]
Closing this issue because the UI has changed and there's no Next button on top of the keyboard:
<img src="https://user-images.githubusercontent.com/5533851/156497798-97ca85d5-999a-41ac-909e-04ce80d0ccde.png" width=320 />
