### ISSUE TITLE
Autolayout warning on action sheet when the order list filters are displayed

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#1685]
Xcode prints some autolayout warnings in the console log, when the order list filters action sheet is displayed.

## Console log
```
2019-12-30 20:44:10.950855+0100 WooCommerce[22548:1635163] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600000527e80 UIView:0x7fad6a446dd0.width == - 16   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600000527e80 UIView:0x7fad6a446dd0.width == - 16   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```

## Screenshots
![Simulator Screen Shot - iPhone 11 Pro - 2019-12-30 at 20 44 15](https://user-images.githubusercontent.com/495617/71598126-f7e5ed00-2b45-11ea-9355-07f548f3888d.png)

## Mobile Environment
Please include:
- Device: Simulator iPhone 11 Pro
- iOS version: 13.2.2
- WooCommerce iOS version: 3.3

**Comment by pmusolino** [comment]
Searching for a solution, I discovered that it's a new bug in iOS versions:

- 12.2
- 12.3
- 12.4
- 13.0
- 13.1
- 13.2
- 13.2.3
- 13.3

**Comment by eshurakov** [comment]
Closing this as the filter is moved to Search and not causing auto layout issues anymore.
