### ISSUE TITLE
Product image upload

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1713]
Spike in p99K0U-1Xg-p2
Spike branch https://github.com/woocommerce/woocommerce-ios/compare/spike/media-library?expand=1

- [x] Product Images UI: ProductImagesCollectionViewController + ColumnFlowLayout + ProductImagesViewController https://github.com/woocommerce/woocommerce-ios/pull/1714
- [x] show a fullscreen image with action to delete an image https://github.com/woocommerce/woocommerce-ios/pull/1727
- [x] fix the order of Product images (requires schema migration) https://github.com/woocommerce/woocommerce-ios/pull/1726
- [x] update Product images remotely https://github.com/woocommerce/woocommerce-ios/pull/1723
- [x] Media picking action sheet https://github.com/woocommerce/woocommerce-ios/pull/1743
- [x] Photo library: DeviceMediaLibraryPicker https://github.com/woocommerce/woocommerce-ios/pull/1744
- [x] Camera capture: CameraCaptureCoordinator https://github.com/woocommerce/woocommerce-ios/pull/1744
- [x] Media remote: upload media https://github.com/woocommerce/woocommerce-ios/pull/1760
- [x] Export image assets to local file system https://github.com/woocommerce/woocommerce-ios/pull/1767
- [x] Support images that don't have the allowed file extensions (e.g. HEIC from iOS devices) https://github.com/woocommerce/woocommerce-ios/pull/1776
- [x] MediaStore: upload images https://github.com/woocommerce/woocommerce-ios/pull/1788
- [x] UI (Product image loading state) and integration with `MediaStore` https://github.com/woocommerce/woocommerce-ios/pull/1800
- [x] Use the asset image to prevent unnecessary image downloads after an asset is uploaded to a remote Product image https://github.com/woocommerce/woocommerce-ios/pull/1878
- [x] `ProductImagesViewController` and related classes were retained after leaving Edit Product screen https://github.com/woocommerce/woocommerce-ios/pull/1877
- [x] The spinner stops after backgrounding the app https://github.com/woocommerce/woocommerce-ios/pull/1882
- [x] Thread safety for image statuses in `ProductImagesService`: https://github.com/woocommerce/woocommerce-ios/pull/1878#discussion_r384614471 https://github.com/woocommerce/woocommerce-ios/pull/2135
- [x] Allow an image request to be cancelled when used in a reusable cell: https://github.com/woocommerce/woocommerce-ios/pull/1878#discussion_r384647905 https://github.com/woocommerce/woocommerce-ios/pull/2114
- [x] Rename `ProductImagesProvider` to `ProductUIImageLoader`: https://github.com/woocommerce/woocommerce-ios/pull/1878#discussion_r384657276 https://github.com/woocommerce/woocommerce-ios/pull/1914
- [x] Refactor `ProductImagesService`:
  - [x] Rename to `ProductImageActionHandler`  https://github.com/woocommerce/woocommerce-ios/pull/1878#discussion_r385043246 https://github.com/woocommerce/woocommerce-ios/pull/1914
  - [x] add back test case when an asset is uploaded
- [x] Fix images header scrolling back on image status changes: https://github.com/woocommerce/woocommerce-ios/pull/1878#discussion_r384669536 https://github.com/woocommerce/woocommerce-ios/pull/2144
- [x] Collection view layout warnings (iPhone 11 Pro (simulator) with iOS 13.2.2): https://github.com/woocommerce/woocommerce-ios/pull/1714#pullrequestreview-340526979 https://github.com/woocommerce/woocommerce-ios/pull/1916
- [x] The app shouldn't request Photos permission when opening Edit Product for the first time (reproducible on iOS 12.1) https://github.com/woocommerce/woocommerce-ios/pull/2127
- [x] Update the media POST endpoint to 1.1 https://github.com/woocommerce/woocommerce-ios/pull/2075

Update UX as in p99K0U-2mN-p2#comment-4732:
- [x] If the user taps “Done” while some images are still being uploaded, we will keep track of the images that are in-progress, display the in-progress UI (blurred image + circle spinner) for these images on the Edit Product screen, and then update the UI for these images once they are uploaded. https://github.com/woocommerce/woocommerce-ios/pull/1878
  - [x] When the user taps “Update” on the Edit Product screen, we first show the in-progress UI, wait for all images to be uploaded and then update the Product remotely. https://github.com/woocommerce/woocommerce-ios/pull/2126
  - [x] When the user navigates away from the Edit Product screen, no changes are made to the Product and these images keep being uploaded in the background. https://github.com/woocommerce/woocommerce-ios/pull/2126
- [x] If the user navigates away from the Edit Product Images screen while some images are still being uploaded, these images keep being uploaded in the background but they won’t be added to the Product. https://github.com/woocommerce/woocommerce-ios/pull/2126

**Comment by shiki** [comment]
Moving this out of the Kanban board which will soon be archived. 🙂

**Comment by jaclync** [comment]
closing now that all the subtasks are done! can open new issues for bugs
