### ISSUE TITLE
Order Details: lag in Shipping Address when loading an order

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1734]
Not sure if it's a bug or an optimization that needs made. After introducing PR #1720 into develop, there has been a significant lag in drawing in the Shipping Address table cell. 

It might be faster to check for physical products in the products array rather than verifying that all products are virtual. (Not sure yet, theory untested).

![shipping-address-lag](https://user-images.githubusercontent.com/1062444/72480197-332a2200-37bc-11ea-98bf-03a9e8f3d5d7.gif)

**Comment by pmusolino** [comment]
It doesn't seem to happen anymore. Closing it 👍
