### ISSUE TITLE
Product List: Product list does not load correctly after Google login until app is relaunched.

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1737]
**Describe the bug**

After logging in to the app with Google, the product list (on the Products tab) does not load until you pull to refresh. (This persists even if you log out and log in using another method.)

Also, if you switch stores, the product list does not switch until you pull to refresh or until the app is force closed and relaunched. (After relaunching the app, the product list works as expected consistently.)

**To Reproduce**
1. Log out of the app.
2. Log in to the app using Google.
3. If the Products tab isn't visible, go to Settings > Experimental Features and enable Products.
4. Tap the Products tab.
5. Notice the "Work in Progress!" banner is visible but the product list (or the empty state illustration/message) is not visible.
6. Pull to refresh, and notice that the product list loads.
7. Switch stores in the app.
8. Go to the Products tab again and notice that the wrong store's product list appears.
9. Pull to refresh, and notice that the correct product list loads.
10. Force close the app.
11. Relaunch the app and notice that the product list now loads correctly every time.

**Screenshots**

Products tab immediately after logging in to the app, on a store with products:

<img src="https://user-images.githubusercontent.com/8658164/72541662-d3468080-387a-11ea-88f1-a94cd70bfe81.png" width="50%">

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.3
- WooCommerce iOS version: 3.4.0.0 TestFlight build

**Comment by jaclync** [comment]
I got to reproduce this by first logging into a store, logging out, and then logging into the same store - my guess is that there are some issues for `ProductsViewController` to update the data source after logging out and in to the same store, and the following store switch (e.g. `StoresManagerDidUpdateDefaultSite` notification)
