### ISSUE TITLE
Support: Can't enter name/email to contact support during login

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1738]
**Describe the bug**

When I try to contact support during login, after I enter my email address and name the "OK" button never enables so I can't continue.

I tried multiple names and email addresses (including emails with no special characters) but reproduced the same issue each time.

**To Reproduce**
1. Log out of the app.
2. Select "Log in with Jetpack" to start logging in.
3. Tap "Help" in the top right.
4. On the Help scree, tap "Contact Support."
5. In the window that pops up, enter your email address and name.
6. Try tapping "OK" to continue but notice that it is not enabled.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/72544599-93ce6300-387f-11ea-9892-9c4410fe5873.png" width="50%">

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.3
- WooCommerce iOS version: 3.4.0.0 TestFlight build

**Comment by jaclync** [comment]
Should be fixed by https://github.com/woocommerce/woocommerce-ios/pull/1741 targeting release 3.4, closing now
