### ISSUE TITLE
Localize the quote icon

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1739]
**Is your feature request related to a problem? Please describe.**
Different languages have different quote delimiters. In Order Details we represent Customer Notes with the [Quote Gridicon](http://automattic.github.io/gridicons/) (`gridicons-quote`). This is English-centric and makes our app stand out as foreign.

<img src="https://user-images.githubusercontent.com/1062444/72549659-b8faab80-3856-11ea-93a1-b8ccd1dbd12f.png" width="350" />

<img src="https://user-images.githubusercontent.com/1062444/72549667-bd26c900-3856-11ea-96a0-88a21405b97c.png" width="350" />

**Describe the solution you'd like**
Remove the Gridicon and use the text-based quote. Make sure it's a localized string and a large enough font size that it looks like a Gridicon.

**Describe alternatives you've considered**
We could add more quote icons to the Gridicons library, since it's used by an international audience. It might be a high effort / low reward endeavor, because designers would need to create the new icons and developers would have to create an enum or other method to switch between the icons.

**Additional context**
See also this excellent discussion of [Locale](https://nshipster.com/locale/) on NSHipster.

**Comment by ealeksandrov** [comment]
We don't have quote icon for customer note now, instead adding quotes around note string (that can be localized):

https://github.com/woocommerce/woocommerce-ios/blob/a17039d1918f6751da0c0f9d3969ed314735d4bb/WooCommerce/Classes/ViewModels/Order%20Details/OrderDetailsDataSource.swift#L379-L382

<img width=350 src="https://user-images.githubusercontent.com/3132438/144443566-894fbdb7-3f6e-48c7-b88d-447faac5f3d9.png">

But we still have same icon on "reason for refund" field in refunded order details:

<img width=350 src="https://user-images.githubusercontent.com/3132438/144444746-cf5a9981-8d2e-47dc-934c-fd4892043c4d.png">
