### ISSUE TITLE
Improvements to NoticePresenter for cancelling a notice in the queue

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#1752]
We have some cases in the app, where we use the NoticePresenter to show some local errors.
The ideal would be to give the possibility to delete some Notices in the queue or prevent to add a notice more than one time if it is already in the queue.

**One case where can be useful:**
In _Products > Edit Product > Edit Price_ if you try to insert a sale price higher than the regular price, and you press save, we show an error notice. If you press saves more than one time, you will see a lot of similar Notices.

**Comment by shiki** [comment]
WPiOS handles this by using a [`NoticeStore`](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Stores/NoticeStore.swift) which acts as the data layer for notices. The complexity of canceling and queueing is hidden inside it.
