### ISSUE TITLE
Order Details → Pending payment status gets clipped on iPhone 11 Pro Max

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#1761]
**Describe the bug**

Related to #1061. Found in #1755.

When using iPhone 11 Pro Max, the word “Pending payment” gets clipped.  

**To Reproduce**

1. Set the phone's font size to the largest size available
2. Navigate to an Order with “Pending payment” status.
3. Observe the status being clipped.

As shown in the screenshots below, if the text is longer, the text does not get clipped. 

**Screenshots**

Clipped ❌  | Okay ✅  | Okay ✅ 
--------|-------|--
<img width="584" alt="iphone-pro-2" src="https://user-images.githubusercontent.com/198826/72897382-140d2200-3cdf-11ea-82fe-e245091edd61.png"> |<img width="584" alt="pending-payments" src="https://user-images.githubusercontent.com/198826/72897401-1e2f2080-3cdf-11ea-9332-891afcb3e80a.png">|<img width="584" alt="iphone-11-pro-max" src="https://user-images.githubusercontent.com/198826/72897405-20917a80-3cdf-11ea-912c-7e9003487833.png">   

**Expected behavior**

The text should not get clipped.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**

- Device: iPhone Simulator → 11 Pro Max
- iOS version: 13.1
- WooCommerce iOS version: b01540da2aaf083978e18c0a2065d947f13c97ab

**Comment by shiki** [comment]
This is still valid in latest `develop` (085a2e8).

**Comment by Ecarrion** [comment]
<img width="381" alt="Screen Shot 2021-08-13 at 7 16 03 PM" src="https://user-images.githubusercontent.com/562080/129428613-bd16e560-8031-4f8a-89c8-16849595071d.png">

This does not seem to be a problem anymore.
