### ISSUE TITLE
Bug: Clicking new order notification opens reviews tab

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-ios#1782]
Received a report that when clicking on a new order notification the app will load the reviews tab instead of the order detail.

**Comment by rachelmcr** [comment]
Version 3.4 was just released this week with a fix for this issue (https://github.com/woocommerce/woocommerce-ios/pull/1664). Could the reporter update to 3.4 and confirm whether they're still seeing any issue with this?

**Comment by rachelmcr** [comment]
Since there was a fix that should have resolved this issue, and we haven't received any new reports/seen this issue again in our own testing, I'm going to close this issue as presumably resolved. Please reopen if you think there's more to be investigated here.
