### ISSUE TITLE
Product Shipping Settings: handle zero values on width and dimensions textfields

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#1785]
Currently, we always show zero `0` when a field is empty on the web, which is a wrong information.
The ideal would be to be able to handle this case and maybe show a placeholder that shows zero.

![Simulator Screen Shot - iPhone 11 Pro - 2020-01-28 at 11 14 23](https://user-images.githubusercontent.com/495617/73255858-38766c00-41c1-11ea-8cdc-b887dcf7eb55.png)

**Comment by leonardodamato** [comment]
Hi @pmusolino. 

This cells you mentioned are configured to use a "Reusable View", so its class is also applied for other cells such as: 
Product > Price
Product > Sale Price
Product > (turn on 'manage stock') >Quantity.

Should we change the current class and apply this change to all these fields above? Or create another class to apply only to the Shipping Settings cell?

Unless there is a different way to solve it :)

**Comment by pmusolino** [comment]
Hi @leonardodamato. I'm so sorry, I forgot to assign this issue to me because I already started to work on it 😉

**Comment by leonardodamato** [comment]
Oh, awesome, @pmusolino! Will have look at the other ones :)
