### ISSUE TITLE
Dashboard: Navbar text color changes to black (in light mode) after opening support tickets

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1793]
**Describe the bug**

After opening My Tickets in Help & Support, the navbar text color for the entire My store section (including Settings) changes color from white to black (in light mode).

**To Reproduce**
1. Set your device to light mode. (This issue can be triggered in dark mode, but it's only visible in light mode.)
2. Log in to the app.
3. Open My store > Settings > Help & Support and note that up to now the navbar text is white.
4. In the Help section, open My Tickets. Notice that the navbar text is black.
5. Go back and notice that now every screen in the My store tab and Settings has black navbar text.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/73356344-0f71dc00-4292-11ea-8d5c-c0fc2f4d4735.png" width="50%">

<img src="https://user-images.githubusercontent.com/8658164/73356369-1dbff800-4292-11ea-91a3-fc97fdd84b40.png" width="50%">

<img src="https://user-images.githubusercontent.com/8658164/73356393-2b757d80-4292-11ea-87b4-8265cd506fae.png" width="50%">

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.3
- WooCommerce iOS version: 3.5.0.0 TestFlight beta

**Comment by shiki** [comment]
This is the same as #1513. I'm going to close this in favor of that.
