### ISSUE TITLE
Edit Product: analytics when the user changes individual fields in price/inventory/shipping settings

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1797]
### Inventory settings screen

event name | trigger | properties
-- | -- | --
product_inventory_settings_sku_updated | User updated the SKU field in the product inventory settings screen | n/a
product_inventory_settings_manage_stock_updated | User updated the "Manage stock" switch in the product inventory settings screen | n/a
product_inventory_settings_stock_quantity_updated | User updated the stock quantity field in the product inventory settings screen | n/a
product_inventory_settings_backorders_updated | User updated the backorders field in the product inventory settings screen | n/a
product_inventory_settings_sold_individually_updated | User updated the "Limit one per order" field in the product inventory settings screen | n/a
product_inventory_settings_stock_status_updated | User updated the stock status field in the product inventory settings screen | n/a

### Price settings screen

event name | trigger | properties
-- | -- | --
product_price_settings_regular_price_updated | User updated the regular price field in the product price settings screen | n/a
product_price_settings_sale_price_updated | User updated the sale price field in the product price settings screen | n/a
product_price_settings_schedule_sale_toggled | User toggled the schedule sale field in the product price settings screen | n/a
product_price_settings_sale_start_date_updated | User updated the sale start date field in the product price settings screen | n/a
product_price_settings_sale_end_date_updated | User updated the sale end date field in the product price settings screen | n/a
product_price_settings_tax_status_updated | User updated the tax status field in the product price settings screen | n/a
product_price_settings_tax_class_updated | User updated the tax class field in the product price settings screen | n/a

### Shipping settings screen

event name | trigger | properties
-- | -- | --
product_shipping_settings_weight_updated | User updated the weight field in the product shipping settings screen | n/a
product_shipping_settings_length_updated | User updated the length field in the product shipping settings screen | n/a
product_shipping_settings_width_updated | User updated the width field in the product shipping settings screen | n/a
product_shipping_settings_height_updated | User updated the height field in the product shipping settings screen | n/a
product_shipping_settings_shipping_class_updated | User updated the shipping class field in the product shipping settings screen | n/a

**Comment by pmusolino** [comment]
Do we want to include these events in the product release 1? @astralbodies @jaclync

**Comment by jaclync** [comment]
I think it'd be nice to track these for us to understand which fields are edited more often, which could be useful for future prioritization 🙂

**Comment by jaclync** [comment]
@astralbodies I'm closing this based on a discussion from an earlier team meeting (the Kindle example), feel free to reopen/comment if you think it's worth working on
