### ISSUE TITLE
Login: Site URL disappears when keyboard appears

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-ios#1807]
**Describe the bug**
When logging in by URL to start the URL disappears above the username field when the keyboard appears.

**To Reproduce**
1. Launch the app.
2. Tap continue.
3. Tap sign in with URL to start.
4. Enter a valid Woo/JP url.
5. Tap next. Tap into the username field.

**Screenshots**
![IMG_0002](https://user-images.githubusercontent.com/373903/73685388-b5a35480-468b-11ea-85dc-e2f88804eecf.PNG)

**Expected behavior**
The URL should remain on the screen.

**Mobile Environment**
Please include:
- Device: iPhone 6s Plus
- iOS version: 13.1.1
- WooCommerce iOS version: 3.5.0.0 (beta testing it)

**Comment by shiki** [comment]
This is for an old design and does not seem to be valid anymore.
