### ISSUE TITLE
Orders: Product name showing HTML entities instead of being decoded

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-ios#1808]
**Describe the bug**
When a product description contains something commonly escaped in HTML (like an ampersand &) it's showing up as an HTML entity in the order details screen.

**To Reproduce**
1. Place an order with a product containing an ampersand.
2. View the order in the app.

**Screenshots**
![IMG_0004](https://user-images.githubusercontent.com/373903/73686288-4dee0900-468d-11ea-88cf-0cb953684266.PNG)

**Expected behavior**
HTML entities should be decoded before saving to the local db.

**Mobile Environment**
Please include:
- Device: iPhone 6s Plus
- iOS version: 13.1.1
- WooCommerce iOS version: 3.5.0

**Comment by pmusolino** [comment]
It's strange, I'm not able to reproduce the bug on release 3.5.

![unable to reproduce](https://user-images.githubusercontent.com/495617/73743300-7d187f00-474e-11ea-83b0-d25952c8b797.png)

**Comment by astralbodies** [comment]
@pmusolino Can you confirm that the API is returning something like `Yellow Pants (H&amp;M)` in the call for that product on your test site?

**Comment by pmusolino** [comment]
The API is returning me:
`"name" : "woo ninja - h&m"`

**Comment by jaclync** [comment]
Other than the Order Item's name, I think it's worth decoding the Product name for Edit Product UI as well because we use a plain text field for Product name field
