### ISSUE TITLE
Public note showing strange characters near time field

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-ios#1809]
**Describe the bug**
When adding a public note on an order I'm seeing some strange characters near the date/time field.

**To Reproduce**
1. Find an order.
2. Add a public note for the customer.

**Screenshots**
![IMG_0005](https://user-images.githubusercontent.com/373903/73686700-1d5a9f00-468e-11ea-8079-c3ea54ca99a4.PNG)

**Expected behavior**
The date shouldn't contain those characters.

**Mobile Environment**
Please include:
- Device: iPhone 6s Plus
- iOS version: 13.1.1
- WooCommerce iOS version: 3.5.0.0

**Comment by pmusolino** [comment]
Fixed here https://github.com/woocommerce/woocommerce-ios/pull/1811
