### ISSUE TITLE
On tapping Review push notification, two same API requests are made to fetch the first page of Product Reviews

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1812]
- Go to the Reviews tab
- Background the app
- Leave a product review on web to receive a push notification
- Tap the push notification to open the app

Two of the same API requests are made [when presenting the review details](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/ViewRelated/Notifications/ReviewsViewController.swift#L135-L136). Let's make sure only one is made (probably can remove https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/ViewRelated/Notifications/ReviewsViewController.swift#L135).

**Comment by shiki** [comment]
@jaclync If I understand the description correctly, we can close this because of the changes in #2669. Is that correct?

**Comment by jaclync** [comment]
yes, this doesn't look like an issue anymore! thanks for circling back to this issue, closing now
