### ISSUE TITLE
Product Variations: the loading state looks a bit odd in Dark Mode

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1813]
**Describe the bug**
In Dark Mode, the Product Variations screen loading state doesn't look as expected.

**To Reproduce**

Prerequisite: the device is in Dark Mode

- Go to the Products tab
- Tap on a Variable Product
- Tap on the Product Variations row

Expected: the cells in the loading state should flash
Actual: the cells in the loading state remain the same color with a rectangle in the accessory view

**Screenshots**
<img src="https://user-images.githubusercontent.com/1945542/73718487-a2f65180-4757-11ea-939c-1a3121e9a6fc.jpeg" width="320" />

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XR
- iOS version: iOS 13.3.1
- WooCommerce iOS version: 3.5.0.0

**Comment by pmusolino** [comment]
I ran into the same bug, but I noticed that it also happens in Light mode, and I noticed that it only occurs during the first loading. If you try to pull-refresh, the problem no longer occurs.
