### ISSUE TITLE
Edit Product: add the Product Settings screen

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#1821]
Since the new Edit Product will allow users to add some extra settings, we need to implement a new **Product Settings screen**, which will be shown after pressing the new voice "Product Settings" inside the "more" action sheet https://github.com/woocommerce/woocommerce-ios/issues/1819

To be discussed: will the screen be presented in modal or push mode?

<img width="665" alt="Schermata 2020-02-05 alle 19 08 20" src="https://user-images.githubusercontent.com/495617/73869680-0d3bee80-484b-11ea-973c-79d39496ea36.png">

**Comment by pmusolino** [comment]
cc @kyleaparker @Garance91540: will the screen be presented in modal or push mode? It seems in modal since there is an X on the screen, but I ask just to be sure.

**Comment by kyleaparker** [comment]
I actually think push mode might be better here, what do you think @Garance91540?
