### ISSUE TITLE
[Order Details] Paid By Customer section should be hidden if no date_paid returned

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-ios#1827]
To match Core behavior, let's update the app to show/hide the "Paid by customer" section in order details based on there being a date paid or not. This may already be the case on iOS, but confirm and test with a site.

Core: https://github.com/woocommerce/woocommerce/pull/25504#discussion_r375455622

Verify payment details show up properly when using the "Cash on delivery" option.

cc: @LevinMedia

Android issue: https://github.com/woocommerce/woocommerce-android/issues/1900

**Comment by joshheald** [comment]
Still to be done on iOS, and confirmed in p91TBi-8P0-p2#line-items-in-the-payment-section that we should hide this when there is no `date_paid`.
