### ISSUE TITLE
No way to clear the sale price

### ISSUE THREAD

**Issue by kyleaparker** [woocommerce/woocommerce-ios#1834]
**Describe the bug**
There is currently no way to clear the sale price, it stays at $0. You should be able to remove that last 0 or alternatively grey it out so it's clear the sale price isn't set to $0:

![IMG_4933](https://user-images.githubusercontent.com/712873/73988648-4e96d180-4911-11ea-91b0-9574f7980d60.PNG)

cc @pmusolino

**Comment by jaclync** [comment]
I believe @pmusolino fixed this in https://github.com/woocommerce/woocommerce-ios/pull/1792, I tested on the latest `develop` and was able to clear the price fields - @kyleaparker if you get a chance, maybe you can try the latest build [here](https://install.appcenter.ms/orgs/automattic/apps/WooCommerce-Installable-Builds) (#5971)?

**Comment by pmusolino** [comment]
Hi @kyleaparker. Yes, I fixed it in #1792, maybe you are testing the release 3.5?

**Comment by kyleaparker** [comment]
oops i didn't see that, closing this!
