### ISSUE TITLE
Order Details: navigate to Edit Product when tapping on a simple Product in the Order

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1837]
More context in p99K0U-2iz-p2

When tapping a simple Product from the Order Details, let's navigate to the Edit Product screen with a dismiss button in the left navigation bar:

<img width="385" alt="Screen Shot 2020-02-07 at 1 37 32 PM" src="https://user-images.githubusercontent.com/1945542/74003858-029a6a00-49af-11ea-95a1-60c44c8304e6.png">

**Comment by pmusolino** [comment]
Does this mean that we will present the product screen modally full screen? cc @kyleaparker @Garance91540 
I'm right?

**Comment by kyleaparker** [comment]
It could be either full screen modal or the partial sheet 👍
