### ISSUE TITLE
Refactor each tab view controller to be associated with a constant site ID

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1838]
Currently, each of our tab view controller (`DashboardViewController`, `OrdersMasterViewController`, `ProductsViewController`, `ReviewsViewController`) is created only once per app lifetime. Thus, it has to rely on the default `NotificationCenter` to update its data whenever the site changes from site switcher or logging out and in. We've had bugs like https://github.com/woocommerce/woocommerce-ios/issues/1737 related to the site change notification, and we have many instances of checking `sessionManager.defaultStoreID` for the site ID because the site could change during the class' lifetime.

I think we can start with replacing the tab view controllers whenever the site changes (e.g. on the `defaultAccountWasUpdated` notification). Then we can add a constant site ID to each tab view controller, and replace the usage of `sessionManager.defaultStoreID`.

Prep
- [x] Reviews tab: move VCs away from Storyboard https://github.com/woocommerce/woocommerce-ios/pull/1919
- [x] Dashboard tab: move VCs away from Storyboard https://github.com/woocommerce/woocommerce-ios/pull/2819

DI site ID
- [x] Reviews tab: DI site ID to VCs, and tear down the root VC when the site changes
- [x] Dashboard tab: DI site ID to VCs, and tear down the root VC when the site changes
- [x] Orders tab: DI site ID to VCs, and tear down the root VC when the site changes
- [x] Products tab: DI site ID to VCs, and tear down the root VC when the site changes

**Comment by shiki** [comment]
From @astralbodies 

> Don’t forget to consider the iPad interface and what it looks like if a controller is recreated.

**Comment by jaclync** [comment]
All tabs done now, closing this!
