### ISSUE TITLE
Fulfillment: Tracking

### ISSUE THREAD

**Issue by jleandroperez** [woocommerce/woocommerce-ios#185]
### Details:
Order Fulfillment should allow users to set the Tracking Details. Note that this is not part of Woo Core, but it can be added by means of [this plugin](https://woocommerce.com/products/shipment-tracking).

Also: Make sure to add the Shipping Footer Note details (`"Customer selected expedited shipping"`).

---

### i6 Designs
<img width="1231" alt="screen shot 2018-08-20 at 6 37 25 pm" src="https://user-images.githubusercontent.com/154014/44372134-22cb2600-a4a8-11e8-9baa-071ceb742d1b.png">

**Comment by bummytime** [comment]
Closing this issue in favor of #250
