### ISSUE TITLE
Dashboard: navigate to Edit Product when tapping on a simple Product in the "Top Performer"

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#1850]
When tapping a simple Product in the table view inside **Top Performer** section in the Dashboard, let's navigate to the Edit Product screen with a dismiss button in the left navigation bar.

![Simulator Screen Shot - iPhone 11 Pro - 2020-02-10 at 15 04 47](https://user-images.githubusercontent.com/495617/74156539-cd905080-4c16-11ea-9470-3c9f5aa094fe.png)

**Comment by jaclync** [comment]
this issue https://github.com/woocommerce/woocommerce-ios/issues/1034 might explain some reasons why it hasn't been implemented? it seems like it could be from the table view being inside a horizontal scroll view via `XLPagerTabStrip`, but it's worth revisiting if we could handle the top performers table view cell tap event
