### ISSUE TITLE
Refunds: "Begin Fulfillment" appears as long as order is not fully refunded, even if all products are refunded

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1859]
**Describe the bug**

Even if every product in an order has been refunded, if the order is not fully refunded (e.g. shipping is not yet refunded) the "Begin Fulfillment" button still appears. Tapping it takes you to the "Fulfill Order" flow with all refunded products showing.

**To Reproduce**
1. On the web, refund all the products in an order but do not refund the shipping.
2. In the app, open the same order and notice that no products appear under "Product" but there's still a "Begin Fulfillment" button.
3. Tap "Begin Fulfillment" and notice that the usual fulfillment screen appears with all the products still showing.

**Screenshots**

Order Details|Fulfillment Screen
-|-
![IMG_1624](https://user-images.githubusercontent.com/8658164/74443333-e2fdb880-4e6a-11ea-9eed-f64f53595488.PNG)|![IMG_1625](https://user-images.githubusercontent.com/8658164/74443322-df6a3180-4e6a-11ea-9bba-f165bec74092.jpg)

**Expected behavior**

I expect that if all products are refunded, I won't be able to fulfill the order.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.3.1
- WooCommerce iOS version: 3.6.0.1 TestFlight Beta

cc @pmusolino

**Comment by pmusolino** [comment]
Thanks @rachelmcr for reporting this issue.
I think that when all the products are refunded, the status of the order needs also to be changed to `refunded`, but on your screen, I see `processing`, and I think this is the reason why you are able to see the Fulfill button. 
I did a test, and I noticed that if you refund all the products, but not the shipping, the status of the order remains in the `processing` status. So, I'm not sure if we need to manage this case inside the app, or if it's a bug of the backend (I think it doesn't make much sense that the order stays in the `processing` state).

@astralbodies what do you think?

**Comment by rachelmcr** [comment]
Hm, I wouldn't expect the status of the order to be automatically changed to `refunded` unless the payment was fully refunded, including shipping.

In a real-life scenario I might change the order status to `cancelled` instead of leaving it as `processing` when I refunded all the products. However, in that case instead of seeing the Fulfill button I see the Product section with "Details" that goes to a list of the refunded products in the order:

<img src="https://user-images.githubusercontent.com/8658164/74450016-59071d00-4e75-11ea-93c8-4353fde79084.jpeg" width="50%">

**Comment by rachelmcr** [comment]
Another issue that seems strongly related to this one (both cases are related to the fulfill order screen and refunded products):

If some (or all) products are refunded, the Fulfill Order screen shows all products in the original order instead of removing refunded products.

For example, this order originally included 2 sunglasses. One of the sunglasses was refunded. The order details show the correct quantity (1) but the fulfill order screen shows the wrong quantity (2).

Screenshots:

Order details screen|Fulfill order screen
-|-
![IMG_3612](https://user-images.githubusercontent.com/8658164/86482673-53d63c00-bd4a-11ea-967c-9684f66dd9aa.PNG)|![IMG_3613](https://user-images.githubusercontent.com/8658164/86482666-5042b500-bd4a-11ea-8455-3b9cb73a49d1.PNG)

Let me know if you'd like this in a new issue, but it feels like it's similar enough to include here.

**Comment by Ecarrion** [comment]
This seems to have been fixed by the amazing @jaclync on [this PR](https://github.com/woocommerce/woocommerce-ios/pull/3268/files#diff-b6999e624913fd52e3e1309e073efd298acda219ddfaa387dcc28795115a77a0R726-R728) 🎉 

<img width="399" alt="Screen Shot 2020-12-06 at 9 34 41 PM" src="https://user-images.githubusercontent.com/562080/101303188-7b569680-380b-11eb-8047-3d2b309b9a5b.png">
