### ISSUE TITLE
Refunds: Refund details show manual refunds as via the customer's payment method

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1860]
**Describe the bug**

The refund details screen always shows the customer's original payment method as the refund method, even for manual refunds. For example, I have an order that was paid via Direct Bank Transfer. In the order details, it shows the payment was refunded "via manual refund" but in the refund details it says "Refunded manually via Direct Bank Transfer."

**To Reproduce**
1. On the web, manually refund all or part of an order.
2. In the app, open the order details and confirm you see the Payment section including the customer's payment method and the refund listed "via manual refund."
3. Tap the "Refunded" line to open the refund details.
4. Notice the refund details include "Refunded manually via" and then the customer's payment method.

**Screenshots**

Order details|Refund details
-|-
![IMG_1626](https://user-images.githubusercontent.com/8658164/74444514-e5f9a880-4e6c-11ea-832c-c22710bfbb09.PNG)|![IMG_1628](https://user-images.githubusercontent.com/8658164/74444525-e98d2f80-4e6c-11ea-808e-f2b7d32b304b.PNG)

**Expected behavior**

I expect manual refunds to only say they were refunded manually, without assuming the refund was done via the same method as the customer's payment method.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.3.1
- WooCommerce iOS version: 3.6.0.1 TestFlight beta

**Comment by rachelmcr** [comment]
cc @pmusolino

**Comment by pmusolino** [comment]
Hey @0nko, how do you manage this on Android?
I see that we're making the assumption that the payment method is the same as the refund method, but if we don't have a refund gateway, we always show `manual refund`.

**Comment by jaclync** [comment]
It looks like the payment method is shown on Android in both places:

Order Details | Refund Details
-- | --
![Screenshot_1581926765](https://user-images.githubusercontent.com/1945542/74634765-81598900-519f-11ea-9efd-670c487d0b61.png) | ![Screenshot_1581926746](https://user-images.githubusercontent.com/1945542/74634758-7e5e9880-519f-11ea-9453-b75b629848a7.png)

@rachelmcr do you think we should just say "Refund manually" on the Refund Details screen? cc @Garance91540

**Comment by 0nko** [comment]
Hey @pmusolino. Yes, we use the following logic to determine the payment type:
```
val paymentType = if (order.paymentMethodTitle.isBlank())
    manualRefund
else if (refund.automaticGatewayRefund || order.paymentMethod.isCashPayment)
    order.paymentMethodTitle
else
    "$manualRefund - ${order.paymentMethodTitle}"
```
