### ISSUE TITLE
Orders: Order notification doesn't open order details when opened from lock screen

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1867]
**Describe the bug**

If my device screen is locked, and I get a new order notification for that order, tapping the notification doesn't open the order in the app. Instead, the app just opens to the last screen I was viewing.

**To Reproduce**

0. Lock your device screen (app can be running in background or not).
1. Create a new order on your store.
2. Tap the new order push notification on your device.
3. If the order details don't open, tap the Orders tab to view your orders list. Notice that the new order isn't already in the list but it loads while you are on that tab.

**Expected behavior**

I expect the order details for the new order to load when I tap on the notification.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.3.1
- WooCommerce iOS version: 3.6.0.2

**Comment by rachelmcr** [comment]
This is the same issue I raised during 3.5 beta testing, but didn't open an issue at that time since it was inconsistent. (Internal link: p5T066-19o-p2#comment-4215)

**Comment by jaclync** [comment]
hm I wasn't able to repro during my testing today with a few order notifications when the app wasn't launched and in the background 🤔 will keep an eye out for it though!

**Comment by rachelmcr** [comment]
I saw this happen again while testing the 4.1.0.0 beta. However, the issue only happened once, and every time after that it worked as expected. I still haven't found more reliable steps to reproduce it, or details about the cause, but I wanted to mention that it's still happening sometimes.

**Comment by shiki** [comment]
I experienced this today on 4.4 using iPhone 8 plus. It consistently opens the last screen if the device was locked. If the device was not locked, then the app opens the order details correctly. My device was also in low power mode. Maybe that's significant. 🤷

**Comment by rachelmcr** [comment]
I experienced this again while testing 4.8 on iPad Mini 4 (iPadOS 14 beta) and confirmed that the issue consistently occurs if the device is locked and the push notification is opened from the lock screen. (Other things don't seem to be a factor.) I updated the issue title and steps to reproduce to reflect that.

**Comment by shiki** [comment]
I looked into this a bit today. It looks like when a push notification is tapped from the lock screen, the application state is `background` and so this routine is called which only synchronizes notifications but does not _present_ the Order:

https://github.com/woocommerce/woocommerce-ios/blob/74d9f5b92b55fc9fa51336e4d72e1d3c0831bcf7/WooCommerce/Classes/Notifications/PushNotificationsManager.swift#L386-L394

The **expected** behavior is for this method to be called which presents the Order details:

https://github.com/woocommerce/woocommerce-ios/blob/74d9f5b92b55fc9fa51336e4d72e1d3c0831bcf7/WooCommerce/Classes/Notifications/PushNotificationsManager.swift#L359-L375

We currently rely on the application state to _guess_ if the user tapped on the notification. But with this finding, this strategy no longer works. 

A possible solution would be to look at using [`UNUserNotificationCenter`](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter) to handle the notifications instead.

**Comment by designsimply** [comment]
(In case it's helpful) a similar problem was solved in WPiOS at https://github.com/wordpress-mobile/WordPress-iOS/pull/14349.

**Comment by designsimply** [comment]
I tried the following testing steps today as part of 5.9 beta testing and I was unable to replicate the problem.

My testing steps:

1. Leave WCiOS in the foreground or background the app.
1. Lock the device.
1. Receive a push notification for a new order.
1. Wait ~4 seconds.
1. Tap the push notification without unlocking the device.<br><sup>On FaceID capable phones, make sure to keep your face away from the sensor.</sup><br><sup>On TouchID phones, press with an unregistered finger.</sup>
1. Wait for the "FaceID to Unlock".
1. Perform FaceID to unlock.
1. Confirm the correct order is displayed in the app.
1. Repeat the steps once more with a 2nd order.
1. Repeat the steps once more with a 3rd order except background the app in step 1.

**Result:** the correct order opened for me in the app after tapping push notifications on the lock screen and <em>then</em> unlocking my device even after leaving a previous order open and repeating the testing steps. It didn't matter whether I left the app in the background or not.

Push notification showing on the lock screen|Push notification after long-press|Face ID prompt|View after app opens
---|---|---|---
![IMG_4767](https://user-images.githubusercontent.com/1119271/106814553-d0f2c800-662f-11eb-89eb-d6236c6d8acd.PNG)|![IMG_4768](https://user-images.githubusercontent.com/1119271/106814572-d7813f80-662f-11eb-8971-ff2773240fc0.PNG)|![IMG_4769](https://user-images.githubusercontent.com/1119271/106814577-d94b0300-662f-11eb-8682-3521f1ee7f37.PNG)|![IMG_4770](https://user-images.githubusercontent.com/1119271/106814581-da7c3000-662f-11eb-9e0f-e745a9ef16d4.PNG)

<sup>Tested with WCiOS 5.9.0.0 TestFlight beta on iPhone 11 iOS 14.4.</sup>

**Comment by designsimply** [comment]
I tested this again with WCiOS 6.0.0.0 and found that I could replicate the bug when using my iPhone 6S with iOS 13.7. 

But I still could not replicate the bug when using my iPhone 11 with iOS 14.4.

I suspect this bug is related to iOS 13.

**Comment by Ecarrion** [comment]
I've been trying to replicate this on my test devices and I haven't been able to.

Since we don't support iOS 13 anymore I think this does not needs any immediate action and **close this issue.** 

We also should plan a project/refactor to update our code to use newer APIS like `UNUserNotificationCenter`

Do you agree @shiki?

**Comment by shiki** [comment]
Thanks for checking this! Let's close this then. 

> We also should plan a project/refactor to update our code to use newer APIS like UNUserNotificationCenter

If things are still working and we're not touching the code all the time, it's probably not worth it to spend the time. I don't see any benefits to our customers. 

We _could_ consider it if we're changing the push notification logic during the multi-site push notifications. Or maybe during https://github.com/woocommerce/woocommerce-ios/issues/2902.
