### ISSUE TITLE
Order Detail: product images are not updated correctly until the Edit Product screen is opened

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#1869]
zen-2709210

Seems that if a user updates a product image from the web when he opens an order detail with that product, the image will not be updated until the Edit Product screen is opened.

## Animated GIF of the problem
![2020-02-14 16-34-30 2020-02-14 16_35_03](https://user-images.githubusercontent.com/495617/74545604-6d1c4e80-4f49-11ea-9551-162e9ad55b5b.gif)

## Steps to reproduce the behavior:
1. Navigate from the web to a product which is contained inside an order
2. Edit the product image
3. Open the app and navigate to the order detail which contains the edited product
4. You will see that the product image showed is the old image (or the placeholder).  
5. Tap on the product
6. If the Edit Product screen is opened, close the screen
7. Now you can notice that the product image was correctly updated.

## Isolating the problem
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

## Mobile Environment
- Device: simulator iPhone 11 Pro 
- iOS version: 13.2.2
- WooCommerce iOS version: 3.5 and 3.6

**Comment by pmusolino** [comment]
Discussion here https://a8c.slack.com/archives/C6H8C3G23/p1581691740431800

**Comment by shiki** [comment]
I can confirm that the bug still happens on 5.6.

**Comment by shiki** [comment]
Related issue: https://github.com/woocommerce/woocommerce-ios/issues/1869

**Comment by shiki** [comment]
We did some fixes for variations in https://github.com/woocommerce/woocommerce-ios/pull/3314 but I think this bug is different and still happens. I'm just leaving a comment to mention that I tested this again after #3314 is merged. 😄

**Comment by joshheald** [comment]
I can still reproduce this.

Prioritization:
Severity – low (visual issue)
Impact – low: estimated 0-5% of users affected (the image reloads as expected in the Product List and for new orders)
= low

**Comment by rachelmcr** [comment]
I tested again on WCiOS 20.0 (TestFlight beta) and can no longer reproduce this. When I open the app and navigate to the Products tab, the product image is updated in the list before opening the product details.
