### ISSUE TITLE
Connecting with Woo REST API: wc/v2

### ISSUE THREAD

**Issue by msilbers** [woocommerce/woocommerce-ios#1870]
It looks like we’re supposed to tell users that they need to upgrade to v3 when the app starts, but that may not be happening. We have a support ticket where someone is connected and can see My Store, but nothing in Orders. The following error appears in the logs, right at the start:

> You are using an older version of the Woo REST API: wc/v2, for path: orders/12462/shipment-trackings/2020/02/13 00:26:29:704

When trying to load Orders it says "Unable to refresh list"

Full logs in #2711976-zen

**Expected behavior**
To prompt an update to v3

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 11,2
- iOS version: 13.3.1
- WooCommerce iOS version: 3.5.0.2

**Comment by astralbodies** [comment]
I think using the v2 API for the Shipment Tracking extension is a known issue ( p99K0U-1iR-p2 ) and it might be  unrelated to the order list not updating in this case. @anitaa1990 have we checked to see if the extension has a v3 API yet?

**Comment by shiki** [comment]
@astralbodies That's correct. I ran into this issue just recently. The API here is for the Shipment Tracking extension and is still working as far as I know. It's normal to see that in the log. That's coming from here:

https://github.com/woocommerce/woocommerce-ios/blob/4bfcb596ef5507b03e79e6c08a0e3c9b9786c9ec/Networking/Networking/Requests/JetpackRequest.swift#L44-L46

As for the upgrade prompt, we do show that went the user logs in. And it looks like it still works. 

<img src="https://user-images.githubusercontent.com/198826/93653026-615ba380-f9d4-11ea-8fa6-8aa7b15e45c2.png" width="240">

--- 

I think we can close this for now. 🙂  Thank you for reporting!
