### ISSUE TITLE
Top Performers & Refunded Products: product name showing HTML entities instead of being decoded

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1871]
Similar to https://github.com/woocommerce/woocommerce-ios/issues/1808, but in the top performers UI and refunded products UI:

top performers | refunded products
-- | --
![IMG_7666](https://user-images.githubusercontent.com/1945542/74633189-0cd11b00-519c-11ea-9529-3a59054c7a56.PNG) | ![IMG_7667](https://user-images.githubusercontent.com/1945542/74633205-13f82900-519c-11ea-9151-ba3b1b34f1c6.PNG)

**Comment by shiki** [comment]
Tested this on `develop` (66d9e2403) and it looks like it's already fixed. 

Order Details | Top Performers | Refunded Products
--------|-------|-
![image](https://user-images.githubusercontent.com/198826/87722077-b7159480-c774-11ea-893e-e31444965a48.png)       |       ![image](https://user-images.githubusercontent.com/198826/87722104-bed53900-c774-11ea-9281-edd1df8fb1a8.png)|![image](https://user-images.githubusercontent.com/198826/87722245-f9d76c80-c774-11ea-8bac-0cc5cb148e18.png)
