### ISSUE TITLE
Order Details: shipping address is flipped for some regions

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1872]
**Describe the bug**

The address in the "Shipping details" and "Billing information" is flipped on both of my devices, but not on the simulators 🤔 

**To Reproduce**

- Go to the Orders tab
- Tap on an Order that contains a physical product and valid shipping address
- Note the address under CUSTOMER > Shipping details and also inside "View Billing Information"

**Screenshots**

<img src="https://user-images.githubusercontent.com/1945542/74633631-03947e00-519d-11ea-875a-650962ed3895.PNG" width="320"/>

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XR & iPhone 6s Plus
- iOS version: 13.3.1 & 12.1
- WooCommerce iOS version: 3.6.0.2 (and also in 3.5 and 3.4 TestFlight beta builds)

**Comment by pmusolino** [comment]
@jaclync I checked this bug and I'm not able to replicate it from the device or from the simulator. Can you retry it on the same order? Probably it was fixed 

This is a screenshots from a read device (iPhone X):
<img src="https://user-images.githubusercontent.com/495617/82572413-90781a80-9b84-11ea-85fe-bab26824bc1d.jpeg" width=300 />

**Comment by jaclync** [comment]
Thanks Paolo for testing! After more testing for shipping labels today, I realized that the address is in reverse order for certain regions [like Taiwan](https://en.wikipedia.org/wiki/Postal_addresses_in_Taiwan) (and some eastern Asian regions). It makes sense when the addresses are in their own language, but it's just a bit confusing seeing English addresses in reverse order 😅 

It looks like the order of address lines currently follows the region of the device, and we can set `CNPostalAddress`'s `isoCountryCode` to make it adapt to the order of the country. I'll open a PR for this!
