### ISSUE TITLE
Edit Products M2: analytics

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1879]
### Product Images

- I want to manage my product's images.

event name | trigger | properties
-- | -- | --
*_product_image_settings_done_button_tapped | User tapped on the Done menu button in the product images screen. | `has_changed_data`: a boolean that indicates whether the user has changed the product images.
*_product_detail_add_image_tapped | User tapped on the "+" button in the Product Detail screen to update product images. | n/a
*_product_image_settings_add_images_button_tapped | User tapped on the Add Photos button in the product image settings screen. | n/a
*_product_image_settings_add_images_source_tapped | User tapped on the image source menu button in the product image settings screen. | `source`: the image source the user chose between `camera`, `device`, `wpmedia`
*_product_image_settings_delete_image_button_tapped | User tapped on the trash button in the product image screen. | n/a

### More Product Menu

- I want to view my product webpage.

event name | trigger | properties
-- | -- | --
*_product_detail_view_external_tapped | User tapped on the View Product in Store option in the product detail menu | n/a

- I want to share my product.

event name | trigger | properties
-- | -- | --
*_product_detail_share_button_tapped | User tapped on the Share option in the product detail menu | n/a

### Product Settings

event name | trigger | properties
-- | -- | --
*_product_detail_view_settings_button_tapped | User tapped the Product Settings menu button in the product detail screen | n/a
*_product_settings_done_button_tapped | User tapped on the Done menu button in the product settings screen | n/a

- I want to change the status of my product.

event name | trigger | properties
-- | -- | --
*_product_settings_status_tapped | User tapped on the status row in the product settings screen | n/a

- I want to modify the catalog visibility of my product.

event name | trigger | properties
-- | -- | --
*_product_settings_catalog_visibility_tapped | User tapped on the catalog visibility row in the product settings screen | n/a

- I want to edit my product's short description.

event name | trigger | properties
-- | -- | --
*_product_detail_view_short_description_tapped | User tapped on the short description row in the Product Detail screen | n/a
*_product_short_description_done_button_tapped | User tapped on the Done menu button in the Aztec editor screen for product short description. | `has_changed_data`: a boolean that indicates whether the user has changed the product short description

- I want to edit my product's URL in my store.

event name | trigger | properties
-- | -- | --
*_product_settings_slug_tapped | User tapped on the slug row in the product settings screen | n/a

- I want to edit my product's purchase note

event name | trigger | properties
-- | -- | --
*_product_settings_purchase_note_tapped | User tapped on the purchase note row in the product settings screen | n/a

- I want to edit my product's visibility

event name | trigger | properties
-- | -- | --
*_product_settings_visibility_tapped | User tapped on the visibility row in the product settings screen | n/a

- I want to set an order for my product in the Menu Order

event name | trigger | properties
-- | -- | --
*_product_settings_menu_order_tapped | User tapped on the menu order row in the product settings screen | n/a

### Product List Sorting/Filtering

- I want to sort products by ascending/descending name/date

event name | trigger | properties
-- | -- | --
*_product_list_view_sorting_options_tapped | User tapped on the sorting button in the Product List screen | n/a
*_product_sorting_list_option_selected | User selects a sorting option from the Sorting list bottom sheet | `order={name/date},{ascending/descending}` (e.g. `order=name,ascending`)

- I want to filter products by stock status, product status, and product type

event name | trigger | properties
-- | -- | --
*_product_list_view_filter_options_tapped | User tapped on the filtering button in the Product List screen | n/a
*_product_filter_list_show_products_button_tapped | User tapped on the Show Products button in the product filter list screen | `filters=comma-separated-filter-options i.e "filters":"instock,publish,simple"`
*_product_filter_list_clear_menu_button_tapped | User tapped on the Clear All menu button in the product filter list screen | n/a
*_product_filter_list_dismiss_button_tapped | User tapped on the Dismiss menu button in the product filter list screen | n/a

**Comment by pmusolino** [comment]
I added a new event that was missing:
event name | trigger | properties
-- | -- | --
*_product_settings_visibility_tapped | User tapped on the visibility row in the product settings screen | n/a
