### ISSUE TITLE
Rename `briefDescription` to `shortDescription`

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1899]
In core, the field is called "short description" while we call it `briefDescription` in the codebase. Since `briefDescription` is already in the core data schema, we could probably rename every `briefDescription` to `shortDescription` except for in Storage

**Comment by shiki** [comment]
It looks like it was originally `shortDescription` but was change to `briefDescription` in bd27070 (#805) by @bummytime. 

@bummytime, what was the reason for the rename? 🙂
