### ISSUE TITLE
i18n: Numbers in relative time on reviews are not fully localized

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1902]
**Describe the bug**

The numbers in the relative time on reviews (e.g. "Last 24 hours" and "Older than 7 days") are not fully localized for languages with non-English numerals. Found while testing the changes in https://github.com/woocommerce/woocommerce-ios/pull/1829 and https://github.com/woocommerce/woocommerce-ios/pull/1844.

It might also be worth a full audit by a native speaker using a store that's set up in the target language, also to check things like currency placement and any other formatting issues.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/75371992-a9439d80-58bf-11ea-9ba4-418469d4e266.PNG" width="50%">
<img src="https://user-images.githubusercontent.com/8658164/75371994-aa74ca80-58bf-11ea-819e-63e1681dc9bc.PNG" width="50%">

**Mobile Environment**
Please include:
- Device: iPhone XS set to Arabic (device language)
- iOS version: 13.3.1
- WooCommerce iOS version: 3.7.0.0 TestFlight beta

**Comment by shiki** [comment]
I have a feeling that this is fixed by https://github.com/GlotPress/GlotPress-WP/pull/1105. This should be fixed in WCiOS 4.1.

**Comment by rachelmcr** [comment]
I'm not sure why I didn't realize this before, but the relative times here aren't variables that need to be localized (as I originally thought). They are part of the strings themselves and have been translated with western numerals, for example [here](https://github.com/woocommerce/woocommerce-ios/blob/8611d84058aea9bafba260c297056bb29c950413/WooCommerce/Resources/ar.lproj/Localizable.strings#L761) and [here](https://github.com/woocommerce/woocommerce-ios/blob/8611d84058aea9bafba260c297056bb29c950413/WooCommerce/Resources/ar.lproj/Localizable.strings#L993).

Closing since this isn't an app issue but rather a decision made during translation, and can be updated separately if need be.
