### ISSUE TITLE
Reviews: First recent review for product can have "Unknown" product name

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1907]
**Describe the bug**

After receiving a new review notification and opening the review details, the product name can show up as "Unknown." I found this most consistently happened for products that hadn't been shown recently in the app (no recent orders, hadn't viewed product details, didn't have another recent review).

In some cases, going back to the review list was sufficient for the product name to appear the next time I opened the review detail. But in other cases, navigating around the app and even force-closing and relaunching the app didn't resolve it. In those cases, the product name was also missing from the review in the reviews list.

In one case, I noticed that it was only resolved when I enabled the Products tab and scrolled down until that product was loaded in the products list. Then, when I went back to the review detail the product name appeared. Once it was fixed, any subsequent reviews for the same product worked as expected.

(This was also mentioned in https://github.com/woocommerce/woocommerce-ios/issues/1810 but I saw it separate from that issue.)

**To Reproduce**

1. Create a new review for a product you haven't viewed in the app recently (no orders or reviews, etc.).
2. Tap the push notification to open the review detail.
3. Notice that the product name in the review detail is "Unknown" and tapping it does not open a link to the product.
4. Go back to the reviews list and check if the review has the product name.

**Screenshots**
<img src="https://user-images.githubusercontent.com/8658164/75440944-a8a91680-5954-11ea-9d69-6d704b949316.PNG" width="50%">
<img src="https://user-images.githubusercontent.com/8658164/75440950-aa72da00-5954-11ea-9687-e8e7f8dd4ea5.PNG" width="50%">

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.3.1
- WooCommerce iOS version: 3.7.0.0 TestFlight beta

**Comment by jostnes** [comment]
Was able to reproduce this issue when writing UI tests for the Reviews screen, this is the steps that the test is using:
1. Log in to WooCommerce using WordPress.com
2. Tap on Reviews on the tab navbar
3. See that product is not displayed on the Reviews screen (left blank)
4. Tap on a review
5. See that on the Single Reviews screen, the product is displayed as "Unknown"

<img width="469" alt="reviews screen" src="https://user-images.githubusercontent.com/17252150/147904442-cdae6f32-5a57-436b-b8f4-d272b33f50cd.png">

<img width="471" alt="single review screen" src="https://user-images.githubusercontent.com/17252150/147904446-c408ad64-c048-4f1c-86d7-b751dc75bd61.png">

For now, the workaround for the UI test is to [visit the Products screen first](https://github.com/woocommerce/woocommerce-ios/blob/f88ed22edfad33fdff0b6fe6e883bc2553fc764a/WooCommerce/WooCommerceUITests/Tests/ReviewsTests.swift#L19-L20) before tapping on Reviews.
