### ISSUE TITLE
Reviews: Trashed reviews aren't always removed from reviews list

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1908]
**Describe the bug**

Sometimes, trashing a review doesn't remove it from the reviews list. The list "jumps" a little but the review remains in the list, even though wp-admin shows that it's trashed. Pulling to refresh the list doesn't remove it from the list, although trashing it again from the app does work.

**To Reproduce**

I haven't found 100% reliable steps to trigger the issue, but when it happens the behavior is consistent after that. It seems to most often happen when I first open the app after force-closing it, and when I am moderating a review that isn't first in the list.

1. Open the reviews list and select a review.
2. Tap the trash button on the review detail.
3. Watch for the success message, and wait to see if the review is removed from the list.
4. If it isn't removed, pull to refresh and notice that it still isn't removed from the list.

**Screenshots**

Screencast (issue shown at about 5s): https://cloudup.com/cLmSLODVhDS

**Expected behavior**

I expect the review to always be removed from the list when it is successfully trashed, and for pulling to refresh to reflect the latest changes to the reviews.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.3.1
- WooCommerce iOS version: 3.7.0.0 TestFlight beta

**Comment by pmusolino** [comment]
The issue doesn't happen anymore. Closing it for the moment.
