### ISSUE TITLE
Update "Top performers" product list items to match items on "Products" screen

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-ios#1934]
The "Top Performers" list items are different from the "Product List" items. Let's update the "Top Performers" list items so they match the "Product List" items

https://d.pr/i/bFCsK6

## Tasks

- [x] Fix Top Performers 
- [ ] Fix Products tab. See https://github.com/woocommerce/woocommerce-ios/pull/2004#issuecomment-600778618

**Comment by pmusolino** [comment]
Working on this issue will fix also this: https://github.com/woocommerce/woocommerce-ios/issues/1857

**Comment by pmusolino** [comment]
Working on this issue will fix probably also this: #1945
