### ISSUE TITLE
[Order Details /Shipment Tracking] - Add placeholder text for "Shipping provider"

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-ios#1937]
To reproduce:
1. install WooCommerce shipment tracking extension
2. Go to order details screen
3. select "Add tracking"

You can see that the "Shipping Provider" field is empty. We should add a placeholder text that says " Select Carrier" https://d.pr/i/pB2vlh (we are changing all mention of "provider" to "carrier" in a separate issue)

**Comment by shiki** [comment]
Fixed by @pmusolino in https://github.com/woocommerce/woocommerce-ios/pull/1950.
