### ISSUE TITLE
[Dark mode] Add border to bottom nav

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-ios#1938]
Bottom nav bar should have a border https://d.pr/i/Jmhz66

See design in Figma: https://www.figma.com/file/S62xbAwtgoMgax4GcuFjKS/System---Dark%2FLight-modes?node-id=170%3A5076

**Comment by astralbodies** [comment]
I'm tagging this one for an outside contributor.

**Comment by shiki** [comment]
Done in #1973.
