### ISSUE TITLE
Top Performers: product images aren't always shown

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1945]
**Describe the bug**
For some products under the Top Performers section, the image isn't shown in the product row while the product image exists in the Products tab.

**To Reproduce**

Note: this is not always reproducible, some product images are shown while some aren't.

- On web, place an order with the product that has at least an image
- Launch the app
- Go to the Products tab and make sure the product from step 1 is loaded with an image
- Go to "My store" tab and scroll to the Top Performers section --> the product from step 1 should appear with an image (assuming that there are not many other orders for today)

**Screenshots**

Products tab (note that the "Manga & Comics"! product has an image) | Top Performers (the image isn't shown)
-- | --
![IMG_7672](https://user-images.githubusercontent.com/1945542/76483666-9221b580-6452-11ea-93a3-342a4f1d86d5.PNG) | ![IMG_7674](https://user-images.githubusercontent.com/1945542/76483700-a796df80-6452-11ea-8410-570a30289c1b.PNG)

**Expected behavior**

The product image should show up under the Top Performers section.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 6s Plus
- iOS version: iOS 12.1
- WooCommerce iOS version: 3.8.0.0

**WordPress Environment**
WC version 4.0

**Comment by pmusolino** [comment]
More about this issue [here](https://a8c.slack.com/archives/CGPNUU63E/p1588069982033900) and here: p99K0U-1SZ

**Comment by jaclync** [comment]
I cannot reproduce this in multiple test stores, closing this for now.
