### ISSUE TITLE
Stats banner update for Woo 4.0

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-ios#1946]
There are a couple of changes needed in the app now that Woo 4.0 is released and includes WooCommerce Admin plugin.

1. If we know for sure the new stats endpoint is available, then default to the new stats UI instead of displaying a banner message.
2. Site does not have v4 wc-analytics namespace available OR Woo version is less than 4.0 - inform user that old stats will eventually go away, upgrade to 4.0 or install WCAdmin.

- [ ] if we want to check if the WC version, it is a new endpoint that we are going to implement: `/wc/v3/system_status?_fields=environment`

<img width="541" src="https://user-images.githubusercontent.com/22608780/76535968-b658b300-64a1-11ea-91ae-fd6bed185e9a.png">

**Comment by AmandaRiu** [comment]
NOTE: Use September 1, 2020 as the cutoff date for old stats support.

**Comment by shiki** [comment]
Ref: p91TBi-2tl-p2#comment-207

**Comment by shiki** [comment]
Closed by #2467.
