### ISSUE TITLE
Zendesk: Populate selected site if available

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-ios#1951]
The WP apps list the currently selected site if one is selected which is helpful to support personnel. Replicate that functionality in the Woo app and use the same field that WP uses.

Android: https://github.com/woocommerce/woocommerce-android/issues/2044

**Comment by pmusolino** [comment]
I was investigating this issue, and I found that this functionality is already implemented on iOS. We populate the "Current Site" field on Zendesk if available. 
@astralbodies maybe you were referring to some other field?

**Comment by astralbodies** [comment]
@pmusolino It's possible that this wasn't the case back in early 2020, so feel free to close it!
