### ISSUE TITLE
Products: Scheduling a sale is hard due to the date picker behavior

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1952]
**Describe the bug**

Scheduling a sale for a product is hard to do, due to the way the date picker behaves.

The start and end dates are set automatically when the sale toggle is enabled, with an end date immediately after the start date. The picker won't let me choose a start date later than the end date, so I (unintuitively) have to set the end date first, and then go back to set the start date.

The date picker also doesn't explain what's happening — at first I thought it was broken, because when I tried to choose a future start date it just reset the date back to the initial setting.

**To Reproduce**
1. Select the product and open the Price settings.
2. Enable the "Schedule sale" toggle.
3. Notice the preset start and end dates.
4. Try to schedule a future start date for the sale, past the preset end date.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/76614782-a7f9ae00-6518-11ea-8ec3-d485b7475164.png" width="50%">

Screencast: https://cloudup.com/cQ5o6hvsiRy

**Expected behavior**

Here's my expected workflow:

1. Select the product and open the Price settings.
2. Enable the "Schedule sale" toggle.
3. Select a start date.
4. Select an end date.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.3.1
- WooCommerce iOS version: 3.8.0.0

**Comment by pmusolino** [comment]
Fixed here #1999
