### ISSUE TITLE
Products: Unclear UI for saving/discarding changes to a product

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1953]
**Describe the bug**

After editing a product, it isn't clear to me when my changes will be saved or discarded.

The UI is fairly clear when editing a specific field for a product, e.g. the title. When I tap the "Done" button the change is saved (the action "done" is a little unclear to me, but I figured it out in context); when I tap the back button I get a prompt to discard my changes.

However, the UI is _not_ clear and doesn't stop me from accidentally discarding changes when I'm looking at the main product editing screen. I have to tap "Update" to actually save my changes (even though the editing screen for each field made it feel like saving/discarding happened there). If I go back to the Products list without updating the product, my changes are discarded with no warning.

**To Reproduce**
1. Go to the Products tab.
2. Select a product.
3. Tap any field on the product to edit it.
4. Make a change and tap "Done." Notice that you're taken back to the main product editing screen and your change was saved.
5. Tap any field on the product to edit it again.
6. Make a change and tap the back button. Notice that you get a prompt to discard the changes you made.
7. Discard the changes and notice that you're taken back to the main product editing screen and your change wasn't saved.
8. Tap any field on the product to edit it again.
9. Tap "Done" to save the change.
10. On the main product editing screen, tap the "Update" button and notice the "Publishing your product..." screen.
11. Tap the back button to go back to the Products list.
12. Open the product again and confirm your changes were saved.
13. Tap any field on the product to edit it again.
14. Tap "Done" to save the change.
15. On the main product editing screen, to the back button to go back to the Products list. Notice that there is no prompt to save/discard your changes.
16. Open the product again and notice that your last change wasn't saved.

**Screenshots**

Screencast showing the steps outlined above: https://cloudup.com/cSxkhK0hVD3

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.3.1
- WooCommerce iOS version: 3.8.0.0 TestFlight beta

**Comment by jaclync** [comment]
fixed in https://github.com/woocommerce/woocommerce-ios/pull/1977, closing
