### ISSUE TITLE
Products: Tax classes aren't cached/loading indicators appear each time it's opened

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1954]
**Describe the bug**

Most options for product settings (e.g. Tax status, Stock status) are immediately available when I edit that field.

However, when I open the "Tax class" setting, the list of tax classes always have to be reloaded. A loading indicator appears each time (the list doesn't seem to be cached).

**To Reproduce**
1. Go to the Products tab.
2. Select a product.
3. Select "Price."
4. Select "Tax class." Notice the loading indicators before the list of tax classes loads.
5. Go back to the Price screen.
6. Select "Tax class" again. Notice the loading indicators again.

**Screenshots**

Screencast: https://cloudup.com/c-Cd44H_GbX

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.3.1
- WooCommerce iOS version: 3.8.0.0 TestFlight beta

**Comment by jaclync** [comment]
we currently fetch the latest tax classes from the site every time to simplify the states and the chance of selecting an outdated tax class. it'd be nice to cache these per edit session at least, while caching could introduce more states. I think we can leave it as a future enhancement?

**Comment by rachelmcr** [comment]
That makes sense to me! It'd be nice to cache them to some extent (per edit session seems reasonable). I've marked this as an enhancement we can look at in the future.
