### ISSUE TITLE
Products: Inconsistent case in error message title

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1955]
**Describe the bug**

If the app can't update a product (e.g. you try to use a SKU already used on another product) the error message uses inconsistent case:

> Cannot update Product

We shouldn't capitalize nouns like "Product" unless we're using title case in the error message. I expect the error to be one of these:

> Cannot update product

> Cannot Update Product

**To Reproduce**
1. Go to the Products tab.
2. Select a product.
3. Open the Inventory section.
4. Change the SKU to one already used on another product.
5. Select "Done" and then select "Update."
6. Notice the error message that appears.

**Screenshots**
<img src="https://user-images.githubusercontent.com/8658164/76617810-f8740a00-651e-11ea-841a-2a89cad2510c.png" width="50%">

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.3.1
- WooCommerce iOS version: 3.8.0.0 TestFlight beta

**Comment by pmusolino** [comment]
Fixed in #1972
