### ISSUE TITLE
Products: Currency symbol in wrong position in Price section

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1956]
**Describe the bug**

In my store's currency (GBP) I expect the currency symbol (`£`) to appear to the left of the price.

Instead, it appears on the right side of the `Price` and `Sale price` fields when I edit them.

**To Reproduce**
1. Go to the Products tab.
2. Select a product.
3. Select "Price."
4. Notice that the currency symbol appears to the right of the price/sale price amount, instead of to the left.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/76618206-e47cd800-651f-11ea-8562-4dc999521bf5.png" width="50%">

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.3.1
- WooCommerce iOS version: 3.8.0.0 TestFlight beta

**Comment by jaclync** [comment]
I spent a few hours trying to include the currency symbol in the price text field respecting the WC settings, struggling with the following:

- the currency symbol could be at one of the 4 positions under wp-admin > WooCommerce > Settings > General > Currency options > Currency position:
  - Left (e.g. `$1.6`)
  - Right (e.g. `1.6$`)
  - Left with a space (e.g. `$ 1.6`)
  - Right with a space (e.g. `1.6 $`)
- a price could be negative (not sure about the use cases but it's allowed in core), and the formatting is complicated with the negative symbol (`-`) considering LTR/RTL: https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/Tools/Currency/CurrencyFormatter.swift#L73-L115
- Currently, `CurrencyFormatter` uses `CurrencySettings.shared` singleton, and it adds lots of changes to add unit tests for different currency settings

I don't think this is suitable for release 3.8, but I'm planning on giving it a bit more time for 3.9 given the current progress 😅 (cc @pmusolino @shiki)

**Comment by pmusolino** [comment]
Thanks for investigating deeply this issue @jaclync! And yes, I agree with you, this is not suitable for release 3.8.

In the edit price screen, since the price is editable and the symbol inside the price can create a lot of problems during the editing, the symbol is not part of the text field, but it's a separate view.

`UnitInputTableViewCell`:
<img width="400" alt="Schermata 2020-03-18 alle 11 42 38" src="https://user-images.githubusercontent.com/495617/76952633-add30300-690d-11ea-9989-dac414b63c3d.png">

This is just an idea: since the text field and the unit label are nested inside a horizontal stack view, I think that we can switch the position of the unit label based on the Currency position and on LTR/RTL languages. What do you think?

**Comment by jaclync** [comment]
I like the idea! not sure if the Auto Layout constraints would play nicely with different stack view orders, but it's worth a try toward this direction (separating the currency and price text field). I haven't found a simple way to include the currency symbol in the price text field & handling each text change, and it's more error prone considering many different currency position settings and negative values

**Comment by shiki** [comment]
My gut feeling is that we should implement our own `UITextField` component (subclass) that supports what Jaclyn mentioned in https://github.com/woocommerce/woocommerce-ios/issues/1956#issuecomment-600547487. Managing the currency symbol and the text field separately could be challenging to maintain. 

I haven't used these yet, but I wonder if we can use the `leftView` and `rightView` as shown [here](https://medium.com/@parmarvhv/customizing-uitextfield-a7cd80769c35)? 

Also, I have a feeling that there's a third party library existing to solve this problem so I wouldn't be opposed to that either. 

---

> I don't think this is suitable for release 3.8, but I'm planning on giving it a bit more time for 3.9 given the current progress

I don't believe this is something that we should rush to fix. 🙂

**Comment by mahdialikhanusiya** [comment]
I have similar issue in RTL site

**Comment by jaclync** [comment]
Hello @mahdialikhanusiya, thanks for reaching out. Could you create a new issue with more information about the issue you had? Screenshots and some information about your store and device would be very helpful.
