### ISSUE TITLE
Products: Provide actionable empty states for product editing

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1958]
**Is your feature request related to a problem? Please describe.**

On certain screens in the Products section, I can see an empty state that doesn't provide an actionable message so I don't know how to proceed. This includes:

* Product list with no products (just a message, no CTA).
* Products search with no products (just a blank screen, no message or CTA).
* Product > Shipping > Shipping class with no shipping classes (just a message, no CTA).

**Describe the solution you'd like**

Ideally, any empty state will be actionable. This includes places where the action requires going to WP Admin on the web.

**Additional context**

<img src="https://user-images.githubusercontent.com/8658164/76619579-252a2080-6523-11ea-94e9-e379f90ad826.png" width="50%">
<img src="https://user-images.githubusercontent.com/8658164/76619581-265b4d80-6523-11ea-82a8-a347fc148b3d.png" width="50%">
<img src="https://user-images.githubusercontent.com/8658164/76619583-28bda780-6523-11ea-9d68-579419892f27.png" width="50%">

As seen on iPhone XS, iOS 13.3.1, WCiOS 3.8.0.0 TestFlight beta.

**Comment by jaclync** [comment]
thanks for raising this! we do have plans to update the empty states from @Garance91540's emotional design in p99K0U-1Zy-p2:

<img width="707" alt="Screen Shot 2020-03-16 at 2 00 22 PM" src="https://user-images.githubusercontent.com/1945542/76727321-aafdd400-678e-11ea-9eaf-b7cf767cd1a8.png">

- Products tab: we will add a CTA to add a product when we implement Add Products
- Search products: nothing blocking, I believe we have plans to implement this in the near future - I created https://github.com/woocommerce/woocommerce-ios/issues/1974 to track this
- Shipping classes: I don't think we plan on supporting Add Shipping Classes yet

From my understanding, we currently don't show any CTA that links to wp-admin in the app. My guess is that it adds complexity for us to authenticate the site, and we try keeping users in the app

**Comment by rachelmcr** [comment]
Thanks, I missed those plans and they should address most of my concerns!

> From my understanding, we currently don't show any CTA that links to wp-admin in the app. My guess is that it adds complexity for us to authenticate the site, and we try keeping users in the app

I think it's worth considering having either links or at least information for users who run into a dead end in the app that requires them to go to WP Admin to resolve it. It reminds me of the refund notice we're showing on Android for custom shipping/tax, implemented in https://github.com/woocommerce/woocommerce-android/pull/1968.

It might not be a big deal for this particular screen, though. I'm ok with us closing this issue if we don't want to make any changes to that screen at this point. We can always wait for end user feedback and reconsider if there's any confusion around how to add shipping classes.

**Comment by Garance91540** [comment]
Hi @rachelmcr ! 

@jaclync already answered most of your questions but thanks for bringing up the shipping class empty state screen. We need to update the illustration and I like your suggestion to add a link to WP-Admin too. I'll update the designs and create an issue for Android (as we haven't started implementing empty states yet on iOS) on the groundskeeping board. (So I think we can close this one)
