### ISSUE TITLE
Products: Discard changes prompt (action sheet popover) not visible on iPad

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1960]
**Describe the bug**

When I make a change to a product setting and don't save it, an action sheet popover appears on iPad but the discard changes prompt isn't visible.

**To Reproduce**
1. Go to the Products tab on an iPad.
2. Select a product.
3. Make a change to the product (e.g. edit the title).
4. Tap the back button, and notice that you are blocked from going back and an empty action sheet popover appears at the top of the screen.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/76621131-9a4b2500-6526-11ea-8889-6f89f99e3f77.PNG" width="50%">

**Mobile Environment**
Please include:
- Device: iPad Mini 4
- iOS version: iPadOS 13.3.1
- WooCommerce iOS version: 3.8.0.0 TestFlight beta

**Comment by pmusolino** [comment]
Fixed in #1969
