### ISSUE TITLE
Products: Aztec HTML mode (when editing a product description) doesn't show text in dark mode

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1963]
**Describe the bug**

With the device set to dark mode, Aztec (used when editing a product description) doesn't show text when you switch to HTML mode.

**To Reproduce**
1. Set your device to dark mode.
2. Go to the Products tab.
3. Select a product.
4. Select "Description."
5. Tap in the text field to give the editor focus.
6. Expand the editor toolbar and select the HTML toolbar button (`</>`) to switch to HTML mode. Notice that the text doesn't appear against the dark background.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/76625301-d5515680-652e-11ea-85ec-59c5c53e19ff.png" width="50%">

**Mobile Environment**
Please include:
- Device: iPhone XS in dark mode
- iOS version: 13.3.1
- WooCommerce iOS version: 3.8.0.0 TestFlight beta

**Comment by jaclync** [comment]
I also noticed the colors are off with blockquote in Dark mode, fixing both in https://github.com/woocommerce/woocommerce-ios/pull/1986:

<img src="https://user-images.githubusercontent.com/1945542/76816771-1782dc80-683c-11ea-865b-e5b56a1ea680.png" width="320" />

**Comment by pmusolino** [comment]
Fixed in #1986
