### ISSUE TITLE
Products: Can't select/edit a link in a product description

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1964]
**Describe the bug**

I expect to be able to select a link to edit it in a product description (using the Aztec editor).

However, links in the product description editor are active, so when I tap on them it opens the link in Safari. If I try to long/force tap on them, it does a peek/pop gesture. Even attempts to select the text in other ways (e.g. select nearby text and then move the text selection to the linked text) didn't work as I accidentally triggered the link while changing the text selection.

**To Reproduce**
1. Go to the Products tab.
2. Select a product.
3. Select "Description" to open the editor.
4. Add a link to some text.
5. Tap the link and notice it opens in Safari.
6. Long tap or force tap the link and notice it does a peek/pop gesture.

**Screenshots**

Screencast: https://cloudup.com/cPBWp3IvCwJ

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.3.1
- WooCommerce iOS version: 3.8.0.0 TestFlight beta

**Comment by jaclync** [comment]
This seems similar to the WPiOS issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1373

**Comment by jaclync** [comment]
fixed in https://github.com/woocommerce/woocommerce-ios/pull/2005, closing this for now!
