### ISSUE TITLE
Products: Search shows read-only product details

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1965]
**Describe the bug**

When I browse my Products list and choose a product, I’m automatically taken into the product editing screen. But when I search for a product, I get the read-only view of the product, with no way to edit it.

As confirmed by @Garance91540:

> The behavior should be the same on the Product tab whether you access a product from the product list or via search: you should see the editable version in both cases

**To Reproduce**

1. Go to the Products tab.
2. Select the search icon.
3. Enter a search query.
4. Select a product from the search results. Notice the product details are read-only.

**Screenshots**

Search screen | Search results | Product details from search
--- | --- | ---
![2020-03-12 20 47 38](https://user-images.githubusercontent.com/8658164/76637459-b2c93880-6542-11ea-8c17-6b3a05c6de42.png) | ![2020-03-12 20 47 42](https://user-images.githubusercontent.com/8658164/76637466-b65cbf80-6542-11ea-9e8f-ec72d1f43009.png) | ![2020-03-12 20 47 49](https://user-images.githubusercontent.com/8658164/76637468-b6f55600-6542-11ea-930d-ddf5fa1f28d0.png)

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.3.1
- WooCommerce iOS version: 3.8.0.0 TestFlight beta

**Comment by pmusolino** [comment]
Fixed in #1971
