### ISSUE TITLE
Products: Missing "share" feature in more actions menu

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-ios#1967]
I'm not seeing the more action menu with the "Share" feature on iOS (seeing it on Android though)

Designs:
<img width="435" alt="Screen Shot 2020-03-13 at 5 33 25 PM" src="https://user-images.githubusercontent.com/28450084/76640741-c54a6e80-6550-11ea-9c0a-241c5de69f14.png">

Here's how it's currently implemented on Android:
![Screenshot_20200313-172127](https://user-images.githubusercontent.com/28450084/76640587-7c92b580-6550-11ea-9f46-8b6aecbf642f.png)
![Screenshot_20200313-173003](https://user-images.githubusercontent.com/28450084/76640593-7ef50f80-6550-11ea-8739-6f975c8026d0.png)

**Comment by jaclync** [comment]
as @pmusolino mentioned in p5T066-1dj-p2#comment-4519, it's part of milestone 2 and we already implemented this in https://github.com/woocommerce/woocommerce-ios/issues/1820 (PR: https://github.com/woocommerce/woocommerce-ios/pull/1833)

also in M1, there are no other features available in the "..." menu so it might be odd to show the menu with only one action (share product) in M1

**Comment by Garance91540** [comment]
> also in M1, there are no other features available in the "..." menu so it might be odd to show the menu with only one action (share product) in M1

I think that's ok actually. So if it's ready, don't hesitate to include it! if not, totally ok to wait for M2
