### ISSUE TITLE
Product: "update" CTA should only be displayed when a change is made

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-ios#1968]
Right now, when I open a product page, I see the "Update" CTA by default on the top right corner of the screen. Let's have this CTA only show when there's something to update, so when the user makes an edit to the page. 

<img width="866" alt="Screen Shot 2020-03-13 at 5 46 08 PM" src="https://user-images.githubusercontent.com/28450084/76642066-ddbb8880-6552-11ea-926f-31ce32881155.png">

**Comment by jaclync** [comment]
Fixed in https://github.com/woocommerce/woocommerce-ios/pull/1989, closing
