### ISSUE TITLE
Empty states: search products

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1974]
Ref p99K0U-1Zy-p2:

Currently, the results UI is just empty when there are no search results on the Search Products screen. Let's update the results UI to the empty states design (design links in p2): 

<img width="148" alt="Screen Shot 2020-03-16 at 2 09 58 PM" src="https://user-images.githubusercontent.com/1945542/76727767-e9e05980-678f-11ea-9321-5fc25766d5df.png">

**Comment by pmusolino** [comment]
Since we reuse the `SearchViewController` used for searching Orders, we need to update at the same time the empty state for orders. 👍
