### ISSUE TITLE
Stats 4.0: changes required to stop support for the old v3 stats UI 

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-ios#1975]
After we retire the old stats (date to be confirmed as to when this will take place), if site version is <4.0 or WC admin manually disabled, we would need to display an empty screen to the user:

<img width="300"  src="https://user-images.githubusercontent.com/22608780/76737494-e4ceda80-678e-11ea-879a-f95c228182c8.png">

**Comment by shiki** [comment]
This was done in #2521.
