### ISSUE TITLE
Edit Products: app crashes after visiting the tax class list selector screen a few times

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1978]
I haven't found consistent steps to repro, but I've had it at least twice after performing these steps:
- Go to the Products tab
- Tap on a simple Product
- Tap on the price settings
- Tap on the tax class row to see a list of tax classes
- Navigate back
- Repeat the above 2-3 steps a few times

My guess is that the app was in the middle of inserting the remote tax classes to the storage while navigating away from the tax class list selector screen. Maybe we missed some teardown step there, or we can skip saving the remote tax classes to the storage (though it might make it harder to add caching for https://github.com/woocommerce/woocommerce-ios/issues/1954)

Crash reports:
- https://sentry.io/organizations/a8c/issues/1397122471
- https://sentry.io/organizations/a8c/issues/1566577566

**Comment by pmusolino** [comment]
This is the crash I get when I try to replicate the issue on simulator:

```
2020-03-16 16:14:44.999079+0100 WooCommerce[20269:2860835] [error] error: Serious application error.  Exception was caught during Core Data change processing.  This is usually a bug within an observer of NSManagedObjectContextObjectsDidChangeNotification.  *** Collection <__NSCFSet: 0x6000038e5170> was mutated while being enumerated. with userInfo (null)
CoreData: error: Serious application error.  Exception was caught during Core Data change processing.  This is usually a bug within an observer of NSManagedObjectContextObjectsDidChangeNotification.  *** Collection <__NSCFSet: 0x6000038e5170> was mutated while being enumerated. with userInfo (null)
2020-03-16 16:14:45.006371+0100 WooCommerce[20269:2860835] *** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSCFSet: 0x6000038e5170> was mutated while being enumerated.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c6e150 +[__NSFastEnumerationEnumerator allocWithZone:] + 0
	3   CoreData                            0x00007fff23835300 -[NSManagedObjectContext(_NSInternalChangeProcessing) _processDeletedObjects:] + 272
	4   CoreData                            0x00007fff238226be -[NSManagedObjectContext(_NSInternalChangeProcessing) _propagatePendingDeletesAtEndOfEvent:] + 88
	5   CoreData                            0x00007fff2381dfec -[NSManagedObjectContext(_NSInternalChangeProcessing) _processRecentChanges:] + 774
	6   CoreData                            0x00007fff237f8f27 _performRunLoopAction + 365
	7   CoreFoundation                      0x00007fff23bd3867 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	8   CoreFoundation                      0x00007fff23bce2fe __CFRunLoopDoObservers + 430
	9   CoreFoundation                      0x00007fff23bce97a __CFRunLoopRun + 1514
	10  CoreFoundation                      0x00007fff23bce066 CFRunLoopRunSpecific + 438
	11  GraphicsServices                    0x00007fff384c0bb0 GSEventRunModal + 65
	12  UIKitCore                           0x00007fff48092d4d UIApplicationMain + 1621
	13  WooCommerce                         0x000000010b08c1f1 main + 497
	14  libdyld.dylib                       0x00007fff5227ec25 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by pmusolino** [comment]
I tried to investigate this crash for around 2 hours... I wasn't able to find an effective solution, but I discovered something new.

> Maybe we missed some teardown step there

I went deeper into the `TaxClassStore` class, which has nothing different from other Stores classes. Seems that this crash is more frequently here because we download every time the info, and we delete/push them into the DB while we are trying to fetch the information (we subscribe to every change in `PaginatedListSelectorViewController`). This is why we get this error `Collection <__NSCFSet: 0x6000038e5170> was mutated while being enumerated` and also the error `This is usually a bug within an observer of NSManagedObjectContextObjectsDidChangeNotification.`.

I think this problem could, therefore, occur not only here, but generally everywhere. Until now it has not popped up because in other places the data do not have this update frequency.

I have a concern about what happens if a new `didChange` arrives while the `performBatchUpdates` is processing the previous batch. Maybe there is a race condition.

Interesting related question and answer I found: https://stackoverflow.com/questions/47614583/delete-multiple-core-data-objects-issue-with-nsfetchedresultscontroller

**Comment by jaclync** [comment]
I looked more into the crash (also spent lots of time reproducing the crash since it didn't happen every time), and I think the issue was from calling `saveIfNeeded` on the main Core Data context inside an async `perform` block of its child context:

```swift
    func upsertStoredTaxClassesInBackground(readOnlyTaxClasses: [Networking.TaxClass], onCompletion: @escaping () -> Void) {
        let derivedStorage = sharedDerivedStorage
        derivedStorage.perform {
            self.upsertStoredTaxClasses(readOnlyTaxClasses: readOnlyTaxClasses, in: derivedStorage) // crashed
        }

        storageManager.saveDerivedType(derivedStorage: derivedStorage) {
            DispatchQueue.main.async(execute: onCompletion)
        }
    }
```

where the `derivedStorage` is a child context of the main context. Inside `derivedStorage.perform`, `upsertStoredTaxClasses(readOnlyTaxClasses:in:)` calls `resetStoredTaxClasses(onCompletion:)`:

```swift
    func resetStoredTaxClasses(onCompletion: () -> Void) {
        let storage = storageManager.viewStorage
        storage.deleteAllObjects(ofType: Storage.TaxClass.self)
        storage.saveIfNeeded() // crashed!
        DDLogDebug("Tax Classes deleted")

        onCompletion()
    }
```

I saw some problems calling `resetStoredTaxClasses(onCompletion:)`:
- we generally don't want to save the child context in the middle of a series of updates (deleting existing tax classes and then inserting new ones from remote data), especially since we're already saving the child context at the end of `upsertStoredTaxClassesInBackground(readOnlyTaxClasses:onCompletion:)`
- even if we want to save the child context, it should be saving its own context and not **its parent context (`storageManager.viewStorage`)**

I'm not super sure what are the consequences of saving a parent context inside a child context's async block 🤔for now, I'm planning on removing the call to `resetStoredTaxClasses(onCompletion:)` and just deleting the existing tax classes with a simple call without saving the context

**Comment by jaclync** [comment]
closing for now from https://github.com/woocommerce/woocommerce-ios/pull/1991, we can reopen when we see crashes again
