### ISSUE TITLE
Edit Products: extract view data logic from view controller to a separate view model

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1985]
With the introduction of discard changes action sheet, the logic becomes more complicated especially when fixing price and inventory settings in https://github.com/woocommerce/woocommerce-ios/pull/1979. I intended to add unit tests in that PR, but it wasn't suitable for a release hot fix. Let's spend a little time extracting the view data logic from the view controller to a separate view model for the following screens just to start:

- [x] `ProductPriceSettingsViewController`
- [x] `ProductFormViewController`: thread https://github.com/woocommerce/woocommerce-ios/pull/1977#discussion_r393014680
- [x] `ProductInventorySettingsViewController` https://github.com/woocommerce/woocommerce-ios/pull/2602
- [ ] `ProductShippingSettingsViewController` https://github.com/woocommerce/woocommerce-ios/pull/2714

**Comment by shiki** [comment]
I also would not be opposed to incrementally extracting the complex parts of the code to **Use Cases** / **Interactors** like this [Domain Layer example](https://tech.olx.com/clean-architecture-and-mvvm-on-ios-c9d167d9f5b3#3dc5) so they can be individually tested.

**Comment by jaclync** [comment]
Moving this to M2 since this doesn't block M1
