### ISSUE TITLE
Edit Product: enable editing basic fields for non-core products

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-ios#1998]
As discussed internally, we need to enable editing product title and description for all product types. Currently, editing is only enabled for Simple products.

Based on the discussion (CGPNUU63E/p1596617913064000?thread_ts=1596591699.062300-slack), we will support the following fields for products that don't have a core product type (simple/variable/external/grouped):

- Name
- Description
- Images
- Price settings (readonly)
- Inventory (readonly)
- Short description
- Categories
- Tags

And all of the product settings.

After this issue, we can delete the old `ProductDetailsViewController` and related code!

**Comment by pmusolino** [comment]
This is scheduled for Products M3 👍

**Comment by jaclync** [comment]
I updated the issue for us to support non-core products on iOS in M3!
