### ISSUE TITLE
Settings > Experimental Features: add back the Products switch for M2 features

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2042]
Since we temporarily remove the Experimental Features > Products switch in https://github.com/woocommerce/woocommerce-ios/issues/2033 for release 4.0, let's add back the switch to turn on/off Edit Products M2 features when we are ready to launch M2!

- [x] Show M2 switch in settings, and enable M2 features based on the switch value https://github.com/woocommerce/woocommerce-ios/pull/2275
- [x] Show different copy in Products tab banner https://github.com/woocommerce/woocommerce-ios/pull/2283

- M2 switch off: `Limited editing available` — `We've added editing functionality to simple products. Keep an eye out for more options soon!`
- M2 switch on: `New editing options available` — `We've added more editing functionalities to products. You can now update images, see previews and sort, filter & share products!`

Design update
- [ ] Collapse the banner by default https://github.com/woocommerce/woocommerce-ios/pull/2300

**Comment by anitaa1990** [comment]
Just wanted to add here that we also need to update the Products WIP banner as mentioned in the design:

<img width="596" alt="Screenshot 2020-04-30 at 11 05 10 AM" src="https://user-images.githubusercontent.com/22608780/80675620-8fe2eb80-8ad2-11ea-860f-218333b5f8ae.png">

Based on the designs, we would need to update the WIP banner based on the beta switch being turned on/off.

<img width="300" alt="Screenshot 2020-04-30 at 11 05 32 AM" src="https://user-images.githubusercontent.com/22608780/80675658-a426e880-8ad2-11ea-9c06-ed7751c18eeb.png">

**Comment by astralbodies** [comment]
Let's also make sure to include a bit in the release notes indicating that the M2 features are available for beta testing.
