### ISSUE TITLE
Product shipping class - shipping class not set since shipping class name is not found

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-ios#2064]
If product shipping classes haven't been fetched yet, then the shipping settings screen doesn't show the shipping class even when one is assigned to the product.

<img src="https://user-images.githubusercontent.com/22608780/78015596-3bc7d880-7367-11ea-82a7-06832f00dcf5.gif" width="300"/>

**Comment by jaclync** [comment]
fixed in https://github.com/woocommerce/woocommerce-ios/pull/2107, closing now!
