### ISSUE TITLE
Edit Products: manage product tags

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2081]
- [ ] Show product tags on the edit product main screen (and in the bottom sheet when it's ready)
<img width="194" alt="Screen Shot 2020-04-03 at 2 11 25 PM" src="https://user-images.githubusercontent.com/1945542/78329843-3f509f00-75b5-11ea-87f0-2beff9792779.png">

- [ ] Edit product tags: we will follow the design in WPiOS for this milestone (ref slack-C6H8C3G23/p1585918083161600), and we can update to the Woo design below in the future
<img width="711" alt="Screen Shot 2020-04-03 at 2 11 10 PM" src="https://user-images.githubusercontent.com/1945542/78329808-2d6efc00-75b5-11ea-8e2a-3ef932497030.png">

**Comment by pmusolino** [comment]
> Edit product tags: we will follow the design in WPiOS for this milestone 

Seems that the slack post no longer exists (or it refers to the wrong thread). Do you have more info about it @jaclync? Do you remember where the discussion happened? 🙇‍♂️

**Comment by jaclync** [comment]
hey @pmusolino ! yes, the thread is at slack-C6H8C3G23/p1585905360150100 (not sure why the ref didn't work anymore). there were some third-party library suggestions for the token list UI, and we're going to use the same post tags UI as in WPiOS at least for Products M3.
