### ISSUE TITLE
Edit Variable Products: edit product variation

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2085]
More details in p91TBi-33Q-p2

Differences between Product and Product Variation screens:

- Edit product main screen
  - A “Visible” row where the user can show/hide a product variation - will be implemented in https://github.com/woocommerce/woocommerce-ios/issues/2511
  - [x] Product variation name row is now readonly https://github.com/woocommerce/woocommerce-ios/pull/2588
  - [x] Hide the ellipsis menu from the navigation bar for a product variation https://github.com/woocommerce/woocommerce-ios/pull/2588
- Product images screen
  - [ ] Update UI to be https://github.com/woocommerce/woocommerce-ios/pull/2589
![image](https://user-images.githubusercontent.com/1945542/89001966-6c784880-d32e-11ea-9a27-4ae34bde732a.png)
  - [ ] Remove trash icon in the image details due to an API issue #2576  https://github.com/woocommerce/woocommerce-ios/pull/2589
- Price settings screen
  - [x] Remove tax section (tax class, tax status) https://github.com/woocommerce/woocommerce-ios/pull/2566
- Inventory settings screen
  - [x] Remove “Limit one per order” (`sold_individually`) field https://github.com/woocommerce/woocommerce-ios/pull/2579
  - [x] When "Manage stock" toggle is disabled, the stock status is readonly (from the parent product) https://github.com/woocommerce/woocommerce-ios/pull/2588
- Shipping settings screen
  - [x] Hide the shipping class row due to an API issue https://github.com/woocommerce/woocommerce-ios/pull/2588

**Comment by jaclync** [comment]
hey @Garance91540! I'd like to clarify the product type options for a product variation:

<img width="134" alt="Screen Shot 2020-05-20 at 3 21 24 PM" src="https://user-images.githubusercontent.com/1945542/82417215-cd251280-9aad-11ea-8e00-746675221dd4.png">

for a product variation, we can't change the product type since it's part of a variable product. so I think the "product type" here is to set the "virtual" field like in core:

<img width="300" alt="Screen Shot 2020-05-20 at 3 27 06 PM" src="https://user-images.githubusercontent.com/1945542/82417643-6ce2a080-9aae-11ea-89b6-18d22bc892ce.png">

in this case, I think we can use the "Physical product" and "Virtual product" options in the original design?

<img width="200" alt="Screen Shot 2020-05-20 at 3 28 24 PM" src="https://user-images.githubusercontent.com/1945542/82417811-a9ae9780-9aae-11ea-9b28-8ad61114f25c.png">

**Comment by Garance91540** [comment]
Hi @jaclync , I started a convo in Slack I think it might be easier to talk through this!

**Comment by Garance91540** [comment]
Based on our convo on slack, we'll be adding a new product type "Variant product", next to the "Physical" and "Virtual" products
