### ISSUE TITLE
Any chance to use WooCommerce Mobile App without Jetpack?

### ISSUE THREAD

**Issue by poehaldur** [woocommerce/woocommerce-ios#2097]
There is no functionality I need from Jetpack. I only need an app to check my store orders. Is there a way to connect to my store without installing Jetpack?

**Comment by pmusolino** [comment]
Hi @poehaldur, and thanks for asking!

Jetpack is required because there are limitations in either XML-RPC and the core WordPress API which Jetpack API allows us to work around easily, and some features that can only be provided by a plugin.

Please refer to our FAQ page for more details:
https://woocommercehalo.wordpress.com/faq/

If you have other questions, don't hesitate to ask, or to contact our customer support from the app!

**Comment by s-a-s-k-i-a** [comment]
Is it possible to provide a simple plugin for that, if so, why don't you provide this? Without jetpack overload?

**Comment by ignacyhologa** [comment]
Jetpack is now offering separate plugins for specific functionality. Which one are the required one to make the woocommerce app working?

**Comment by pmusolino** [comment]
Hello there @s-a-s-k-i-a @ignacyhologa. You can use the `Jetpack Connection Package`, which is basically a way to use our mobile apps without the jetpack overload. Some plugins include it by default, like WCPay or WCShip.

**Comment by rwkyyy** [comment]
@pmusolino do you have a sample plugin with JetPack Connection Manager so one might try to implement? Not have to build.

**Comment by pmusolino** [comment]
@rwkyyy hi there. You could use WCPay and WCShip, both are free.

**Comment by rwkyyy** [comment]
@pmusolino you mean the WooCommerce Payments and WooCommerce Shipping & tax?

**Comment by pmusolino** [comment]
@rwkyyy exactly 👍

**Comment by rwkyyy** [comment]
OK, that's great, but I do not use any of them 🤦‍♂️ but it's better than jetpack so.. it's a start.

**Comment by almogbu** [comment]
https://wemanage.app/

woocommerce app without jetpack
Amazing app for ios and android

**Comment by israelb12** [comment]
> https://wemanage.app/
> 
> woocommerce app without jetpack Amazing app for ios and android

the best!!!!!
