### ISSUE TITLE
Improvement: ResultsController ReadOnly Caching

### ISSUE THREAD

**Issue by jleandroperez** [woocommerce/woocommerce-ios#210]
### Details:
As of now, ResultsController does not keep a cache of `ReadOnly` entities (Sections and NSMO).
Let's implement a caching mechanism that considers:

- Low Memory Notifications
- All of the possible flows in which the cache might get invalidated

**Comment by shiki** [comment]
Since we're _slowly_ replacing ResultsController with DiffableDataSource, I'll just close this for now. We'll create new issues for DiffableDataSource when problems come up. 😅
