### ISSUE TITLE
Order Details > Products: the image isn't shown for product variations

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2113]
When an order includes a product variation purchase, the image isn't shown in Order Details > Product section for the item even though the variation does have an image (example screenshots below).

I looked into the issue for a bit, and it seems like there are 2 issues:

## Issue 1

The first issue is where we request the missing products for an order - currently, we only request missing products but not product variations.

https://github.com/woocommerce/woocommerce-ios/blob/9971547b8c2c7e76ce09ff5035c008bc7282ba8d/Yosemite/Yosemite/Stores/ProductStore.swift#L114-L127

## Issue 2

When fetching the missing products (`ProductAction.requestMissingProducts`), we make an API request `wc/v3/products?include={{list_of_product_or_variation_ids}}`.  However, the `wc/v3/products`'s `include` parameter with a list of remote IDs only includes posts with post type (`post_type` in the database) `product` while the variations are of `product_variation` type. Therefore, we cannot use the same `wc/v3/products` endpoint to request missing product variations.

I think we can fix this by:
- Add a `ProductVariationAction` to request missing product variations similar to the `ProductAction` used to fetch missing products (that aren't in the storage yet): `wc/v3/products/{{product_id}}/variations?include={{list_of_variation_ids}}` - it seems like we need both the product & product variation ID(s) to make a request per product, so there could be multiple API requests for the missing variations.
- Similar to https://github.com/woocommerce/woocommerce-ios/blob/9971547b8c2c7e76ce09ff5035c008bc7282ba8d/Yosemite/Yosemite/Stores/ProductStore.swift#L114, with the difference that we need to know both the product and product variation ID.

All product variations | Order details with 2 product variations
-- | --
![Simulator Screen Shot - iPhone 11 - 2020-04-09 at 12 52 05](https://user-images.githubusercontent.com/1945542/78859218-4b2edc00-7a61-11ea-9d8d-755d8ec0a4cf.png) | ![Simulator Screen Shot - iPhone 11 - 2020-04-09 at 12 52 08](https://user-images.githubusercontent.com/1945542/78859228-508c2680-7a61-11ea-8c13-ea21065fadae.png)

**Comment by pmusolino** [comment]
Similar issue here: https://github.com/woocommerce/woocommerce-ios/issues/1945

**Comment by shiki** [comment]
I can confirm that this still happens on version 5.6.
