### ISSUE TITLE
Drop iOS 11 support

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2115]
Ref: p91TBi-2Dj-p2

Now that the iOS 11 usage in our app is less than 1% based on Tracks and App Store Connect (details in the p2 post), let's drop the iOS 11 support in our project! (it's also confusing where the project-level deployment target is iOS 12 while the WooCommerce target is iOS 11, as pointed out by @pmusolino earlier)

**Comment by astralbodies** [comment]
Confirming that this is slated for no earlier than 4.2 to give our iOS 11 users two releases with the initial products list and simple editing features.

**Comment by pmusolino** [comment]
Then, we can move it to 4.3? @astralbodies

**Comment by astralbodies** [comment]
Ah yes, you're correct, develop right now is 4.2 and we want develop next sprint, so 4.3.
