### ISSUE TITLE
Product Detail → The full product name is not shown 

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2116]
## Describe the bug

In Product Detail, the product name is not fully displayed if it's too long. 

### VoiceOver

When VoiceOver is turned on, there is no mention that this is the "name" of the product. 

## To Reproduce

1. Go to Products 
2. Pick a product with a really long name

## Screenshots

<img src="https://user-images.githubusercontent.com/198826/78895894-d04bce00-7a2c-11ea-9e39-bdfb25e6392c.png" width="320">

## Expected behavior

I'm not sure if we should even support multiline. What do you think, @Garance91540?

**Comment by Garance91540** [comment]
Oh yes that's pretty inconvenient! I think we should support multiline since there's no other way to see the product's title if it doesn't fit in one line
