### ISSUE TITLE
Products List → Full product name is not shown

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2119]
The product name is not fully shown in the Products List.

&nbsp;  | &nbsp;
--------|-------
<img src="https://user-images.githubusercontent.com/198826/78897517-8d3f2a00-7a2f-11ea-959e-f2a2f3532b16.png" width="320">      |       <img src="https://user-images.githubusercontent.com/198826/78897563-9defa000-7a2f-11ea-99f7-a963d14850ed.png" width="320">

Is this by design, @Garance91540?

**Comment by Garance91540** [comment]
I think we probably set a max of 2 lines. IMO that's good enough! Users can select the product and see the full title on the Product detail screen. I'd worry about overcrowding the Product list if we showed all products with super long names.

**Comment by shiki** [comment]
Great! Thanks for confirming!
