### ISSUE TITLE
Orders → Section Titles are not Updated 

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2136]
## Describe the Bug

The section titles do not automatically update whenever the date changes.

<img src="https://user-images.githubusercontent.com/198826/79242185-37a0be00-7e31-11ea-9a41-ee78589e2526.png" width="320">

## To Reproduce

1. Navigate to Orders. Make sure to use an account that has existing Orders.
2. Set the device's clock to **tomorrow**
3. Go back to the app. 

The Orders list will still show "Today" for Orders that are supposed to be for yesterday. 

## Notes

This could be a contributing factor to https://github.com/woocommerce/woocommerce-ios/issues/1543. 

## Expected Behavior

The section titles should automatically update. 

## Isolating the Problem 

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

## Mobile Environment

- Device: iPhone 8 Plus
- iOS version: 13.2.1
- WooCommerce iOS version: `develop`

**Comment by itsmeichigo** [comment]
Setting this as low-priority (more like won't fix) because (1) the section titles can be updated after refreshing the list and (2) this is not a common use-case. Plus the effort can be high.

**Comment by shiki** [comment]
Thanks for cleaning up, Huong! I agree. Might as well close this.
