### ISSUE TITLE
Color Palettes contain the wrong colors

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#2138]
**Describe the bug**
gray shade0 is now drawing in as red, shade0, alpha 95%, all over the app. I do not know how many other colors are incorrectly coded.

**Context**
When dark mode was first introduced (5 months ago), Color-Studio.blog version 2.2.1 released the new color palette. Color-Studio's assets changed (3 months ago). A new version was not released when the color corrections were made, so nobody was notified of the changes.

When [Xcode 11.4 was released](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_4_release_notes), Apple added `dynamic system gray colors to inspector color pickers`. One can only guess that other behind-the-scenes color changes occurred.  

Combine the incorrect color palette assets with Xcode 11.4, and now we're seeing the strange tinge.

**To Reproduce**
1. Use Xcode 11.4 to see the color palettes now getting rendered and used in the apps
2. Build and run from develop
3. Log out of the app
4. Log in. Notice that the listBackground gray is actually red shade 0.

**Screenshots**
| Xcode 11.3 | Xcode 11.4 |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/1062444/79278354-28416500-7e71-11ea-87d1-2d45896fe7a1.png" /> | <img src="https://user-images.githubusercontent.com/1062444/79278357-29729200-7e71-11ea-9f9b-68c5269e86a7.png" /> |

**Expected behavior**
Re-import the [Color Palette assets](https://github.com/Automattic/color-studio/tree/2.2.1/dist/ios/ColorStudioPalette.xcassets). Problem fixed. The only downside to importing the color palette wholesale is that other color changes have occurred. I do not know which other colors were the wrong shades that were also updated.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone SE
- iOS version: ~13.4~ 12.4 (edit: Xcode 11.4.1 no longer uses the Color Palette directly for 13.4 sims) 
- WooCommerce iOS version: any version that has the app built and released using Xcode 11.4

**WordPress Environment**
n / a

**Comment by jaclync** [comment]
@mindgraffiti I wasn't able to reproduce the background color issue on a build from Xcode 11.4 (same on an iOS 13.4 device), not sure if I missed anything? which types of device did you see this issue on?

<img width="526" alt="Screen Shot 2020-04-15 at 5 11 07 PM" src="https://user-images.githubusercontent.com/1945542/79320312-390add00-7f3c-11ea-97f4-1f97f8a4500d.png">

**Comment by mindgraffiti** [comment]
Ooh weird. @jaclync I tested it on the iPhone SE, iOS 13.4. I can also reproduce it on an iPhone XR. 
I tried it on an iPhone 11 sim and see the normal colors. It's odd that it's device specific!

<img src="https://user-images.githubusercontent.com/1062444/79340376-d4c22c00-7eef-11ea-9b80-76b6ef9c86e1.png" width="400" />

**Comment by shiki** [comment]
This is weird. I can't seem to reproduce this using Xcode 11.4 on the recent `develop` (97f0582).

iPhone SE 13.4 | iPhone XR 13.4
--------|-------
![iphone-se-13 4](https://user-images.githubusercontent.com/198826/80397196-041f5400-8873-11ea-8a49-d69c2d8c93cd.png)        |       ![iphone-x4-13 4](https://user-images.githubusercontent.com/198826/80397206-07b2db00-8873-11ea-8dfe-d39d13e11cc8.png)

Am I testing this incorrectly? 😅

**Comment by mindgraffiti** [comment]
Hey @shiki 👋 

So I updated to Xcode 11.4.1 and I no longer see the color palettes used directly by any of the iOS 13.4 device sims. I do still see it on the 12.4 device sims. This is iPhone SE, iOS 12.4, this morning on the `develop` branch:

<img src="https://user-images.githubusercontent.com/1062444/80398730-b65c1900-887d-11ea-9656-cdb0d22b0f22.png" width="350" />

**Comment by shiki** [comment]
Thank you, @mindgraffiti! 🙇 I see it now using Xcode 11.4 and iPhone SE 12.4. 

![image](https://user-images.githubusercontent.com/198826/80418609-f084e500-8894-11ea-88f8-df12ccb6ed62.png)

**Comment by shiki** [comment]
This issue is a blocker for #2471.

**Comment by shiki** [comment]
I tried to tackle this today and I have no idea what's happening. Or what's wrong. Or how to fix it. 😅 

First, I commented out this line to force the app to use gray shade 0. 

https://github.com/woocommerce/woocommerce-ios/blob/66d9e2403fa0126ba3c1193677e072e99a7e8d86/WooCommerce/Classes/Styles/UIColor%2BSemanticColors.swift#L381-L383

And then I tested it in various Xcode and simulator combinations. 

### iPhone SE 12.4

Xcode 11.2.1 | Xcode 11.6
--|--
![xcode-11 2 1-iPhoneSE-12 4](https://user-images.githubusercontent.com/198826/87738867-96ad0080-c79b-11ea-8cd4-23312b2e29de.png) | ![xcode-11 6-iPhoneSE-12 4](https://user-images.githubusercontent.com/198826/87738928-bba17380-c79b-11ea-8449-5b7b435fd4ba.png)

### iPhone 8 12.2

Xcode 11.2.1 | Xcode 11.6
--|--
 ![xcode-11 2 1-iPhone8-12 2](https://user-images.githubusercontent.com/198826/87738864-957bd380-c79b-11ea-8a1b-e9d230ffa2cf.png) |  ![xcode-11 6-iPhone8-12 2](https://user-images.githubusercontent.com/198826/87738924-b9d7b000-c79b-11ea-939b-b66f7b929ce4.png)

### iPhone 11 13.6

Xcode 11.3 | Xcode 11.6
--|--
![xcode 11 3 - iPhone 11 13 6](https://user-images.githubusercontent.com/198826/87739520-4cc51a00-c79d-11ea-8bb0-a88b71adb655.png) | ![xcode 11 6 - iPhone 11 13 6](https://user-images.githubusercontent.com/198826/87739153-67e35a00-c79c-11ea-8f6b-9e072ea3e416.png)

---

As shown above, the colors seem to be the same no matter what Xcode version I use. I wonder if this is how the color is really supposed to look like?

I also used the Digital Color Meter app to look at what color the simulators are showing and they seem to be the same values as the [Gray0.colorset](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Resources/ColorPalette.xcassets/Gray0.colorset/Contents.json). 

Maybe it's all okay? 🤪 Also, I'm no expert when it comes to colors so I'm most probably misunderstanding a lot of things here.

**Comment by jaclync** [comment]
I was having a hard time telling the color difference, posting a screenshot from my iOS 12.1 device here for comparison:

<img src="https://user-images.githubusercontent.com/1945542/87740299-71a8a400-c814-11ea-8c8f-2507ef93bdc1.PNG" width="320" />

**Comment by shiki** [comment]
I don't believe this is valid anymore since the minimum iOS version is now 13 and we've recently changed the login UI.
