### ISSUE TITLE
Improve VoiceOver support in Product Price screen

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#2160]
As reported by @shiki [here](https://github.com/woocommerce/woocommerce-ios/pull/2158), we don't offer good VoiceOver support in the Product Price screen. 

As shown in [this video](https://drive.google.com/file/d/1033QAq6kB7b0Dn9obi2G4SxKevcslBLZ/view?usp=sharing), it can be challenging to understand what's happening because VoiceOver is reading things out of sequence (hear for example how the price was pronounced).

**Comment by shiki** [comment]
I wrote an idea for how this should work in https://github.com/woocommerce/woocommerce-ios/pull/2158#issuecomment-617205164
