### ISSUE TITLE
Shipping Labels M1: UI to display shipping labels purchased for an order

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-ios#2167]
Landing on the Order Detail screen will now give you the option to view shipping label details for an order.

Prerequisite: https://github.com/woocommerce/woocommerce-ios/issues/2164
Dev plan: p91TBi-3Lo-p2

### Order details > shipping label card

- [x] Display shipping label cards for an order with partial UI https://github.com/woocommerce/woocommerce-ios/pull/3188
- [x] Show aggregated order items for a shipping label (the logic is quite complicated) https://github.com/woocommerce/woocommerce-ios/pull/3197
- [x] Sync missing variations for an order https://github.com/woocommerce/woocommerce-ios/pull/3278
- [x] Polish order item rows without a price/quantity https://github.com/woocommerce/woocommerce-ios/pull/3254
- [x] Show ellipsis menu in the card header if the shipping label hasn't been refunded https://github.com/woocommerce/woocommerce-ios/pull/3209
- [x] Add “Don’t know how to print from your phone?” CTA row (the screen is implemented in #2174) https://github.com/woocommerce/woocommerce-ios/pull/3230
- [x] Update design for tracking number row with two actions: https://github.com/woocommerce/woocommerce-ios/pull/3226
  - “Copy tracking number”: same as existing copy tracking number action
  - “Track shipment”: opens a webview with a URL based on the carrier and tracking number (this is implemented in https://github.com/woocommerce/woocommerce-ios/issues/2564) ([Android code](https://href.li/?https://github.com/woocommerce/woocommerce-android/blob/26590149ffa14773b49758e13a215e1e00168d75/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/ShipmentTrackingUrls.kt))
- [x] Hide Shipment tracking sections if an order has non-empty shipping labels https://github.com/woocommerce/woocommerce-ios/pull/3268
- [x] The Products section only shows products/variations that aren't in a non-refunded shipping label https://github.com/woocommerce/woocommerce-ios/pull/3268

### Polishes

- (Moved to https://github.com/woocommerce/woocommerce-ios/issues/3334) Hide separators of "Reprint Shipping Label" CTA and remove top spacing in the printing info row (requires refactoring of `TopLeftImageTableViewCell` to use Auto Layout)
- (Moved to https://github.com/woocommerce/woocommerce-ios/issues/3334) Update "House" icon to outlined house icon (either by adding a new one to Gridicons or exporting to a PDF)

### Expanded shipping details

- [x] Implement a separate screen that displays expanded shipping details for a shipping label https://github.com/woocommerce/woocommerce-ios/pull/3277

- Payment method: hard coded to "Credit card" for now, until we can get the last 4 digits of credit card from the API in the future

<img width="300" alt="Screenshot 2020-04-21 at 8 57 52 PM" src="https://user-images.githubusercontent.com/22608780/79884468-d3729100-8412-11ea-9888-e23234903186.png">. <img width="300" alt="Screenshot 2020-04-21 at 8 58 01 PM" src="https://user-images.githubusercontent.com/22608780/79884458-d077a080-8412-11ea-8ead-d03722f76458.png">

**Comment by jaclync** [comment]
Moved the polish subtasks to https://github.com/woocommerce/woocommerce-ios/issues/3334, closing this issue!
