### ISSUE TITLE
Products: change the product type from simple to variant, grouped or external product

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#2198]
As part of Products M3, we want to offer the possibility to change the product type from simple to variant, grouped, or external product. 

- [ ] When editing `ProductFormActionsFactory`, let's also update the enabled features to be an array of feature flags like discussion in https://github.com/woocommerce/woocommerce-ios/pull/2357#pullrequestreview-421995127
 
Feel free to divide this issue into more detailed subtasks.

<img src="https://user-images.githubusercontent.com/495617/80390667-07cfcc80-88ad-11ea-81b2-d5b3be06305e.png" width=400 />

**Comment by jaclync** [comment]
the product type row is added in https://github.com/woocommerce/woocommerce-ios/issues/2262 - this issue implements the update action that sets the product's `productType` and also updates the available fields in the product form
