### ISSUE TITLE
Products: edit an existing grouped product

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#2199]
As part of Products M3, we should provide a way to edit an existing grouped product.

Feel free to split this issue into more subtasks.

- [x] display a grouped product with readonly properties for the new row (linked products) https://github.com/woocommerce/woocommerce-ios/pull/2449
- [x] editing products for the grouped product
  - [x] Networking & Yosemite layer changes https://github.com/woocommerce/woocommerce-ios/pull/2459
  - [x] Product cell: selected state, accessory view https://github.com/woocommerce/woocommerce-ios/pull/2483
  - [x] existing grouped products screen with delete functionality https://github.com/woocommerce/woocommerce-ios/pull/2505
  - [x] adding grouped products screen https://github.com/woocommerce/woocommerce-ios/pull/2517
  - [x] adding grouped products screen - search https://github.com/woocommerce/woocommerce-ios/pull/2541
- [ ] more unit tests: `ProductsRemote` and `ProductStore` on `loadProducts`'s new params (`pageNumber` and `pageSize`) (Ref https://github.com/woocommerce/woocommerce-ios/pull/2505#discussion_r455203673)

<img width="421" alt="Screen Shot 2020-06-18 at 3 25 35 PM" src="https://user-images.githubusercontent.com/1945542/84990631-02d61d80-b178-11ea-8757-d923fcd99d5b.png">

This is the entire flow:
<img src="https://user-images.githubusercontent.com/495617/80395967-40bf6f80-88b4-11ea-9e5b-191185224617.jpg" width=800 />

**Comment by jkmassel** [comment]
We're freezing version `4.7` today, so I'm bumping this to `4.8`. If you need this to be part of `4.7`, please merge this PR into `release/4.7` and DM me – I'll be happy to cut a new beta release!
