### ISSUE TITLE
Products: edit an existing external product

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#2200]
As part of Products M3, we should provide a way to edit an existing external product.

- [x] schema update:
  - [x] add `buttonText: String` field to `Product` that corresponds to `button_text` field in the API response https://github.com/woocommerce/woocommerce-ios/pull/2391
  - [x] Networking + Yosemite layers https://github.com/woocommerce/woocommerce-ios/pull/2392
- [x] display an external product with readonly properties for the new rows (product link, attributes) https://github.com/woocommerce/woocommerce-ios/pull/2432:
  - always shown in the settings section: price, product type (implemented in https://github.com/woocommerce/woocommerce-ios/issues/2262), product link
  - bottom sheet actions: attributes (edit action is implemented in https://github.com/woocommerce/woocommerce-ios/issues/2385), SKU, categories, tags, short description

![external products flow ios](https://user-images.githubusercontent.com/495617/80397036-dc9dab00-88b5-11ea-8188-a609ae0b0b92.jpg)

- [x] editable product link https://github.com/woocommerce/woocommerce-ios/pull/2442
<img width="156" alt="Screen Shot 2020-06-04 at 4 03 08 PM" src="https://user-images.githubusercontent.com/1945542/83731325-e7015080-a67c-11ea-8442-4f9321ea5378.png">

- [ ] editing product link followup: local validation for external URL
- [ ] editing product link followup: auto-fill button text with "Buy product" when the external URL field becomes non-empty

- [x] editable SKU https://github.com/woocommerce/woocommerce-ios/pull/2437
<img width="231" alt="Screen Shot 2020-06-04 at 4 01 46 PM" src="https://user-images.githubusercontent.com/1945542/83731215-b9b4a280-a67c-11ea-8bad-e2cd95044488.png">

**Comment by jkmassel** [comment]
We're freezing version `4.7` today, so I'm bumping this to `4.8`. If you need this to be part of `4.7`, please merge this PR into `release/4.7` and DM me – I'll be happy to cut a new beta release!

**Comment by jaclync** [comment]
Moved the 2 design enhancements to a separate task https://github.com/woocommerce/woocommerce-ios/issues/2609 so that we can close the main issue now
