### ISSUE TITLE
Orders: Predicate is not refreshed

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2202]
In All Tabs, the `resultsController` `predicate` should be refreshed on `viewWillAppear`

This bug happens in All Tabs.

1. Run the app with a one-month-old date.
2. Navigate to All Orders
3. Set the device date back to today
4. Pull-to-refresh to All Orders. 

All Orders will be empty or no **recent orders** will be shown. The list will still show orders that were created more than a month ago.

## Possible Solution.

Maybe the predicate can be refreshed on the next query so that the date in the query condition is updated too.

**Comment by shiki** [comment]
Tackling this may also fix #2136.

**Comment by shiki** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/woocommerce/woocommerce-ios/issues/2202](https://trello.com/c/WjThnjuq/2-https-githubcom-woocommerce-woocommerce-ios-issues-2202)

**Comment by pmusolino** [comment]
@shiki is this something that should be still handled?

**Comment by shiki** [comment]
@pmusolino Thanks for bringing this to my attention. I tested this and this is still valid. And I just realized that this may be the reason why we have user reports saying that the orders are **not updated**. 😬 We should definitely get this fixed ASAP!

I updated the description to add more info.
