### ISSUE TITLE
Orders → Search: Status totals aren't updated with remote changes until order list is refreshed

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#2250]
**Describe the bug**

In https://github.com/woocommerce/woocommerce-ios/pull/2208 we added the total number of orders of a given status in Orders → Search.

However, if a new order is received or an order status is changed remotely, the order list updates immediately to show the new order/status but the status totals in Orders → Search don't change until the order list is refreshed (e.g. with a pull to refresh).

cc @shiki 

**To Reproduce**

1. Open the Orders tab and check the Processing badge count on the tab.
2. Open Orders → Search and confirm the Processing status count matches the badge count.
3. Receive a new order with Processing status on your store.
4. Notice the order appears in the orders list and the Processing badge count on the Orders tab updates.
5. Open Orders → Search and notice the Processing status count hasn't changed.
6. Go back to the orders list and pull to refresh.
7. Open Orders → Search and notice the Processing status count is now correct.

**Screenshots**

Orders badge (accurate count)|Status totals (outdated count)
-|-
<img src="https://user-images.githubusercontent.com/8658164/81302954-fb006500-9072-11ea-898b-328a59eb1a40.PNG" width="300px">|<img src="https://user-images.githubusercontent.com/8658164/81302943-f6d44780-9072-11ea-9ae2-23c7612d69ba.PNG" width="300px">

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.4.1
- WooCommerce iOS version: 4.2.0.0 TestFlight beta

**Comment by shiki** [comment]
Also experienced by Jaclyn when testing #2820 → https://github.com/woocommerce/woocommerce-ios/pull/2820#pullrequestreview-489447474

**Comment by itsmeichigo** [comment]
Closing this issue because this seems like an outdated design and we're no longer showing the order status list when searching order now. Let me know if I'm missing something 😅.
