### ISSUE TITLE
Orders Empty States are not vertically aligned

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2252]
## To Reproduce

1. Use the #2245 branch
2. Navigate to Orders → Search
3. Make sure the keyboard is shown if you're using the simulator. 
4. Pick a filter that is empty.

This seems to be related to the `KeyboardFrameObserver` usage in `EmptyStateViewController`. 

---

More reproducible steps from Garance at p5T066-2p9-p2#comment-8783: 

1. Navigate to Products 
2. Tap on plus button. 
3. Pick Variable product. 
4. Enter a text in the title. Make sure the keyboard is present if you're using the simulator.
5. Abort everything and go back to the Products list. 
6. Tap on plus button again. 
7. Pick Variable product.
4. Tap on Add variations row. This is the result:
    <img src="https://user-images.githubusercontent.com/198826/131171391-2e9bb862-856b-43f1-b278-06db97ba6df3.png" width="300">
 
## Expectations

The content should be vertically centered.

**Comment by shiki** [comment]
In-progress at [issue/2215-orders-empty-state-vertical-alignment](https://github.com/woocommerce/woocommerce-ios/tree/issue/2215-orders-empty-state-vertical-alignment) but pausing for now.

**Comment by Ecarrion** [comment]
Update: Also happening in variations
