### ISSUE TITLE
Order Detail: Order Status Cell wrong cell appearance

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#2256]
Navigating to an Order Detail -> Order Status, and selecting the last cell, the end separator is not shown, so it seems that the cell its part of the background.

<img src="https://user-images.githubusercontent.com/495617/81335878-9a8c1a80-90a8-11ea-9b8b-269a8f9bcfce.png" width=300 />

## Mobile Environment
- Device: iPhone Xs simulator
- iOS version: 12.2
- WooCommerce iOS version: 4.2

**Comment by pmusolino** [comment]
@Garance91540 what should be the correct behavior here? Always show the separator?

**Comment by Garance91540** [comment]
oh that's weird. yes let's show the bottom separator

**Comment by pmusolino** [comment]
After a quick investigation, seems that the separator is present, but since it has the same color as the background, it's not visible. What do you suggest to do in this case?

<img width="820" alt="Schermata 2020-05-20 alle 19 47 45" src="https://user-images.githubusercontent.com/495617/82479604-e5f3ef00-9ad2-11ea-9da0-12e96d84c1a5.png">

**Comment by Garance91540** [comment]
Actually @pmusolino looking at our existing selecting states, it seems like we are keeping the row background color white when selected https://d.pr/i/eAjvQi

Could we do the same here?
