### ISSUE TITLE
Edit Products: add product type row

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2262]
Original discussion: https://github.com/woocommerce/woocommerce-ios/pull/2217#issuecomment-624100123

Let's add a product type row to product form (simple products for now) based on the design:

<img width="259" alt="Screen Shot 2020-05-11 at 9 29 33 AM" src="https://user-images.githubusercontent.com/1945542/81516352-26809980-936a-11ea-8509-aef370f3f15b.png">

Possible product types:

Simple product
Grouped product
External product
Variable product
Custom product type name (e.g. subscriptions)

---

from the design, it seems like we currently have 4 product types:
- Physical product
- Virtual product
- Grouped product
- External product

<img width="381" alt="Screen Shot 2020-05-11 at 9 36 03 AM" src="https://user-images.githubusercontent.com/1945542/81516561-d9e98e00-936a-11ea-911a-594df7e43143.png">

@Garance91540 I have some questions for this feature:

### Question 1

Could we display the product type as in core/API instead of categorizing a product into one of the 4 options above (so that we show "Simple product"/"Grouped product"/"External/Affiliate product"/"Variable product"/other custom product from the product type field)? some reasons I can think of:
- For variable products, each variation has its own virtual/downloadable options so that a variable product might offer a mix of virtual and physical services. In these cases, we can't simply categorize a variable product as a physical or virtual product
- There could be many other custom product types from plugins. For example, subscriptions and booking are common product types from support rotation

### Question 2

Could we only display the product type on editable simple products for M2? The design looks quite different from non-simple products that are readonly now (example screenshot below). I understand that Android might have implemented in a different way so that all product types share the same updated design, while iOS only updated the design for editable product types (simple products for M2). since we're making more product types editable in the upcoming products releases and deprecating the readonly product screens like in the screenshot, I thought we could spend time on supporting more editable product types rather than changing the readonly product screens that we're deprecating in the near future.

<img src="https://user-images.githubusercontent.com/1945542/81517391-609f6a80-936d-11ea-985d-08f47b815a9e.png" width="320" />

**Comment by Garance91540** [comment]
Hi @jaclync !

>Could we display the product type as in core/API instead of categorizing a product into one of the 4 options above (so that we show "Simple product"/"Grouped product"/"External/Affiliate product"/"Variable product"/other custom product from the product type field)? 

That's fine by me! Is it possible to communicate that change on the mobile-woo-asynch-meeting slack room for visibility with android devs too and make sure there were no other underlying reasons why we chose to implement it differently? I'll update the designs accordingly. 

Are we supporting "/other custom product from the product type field" any time soon? 

> Could we only display the product type on editable simple products for M2? 

sounds good

**Comment by jaclync** [comment]
> Are we supporting "/other custom product from the product type field" any time soon?

I think for the scope of our Products project, we are supporting the product types in core for now - so just **simple, variable, grouped, external/affiliate** product types. It would be nice if we could start supporting other popular product types that aren't in core after the Products work 🙂

**Comment by jaclync** [comment]
@Garance91540 do you know if we want to update the copy for the product type action sheet now that we have different options from the design?

<img width="381" alt="Screen Shot 2020-05-11 at 9 36 03 AM" src="https://user-images.githubusercontent.com/1945542/81516561-d9e98e00-936a-11ea-911a-594df7e43143.png">

now the options are:

- Simple product
- Variable product
- Grouped product
- External product

the copy for the Grouped and External products from the design looks good, just the Simple and Variable product options need updates!

**Comment by jaclync** [comment]
ℹ️ update - after chatting with @Garance91540 via DM, we will keep the physical/virtual product options for simple product type in core with `virtual` field off/on, respectively:

- Physical product (`type` is `simple`, `virtual` field is off)
- Virtual product (`type` is `simple`, `virtual` field is on)
- Variable product (`type` is `variable`)
- Grouped product (`type` is  `grouped`)
- External product (`type` is `external`)

(the copy for Variable product option will be updated separately)

**Comment by Garance91540** [comment]
Hi @jaclync! I summarized the latest product types decisions [here](https://woomobilep2.wordpress.com/2020/06/03/products-product-types-updates-and-final-states-design/). And I updated the product type bottom sheet in Figma https://d.pr/i/AAIO01
