### ISSUE TITLE
Remove the separator between Password protected and Password in Product Visibility

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#2274]
- [ ] Remove the separator between Password protected and Password rows in Product Visibility

![Screen Shot 2020-05-11 at 09 53 44](https://user-images.githubusercontent.com/495617/81751959-c5afa900-94b0-11ea-82f8-181e83f9cf77.png)

**Comment by rachelmcr** [comment]
I started looking into this issue; here are some notes from my investigation.

To start, I wanted to remove the separator by updating this reusable cell configuration:

https://github.com/woocommerce/woocommerce-ios/blob/2ac34dd3fb92773e913534fc502865ed1a426cc9/WooCommerce/Classes/ViewRelated/Products/Edit%20Product/Product%20Settings/Visibility/ProductVisibilityViewController.swift#L208-L213

I tried adding this block to hide the separate on the Protected Password row, when it's selected:

```
        // Hide separator between password protected and password when selected
        if row == .passwordVisibility && row.visibility == visibility {
            cell.hideSeparator()
        } else {
            cell.showSeparator()
        }
```

This works if the product visibility setting is Public or Private to begin with, but it doesn't work if the product visibility setting is already Password Protected. In the latter case, the Password Protected separator never shows up, even after selecting other visibility settings:

<img src="https://user-images.githubusercontent.com/8658164/104731863-3b50d080-5734-11eb-8611-ba0ab40891a5.gif" width="300px">

I investigated and tried other approaches, but whenever a cell is initially configured with `hideSeparator()` there's no way I can find to get `showSeparator()` to work correctly later. We couldn't find the underlying cause of this while debugging (internal ref: p1610644525015300-slack-C70PAM3RA), so a workaround could be just to not reuse cells on this screen.
