### ISSUE TITLE
Woo logo on launch screen is stretched out on

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-ios#2289]
On launch screens of iPhone 11 pro, Woo logo appears stretched out. 

<img width="706" alt="Screen Shot 2020-05-14 at 11 13 42 AM" src="https://user-images.githubusercontent.com/28450084/81916598-4915eb00-95d4-11ea-9725-0dc9c12e532f.png">

**Comment by pmusolino** [comment]
Hi @Garance91540. 

I'm able to see it correctly. Can you try to delete the app and reinstall it? 
Maybe you are updating the app from a really old version, and the [launch screen has been cached](https://stackoverflow.com/questions/33002829/ios-keeping-old-launch-screen-and-app-icon-after-update). 

<img src="https://user-images.githubusercontent.com/495617/82915945-aa916e80-9f71-11ea-9785-31c6cb555d5b.png" width=300 />

**Comment by Garance91540** [comment]
it seems to work now after I deleted the app and installed again! Thanks!
