### ISSUE TITLE
Editing product from order doesn't save change.

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-ios#2292]
When I select a product in an order and make a change (ie "Price"), it's doesn't actually save this change in the Product . 

It's normal that this change isn't reflected in the product in the order, but it should be reflected in the product moving forward. 

For example, if I open order #12, select Product 1, and change its price from $50 to $40, the price of Product 1 in order #12 should still be $50. 

However, if I open Product 1 from order #12 or from the Product tab, its price should now be $40.

https://cloudup.com/cux7YGxMRfZ

**Comment by pmusolino** [comment]
Hi @Garance91540, the bug has already been fixed here https://github.com/woocommerce/woocommerce-ios/pull/2233, and will be available in the next release. 👍
