### ISSUE TITLE
Outstanding changes method in ProductImagesViewController always return false

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#2305]
The method `hasOutstandingChanges()` in `ProductImagesViewController` always returns false. We need to fix it since it returns wrong data to our analytics. 
More here: https://github.com/woocommerce/woocommerce-ios/pull/2296#discussion_r425792156

**Comment by jaclync** [comment]
I just tested tapping Done from product images editing with and without changes, and `product_image_settings_done_button_tapped` seems to be fired with the corresponding `has_changed_data` attribute. In Tracks, the event also has 91% true and 9% false. Closing this issue now!
