### ISSUE TITLE
Login: Google login with account not linked to WordPress.com leads to signup flow

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#2313]
**Describe the bug**

When I choose to log in with Google, using a Google account not linked to a WordPress.com account leads to a signup flow within the app. We don't fully support signup in the app, yet I can still sign up and end up logged in to the app. This leads to a broken experience since I don't have a site.

**To Reproduce**

1. Start logged out of the app.
2. Tap "Log In."
3. Select the Google login option ("Log in with Google.")
4. When prompted, select or log in to a Google account that isn't linked to a WordPress.com account.
5. On the "Connected but..." screen, select "Sign up."
6. Notice that you are on a screen that says, "To create your new WordPress.com account, please enter your email address" with your Google account address pre-filled. Select Next.
7. Follow the prompts to open the magic signup link email and return to the Woo app.

Result: You end up logged in to the app with a new account, but nothing loads because you don't have a site.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/82214435-bba50480-990d-11ea-8a53-dfbb957afcd7.PNG" width="300px">

**Expected behavior**

I expect that the "Sign up" option won't be available in the Woo app. Instead, I expect that screen to only have options for logging in with a different email or with my site address.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.4.1
- WooCommerce iOS version: 4.2.0.0 TestFlight beta (although I expect this issue has always existed, since we enabled Google login)

**Comment by rachelmcr** [comment]
I checked and the analytics event `login_social_login_failure` is recording from the Woo app about 40-60 times per day, which gives an estimate of the number of users who could be affected by this. (I don't see any analytics that record how many users actually select the "sign up" option, but anyone who gets that error could try it.)

**Comment by jaclync** [comment]
This screen is in the WP Authenticator framework `LoginSocialErrorViewController`. Since Woo app isn't supporting sign up for the foreseeable future, let's disable the Sign Up option on this screen.

Perhaps we can use `authenticationDelegate.shouldPresentSignupEpilogue()` to determine whether the Sign Up option should be shown.

**Comment by rachelmcr** [comment]
I tested this again with the new UL&S (milestone 1) in the 5.7 beta and confirmed I am not given a signup option anymore. Closing as no longer valid.

<img src="https://user-images.githubusercontent.com/8658164/102376556-abe0c200-3fbb-11eb-8eb5-f0a4433593b1.png" width="300px">
