### ISSUE TITLE
Localize Address.fullName and related methods

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2314]
As mentioned in https://github.com/woocommerce/woocommerce-ios/pull/2298#discussion_r426330490, the strings in [`Address.fullName`](https://github.com/woocommerce/woocommerce-ios/blob/86dcbe87419b0aa2ddffb32d8c1ec91bb8b9fe83/WooCommerce/Classes/Model/Address+Woo.swift#L12-L14) and `fullNameWithCompany` should be localized.

It might be worth it to merge the localization methods that were created in https://github.com/woocommerce/woocommerce-ios/pull/2298.

**Comment by eshurakov** [comment]
What do you think about using [PersonNameComponentsFormatter](https://developer.apple.com/documentation/foundation/personnamecomponentsformatter) instead of localising it via `NSLocalizedString`?

**Comment by shiki** [comment]
I've never heard of that but it sounds like a good idea!
