### ISSUE TITLE
Variants: Edit An Attribute

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2322]
When the user taps on an existing product attribute from #2321 (the first screenshot below), the user is able to rename the attribute name and edit the options.

<img width="168" alt="Screen Shot 2020-05-20 at 4 26 50 PM" src="https://user-images.githubusercontent.com/1945542/82423885-00b86a80-9ab7-11ea-9e67-e7f3c444921d.png">

<img width="469" alt="Screen Shot 2020-05-20 at 4 24 26 PM" src="https://user-images.githubusercontent.com/1945542/82423514-6bb57180-9ab6-11ea-95cc-c12d78647ee1.png">

When the user taps "Done", we save the product attribute and then update the product's variations accordingly.

**Comment by shiki** [comment]
This is outdated and no longer follows the i2 plan (p91TBi-2Ur-p2). I will close this issue. 🙂
