### ISSUE TITLE
Products: Trying to view a draft product on the store leads to 404 error

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#2332]
**Describe the bug**

When I edit a draft product on my store, I have the option "View product on store" but it leads to a 404 error. (This also happens with any product that isn't publicly published, e.g. pending review and private products.)

Android issue: https://github.com/woocommerce/woocommerce-android/issues/2471

**To Reproduce**

1. Enable Product editing under Settings > Experimental features.
2. Go to the Products tab.
3. Select a draft product to edit it. (If you don't have a draft product, select a product and go to the ellipsis menu > Product settings and change the Status to Draft. Update the product to save the draft status.)
4. Go to the ellipsis menu > View product on store.

Result: Your store opens with a 404 error.

**Expected behavior**

I expect to either not have that "View product on store" option (if draft products can't yet be previewed) or for the webview to be authenticated so I can preview the draft product.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.4.1
- WooCommerce iOS version: 4.3.0.0 TestFlight beta

cc @pmusolino

**Comment by pmusolino** [comment]
Good catch @rachelmcr. We need to hide the option `View product on store` when the product is on a status different from "published".
