### ISSUE TITLE
Products: "Discard changes" prompt erroneously appears for some Product Settings

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#2333]
**Describe the bug**

If I edit the Slug, Purchase Note, and Menu Order product settings, the "Discard Changes" prompt appears when I try to go back. This is unexpected because there is no "Done" button or other way to save the changes I make to these settings until I go back to the Product Settings screen. (And even if I select "Discard Changes" the changes are saved.)

Once one of those settings is changed, just opening one of the other settings triggers the "Discard Changes" prompt, even if no changes are made.

**To Reproduce**

1. Enable Product Editing under Settings > Experimental Features.
2. Go to the Products tab.
3. Select a product.
4. Go to the ellipsis menu > Product Settings.
5. Under "More Options" select Slug.
6. Edit the slug and try to go back to the main Product Settings screen. Notice that the "Discard Changes" prompt appears.
7. Open the Purchase Note and Menu Order settings and go back without making any changes. Notice that the "Discard Changes" prompt appears.

**Expected behavior**

I expect to be able to make changes to each of the Product Settings and go back to the main Product Settings screen without seeing the "Discard Changes" prompt. I should only see that prompt if I try to exit the main Product Settings screen without saving my changes.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.4.1
- WooCommerce iOS version: 4.3.0.0 TestFlight beta

cc @pmusolino

**Comment by rachelmcr** [comment]
I just noticed that if I tap the Return key to dismiss the keyboard before going back, the discard changes prompt isn't triggered. But because the text field automatically has focus when I open each setting, I'm more likely to try to exit that screen while the keyboard is up/the text field has focus, which triggers the prompt.

**Comment by jaclync** [comment]
I was able to reproduce this issue by swiping back from the screens navigated from the product settings. It looks like it's because on swipe back, `ProductSettingsViewController` intercepts the swipe back gesture even though it's not the top view controller in the navigation stack

<img width="638" alt="Screen Shot 2020-05-25 at 5 01 33 PM" src="https://user-images.githubusercontent.com/1945542/82799038-fa0d6700-9eab-11ea-8f4b-6d4a440b453e.png">
