### ISSUE TITLE
Reviews: Remotely trashed review remains in app

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#2335]
**Describe the bug**

When a review is trashed remotely (e.g. via the web) it remains in the app, even after pulling to refresh or force-closing the app.

The trashed review wasn't removed from the app until I completely refreshed the Reviews screen, e.g. by switching stores and then switching back.

I'm not sure if this is related to https://github.com/woocommerce/woocommerce-ios/issues/1908 (an issue where reviews trashed from **within** the app remain in the app).

**To Reproduce**

1. View the Reviews list in the app.
2. On the web, trash a review (from the product details screen).
3. In the app, pull to refresh the Reviews screen and notice the review remains.
4. Notice you can open the review in the app, navigate to others and back, and even force-close the app and the review remains there.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.4.1
- WooCommerce iOS version: 4.2.0.1 and 4.3.0.0 TestFlight Beta

**Comment by shiki** [comment]
I ran into this today. The behavior seems to be inconsistent. Sometimes when trashing a review, it gets removed from the list right away. Sometimes the review does not get removed from the list but trashing it the second time will.

**Comment by pmusolino** [comment]
Discussion opened here p91TBi-3gI
