### ISSUE TITLE
Products: "Discard changes" prompt erroneously appears on Shipping

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#2336]
If I navigate to the Shipping screen of a Product, and I just press back, the Discard Changes action sheet is prompted, even though I haven't made any changes.

![2020-05-22 14-46-10 2020-05-22 14_46_45](https://user-images.githubusercontent.com/495617/82669099-15257000-9c3b-11ea-965e-34e5bd51116d.gif)

## Environment:
- Device: iPhone X
- iOS version: 13.5
- WooCommerce iOS version: 4.3

**Comment by jaclync** [comment]
I think this is the same issue as https://github.com/woocommerce/woocommerce-ios/issues/2263, which was fixed for release 4.4 in https://github.com/woocommerce/woocommerce-ios/pull/2301
