### ISSUE TITLE
Log messages/crashes in Storage framework

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2364]
Since the `CrashLogging` class that logs messages to Sentry is in the Tracks framework, and the message in `fatalError` does not show up in the crash log in Xcode/Sentry, it'd be great if we could log these fatal errors with debug message to Sentry.

**Comment by shiki** [comment]
Since we now have Encrypted Logging, we can make use of `DDLogError()`. https://github.com/woocommerce/woocommerce-ios/pull/2867 shows how this can be on in the Storage framework. I _think_ it will work.

**Comment by joshheald** [comment]
@jaclync it looks like your #2366 PR should have closed this issue. Is the `CrashLogger.logFatalErrorAndExit` sufficient, or should it be changed to use `DDLogError` as @shiki suggests, do you think?

**Comment by jaclync** [comment]
It looks like the PR https://github.com/woocommerce/woocommerce-ios/pull/2366 meant to close this issue but because it was targeting a release branch and not `trunk`/`develop` this issue remains open 😅 closing now, thanks for following up on this old issue Josh!
