### ISSUE TITLE
Untangle Core Data Setup and CrashLogging

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2370]
Found by @jaclync in p91TBi-2PM-p2#comment-860. When CrashLogging is initialized, the Core Data setup is also unexpectedly started because of this line: 

https://github.com/woocommerce/woocommerce-ios/blob/a10080aa477ba4388c7af5eb63f70ec813ddafd9/WooCommerce/Classes/Tools/Logging/CrashLogging.swift#L17-L24

**Comment by shiki** [comment]
This may help with #2371

**Comment by shiki** [comment]
Related discussion by @koke in paNNhX-f9-p2.

**Comment by itsmeichigo** [comment]
CrashLogging initialization seems to no longer be tangled with Core Data after the change in #10049. I've added the initialization of Core Data as part of the AppDelegate setup in #14013, so the order of initialization should be as follows:

CrashLogging > CoreDataManager > DefaultStoresManager.

I'll mark #14013 as closing this issue for now.
