### ISSUE TITLE
Crash on startup: NSPersistentContainer loading failure

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2371]
Found by @jaclync in p91TBi-2PM-p2. This is currently not tracked by Sentry.

For the 4.1 release, 196 devices were affected. 

---

- [ ] Investigate file access
- [ ] Investigate adding breadcrumbs
- [ ] Consider not crashing and show a message to the user instead
- [ ] Consider not deleting the databases inside the `loadPersistentStore` callback
- [ ] Consider signing the user out if we cannot recover

---

Improvements for `CoreDataManager` and Core Data related:

- [x] Fix Transformer errors/warnings in iOS 13 https://github.com/woocommerce/woocommerce-ios/issues/1372
- [ ] Use NSPersistentStoreCoordinator instead of FileManager in Core Data Backups https://github.com/woocommerce/woocommerce-ios/issues/2473
- [x] Replace `fatalError` with non-fatal error logging when failing to back up the pre-existing persistent store
- [x] Separate retrieval of all model versions to a separate class/struct with unit tests

**Comment by jaclync** [comment]
> Consider not crashing and show a message to the user instead

👍  If we really cannot recover from the Core Data setup, signing the user out would still be better than the app crashing consistently

**Comment by shiki** [comment]
@jaclync Do you think we should close this and the linked issues in Sentry?

**Comment by shiki** [comment]
As of August 17, 2020:

- 60k events
- No number of users recorded

**Comment by shiki** [comment]
I marked the Sentry issue as resolved but I'm leaving this open for now.

**Comment by shiki** [comment]
I'm going to close this now. We have significantly decreased the number of crashes. We do have a few startup crashes left which we'll be tracking in #2667.
