### ISSUE TITLE
External & Grouped Products: manage attributes

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2385]
The flow is very similar to the product variation attributes flow in https://github.com/woocommerce/woocommerce-ios/issues/2321, let's implement in a way so that it works for both with only visual differences.

<img width="1211" alt="Screen Shot 2020-06-04 at 3 41 03 PM" src="https://user-images.githubusercontent.com/1945542/83729163-dc918780-a679-11ea-8ef7-310370cdb35d.png">

**Comment by jaclync** [comment]
Moving this to M4 since it's the same flow as editing variation attributes

**Comment by shiki** [comment]
Based on our discussion, we will not be doing this for M5. We're also not sure **when** we should be working on this so I will close this issue for now. 

p91TBi-3LX-p2
