### ISSUE TITLE
Products → Manage Stock is Indented Differently

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2397]
## Describe the Bug

The “Manage Stock“ field is indented slightly more than the other fields on the screen. 

<img src="https://user-images.githubusercontent.com/198826/83909113-6b0f1300-a725-11ea-8552-d45abdf4dd63.png" width="320">

## To Reproduce

1. Navigate to a simple product
2. Navigate to inventory

## Expected Behavior

It should be aligned with the other fields. 

## Isolating the Problem 

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

## Mobile Environment

- Device: iPhone 8 Plus
- iOS version: 13.3.1
- WooCommerce iOS version: 4.4

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by jaclync** [comment]
this looks related to https://github.com/woocommerce/woocommerce-ios/issues/1933 - reopening it

**Comment by pmusolino** [comment]
I checked it, and in our release 4.9 the alignment is ok 🤔I'm going to close it for the moment.

<img src="https://user-images.githubusercontent.com/495617/91581632-f8da5300-e94e-11ea-8fb0-f2c3f7c1dd81.png" width=300 />
