### ISSUE TITLE
[Product Details][Price] Only displays sale price when > $0

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-ios#2400]
In the Product Details screen, if there's no sale price set, we should only display the "Regular price" amount. 

https://d.pr/i/Fkyo6D

**Comment by pmusolino** [comment]
I did a test, and now it's no more visible. Probably it was fixed in one of the previous [PR on price settings](https://github.com/woocommerce/woocommerce-ios/pulls?q=is%3Apr+price+settings+is%3Aclosed+).
