### ISSUE TITLE
[Product Details] [Variations] Can't see the variations list when selecting "Variations"

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-ios#2401]
On the product details screen, when I select the variation row, I get an error message and can't see the variation list.

https://cloudup.com/co4_r6oy1DS

To reproduce:
1. Open Product details screen for a products with variations. 
2. Select "Variations"

**Comment by jaclync** [comment]
hey @Garance91540, do you mind adding me to your site (jaclyn.chen at automattic.com) so I can see what caused the error when fetching the variations? I couldn't reproduce on my site, and I'd like to check if the response on your site

**Comment by Garance91540** [comment]
Added!
