### ISSUE TITLE
[Product Details] [Image] Enable right/left swipe on product images

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-ios#2403]
On the "Photos" screen, when a product has several images, can we enable right and left swipping to scroll through the different images? 

Here's a video of this interaction on the Etsy app:
https://cloudup.com/cAXEJc9AgBg

**Comment by pmusolino** [comment]
As discussed here p91TBi-366 we will follow the same behavior of Android  👍 If the swipe gesture isn’t too much work we could try to get it in for M3, otherwise later. I'll update the issue if something changes.
