### ISSUE TITLE
Add support for Catalan language in the app

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-ios#2419]
We have interest from an outside contributor to provide translations for the Catalan language (`ca` ANSI code I believe). `3042148-zen`

@jkmassel if we add Catalan to the app languages supported to open it up on GlotPress, does that automatically become one of the languages we send over to our agency for paid translation?

**Comment by shiki** [comment]
It looks like this has stalled. Let me know if we should keep it open. If we should, this should probably be in the Product Backlog.
