### ISSUE TITLE
v4 Top Performers: Add UI Support

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-ios#2423]
Use the new `wc-analytics` API endpoint for populating Top Performers if the site is either running WC 4.0 or has the WCAdmin plugin installed.

**Comment by AmandaRiu** [comment]
Related Android issue: https://github.com/woocommerce/woocommerce-android/issues/2538

**Comment by shiki** [comment]
Based on our research during the development of #2422, it looks like we don't need to change anything in the UI. The changes will only be in the API calls. That will be tackled in #2422.
