### ISSUE TITLE
Make GhostTableViewController Reusable

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2448]
As we've found in https://github.com/woocommerce/woocommerce-ios/pull/2255, the `UITableView.dataSource` switching caused by using `displayGhostContent()` and `removeGhostContent()` can cause crashes like https://github.com/woocommerce/woocommerce-ios/issues/1711. 

We should replace all those who use `displayGhostContent()` and `removeGhostContent()` directly and use `GhostTableViewController` as a **child view** instead. Similar to what was done in #2255. 

## What To Do

- [x] Move [`GhostTableViewController`](https://github.com/woocommerce/woocommerce-ios/blob/fba94b532d93f1330dadf6bb4e21492501832051/WooCommerce/Classes/ViewRelated/Dashboard/MyStore/TopPerformerDataViewController.swift#L321) outside of `TopPerformerDataViewController`. 
- [X] Make the new [`GhostTableViewController`](https://github.com/woocommerce/woocommerce-ios/blob/trunk/WooCommerce/Classes/ViewRelated/ReusableViews/GhostTableViewController.swift) more configurable with number of visble rows etc. 
- [x] Use `GhostTableViewController` in all places that use `displayGhostContent()`. An example is [PaginatedListSelectorViewController](https://github.com/woocommerce/woocommerce-ios/blob/fba94b532d93f1330dadf6bb4e21492501832051/WooCommerce/Classes/ViewRelated/ListSelector/PaginatedListSelectorViewController.swift#L294-L302). This should be split in multiple PRs.

**Comment by pmusolino** [comment]
@itsmeichigo recently extracted `GhostTableViewController` to be a reusable type that displays ghost animation over a table view. https://github.com/woocommerce/woocommerce-ios/pull/6387

**Comment by itsmeichigo** [comment]
I didn't know this issue exists 😅 I think my work can be further improved with configuration for the number of cells displayed. For now only the cell type is configurable.

**Comment by shiki** [comment]
Feel free to update the issue to what you think should be the enhancement considering the current state of the code. Or close it if it's not applicable anymore. 🙂 

This issue is now 2 years old and I don't have a good grasp of the state of the code anymore. 🤪

**Comment by itsmeichigo** [comment]
I just updated the issue to tick off one item and add a new one to the checklist ☑️

**Comment by joshheald** [comment]
Checked with @toupper and this is now complete 🥳
