### ISSUE TITLE
"Offline mode" UI banner

### ISSUE THREAD

**Issue by bummytime** [woocommerce/woocommerce-ios#248]
Per the i6 design, we need to display a user-facing banner when we are in offline mode:

<img width="463" alt="screen shot 2018-08-20 at 4 53 06 pm" src="https://user-images.githubusercontent.com/154014/44368813-bcd7a200-a499-11e8-84c0-05b15844f768.png">

**Comment by bummytime** [comment]
Ref: paCBwp-42-p2

**Comment by mindgraffiti** [comment]
Closing in favor of feature planning in Monday
