### ISSUE TITLE
Order Details: Flow status change

### ISSUE THREAD

**Issue by bummytime** [woocommerce/woocommerce-ios#249]
Putting this issue here as a placeholder for the "flow" status changes (fulfillment was handled in #9  and #122). The remaining ones appear to be:
* Payment Cleared
* Refund Order
* Cancel Order

<img width="575" alt="screen shot 2018-08-20 at 5 22 40 pm" src="https://user-images.githubusercontent.com/154014/44369954-d7137f00-a49d-11e8-9fd7-a37b72793420.png">

We should break these down into sub-issues.

### Why is this in MVLP and manual status change aren't?
**Context** p99K0U-C7-p2

**Comment by mindgraffiti** [comment]
Closing in favor of sprint planning in Monday.com. New issue can be created when Order Statuses redesign is ready. Ref p99K0U-26E-p2
