### ISSUE TITLE
Products: Shouldn't be able to schedule a sale without sale price

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#2496]
**Describe the bug**

@Garance91540 noticed it was possible to schedule a sale without entering a sale price. In that case it seems like the sale price is set to 0$. Can we display the following error message if users try to schedule a sale without entering a sale price?

![ios-add-price-1](https://user-images.githubusercontent.com/8658164/86480857-bd544b80-bd46-11ea-864b-c93b3ea01a5c.png)

##### Tested in Woo iOS 4.6.0.0 beta (internal ref: p5T066-1o1-p2#comment-5289)

To be worked by @caiobzen

**Comment by caiobzen** [comment]
Hello!
I was looking at the suggested UI _(to display a native alert regarding the empty salePrice)_ but I was looking at the code and all the other error messages on this particular screen are being displayed as "toast-like" alerts.
I was wondering if we shouldn't stick with that pattern for this case, ending up with something like this:
![image](https://user-images.githubusercontent.com/997521/129807885-710e82d3-b36b-437f-97b7-b1cf988d3913.png)
Any thoughts on that, @adamzelinski?

cc: @Ecarrion

**Comment by Ecarrion** [comment]
Good call Carlos!

I think we can drop the title("Cannot save changes") to be more in line to other error messages in that screen.

EG:
![IMG_4D4C2CC034CC-1](https://user-images.githubusercontent.com/562080/129810554-1fc984f5-0720-4fd0-bf96-4da41311db4d.jpeg)

What do you think @adamzelinski?

**Comment by ghost** [comment]
@Ecarrion yes, that looks good to me and looks the same as how we show it when you add a sale price with no price and hit done so let's go with that thanks :)
