### ISSUE TITLE
Orders: Support searching by custom order number

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#2507]
**Is your feature request related to a problem? Please describe.**

If a store uses custom order numbers (e.g. with the [Custom Order Numbers for WooCommerce](https://en-gb.wordpress.org/plugins/custom-order-numbers-for-woocommerce/) plugin), you can't search by order number in the app. Trying to search by the custom order number doesn't return any results.

**Describe the solution you'd like**

By default, the order `id` and `number` attributes are matching, e.g. `id` is `123` (integer) and `number` is `123` (string).

However, using the plugin mentioned above the order can have different attributes, e.g. `id` is `123` and `number` is `S123` with a prefix (or the numbers may not match at all). The Core REST API endpoint `/wp-json/wc/v3/orders/<id>` will return the custom order number as the `number` attribute, like this: `{"id":123,"parent_id":0,"number":"S123", ...`

The app should be able to search on that `number` field, not just the order ID.

**Additional context**

Searching by order ID|Searching by custom order number
-|-
![IMG_3705](https://user-images.githubusercontent.com/8658164/87424920-bd6d0a80-c5d4-11ea-823c-67ba8df363fd.PNG)|![IMG_3706](https://user-images.githubusercontent.com/8658164/87424913-bc3bdd80-c5d4-11ea-85d2-29a7993abb50.PNG)

Original report from a public beta tester, tested internally (internal ref: p5T066-1o1-p2#comment-5345)

**Comment by thewho2018** [comment]
Could this also be the reason why search does not work for my friend who imported orders from Shopify? with https://sv.wordpress.org/plugins/woocommerce-sequential-order-numbers/

**Comment by rachelmcr** [comment]
Hi @thewho2018! Sorry, this issue was originally reported quite a while ago — I just re-tested it and searching by a custom order number is now working when I try it on my end.

If search isn't working for your friend, please ask them to contact support for additional help and troubleshooting for their store. That way our support team can look at exactly what's going on there. They can contact support in the app by going to Menu > Settings > Help & Support > Contact Support.
