### ISSUE TITLE
Hide a variant product in Store

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#2511]
As part of Milestone 3, we want to give to the user the possibility to hide a variant of a product from the store.

- Whether the product variation is visible: `status` field is `private` or `publish`

This the option on the web
![Schermata 2020-07-15 alle 15 35 06](https://user-images.githubusercontent.com/495617/87551551-d3e89400-c6b0-11ea-82e3-ac312677126f.png)

This is what we expect to see on mobile:
![Schermata 2020-07-15 alle 15 34 38](https://user-images.githubusercontent.com/495617/87551578-dba83880-c6b0-11ea-8e8d-16b3b7e76ee3.png)

**Comment by jaclync** [comment]
I was planning on implementing this in https://github.com/woocommerce/woocommerce-ios/issues/2085 but we can leave this open too 😄
