### ISSUE TITLE
Edit Product: edit an existing variant

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#2512]
As part of M3, we want to offer a way to edit an existing variant of a product. 

Please, use these screenshots just as a reference, and check them on Figma, where you can find the latest version updated.

![Schermata 2020-07-15 alle 16 15 17](https://user-images.githubusercontent.com/495617/87556024-75beaf80-c6b6-11ea-8946-e42be69eaaf1.png)

**Comment by jaclync** [comment]
is this the same as this one https://github.com/woocommerce/woocommerce-ios/issues/2085 ?

**Comment by pmusolino** [comment]
@jaclync yup! I missed it. I'm going to close this issue.
