### ISSUE TITLE
Ghost tableview cells are selectable

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#2513]
While I was testing some screens, I discovered that while we show the ghost tableview, for example in Product List or in Product Variations, the user is able to select a cell. This happens on every screen where we use a ghost tableview.
It's a Non-blocking issue, but it needs to be fixed.

| Product List             |  Product Variations | Reviews
:-------------------------:|:-------------------------:|:-------------------------:
![Simulator Screen Shot - iPhone 11 Pro - 2020-07-15 at 16 41 04](https://user-images.githubusercontent.com/495617/87559347-778a7200-c6ba-11ea-9c6b-e16c0fbad841.png) | ![Simulator Screen Shot - iPhone 11 Pro - 2020-07-15 at 16 37 53](https://user-images.githubusercontent.com/495617/87559321-6fcacd80-c6ba-11ea-9a9c-90070fbee5b2.png) | ![Simulator Screen Shot - iPhone 11 Pro - 2020-07-15 at 16 43 58](https://user-images.githubusercontent.com/495617/87559369-7e18e980-c6ba-11ea-8406-190cc7d5da54.png)

**Comment by shiki** [comment]
lol

**Comment by raziqfarid** [comment]
@shiki Would love to work on this. Can you please assign this to me?

**Comment by shiki** [comment]
@raziqfarid Assigned. Thank you. 🙂 Let us know if you need help!
