### ISSUE TITLE
Add a switch to update whether a simple product is physical/virtual

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2514]
In product settings for a simple product, let's add a switch to update whether the product is virtual (on) or physical (off):

<img width="224" alt="Screen Shot 2020-07-16 at 9 05 01 AM" src="https://user-images.githubusercontent.com/1945542/87614804-a4cf3280-c743-11ea-8506-29c09c10f83f.png">

**Comment by pmusolino** [comment]
This is also valid for grouped and variable products?

**Comment by jaclync** [comment]
in core, simple products are the only product type that I saw with this "virtual" toggle. feel free to double check in core! this makes sense, since a grouped product is defined by a group of products and a variable product comprises of the variations

**Comment by pmusolino** [comment]
Perfect, thanks. I'll double check on Core
