### ISSUE TITLE
Settings: Notifications

### ISSUE THREAD

**Issue by bummytime** [woocommerce/woocommerce-ios#252]
Per the i6 Designs, the main settings screen contains the following notification options:

<img width="392" alt="napkin 88 08-21-18 10 02 17 am" src="https://user-images.githubusercontent.com/154014/44410122-5c904100-a529-11e8-93cb-539ca6e918a7.png">

Ref: #17 
Ref: #19

**Comment by shiki** [comment]
Discussed with Aaron and we decided to close this for now.
