### ISSUE TITLE
Make sure UI is not rounding decimals on top performers views

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#2542]
It seems like the iOS app is rounding decimals on the top performers' leaderboard.

Corroborate which is the expected behavior.

## Web
<img width="827" alt="web" src="https://user-images.githubusercontent.com/562080/88191626-430a3f00-cc01-11ea-8a4e-8428b7d55c31.png">

## App
<img width="413" alt="Screen Shot 2020-07-22 at 9 49 05 AM" src="https://user-images.githubusercontent.com/562080/88191654-4ac9e380-cc01-11ea-9806-5c27a893adb4.png">

**Comment by shiki** [comment]
@Garance91540 Should we keep the rounded decimals?

**Comment by Garance91540** [comment]
Since we are displaying rounded decimals on the chart for revenue numbers, let's apply the same behavior here for consistency!

**Comment by shiki** [comment]
Thanks, @Garance91540! 

@Ecarrion I'm gonna close this now. 🙂
