### ISSUE TITLE
[IAFeedback] Use Correct Generic Crowdsignal URL

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2545]
1. Acquire the Crowdsignal generic survey from Garance
2. Replace the temporary URL created in #2544
3. Confirm that WCAndroid is using the same URL

**Comment by Ecarrion** [comment]
I think we can close this.
@ThomazFB Can you confirm you already have the correct production URL?

**Comment by ThomazFB** [comment]
I can confirm @Ecarrion, we got the production URL just fine 👍
