### ISSUE TITLE
[IAFeedback] Customize Generic Crowdsignal Survey Style

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2546]
Customize the generic Crowdsignal survey (#2545) so that it matches the app colors. See [How do I create a custom survey style?](https://crowdsignal.com/support/how-do-i-create-a-custom-survey-style/) how this can be done.

- [x] Fix styling on Android.
- [x] Remove error icons for now until Crowdsignal is fixed.

**Comment by Ecarrion** [comment]
Was just checking this and it appears to be fully [CSS customization](https://crowdsignal.com/support/custom-survey-css/)
Should we bring someone on board to help out here, my CSS abilities are close to none! 😅 

cc @Garance91540 @astralbodies

**Comment by Garance91540** [comment]
Hi @Ecarrion , I see @shiki has done great job with CSS customization! https://d.pr/i/DvVtCQ So we are good to go here!

**Comment by shiki** [comment]
There is a slight problem with the styling for the survey. The Crowdsignal CSS editor duplicates backslashes and this causes the error icons to be broken. 

Desired | Reality
--------|-------
![](https://user-images.githubusercontent.com/198826/90457407-ab412900-e0b8-11ea-80dd-9204da7d17a5.png)| ![](https://user-images.githubusercontent.com/198826/90457399-a2e8ee00-e0b8-11ea-84f6-398f033d5dbd.png)      

I have reported the issue to Crowdsignal (link in p91TBi-2RL-p2#comment-1530).

**Comment by shiki** [comment]
I looked at how the CSS worked in Android (https://github.com/woocommerce/woocommerce-android/pull/2723) and it looks like the radio button can be improved. They're squares instead of circles. 🙃 

<img src="https://user-images.githubusercontent.com/198826/90771323-5831c680-e2b0-11ea-947b-add87c9d7db0.png" width="240">

I'll fix those next sprint.
