### ISSUE TITLE
[IAFeedback] Add “Give Feedback” and ”Dismiss” Buttons In Products Banner

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2547]
![image](https://user-images.githubusercontent.com/198826/88222125-bbcdc300-cc22-11ea-983c-4bb175543ef4.png)

The Give Feedback button will show a Crowdsignal survey. We should be able to reuse the component created in #2544. 

From Garance: Once users have interacted with the banner (either by sharing feedback or by clicking “Dismiss”), they’ll no longer see the banner. 

Ref p91TBi-2Ne-p2

**Comment by Ecarrion** [comment]
Closed in favor of https://github.com/woocommerce/woocommerce-ios/issues/2646 https://github.com/woocommerce/woocommerce-ios/issues/2647 https://github.com/woocommerce/woocommerce-ios/issues/2648
