### ISSUE TITLE
Remove currency from TopEarnerStatsItem

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#2549]
`TopEarnerStatsItem` has a currency field that is not being used. 

Aside from that, we don't have a way to populate it with the new leaderboards API.

Also, consider if a core data migration is required

**Comment by shiki** [comment]
Thanks for logging this issue, @Ecarrion. I think it's best to work on this once #2371 has settled down. 😬 I'll move this to the CI board for now. 

> Also, consider if a core data migration is required

I think no mapping model is needed for this.
