### ISSUE TITLE
Create a shared helper function for generating a date from string in unit tests

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2551]
Original discussion: https://github.com/woocommerce/woocommerce-ios/pull/2539#discussion_r459152372

In our tests, we have a bunch of helper functions that do the same - generating a `Date` from `String` with `DateFormatter.Defaults.dateTimeFormatter`. AFAIK, we have 2 functions like this:
- `func date(with dateString: String) -> Date` (in 14 classes)
- `func dateFromGMT(_ dateStringInGMT: String) -> Date` (in 4 classes)

Let's create a helper function that can be shared in these classes in tests, so that we don't have to make another function each time we need it :)

**Comment by joshheald** [comment]
Now used in 33 Test files
