### ISSUE TITLE
⛔️ Error loading dashboard: Dotcom Error: [woocommerce_rest_cannot_view]

### ISSUE THREAD

**Issue by Cloudore** [woocommerce/woocommerce-ios#2559]
Hello everyone,

I have been getting this error and cannot find a way to overcome it, I have tried singing in with wordpress, directly with my website address, changing the email accounts and nothing works. I understand from my research that the authentication is being refused, but I can't understand why, I am fully synced with Jetpack, the Jetpack Debug Tool says that there is no problem with my site. 

I though about disabling really simple ssl but didn't think that was the issue and didn't want to risk bringing down the site, is there a possibility that the app is trying to authenticate through http instead of https? I have on my website settings https everywhere.

This issue means "unable to load content" and "unable to refresh" is on every single tab. Weirdly though, my top performers of products bought while I had the app installed to appear, and when I get a new order I get the notification, as soon as I tap on it though it will open the app and not be able to refresh anyways.

I tried the support tab in the app but the zendesk was not able to connect either. 

If anyone has any idea on how I could approach this issue, it would be greatly appreciated

[text-40B8899EC397-1.txt](https://github.com/woocommerce/woocommerce-ios/files/4972590/text-40B8899EC397-1.txt)

**Comment by pmusolino** [comment]
Hi @Cloudore!

It seems an issue that our mobile support can handle, better than us. Please submit a ticket to us (mobile-support@woocommerce.com) or reach out to us in the app via the help menu so we can troubleshoot with you. 👍
