### ISSUE TITLE
Show unsaved changes alert when the user drags to dismiss the product selector search modal

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2561]
Original discussion: https://github.com/woocommerce/woocommerce-ios/pull/2541#pullrequestreview-455135957

Since a modal in iOS 13 can be dismissed by dragging down the modal, it'd be nice if we show the unsaved changes prompt when the user dismisses the product selector search modal with `UIAdaptivePresentationControllerDelegate`:

![adaptive-dismiss](https://user-images.githubusercontent.com/562080/88430967-0421e800-cdbf-11ea-8505-a28d3f4c6d4c.gif)

**Comment by shiki** [comment]
I experienced this today on an iPad. The experience is worse on an iPad because you can tap on a big area and the modal is dismissed right away. It is so easy to lose changes. 🙈
