### ISSUE TITLE
Shipping Labels M1: provide option to track a shipment in WCS

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-ios#2564]
**Update**: we only support tracking a shipping label with the latest product requirements (same in Android). The user cannot delete a shipping label but refund one.

---

As part of the M1 release, we need to provide an option to:
- Track a shipment from the shipping label, with or without the Shipment Tracking plugin.
- Delete a shipment from the shipping label **only if the Shipment Tracking plugin is available**.

#### Tracking shipment
- **With the Shipment Tracking plugin available:** Calling the GET shipment tracking list API endpoint will provide the list of shipment trackings for the order. We can then match the shipping label tracking number with the shipment tracking number to display the corresponding tracking link.
- **Without the Shipment Tracking plugin:** If the shipment tracking plugin is not available, we won't be able to use the GET shipmen tracking API endpoint. But WCS still displays the tracking link in `wp-admin`.  We need to [store the tracking link for each carrier in the app and we just need append the tracking Id for that shipping label to that link](https://github.com/Automattic/woocommerce-services/blob/develop/client/extensions/woocommerce/woocommerce-services/views/shipping-label/tracking-link.js), if the tracking link icon is clicked from the app.

#### Deleting shipment
- **With the Shipment Tracking plugin available:** Currently, if the ST plugin is available, we provide the option to delete the shipment id from the app. We just need to call the same DELETE shipment tracking API to delete the shipment.
- **Without the Shipment tracking plugin:** Deleting the shipment option is only visible if the ST plugin is available. If not, this option should not be displayed in the app.

<img width="300" alt="Screenshot 2020-07-28 at 11 45 21 AM" src="https://user-images.githubusercontent.com/22608780/88626208-df33ba80-d0c7-11ea-9c6d-d2ba14a7a598.png">

**Comment by jaclync** [comment]
@anitaa1990 do you know if the actions in this issue are still up to date? I don't see the delete action in Android 🤔  In Android, I see these two actions on the tracking number:

- Copy tracking number
- Track shipment

(My site has Shipment Tracking plugin activated)

<img src="https://user-images.githubusercontent.com/1945542/100561272-60f45880-32f3-11eb-9504-a34ca5621f19.png" width="300" />

**Comment by jaclync** [comment]
Updated the title & description to only track a shipping label following Android, after confirming with @anitaa1990 🙂
