### ISSUE TITLE
Consider adding a loading indicator while the survey loads

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#2571]
@Jaclyn mentioned that the survey takes around 1-2s to load.

We should consider adding a loading indicator if that improves the user experience

**Comment by shiki** [comment]
@Garance91540 What do you think about this?

**Comment by Garance91540** [comment]
@shiki @Ecarrion @jaclync I'm always in favor of adding more feedback to the user! Could you please send me a screencast of the current flow so I can see exactly where we would need the loading indicator?

**Comment by Ecarrion** [comment]
Sure @Garance91540 
Here is a quick gif capture.

![Survey-Load-Time](https://user-images.githubusercontent.com/562080/89189471-a1221500-d565-11ea-9db8-724fb7b61643.gif)
