### ISSUE TITLE
Support removing a product image from a product variation after it's fixed in the API

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2576]
Ref: p91TBi-34W-p2

As of writing, there is an issue on removing a product image from a product variation in the API. Let's re-enable this feature in the app after it's fixed in the API.

TBD: whether to support this with a WC version check or wait until the WC version with the fix has been widely adopted.

---

Corresponding Android issue: https://github.com/woocommerce/woocommerce-android/issues/3066

**Comment by anitaa1990** [comment]
This looks to be [fixed](https://github.com/woocommerce/woocommerce/pull/27299) on the API side in WooCommerce 4.7 release

**Comment by jaclync** [comment]
h/t to @astralbodies for the idea (Ref C6H8C3G23/p1603371688067800?thread_ts=1603285483.027300&cid=C6H8C3G23-slack)

Regarding how we handle stores without the fix (< WC 4.7), let's update the error message to `Sorry, image removal on product variations is supported in WooCommerce 4.7 or greater, please update your site` if they get a 404 error (ideally, there's an error code for this specific error).

**Comment by shiki** [comment]
@jaclync @anitaa1990 or @astralbodies  Just to clarify, is this the desired functionality?

1. Navigate to a variable product.
2. Tap on Variations. This should be the page:

    <img src="https://user-images.githubusercontent.com/198826/97627454-049ad200-19f1-11eb-937d-545deb88ceaf.png" width="300">

3. Tap on one of the variations. 
4. Tap on the image.
5. Tap on the delete button to delete the image. <--- is this the functionality that's missing?

At the moment, there is no button to delete. 

Also, I think I may have found a bug on iOS.

1. On the app, load the Products tab.
2. Navigate to a variable product → Variations → any variation. 
2. In wp-admin, delete that variation's image. Publish the changes.
2. Pull-to-refresh on the app.
3. Navigate to a variable product → Variations → any variation again. 

The (deleted) image is still there. ❌
