### ISSUE TITLE
External product: external URL & link button design enhancements

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2609]
There are two UX enhancements for editing an external product's external URL & link button from this PR https://github.com/woocommerce/woocommerce-ios/pull/2442:

- local validation for external URL (we have a helper `String+URLValidation` `isValidURL() -> Bool` if that helps)

<img width="171" alt="Screen Shot 2020-08-06 at 4 45 15 PM" src="https://user-images.githubusercontent.com/1945542/89511293-49eda000-d804-11ea-887c-dff1f3bf27dc.png">

- auto-fill button text with "Buy product" if the external URL field is empty in the beginning

**Comment by jaclync** [comment]
Sorry @Garance91540 I'd like to clarify more about auto-filling "Buy product" to the product's button text when it's empty. If the button text was empty before, the user lands on this screen and the button text field is auto-filled with "Buy product". When they tap "Done" to commit the changes on this screen, do we also commit the change on their button text as "Buy product" even if they didn't type it in themselves? So if they change nothing on this screen, and tap "Done", the "Update" CTA is shown on the product details screen.

**Comment by Garance91540** [comment]
>When they tap "Done" to commit the changes on this screen, do we also commit the change on their button text as "Buy product" even if they didn't type it in themselves? So if they change nothing on this screen, and tap "Done", the "Update" CTA is shown on the product details screen.

Correct, as soon as the user adds a link in the "Product URL" field, we automatically display "Buy product" as the button CTA, even if the user didn't add it (similar behavior in core).
