### ISSUE TITLE
Hide in-app feedback card when tapping on CTAs

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#2629]
#2537 Should be completed first

After tapping the "Could be better" or "I like it button" the in-app feedback card on the dashboard card should be hidden.

**Comment by Ecarrion** [comment]
@shiki should the card be dismissed when tapping the "Could be better" button or should we wait for the survey completion? 🤔

**Comment by shiki** [comment]
Thanks for creating this issue! 

I think it should be the same as the "I Like It" button so we should hide it right away. Or else, it would feel like we're *requiring* the feedback. If the user wants to give some feedback later, they can use the button that will be implemented in the settings (#2553).

**Comment by Ecarrion** [comment]
[Initial implementation here](https://github.com/woocommerce/woocommerce-ios/tree/issue/2669-hide-app-feedback-card) while #2537 is completed
