### ISSUE TITLE
[IAFeedback] Extend BannerView to support multiple action buttons

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#2646]
The new Product Banner view shows two action buttons at the bottom of the banner which is not currently supported.

<img width="677" alt="Screen Shot 2020-08-12 at 4 24 52 PM" src="https://user-images.githubusercontent.com/562080/90069771-608a7000-dcb8-11ea-9eec-8062594e14fc.png">

Tasks:
- [x] Modify BannerView to support multiple actions #2680 
- [ ] Modify ProductBanner to include the new CTAs

**Comment by Ecarrion** [comment]
Hey @Garance91540 I was playing with this view and it took me a while to realize that this is an android design 😅 

**This is how our current banner looks**
<img width="423" alt="current" src="https://user-images.githubusercontent.com/562080/90090310-4e74f580-dce9-11ea-8831-d86b02c0312c.png">


As you can see it only supports one action button. The "close" button we normally place it like an "X" instead of the "Chevron" icon that makes the banner collapsable.

If the banner should definitely have a dismiss button here are some mockups I came up with.

### Vertical Layout
<img width="417" alt="vertical" src="https://user-images.githubusercontent.com/562080/90090531-db1fb380-dce9-11ea-83b9-2931b5b5c4da.png">


### Horizontal Layout Equally-distributed
<img width="428" alt="horizontal-equal" src="https://user-images.githubusercontent.com/562080/90090557-ef63b080-dce9-11ea-8b37-1e359c76fd8a.png">

### Horizontal Layout Proportionally-distributed
<img width="424" alt="horizonta-proportional" src="https://user-images.githubusercontent.com/562080/90090572-fb4f7280-dce9-11ea-9182-7c9bd79494d7.png">

----

Do you have any preference or a different idea on how it should look?

cc @shiki

**Comment by Garance91540** [comment]
HI Ernesto! that's cool, I really like "Horizontal Layout Equally-distributed"! The only thing left is to update the icon so it matches the Android design speaker icon.
