### ISSUE TITLE
Support push notifications for multiple stores

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2682]
Paolo started working on handling push notifications for multiple stores in https://github.com/woocommerce/woocommerce-ios/pull/2013, there's still server side changes required but we can get the client side ready whenever.

One issue I noticed when testing Jayson's PR https://github.com/woocommerce/woocommerce-ios/pull/2669: when the app receives a push notification from a different store, it increments the notification count for Reviews tab badge and app badge number for the current store instead of the store the push notification originated.

https://github.com/woocommerce/woocommerce-ios/blob/3d8367b6b0b8d587911daaf92e7caf74424de7a6/WooCommerce/Classes/Notifications/PushNotificationsManager.swift#L217-L225

we probably want to use the store ID from the push notification payload instead of the default current store (which could be a different store when we support push notifications for multiple stores). This is probably pretty straightforward to do 🙂

Example notification payload:
```
[AnyHashable("post_id"): 2754, AnyHashable("type"): comment, AnyHashable("blog_id"): 161199960, AnyHashable("note_id"): 4848739093, AnyHashable("comment_id"): 6646, AnyHashable("aps"): {
    alert = "Jaclyn Chen left a review on Banana ice cream\U00a0\Ud83c\Udf68\Ud83c\Udf66: Perfect for the summer \Ud83d\Ude42";
    badge = 3;
    category = "replyto-comment";
    "content-available" = 1;
    "mutable-content" = 1;
    sound = default;
    "thread-id" = "comment-2754";
}, AnyHashable("blog"): 161199960]
```

**Comment by pmusolino** [comment]
Nice discovery! 💯

**Comment by shiki** [comment]
Thanks for creating the issue! I guess I missed this when testing. 😄 We'd definitely need to review things again once we get API support.

**Comment by shiki** [comment]
We're tracking support for all stores separately since we've considered this as a bigger project. I will close this for now since a single issue may not be enough. We'll reorganize. This information is still useful though so I linked to it.
