### ISSUE TITLE
[IAFeedback] Review accessibility

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2684]
Let's do an accessibility review for the UI components that we created during this project.

**Comment by Ecarrion** [comment]
Results of the audit

## InApp Feedback Card
Small | Large | RTL
---- | ---- | ----
<img width="407" alt="card-min" src="https://user-images.githubusercontent.com/562080/91063081-1fb52400-e5f3-11ea-8010-ce24ccb581c4.png"> | <img width="403" alt="card-max" src="https://user-images.githubusercontent.com/562080/91063064-1cba3380-e5f3-11ea-9329-11afcf123d60.png"> | <img width="409" alt="card-rtl" src="https://user-images.githubusercontent.com/562080/91063076-1f1c8d80-e5f3-11ea-9f39-6e3a848d6b58.png">


## Survey
Small | Large | RTL
---- | ---- | ----
<img width="400" alt="survey-min" src="https://user-images.githubusercontent.com/562080/91063302-702c8180-e5f3-11ea-8402-05ff839afeaa.png"> | <img width="404" alt="survey-max" src="https://user-images.githubusercontent.com/562080/91063301-6f93eb00-e5f3-11ea-8882-a7326cbb5b36.png"> | <img width="401" alt="survey-rtl" src="https://user-images.githubusercontent.com/562080/91063296-6c98fa80-e5f3-11ea-842c-aa5ff3f844f2.png">

Issue: https://github.com/woocommerce/woocommerce-ios/issues/2699

## Completion Survey
Small | Large | RTL
---- | ---- | ----
<img width="413" alt="completion-min" src="https://user-images.githubusercontent.com/562080/91063501-b386f000-e5f3-11ea-9732-0fc45c303ef1.png"> | <img width="200" alt="completion-max-1" src="https://user-images.githubusercontent.com/562080/91063494-b1249600-e5f3-11ea-8319-b25240a081ac.png"> <img width="200" alt="completion-max-2" src="https://user-images.githubusercontent.com/562080/91063503-b4b81d00-e5f3-11ea-973d-aa5dab8d3ee0.png"> |  <img width="404" alt="completion-rtl" src="https://user-images.githubusercontent.com/562080/91063505-b4b81d00-e5f3-11ea-9632-b279d4dbad57.png">



## Products Banner
Small | Large | RTL
---- | ---- | ----
<img width="403" alt="banner-min" src="https://user-images.githubusercontent.com/562080/91063866-1ed0c200-e5f4-11ea-95ec-09382c4ba952.png"> | <img width="200" alt="banner-max-1" src="https://user-images.githubusercontent.com/562080/91063850-1bd5d180-e5f4-11ea-87a3-9d03ecdc6f18.png"> <img width="200" alt="banner-max-2" src="https://user-images.githubusercontent.com/562080/91063865-1e382b80-e5f4-11ea-9141-aff1098ef036.png"> | <img width="408" alt="banner-rtl" src="https://user-images.githubusercontent.com/562080/91063871-1f695880-e5f4-11ea-8ba9-0d94e29e54a0.png">

Issue: https://github.com/woocommerce/woocommerce-ios/issues/2698

----

## VoiceOver
I tested voice over for the flows we built and found have a couple of thoughts:
- The survey webview has a couple of accessible items that could use a custom label/description, like the `*` indicating that a field is mandatory.
- The inApp Card should fire a layout notification to indicate that it disappeared from the screen upon tapping a CTA.
- The products banner should fire a layout notification to indicate that it disappeared from the screen upon tapping a CTA or when the chevron button that expands/collapses it is tapped.

@shiki  Not sure if those notes are worth creating issues for or are just something to consider in the future.

**Comment by shiki** [comment]
Great audit, @Ecarrion! 👏 

> The survey webview has a couple of accessible items that could use a custom label/description, like the * indicating that a field is mandatory.

I don't know how this works on HTML but we could probably submit an issue in the Crowdsignal repo. 

> The inApp Card should fire a layout notification to indicate that it disappeared from the screen upon tapping a CTA.
> The products banner should fire a layout notification to indicate that it disappeared from the screen upon tapping a CTA or when the chevron button that expands/collapses it is tapped.

Good catch. 🙂 While I think this is ideal, it's probably not necessary because there would new screens that will pop up after the tap. So the user will be taken out of the existing screen anyway and the layout notification will not be useful. 

> when the chevron button that expands/collapses it is tapped

This one I think we should do since the user will stay on the screen. But probably part of [Continuous Improvements](https://github.com/woocommerce/woocommerce-ios/projects/11).
