### ISSUE TITLE
[IAFeedback] Survey WebView Accessibility

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#2699]
parent #2684 

The survey web view has some accessibility problems:

- It does not support dynamic type.
- ist not aligning content on RTL setups.

---

- We also need to corroborate that it is properly localized.

# Screenshots

## XXL Font
<img width="404" alt="survey-max" src="https://user-images.githubusercontent.com/562080/91063301-6f93eb00-e5f3-11ea-8882-a7326cbb5b36.png"> 

## RTL
<img width="401" alt="survey-rtl" src="https://user-images.githubusercontent.com/562080/91063296-6c98fa80-e5f3-11ea-842c-aa5ff3f844f2.png">

**Comment by shiki** [comment]
@Ecarrion Since the WebView contents are from Crowdsignal, how much of this can we fix? I wonder if it's possible to _pass_ a font-size to WebKit. 🤔 

As for localization, I could not find information in Crowdsignal if that is supported. But we could probably ask.

**Comment by Ecarrion** [comment]
# Dynamic type

@shiki I did some investigation and you can use apple font types in order to get what we want. [ref](https://useyourloaf.com/blog/using-dynamic-type-with-web-views/)

I played a bit with the CSS but I had to remove all the fixed font-sizes in order to work. The downside is that all the hardcoded line-heights made it look terrible.

I didn't felt comfortable modifying more, since I don't know what most of those CSS ids/classes mean and I don't have a way to test on Android.

Do you want to give it a spin?

**Comment by Ecarrion** [comment]
# Localization
Asked the crowdsignal team and apparently we can't have fully localized surveys.

A workaround could be to create surveys for each language we support, localize them and serve them based on the user's language. The issues would be that it will be hard to maintain and it will be hard to aggregate the data.

I'm also not a fan on leaving out feedback from all users that don't speak English.

@shiki  How do you think we should move forward?

**Comment by shiki** [comment]
@Ecarrion Re: localization. Would you mind p2-ing that issue? 

Re: dynamic type. Thanks for that! I'll see what I can do.

**Comment by shiki** [comment]
Dynamic font size CSS changes were applied in #2709.

**Comment by shiki** [comment]
Completed in #2709.

**Comment by Ecarrion** [comment]
> Would you mind p2-ing that issue?

Sure, p91TBi-3cs-p2
