### ISSUE TITLE
Products: Variations price warning banner doesn't fully load on first refresh

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#2707]
**Describe the bug**

After removing the price from a product variation, I expect if I refresh the variations list I'll see a banner at the top of the screen warning me that variations without a price won't be shown on my store.

However, when I pull to refresh the first time, the banner text doesn't fully load. It only loads after another refresh.

This looks like a fairly low priority issue, though, since the banner loads as expected the first time if I start on the product details screen and open the variations list to see the banner. (It's only an issue if I'm already on the variations list and pull to refresh.)

**To Reproduce**

1. Go to the Products tab.
2. Open a variable product.
3. Open the Variations section to view the variations list.
4. In wp-admin in a browser, remove the price from one of the variations and save the change.
5. In the app, pull to refresh the variations list.

**Screenshots**

Screencast: https://cloudup.com/c9FXlMR2qnq

<img src="https://user-images.githubusercontent.com/8658164/91164414-e0f09e00-e6c6-11ea-9e65-f5c7ccabd10e.jpeg" width="300px">

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.6
- WooCommerce iOS version: 4.9.0.0 TestFlight beta

**Comment by itsmeichigo** [comment]
Closing this because the banner has been removed in the new iteration.
