### ISSUE TITLE
Log In: some colors are off in dark mode

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2716]
- [x] The spinner color makes it not visible at all in dark mode; it's visible in light mode (this is new in release 4.9, potentially due to color changes in `AuthenticationManager` in this PR https://github.com/woocommerce/woocommerce-ios/pull/2644

example 1 | example 1
-- | --
![Simulator Screen Shot - iPhone 11 Pro - 2020-08-26 at 15 47 43](https://user-images.githubusercontent.com/1945542/91276028-86813b80-e7b3-11ea-84e1-71d409c9d35a.png) | ![Simulator Screen Shot - iPhone 11 Pro - 2020-08-26 at 15 41 19](https://user-images.githubusercontent.com/1945542/91275873-4fab2580-e7b3-11ea-8118-8ec440273833.png)

~~- [ ] The colors of the site address after entering site address look odd (this is pre-existing)~~ (update: this screen is no longer shown in the new UL&S)

<img src="https://user-images.githubusercontent.com/1945542/91275721-1b376980-e7b3-11ea-9300-93db50a359c6.png" width="300" />

**Comment by jaclync** [comment]
After debugging, the spinner is not visible because we changed `WordPressAuthenticatorStyle.secondaryTitleColor` from `.secondaryButtonTitle` (dark in light mode and light in dark mode) to always black for both light and dark mode in https://github.com/woocommerce/woocommerce-ios/pull/2644/files to work for the sign in method CTAs. When a submit button becomes disabled, the spinner color is [updated to `WordPressAuthenticatorStyle.secondaryTitleColor`](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/blob/9cf4ed196f4050b3f8e6a6fbb2beae4d32aed4af/WordPressAuthenticator/NUX/NUXButton.swift#L15). @Garance91540 do you know if we might update the buttons to be different colors in dark/light mode in the next iteration? if not, some changes to add more style constants to WPAuthenticator library are needed.

**Comment by Garance91540** [comment]
> @Garance91540 do you know if we might update the buttons to be different colors in dark/light mode in the next iteration? if not, some changes to add more style constants to WPAuthenticator library are needed.

@jaclync here is a small overview of the unified sign in on IOS. The Primary buttons in enabled state will be pink 30, and disable state like we have currently (black background grey stroke). 

https://d.pr/i/21Oqh5

I don't know when these changes will happen on iOS, so in the time being I think we should update the WPAuthenticator library as you suggested
