### ISSUE TITLE
[Product List] When sorting by "Newest to Oldest", draft products appear on top of the list even if I created them before other products

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-ios#2727]
When sorting by "Newest to Oldest" my products in my product list, the draft products I have created appear on top of the list even if I created them before other products. 

Example: on this screenshot, the "test" product was created months ago and the "[simple] Grand Ficus Elastica" was created an hour ago

![IMG_3517CEFBB341-1](https://user-images.githubusercontent.com/28450084/91440007-387d3e00-e86e-11ea-8c9a-cf396b632247.jpeg)

**Comment by jaclync** [comment]
Hey @Garance91540! I took a look at your site, and it looks like a limitation of the storage layer on iOS using Core Data. In core, it seems like the ordering is more advanced - sort by either the **creation date** for published products or the **modified date** for draft products. The creation date and modified date are two different properties of a product, and in Core Data we can only sort by one property at a time - right now we sort by the creation date.

If we want to achieve the same ordering as in core, we might want to create another calculated date field to `Product` like `date`, but this would require schema update. Any other solutions to achieve this sorting by a calculated value @woocommerce/ios-developers?

**Comment by pmusolino** [comment]
Discussion here: CGPNUU63E/p1598529915011700

**Comment by Ecarrion** [comment]
> Any other solutions to achieve this sorting by a calculated value @woocommerce/ios-developers?

Apparently you can [hack your way around a computed value on CoreData](https://stackoverflow.com/questions/46593574/creating-a-calculated-property-in-core-data) but it does not look safe or pretty!

**Comment by shiki** [comment]
Just dropping by to say I have nothing to contribute aside from agreeing with @jaclync. 😁
