### ISSUE TITLE
Products: Show empty state screen in product's Reviews section when product has no reviews

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#2729]
On Android, if a product has reviews enabled but no reviews yet, we link to the reviews empty state screen:

Android product details|Android empty state
-|-
![image](https://user-images.githubusercontent.com/8658164/91475468-8b1d2100-e893-11ea-95e6-496aa0c18e85.png)|![image](https://user-images.githubusercontent.com/8658164/91475489-953f1f80-e893-11ea-8687-f9056d34ade2.png)

We should do the same on iOS. Here's the iOS design for that empty state screen:

![image](https://user-images.githubusercontent.com/8658164/91475649-c6b7eb00-e893-11ea-973c-ddf5740c15ea.png)

Internal ref: p5T066-1tW-p2#comment-5678

**Comment by pmusolino** [comment]
Hey @rachelmcr, I opened the issue on the right repo here https://github.com/woocommerce/woocommerce-android/issues/2797 👍

**Comment by jaclync** [comment]
@pmusolino I think this issue is correct in the iOS repo? from my understanding, we're making the changes to show an empty reviews screen when a product has no reviews on iOS from p5T066-1tW#comment-5695-p2?

**Comment by pmusolino** [comment]
Ops my bad! I understood something completely wrong. I'm going to reopen it and close the one on Android. 🙇
