### ISSUE TITLE
Products tab: persist sort order and filter options

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2732]
On the products tab, the user can pick a sort order and filter option. Let's persist these two settings so that users see the same list of products between launches!

**Comment by pmusolino** [comment]
Just for alignment, what is your opinion on this task? 
Should it be managed on core data or on NSUserDefaults / plist file? I don't have a strong opinion, but I believe that this decision will affect similar choices in the future, so it would be good to take the correct one from the start.

cc @shiki @Ecarrion @jaclync @allendav @ctarda

**Comment by shiki** [comment]
My first instinct is to save them as a property inside [`GeneralAppSettings`](https://github.com/woocommerce/woocommerce-ios/blob/develop/Storage/Storage/Model/GeneralAppSettings.swift) which is saved through an `Action` in Yosemite's [`AppSettingsStore`](https://github.com/woocommerce/woocommerce-ios/blob/develop/Yosemite/Yosemite/Stores/AppSettingsStore.swift). In this way, we'll only have one plist file for all settings. 

But maybe there's a better way to do it. 🤷

**Comment by ctarda** [comment]
I agree with @shiki A centralized place to deal with these kind of device-specific configuration seems like the optimal way to go, within our current architecture.

**Comment by jaclync** [comment]
Saving the sort order & filter option in `GeneralAppSettings` via `AppSettingsAction` sounds good to me! The API is a bit cumbersome with async callback (as with many `*Store` actions) but it's nice to centralize all the app settings

**Comment by pmusolino** [comment]
Thank you for all your feedback! 🙌 I'm going to work on this, using `GeneralAppSettings` for saving the properties.
