### ISSUE TITLE
Products: Dismissing "Add more details" sheet also dismisses product details screen when editing product outside Products tab

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#2735]
**Describe the bug**

When the "Add more details" bottom sheet is available for a product, and you're editing the product outside the Products tab (for example, opening the product details from the My store > Top performers section, or from an order's details), dismissing the "Add more details" sheet also dismisses the product details screen. If you have made edits to the product details but haven't updated the product yet, you lose those changes.

You can also lose your changes when just swiping down (without the "Add more details" bottom sheet open) but that feels like a more intentional dismissing action than the scenario described above.

**To Reproduce**

1. Optional: Go to Settings > Experimental features and enable "Product editing." (This makes the "Add more details" bottom sheet appear on more products.)
2. Go to My store > Top performers or to Orders > select an order.
3. Tap on a product on one of those screens to open the product details.
4. Tap on "Add more details" at the bottom of the product details screen.
5. Swipe or tap to close the "Add more details" bottom sheet. Notice the product details also closes.

You can also repeat those steps but make a change to the product details (without updating the product), and notice that having a pending change to the product details doesn't prevent the details screen from closing.

**Screenshots**

Screencast: https://cloudup.com/cBT0OIulszs

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.6.1
- WooCommerce iOS version: 4.9.0.0 TestFlight beta

**Comment by jaclync** [comment]
Hey @rachelmcr thanks for reporting this! I also noticed this issue last week and fixed it for 5.0 in https://github.com/woocommerce/woocommerce-ios/issues/2701 ([PR](https://github.com/woocommerce/woocommerce-ios/pull/2702)) - I generated an installable build for the latest `develop`, see if it you'd like to check again!

**Comment by rachelmcr** [comment]
Ah, yeah! I didn't see the existing issue and fix, and that covers it. I'll close this issue since it's already resolved.
