### ISSUE TITLE
Create a new product (simple/grouped/external)

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2740]
- [x] Add a CTA to the products tab ("+") https://github.com/woocommerce/woocommerce-ios/pull/2749
- [x] Networking/Yosemite: add an action to create a product. `ProductAction.addProduct(product: Product, onCompletion: (Result<Product, ProductUpdateError>) -> Void)` https://github.com/woocommerce/woocommerce-ios/pull/2754
- [x] Refactor password/product remote update so that they can be updated differently when adding and editing a product
  - [x] Only retrieve password when editing a product https://github.com/woocommerce/woocommerce-ios/pull/2779
  - [x] Encapsulate async product & password updates into a use case https://github.com/woocommerce/woocommerce-ios/pull/2785
- [x] Create a coordinator to show a bottom sheet for selecting a product type, and navigate to a product form based on the selected product type with default values following core behavior https://github.com/woocommerce/woocommerce-ios/pull/2802
- [x] Fix bottom sheet pointing to the CTA on products tab on iPad https://github.com/woocommerce/woocommerce-ios/pull/2860 and https://github.com/wordpress-mobile/WordPressUI-iOS/pull/72
- [x] Update UI differences from editing a product (ref p91TBi-3f7-p2)
  - [x] Navigation bar "Publish" CTA is always shown (where "Update" CTA is when editing a product) and it creates a product with the status in product settings https://github.com/woocommerce/woocommerce-ios/pull/2846
  - Navigation bar > ellipsis menu:
    - [x] Add "Save as draft" action to create a product with status "draft", regardless of the status in product settings https://github.com/woocommerce/woocommerce-ios/pull/2859
    - [x] Disable "View Product in Store" and "Share" actions https://github.com/woocommerce/woocommerce-ios/pull/2846
  - [x] Unsaved changes action sheet (when the user navigates away from product details with outstanding changes):
    - Add "Save as draft" action (same behavior as “Save as draft” above) https://github.com/woocommerce/woocommerce-ios/pull/2859
  - [x] Hide product type row (it will be editable again in M5 when we support adding a variable product) https://github.com/woocommerce/woocommerce-ios/pull/2846

We're not supporting creating a variable product for M4 since there is no way to create a variation yet.

The whole flow:

<img width="1069" alt="Screen Shot 2020-08-31 at 4 46 22 PM" src="https://user-images.githubusercontent.com/1945542/91701225-8fa24c00-eba9-11ea-9052-c1f7408a82bb.png">

**Comment by pmusolino** [comment]
Related to the Android task pbMoDN-12y 👍

**Comment by jaclync** [comment]
all subtasks done, closing this!
