### ISSUE TITLE
Edit Product: product name and description are not aligned at leading edge

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2741]
**Describe the bug**

The product name text starts a little to the right of the product description text below, it'd be nice for these two to be aligned.

**To Reproduce**
- Make sure the products feature switch is on under Settings > Experimental Features
- Go to the Products tab
- Tap on any product with a name and description --> check the leading alignment of the two rows

**Screenshots**

<img width="438" alt="Screen Shot 2020-08-31 at 4 54 39 PM" src="https://user-images.githubusercontent.com/1945542/91702299-1b68a800-ebab-11ea-9adf-3fbbdd0a50b5.png">

**Expected behavior**

The product name and description rows should be aligned by the leading edge.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 11
- iOS version: iOS 13.5
- WooCommerce iOS version: 4.9.0.0

**Comment by pmusolino** [comment]
Good catch @jaclync! On it
