### ISSUE TITLE
[Issue Refunds] Research Feasibility of Refunding Shipping Cost and Refund by Amount

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2751]
<img src="https://user-images.githubusercontent.com/198826/91985350-aa7bda00-ece9-11ea-8877-94ec9c0056a7.png" width="240">

> on Android, we only allow refund for products and we left this notice here basically telling users they can refund their shipping cost in their site-admin.

## Goals

- [ ] Research why this was not implemented on Android 
- [ ] Implement this if feasible 

## References

CGPNUU63E-p1598914787025200-slack

**Comment by Ecarrion** [comment]
Conclusion: possible. 
Ref: p91TBi-3hR-p2
