### ISSUE TITLE
[Issue Refunds] Audit for accessibility and localization

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2764]
We're not gonna forget to do this, this time around. 😁

**Comment by Ecarrion** [comment]
- [x] Issue Refund screen headers should respect safe areas
<img width="832" alt="Screen Shot 2020-12-02 at 2 14 47 PM" src="https://user-images.githubusercontent.com/562080/100920178-c178c680-34a8-11eb-9ec0-f6f4d3fae528.png">

- [x] Issue Refund screen next button should respect safe areas
<img width="836" alt="Screen Shot 2020-12-02 at 2 15 12 PM" src="https://user-images.githubusercontent.com/562080/100920250-d6555a00-34a8-11eb-97e2-f99d2a683353.png">

- [x] List item selector cell background should go to the screen's full width 
<img width="833" alt="Screen Shot 2020-12-02 at 2 15 55 PM" src="https://user-images.githubusercontent.com/562080/100920353-fe44bd80-34a8-11eb-8aed-0044ae1531c7.png">

- [x] Refund Confirmation screen should go to the screen full width
<img width="840" alt="Screen Shot 2020-12-02 at 2 17 07 PM" src="https://user-images.githubusercontent.com/562080/100920454-2502f400-34a9-11eb-93b4-c22983f02c38.png">

- [x] Refund Confirmation screen reason text field should be visible when the keyboard goes up
<img width="828" alt="Screen Shot 2020-12-02 at 2 18 22 PM" src="https://user-images.githubusercontent.com/562080/100920581-54b1fc00-34a9-11eb-9896-f15c2a73082e.png">

- [x] Issue refund screen header is not completely visible when using large fonts
<img width="394" alt="Screen Shot 2020-12-02 at 2 21 02 PM" src="https://user-images.githubusercontent.com/562080/100920882-bffbce00-34a9-11eb-892c-1a4f5625920e.png">

- [x] Refund Confirmation screen "previously refunded" and "Refund amount" are not completely visible when using large fonts
<img width="393" alt="Screen Shot 2020-12-02 at 2 23 05 PM" src="https://user-images.githubusercontent.com/562080/100921071-0cdfa480-34aa-11eb-8cbd-5a1ee1f9aeb2.png">

- [ ] Isssue Refund screen needs more voice over info on: Navigation title, and quantity of each item and maybe a hint when the "next button" is disabled.
