### ISSUE TITLE
[Issue Refunds] Refund Summary View

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#2768]
After tapping the `next` button on the [refund by item view](https://github.com/woocommerce/woocommerce-ios/issues/1094), a summary of the amount to be refunded should be shown.

<img width="357" alt="summary" src="https://user-images.githubusercontent.com/562080/92197114-7eba3a80-ee36-11ea-9398-4a622aee3d04.png">

On non-automatic refunds, a disclaimer will be shown
<img width="272" alt="Screen Shot 2020-09-03 at 10 47 43 PM" src="https://user-images.githubusercontent.com/562080/92197523-91813f00-ee37-11ea-9355-5d12e515bccd.png">

## Known Goals

- Show refund method
- Include refunded shipping costs in the total amount to be refunded
- Allow entry of Reason for Refund

## Unknowns

Is the refund method hardcoded depending on the payment method or is it something the store owner can change?

## Split Tasks 

This has been split into multiple tasks so it's clearer what's left. 

- https://github.com/woocommerce/woocommerce-ios/issues/2980
- https://github.com/woocommerce/woocommerce-ios/issues/2981
- https://github.com/woocommerce/woocommerce-ios/issues/2982

**Comment by shiki** [comment]
I have split the remaining into separate tasks and marking this to be closed by the PR #2979.
