### ISSUE TITLE
Products: Variable product > Inventory section shows (potentially inaccurate) stock status when "manage stock" is disabled

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#2783]
**Describe the bug**

As noted in https://github.com/woocommerce/woocommerce-ios/pull/2725, the Inventory section for a variable product should include a "Manage Stock" toggle but _not_ a Stock Status row.

However, the product details screen for a variable product still shows a stock status (In Stock/Out of Stock) when "Manage Stock" is toggled off at the product level. This could be ok if it matches the variation stock status, but updating the variation stock status doesn't necessarily update the product-level stock status shown in product details.

cc @jaclync 

**To Reproduce**

1. Go to Settings > Experimental Features and enable Product Editing.
2. Go to the Products tab and select a variable product.
3. Notice that under "Inventory" it shows a stock status (e.g. "In stock").
4. On the product details screen, tap "Inventory" to open the product's inventory settings.
5. Confirm "Manage stock" is toggled **off**.
6. Go back to product details and tap "Variations" to open the variations list.
7. Tap a variation to open its details.
8. Tap "Inventory" to open the variation's inventory settings.
9. Confirm "Manage stock" is toggled **off** and switch the stock status so it's opposite of the product stock status you noted in step 3 (e.g. if the product showed "In stock" switch it to "Out of stock").
10. Repeat steps 7-9 for every variation.
11. Go back to product details and notice that the stock status hasn't changed. (For example, even if every variation is "Out of stock" it still shows "In stock.") Notice that you can't pull to refresh that stock status.
12. Make some other change to the product details and tap "Update." Notice that this refreshes the product details and the product's Inventory section now shows the correct stock status.

**Screenshots**

Screencast: https://cloudup.com/cW90PqR4FKe

Stock status in product details:

<img src="https://user-images.githubusercontent.com/8658164/92491398-18dd0280-f1ea-11ea-91f0-9e59cf43db5b.PNG" width="300px">

**Expected behavior**

Since stock status can't be controlled at the product level, it would make sense not to show it there.

Alternately, if it does show a stock status, that status should update according to the stock status of the product variations (as soon as the variation stock status is updated).

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.6.1
- WooCommerce iOS version: 5.0.0 TestFlight beta

**Comment by jaclync** [comment]
Thanks for catching this @rachelmcr! It makes sense to just not show the stock status since it's not controlled at the product level, will update!
