### ISSUE TITLE
Product Images are not showed if they contain Cyrillic characters in the link

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#2789]
## Describe the bug
Rebecca [reported](https://a8c.slack.com/archives/C6H8C3G23/p1599648229152800) a user who is unable to view images in products. After some investigations, it seems that we are unable to download/render images that contain Cyrillic characters in the image link.

## Screenshots
The first two images contain Cyrillic characters in the link, the last one no, and in fact, it’s showed correctly.
<img src="https://user-images.githubusercontent.com/495617/92593274-243f3500-f2a1-11ea-87ad-a378a574f52e.png" width=300 />

**Comment by rezzap** [comment]
Another report of this similar issue in 3777998-zen
