### ISSUE TITLE
SIWA: the app gets into a weird state when the Apple ID credential is revoked while the user is on the store picker screen

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2829]
Thanks to @shiki's report in https://github.com/woocommerce/woocommerce-ios/pull/2818#pullrequestreview-489138112

**Describe the bug**

If the Apple ID credential is revoked while the user is on the store picker screen (before the app enters the "authenticated" state when signing in to a store), the app gets into a weird state where the user can still continue to see an empty store. Relaunching the app brings the user back to the logged out state but it's not ideal.

**To Reproduce**

- Login with SIWA
- Stay on the store picker screen
- Unlink the Apple ID (steps below)
- Go back to the app
- The store picker screen is still active and you can still proceed with logging in. No data loads happen

Steps to disconnect in your Apple account on a device:

Go to iOS Settings
Select your iCloud account at the top
Go to Password & Security > Apps Using Your Apple ID
Select WordPress > Stop Using Apple ID (we share the same app group as WordPress)

**Expected behavior**

The app should be back to the log in screen after the Apple ID credential is revoked.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 6s Plus
- iOS version: iOS 13.7
- WooCommerce iOS version: any

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by joshheald** [comment]
@jaclync I can't reproduce this any more, feel free to reopen if you can 😊
