### ISSUE TITLE
Trashing products only when viewing in products tab

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-ios#2869]
There are a couple of places we show products: Top Performers, Order Details, and in the Products tab/list. The Trash button contextually only makes sense when it's in the Product List. 

Ref: p1600967917003400-slack-mobile-woo-async-mtg

cc: @jaclync

**Comment by eshurakov** [comment]
I think it makes sense to show delete button when product is opened in edit mode and hide it when product is opened in readonly mode (there is already code in place). If we hide delete button when product is opened from Top Performers, we end up in a situation in which you can edit a product, but not delete it. I think that would be confusing.

Right now we show product in readonly mode if it's opened from Order.
In all other places product is opened in edit mode.

**Comment by pmusolino** [comment]
I agree @eshurakov, it makes sense. Consider that when this decision was taken, we didn't have a chance to show the new product screen in read-only mode 👍

**Comment by eshurakov** [comment]
@pmusolino I'm then closing this issue as there is nothing needs to be done.
