### ISSUE TITLE
Document: New Store / Action / Remote / Entity

### ISSUE THREAD

**Issue by jleandroperez** [woocommerce/woocommerce-ios#287]
### Details:
Although we do have an architecture document, let's extend things and add a document detailing how to:

- [x] Add a new Store
- [ ] Add a new Action
- [ ] Add a new Remote
- [ ] Add a new Entity

**Comment by mindgraffiti** [comment]
Closing in favor of past PRs as examples + architectural tour given during onboarding for new devs
