### ISSUE TITLE
Strings in Info.plist file aren't localized

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#2874]
**Describe the bug**

@pmusolino reported that strings in the `Info.plist` file aren't localized. One option is to use the hack used for WordPress; as @loremattei shared:

> the strings are copied into a .c file, so that `genstrings` gathers them when it updates Localizable.strings.

https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Utility/InfoPListTranslator.c

**Screenshots**

![image](https://user-images.githubusercontent.com/8658164/94264369-7bded100-ff2e-11ea-8269-345a8287048a.png)

**Comment by joshheald** [comment]
I can still reproduce this.

Prioritization:
Severity – Medium: UI/UX issue in multiple flows which gives a poor first impression
Impact – High: estimate 45% of users use a language other than English
= high
