### ISSUE TITLE
Fix Xcode 12 build failure

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2880]

**Comment by asbajaj001** [comment]
I am also getting error on 11.5 which is a recommended version on readme file. I kept getting issue in xcode 12 and kept trying for two days and just stumbled upon this issue.

The build (feels like) is randomly failing. e.g., latest issue it is giving me is: Swift Compiler Error "Type 'ApiCredentials' has no member 'loggingEncryptionKey'" in EventLogging.swift AND "Command CompileSwift failed with a nonzero exit code" in two files viz. Ghost+Woo.swift and WooConstants.swift.

I am not trying to update the code because I want the code to first run as-is as downloaded from official github.

Any pointers or ideas would be appreciated.

**Comment by shiki** [comment]
Hi @asbajaj001! Sorry about that. It looks like the template used for generating `ApiCredentials.swift` was missing a property. I have submitted a PR to fix this https://github.com/woocommerce/woocommerce-ios/pull/2926. 

But you should be able to fix it by changing your `ApiCredentials.swift` file to the contents of this [`ApiCredentials-Template.swift`](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Credentials/Templates/ApiCredentials-Template.swift) file. You'll have to re-enter the Client ID and Client Secret after that. 

Please let me know how it goes!

**Comment by asbajaj001** [comment]
Hi @shiki thanks for your quick help. I replaced content of ApiCredentials.swift in woocommerce/derivedsources folder and then I am trying to view canvas but nothing appears for swift files. Attaching a screenshot. What am I doing wrong?

Thanks!
![Uploading Screen Shot 2020-10-05 at 7.10.11 PM.png…]()

**Comment by shiki** [comment]
Hello again @asbajaj001! I got an email that you responded to this issue but it's not on Github anymore. I guess it was deleted. 🙂 Let me know if you still need help!

**Comment by asbajaj001** [comment]
@shiki thanks for following up. I deleted my previous response because I confused it with something else. As for this issue, I went with 5.0 release and it worked fine. Thanks for your awesomeness.

**Comment by asbajaj001** [comment]
@shiki I downloaded 5.1 release version and trying to rebuild but getting the same error again. I followed the steps but it is failing continuously with message: Type 'ApiCredentials' has no member 'loggingEncryptionKey'

**Comment by shiki** [comment]
Heya @asbajaj001! Unfortunately, the fix for that is still currently in [`develop`](https://github.com/woocommerce/woocommerce-ios) branch. It'll be released as part of 5.3 in a couple of weeks. 

However, you should be able to fix that error with the manual fix I mentioned in https://github.com/woocommerce/woocommerce-ios/issues/2880#issuecomment-703976921. Please also check [Credentials for External Contributors](https://github.com/woocommerce/woocommerce-ios#credentials-for-external-contributors) if you are unable to find the `ApiCredentials.swift` file. 

Let me know how it goes!

**Comment by asbajaj001** [comment]
@shiki i thought I followed the manual fix last night and then posted but I will try again tonight after business hours. Thanks!
