### ISSUE TITLE
Unit tests: replace `SessionManager.testingInstance` static singleton with `makeForTesting()`

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2885]
Original discussion: https://github.com/woocommerce/woocommerce-ios/pull/2850#discussion_r495245234

We have a bunch of usage of `SessionManager.testingInstance` in unit tests. However, `.testingInstance` is actually a static singleton and let's instantiate a new instance every time in the updated `makeForTesting()` so that each test case is using a brand new `SessionManager`.

https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/WooCommerceTests/Internal/SessionManager+Internal.swift#L10-L14

**Comment by joshheald** [comment]
I've checked this: `testingInstance` isn't actually a singleton, and it makes a brand new `SessionManager` whenever it's called.

As a static computed var, the closure is run every time it's called, it's not a `lazy` instantiation which gets stored.

I've confirmed this with a breakpoint in `testingInstance`, running a suite of tests, and printing the `sessionManager` each time we hit the breakpoint:

```
(lldb) po sessionManager
<SessionManager: 0x600001302f00>
(lldb) po sessionManager
<SessionManager: 0x600001337a00>
(lldb) po sessionManager
<SessionManager: 0x600001308e00>
(lldb) po sessionManager
<SessionManager: 0x60000130c800>
```
