### ISSUE TITLE
SessionManager: Tech Debt

### ISSUE THREAD

**Issue by jleandroperez** [woocommerce/woocommerce-ios#289]
### Details:
This is a R+D task:

0. Perhaps try to split SessionManager in three different containers? `Settings`, `Entities`, `Credentials`

1. Analyze if it's possible to nuke the optionals from SessionManager
2. (Depending on the outcome of the point above) perhaps SessionManager should only exist in the AuthenticatedState
3. Analyze if the SynchronizeEntities / RestoreEntities sequence could be moved over to the AuthenticatedState, as well.

**Comment by shiki** [comment]
Closing this for now.
