### ISSUE TITLE
If Products feature switch was disabled before, M3 features are not available by any means

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2927]
In https://github.com/woocommerce/woocommerce-ios/pull/2891, we removed the feature switch from Settings > Experimental Features but I think we're still using the latest feature switch value. Now that the feature switch is removed, if the feature switch was disabled before there is no way to enable M3 features anymore.

Steps to repro:

- Launch the app with [release 5.1](https://github.com/woocommerce/woocommerce-ios/releases/tag/5.1) or TestFlight 5.1 build
- Go to Settings > Experimental Features, and turn off the products feature switch
- Launch the app from `develop`
- Go to the products tab
- Tap on a variable/external/grouped/non-core product

actual: the product is not editable.
expected: the product is editable since we're making M3 features available for everyone in release 5.2

**Comment by jaclync** [comment]
@rachelmcr do you think this issue is worth targeting release 5.2 as a hotfix? I created a PR for this: https://github.com/woocommerce/woocommerce-ios/pull/2928

I thought that since we mention M3 features in the release notes, if the user didn't get a chance to turn on the feature switch before (default off) then they can't access the M3 features at all.

**Comment by rachelmcr** [comment]
Thanks for noticing and fixing this! Yes, I agree this is worth a fix in the 5.2 release so that everyone gets the M3 features as announced in the release notes.

**Comment by jaclync** [comment]
closing since the PR was merged targeting release 5.2 branch
