### ISSUE TITLE
Products: Labels on Price screen clipped with large text sizes

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#2942]
**Describe the bug**

When using a large text size (dynamic type) on the device, the "Price" and "Tax settings" labels on the Product Details > Price screen are getting clipped.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/95467828-d425c200-0975-11eb-9e22-fa95d217d224.PNG" width="300px">

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 14.0.1
- WooCommerce iOS version: 5.2.0.1 TestFlight beta

**Comment by pmusolino** [comment]
Fixed here https://github.com/woocommerce/woocommerce-ios/pull/3090
