### ISSUE TITLE
ButtonTableFooterView Has Unnecessary Margin in iPhones with Notches on Landscape

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2943]
The `ButtonTableFooterView` was created from an existing (Fulfill) view in #2938. @Ecarrion found that on iPhones with notches in landscape mode, it has an unnecessary margin.

Portrait ✔️ | Landscape ❌
--------|-------
<img src="https://user-images.githubusercontent.com/198826/95474227-1df4b500-0942-11eb-8110-8d727b00ec43.png" width="340">        |       <img src="https://user-images.githubusercontent.com/198826/95474315-349b0c00-0942-11eb-8fb0-2409c2faad45.png" width="540">

## iPad

It seems to work fairly well on iPad.

Portrait ✔️ | Landscape ✔️
--------|-------
<img src="https://user-images.githubusercontent.com/198826/95474602-89d71d80-0942-11eb-9bf4-4d3fdcf0d9c4.png" width="340">        |       <img src="https://user-images.githubusercontent.com/198826/95474595-8774c380-0942-11eb-972f-03c5e85b5e22.png" width="440">

## iPhone 8

On iPhone 8, which does not have a notch, it also works fine.  So we probably only need to fix it for iPhones with notches. 

Portrait ✔️ | Landscape ✔️
--------|-------
<img src="https://user-images.githubusercontent.com/198826/95475029-0a961980-0943-11eb-868d-8b11b4ff935d.png" width="340">        |       <img src="https://user-images.githubusercontent.com/198826/95475051-11249100-0943-11eb-98e9-752cca90a956.png" width="540">

**Comment by eshurakov** [comment]
Maybe a solution here is to make sure that cells are edge to edge, but cells content should still respect a safe area. 
Right now for iPhones with a notch it looks like a cell and it's separator starts from nowhere and ends nowhere :-)

**Comment by eshurakov** [comment]
@woocommerce/mobile-designers 
What do you think about making the cells go edge to edge? Will look like this. Notch is not visible on the screenshots, but imagine that it's on one of the sides :-)

![Simulator Screen Shot - iPhone 11 - 2020-12-14 at 15 02 48](https://user-images.githubusercontent.com/54751/102323713-23ddc680-3f81-11eb-8c9a-a156fbf05f42.png)

---

![Simulator Screen Shot - iPhone 11 - 2020-12-14 at 15 02 45](https://user-images.githubusercontent.com/54751/102323709-23453000-3f81-11eb-82dd-c2e1ba2d9a41.png)

**Comment by Garance91540** [comment]
@adamzelinski I think you reviewed something similar last week? I think your call was to make the cells go edge to edge?

**Comment by ghost** [comment]
> @woocommerce/mobile-designers
> What do you think about making the cells go edge to edge? Will look like this. Notch is not visible on the screenshots, but imagine that it's on one of the sides :-)
> 
> ![Simulator Screen Shot - iPhone 11 - 2020-12-14 at 15 02 48](https://user-images.githubusercontent.com/54751/102323713-23ddc680-3f81-11eb-8c9a-a156fbf05f42.png)
> 
> ![Simulator Screen Shot - iPhone 11 - 2020-12-14 at 15 02 45](https://user-images.githubusercontent.com/54751/102323709-23453000-3f81-11eb-82dd-c2e1ba2d9a41.png)

@eshurakov @Garance91540 Yes, I think your screenshots look great here and that's exactly how I thought we could do it. As long as the content keeps that same width.

**Comment by eshurakov** [comment]
Thank you @Garance91540 and @adamzelinski!
