### ISSUE TITLE
[Issue Refunds] Handle previous refunds

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#2967]
When refunding an order we need to make sure that.

- Do not show the "refund shipping" switch if shipping was already refunded.
- Take into account already refunded items to display the proper max quantities to refund.

**Comment by shiki** [comment]
This is the REST API issue we're waiting for to identify if shipping costs were already refunded. https://github.com/woocommerce/woocommerce/issues/27566

**Comment by Ecarrion** [comment]
PR https://github.com/woocommerce/woocommerce/pull/28241
