### ISSUE TITLE
Woo: Shipping Labels - add endpoint to validate the origin and destination address

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-ios#2969]
As part of the [shipping labels project](https://github.com/woocommerce/woocommerce-ios/projects/24), we need to add an endpoint to validate the origin and destination address.

**Comment by pmusolino** [comment]
Related P2 post p91TBi-42G

**Comment by pmusolino** [comment]
- [x] Networking layer
- [x] Yosemite layer
