### ISSUE TITLE
Shipping Labels M2: check if the order is eligible for shipping label creation

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-ios#2971]
- [ ] Add a new button in the Order detail screen to Create Shipping Label. This button will only be displayed if:
- WooCommerce Services is installed and active on the store.
- the store is in the US. 
- the destination address for the order is in the US. 
- the order has physical products or a combination of physical and virtual products.
- [x] If CTA is displayed, also show `Learn more about creating labels with your phone` info row at the end of the Products section

<img width="300" src="https://user-images.githubusercontent.com/22608780/95943338-1ed68c80-0e03-11eb-8774-97987bd5e040.png">

**Comment by rachelmcr** [comment]
Completed in #4143.
