### ISSUE TITLE
Shipping Labels M2: create shipping label form

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-ios#2972]
Once a [button is added to create a shipping label](https://github.com/woocommerce/woocommerce-ios/issues/2971), we would need to redirect to a new screen when the button is clicked. This screen should display the origin and destination address for the shipping label.

There are five sections in this form:

- Origin address (M2)
- Destination address (M2)
- Package details (M2+M3)
- Carrier & rates (M3)
- Payment (M3)

<img width="300" alt="Screenshot 2020-10-14 at 9 57 33 AM" src="https://user-images.githubusercontent.com/22608780/95943527-b045fe80-0e03-11eb-9c43-0a23a9669059.png">

**Comment by jaclync** [comment]
@pmusolino I'm thinking we can implement the form with the following features:

- Implemented by `UITableView`
- Each row has a data state like `enum DataState` (feel free to suggest better naming!):
  - Case `validated`: the data are validated
  - Case `pending`: the data still need to be validated
- Each row has a UI state like `enum DisplayMode`:
  - Case `editable`: the row is not greyed out and is available for edit (a disclosure indicator is shown in the accessory view) and "Continue" CTA is shown to edit the row details
  - Case `disabled`: the row is greyed out
- We can have a state machine that keeps track of a list of rows with corresponding data state and UI state. On each state change (any data change from any rows or API validation response), the state machine:
  - First updates the date state of affected rows
  - Then recalculates the UI state of all rows
    - A row's UI state is `editable` if:
      - All previous rows (lower index) have data state as `validated`
      - For the first row, it is always editable
- The state machine will later receive different actions that could alter each row's data state like in https://github.com/woocommerce/woocommerce-ios/issues/2973
- We reload the table view on state changes, and configure each cell with the row's UI state

We can implement this form UI without any actions first (and test with mock actions). Very open to suggestions or any other ideas for this UI!
