### ISSUE TITLE
[Issue Refunds] Add Refund Via Implementation to RefundConfirmationViewController

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2982]
Continuation of #2768. We should fill in the “Refund Via” field with real data. I don't know the specifics of this yet but we can follow what Android does.  

<img width="357" alt="summary" src="https://user-images.githubusercontent.com/562080/92197114-7eba3a80-ee36-11ea-9398-4a622aee3d04.png">

On non-automatic refunds, a disclaimer will be shown:

<img width="272" alt="Screen Shot 2020-09-03 at 10 47 43 PM" src="https://user-images.githubusercontent.com/562080/92197523-91813f00-ee37-11ea-9355-5d12e515bccd.png">

We're currently showing fake text. 😄

**Comment by Ecarrion** [comment]
On Hold while this is done https://github.com/woocommerce/woocommerce-ios/issues/3110
