### ISSUE TITLE
Hide Pricing and Inventory for non-core product types

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-ios#2985]
As per our Slack discussion, we should hide pricing and inventory for non-core product types (such as subscriptions). We should instead show only:

- Reviews
- Categories
- Tags
- Short description
- Product type

The last four are currently read-only on iOS, but only product type should be read-only.

**Comment by jaclync** [comment]
These fields are currently editable on iOS:

- Name
- Images
- Description
- Product settings
- Categories
- Tags
- Short description

And these are currently readonly:

- Price (only shown if non-empty)
- Reviews (as for every product type)
- Inventory
- Product type

I think the proposal is to remove price and inventory from product details, discussion in CGPNUU63E/p1602608236078400-slack
