### ISSUE TITLE
Grouped products show the wrong product type

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-ios#2986]
In product detail, grouped products show as physical products.

![unnamed](https://user-images.githubusercontent.com/3903757/96111865-cad5b180-0eaf-11eb-8cd4-2f8982ae0394.jpg)

**Comment by jaclync** [comment]
Hmm I couldn't seem to reproduce this in my test store after testing the following scenarios:

- After changing a product's product type to Grouped Product, then loading it again (before and after pulling down to refresh)
- After creating a new product with Grouped Product type, then publishing it
- After filtering the products tab by grouped product, then tapping on one of them

Do you mind adding me to your test store so I can look into this product?

**Comment by pmusolino** [comment]
I also tested this case, and I wasn't able to replicate it. @nbradbury are you sure it was a Grouped Product since it doesn't show also the `Grouped products` cell?

**Comment by rachelmcr** [comment]
I am also unable to reproduce this in the 7.0 release. I'll close this issue for now, but we can reopen if we find it happens in specific cases.
