### ISSUE TITLE
Update README.md to mention loggingEncryptionKey

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#2992]
The README.md file, [in the section for external contributors](https://github.com/woocommerce/woocommerce-ios#credentials-for-external-contributors), does not mention the need of a loggingEncryptionKey declared in APICredentials.swift.

This would make difficult for external contributors to build the app out of the box.

**Comment by ctarda** [comment]
@jkmassel suggested using `JcrAAGTmdL9+GgLgwEpV9QlwlOlOCp5Ag2QvHhC01Vs=`

**Comment by iamgabrielma** [comment]
Closing this, resolved via https://github.com/woocommerce/woocommerce-ios/pull/2926 👍
