### ISSUE TITLE
[IAFeedback] Add Custom Tags to All Launched Surveys

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#3006]
## Problem

Discussed in C6H8C3G23-p1602779691418100-slack.

We want to be able to **reliably** identify how many survey responses came from iOS and how many from Android. 

## Solution

As suggested by the Crowdsignal team, we can use [Custom Tags](https://crowdsignal.com/support/using-custom-tags-to-track-survey-responses/) for this. For all the Crowdsignal surveys that we launch, append a query parameter named `woo-mobile-platform` and value `"ios"`. For example, if this is the survey URL:

```
https://kristastevens.survey.fm/acme-customer-survey
```

Then the full URL that will be launched should be:

```
https://kristastevens.survey.fm/acme-customer-survey?woo-mobile-platform=ios
```

## Acceptance Criteria

Confirm that the custom tag is visible in Crowdsignal. 

---

Android issue: https://github.com/woocommerce/woocommerce-android/issues/3045

**Comment by anitaa1990** [comment]
Closed via #3041
