### ISSUE TITLE
Bug: Product List screen doesn't refresh the "No products yet" placeholder state

### ISSUE THREAD

**Issue by AliSoftware** [woocommerce/woocommerce-ios#3011]
**Describe the bug**

When there's a single product in the product list screen and you edit it to change its status (making it filtered out from the list) and go back, the list is empty but the "No Products yet" placeholder is shown until pull to refresh

**To Reproduce**

1. Make it so you have only one product in a specific state, for example only one product in Draft state
2. Go to the Products tab, and add the relevant filter to make the list only show one product.
3. Tap on the product to edit it, and change it state to something else, save and Update.
4. Use the Back button to go back to the product list. The product has disappeared from the list as expected, making the list empty, but the "No Products yet" placeholder isn't visible
5. Pull to refresh. Only then is the "No Products yet" placeholder rightfully shown

**Screenshots**

![video](https://user-images.githubusercontent.com/216089/96445675-972cbb80-1210-11eb-90c5-080b6e2a1f46.gif)

**Expected behavior**

The "No products yet" placeholder visibility state should be updated every time we get back on the screen (on `viewDidAppear`?)

**Mobile Environment**

- Device: iPhone 11 Pro
- iOS version: 14.0.1
- WooCommerce iOS version: 5.2.0.2 and 5.3.0.0

FYI: There's the same issue on Android: woocommerce/woocommerce-android#3046

**Comment by joshheald** [comment]
I can no longer reproduce this, closing.
