### ISSUE TITLE
[Xcode 12] Convert WordPressAuthenticator to Swift 5

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#3016]
<img src="https://user-images.githubusercontent.com/198826/96478410-e2d16c00-11f4-11eb-9c81-a691596b45e9.png" width="500">

This warning is shown when compiling using Xcode 12. It's possible that Platform has already taken care of upgrading WPAuth so we probably just need to upgrade the version.

**Comment by iamgabrielma** [comment]
Closing this one as the warning is no longer there. At the moment we're using [WordPressAuthenticator 4.2](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/blob/cf6a2a59211cb3cff24e52d42c22e62e1bd0913a/WordPressAuthenticator.podspec) and the `SWIFT_VERSION` was updated to 5.0:

<img width="793" alt="Screenshot 2022-11-15 at 10 56 16" src="https://user-images.githubusercontent.com/3812076/201807547-62c20a20-260e-4916-8ec9-8b7b0e3db9ae.png">
