### ISSUE TITLE
[Xcode 12] Convert TestKit to Swift 5

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#3017]
![image](https://user-images.githubusercontent.com/198826/96478594-157b6480-11f5-11eb-8d2f-e198d01514d9.png)

This warning is shown when compiling with Xcode 12. When I tried “fixing” it, nothing happened and the warning just disappeared. I'm not entirely sure what to do here yet. 😄

**Comment by iamgabrielma** [comment]
Closing this one as it seems the warning has disappeared. I can't pinpoint exactly when this happened, but possibly when the package was [updated to require Swift tools 5.x ](https://github.com/krzysztofzablocki/Difference/blob/master/Package.swift)?
