### ISSUE TITLE
Remove Order Fulfillment Screen

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#3034]
When navigating to an order, a button named “Begin Fulfillment” is shown. 

<img src="https://user-images.githubusercontent.com/198826/96624978-c7d12b80-12ca-11eb-9f68-13f7f60e4317.png" width="300">

This leads to a fulfillment screen. This screen has since been removed in Android. Android just shows “Mark Order Complete”. 

<img src="https://user-images.githubusercontent.com/198826/96625063-e7685400-12ca-11eb-8500-0d91b847180a.png" width="300">

We should do the same in iOS and remove the fulfillment screen.

## Goals

- [ ] Remove Fulfillment Screen
- [ ] Move order completion logic to Order Details

---

Ref p91TBi-3mT-p2#comment-1857

**Comment by raziqfarid** [comment]
@shiki Would love to work on this. Can you please assign this to me?

**Comment by shiki** [comment]
This was done in #3453. There are a few things I need to supplement like unit tests but I'll create separate issues for those.
