### ISSUE TITLE
Linked Products: add Upsell and Cross-sell screen selectors (part 3)

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#3073]
Ref p91TBi-2XV-p2

## Goals 

- [ ] Show a products list when tapping on “Add products” (see #3072) 
- [ ] Show the "Upsell/Cross-sell already added" screen when tapping on “Edit Products” (see #3072)
- [ ]  Allow multiple selections. This used to be “tap and hold” and Jayson confirmed with Garance that **multiple selections happen right away**. Just tapping will enable multiple selections. 
- [ ]  Tapping on Done will show the Linked Products screen.
- [ ] The list of selectable products should not include the products that are already linked. 

## Notes

- We could probably reuse the Grouped Products screens for this.
- Search will be handled in a different task. 

## Screenshots

| Add Upsell/Cross-sell screen             |  Upsell/Cross-sell already added | Selection style (similar to Grouped Products) |
:-------------------------:|:-------------------------:|:-------------------------:
![Schermata 2020-10-28 alle 15 31 46](https://user-images.githubusercontent.com/495617/97450174-ba531b80-1932-11eb-8aed-ad6740ded2b1.png) | ![Schermata 2020-10-28 alle 15 34 24](https://user-images.githubusercontent.com/495617/97450472-128a1d80-1933-11eb-8bb3-b814c1757e94.png) | ![Simulator Screen Shot - iPhone 11 Pro - 2020-10-28 at 15 33 35](https://user-images.githubusercontent.com/495617/97450705-4b29f700-1933-11eb-8779-9ee1db45f51c.png)

**Comment by shiki** [comment]
I added this item to the Goals. We missed it in Android initially but we found it early (https://github.com/woocommerce/woocommerce-android/issues/3126).

> Show the "Upsell/Cross-sell already added" screen when tapping on “Edit Products”

**Comment by shiki** [comment]
Also added:

> The list of selectable products should not include the products that are already linked.
