### ISSUE TITLE
Disabled state on buttons not working

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#3081]
**Describe the bug**
Our `applyPrimaryButtonStyle` method on `UIButton` seems to be applying the wrong style for the disabled state.

**To Reproduce**
1. Apply `applyPrimaryButtonStyle` to any button
2. Set it as disabled `button.isEnabled = false`
3. See wrong style applied

**Screenshots**
Current | Expected
---- | ----
<img width="439" alt="bad" src="https://user-images.githubusercontent.com/562080/97575197-60963400-19ba-11eb-9675-5960cbb1c39b.png"> | <img width="131" alt="good" src="https://user-images.githubusercontent.com/562080/97575201-612eca80-19ba-11eb-8e85-06c38fea8847.png">

**Mobile Environment**
Happening on iOS 13 and 14, both simulator and device

**Comment by br3akzero** [comment]
I would like to do this if this task is still active ?

**Comment by Ecarrion** [comment]
Sure @Denpex, let us know if you need any assistance. 👍

**Comment by jaclync** [comment]
I think the design for disabled primary button is the following (in "System - iOS Components" design board):

@Garance91540 feel free to correct!

\ | Light mode | Dark mode
-- | -- | --
Design | <img width="381" alt="Screen Shot 2020-10-30 at 3 12 49 PM" src="https://user-images.githubusercontent.com/1945542/97671438-3c724a00-1ac3-11eb-85b5-b0c77b48b3c7.png"> | <img width="357" alt="Screen Shot 2020-10-30 at 3 12 58 PM" src="https://user-images.githubusercontent.com/1945542/97671471-4eec8380-1ac3-11eb-89df-981962d2c36d.png">
Text color | iOS System Quaternary Label Color | iOS System Tertiary Label Color
Border color | Same as text color | Same as text color

**Comment by br3akzero** [comment]
@jaclync thanks for the heads up, I will make sure to follow these guidelines.

**Comment by Garance91540** [comment]
That's correct @jaclync , thank you!

**Comment by Ecarrion** [comment]
Hi @Denpex do you still plan to work on this?
