### ISSUE TITLE
Order Details: Rename Labels and Add Fees

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#3084]
This is for the Orders → Order Details page.

## Order Total Updates

- “Paid by Customer” is becoming “Paid” for simplicity (for all orders, refunded or not)
- When a refund is processed, “Net Total” is becoming “Net Payment” to better reflect that it’s showing the total amount paid after the refund.

<img src="https://user-images.githubusercontent.com/198826/97629389-a8857d00-19f3-11eb-8b73-077259eb257b.png" width="300">

## Fees

You can add a fee item when creating a new product in wp-admin. The fee currently does not show up in Order Details. 

Add a Fee row in Order Details. 

<img src="https://user-images.githubusercontent.com/198826/97630284-fe0e5980-19f4-11eb-96c8-bccba12d22e1.png" width="300">

Ref p91TBi-36J-p2.

**Comment by raziqfarid** [comment]
@shiki Would love to work on this. Can you please assign this to me?

**Comment by shiki** [comment]
@raziqfarid Awesome! Thanks for contributing! I assigned this to you. 🙂
