### ISSUE TITLE
The keyboard is not correctly dismissed in Order -> Add Tracking screen

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#3102]
Ref. p5T066-1Bt#comment-6192

@rachelmcr while was testing the beta release 5.4 discovered a bug to the keyboard that is not hidden in the Add Tracking screen.

**I report her message here:**
_When I’m adding shipment tracking to an order, once I tap into the Tracking Number field the keyboard comes up and there’s no way to dismiss it. (I usually go through that screen top to bottom, so I choose a shipping provider, enter the tracking number, and then select the date.) I can’t find any way to change the focus away from that tracking number field so the keyboard goes away.
Although I can still select the date field and use the date picker, the keyboard remains on screen. Is there a way to auto-dismiss the keyboard once the date field is selected, or otherwise make it possible to dismiss the keyboard there?_

**It would be good in my opinion to dismiss the keyboard by pressing the date picker and also the return button on the keyboard.**

## Screenshots
<img src="https://user-images.githubusercontent.com/495617/98270177-e6077e80-1f8e-11eb-8432-f25df94fb7e4.png" width=300 />

**Comment by pmusolino** [comment]
Good first issue for a trial.

**Comment by ealeksandrov** [comment]
![Screen Recording 2020-11-26 at 18 36 26](https://user-images.githubusercontent.com/3132438/100370765-d02e2c00-3017-11eb-928b-607232c9a84e.gif)

Date picker is different now. But I understand that task is still mostly the same:
1. dismiss keyboard on "return"
2. dismiss keyboard when calendar field tapped

@pmusolino can you confirm?

**Comment by pmusolino** [comment]
Hi @ealeksandrov, exactly. The expected behavior is still the same 👍
