### ISSUE TITLE
[UL&S] Update strings: getting started with WordPress

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3118]
Update the copy `Enter your email address to log in...`
<img src="https://user-images.githubusercontent.com/2722505/98904363-6a5c8300-24f4-11eb-951f-807fc88f5bbd.png" width="350"/>

According to the design:
<img width="350" alt="Screenshot 2020-11-12 at 2 28 17 PM" src="https://user-images.githubusercontent.com/2722505/98904423-85c78e00-24f4-11eb-96ab-07347c780408.png">

**Comment by shiki** [comment]
I saw that this is already in the Done column in the Unified Login board. I'll close this now but feel free to reopen if I made a mistake. 😅
