### ISSUE TITLE
[UL&S] Update WPAuthenticator configuration flags

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3119]
`WPAuthenticator` can be initialised with an instance of `WordPressAuthenticatorConfiguration` which is a struct that encapsulates mostly boolean flags that will change the runtime behaviour of the Unified Login flow.

**Comment by shiki** [comment]
I saw that this is already in the Done column in the Unified Login board. I'll close this now but feel free to reopen if I made a mistake. 😅
