### ISSUE TITLE
[UL&S] Login prologue. Change order of login options, present "Ever Your Store Address" as the first option

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3128]
Attempt to change the ordering of the two options in the Login Prologue:
<Img src="https://user-images.githubusercontent.com/2722505/98760472-4f174800-240e-11eb-9966-a1bf505abf16.png" width="350"/>

**Comment by ctarda** [comment]
This does not seem to be possible out of the box. 

The two buttons at the bottom of the screen ("Continue with WordPress.com" and "Enter Your Store Address") are constructed by WPAuthenticator.LoginPrologueViewController, and the order does seem to be fixed. 

We would need to modify WPAuthenticator to add an extension point to decide the ordering of the buttons

**Comment by ctarda** [comment]
The relevant method to look at in WPAuthenticator is LoginPrologueViewController.buildUnifiedPrologueButtons

**Comment by shiki** [comment]
I saw that this is already in the Done column in the Unified Login board. I'll close this now but feel free to reopen if I made a mistake. 😅
