### ISSUE TITLE
[UL&S] UI. Updates to error states: jetpack not installed

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3130]
Update Error screens:

<img width="945" alt="Screenshot 2020-11-11 at 11 12 59 AM" src="https://user-images.githubusercontent.com/2722505/98760773-f0060300-240e-11eb-87b5-fe4dacb7896a.png">

**Comment by shiki** [comment]
I saw that this is already in the Done column in the Unified Login board. I'll close this now but feel free to reopen if I made a mistake. 😅
