### ISSUE TITLE
[UL&S] UI. Jetpack required

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3131]
<img width="293" alt="Screenshot 2020-11-11 at 11 14 11 AM" src="https://user-images.githubusercontent.com/2722505/98760837-1e83de00-240f-11eb-9a75-649081ac8a81.png">

**Comment by shiki** [comment]
I saw that this is already in the Done column in the Unified Login board. I'll close this now but feel free to reopen if I made a mistake. 😅
