### ISSUE TITLE
[UL&S] Login Prologue: Remove mention to Jetpack and link to Jetpack's configuration instructions

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3142]
This is how the Login Prologue looks now:

<img src="https://user-images.githubusercontent.com/2722505/98885112-6d437d80-24cc-11eb-9271-c81e24f1746c.png" width="350"/>

And this is how it should look:
<img src="https://user-images.githubusercontent.com/2722505/98885143-7df3f380-24cc-11eb-846e-1b3a1cfa4875.png" width="350"/>

Notice the mention to Jetpack has been removed

**Comment by shiki** [comment]
I saw that this is already in the Done column in the Unified Login board. I'll close this now but feel free to reopen if I made a mistake. 😅
