### ISSUE TITLE
[UL&S] Prologue: Update background color of area where bottom buttons seat

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3144]
We are passing a background color for this area as a parameter to WordPressAuthenticatorStyle. However, there does not seem to be a similar parameter in WordPressAuthenticatorUnifiedStyle, which makes this area background color not match WooCommerce's accent color.

**Comment by ctarda** [comment]
The relevant change to WPAuthenticator would be:

LoginPrologueViewContoller.buildPrologueButtons sets `buttonViewController.backgroundColor = style.buttonViewBackgroundColor`

**Comment by ctarda** [comment]
Actually the previous comment is not correct. The background color is set to clear in buildUnifiedPrologueButtons(). That, in turn, shows WPAuthenticator.LoginPrologueViewController's background color, which is WordPressAuthenticator.shared.unifiedStyle?.viewControllerBackgroundColor.

So, all that being said, the background color of the button area is set to the background color that we assign to the view controllers via WordPressAuthenticatorUnifiedStyle.

One potential solution is adding an extra (optional) property to WordPressAuthenticatorUnifiedStyle for this background color, with default value viewControllerBackgroundColor

**Comment by shiki** [comment]
I saw that this is already in the Done column in the Unified Login board. I'll close this now but feel free to reopen if I made a mistake. 😅
