### ISSUE TITLE
[UL&S] Continue with WP.com: remove link to WP terms of service displayed right below email textfield

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3145]
The link to WP.com links of service displayed below the textfield to enter email address should be removed.

This is how it looks now:
<img src="https://user-images.githubusercontent.com/2722505/98891079-60c52200-24d8-11eb-88de-f88470ecb707.png" width="350"/>

And this is how it should look:
<img src="https://user-images.githubusercontent.com/2722505/98891097-6c184d80-24d8-11eb-93d6-8a36e7cd0b9c.png" width="350"/>

**Comment by ctarda** [comment]
WPAuthenticator's `GetStartedViewController` declared and initialises a private array of `rows`, assigning its initial content to `[.instructions, .email, .tos]`.

A potential solution is finding a way to either override that property or to provide a parameter that would let us decide if we add the `.tos` section to the table view or not

**Comment by shiki** [comment]
I saw that this is already in the Done column in the Unified Login board. I'll close this now but feel free to reopen if I made a mistake. 😅
