### ISSUE TITLE
[UL&S] Prevent signups to wp.com

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3146]
1. Tap "Continue with wordpress.com"
2. Enter an email that does not match a wordpress.com account

At this moment, we present this screen:
<img src="https://user-images.githubusercontent.com/2722505/98902369-90802400-24f0-11eb-84f7-e9080b8b43c2.png" width="350"/>

However, we should present this one:
<img src="https://user-images.githubusercontent.com/2722505/98902375-9544d800-24f0-11eb-8e1b-f4a129ee1285.png" width="350"/>

**Comment by shiki** [comment]
I saw that this is already in the Done column in the Unified Login board. I'll close this now but feel free to reopen if I made a mistake. 😅
