### ISSUE TITLE
[UL&S] Implement logic to present screen to request users to enter another site address or login with a different account when entering a site address that does not match a wp.com account

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3161]
After entering the site address, WPAuthenticator calls the delegate method `shouldPresentUsernamePasswordController`

The delegate method receives a parameter of type `WordPressComSiteInfo` with boolean properties that can help us identify if the site is a wp.com site and if it has jetpack installed

This is where we would need to implement brand new UI to support the new screens:
<img width="419" alt="Screenshot 2020-11-17 at 5 53 00 PM" src="https://user-images.githubusercontent.com/2722505/99376127-7b93fe00-28ff-11eb-82a5-3bd8f3b5e1c5.png">
<img width="397" alt="Screenshot 2020-11-17 at 5 52 50 PM" src="https://user-images.githubusercontent.com/2722505/99376142-7f278500-28ff-11eb-91d2-50c0cf69a42e.png">

**Comment by shiki** [comment]
I saw that this is already in the Done column in the Unified Login board. I'll close this now but feel free to reopen if I made a mistake. 😅
