### ISSUE TITLE
Unable to load Content 

### ISSUE THREAD

**Issue by Dynamic453** [woocommerce/woocommerce-ios#3169]
Hello 
I have Woocommerce Store and everything is fine but stats are not working i already enable status on Jetpack but still nothing 
`020/11/18 3:58:10:715 pm  ⛔️ Dashboard (Top Performers) — Error synchronizing top earner stats: typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "regular_price", intValue: nil)], debugDescription: "Expected to decode String but found a number instead.", underlyingError: nil))
2020/11/18 3:58:10:716 pm  ⛔️ Error synchronizing top earners stats: typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "regular_price", intValue: nil)], debugDescription: "Expected to decode String but found a number instead.", underlyingError: nil))
2020/11/18 3:58:10:724 pm  ⛔️ Error loading dashboard: typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "regular_price", intValue: nil)], debugDescription: "Expected to decode String but found a number instead.", underlyingError: nil))
2020/11/18 3:58:14:347 pm  🔵 Tracked`

**Comment by rezzap** [comment]
Can you please submit a support request through the app by going to My Store > Settings (the gear icon in the top right corner) > Help & Support > Contact Support? Please share your site address with us there and our support team will follow up with you as soon as possible with some steps to try and resolve this. 

This is for reporting bugs that require developer attention, but the errors you are seeing should be able to be resolved by our support team. I'll close this request for now.
