### ISSUE TITLE
Variations: Attribute Values and Offered Options Management Flow

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#3182]
Partly depends on #3181. 

Refs p91TBi-3Oc-p2, p91TBi-2Ur-p2.

Given an entered new attribute or an existing attribute, allow users to add or select options to use. 

### Transition

<img src="https://user-images.githubusercontent.com/198826/99741826-5f26cb80-2a8f-11eb-9f82-81b90c432628.png" width="600">

### Options Management

<img src="https://user-images.githubusercontent.com/198826/99755054-03683c80-2aa7-11eb-95ca-2211cf3c0ce7.png" width="600">

## Goals

- [ ] From #3181, accept a new attribute name. This new attribute should be created as a product-level attribute. 
- [ ] If the user selected an existing attribute in #3181, synchronize and display existing options. 
- [ ] Allow the user to select options to _offer_. This selected option will be used to generate the variations in a later task. 
- [ ] Allow the user to sort offered options. 
- [ ] Allow the user to remove an offered option from the list.

For now, we're not going to allow users to permanently delete an attribute value. If they make typos, they just don't have to select that as an offered option. p91TBi-3Oc-p2#comment-2421

---

Android: https://github.com/woocommerce/woocommerce-android/issues/3208

**Comment by pmusolino** [comment]
Connected task https://github.com/woocommerce/woocommerce-ios/issues/3412

**Comment by Ecarrion** [comment]
Closed in favor of #3527 #3528 #3529 #3530
