### ISSUE TITLE
Variations: Renaming an Attribute

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#3212]
Ref p91TBi-3Oc-p2.

From #3183, users would be presented with the options management screen (#3182). On that screen, the user should be able to rename the attribute. 

<img src="https://user-images.githubusercontent.com/198826/100246881-f0b29500-2ef6-11eb-82c8-998066069eab.png" width="800">

## Goals 

- [x] Add a Rename button in the options menu.
- [x] Build and Present the Rename Attribute screen.
- [x] Tapping on Done will rename the attribute. 
- [x] Add Tracking https://github.com/woocommerce/woocommerce-ios/issues/3703

---

Android: https://github.com/woocommerce/woocommerce-android/issues/3214

**Comment by Ecarrion** [comment]
Closed the wrong issue 😇
