### ISSUE TITLE
Site Address login screen input fields overlap with keyboard

### ISSUE THREAD

**Issue by rezzap** [woocommerce/woocommerce-ios#3215]
**Describe the bug**
On the Site Address Login screen, the input fields for Username and Password don't scroll. A user has reported in app review that the keyboard covers the fields and prevents input. 

I wasn't able to reproduce this on my iPhone X, but I do see the screen doesn't scroll and probably overlap on different size phones. 

**To Reproduce**
1. Go to the main login screen.
2. Click on 'entering your site address' and add a site address to connect to.
3. On the next screen you won't be able to scroll up or down in the fields and some devices most likely get the overlap.

**Screenshots**
![IMG_EA81042A97A3-1](https://user-images.githubusercontent.com/10325627/100339599-f7faa100-2fd1-11eb-8ec0-5536596bbb21.jpeg)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone X
- iOS version: 4.12
- WooCommerce iOS version: 5.4

Reported in a 1* app review: 

> Poor design and buggy
by Big Blue Squid – Nov 22, 2020

> The login pages don’t scroll, so the keyboard covers the input boxes.
Logins aren’t accepted unless using the WordPress, google or apple accounts. There is an option to use your own site login, but it doesn’t work.

**Comment by itsmeichigo** [comment]
Closing because the design has changed now:

<img src="https://user-images.githubusercontent.com/5533851/156335754-4376ce09-c588-42e6-bb53-6707e7038bac.jpeg" width=320 />
