### ISSUE TITLE
[UL&S] UI. Not a WordPress site

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3218]
Implement UI for error screen when user enters a site address that does not correspond with a WordPress site

<img src="https://user-images.githubusercontent.com/2722505/100408424-ec78aa00-30a5-11eb-9704-0e32726b74c0.png" width="350"/>

**Comment by shiki** [comment]
I saw that this is already in the Done column in the Unified Login board. I'll close this now but feel free to reopen if I made a mistake. 😅
