### ISSUE TITLE
[UL&S] Fix margins of custom UI in tablets

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3224]
The custom UI provided to WPAuthenticator spreads horizontally to cover all the available space. 

It should respect the same margins WPAuthenticator inserts in the UL UI it provides by default.

Look at LoginViewController.setTableViewMargins

**Comment by shiki** [comment]
I saw that this is already in the Done column in the Unified Login board. I'll close this now but feel free to reopen if I made a mistake. 😅
