### ISSUE TITLE
Order Creation: add navigation bar button for adding a new order (step 2)

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#3236]
As part of the Order Creation process, we should add the bar button item in the Order List. The button should be hidden if the `orderCreation` flag is disabled.

<img src="https://user-images.githubusercontent.com/495617/100633293-3247a380-332e-11eb-9fde-d28b1459fe64.png" width=350 />

**Comment by shiki** [comment]
I'm going to close this for now since we're not actively working on Order creation. Feel free to reopen if I made a mistake. 😅
