### ISSUE TITLE
Order Creation: add the Order Creation screen (step 3)

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#3237]
Discussion here: p91TBi-2pw

As part of the Order Creation, we should implement this new screen which is the skeleton for creating a new order from mobile.
<img src="https://user-images.githubusercontent.com/495617/100633614-99fdee80-332e-11eb-8f45-321ac41ce02b.png" width=350 />

**Comment by shiki** [comment]
I'm going to close this for now since we're not actively working on Order creation. Feel free to reopen if I made a mistake. 😅
