### ISSUE TITLE
Order Creation: select products and product variation to be added to a new order (step 7)

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#3238]
As part of the Order Creation process, the user can add products and product variations to a new order.

The first step, tapping the "Add Items" row will be to present the Product Selector screen (plus search). 
<img src="https://user-images.githubusercontent.com/495617/100634027-0d9ffb80-332f-11eb-9165-4b3392b48857.png" width=800 />

For Variants, should be possible to select a variation.

<img src="https://user-images.githubusercontent.com/495617/100634174-3e803080-332f-11eb-823e-157729208706.png" width=400 />

**Comment by shiki** [comment]
I'm going to close this for now since we're not actively working on Order creation. Feel free to reopen if I made a mistake. 😅
