### ISSUE TITLE
Order Creation: add a custom item to a new order (step 8)

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#3239]
As part of the Order Creation process, we should allow users to add a custom item to a new order.

After selecting "Add Custom item"

![100634027-0d9ffb80-332f-11eb-9165-4b3392b48857](https://user-images.githubusercontent.com/495617/100634673-e39b0900-332f-11eb-8cdd-0102830f1775.png)

we should show this new screen

![Schermata 2020-11-30 alle 17 17 43](https://user-images.githubusercontent.com/495617/100634759-fa416000-332f-11eb-84d7-16a719a644a4.png)

**Comment by shiki** [comment]
I'm going to close this for now since we're not actively working on Order creation. Feel free to reopen if I made a mistake. 😅
