### ISSUE TITLE
Order Creation: edit or delete an item inside a new order (step 9)

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#3240]
As part of the Order Creation, we should allow our users to edit or delete an item added to a new order.

| Tap an existing item            |  Item details |
:-------------------------:|:-------------------------:
![Schermata 2020-11-30 alle 17 23 21](https://user-images.githubusercontent.com/495617/100635399-c581d880-3330-11eb-896e-fb16aff191ae.png) | ![Schermata 2020-11-30 alle 17 23 53](https://user-images.githubusercontent.com/495617/100635501-e2b6a700-3330-11eb-92a7-da8309d20330.png)

**Comment by shiki** [comment]
I'm going to close this for now since we're not actively working on Order creation. Feel free to reopen if I made a mistake. 😅
