### ISSUE TITLE
Order Creation: networking, yosemite and storage layers for fetching and store Customers (step 4)

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#3241]
As part of the Order Creation, we should implement the networking, Yosemite, and storage layers for fetching every customer.

Here is possible to find the [API documentation](https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-customers).

**Comment by shiki** [comment]
I'm going to close this for now since we're not actively working on Order creation. Feel free to reopen if I made a mistake. 😅
