### ISSUE TITLE
Order Creation: networking, yosemite and storage layers for creating a new Customer (step 5)

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#3242]
As part of the Order Creation process, after having worked on #3241 we should implement the networking, Yosemite and storage layers for creating a new customer following the [API documentation](https://woocommerce.github.io/woocommerce-rest-api-docs/#create-a-customer).

**Comment by shiki** [comment]
I'm going to close this for now since we're not actively working on Order creation. Feel free to reopen if I made a mistake. 😅
