### ISSUE TITLE
Order Creation: list customers and add a new customer screens (step 6)

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#3243]
As part of the Order Creation step, we should implement two new screens: List Customers and the possibility to add a New Customer, after having implemented the layers required here #3241 and here #3242. 

![Schermata 2020-11-30 alle 17 38 20](https://user-images.githubusercontent.com/495617/100637167-daf80200-3332-11eb-995e-c6160ee99932.png)

**Comment by shiki** [comment]
I'm going to close this for now since we're not actively working on Order creation. Feel free to reopen if I made a mistake. 😅
