### ISSUE TITLE
Refunds: Typo in refund success notice

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#3256]
**Describe the bug**

There's a small typo in the refund success notice (after issuing a refund):

> 🎉 Products successfuly refunded

It should be `successfully` (instead of `successfuly`) there.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/100738195-2b23a280-33cd-11eb-918f-121d06179ad4.PNG" width="300px">

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 14.2
- WooCommerce iOS version: 5.6.0.0 TestFlight beta

**Comment by shiki** [comment]
This was fixed in the release branch via #3258. Thanks, Ernesto!
