### ISSUE TITLE
Product Images for variable products missing from Order details screen 

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3269]
**Describe the bug**
Some product images are missing from the Order Details screen. The images are displayed in the Product list though. It seems like the Products that do not display any image in the Order Details screen are Variable Products.

Order Details:
<img src="https://user-images.githubusercontent.com/2722505/100830518-cdf82180-349e-11eb-8039-5669df9a9961.PNG" width="350"/>

Product List:
<img src="https://user-images.githubusercontent.com/2722505/100830499-c8024080-349e-11eb-8dfe-b1251773779e.PNG" width="350"/>

<img src="https://user-images.githubusercontent.com/2722505/100830706-35ae6c80-349f-11eb-9d68-bf1f25d01aae.gif" width="350"/>

Tapping on any Product displays a modal view, where the images are visible, no matter if it is a variable product or not.

<img src="https://user-images.githubusercontent.com/2722505/100831242-562af680-34a0-11eb-9f48-91dd89d85d5e.gif" width="350"/>

**To Reproduce**
0. In your store dashboard, check the existing Products, make sure all have a Product Image set.
1. In your store dashboard (WooCommerce > Orders > Add order), create a new order.
2. Add a mix of Simple Products and Variable Products to the order
3. Create the order.
4. Navigate to the Orders tab in the iOS app. Select the new order. Notice images missing for Products with variations
5. Navigate to the Products tab. Notice how the Products that were missing images in the Order Details screen now display their associated image in the Products tab.

**Screenshots**

Order Details screen:
<img src="https://user-images.githubusercontent.com/2722505/100830499-c8024080-349e-11eb-8dfe-b1251773779e.PNG" width="350"/>

Products tab:
<img src="https://user-images.githubusercontent.com/2722505/100830706-35ae6c80-349f-11eb-9d68-bf1f25d01aae.gif" width="350"/>

**Expected behavior**
I would expect the Product Images to be displayed in the Order Details screen

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 12 Pro, iPhone 8
- iOS version: iOS 14.2.1
- WooCommerce iOS version: 5.6 (5.6.0.1)

**Comment by shiki** [comment]
Related to https://github.com/woocommerce/woocommerce-ios/issues/2113 and https://github.com/woocommerce/woocommerce-ios/issues/1869.
