### ISSUE TITLE
Order Details: "Details" screen duplicates information from the main order screen. Not needed?

### ISSUE THREAD

**Issue by eshurakov** [woocommerce/woocommerce-ios#3279]
**Details**
When an order is in [failed, on hold, pending] state, there is a "details" row under the list of products on the order screen. Details screen shows same information that you can already get from the main order screen.

Maybe details screen can be removed?

|||
|-|-|
|![IMG_DBE70A8261EC-1](https://user-images.githubusercontent.com/54751/100980656-de170c00-3545-11eb-972b-71ba43a624af.jpeg)|![IMG_DBE70A8261EC-2](https://user-images.githubusercontent.com/54751/100980678-e4a58380-3545-11eb-97bf-8c11dc463586.jpeg)|

**Mobile Environment**
Please include:
- Device: iPhone
- iOS version: iOS 14.2
- WooCommerce iOS version: 5.6

**Comment by eshurakov** [comment]
If details screen is removed, issue https://github.com/woocommerce/woocommerce-ios/issues/3274 will also be fixed.

**Comment by jaclync** [comment]
From [G's comment](https://github.com/woocommerce/woocommerce-ios/pull/3769#pullrequestreview-601910258), we are good to remove the "Details" row in order details and the product list screen, which presents the same information as the product list in order details. cc @woocommerce/mobile-designers 

I'll work on this shortly!

**Comment by jaclync** [comment]
We no longer have the "details" row in the products section anymore, I also checked [`OrderDetailsDataSource` code to confirm](https://github.com/woocommerce/woocommerce-ios/blob/4eb7ba59270a9d899b0a19a04a07f14640f2fa05/WooCommerce/Classes/ViewModels/Order%20Details/OrderDetailsDataSource.swift#L902-L950). Closing!

<img src="https://user-images.githubusercontent.com/1945542/158960101-bde6e695-6222-474f-8e69-917709da4794.png" width="300" />
