### ISSUE TITLE
Remove Option to Change Product Status to Trashed

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#3288]
As suggested by @hichamboushaba and agreed to by @Garance91540 in https://github.com/woocommerce/woocommerce-android/issues/3047#issuecomment-738048225, we should remove the option to change a Product's status to Trashed. 

Refer to https://github.com/woocommerce/woocommerce-android/issues/3047 what the implications are if we keep it.

**Comment by eshurakov** [comment]
I checked and iOS doesn't show Trashed status in the product settings. iOS only shows and lets select from: published, draft and pending review.
[Related code](https://github.com/woocommerce/woocommerce-ios/blob/14ced0b655757025532350c4e3bd281a064b84d8/WooCommerce/Classes/ViewRelated/Products/Edit%20Product/Product%20Settings/List%20Selector%20Data%20Source/ProductStatusSettingListSelectorCommand.swift)

Therefore closing this :-)

**Comment by shiki** [comment]
Thank you for checking it! 🙏
