### ISSUE TITLE
[UL&S] Add tests for view models supporting errors presented when login with a "not wp" site or a non valid wp.com account

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3292]
The logic to support both those errors has already been merged, or in review, but I forgot to add the corresponding unit tests for NotWPErrorViewModel and NotWPAccountViewModel

**Comment by shiki** [comment]
I saw that this is already in the Done column in the Unified Login board. I'll close this now but feel free to reopen if I made a mistake. 😅
