### ISSUE TITLE
Not seeing the notification dot on the Woo app badge

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-ios#3298]
Hi team! As reported in [this Slack convo](https://a8c.slack.com/archives/CGPNUU63E/p1607331727000500), I am not seeing a red dot for notifications on my Woo app badge on my iOS Home screen. 

https://d.pr/i/8AKd5S

I have checked my settings and I am allowing notifications for the Woo app, and I am not seeing the badge when creating new orders or reviews.

Anyone has an idea on the issue?

Device: iPhone 11
iOS Version: 14.0.1
WC iOS version: 5.5.0.2

**Comment by BDoGG12** [comment]
Hi, Do you mind if I take a look on this issue?

**Comment by joshheald** [comment]
I can't repro this any more, badges work correctly.
