### ISSUE TITLE
Improve Show / Hide Billing Animation

### ISSUE THREAD

**Issue by jleandroperez** [woocommerce/woocommerce-ios#330]
### Details:
Let's check if we can improve the `Show Billing` / `Hide Billing` animation (Order Details) so that it grows / shrinks gradually.

**Comment by mindgraffiti** [comment]
**Note:** this will not be an easy task. Custom cell animations inside of a standard tableview aren't supported. We'll have to convert to a scrollview with custom views inside of it, and then animate the views. The only other solution I can think of to decrease scope and still improve the screen is to pick a better standard tableview animation and leave it at that.

**Comment by bummytime** [comment]
> The only other solution I can think of to decrease scope and still improve the screen is to pick a better standard tableview animation and leave it at that.

This sounds reasonable to me. 👍

**Comment by mindgraffiti** [comment]
Fixed due to a redesign. Thanks @kyleaparker !
