### ISSUE TITLE
[UL&S] Error screens in landscape

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3300]
Brought up during the review of #3286

![101341425-098a5580-38bc-11eb-87f2-43381e88db01](https://user-images.githubusercontent.com/2722505/101416265-6de0ff80-3924-11eb-9a2c-576ecf28ad1d.png)

The main action buttons overlap the error message. The simplest solution might be changing the axis of the stack view on rotation

**Comment by ctarda** [comment]
@Garance91540 do you have any suggestion to solve this? Would placing the illustration and the error message side by side work or should I just make the illustration smaller so that illustration and text fit vertically?

**Comment by Garance91540** [comment]
Hi @ctarda , would it be possible to place the CTAs side by side instead of stacked vertically? https://d.pr/i/VZR37f

This is how we've been addressing those on Android

**Comment by ctarda** [comment]
Thanks @Garance91540 ! It should work!

**Comment by ctarda** [comment]
Hi again @Garance91540 sorry for the noise!

I am looking at the now, and it turns no other screens in the login flow support rotation (on phones).

So I have been looking into WPAuthenticator, and it turns out, the library only supports rotation on iPad (but not on iPhone). So I am going to disable rotation in this screen for now, so that we can reassess later.

**Comment by shiki** [comment]
This was moved to the Done column in the project so I'll close this issue.
