### ISSUE TITLE
[UL&S] Update "Find your site address" copy to "Find your store address"

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3323]
This can be delayed to phase 2

1. Select Login with Store Address
2. Notice copy below textfield

<img src="https://user-images.githubusercontent.com/2722505/101760620-10aca000-3b16-11eb-9d09-9af02cc01cf0.png" width="350"/>

**Comment by rachelmcr** [comment]
Closing as this was done in https://github.com/woocommerce/woocommerce-ios/pull/3329.
