### ISSUE TITLE
[UL&S] Change title: Get started to Log In

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3324]
This can be delayed to phase 2.

1. Select Login with wordpress.com account
2. Notice the title

<img src="https://user-images.githubusercontent.com/2722505/101760863-684b0b80-3b16-11eb-8b63-a5354525e37a.png" width="350"/>

**Comment by rachelmcr** [comment]
Closing; this was done in https://github.com/woocommerce/woocommerce-ios/pull/3328.
