### ISSUE TITLE
[UL&S] Error message when entering a non-valid url address

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3325]
This can be delayed to phase 2, if it is too complicated to implement.

The following error seems to originate in WordPressKit. In theory, we should already be able to intercept it.

<img src="https://user-images.githubusercontent.com/2722505/101761169-c7a91b80-3b16-11eb-8105-aabbbbeafa4f.png" width="350"/>

**Comment by ctarda** [comment]
@Garance91540 I was looking into this, and I was building a popover like the one in the screenshot but with similar wording to the error message presented in Android, but I was wondering if this case would be a good candidate for presenting this error instead (which would have the added benefit of being easier to implement):

<img width="443" alt="Screenshot 2020-12-14 at 10 36 16 AM" src="https://user-images.githubusercontent.com/2722505/102034177-5c05cd80-3df8-11eb-9f1a-9bf016b7970a.png">

What do you think?

**Comment by ctarda** [comment]
This is how it would look in action:
<img src="https://user-images.githubusercontent.com/2722505/102034616-6e343b80-3df9-11eb-9009-c26d14358fee.gif" width="350"/>

**Comment by Garance91540** [comment]
Hi Cesar, that works!
