### ISSUE TITLE
Errors in login are being clipped for long sentences, for example in German

### ISSUE THREAD

**Issue by mzorz** [woocommerce/woocommerce-ios#3331]
**Describe the bug**
Errors in login are being clipped for long sentences, for example in German

**To Reproduce**
1. switch your phone to German
2. try to login, but using a wrong account
3. see error 

**Screenshots**
<img width="392" alt="Screen Shot 2020-12-10 at 17 53 51" src="https://user-images.githubusercontent.com/6597771/101830822-d6da9a00-3b13-11eb-8f98-a02cc4fa3012.png">

**Expected behavior**
Errors should be clear in all languages (don't clip sentences for errors)

**Isolating the problem (mark completed items with an [x]):**
This was reported by a user (ref `z-3561317`)
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: 
- iOS version: 
- WooCommerce iOS version: 5.5.0.2

**Comment by joshheald** [comment]
These are now shown in a full screen error, but one of the strings is still a little truncated in German.
