### ISSUE TITLE
[UL&S] Update copy "Find my site address" in popup alert

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3333]
Pointed out during the review of #3329

<img src="https://user-images.githubusercontent.com/2722505/101884972-6e072680-3bd4-11eb-93d7-5a3c40355ce2.png" width="350"/>

**Comment by ctarda** [comment]
This requires digging into WPAuthenticator a bit. 

Those strings are declared in FancyAlertViewController+LoginError, and we would need to find a way for those strings to use the values provided in WordPressAuthenticatorDisplayStrings

**Comment by allendav** [comment]
In the context of WooCommerce, I think "Store Address" may be confused with the physical address of the business, e.g. like is shown in wp-admin > WooCommerce > Settings:

<img width="854" alt="store-address" src="https://user-images.githubusercontent.com/1595739/103827202-4b2e2d80-502d-11eb-84ab-3ed51b356692.png">

I would recommend we instead use "Site Address (URL)" like is shown in wp-admin > Settings > General. Thoughts?

<img width="1152" alt="site-address-url" src="https://user-images.githubusercontent.com/1595739/103827367-a9f3a700-502d-11eb-839b-517761c996c9.png">

**Comment by ctarda** [comment]
👋  @woocommerce/mobile-designers I'd like to bring @allendav 's [comment above](https://github.com/woocommerce/woocommerce-ios/issues/3333#issuecomment-755761898) to your attention 😊

**Comment by Garance91540** [comment]
👋 I think the copy "your store address appears in the bar at the top of the screen when you visit your site on safari" makes it hard to get confused, but we can never be too cautious so we can leave site "site" instead of "Store" in this dialog. 

I noticed there's a typo: "your store address appears in the bar at the **the** top of the screen when you visit your site on safari"

**Comment by allendav** [comment]
👍 the the - I totally missed that - good catch @Garance91540 !

Edit: Opened here https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/556

**Comment by allendav** [comment]
@ctarda ok to close this issue?

**Comment by ctarda** [comment]
@allendav not yet 😉  we would need to pin the dependency with WPAuthenticwtor to the version that implements the fix, so we still need to submit a PR with that change to WooCommerce one the PR bumping the pod version of WPAuthenticator is merged 😃

**Comment by allendav** [comment]
Done in https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/commit/f3ec73993dd73757f6b923e1b087bd085bc24eaa https://github.com/woocommerce/woocommerce-ios/commit/1f53f6ab767442c4ef9ea6709da57943168d0370#diff-8f7d6adf31268a2d897ee34bd170592648d6e520aa237104395e4a4438af50cb
