### ISSUE TITLE
[UL&S] Improve UI tests

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3347]
Add UI tests to cover all UL&S flows

**Comment by rachelmcr** [comment]
This is also something that Platform9 has been planning to help with, at least to add UI tests for the UL&S flows that we smoke test regularly. (We started to work on UI tests and then paused to wait for UL&S to launch.) It's something that @startuptester was planning to look at in early 2021, but @ctarda if you're interested in learning UI testing I'm sure we can make it a collaboration!

**Comment by ctarda** [comment]
@rachelmcr Oh, I would definitely love to learn about UI testing, thanks for offering your guidance! 🙇 

Yesterday I pretty much lifted the infrastructure in WordPress-iOS and dropped it into WooCommerce to do the bare minimum to have one test passing. 

I would love to get a few more flows tested either today or tomorrow, do you mind if I ping you and @startuptester  in the PR to get your feedback?

**Comment by rachelmcr** [comment]
> I would love to get a few more flows tested either today or tomorrow, do you mind if I ping you and @startuptester in the PR to get your feedback?

Please do! Just a heads up that I'll likely be fairly busy the next couple days beta testing the new beta builds, so I may not have time to do a thorough review but I'll provide any feedback I can.

@startuptester This is worth keeping in mind when Platform9 gets to work on these tests again:

> Yesterday I pretty much lifted the infrastructure in WordPress-iOS and dropped it into WooCommerce to do the bare minimum to have one test passing.

It'd be good to think about how we can better share the common UI test infrastructure between WordPress and WooCommerce. (Especially around mocks and the unified login flow.)
