### ISSUE TITLE
Setting a sale price: error notice appears as many times as Done button is pressed

### ISSUE THREAD

**Issue by eshurakov** [woocommerce/woocommerce-ios#3357]
**Describe the bug**
If sale price is lower than regular price a notice is shown when trying to save the changes. Pressing "Done" button X times will enqueue the notice to show X times even if I leave the screen. 

**To Reproduce**
1. Open a product
2. Click on 'Price'
3. Set 'sale' price higher than 'regular' price
4. Press 'Done' button multiple times
5. Notice the error message
6. Leave the screen
7. Notice that the same error message keep coming up on screen

**Expected behavior**
Tap on Done button would show error message only if it's not enqueued or on screen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone
- iOS version: 14.3
- WooCommerce iOS version: 5.6

**Comment by pmusolino** [comment]
I'm closing this issue since there is another one already opened for the same problems that regard not only the product price, but every point where we use the Notice Presenter. https://github.com/woocommerce/woocommerce-ios/issues/1752 👍
