### ISSUE TITLE
[UL&S] Help links can be cut off instead of wrapping the text

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#3361]
**Describe the bug**

Help links in the login flow can end up cut off instead of wrapping the text to fit on smaller screens, or with larger text sizes. For example, on the error screen when you enter an email not associated with a WordPress.com account, this text:

> Need help finding the connected email?

Can become this text on an iPhone XS (not a particularly small device):

> Need help finding...connected email?

**To Reproduce**
1. Start logged out of the app. Use a device with a smaller screen size, and/or go to the device accessibility settings and choose a larger text size.
2. Select "Continue with WordPress.com."
3. Enter an email address *not* linked to a WordPress.com account.
4. On the error screen, notice the help link is cut off.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/102369415-cf077380-3fb3-11eb-9c8d-7e0ed71a653e.png" width="300px">

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 14.2
- WooCommerce iOS version: 5.7.0.0 TestFlight beta

**Comment by ctarda** [comment]
This is an issue with the constraints or the `extraInfroButton` in `ULErrorViewController`. Maybe the best solution is to allow that button to span two lines.

**Comment by pmusolino** [comment]
@mokagio discovered a similar issue on the iPod touch

<img width="506" alt="Screen Shot 2021-08-06 at 3 33 36 pm" src="https://user-images.githubusercontent.com/495617/128494484-3083adf0-51f8-41f5-9e83-56b2f832ce56.png">

**Comment by mokagio** [comment]
I'm pretty sure one can reproduce simply by logging into Woo with a WordPress.com account that doesn't have a store, but the way I got there was by running the UI tests without the mocks in the background.

**Comment by johncodeos** [comment]
Found another one.
When you type an email that is not associated with a wordpress.com account, the help link goes over the button "Enter Your Address"

Device: iPod touch 7th gen

Screenshot:
<img src="https://user-images.githubusercontent.com/11445928/144844488-9f83bb67-af7e-46c4-a818-6b36b794c639.png" width="400" height="100%">

**Comment by johncodeos** [comment]
This issue hasn't been fixed completely #5640
