### ISSUE TITLE
[UL&S] "What is Jetpack" help text missing punctuation

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#3363]
**Describe the bug**

On the "What is Jetpack" error screen and help modal, there is missing punctuation:

1. The link on the error screen should have a question mark (“What is Jetpack?” instead of “What is Jetpack”).
2. The text on the modal should have a period at the end of the sentence ("... including push notifications and stats.")

**To Reproduce**
1. Start logged out of the app.
2. Select the “Enter your store address” option.
3. Enter a self-hosted site address that doesn’t have Jetpack.
4. Tap the "What is Jetpack" help link.

**Screenshots**

Jetpack error screen|Jetpack help modal
-|-
![2020-12-16 15 02 40](https://user-images.githubusercontent.com/8658164/102373417-12fc7780-3fb8-11eb-8fd2-dfedce9ec0a8.png)|![2020-12-16 15 03 09](https://user-images.githubusercontent.com/8658164/102373424-142da480-3fb8-11eb-8845-52565c118e6e.png)

**Mobile Environment**
Please include:

- Device: iPhone XS
- iOS version: 14.2
- WooCommerce iOS version: 5.7.0.0 TestFlight beta

**Comment by ctarda** [comment]
This is a pretty easy fix, the strings are constants declared in Woo

**Comment by 96RadhikaJadhav** [comment]
@rachelmcr  Can I work on the issue?

**Comment by rachelmcr** [comment]
@96RadhikaJadhav Sure, thank you! Let us know if you have any questions. :)

**Comment by AliSoftware** [comment]
💡 One thing to be aware of if you want to work on the issue: thanks to the automation process and scripts we use, you only need to change the string in the `.swift` file where those appear, as they are the source of truth there.

_(The `.strings` file for `en.lproj` is later generated/updated from that source code by our scripts, and we partner with a translation company to provide us the translations for all other locales and `.lproj` files.)_
