### ISSUE TITLE
[UL&S] Mixed styles on epilogue/error screen when WordPress.com account has no connected WooCommerce stores

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#3364]
**Describe the bug**

There are odd, mixed styles on the epilogue/error screen when WordPress.com account has no connected WooCommerce stores.

**To Reproduce**
1. Start logged out of the app.
2. Select the WordPress.com login option.
3. Enter the email address for a WordPress.com account that is *not* connected to any WooCommerce stores.
4. Finish logging in with the account password or magic link.
5. Notice that the epilogue/error screen shows the error message, illustration, and primary CTA in the middle of the screen with a white background, surrounded by the old epilogue styling (grey background).

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/102375458-74254a80-3fba-11eb-974e-b0c2b05e3a29.PNG" width="300px">

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 14.2
- WooCommerce iOS version: 5.7.0.0 TestFlight beta

**Comment by ctarda** [comment]
This sounds like it should be fixable by looking at the styles provided to WPAuthenticator on initialization.
