### ISSUE TITLE
[UL&S] Logging in with Google account not linked to WordPress.com is a dead end

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#3365]
**Describe the bug**
If you try to log in to WordPress.com using a Google account that isn't already linked to WordPress.com, you hit a dead end:

* The "Log in" screen says it will create a new WordPress.com account, but it doesn't.
* The screen you end up on has options to try with another email or site address, but tapping on them doesn't go anywhere.

**To Reproduce**
1. Start logged out of the app.
2. Select the WordPress.com login option.
3. Select "Continue with Google."
4. Select or log in to a Google account that is *not* linked to a WordPress.com account.
5. On the resulting error screen, tap the options to try logging in a different way and notice they don't do anything.

**Screenshots**

"Log in" screen|Error screen
-|-
![2020-12-16 14 53 20](https://user-images.githubusercontent.com/8658164/102377923-23632100-3fbd-11eb-82d2-d1e07c0be060.png)|![2020-12-16 16 24 05](https://user-images.githubusercontent.com/8658164/102377935-252ce480-3fbd-11eb-8ac3-828951067eba.png)

**Mobile Environment**
Please include:

- Device: iPhone XS
- iOS version: 14.2
- WooCommerce iOS version: 5.7.0.0 TestFlight beta

**Comment by ctarda** [comment]
This is a clear oversight on my side. We would need to check if:
- We get notified that Continue With Google has been completed and we get notified that there is no WP.com account associated to that login
- If that is the case, we would need to provide custom UI to handle the error.

This might require digging into WPAuthenticator.
