### ISSUE TITLE
[UL&S] Gravatar should be a circle on password login screen

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#3366]
**Describe the bug**
On the password login screen, the Gravatar should be a circle but appears as a square.

**To Reproduce**
1. Start logged out of the app.
2. Select the WordPress.com login option.
3. Enter the email address for a WordPress.com account with a password.
4. Notice the Gravatar on the password screen is square instead of a circle.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/102379290-a5077e80-3fbe-11eb-8ae4-e830d69d8064.png" width="300px">

**Mobile Environment**
Please include:

- Device: iPhone XS
- iOS version: 14.2
- WooCommerce iOS version: 5.7.0.0 TestFlight beta

**Comment by ctarda** [comment]
This is PasswordViewController. The gravatar view is part of `GravatarEmailTableViewCell`, and the image is set in the `configure` method. I don't see any code that sets any mask or a cornerRadius, but this same cell works on WP, so there might be some configuration missing on our side
