### ISSUE TITLE
[UL&S] Error screen for non-WordPress sites is missing site address

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#3368]
**Describe the bug**
If I enter a store address that isn't a WordPress site, I end up on an error screen. That screen should have an error that includes the address I entered, like this:

> The website **example.com** is not a WordPress site.

However, the message is missing the address:

> The website is not a WordPress site.

**To Reproduce**
1. Start logged out of the app.
2. Select the store address login option.
3. Enter the address of a site that doesn't use WordPress.
4. Notice the error screen doesn't include the address you entered.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/102381671-6c1cd900-3fc1-11eb-9685-3330d57d1c54.png" width="300px">

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 14.2
- WooCommerce iOS version: 5.7.0.0 TestFlight beta

**Comment by ctarda** [comment]
Depending on the way this screen is reached, it might be possible that we do not actually know the site url. 

We reach this screen from two different code paths:
* AuthenticationManager's `shouldPresentUsernamePasswordController`. This method receives an instance of `WordPressComSiteInfo`, that, in most cases, contains the site url. In those cases, we can provide the url to the error UI
* AuthenticationManager's `handleError(_ error: Error, onCompletion: @escaping (UIViewController) -> Void)`. In this case, the error does not contain the URL (in most cases). This is where we present an error without including the url

**Comment by rachelmcr** [comment]
Closing this as the current error screen is not meant to show the site URL:

![Simulator Screenshot - iPhone 15 - 2024-08-20 at 16 08 59](https://github.com/user-attachments/assets/8c849579-8557-42dd-b215-b46fbb28bbd7)
