### ISSUE TITLE
[UL&S] Crash after entering site credentials in store address login flow

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#3384]
**Describe the bug**

The app crashes after I enter my site credentials in the store address login flow. cc @ctarda 

**To Reproduce**
1. Start logged out of the app.
2. Select "Enter your store address."
3. Enter your WooCommerce store address and select "Continue." (Be sure to use a self-hosted store, not a store hosted on WordPress.com.)
4. Enter your username/password and select "Continue."

Result: Crash!

**Expected**

I expect to end up on a screen asking me to log in to my connected WordPress.com account.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 14.2
- WooCommerce iOS version: 5.7.0.1

**Comment by ctarda** [comment]
The crash happens on the WooCommerce side (which is good because it is not due to changes to Authenticator)

The crash is due to a `fatalError("Self Hosted sites are not supported. Please review the Authenticator settings!")` in AuthenticationManager's `func sync(credentials: AuthenticatorCredentials, onCompletion: @escaping () -> Void)`

**Comment by ctarda** [comment]
@Garance91540 That means that, until now, we have not supported logging in with a self hosted site.

In fact, if I try to log in to a self-hosted site with the version of the app currently in the App Store, I get this error:
<img src="https://user-images.githubusercontent.com/2722505/102679482-2fccc100-41eb-11eb-89c6-90cc153f43d4.PNG" width="350"/>

So, do we support logging in to self-hosted sites? If we don't, should be present an error like this, but with different copy?:
<img width="342" alt="Screenshot 2020-12-19 at 11 15 36 AM" src="https://user-images.githubusercontent.com/2722505/102679563-9225c180-41eb-11eb-9f73-1fb08a367df8.png">

**Comment by ctarda** [comment]
Another possibility is: when WPauthenticator calls AuthenticationManager's `shouldPresentUsernamePasswordController`, present a custom error if `isSelfHosted` == true

**Comment by Garance91540** [comment]
Hi @ctarda ! I think we support self-hosted site, at least I've been able to log in with mine so far. I think there's a potential confusion here:[ This screen](https://d.pr/i/ruNKPU) should be shown if the site doesn't have WP installed, but it can totally be a self-hosted site.

**Comment by designsimply** [comment]
I ran into this crash after logging out then back in to a Jetpack-connected site after upgrading from 4.7.0.0 to 5.7.0.1 (both are TestFlight betas) and trying to use the "Enter Your Store Address" flow.

Video: [1m5s](https://cloudup.com/c1Buz6TOnZ9)

* Crashlog from App Store Connect: [testflight_feedback.zip](https://github.com/woocommerce/woocommerce-ios/files/5725836/testflight_feedback.zip)
* JSON from event 87453d2066994164a305e37e8f822c92 in Sentry: [87453d2066994164a305e37e8f822c92.json.zip](https://github.com/woocommerce/woocommerce-ios/files/5725854/87453d2066994164a305e37e8f822c92.json.zip)

<img src="https://user-images.githubusercontent.com/1119271/102810400-e31aee80-4380-11eb-93a1-acb723e9ec95.png" width="270" alt="Screen Shot 2020-12-21 at Dec 21 11 36 58 AM"> <img src="https://user-images.githubusercontent.com/1119271/102810387-df876780-4380-11eb-8dfa-91632ee4a5ab.png" width="270" alt="Screen Shot 2020-12-21 at Dec 21 11 37 02 AM">
<sup>Tested with iPhone 6S, iOS 13.7, WooCommerce app version 5.7.0.1 (TestFlight beta)</sup>

Site & device details:

* testingallthetime.com (hosted at Bluehost)
* WordPress 5.6 
* Jetpack 8.5 (current latest avail is 9.2.1 so this is out of date)
* WooCommerce 4.8.0
* WooCommerce iOS 5.7.0.1
* iPhone 6S
* iOS 13.7

<sup>(internal references: [App Store Connect Crash Feedback](https://appstoreconnect.apple.com/apps/1389130815/testflight/crashes/AJELQjAPR5jVYqHXSDY3jcs?preReleaseVersionId=99b88a70-3764-46ed-a232-09fb9016929c&sort=-timestamp), [Sentry](https://sentry.io/organizations/a8c/issues/2101171959/events/87453d2066994164a305e37e8f822c92/))</sup>

**Comment by designsimply** [comment]
> So, do we support logging in to self-hosted sites? If we don't, should be present an error like this, but with different copy?

I think there may be some confusion around what a self-hosted site means. 

@ctarda my understanding is that the WooCommerce apps do not support self-hosted sites unless the site has Jetpack installed and connected. However, we should discuss this in a separate issue. If the self-hosted site you tested did not have Jetpack installed or connected, you should have seen a screen like this before you are prompted for a username and password:

<img src="https://user-images.githubusercontent.com/1119271/102813010-4f97ec80-4385-11eb-8e35-e2bcefa5dd88.PNG" width="270" alt="IMG_3865">
<sup>Tested using iPhone 6S iOS 13.7 WooCommerce 5.7.0.1 (TestFlight beta) on a site running WordPress 5.6 (charming-rook.jurassic.ninja) with no plugins installed.</sup>

@Garance91540 in the past, we have used "self-hosted" to refer to sites that have WordPress installed but do not have Jetpack installed. Technically, a Jetpack site could be considered self-hosted but in my experience at Automattic we've referred to self-hosted sites with Jetpack sites installed as just Jetpack sites (though this may be changing as I have noticed others referring to Jetpack sites as self-hosted sites lately 🙂).

**Comment by Garance91540** [comment]
> @Garance91540 in the past, we have used "self-hosted" to refer to sites that have WordPress installed but do not have Jetpack installed. Technically, a Jetpack site could be considered self-hosted but in my experience at Automattic we've referred to self-hosted sites with Jetpack sites installed as just Jetpack sites (though this may be changing as I have noticed others referring to Jetpack sites as self-hosted sites lately 🙂).

Thank you for explaining this @designsimply ! I've been assuming self-hosted sites meant sites that weren't hosted on WordPress.com

**Comment by rachelmcr** [comment]
I'm sorry I didn't clarify this in my original report, but this crash happens with any self-hosted site (any site not hosted on WordPress.com), including self-hosted sites with Jetpack connected (where you should be able to log in to the app).

**Comment by ctarda** [comment]
This might have been fixed by #3426

**Comment by ctarda** [comment]
To recap:
* Logging in with username and password should only be possible when users select "Login with Store Credentials"
* Login with Store Credentials has been removed for M1
* Therefore this should not happen anymore, given #3426 dos not make reaching this path possible.

**Comment by ctarda** [comment]
Closing for now.
