### ISSUE TITLE
Login Loading indicator in dark mode is hard to see

### ISSUE THREAD

**Issue by chipsnyder** [woocommerce/woocommerce-ios#3386]
**Describe the bug**
The log in loading indicator is difficult to see while in dark mode.

**To Reproduce**
Steps to reproduce the behavior: With a fresh install or logged out:

### Enter Your Store Address
1. Set your device to Dark Mode
    - Bonus: It might help to switch to a slow connection in the developer settings.
1. From the login page select "Enter Your Store Address"
1. Enter a valid Woo URL

- Notice the loading indicator in the "Continue" button is hard to see

###
1. Set your device to Dark Mode
    - Bonus: It might help to switch to a slow connection in the developer settings.
1. From the login page select "Continue With WordPress.com"
1. Enter a valid username and password

- Notice the loading indicator in the "Continue" button is hard to see

**Screenshots**
The following video was taken for the "Enter Your Store Address" when Jetpack was disconnected. 

<kbd><a href="https://user-images.githubusercontent.com/3384451/102658341-63eda680-4145-11eb-92f7-c7fba882a2d0.gif)
"><img width="300" src="https://user-images.githubusercontent.com/3384451/102658341-63eda680-4145-11eb-92f7-c7fba882a2d0.gif)
"/></a></kbd>

**Expected behavior**
Loading indicator should be styled for Dark mode. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 11
- iOS version: iOS 13.5
- WooCommerce iOS version:  5.7.0.1

**Comment by jaclync** [comment]
Likely similar to https://github.com/woocommerce/woocommerce-ios/issues/2716
