### ISSUE TITLE
Selecting Try another account after logging in with a Magic Link leads to a dead end

### ISSUE THREAD

**Issue by chipsnyder** [woocommerce/woocommerce-ios#3387]
**Describe the bug**
When logging in with a Magic Link, if the user selects "Try Another account" they will hit a dead end, forcing them to force kill the app.

**To Reproduce**
From a logged out state
1. Select "Continue With WordPress.com" from the login screen
2. Enter the email address of a WordPress.com account
3. Select "Get a login link by email"
4. Navigate to the mail app
    - I was able to reproduce this with the "Open Mail" button and by just closing the app and opening mail my self
5. Select "Log in to the app" from your email
6. Select "Try Another account"

Notice that the screen locks up on this loading page and the user needs to force close the app to move forward

**Screenshots**
<kbd><a href="https://user-images.githubusercontent.com/3384451/102662304-94850e80-414c-11eb-9d9d-8d6b3cf8896f.gif"><img width="300" src="https://user-images.githubusercontent.com/3384451/102662304-94850e80-414c-11eb-9d9d-8d6b3cf8896f.gif"/></a></kbd>

**Expected behavior**
The user should be taken back to the login screen.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 11
- iOS version: iOS 13.5
- WooCommerce iOS version: 5.7.0.1

**Comment by rachelmcr** [comment]
Thanks for the report! I'm going to close this as we have a duplicate report in https://github.com/woocommerce/woocommerce-ios/issues/3367.
