### ISSUE TITLE
[UL&S] Login epilogue screen says my site is not a WordPress site when it is a WordPress site

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#3392]
Steps to reproduce:

1. Start with a site running an older version of WordPress, such as WordPress 5.1.4.
1. Log out of the app.
1. Tap "Enter Your Store Address".
1. Enter the address of a self-hosted WordPress site that does not have Jetpack installed.
1. Enter the site address and tap Continue.

**Result:** If try to login using a site address and I have an older version of WordPress installed then the app tells me:

> The website is not a WordPress site. For us to connect to it, the site must have WordPress installed.

<img src="https://user-images.githubusercontent.com/1119271/102813708-89b5be00-4386-11eb-831d-b7247e63279a.PNG" width="270" alt="IMG_3864">
<sup>Tested with iPhone 6S, iOS 13.7, WooCommerce app version 5.7.0.1 (TestFlight beta) using the site address login flow with designsimply.com which is currently running WordPress 5.1.4 and has Jetpack 7.1.1 installed but not active—the only other active plugins are Akismet and https://wordpress.org/plugins/random-images/, WooCommerce is not installed.</sup>

### Expected behavior

I expect that if I enter a WordPress site address that does not have Jetpack or WooCommerce installed and try the site address flow I will be prompted to install Jetpack like this: 

> To use this app for charming-rook.jurassic.ninja you'll need to have the Jetpack plugin installed and connected on your store.

<img src="https://user-images.githubusercontent.com/1119271/102814152-53c50980-4387-11eb-96af-d4672e77e273.PNG" width="270" alt="IMG_3865">
<sup>Tested with iPhone 6S, iOS 13.7, WooCommerce app version 5.7.0.1 (TestFlight beta) using the site address login flow with charming-rook.jurassic.ninja which is currently running WordPress 5.5.3 and has no plugins.</sup>

**Comment by designsimply** [comment]
### Proposed copy change

Current:

> The website is not a WordPress site. For us to connect to it, the site must have WordPress installed.

Proposed: 

> We were not able to detect a WordPress site at the address you entered. Please make sure WordPress is installed and that you are running the latest available version.

Feedback welcome on the copy if you'd like to change or shorten it!

**Comment by shiki** [comment]
@Garance91540 or @adamzelinski What do you think about the message that @designsimply shared above (https://github.com/woocommerce/woocommerce-ios/issues/3392#issuecomment-749155461)?

**Comment by ghost** [comment]
I really like the new proposed copy and happy to go with that. Thanks for the suggestion @designsimply @shiki
