### ISSUE TITLE
Products: Product list doesn't load with Core 4.9 release candidate

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#3421]
**Describe the bug**

I updated WooCommerce Core on my test store to [version 4.9.0-rc.1](https://github.com/woocommerce/woocommerce/releases/tag/4.9.0-rc.1). As a result, the Products list no longer loads in the app, even when I revert to a previous version of the app. Here are the errors I'm seeing in the app logs:

```
2021/01/04 17:08:54:148  🔵 Tracked product_list_load_error, properties: [AnyHashable("error_domain"): "NSCocoaErrorDomain", AnyHashable("error_code"): "4865", AnyHashable("error_description"): "Swift.DecodingError.keyNotFound(CodingKeys(stringValue: \"stock_status\", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: \"data\", intValue: nil), _JSONKey(stringValue: \"Index 0\", intValue: 0)], debugDescription: \"No value associated with key CodingKeys(stringValue: \\\"stock_status\\\", intValue: nil) (\\\"stock_status\\\").\", underlyingError: nil))"]
2021/01/04 17:08:54:148  ⛔️ Error synchronizing products: keyNotFound(CodingKeys(stringValue: "stock_status", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"stock_status\", intValue: nil) (\"stock_status\").", underlyingError: nil))
```

**To Reproduce**
1. Install the WooCommerce Beta Tester plugin on your store.
2. Update to 4.9.0-rc.1 (the current 4.9 release candidate).
3. Open the app.
4. Open the Products tab and notice the list doesn't load.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin (and WooCommerce Beta Tester plugin) is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 12 Mini
- iOS version: 14.3
- WooCommerce iOS version: 5.7.0.2

**Comment by rachelmcr** [comment]
Just a note that I confirmed that using Woo iOS 5.7.0.2 after reverting WooCommerce Core to 4.8.0 works as expected. The error only occurs after updating to the 4.9.0 release candidate.

**Comment by ThomazFB** [comment]
Investigation suggested that this is a regression introduced by the Core 4.9.0 version caused by the sudden unavailability of the `stock_status` JSON field, I've reported the bug to the Woo Core team and opened an issue at the repository right here: https://github.com/woocommerce/woocommerce/issues/28729

**Comment by rachelmcr** [comment]
I updated to Woo Core 4.9.0-rc.2 and confirmed this issue is resolved there. 🎉
