### ISSUE TITLE
Unable to type my password after selecting "entering your site address"

### ISSUE THREAD

**Issue by eduardozulian** [woocommerce/woocommerce-ios#3458]
**Describe the bug**
After clicking on "entering your site address", we see fields for both username and password. Clicking on the password field, however, triggers the **Lost your Password?** link that slides under the password field whenever the keyboard is visible.

**To Reproduce**
1. Open the app
2. Click Log In > Continue with WordPress.com
3. Select **Or log in by entering your site address**
4. Type your WP address
5. Add your username
6. Try to add your password

**Screenshots**

https://user-images.githubusercontent.com/1136160/104376195-6bfdf380-5503-11eb-967c-f16cf7f0bdd9.MP4

**Expected behavior**
To be able to add my password and log in to the site.

Instead, the app thinks I am trying to click on the **Lost your password?** link.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
- Device: iPhone 7
- iOS version: tested with 14.2 and 14.3
- WooCommerce iOS version: 5.7

**Comment by ctarda** [comment]
Thanks for reporting this @eduardozulian 🙇

**Comment by designsimply** [comment]
Looping back to note that the login flow was updated in [v5.8](https://github.com/woocommerce/woocommerce-ios/releases/tag/5.8) and the Log In screen now prompts for an email address and a password on two separate screens. I re-tested using WCiOS 5.9.0.0 (TestFlight beta) by tapping all along the row with the Password field and I was unable to trigger the reset password link so this appears to be fixed. 🎉

<img src="https://user-images.githubusercontent.com/1119271/106790632-0e942880-6611-11eb-89a0-68477e16ed00.PNG" width="270" alt="IMG_4762"> <img src="https://user-images.githubusercontent.com/1119271/106790638-0fc55580-6611-11eb-994d-66d6416033eb.PNG" width="270" alt="IMG_4763">

@eduardozulian please comment back or add a new issue if you're still having any trouble after updating to the latest version!

**Comment by eduardozulian** [comment]
Tested with 5.8 and is working like a charm. Thank you all!

I'll mark this one as closed.
