### ISSUE TITLE
Edit product > product type: "Physical" is shown for a downloadable product

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#3477]
For a simple product, we currently show either "Physical" or "Virtual" in the product type row in product form depending on whether the `virtual` flag is on. However, a downloadable product could have its `virtual` flag off while `downloadable` flag is on like in product settings:

core | app
-- | --
<img width="450" alt="Screen Shot 2021-01-15 at 3 05 36 PM" src="https://user-images.githubusercontent.com/1945542/104692803-8aeac880-5743-11eb-95c6-7045b2299f26.png"> | <img src="https://user-images.githubusercontent.com/1945542/104692831-976f2100-5743-11eb-99c5-18b9ae307a40.png" width="300" />
<img src="https://user-images.githubusercontent.com/1945542/104692915-b66db300-5743-11eb-9aba-c64f9e0b93ad.png" width="300" />

@woocommerce/mobile-designers do you think it makes sense to show "Downloadable" when a product's `downloadable` flag is on? So that the logic is like:

- If `downloadable` is on, show "Downloadable"
- If `downloadable` is off:
  - If `virtual` is on, show "Virtual"
  - If `virtual` is off, show "Physical"

**Comment by ctarda** [comment]
This looks like something we could prioritize
