### ISSUE TITLE
Edit product > linked products: the number of products row is tappable without action

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#3479]
**Describe the bug**

In edit product > linked products, the `# product(s)` row for upsells or cross-sells products is tappable but there is no action. Maybe we can disable selection for these rows.

**To Reproduce**

- Go to the products tab
- Tap on a product whose linked products are editable
- Tap on Linked products row or from the bottom sheet
- If there are no products selected yet, tap "Add Products" to add at least one product
- After navigating back to the linked products screen, tap the "# product(s)" row --> highlighted state is shown without action

**Screenshots**

<img src="https://user-images.githubusercontent.com/1945542/104693470-adc9ac80-5744-11eb-9d3f-5228ba2a0c14.png" width="300" />

**Expected behavior**

It'd be nice if the row doesn't appear tappable (like we can set `cell.selectionStyle = .none` for these two rows).

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 6s Plus
- iOS version: iOS 14.1
- WooCommerce iOS version: 5.8.0.0

**Comment by ctarda** [comment]
Similar to #3476
