### ISSUE TITLE
[UL&S] Catch the case when users initiate a log in with a store address, then use a wp account different to the store address entered

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3482]
For context:
pbMoDN-1KW#comment-3684-p2
pbMoDN-1KW#comment-3687-p2

When logging in with store address, we are missing presenting an error when a user logs in with a wordpress.com or jetpack account that do not match the store address entered.

**Comment by shiki** [comment]
I saw that this is already in the Done column in the Unified Login board. I'll close this now but feel free to reopen if I made a mistake. 😅
