### ISSUE TITLE
Send Whatsapp message to billing phone number (in addition to existing call and message options)

### ISSUE THREAD

**Issue by wongalvis14** [woocommerce/woocommerce-ios#3499]
Please submit all enhancements to the ideas board located at http://ideas.woocommerce.com/forums/133476-woocommerce?category_id=84283.
https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/42488266-whatsapp

Currently in the order details -> billing information page, the user can click the phone number and see the call and message options. It would be great to have a Whatsapp option too, or perhaps using the default iOS popup

**Comment by shiki** [comment]
Hi. @wongalvis14! Thank you for using the Woo Mobile app! Feature requests are not currently processed in GitHub. Please go to [this link](http://ideas.woocommerce.com/forums/133476-woocommerce?category_id=84283) to either up-vote this feature on the ideas board, or to add a new feature request if it doesn't already exist.

Thank you!
