### ISSUE TITLE
StorePickerViewController is presenting a list of sites in fourth different contexts. It should be broken down

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3507]

**Comment by shiki** [comment]
Hi, @ctarda! When you get the time, would you mind giving more information about this? Or if this was born of a discussion in a PR, would you mind linking to it? 🙂 TIA!

**Comment by ctarda** [comment]
Right, I should have explored this further, sorry. I do not have the bandwidth to chase this now properly, so I will close for now.
