### ISSUE TITLE
[UL&S] "Enter your store address" button looks weird in some languages

### ISSUE THREAD

**Issue by loremattei** [woocommerce/woocommerce-ios#3508]
**Describe the bug**
In some languages, the text in the "Enter your store address" button needs two lines. In this case, the button doesn't look very nice.

**To Reproduce**
1. Switch your device to Italian. 
2. Navigate to the Login screen.

**Screenshots**
![IMG_2721](https://user-images.githubusercontent.com/4836764/105513208-52fafc80-5cd2-11eb-9203-df343a365dfe.PNG)

**Mobile environment**
WooCommerce iOS version: 5.8.0.3

**Comment by joshheald** [comment]
Prioritization:
Severity – medium: visual issue in login (first impressions)
Impact – medium: hard to know for sure, because it's language and device dependent, but potentially more than 6% since everyone sees login.
= medium

**Comment by bozidarsevo** [comment]
Do we use this screen anymore? I am having trouble getting to it in the app.

**Comment by joshheald** [comment]
@bozidarsevo I don't think we do, and I can't find it either... but @itsmeichigo would be the person I'd ask for confirmation.

**Comment by itsmeichigo** [comment]
We changed the design and wording for the buttons on the prologue screen to Log In and Create a New Store. I'll go ahead and close this issue then.
