### ISSUE TITLE
Variations: Add Attribute screen updates

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#3526]
<img width="420" alt="Screen Shot 2021-01-26 at 12 06 28 PM" src="https://user-images.githubusercontent.com/562080/105879144-d1f07d80-5fcf-11eb-900c-f8b63bb2b4d6.png">

Tasks:
- [x] Update "Attribute Name" placeholder copy
> New Attribute Name

- [x] Update "To create a variation" placeholder copy
> To create a variation, you’ll need to set its attributes (ie “Color”, “Size”) first

- [ ] ~Update "Existing attribute" section title copy~
> ~OR TYPE TO SELECT EXISTING ATTRIBUTE~

- [x] Disable "Next" Button while the attribute text field is empty. Consider navigating to next screen when tapping `return`

**Comment by rachelmcr** [comment]
> OR TYPE TO SELECT EXISTING ATTRIBUTE

I just want to double check this string change. Do we really want to prompt people to type out existing attributes, rather than tap to select them?

**Comment by Ecarrion** [comment]
I think it should be "TAP", right @Garance91540

**Comment by Garance91540** [comment]
haha yes, that's a TYPO... it should be TAP

**Comment by rachelmcr** [comment]
Heh, that makes more sense, thanks! :)
