### ISSUE TITLE
Move shared foundation utilities to a separate framework

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#3547]
Original discussion: https://github.com/woocommerce/woocommerce-ios/pull/3532#discussion_r565266624

## Goal

There are a few helpers currently in the Storage layer that can also be very useful in the app layer, but we don't want to import `Storage` from the [design doc](https://github.com/woocommerce/woocommerce-ios/blob/develop/docs/architecture-overview.md):

> WooCommerce:  Our main target, which is expected to **only** interact with the entire stack thru the Yosemite.framework.

In order to share the utilities without `Storage` dependency, let's move them to a separate framework so that any layer can use them.

## Files to move

I've identified the following files, feel free to edit the description to add more or share in a comment!

- `TypedPredicates.swift`: for declaring a typed `NSPredicate`
- `Collection+Extensions.swift`: for accessing a collection element at an index safely
- ❓Optional: `CrashLogger.swift`: `CrashLogger` protocol for logging a crash at any layer/framework with a severity level

**Comment by iamgabrielma** [comment]
Closing this one as the 3 items from the initial issue have been moved to WooFoundation in #7337, #7338, and #7346 👍
