### ISSUE TITLE
[UL&S] Fix typo in enter Store Address screen

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3551]
1. Tap Login With Store Address
2. Where it says "Enter the address of *your* WooCommerce store you'd like to connect.", it should say "Enter the address of *the* WooCommerce store you'd like to connect".

**Comment by CrazyBusyCreative** [comment]
I can grab this

**Comment by ctarda** [comment]
Thanks @CrazyBusyCreative !
