### ISSUE TITLE
Handle a fourth state during initial store WCPay interrogation: No readers ordered yet

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#3556]
Building on https://github.com/woocommerce/woocommerce-ios/issues/3555 it would be ideal to handle a fourth state - where a store has the WCPay plugin active, an account setup, but the merchant has not yet ordered any readers.

In this case, we should NOT show any reader hardware settings to the merchant, but instead prompt the merchant how to obtain their first reader

**Comment by ctarda** [comment]
We are going to close this for now.
