### ISSUE TITLE
[UL&S] Remove "Pick store to connect" from store address login flow

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#3571]
When someone logs in with the “enter your store address” flow, they should be taken directly to the My Store section and should not see the "Pick a store to connect" screen. Can we remove it?

Screenshot of the "Select Store" screen showing the "Pick store to connect" option during login:

|<img src="https://user-images.githubusercontent.com/1119271/106667699-7e99a480-6566-11eb-9de1-11553133a943.PNG" width="300" alt="IMG_3937" align="left">|
|---|
|<sup>Tested with WCiOS 5.9.0.0 TestFlight beta, iPhone 6S, iOS 13.7. Note: ignore the user icon, it's a PNG with a black image on a transparent background. :)</sup>|

<sup>(internal reference: p5T066-1K4-p2#comment-6955 ht @Garance91540)</sup>

**Comment by anitaa1990** [comment]
On Android:

- We store the site address that is entered, in SharedPreferences.
- After successful login, in the Site Picker screen, if the site address is available locally, just redirect to the My Store tab.
- Delete the site address from the local storage.

I'm thinking we can follow a similar logic in iOS too but if there is a better way I'm definitely all ears 😊
