### ISSUE TITLE
Shipping Labels: fix icon alignment and update font size for the notes on the "Reprint Shipping Label" screen

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#3573]
<blockquote>On the “Reprint Shipping Label” screen:
<br>– can we vertically align the icons with the links “See layout…” and “Don’t know…” ?
<br>– can we update the font size of these 2 links to “Subhead”?</blockquote>
<sup>(internal reference: p5T066-1K4-p2#comment-6955 ht @Garance91540)</sup>

<br><img width="320" alt="Screen Shot 2021-02-01 at 14 54 33" src="https://user-images.githubusercontent.com/1119271/106659509-134ad500-655c-11eb-8d95-f2cb70d4018a.png">
<sup>Tested with WCiOS 5.9.0.0.</sup>

**Comment by itsmeichigo** [comment]
I think this issue has been solved but couldn't find the PR 😅 This is the current state of the screen:

<img src="https://user-images.githubusercontent.com/5533851/148155137-b31ccea8-5dfa-4b64-a72a-092a02352799.png" width=320 />

I'll close this issue then.
