### ISSUE TITLE
Shipping Labels: Consider removing the bottom divider just above the "Reprint Shipping Label" button on the Order Details screen

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#3575]
<blockquote>On the Order Details screen, can we remove the bottom divider of the last product?</blockquote>
<sup>(internal reference: p5T066-1K4-p2#comment-6955 ht @Garance91540)</sup>

<br><img width="420" alt="Screen Shot 2021-02-01 at 15 03 39" src="https://user-images.githubusercontent.com/1119271/106661043-fb745080-655d-11eb-9f21-180542f33f8f.png">
<sup>Tested with WCiOS 5.9.0.0.</sup>

**Comment by designsimply** [comment]
@Garance91540 should the bottom divider in the products list for an order _only_ be removed if the "Reprint Shipping Label" is present?

**Comment by Garance91540** [comment]
If there;s a CTA under the last product (ie "Mark order as complete", "Create shipping labels", "Reprint label"...) we should always remove the bottom divider

**Comment by jaclync** [comment]
This issue looks similar to https://github.com/woocommerce/woocommerce-ios/issues/3437

**Comment by jaclync** [comment]
This issue looks similar to https://github.com/woocommerce/woocommerce-ios/issues/3437

**Comment by designsimply** [comment]
Aha! @jaclync thanks for catching that! 

Closing as a duplicate of https://github.com/woocommerce/woocommerce-ios/issues/3437. 👍
