### ISSUE TITLE
Push Notifications: review missing from list if push notification received while app is backgrounded

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#3584]
Steps to reproduce:

1. Go to Reviews.
1. Force close the app.
1. Leave a product review to receive a push notification.
1. Tap the push notification and expect the review detail to appear.
1. Tap the back arrow at top left. 
1. Check to see if the new review appears at the top of the review list.
1. Repeat the steps except background the app instead of terminating it in step 2.

**Result:** if the app is backgrounded, tapping a review push notification then the review does not appear in the review list until pull-to-refresh. ([1m14s](https://cloudup.com/cdKv-1Zj_MI)) The same problem does not happen if the app is closed when the push notification is received.

<img src="https://user-images.githubusercontent.com/1119271/106827751-3d78c180-6646-11eb-8c79-2fecc72963dd.gif" width="270" alt="review-missing-from-list-if-push-notification-received-while-app-backgrounded">
<sup>Tested with WCiOS 5.9.0.0 TestFlight beta, iPhone 11, iOS 14.4.</sup>

**Comment by joshheald** [comment]
This is not reproducible any more.

The review details is presented in a nav control with the back button taking the user to the Hub menu. It seems like this should go back to the Reviews list as previously...?
