### ISSUE TITLE
Variations: Review edit variation attribute options accessibility

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#3600]
Make sure the flow works well with:
- [x] Dark Mode
- [x] Big Fonts
- [x] Landscape 
- [x] Voice Over
- [x] Localization

**Comment by rachelmcr** [comment]
Big fonts:

- [x] Long attribute options can be cut off, especially with larger font sizes:

<img src="https://user-images.githubusercontent.com/8658164/107245745-67a3f800-6a27-11eb-97a2-36e2ee43f6a3.png" width="300px">

This may be acceptable if we don't expect attribute options to have long names.

**Comment by rachelmcr** [comment]
Landscape:

- [x] Margins are inconsistent on devices with notches. Some screens have edge-to-edge table cell backgrounds, while other screens have a left/right margin. (All screens respect safe areas)

![Simulator Screen Shot - iPhone 12 mini - 2021-02-08 at 13 05 27](https://user-images.githubusercontent.com/8658164/107246951-b1d9a900-6a28-11eb-8bc2-656c387b4091.png)
![Simulator Screen Shot - iPhone 12 mini - 2021-02-08 at 13 05 31](https://user-images.githubusercontent.com/8658164/107246957-b30ad600-6a28-11eb-900e-b0fe85dd2568.png)
