### ISSUE TITLE
Pull down to refresh on Order Status leaves no status selected

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#3608]
**Describe the bug**

Pulling down to refresh the Order Status list leaves no status selected and apply button unexpectedly active

**To Reproduce**
1. Go to an order
2. Tap on the edit (pencil) to the right of the order status
3. Note the current order status is pre checked for you and the Apply button disabled
4. Tap on a different staus
5. Note the Apply button enables
6. Pull down to refresh
7. Note now that no status is selected and the Apply button is still enabled

**Screenshots**

<img src="https://user-images.githubusercontent.com/1595739/107076391-39f94d80-67a0-11eb-9131-7bd99e4fdd9b.gif" width="50%"/>

**Expected behavior**

I would have expected an order status to be selected after the refresh, probably the current order status, and the apply button to be disabled

**Isolating the problem (mark completed items with an [x]):**

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**

- Device: iPad
- iOS version: 14.3
- WooCommerce iOS version: 5.8

**WordPress Environment**

WP 5.6.1
WC 4.9.2
Jetpack 9.4

**Comment by allendav** [comment]
Hey @pmusolino I just noticed https://github.com/woocommerce/woocommerce-ios/commit/2bdae450f42cc3ee0bef4c2b89b112f91294e5cf - what that the only expected behavior from pull to refresh? i.e. to basically revert to the order status (and not to fetch statuses)?

(See also #3609 - I'm guessing now that fetching newly added custom statuses wasn't the intention)

I'm proposing removing pull-to-refresh in the refactor in #3530 but I could restore it there or in a subsequent PR.

**Comment by pmusolino** [comment]
Hey @allendav. This was a fix introduced in this PR https://github.com/woocommerce/woocommerce-ios/pull/3493 But I also think that there is no reason here to have a pull-to-refresh. Probably it's useful just in the case there was an error fetching the initial order status?

**Comment by allendav** [comment]
@Garance91540 @pmusolino - what I'd like to do is move forward with pr #3530 (which has no refresh now) and then implement this issue and #3609 together so that a refresh re-fetches the order statuses list (and any newly added statuses) as well as re-fetches the current order status. Sound good?

**Comment by joshheald** [comment]
It's no longer possible to pull-to-refresh on this screen.
