### ISSUE TITLE
Pull down to refresh on Order Status does not fetch newly added custom order statuses

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#3609]
**Describe the bug**

It isn't clear what the pull down to refresh on order status is supposed to do. As noted in #3608 it results in no status being selected, and further, if you use a plugin like https://wordpress.org/plugins/ni-woocommerce-custom-order-status/ to add a custom order status while the order status list view is active, the new order status does not appear in the list. (You have to exit out to the order list view, pull down to refresh there, and then return to the order status list to see newly added custom statuses.)

**To Reproduce**

1. Go to an order
2. Tap on the edit (pencil) to the right of the order status
3. Note the current order status is pre checked for you and the Apply button disabled
4. In wp-admin, install the https://wordpress.org/plugins/ni-woocommerce-custom-order-status/ plugin and add a new order status
5. Back in the app, pull down to refresh
6. Note that the newly added order status does not appear
7. Cancel the Order Status view to return to the Order # view
8. Pull down to refresh
9. Tap on the edit (pencil) to the right of the order status
10. Note that the newly added order status still does not appear
11. Cancel the Order Status view to return to the Order # view
12. Exit the Order # view to return to the order list view
13. Pull down to refresh
14. Tap on the order again
15. Tap on the edit (pencil) to the right of the order status
16. Note that the newly added order status now does appear

**Screenshots**

**Expected behavior**

I kinda expected the newly added order status option to appear when I refreshed the order status list

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

Mobile Environment

Device: iPad
iOS version: 14.3
WooCommerce iOS version: 5.8

WordPress Environment

WP 5.6.1
WC 4.9.2
Jetpack 9.4

**Comment by allendav** [comment]
@Garance91540 @adamzelinski - what is the expected behavior of the status list refresh for an order?

Between this issue and #3608 it (refresh) doesn't really do anything at this point:

<img src="https://user-images.githubusercontent.com/1595739/107076391-39f94d80-67a0-11eb-9131-7bd99e4fdd9b.gif" width="50%"/>

So... since order status list refresh is wholly broken, I think I'll remove it as part of the work I am doing in #3447 and we can fix it properly between this issue and #3608 - what do you think @ctarda ? @Ecarrion ?

**Comment by Ecarrion** [comment]
Makes sense to me! I'm always up for splitting tasks in smaller bits :-)

**Comment by Garance91540** [comment]
> @Garance91540 @adamzelinski - what is the expected behavior of the status list refresh for an order?

Mmm great question. The only user case I could think of would be if merchants add a custom status in their site-admin while having the order status for an order screen open, refreshing it to see the newly added order status.

**Comment by designsimply** [comment]
Someone asked about this on the 5.8 community beta testing post (nice!) and said:

> When I am closing Order on the web it is not being refreshed automatically in the mobile app.
> Am I doing something wrong?

<sup>Source: https://woocommercehalo.wordpress.com/2021/01/19/call-for-testing-woocommerce-for-ios-5-8/#comment-891</sup>

Would it be possible to make an order status changed on the web update in the app automatically regardless of what screen they are on?

**Comment by allendav** [comment]
Hey @designsimply - yup - as the user notes, it depends what screen users navigate to (and/or pull down on) as to whether order statuses (among other things) are refreshed. I'll open a new issue to track this, but it is a non trivial amount of work and may also require changes in Jetpack or WooCommerce (not to mention plugins and extensions) for mobile clients to be able to get "all the things that changed since I last talked to you" from the merchant's WooCommerce site.

https://github.com/woocommerce/woocommerce-ios/issues/3635

**Comment by joshheald** [comment]
It's not possible to pull-to-refresh on this screen any more
