### ISSUE TITLE
Variations: non-blocking navigation on attribute creation process

### ISSUE THREAD

**Issue by ealeksandrov** [woocommerce/woocommerce-ios#3629]
Consider the scenario where, while creating an attribute, the user can tap the back button as the screen is not blocked.
App works well and nothing really breaks.

https://user-images.githubusercontent.com/3132438/107529519-00737880-6bcc-11eb-96dc-84ce588298e7.mp4

Should we cancel the network operation? Or forward navigation? Or maybe this is too far of edge case?

**Comment by Ecarrion** [comment]
What do you think @Garance91540 @adamzelinski?

One option I can think of is to show the same loading screen that covers the whole screen, like when we are updating a product.

**Comment by Garance91540** [comment]
> One option I can think of is to show the same loading screen that covers the whole screen, like when we are updating a product.

Yes maybe that's best, so it's consistent with our other loading states and we don't introduce a whole new interaction

**Comment by Ecarrion** [comment]
@Garance91540 any specific wording?

@ealeksandrov Would you mind creating a separate issue(and close this one) with the screens, texts, and whatever else is needed for someone to work on this?

**Comment by Garance91540** [comment]
Designs here:
https://d.pr/i/XUpJVv

**Comment by Ecarrion** [comment]
@Garance91540 while playing the app I noticed that the tags screen works in the same way and I think people have not found this to be a problem.

https://user-images.githubusercontent.com/562080/107774407-f311d780-6d0c-11eb-9af4-164fd3301d89.MP4

Should we still proceed with the change?

**Comment by Garance91540** [comment]
Hi @Ecarrion, I tested the tag flow before and it didn't confuse me to be able to go back while my changes were being saved. It's probably also less of a friction since we are not disrupting the user flow with a full screen loading screen. So...let's keep things as such 😂 (loader in the top nav)

**Comment by Ecarrion** [comment]
Thanks, @Garance91540 for your time!
@ealeksandrov let's close this for the time being. We'll re-assess if merchants start complaining!
