### ISSUE TITLE
Use something like Jetpack activity log to optimize and automate syncing store data to app

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#3635]
This enhancement may require related work in Jetpack and WooCommerce core.

If the mobile apps could periodically query WPCOM/Jetpack to get a list of changes to orders (e.g. status), products, customers, etc - possibly using Jetpack's Activity Log feature?, it could greatly reduce the amount of data fetched to update our local cache of such objects and could support more automatic synchronization of such objects - e.g. see this related request for automatic syncing of order status: https://github.com/woocommerce/woocommerce-ios/issues/3609#issuecomment-776909257

**Comment by shiki** [comment]
I'm moving this to the Product Backlog. As mentioned in https://github.com/woocommerce/woocommerce-ios/issues/3609#issuecomment-777090797, this is non-trivial work. So it's probably best to prioritize this against the other big-ticket items that we have in the Product Backlog. 

Let me know if I misunderstood this though!
