### ISSUE TITLE
Variations: Add "discard changes" alert in AttributePickerViewController

### ISSUE THREAD

**Issue by ealeksandrov** [woocommerce/woocommerce-ios#3638]
Based on discussion in p1612977972011800-slack-CGPNUU63E and p91TBi-4rc-p2#comment-3318 we need to add a check for unsaved changes and show "Discard changes" alert.

Example:

https://github.com/woocommerce/woocommerce-ios/blob/4b748523cf63dc2b296eb5f4e647cea9b6cd62b7/WooCommerce/Classes/ViewRelated/Products/Edit%20Product/Linked%20Products/LinkedProductsViewController.swift#L197-L222

**Comment by ealeksandrov** [comment]
Discussion in Slack ended with decision to remove dedicated "done" actions on child views:

> Only show “Done” in the primary product detail screen. Changes made in the child screens would automatically be saved to the local product draft. Clicking “Done” in product detail would push the changes, and tapping back would show the discard dialog

**Comment by Ecarrion** [comment]
Closing in favor of https://github.com/woocommerce/woocommerce-ios/issues/3652

**Comment by rachelmcr** [comment]
This came up in beta testing the 6.1 release; reopening so we can have the "discard changes" prompt for now (until #3652 is addressed).
