### ISSUE TITLE
Settings: the letters in the Woo logo on the About page should be white

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#3666]
Steps to reproduce:

1. On the device, switch to dark mode.
1. In the app, go to My Store > Settings > About the App > WooCommerce.
1. Examine the logo.

**Result:** the letters in the Woo logo should be white but they appear black when in dark mode.

<img src="https://user-images.githubusercontent.com/1119271/108013371-c7bb1100-6fc8-11eb-8eb3-e524459b2a24.png" width="270" alt="img_4358">
<sup>WCiOS 6.0.0.1</sup>

<sup>(internal reference: p5T066-1NH-p2#comment-7174 /hat tip @adamzelinski for the report.</sup>

**Comment by iamgabrielma** [comment]
We replaced this screen with the [unified Automattic](https://github.com/woocommerce/woocommerce-ios/pull/6421) one and is no longer an issue:

<img width=350 src="https://user-images.githubusercontent.com/3812076/186877844-3fb08919-ad48-43c4-8e0b-93fe456ed5b1.png">


Closing!
