### ISSUE TITLE
Orders with `scheduled-payment` Order Status always appear in `Today` Orders View

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-ios#367]
### Expected behavior

Orders with `scheduled-payment` Order Status should not appear in `Today` Orders View. 

### Actual behavior

Orders with `scheduled-payment` Order Status always appear in `Today` Orders View:

![](https://cloudup.com/c2n7LRiVr4T+)
Image Link: https://cloudup.com/c2n7LRiVr4T

Here is Order #1178 page:

![](https://cloudup.com/cE0llFOBUZn+)
Image Link: https://cloudup.com/cE0llFOBUZn

Here is Order #1179 page:

![](https://cloudup.com/cgJkg1Ks3PG+)
Image Link: https://cloudup.com/cgJkg1Ks3PG

### Steps to reproduce the behavior

1) Download [WooCommerce Deposits](https://woocommerce.com/products/woocommerce-deposits/) extension.

2) Create a **Payment Plan** as follows:

![](https://cloudup.com/cGwAhEGkNmc+)
Image Link: https://cloudup.com/cGwAhEGkNmc

3) Create a product and assign the Payment Plan to it in **Deposits** section:

![](https://cloudup.com/c4vPhcfuP0M+)
Image Link: https://cloudup.com/c4vPhcfuP0M

4) Place an order for that product on the site. Select `Deposit` and `Payment Plan` upon placing item to the cart:

![](https://cloudup.com/c3k0-RPN0cG+)
Image Link: https://cloudup.com/c3k0-RPN0cG

5) Once the order is placed, you should have the initial order for the item for which you paid the deposit + 3 orders that are visible in the **Payment Plan** section. The 3 orders should have a status `scheduled-payment`. In my case, it looks like this:

**Payment Plan (has 2 orders but your view will have 3):**

![](https://cloudup.com/c6AP50jkphZ+)
Image Link: https://cloudup.com/c6AP50jkphZ

**Order 1176 (Deposit Payment - Payment 1) - placed on June 22, 2018:**

![](https://cloudup.com/cboR3744oLY+)
Image Link: https://cloudup.com/cboR3744oLY

**Order 1177 (Payment 2) - placed on August 22, 2018:**

![](https://cloudup.com/cVB7-zlGuAt+)
Image Link: https://cloudup.com/cVB7-zlGuAt

**Order 1178 (Payment 3) - payment scheduled for October 22, 2018:**

![](https://cloudup.com/c_OuC7IXX0A+)
Image Link: https://cloudup.com/c_OuC7IXX0A

**Order 1179 (Payment 4) - payment scheduled for December 22, 2018:**

![](https://cloudup.com/cQ28K8FSX-m+)
Image Link: https://cloudup.com/cQ28K8FSX-m

6) Open the app and you will see that orders that are a part of the Payment Plan and have `scheduled-payment` Order Status appear in `Today` Orders View when they have future date as an Order Date. 

![](https://cloudup.com/c2n7LRiVr4T+)
Image Link: https://cloudup.com/c2n7LRiVr4T

These orders will be appearing every day in `Today` Orders View section. I tested it for several days and they keep moving. 

Ideally, I think we should hide them until they are "placed" (go through as per Payment Plan) and will be actually relevant for `Today` view. 

### Tested in WooCommerce Android App?

Yes. Same issue is present there. 

##### Tested on [device], iOS [version], WCiOS [version]

- iPhone 6S
- iOS v 12.0.1
- WCiOS v 0.8(20181002)

**Comment by mindgraffiti** [comment]
Related https://github.com/woocommerce/woocommerce-android/issues/425
