### ISSUE TITLE
[Mobile Payments] Storage: persist CardReaders

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3739]
After the card reader discovery process is completed, persist card readers to the Storage layer.

First, we need to validate that this is actually possible. [The documentation](https://stripe.dev/stripe-terminal-ios/docs/Protocols/SCPDiscoveryDelegate.html#/c:objc(pl)SCPDiscoveryDelegate(im)terminal:didUpdateDiscoveredReaders:) says that:

> You should not cache the SCPReader objects in the readers array. In other words, after calling connectReader: with a discovered reader, you should not attempt to cache and re-use the Reader object. 

Which indicates that persisting discovered readers, although possible, might be moot, given that readers should not be cached after we have connected to one reader.

However, even if we do not persist readers with the intention of reconnecting to a "trusted card reader" (a reader that we have connected previously to), it seems like we need to temporarily cache the discovered readers until we connect to one. 🤷

**Comment by koke** [comment]
I'm not sure we need to do this. We just have to keep a reference to the reader for a little bit, which can live in memory. We already have a `CardReader` model that we pass to the UI to display the available readers, I think we could store a reference to the original model in an internal property, and extract that when connecting.

**Comment by ctarda** [comment]
Good point. When we wrote this ticket, reconnecting automatically to "known readers"  was part of the scope. 

Known readers are readers that the device has connected to previously. This is something we will probably come back to later (I am not saying this ticket is still valid though, just that we will need to reconsider the feature later).

The reason why we would want to reconnect to a card reader is because readers turn off after a certain period of inactivity (5 minutes if I recall correctly). 

So I guess we went with the widest possible stroke here: persist the full object. It does not have to be that way though 😊

**Comment by koke** [comment]
Oh, that makes sense, I understood the issue as persisting all the discovered readers, regardless of connection. I think in that case it would be enough to persist just the serial numbers.
