### ISSUE TITLE
[Mobile Payments] Connect Your Card Reader View: Hide Footer Bar, Tweak Styles

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#3745]
Feedback on https://github.com/woocommerce/woocommerce-ios/pull/3699 https://github.com/woocommerce/woocommerce-ios/pull/3699#issuecomment-785791371

- [x] Change screen title to “Manage Card Reader”
- [x] Use Headline font for “Connect your card reader”
- [ ] Image too big - should be 206 x 180px
- [x] Title case on Button (should be “Connect Card Reader”)
- [x] Pink Learn more link
- [x] Hide Bottom Nav (Tab) Bar

**Comment by allendav** [comment]
@ctarda @Garance91540 - I've ticked off the things that have been accomplished. All that remains is tweaking the image size (it comes in at about 310x263 (x2) on my iPhone 12 and the bottom nav is not (yet) suppressed:

<img width="533" alt="Screen Shot 2021-07-19 at 11 41 18 AM" src="https://user-images.githubusercontent.com/1595739/126210695-7f9d35c0-5ff9-4d89-9076-92a4211e6f40.png">

**Comment by Garance91540** [comment]
Looking great @allendav , thank you for working on this!

**Comment by allendav** [comment]
Thank you! You are most welcome! :)
