### ISSUE TITLE
[Settings] Re-organize sections and rows

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#3746]
Light mode:

<img src="https://user-images.githubusercontent.com/1595739/109196718-ebacee00-7750-11eb-867d-54da2e9ee463.png" width=40%/>

Dark mode:

<img src="https://user-images.githubusercontent.com/1595739/109196756-f798b000-7750-11eb-9336-9bea68269d6c.png" width=40%/>

Related Android issue: https://github.com/woocommerce/woocommerce-android/issues/3628

cc @Garance91540

**Comment by Garance91540** [comment]
Looking awesome!!
