### ISSUE TITLE
[Mobile Payments] Change table row view outlets to private

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#3771]
and pass values via a `configure` method

Affected classes
- ConnectedReaderTableViewCell
- ImageTableViewCell
- LearnMoreTableViewCell
- NumberedListItemTableViewCell
- TitleTableViewCell

Props @ctarda  https://github.com/woocommerce/woocommerce-ios/pull/3761#discussion_r585587025

**Comment by ctarda** [comment]
I'm doing a bit of cleanup, is this still necessary @allendav ?

**Comment by allendav** [comment]
Yup https://github.com/woocommerce/woocommerce-ios/blob/57f335167cbec942b7cf98d6c6b0b8b2188d6875/WooCommerce/Classes/ViewRelated/ReusableViews/NumberedListItemTableViewCell.swift#L5
