### ISSUE TITLE
Push Notifications are not working for replies to support tickets

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#3776]
Steps to reproduce:

1. Go to My Store > Settings > Help & Support > Contact Support.
1. Create and send a message.
1. Wait for a reply.
1. Check to see if a push notification is received after a reply is sent.

**Result:** no push notifications are received for any replies to support requests.

<sup>Tested using WCiOS 6.1.0.1 TestFlight beta with iPhone 6S iOS 13.7 and iPhone 11 iOS 14.4 with a Jetpack site selected comparative-moth.jurassic.ninja (WP 5.7-RC1 JP 9.4 WC 5.1.0-rc.1) and again with an Atomic site selected madefortesting011121.wpcomstaging.com. Also tried from iPhone 6S iOS 13.7 while logged in as design5279. Also see internal reference: p5T066-1XH-p2#comment-7449.</sup>

**Comment by astralbodies** [comment]
This is a known issue, we ended up not building support for Zendesk push in iOS. So not a bug but definitely not something to lose track of.

**Comment by designsimply** [comment]
Gotcha. In that case, I switched this to an enhancement and ditched the high priority label. 👍

**Comment by Ecarrion** [comment]
This is no longer relevant as we migrate all support replies to happen over email.

**Comment by astralbodies** [comment]
👋 😄
