### ISSUE TITLE
Scoping and estimation for Product Add-ons iOS

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#3815]
Parent: 108-gh-woocommerce/woomobile-private
Ref: p91TBi-4gV-p2

## Goal

- Break things down
- Estimate
- Can we constrain it to up to 3 sprints? If not, what can we achieve within 3 sprints?

## Participants

- Lead: @Ecarrion 
- Product: @astralbodies (He said he can help break it down into stories)
- Design: @adamzelinski ?
- Team: @rachelmcr

**Comment by Ecarrion** [comment]
I'll close this now to be re-opened when/if the API gets improved!
