### ISSUE TITLE
Shipment Tracking Error Messages Are Hidden Behind the Keyboard

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#3818]
**Describe the bug**

When the app fails to add shipment tracking information, the error message is hidden **behind** the keyboard. So it's not visible at all. For the merchant, the app looks like it just silently failed. 

**To Reproduce**

1. The site must have the Shipment Tracking plugin. 
2. Navigate to an order → Add Tracking. 
3. Choose a carrier. 
4. Go offline. 
5. Tap on Add. 

https://user-images.githubusercontent.com/198826/110873398-e68e8980-828e-11eb-8408-194f52b3c6bf.mp4

**Expected behavior**

The error message should be shown above the keyboard.

**Comment by pmusolino** [comment]
This is no more an issue. Tested on WCiOS 8.8.0.0 (with Xcode 13.2.1) on iOS 15.2

<img src="https://user-images.githubusercontent.com/495617/159479298-6871e16f-dec1-4180-aa74-464135b1b027.png" width=300 />
