### ISSUE TITLE
Replaces "Mocks" For "Fakes"

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#3823]
Ref: #3813 

We have a lot of "Mock" classes for our networking models that are not ideal for tests.
We should replace them and use the `GeneratedFakeable` and `GeneratedCopiable` protocols instead.

Tasks:
- [ ] Unite both protocols into a single one for convenience
- [ ] Delete all Mocks and replace them for `Type.fake().copy(...)`

Mocks:
**In WooCommerce**
- [ ] MockReviews
- [ ] MockProductVariation
- [ ] MockOrders
- [ ] MockOrderItem
- [ ] MockRefunds
- [ ] MockShippingLabel
- [ ] MockShippingLabelAddress
- [ ] MockAggregateOrderItem

**In Yosemite**
- [ ] MockNote
- [ ] MockProductReview
- [ ] MockProductVariation
- [ ] MockShippingLabel
- [ ] MockShippingLabelAddress

**Comment by jaclync** [comment]
Hey @Ecarrion, nice work on the Fakes! Do you think we can include classes/structs from Yosemite as well? I was hoping to replace a new mock class for `ProductReviewFromNoteParcel` in [this PR](https://github.com/woocommerce/woocommerce-ios/pull/5044#discussion_r715167994), but the fakes are only created for Networking classes so far. Maybe we were starting with Networking first?

**Comment by Ecarrion** [comment]
@jaclync sure, [here is the PR](https://github.com/woocommerce/woocommerce-ios/pull/5056) to add `Yosemite` support.

**Comment by Ecarrion** [comment]
Closing this as we are not actively following it
