### ISSUE TITLE
Refunds: consider hiding the option to refund if there is nothing to refund

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#3845]
Steps to reproduce:

1. Create an order where the price of the product(s) is equal to zero.<br><sup>Note: one way to do this would be to add a sale price of zero for a product.</sup>
1. Open the order in the app.
1. Attempt to issue a refund for the order. 

**Result:** it's possible to submit a refund for a $0 order. 

Issue Refund button|Refund selection|Refund details|Refund confirm|Refund successful
---|---|---|---|---
![IMG_4075](https://user-images.githubusercontent.com/1119271/111551656-5052db80-8746-11eb-8398-17f86e15882e.PNG)|![IMG_4077](https://user-images.githubusercontent.com/1119271/111551657-5052db80-8746-11eb-9a35-9d571c12f240.PNG)|![IMG_4078](https://user-images.githubusercontent.com/1119271/111551659-50eb7200-8746-11eb-8326-1cf3a0dcf5ff.PNG)|![IMG_4080](https://user-images.githubusercontent.com/1119271/111551654-4e891800-8746-11eb-94bd-4c72765f0910.PNG)|![IMG_4082](https://user-images.githubusercontent.com/1119271/111551661-51840880-8746-11eb-8df7-c9de2bb9821a.PNG)

<sup>Tested with WCiOS 6.2.0.0 TestFlight beta on iPhone 6S iOS 13.7.</sup>

In comparison, the refund option is not available in the Android app for the same order where there is nothing to refund:

<img src="https://user-images.githubusercontent.com/1119271/111551727-75474e80-8746-11eb-9b36-b6b582554f0d.png" width="270" alt="Screenshot_20210317-171502">
<sup>Tested with WCAndroid 6.2-rc-1 on Pixel 3 Android 11.</sup>

<sup>(internal reference: p5T066-21o-p2#comment-7522 /hat tip @pmusolino)</sup>

**Comment by iamgabrielma** [comment]
Related to this issue, with [this new change](https://github.com/woocommerce/woocommerce-ios/pull/4683) in 7.3 refunds from negative-priced products will appear as an option as well, however these are not possible to process as - at the moment - the API doesn't allow refunds `<0` . @allendav posted here as well [an example of this flow](https://github.com/woocommerce/woocommerce-ios/pull/4683#issuecomment-894512820) were when we try this, an error is returned.

We can hide the refund option for both cases, when the refund is `=< 0`. I've assigned myself to this one and work on it shortly 👍
