### ISSUE TITLE
[Mobile Payments] Pass card holder zip code

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3863]
For context: pbUcTB-dh-p2

Logging this now so that we don't forget to check if we need to do this, and how we need to do this (I assume in the payment intent metadata)

See also #4297

**Comment by allendav** [comment]
We do need to pass this during payment intent creation, for US merchants only.

In a `level3` key (same depth as `metadata`, `amount`, etc.) it should be passed as `shipping_address_zip`

The store zip should also be passed in the level3 key as `shipping_from_zip`

**Comment by ctarda** [comment]
@allendav  do we need to move this to the beta 1 column, or to "Post Beta 1"?

**Comment by allendav** [comment]
Post Beta 1. This and the referenced issues can wait until then.

**Comment by allendav** [comment]
Verified working here: https://github.com/woocommerce/woocommerce-ios/issues/4297#issuecomment-896198726
