### ISSUE TITLE
[Mobile Payments] Add localized description to Hardware errors

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3868]
While implementing the first iteration of error handling, we [discussed](https://github.com/woocommerce/woocommerce-ios/pull/3856#discussion_r600912013) the optimal way to present errors in the UI.

We valued having granular errors, but at the same time, we valued having those errors contain as much information as possible. 

So in this iteration we will add to the UnderlyingErrors a readable description.

**Comment by allendav** [comment]
Closed by #4018
