### ISSUE TITLE
New Product: is possible to open the reviews when the user is creating a new product

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#3869]
While a user is creating a new product, the **Reviews cell** is showing, and it's also possible to select it, opening an empty screen.

**Version tested**: WC iOS 6.2
**Simulator**: iPhone 12 Pro - iOS 14.2

| New Product            | Reviews detail screen |
:-------------------------:|:-------------------------:
![Simulator Screen Shot - iPhone 12 Pro - 2021-03-25 at 10 50 33](https://user-images.githubusercontent.com/495617/112453649-32920180-8d58-11eb-974d-4e1b218e7d1e.png) | ![Simulator Screen Shot - iPhone 12 Pro - 2021-03-25 at 10 51 11](https://user-images.githubusercontent.com/495617/112453670-36258880-8d58-11eb-8b35-5d78027bf6c7.png)

**Comment by joshheald** [comment]
This still happens, but doesn't cause any particular issues and hasn't been looked at in over a year. @pmusolino feel free to reopen if you disagree but I think we can close this.
