### ISSUE TITLE
[Mobile Payments] CredStore - performQuery - Error copying matching creds.  Error=-25300

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#3880]
⚠️ This issue is against the feature branch implementing support for Card Present Payments, not against develop ⚠️

The following messages are logged to Xcode's output window when connecting to an actual card reader:

```
2021-03-26 13:33:19.963562-0700 WooCommerce[997:138251] CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    ptcl = htps;
    "r_Attributes" = 1;
    sdmn = "gator.stripe.com";
    srvr = "gator.stripe.com";
    sync = syna;
}
2021-03-26 13:33:19.966814-0700 WooCommerce[997:138251] CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    ptcl = htps;
    "r_Attributes" = 1;
    sdmn = "gator.stripe.com";
    srvr = "gator.stripe.com";
    sync = syna;
}
2021-03-26 13:33:20.048051-0700 WooCommerce[997:138251] CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    ptcl = htps;
    "r_Attributes" = 1;
    sdmn = "gator.stripe.com";
    srvr = "gator.stripe.com";
    sync = syna;
}
2021-03-26 13:33:20.049849-0700 WooCommerce[997:138251] CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    ptcl = htps;
    "r_Attributes" = 1;
    sdmn = "gator.stripe.com";
    srvr = "gator.stripe.com";
    sync = syna;
}
```

**To Reproduce**
1. Go to Settings > Manage Card Readers
2. Tap on Connect to Reader
3. Power on the reader
4. Wait for it to find it. Tap on Connect.
5. See warnings logged to Xcode's output window

**Expected behavior**

No errors. There doesn't seem to be a downside from this behavior other than the errors. 

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XR
- iOS version: 14.4.1
- WooCommerce iOS version: See above

**Comment by allendav** [comment]
Noteworthy: I cannot reproduce this issue with Stripe's [rocket rides pilot example app](https://github.com/stripe-samples/sample-terminal-ios-app).

**Comment by koke** [comment]
I can't reproduce this anymore with either the Chipper or WisePad 3. This looks like a bug in the StripeTerminal framework that they might have fixed already. What I understand, is that something in the Terminal library was trying to find some credentials for `gator.stripe.com` using the `htps` protocol, so it definitely looks like a typo. If it reappears, we should report to Stripe directly
