### ISSUE TITLE
Variations: Update empty state screen

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#3903]
Ref: p91TBi-4O0-p2

If the product doesn't have variations and doesn't have attributes:
- Add subtitle Copy 
- Update button text

<img width="356" alt="no-attrs-no-variations" src="https://user-images.githubusercontent.com/562080/113593674-4b25d580-95fc-11eb-9711-d022077e8d35.png">

Note: Leave the current state when the product doesn't have variations but does have attributes.

**Comment by Ecarrion** [comment]
Being worked on by @itsmeichigo

**Comment by itsmeichigo** [comment]
Hi @Ecarrion - I'm on develop branch and seeing different color on navigation bar and different title label on the empty view as the screenshot below. Are you sure this design is up-to-date?

![Simulator Screen Shot - iPod touch (7th generation) - 2021-04-26 at 22 49 37](https://user-images.githubusercontent.com/5533851/116112675-f8fb4000-a6e1-11eb-8534-ca04a14dc435.png)

**Comment by Ecarrion** [comment]
Hey @itsmeichigo, you can omit the navigation bar color but please adjust the content of the label!
