### ISSUE TITLE
Variations: Update Variations list Buttons

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#3904]
Ref: p91TBi-4O0f-p2

Update variations list screen to:
- Update "Add Variation" button copy
- Move "Edit attributes" action from the navigation bar to a button below the "Add variation" button
- Update buttons to match the designs.

<img width="378" alt="update-variations-list" src="https://user-images.githubusercontent.com/562080/113597551-7c54d480-9601-11eb-82ac-ab12dd0425f6.png">

**Comment by Ecarrion** [comment]
Being worked on by @itsmeichigo

**Comment by itsmeichigo** [comment]
FYI I will ignore the `Done` button as it seems redundant and it's not present in current version also.

![Simulator Screen Shot - iPod touch (7th generation) - 2021-04-26 at 23 30 21](https://user-images.githubusercontent.com/5533851/116118847-eedc4000-a6e7-11eb-8599-21b10ef3c853.png)
