### ISSUE TITLE
Shipping Labels: add custom package flow

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#3909]
As part of Shipping Labels M4, when creating a shipping label for an order, a store owner will get to a step where they need to set up the package used for the products to be shipped. During this step, we want to allow users to:
- Create a custom package, or
- Activate an existing service / predefined package (the API uses the term predefined, but Woo UI uses the term service)

A custom package has parameters that are completely set by the users, while a service/predefined package is a package with parameters that are already defined by the shipping carriers (USPS or DHL at the time of this writing).

Make sure to follow the release order: https://github.com/woocommerce/woocommerce-ios/issues/4595

@hafizrahman published a retrospective for Android here that explain basically everything important on this task p91TBi-5Jh

Subtasks (feel free to split them into more subtasks):
- [ ] Update the eligibility criteria to accept stores with no packages.
- [x] #4742
- [x] Implement an empty screen for all the cases when the Package Selected screen doesn't have any existing package.
- [x] Create a new screen (preferably in SwiftUI, since this flow is entirely in SwiftUI), which contains the two tab selectors "Custom Package" and "Service Packages". Ideally, they are two separates SwiftUI subviews.
- [x] Create the screen "Custom Package", and check that all the fields in the Custom Package form are mandatory.
- [x] Create the screen "Service Packages": we should do a `GET` on `packages`. It will return `formSchema` and `formData`. `formSchema` is the list of all available service packages. `formData` is the list of all created/activated custom/service packages. We had to compare the two to get the service packages that can still be enabled. We should allow the selection of just one predefined package, and this will be the only difference with `wp-admin`.
- [x] Create the Package Type screen with the list selector containing just the two options `Box` and `Envelope`.
- [x] Use the [existing endpoint](https://github.com/woocommerce/woocommerce-ios/issues/3870) for creating a new Custom Package. It should be probably be edited on our side, for enabling also the predefined packages.

Things to be aware of:
- Activate only one service at a time.
- Empty view design is needed in case all packages are already activated.
- Once a service package is activated, make sure it is then listed in the package selector screen and removed from the service package activation screen (in case the user goes back to activate another service package).

An example JSON request to create two custom packages and activate two service packages at once looks like this:
```
{
    "custom":[
        {
            "is_user_defined":true,
            "is_letter":false,
            "name":"My Own Package",
            "inner_dimensions":"10 x 10 x 10",
            "box_weight":1,
            "max_weight":0
        },
        {
            "is_user_defined":true,
            "name":"test 02",
            "inner_dimensions":"1 x 1 x 1",
            "box_weight":1,
            "max_weight":0
        }
    ],
    "predefined":{
        "usps":[
            "small_flat_box",
            "medium_flat_box_top"
        ],
        "dhlexpress":[
            "Box2Cube",
            "Box2Small",
            "Box2Medium",
            "Box3Large"
        ]
    }
}
```

To create just one custom package, we simply enter one object into the custom array and set predefined as an empty object.

To activate a predefined package, we add the carrier/package name pair in predefined and let the custom part be an empty array.

For custom package, as far as I can tell, `is_user_defined` is always set as `true`. `max_weight` do not seem to be used yet in Woo. In core there is no user-facing field to set max_weight value, and saving seems to always set that value to zero, so I’m replicating that behavior in the Android app.

The Figma file is the source of truth.

<img width="730" alt="Schermata 2021-04-06 alle 12 37 31" src="https://user-images.githubusercontent.com/495617/113698539-dd99a800-96d4-11eb-9018-d28ec451e0ff.png">

**Comment by hafizrahman** [comment]
Some non-obvious gotchas I encountered while developing this feature for Android that y'all might be interested in:

**Custom package:**
1. Core allows empty package weight to be zero, but length/width/height can't be zero.
2. Once a custom package is created, make sure it is then listed in the package selector screen (this will be the screen before the package creation screen if there's already existing packages).

**Service package:**
1. Once a service package is activated, make sure it is then listed in the package selector screen _and_ removed from the service package activation screen (in case user goes back to activate another service package).
2. You will need to create an empty screen for service package in case all available service packages are already activated.
