### ISSUE TITLE
Coupon management (task 1): networking layer

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#3912]
Coupons Management is one of the core functionalities that we want to offer to our users, and that is part of the Order Creation process. Also if the Coupons Management is part of the Order Creation, we'd like to maintain the flow separated. In this way, we can allow users to customize them from the app settings or from other points of the app.

The first task will be to implement the networking layer for fetching/adding/editing/delete coupons remotely, plus the creation of the models, based on our [API documentation](https://woocommerce.github.io/woocommerce-rest-api-docs/#coupons).

<img width="939" alt="Schermata 2021-04-06 alle 16 50 32" src="https://user-images.githubusercontent.com/495617/113732272-bd301480-96f9-11eb-9b30-02c966580838.png">

**Comment by joshheald-a8c** [comment]
Coupon Model

- [x] Add fields
- [x] Codable
- [x] Comparible
- [x] GeneratedCopiable
- [x] GeneratedFakeable

Field list:
- id
- code
- amount
- date_created_gmt
- date_modified_gmt
- discount_type
- description
- date_expires_gmt
- usage_count
- individual_use
- product_ids
- excluded_product_ids
- usage_limit
- usage_limit_per_user
- limit_usage_to_x_items
- free_shipping
- product_categories
- excluded_product_categories
- exclude_sale_items
- minimum_amount
- maximum_amount
- email_restrictions
- used_by

**Comment by joshheald-a8c** [comment]
CouponListMapper
- [x] Add coupons-all.json
- [x] Create Mapper
- [x] Test list decoding
- [x] Test siteId injection
- [x] Test date decoding strategy
- [x] Test field decoding

**Comment by joshheald-a8c** [comment]
CouponsRemote

- [x] loadAllCoupons method
- [x] deleteCoupon method
- [x] test error relay

**Comment by joshheald-a8c** [comment]
CouponMapper

- [x] Add coupon.json
- [x] Create mapper
- [x] Test object decoding
- [x] Test siteId injection
- [x] Test date decoding strategy
- [x] Test field decoding
- [x] Consider Refactor to share between List and individual mapper

**Comment by itsmeichigo** [comment]
Closing this issue in favor of the new Coupons project.
