### ISSUE TITLE
Coupon management (task 2): storage layer

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#3913]
The second task of the Coupon management will be to implement the storage layer, storing in Core Data the coupons of every website when they are fetched.

Here P91TBi-48i you can find one of our internal guides on how to generate Core Data Files.

**Comment by joshheald-a8c** [comment]
Storage tasks

- [x] Add Core Data entity
- [x] Add test for migration

**Comment by itsmeichigo** [comment]
Closing this issue in favor of the new Coupons project.
