### ISSUE TITLE
Coupon management (task 3): Yosemite layer

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#3915]
After having implemented the [networking layer](https://github.com/woocommerce/woocommerce-ios/issues/3912) and the [storage layer](https://github.com/woocommerce/woocommerce-ios/issues/3913), we should make in communication them implementing the Yosemite layer, which will be exposed to the Woo app.

**Comment by itsmeichigo** [comment]
Closing this issue in favor of the new Coupons project.
