### ISSUE TITLE
Coupon management (task 4): list all the coupons

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#3916]
As part of the Coupons management, we should implement a screen that displays the list of all the coupons available.

We should manage:
- [ ] Pull to refresh.
- [ ] Pagination.
- [ ] Cells.
- [ ] Tap on cells.
- [ ] State in case of error or in case there are no coupons.
- [ ] "Add" button in the navigation bar.
- [ ] Implement a swipe for deleting the single coupon. 
- [ ] Dark mode.

<img width="436" alt="Schermata 2021-04-06 alle 17 10 44" src="https://user-images.githubusercontent.com/495617/113734520-b0142500-96fb-11eb-995a-a681dc116592.png">

**Comment by joshheald-a8c** [comment]
- [x]  Pull to refresh.
- [x]   Pagination.
- [x]   Cells.
- [x]   Tap on cells.
- [x]   State in case of error or in case there are no coupons.
- [x]   "Add" button in the navigation bar.
- [ ]   Implement a swipe for deleting the single coupon.
- [ ]   Dark mode.

**Comment by itsmeichigo** [comment]
Closing this issue in favor of the new Coupons project.
