### ISSUE TITLE
Coupon management (task 5): add and edit coupon

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#3917]
As part of the coupon management, we should implement a screen that can be used for adding or editing an existing coupon. 

Tasks:
- [ ] The navigation bar button should be `Add` or `Edit`, based on the action we want to accomplish.
- [ ] The navigation title should be updated according to the action we want to accomplish.
- [ ] The amount cell should manage all the edge cases, and a user should be able to add just numeric characters.
- [ ] Generate coupon code button, that ideally follows the same behavior of the backend for generating a coupon code.
- [ ] Coupon expiry: it should display a date picker that works on iOS 13 and iOS 14.
- [ ] Usage Limit: it can be an editable text field that accepts int values.
- [ ] A loading screen that will be fired when the user press "Add".
- [ ] Dark mode.

![new coupon](https://user-images.githubusercontent.com/495617/113734982-19943380-96fc-11eb-891e-aa14310bb6d8.jpg)

**Comment by itsmeichigo** [comment]
Closing this issue in favor of the new Coupons project.
