### ISSUE TITLE
Shipping Labels M2: Invalid address banner seems to always be shown on edit address screen (even with valid address)

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#3919]
**Describe the bug**

I'm not 100% sure that this is an issue (I might be doing something wrong with the addresses I'm using) but I think we're always showing the invalid address banner on the edit address screen, even if the address _is_ valid.

The way the banner was implemented in https://github.com/woocommerce/woocommerce-ios/pull/3731, it should only appear if there is a problem with the address. However, even after I select a suggested address, if I go to the edit address screen I see that top banner.

**To Reproduce**

1. Go to the Orders > Processing tab.
2. Select an order.
3. Select "Create Shipping Label."
4. Select "Continue" in the "Ship from" section.
5. If the "Ship from" address is accepted, the "Continue" button will disappear. (If the "Ship from" address isn't accepted, you'll end up on the suggested address screen. Select "Use Suggested Address" — this will take you back to the Create Shipping Label screen.)
6. Tap on the "Ship from" section to open the edit address screen.
7. Notice that even though you have a valid, accepted origin address, the top banner appears.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/113737492-f9fa0c80-96f5-11eb-8507-1cf5107a5068.gif" width="300px">

**Comment by koke** [comment]
It does look like a bug to me. What I'm seeing is that the error shows up because the address is only being validated when you tap on the Done button. But even then, if you come back to the screen, it will show the banner again, since it's a new view that hasn't validated.

I'm still not fully understanding the validation flow, but I'll investigate more
