### ISSUE TITLE
Images with special characters in filenames fail to load

### ISSUE THREAD

**Issue by ealeksandrov** [woocommerce/woocommerce-ios#3928]
## Description

iOS app fails to preview ([1](https://github.com/woocommerce/woocommerce-ios/blob/14ced0b655757025532350c4e3bd281a064b84d8/WooCommerce/Classes/Tools/ImageService/DefaultImageService.swift#L61), [2](https://github.com/woocommerce/woocommerce-ios/blob/14ced0b655757025532350c4e3bd281a064b84d8/WooCommerce/Classes/ViewRelated/Products/Media/DefaultProductUIImageLoader.swift#L57), [3](https://github.com/woocommerce/woocommerce-ios/blob/14ced0b655757025532350c4e3bd281a064b84d8/WooCommerce/Classes/ViewRelated/Products/Media/Media%2BWPMediaAsset.swift#L8), ...) and [map](https://github.com/woocommerce/woocommerce-ios/blob/f7f51638a0c85bcf58ec5d4c1970995045750d47/Networking/Networking/Model/Media/Media.swift#L50) image URLs with non-encoded special characters.

Support request: p4a5px-2Jd-p2

### Possible solution

Add `.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)` on all affected strings on iOS side.

## Test

1. Create an image with non-latin characters in name, like `test-图像.png`
2. Upload it to Media Library
3. Create a new product and assign test image to it
4. Open mobile app, switch to products tab
5. Check product icon in the list
6. Open product details
7. Check product image in the header
8. Tap "Add Image" icon -> "Add Photos" -> "WP Media Library"
9. Check that media library loads all data and displays test image from step 1

## Screenshots

|Example image in web admin media library|
|---|
|<img width="1118" alt="Screenshot 2021-04-07 at 20 37 09" src="https://user-images.githubusercontent.com/3132438/113910099-1fb01000-97e1-11eb-924a-3d9d0667cc41.png">|

products | product | media lib
---|---|---
![products](https://user-images.githubusercontent.com/3132438/113910718-d3b19b00-97e1-11eb-91f7-faf29d6dbd88.png)|![product](https://user-images.githubusercontent.com/3132438/113910729-d613f500-97e1-11eb-896f-7d055d74a504.png)|![media lib](https://user-images.githubusercontent.com/3132438/113910735-d8764f00-97e1-11eb-91ac-5c65847af044.png)

**Comment by pmusolino** [comment]
This is similar to this issue https://github.com/woocommerce/woocommerce-ios/issues/2789
