### ISSUE TITLE
Stats: tabs text and order are reversed in RTL languages

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-ios#3934]
While testing the app in Arabic, I noticed that when I first open the app, and after the loading view is dismissed, the tabs of the stats are reversed, same as their content:
<img width=400 src="https://user-images.githubusercontent.com/1657201/114030595-7a457c80-9872-11eb-9187-02349250e76d.jpeg"/>
If I sent the app to background, and re-open it, they will show in the correct order:
<img width=400 src="https://user-images.githubusercontent.com/1657201/114030633-816c8a80-9872-11eb-909d-4ab75e6633dc.jpeg"/>

I confirmed that this happens with other RTL languages as well.

**Comment by shiki** [comment]
This was also reported by a customer. Details and comparison about Android here: https://github.com/woocommerce/woocommerce-ios/issues/4164
