### ISSUE TITLE
Update back buttons on login flow

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#3944]
Context: Back buttons on the app should not have any text on them.

Problem: Login flow is showing `Back` as the companions' text for its back buttons.

Desired Solution: Make sure login flow only show the back arrow(`<`) with no text on their back buttons.

<img width="713" alt="Screen Shot 2021-04-09 at 9 54 53 AM" src="https://user-images.githubusercontent.com/562080/114199131-a831cc00-9919-11eb-8702-834bcd8fd46d.png">

**Comment by shiki** [comment]
@ealeksandrov Is this something that you're still working on or should we remove this from the board for now?

**Comment by ealeksandrov** [comment]
Accidental closing :)

> Is this something that you're still working on

Yes, I have changes ready, was messing with some podspec updates to include. Will probably skip that part and push PR with UI changes this week.
