### ISSUE TITLE
[Mobile Payments] [Epic] Allow for card present payment for subscriptions

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#3949]
Buyers will be able to specify "cash on delivery" as their payment method for Buy Online Pick Up In Store (BOPIS) or Delivery and then use card-present payments to pay for their non-subscription based order.

However, WooCommerce core's cash on delivery payment method does not appear in checkout when a subscription product is in the cart. We are going to need to design something for this.

**Comment by allendav** [comment]
@malinajirka  - would you open a corresponding issue for Android?

**Comment by ctarda** [comment]
Closing for now, as this is not something we are going to do soon
