### ISSUE TITLE
Home Screen – Big titles design update

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-ios#3959]
Ref: p91TBi-4N4-p2#comment-3867

The big Titles in the Home screen does not work for longer store names. We want to update the screen to include the “My Store” big title + store name as subtitle by default. On scroll, we could display the scrolled title style and the tabs.

<img width="322" alt="Screenshot 2021-04-13 at 7 09 18 PM" src="https://user-images.githubusercontent.com/22608780/114562525-309ecc80-9c8c-11eb-809f-c554ef35977f.png">

**Comment by Garance91540** [comment]
For current Home screen:

<img width="678" alt="Screen Shot 2021-05-20 at 3 23 39 PM" src="https://user-images.githubusercontent.com/28450084/118986190-687deb80-b97f-11eb-875a-212af0e6ebae.png">

**Comment by Ecarrion** [comment]
We should follow android conclusions:

> IMHO, tabs always visible feel better. The scrolling feels more natural and less elements moving around.


ref: https://github.com/woocommerce/woocommerce-android/issues/3836#issuecomment-863947489

**Comment by fernandofgfer** [comment]
Hi @Garance91540! :wave: I have some doubts:

- Taking into account the current design, when user scrolling, should the title be on the left or the center (like right now)?
- As @Ecarrion says, Should we adopt the Android solution with tabs always visible?

Thanks for your help :smiley_cat:

**Comment by Ecarrion** [comment]
Hey @fernandofgfer!

> Taking into account the current design, when user scrolling, should the title be on the left or the center (like right now)?

The store name should be left-aligned. The navigation title should have the native alignment.

> As @Ecarrion says, Should we adopt the Android solution with tabs always visible?

Yes, always visible, please.

**Comment by Garance91540** [comment]
I liked @Ecarrion 's comment but that might not have been clear enough! I agree with both of @Ecarrion last comments

**Comment by fernandofgfer** [comment]
Hi! I have a new version of this issue, please, let me know your thoughts! 
![Light Mode](https://user-images.githubusercontent.com/11411847/124394414-b0728b00-dcff-11eb-96d5-2d50b36816f2.gif)
![Dark Mode](https://user-images.githubusercontent.com/11411847/124394436-c08a6a80-dcff-11eb-8ede-3c5f47090e70.gif)

**Comment by Garance91540** [comment]
HI, I like this! Feel free to tag @woocommerce/mobile-designers anytime you'd like a design review so either Adam or I get notified to take a look. 

One thing: The date should always be sticky too under the tab so users can be sure which time period they are looking at:
<img width="751" alt="Screen Shot 2021-07-06 at 9 15 43 AM" src="https://user-images.githubusercontent.com/28450084/124558473-f2ecb280-de3a-11eb-974a-9aff1b4077d9.png">

**Comment by fernandofgfer** [comment]
Hi @Garance91540, after researching how to fix the date, we decided to create a new issue since it is quite biggest than we thought initially. The new issue is https://github.com/woocommerce/woocommerce-ios/issues/4571

**Comment by Ecarrion** [comment]
Closing this as it's being solved by @fernandofgfer on https://github.com/woocommerce/woocommerce-ios/pull/4533, the outstanding issue is being tracked in https://github.com/woocommerce/woocommerce-ios/issues/4571 and https://github.com/woocommerce/woomobile-private/issues/47
