### ISSUE TITLE
[Mobile Payments] Recover from user removing access to bluetooth and location

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3972]
Explore what happens if users do not grant access to bluetooth and location services when they are prompted to do so by the Stripe Terminal SDK or if they remove access at a later time

**Comment by koke** [comment]
Solved by #4289 or do you have something else in mind?

**Comment by ctarda** [comment]
Nope, #4289 is exactly what solves this. Closing!
