### ISSUE TITLE
Question regarding collaboration on iOS apps

### ISSUE THREAD

**Issue by izaguirrejoe** [woocommerce/woocommerce-ios#4000]
I understand this isn't directly related to WooCommerce, but I'm not finding help online for this. How do you setup an iOS app to collaborate with other developers? My friend and I have personal iCloud accounts that we use to develop apps in our free time. When he clones to his computer and runs on his phone, he gets errors with the team, bundle identifier, and push notifications. We don't have a company, so I can't create a team and assign roles. How do we collaborate with each other if we can't make a team? Apparently you need to show proof of a company to Apple to create a Team account. Thanks in advance for the help.

**Comment by astralbodies** [comment]
Hey @izaguirrejoe! Code signing can get really tricky - we definitely understand that with our project being open-source. We don't share access to our Apple Developer portal which can make being a contributor difficult. Mostly we have people switch code signing identities to their own, and change the bundle ID to something in their portal. In the past you could create wildcard identifiers which made code signing a lot easier, but I believe Apple has moved away from that. When you get to more complex scenarios like watchOS apps or extensions for sharing, notifications, widgets that makes it nearly impossible to easily switch projects around to a different developer account.

My suggestion would be to consider the legal implications first of having an app in the App Store and consider forming a company. Publishing an app does come with some legal responsibilities as you're creating a customer base, establishing privacy policies with them, and creating a formal relationship with Apple. If your friend is just helping out with your own app, I'd consider sharing your certificate and profiles with them directly. Ultimately whatever entity publishes an app to the App Store is entering a contract with Apple.
