### ISSUE TITLE
Add-Ons: Missing global add-ons

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#4007]
**Describe the bug**

The app is showing only add-ons specifically added to the product, but not those set up for all products or a specific category.

**To Reproduce**
1. [Web] Set up an Add-on from Products > Add-ons that applies to All Products (I used gift-wrapping as an example).
2. [Web] Create an order for a product including this new add-on.
3. [iOS] Open the order detail from the app.

If this is the only add-on in the order, there is no option to view add-ons. If there are product-specific add-ons, the "View add-ons" button is present, but the list of add-ons will exclude the global one.

**Screenshots**

The order on the web:

<img src="https://user-images.githubusercontent.com/8739/115537122-c9d86f00-a29a-11eb-8a34-afddc2e8e2f1.png" width="270" alt="Screen Shot 2021-04-21 at 12 11 39">

The order in the app:

<img src="https://user-images.githubusercontent.com/8739/115537158-d2c94080-a29a-11eb-9af6-f6a61f089231.png" width="270" alt="Simulator Screen Shot - iPhone 12 Pro - 2021-04-21 at 12 11 46">

Add-on list in the app:

<img src="https://user-images.githubusercontent.com/8739/115537178-d8bf2180-a29a-11eb-9a77-d10adf8499ef.png" width="270" alt="Simulator Screen Shot - iPhone 12 Pro - 2021-04-21 at 12 11 49">

**Expected behavior**

The app should also show the add-on that was set for all products.

**Mobile Environment**
Please include:
- Device: Simulator
- iOS version: 
- WooCommerce iOS version: `develop` (488d423d8)

**Comment by Ecarrion** [comment]
Thanks for reporting this @koke, I have analyzed it more deeply and this requires a significant amount of work. For that reason, I've broken it down into four tasks.

- #4042
- #4043
- #4044
- #4045 

Let me close this. 🙇
