### ISSUE TITLE
[Mobile Payments] Improve handling of payment capture errors originating outside the Terminal SDK

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4012]
Right now, if payment capture fails due to a fault not in the reader SDK, but in the self-hosted site and/or our WCPay servers, we present a single generic error.

We should consider distinguishing between errors and present specific alerts or instructions to the merchant.

See https://github.com/woocommerce/woocommerce-ios/pull/4004/files#r617880037

**Comment by AliSoftware** [comment]
Moved this issue's milestone to 6.9, as code freeze for 6.8 is happening today.
