### ISSUE TITLE
[Mobile Payments] Card Reader Settings v2-13: Card Reader Software Updates

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4059]
Add a new enum enumerating the possible update states:

	.checkingForUpdate
	.noUpdateAvailable
	.updateAvailable
	.updateInProgress
	.updateCompleted
	.updateFailed

Update CardReaderSettingsConnectedViewModel
- to dispatch checkForUpdate when connected to a reader
- expose the readerUpdateStatus Enum and readerUpdateProgress Float to its ViewController
- expose a beginUpdate func for the ViewController to be able to call
- add a didUpdate (similar to how the CardReaderSettingsUnknownViewModel) to inform the VC when changes to the reader update status (or progress) have changed

Update CardReaderSettingsConnectedViewController
- hook into the VM didUpdate for notifications
- in that, monitor for changes to the status or progress and display notice, button, or progress modal as appropriate

NOTE: According to Stripe, we can expect that when the reader update completes, the reader will disconnect and need to be discovered again.

NOTE: Recommend doing this in at least two PRs - i.e. one to show that an update is available and a second PR to actually allow the user to do something about it

**Comment by ctarda** [comment]
@allendav may I suggest implementing this against a feature branch instead of develop?

We still don't know how much stabilizing we are going to have to do for beta 1. If there is not enough bugfixing to do, and we have time to implement this on time, we can merge before the release. But if we get pulled away in order to stabilize beta 1, I think it would be safer to avoid adding any other potential instability. Have in mind that we release every two weeks, so worst case scenario it wouldn't be much of a delay 😄

**Comment by ctarda** [comment]
> may I suggest implementing this against a feature branch instead of develop?

Probably a feature flag specific for this would be simpler?

**Comment by allendav** [comment]
Hey @ctarda - I can name this tune in four small PRs - what do you think?

- [ ] First
    - [ ] Add a feature flag for reader-updates
    - [ ] Feature flag should auto-use simulated reader
    - [ ] Add a onViewModelDidUpdate to the CardReaderSettingsConnectedViewController similar to what is already being done for CardReaderSettingsUnknownViewController, and set the VM didUpdate to it
    - [ ] Dispatch the checkForCardReaderUpdate action from the viewmodel updateProperties method 
    - [ ] Have the “please update your reader” row and button appear if a reader update is available (hook up didUpdate in the VM and fire it in the completion for checkForCardReaderUpdate when an update is available)
    - [ ] Add the alert, but only connect skip (don’t connect update)
- [ ] Then
    - [ ] Hook up the alert update button, VM mutates prompting VC to add the full screen “updating reader” modal
    - [ ] Have the VM prompt the VC to close the full screen modal auto close after some hard coded # seconds with a failure
    - [ ] Have the snack bar show the failure (and a retry button that repeats the process)
- [ ] Then
    - [ ] Change the full screen modal to dispatch startCardReaderUpdate
    - [ ] Note: Right now the Figma file doesn’t show any progress indicator
    - [ ] Have the full screen modal close on completion
    - [ ] Have the snack bar show success (or failure) (With this we should be able to see the entire lifecycle - from simulated connected reader needs an update,  to update done, to simulated connected reader no longer needs an update)
- [ ] Then
    - [ ] Remove the feature flag and remove the auto-use of a simulated reader behavior to use real readers

**Comment by ctarda** [comment]
Hi @allendav 

The plan looks good to me, just on question about something I am not sure I understand  (blame it on the language barrier)

> Feature flag should auto-use simulated reader

What does that mean exactly?

**Comment by allendav** [comment]
> Feature flag should auto-use simulated reader

> What does that mean exactly?

I was thinking that the feature flag that this work is done under should, if possible, automatically engage the reader simulator and not real readers - to make testing easier (i.e. the reviewer would just have to set the flag when testing the branch instead of changing code) but if it turns out to be very little / one line to use the simulator, then this won't be needed
