### ISSUE TITLE
[Mobile Payments] [UI] Add support for Dynamic Type to modal view

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#4064]

**Comment by koke** [comment]
Related to this, I spotted a localized string that didn't fit in the existing modals.

<img src="https://user-images.githubusercontent.com/8739/124460191-57523800-dd8f-11eb-8c17-b9dea6245f18.png" width="270" alt="Screen Shot 2021-07-05 at 12 46 30">
