### ISSUE TITLE
[Mobile Payments] Closing the Loop: Add customer name, email, order, order_key and other info to intent metadata

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4077]
Both the WCPay server and WCPay client rely on certain bits of metadata to be added by when creating payment intents.

The fields are, at this time:

- `customer_name`: e.g. "Allen Snook"
- `customer_email`
- `site_url`: e.g. "https://staging.marsiswaiting.com"
- `order_id`: e.g. 6140
- `order_key`: e.g. wc_order_0000000000000
- `payment_type`: e.g. `single`

The site_url is the URL of the store. The order_key is available from order metadata in _order_key. The [payment_type](https://github.com/Automattic/woocommerce-payments/blob/e099744fb8cead46fe23ec25d785e40827947c1f/includes/constants/class-payment-type.php#L20-L23) is `single` for one-time payments and `recurring` for subscription payments.

The WCPay server cares about order_key. It should not be omitted.

The client relies certain bits to display transaction details. Without it, some of the transaction columns in the list view are empty and the transaction detail view in wp-admin fails to load properly at all.

![missing](https://user-images.githubusercontent.com/1595739/116614823-47c9f500-a8ef-11eb-9c21-65c243316260.png)

See also #3863 

cc @ctarda @malinajirka

**Comment by ctarda** [comment]
We can break this down in two. First, for beta one, we can add all the metadata, except for `order_key`. 

As soon as we merge into develop and touching the core data store is safe, we'd need to add the order_key to the Order object.

**Comment by allendav** [comment]
Moved back to "To do" until we are ready to do the remaining step: order key

**Comment by allendav** [comment]
Closing this issue - we have a separate issue now just for order key: #4282
