### ISSUE TITLE
[Mobile Payments] Closing the Loop: Handle error responses from capture_terminal_payment endpoint

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4078]
e.g. wcpay_missing_order, or attempting to capture a payment intent that is not capture-able, etc.

See https://github.com/Automattic/woocommerce-payments/pull/1689/files

Props @malinajirka

**Comment by AliSoftware** [comment]
Moved this issue's milestone to 6.9, as code freeze for 6.8 is happening today.

**Comment by ctarda** [comment]
Closing for now
