### ISSUE TITLE
[Mobile Payments] Disable Apple Pay on the device during card capture

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4079]
Observed (again) today on my iPhone XR and BBPOS Chipper 2XBT during payment capture. I thought I had written this issue up already but alas I apparently did not.

Otherwise, your phone will attempt to complete the payment for you if the card reader is within a few inches of the phone when you start card capture.

See https://developer.apple.com/documentation/passkit/pkpasslibrary/1617078-requestautomaticpasspresentation

Props Karl/Stripe for the suggested fix.

Note:

> This method requires a special entitlement from Apple. If the entitlement isn’t present, the request fails with a PKPassLibrary result. For more information, see developer.apple.com/apple-pay/.

cc @ctarda @AliSoftware

**Comment by ctarda** [comment]
Nice, thanks for logging this. We should probably try to get this into beta 1, so I'll move it to the top of the backlog for now to have visibility
