### ISSUE TITLE
[Mobile Payments] Do not display Create Shipping Label for cash-on-delivery orders

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4101]
When looking at an order that was placed using the cash-on-delivery payment method, don't display the Create Shipping Label button nor the "Learn more" link below it. This might help the payment section float a bit closer to the top of the device viewport

I am assuming we don't support [USPS COD](https://faq.usps.com/s/article/Collect-on-Delivery) labels nor [FedEx COD](https://www.easypost.com/docs/api) - @c-shultz  can you confirm that?

cc @ctarda  @malinajirka @hichamboushaba

**Comment by hichamboushaba** [comment]
That's a good point, and I think an issue should be filed also in the https://github.com/Automattic/woocommerce-services/ and in https://github.com/woocommerce/woocommerce-android, I just tested on the web client, and I can see the "Create shipping label" button on an order with cash on delivery payment:
<img width="1072" alt="Screen Shot 2021-04-30 at 23 28 52" src="https://user-images.githubusercontent.com/1657201/116763143-4b9f6980-aa0c-11eb-937d-6037265f32e3.png">

**Comment by AliSoftware** [comment]
Moved this issue's milestone to 6.9, as code freeze for 6.8 is happening today.
