### ISSUE TITLE
[Mobile Payments] Support for multiple stores

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#4111]
The StripeTerminal framework requires a connection token to work, which I understand is site-specific.

We should ensure that users with multiple stores set up in the app show the right availability for payments and use the correct connection token.

**Comment by ctarda** [comment]
According to Stripe's documentation, there is a method in Terminal that clears all the caches: https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPTerminal.html#/c:objc(cs)SCPTerminal(im)clearCachedCredentials

> Clears the current connection token, saved reader sessions, and any other cached credentials. You can use this method to switch accounts in your app, e.g. to switch between live and test Stripe API keys on your backend.

At this point in time, CardReaderService exposes a method, called `clear()` that calls `Terminal.shared.clearCachedCredentials()`

So what we would need to do, from what I can tell is:
* Add an action to CardPresentPaymentAction to "clear" or "resetService" or whatever we decide to call it. The effect of that action is a call to `disconnectReader()` and then `clear()`
* Dispatch that action in SwitchStoreUseCase's `logOutOfCurrentStore`

When the switch is completed, users would need to start the reader discovery process again to discover and connect to readers, which would automatically fetch a new token.
