### ISSUE TITLE
Migrate SettingsViewController to use MVVM for testability

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#4142]
## Problem
While working on the Settings screen for issue #3921, I had to add a feature flag for the Plugins section as this feature is not yet ready for public users. Then I wanted to add tests to make sure that my feature flag check works right for different build environments, but the `SettingsViewController` is now still using MVC and there's virtually no way to add tests to it.

## Suggested solution
To make the view controller testable, I'd propose migration to the MVVM pattern. The setup is simple:
- The view model takes `FeatureFlagService` as a dependency.
- The view model takes care of the table view contents (rows, sections) and exposes these so that the view controller only needs to display data.
- Unit tests can use a mock feature flag service and check if the displayed rows and sections are as expected.

Let's add tests for more code confidence!

<img src="https://media.giphy.com/media/SKGo6OYe24EBG/giphy.gif" width=400 />

**Comment by selanthiraiyan** [comment]
Hello @itsmeichigo 👋 
I would like to work on this if it is still relevant. (i.e. If we haven't decided to go with SwiftUI)
Kindly assign the ticket to me if you are OK with it. Thank you!
Nice gif BTW. 😀

**Comment by itsmeichigo** [comment]
Thanks for your interest @selanthiraiyan! I have assigned the ticket to you, please go ahead with it 🙂
