### ISSUE TITLE
[Mobile Payments] Unexpected reader disconnection

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#4159]
We completely missed the case where the reader disconnects unexpectedly.

We need to implement this:

https://stripe.dev/stripe-terminal-ios/docs/Protocols/SCPTerminalDelegate.html#/c:objc(pl)SCPTerminalDelegate(im)terminal:didReportUnexpectedReaderDisconnect:

**Comment by ctarda** [comment]
Implemented as part of #4157

**Comment by designsimply** [comment]
Closing because the latest comment says it was implemented as part of https://github.com/woocommerce/woocommerce-ios/pull/4157. Please re-open if that's not right!
