### ISSUE TITLE
Stats Tabs Text is Reversed in Arabic

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#4164]
Possibly even in RTL. 

Reported from 3975927-zd-woothemes.

I don't speak Arabic and can't read it. But this is how the “This Year” looks like right now:

<img width="320" src="https://user-images.githubusercontent.com/198826/117745206-49d16500-b1c7-11eb-9dcf-d7d0dcb4b378.png">

But the string from `Localizable.string` looks like this: 

https://github.com/woocommerce/woocommerce-ios/blob/5f28428223fa869d0c00e192fe52bc0bc24c09af/WooCommerce/Resources/ar.lproj/Localizable.strings#L2740

If you look at it closely, it looks like the text is reversed. The customer mentioned it should look like this: 

<img width="320" src="https://user-images.githubusercontent.com/198826/117745445-b9475480-b1c7-11eb-818e-235a356f0565.png">

### Android

For comparison, this is what Android looks like, which is most probably correct:

<img width="320" src="https://user-images.githubusercontent.com/198826/117745234-548bfa00-b1c7-11eb-8c4a-f3128b645f81.png">

---

Marking as high priority cause this affects readability for all Arabic merchants.

**Comment by shiki** [comment]
@hichamboushaba Would you mind double-checking what I wrote here? Is it iOS or Android that's wrong? Did I explain it correctly? 😅

**Comment by hichamboushaba** [comment]
@shiki you are right, it's a bug in iOS, and I already reported it last month https://github.com/woocommerce/woocommerce-ios/issues/3934

**Comment by shiki** [comment]
And I should have searched lol. Sorry! Thank you very much, Hicham!

Closing this in favor of #3934.
