### ISSUE TITLE
[Mobile Payments] [Receipts] Store contact details

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#4167]
Stripe receipts contain a section with the store contact details (email and phone number). 

Is there a way we can get that information?

**Comment by ctarda** [comment]
@allendav do you know if this is something that could eventually be available for us as part of the WCPayAccount object?

**Comment by allendav** [comment]
Yes

https://stripe.com/docs/api/accounts/object#account_object-business_profile-support_address

https://stripe.com/docs/api/accounts/object#account_object-business_profile-support_email

https://stripe.com/docs/api/accounts/object#account_object-business_profile-support_phone

Edit: We should test this on a WCPay account of course to see what is returned. It is possible these fields are NOT set by our integration yet.

**Comment by allendav** [comment]
Yeah, mine is mostly empty, but this is something we could add to the backend someday:

```
{
  "id": "acct_REDACTED",
  "object": "account",
  "business_profile": {
    "mcc": "5734",
    "name": null,
    "support_address": null,
    "support_email": null,
    "support_phone": "+10000000000",
    "support_url": null,
    "url": "staging.marsiswaiting.com"
  },
...
```
