### ISSUE TITLE
Building the app on M1

### ISSUE THREAD

**Issue by PiotrCzapla** [woocommerce/woocommerce-ios#4171]
**Describe the bug**
I'm not able to build the app on M1, after following the readme, and installing all dependencies I'm getting  one compilation error:
<unknown>:0: error: could not find module 'CocoaLumberjack' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator

**To Reproduce**
Follow your readme on M1 mac. 

You will encounter issues with installing ruby via rbenv. 
To solve the problem use rosetta emulation for homebrew, then 
brew install rbenv readline libyaml openssl
Then the `rbenv install `should be able to compile required ruby version.

Then run:
```
gem install bundler:2.2.15
bundle exec rake dependencies 
```
The required libraries are installed

Open xcode and compile the code (change the wordpress app credential), compile again and observe the issue.

<img width="1512" alt="Screenshot 2021-05-12 at 00 05 50" src="https://user-images.githubusercontent.com/340180/117890673-ed00a800-b2b5-11eb-8351-2d02a29fe222.png">

I'm trying to diagnose an Issue with the app that we have on our production website where the app is able to connect to the woo comerce and fetch data but it can't change anything as all request fails with code 400.

**Comment by PiotrCzapla** [comment]
I really need to diagnose the issue we have with the woocommerce app. I'm going to be fine doing so once I have the build process sorted. It was ages since I last touched xcode and your build process isn't too clear to me. Is there a chance that x86 ruby caused the library to be x86?

**Comment by PiotrCzapla** [comment]
I've got a workaround from support.  Install 'bundle update ffi ethon' (most likely to fix rbenv install that fails on arm), Run XCode in rosseta emulation, follow the readme and it did work for me.

**Comment by mokagio** [comment]
I'm going to close this. The app now builds successfully on M1 machines:

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/1218433/177905961-b109a233-c059-45b3-a6b1-b8655a72ec3b.png">
