### ISSUE TITLE
[Mobile Payments] Testing guide

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#4173]
Write a testing guide similar to this:

https://woomobilep2.wordpress.com/2020/10/19/shipping-labels-m1-testing-guide/

The goal is to provide a step by step guide for testers to:
* setup a store and WCPay
* setup an account with Stripe
* a walkthrough of the feature. How it is meant to work, how it can be tested

**Comment by allendav** [comment]
Draft is under review

**Comment by allendav** [comment]
p91TBi-5eh-p2
