### ISSUE TITLE
[Mobile Payments] Card Reader Settings V2 overlay borders visible during presentation

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#4175]
I was trying out the new card reader settings and I noticed the transparent dark overlay that's added behind the modal visibly slides from the bottom instead of fading in.

Recorded an example on the simulator with Slow Animations enabled:

![modal-overlay-visible](https://user-images.githubusercontent.com/8739/117953344-397bd000-b316-11eb-9074-7e3478e90fa6.gif)

**Comment by allendav** [comment]
Yup! I think @ctarda did it on purpose?

**Comment by ctarda** [comment]
I'll log a ticket for this

**Comment by ctarda** [comment]
Moving this one to the Beta 1 column
