### ISSUE TITLE
[Mobile Payments] Card Reader Settings V2 modal text doesn't fit in available size

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#4176]
Testing the new reader settings screen on an iPhone 12 simulator, the text on the modal when scanning for a reader doesn't fit in the available space.

![Simulator Screen Shot - iPhone 12 - 2021-05-12 at 11 38 04](https://user-images.githubusercontent.com/8739/117953816-b3ac5480-b316-11eb-84c2-a6ecff869dff.png)

With the phone in landscape, there's even less content visible:

![Simulator Screen Shot - iPhone 12 - 2021-05-12 at 11 38 06](https://user-images.githubusercontent.com/8739/117953878-c2930700-b316-11eb-9378-086fde465932.png)

**Comment by ctarda** [comment]
This one should be an easy fix: change the numberOfLines property of that label to 0
