### ISSUE TITLE
[Mobile Payments] Cancel payment

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#4191]
We do not have a way to cancel a payment once the process to capture a payment starts.

We need support for this on the UI.

A "Cancel" button in the first modal, the one that reads "preparing..." to cancel payment, and maybe in the one that reads "insert, tap or swipe card"

**Comment by allendav** [comment]
FWIW, so long as we cancel before we call `Terminal.shared.processPayment`, the buyer will not have an authorization placed on their card. See https://stripe.com/docs/terminal/payments#process-payment

**Comment by designsimply** [comment]
@ctarda I'm closing this issue because it looks like you solved it with a few PRs on May 14. Please re-open if needed though!
