### ISSUE TITLE
Unable to refresh list when using iThemes Security Plugin

### ISSUE THREAD

**Issue by christianswanepoel** [woocommerce/woocommerce-ios#4200]
I have seen a couple of people mentioning this and thought I send my findings.

### Wordpress app error: Unable to refresh list
This happens (for me at least) whenever the iThemes Security plugin is active despite  XML-RPC set to ENABLE.

The fix is to untick "System Tweaks" > "Filter Long URL Strings"

**Comment by shiki** [comment]
Hi, @christianswanepoel! Just to clarify, does the error start with “Wordpress app error:”? When does it happen?

**Comment by christianswanepoel** [comment]
See screenshot. 

<img src="https://user-images.githubusercontent.com/7249713/118295037-b015fa80-b4db-11eb-8327-108177f1cf7d.jpeg" width="300">

**Comment by shiki** [comment]
Thank you!

**Comment by rachelmcr** [comment]
This should be improved with the new error banners introduced in #4407, planned for release in 7.0. @shiki do you think there's more to do here beyond that?

**Comment by shiki** [comment]
We're definitely in a good place after that PR. Thanks for raising this.
