### ISSUE TITLE
[Mobile Payments] More meaningful descriptions for payment intents

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4206]
Right now we create payment intents with `description` set to

`Receipt from {Name of Store}`

This appears in receipts from Stripe as:

<img width="333" alt="receipt" src="https://user-images.githubusercontent.com/1595739/118319336-74fdd200-b4af-11eb-9e21-a5262b65cf52.png">

And appears in our internal dashboard as:

<img width="700" alt="receipt-from" src="https://user-images.githubusercontent.com/1595739/118319353-79c28600-b4af-11eb-95eb-cf2804c7bbf3.png">

It would be better to have this say something like

`Online payment for order 4567 for {Name of Store}`

See also related issue for web payments at https://github.com/Automattic/woocommerce-payments/issues/1807

**Comment by allendav** [comment]
@malinajirka we should consider this for Android as well - cc @ctarda

**Comment by ctarda** [comment]
This is an easy fix. The string is declared in PaymentCaptureOrchestrator, the method `receiptDescription()`
