### ISSUE TITLE
[Mobile Payments] Connecting a reader from payments leaves the app in an odd state and sometimes crashes

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#4224]
I'm not sure how to explain what's going on, but I recorded a video. When you connect to a reader directly from an Order details, there are a few issues:

1. The list of connected readers with the option to disconnect is briefly visible after connecting, before the modal is dismissed [00:16, 00:48]. Possibly related to #4220 
2. When you go to settings and tap on Disconnect, a new modal (Connect your card reader) is presented, on top of an identical one [00:26] . The button in the presented one does nothing [00:28]. When you dismiss it, the one underneath is functional [00:30]. However, on the first run, connecting to a reader crashed the app.
3.  On the second run, I didn't press the connect button on the presented modal and dismissed it immediately. This didn't crash the app. However, it immediately presented the modal to collect payment [01:03], even though I was in the app settings screen.

https://user-images.githubusercontent.com/8739/118800816-9d674100-b8a0-11eb-988f-c52c7d974db5.mp4

**Comment by ctarda** [comment]
This looks like OrderDetailsViewModel might be receiving a new value via the connectedReaders publisher when disconnecting from a reader.

**Comment by koke** [comment]
Some new findings:

1. It seems like this only happens if the reader has been connected before. If you try to connect from payments from a fresh launch, things work ok.
2. If you go to settings first, then connect/disconnect from there, then go to payments, it also works, although the disconnect screen is briefly visible before payment.
3. If you go directly to payments, connect a reader from there and complete payment, then go to settings and disconnect, when you go back to another order and connect while capturing payment it shows the error. It looks like the underlying error is `busy`. I'd say that we're trying to start the capture from the `connect` completion, but I don't know how that's a problem here and not the previous cases. After this, I tried to disconnect the reader from settings, but got this error:
```
Error Domain=com.stripe-terminal Code=1000 "Could not execute disconnectReader because the SDK is busy with another command: collectPaymentMethod."
```
4. If you go directly to payments, connect a reader from there and cancel payment, then go to settings and disconnect, then you get that extra connection modal on settings. If I dismiss it and go back to the order and connect a reader from there I get a `busy` error again. 
5. If you tap Disconnect once on that extra modal, when you go back to the order and connect from there, you get the crash because `CardPresentPaymentsModalViewController` is trying to update its view model, but all the `IBOutlet`s are `nil`:
![Screen Shot 2021-05-24 at 17 37 10](https://user-images.githubusercontent.com/8739/119373287-88cbe400-bcb8-11eb-81b5-1731936eb402.png)

**Comment by koke** [comment]
I think I found at least part of the cause. The method `OrderDetailsViewController.collectPayment` dispatches an `isReadyToCollectPayment` action and starts listening for changes, but since there is no `cancelable` involved, it never stops listening. This causes two issues:

1. Every time a reader connects or disconnects, the callback is called. So if you disconnect from settings, it's this VC that's trying to present the Connect Reader modal.
2. Every time you tap Collect Payment, a new subscription is set up, so every time a reader is connected or disconnected, the completion block gets called multiple times.

Another way to reproduce this:

1. Go to an order, tap on Collect Payment, tap on Connect Card Reader when prompted
2. Turn on your reader and tap Connect to Reader when it appears. Now the callback tries to continue with payment. Tap cancel.
3. Power off your reader. The Connection modal appears even though you're not trying to collect payment.
4. Dismiss the modal
5. Tap on collect payment, turn on the reader, and connect to it
6. The completion block gets called twice, which sends two `collectPayment` actions, which shows the payment failed error.
7. If you repeat 3-5 one more time, that's when `CardPresentPaymentsModalViewController` crashes because somehow all its `@IBOutlet`s are `nil`.

**Comment by ctarda** [comment]
Good catch. I shouldn't have relied on a publisher to check the connection status.

Just dropping a possible ways forward:

* SCPTerminal exposes a [connectionStatus](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPTerminal.html#/c:objc(cs)SCPTerminal(py)connectionStatus). 
* We already declare a CardReaderServiceDiscoveryStatus but I think we don't use it a this point. We could map the connection status to CardReaderServiceDiscoveryStatus (adding one ore case for `connected`)
* We could expose a property in the CardReaderService that returns CardReaderServiceDiscoveryStatus. `isReadyToCollectPayment` consumes that property.

That would also help fix another issue when the connection UI shows up after disconnecting in settings
