### ISSUE TITLE
MediaTypeTests tests fail on iOS 14.5

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#4243]
When running the test suite in Xcode 12.5, the following tests fail:

> Yosemite/YosemiteTests/Tools/Media/MediaTypeTests.swift:98: error: -[YosemiteTests.MediaTypeTests testInitWithOtherMimeType] : XCTAssertEqual failed: ("video") is not equal to ("other") - Unexpected media type for file extension: video/webm
> Yosemite/YosemiteTests/Tools/Media/MediaTypeTests.swift:98: error: -[YosemiteTests.MediaTypeTests testInitWithOtherMimeType] : XCTAssertEqual failed: ("video") is not equal to ("other") - Unexpected media type for file extension: audio/webm

Apparently, WebM is now supported on iOS 14.5.

Updating the tests is easy, but I'm not sure if we were checking for WebM for a specific reason, or just as an example of an unsupported type.

**Comment by pmusolino** [comment]
I'm closing this issue since it was fixed here https://github.com/woocommerce/woocommerce-ios/pull/4459
