### ISSUE TITLE
[Mobile Payments] Text on Right Edge of First? Receipt Cut Off

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4265]
Not sure if this can be prevented

Not sure if this only happens for the first receipt printed after selecting a printer for the first time

p91TBi-5cf

<img width="852" alt="cutoff" src="https://user-images.githubusercontent.com/1595739/119405740-9a03f900-bc96-11eb-8b11-aa243a0e8970.png">

**Comment by koke** [comment]
What I experienced on the simulator is that for some reason the first print seems to render using the paper size of the previously used printer. If you print on regular paper after printing a receipt it's also scaled wrong. So far I haven't found why that might be.

**Comment by ctarda** [comment]
@allendav I do not have a printer, would you mind running a quick test to validate if this is still happening?

**Comment by allendav** [comment]
It is still happening and has a worse outcome now. It printed meters and meters of paper for the receipt.

Here is the preview where you can see the improper formatting:

![cutoff](https://user-images.githubusercontent.com/1595739/143909831-9e5e5ffb-59e1-4f32-8469-5dc6eaadeaad.png)

Here's the meters and meters of paper with the receipt roughly in the middle:

<img width="723" alt="Screen Shot 2021-11-29 at 8 55 36 AM" src="https://user-images.githubusercontent.com/1595739/143910038-32860c60-ec9d-4d51-9866-5a88bc298c22.png">

And then attempting a second print from that same window crashed:

```
2021-11-29 08:50:07.899933-0800 WooCommerce[4416:3462292] -[PKPrinter _internalPrinter]: unrecognized selector sent to instance 0x2812fd180
2021-11-29 08:50:07.904207-0800 WooCommerce[4416:3462292] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PKPrinter _internalPrinter]: unrecognized selector sent to instance 0x2812fd180'
*** First throw call stack:
(0x18164604c 0x199cbaf54 0x181723014 0x1815db474 0x1815da5b0 0x18494ff00 0x18494bf44 0x18497c9d4 0x184977e3c 0x1849829f8 0x184977d68 0x107ecf984 0x107ed00ac 0x10b98830c 0x10b983bec 0x10ba99a28 0x10b96c5a8 0x10b96bda0 0x102588bb0 0x102588cfc 0x102c1a8d0 0x102c1c2d8 0x1028118c0 0x102bb370c 0x10270a070 0x10270a0ac 0x183f1bbf0 0x105910760 0x1841fab80 0x1841e4880 0x1841e4730 0x183f1bbf0 0x105910760 0x184047a4c 0x183dc32c8 0x183dc3318 0x1840f27c0 0x183bb7d40 0x1815ee560 0x1815bd844 0x1815b88dc 0x1815cc3b8 0x19cf5c38c 0x183f6c6a8 0x183ceb7f4 0x1028a6dc0 0x104931a24)
libc++abi: terminating with uncaught exception of type NSException
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PKPrinter _internalPrinter]: unrecognized selector sent to instance 0x2812fd180'
terminating with uncaught exception of type NSException
```

**Comment by ctarda** [comment]
Oh boy

**Comment by allendav** [comment]
Noteworthy: If you cancel the print and tap on the printer again, the printer gives you an idea of what's about to happen. Not sure we can actually print to the Brother right now:

<img width="1353" alt="Screen Shot 2021-11-29 at 9 01 34 AM" src="https://user-images.githubusercontent.com/1595739/143910961-2b5d3f4b-fd10-4c44-8fab-5621d8b267d2.png">
