### ISSUE TITLE
Plugins: Sync plugins from system_status

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#4278]
## Context

Plugin list synchronization was introduced in https://github.com/woocommerce/woocommerce-ios/issues/3921. However, that is only accessible for admin users.

## Requirement

We have the need of fetching the store plugin list from an endpoint that is accessible for all roles. 
`wc/v3/system_status` so we can determine which plugins are installed before presenting certain features, like "Present Card Payments"

## Extra

-  Provide a way to check if a plugin is installed or not.

## Considerations

- Don't delete the current plugin work made on https://github.com/woocommerce/woocommerce-ios/issues/3921 as that is still required for managing plugins as an admin.

## Breakdown

- [x] https://github.com/woocommerce/woocommerce-ios/issues/4604
- [x] https://github.com/woocommerce/woocommerce-ios/issues/4605
- [x] https://github.com/woocommerce/woocommerce-ios/issues/4606
- [x] https://github.com/woocommerce/woocommerce-ios/issues/4607

**Comment by fernandofgfer** [comment]
Thanks, @Ecarrion solving my doubts by Slack.
I think we can split this issue into these smaller:

1. Storage layer:
- Add a new model
- Add migration test.
- Update Storage readme
- Add model to Network Layer
2. Yosemite Layer:
- Add Action
- Add Remote
- Add Mapper
- Add Storage
3. Recover plugins in plugin screen:
- Move sync site plugin to plugin screen
- Recover system plugins in plugin screen
4. Extra - Check plugins to enable features:
- Create component.
- Make an example with "Present Card Payments" feature.

Could you help me to create the issues, please? 
Thanks 😄

**Comment by Ecarrion** [comment]
@fernandofgfer I have created the new issues and have linked them into the main issue description.
If you add a comment on them I could set you as the assignee!
