### ISSUE TITLE
Product Details: make categories and tags screens use a consistent loading indicator

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#4294]
Steps to reproduce:

1. Switch to a store that has many categories.
1. Open any product for editing.
1. Tap the Categories option and check for a loading indicator.
1. Repeat the same steps for Tags.

**Result:** the categories screen doesn't display a proper loading indicator. (<a href="https://user-images.githubusercontent.com/1119271/119735882-374b6280-be3a-11eb-99f8-180ddaaa09fe.mp4">53s</a>) 

Categories loading|Tags loading
---|---
<img src="https://user-images.githubusercontent.com/1119271/119736026-6366e380-be3a-11eb-821c-c78c2a219342.png" width="270" alt="image">|<img src="https://user-images.githubusercontent.com/1119271/119736062-6bbf1e80-be3a-11eb-932d-732058d5ba7e.png" width="270" alt="image">

<sup>Tested with WCiOS 6.7.0.0 TestFlight beta on iPhone 6S iOS 14.6.</sup>

<sup>(internal reference: p5T066-2iC-p2#comment-8430 /ht @elibud)</sup>

**Comment by Ecarrion** [comment]
I think both should have the ghost loading screen. Opinions @woocommerce/mobile-designers?

**Comment by Garance91540** [comment]
Yep ghost loading screen is fine!

**Comment by designsimply** [comment]
Ace. I removed the `needs: design` label with the assumption tags can be updated to use the same ghost loading image categories is currently using. 👍
