### ISSUE TITLE
Reviews: checkmark at top-right used to mark all reviews as read can be confusing

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#4295]
Steps to reproduce:

1. Switch to a store with no reviews.
1. Go to the Reviews screen.
1. Look for a checkmark at top-right and try to determine what it's for.
1. Switch to a store with at least one review.
1. Go to the Reviews screen.
1. Look for a checkmark at top-right and try to determine what it's for.

**Result:** the checkmark at top right is intended to mark all reviews as read, but it's a bit hard to figure that out if the store has no reviews or if the reviews have already been marked as read. 

No results view|Faded checkmark (all items already marked as read)
---|---
<img src="https://user-images.githubusercontent.com/1119271/119737115-00764c00-be3c-11eb-9ffa-a80f16a4acf0.PNG" width="270" alt="IMG_4167">|<img src="https://user-images.githubusercontent.com/1119271/119737108-feac8880-be3b-11eb-89f0-8e4f45dd65bd.PNG" width="270" alt="IMG_4166">

<sup>Tested with WCiOS 6.7.0.0 TestFlight beta on iPhone 6S iOS 14.6.</sup>

<sup>(internal reference: p5T066-2iC-p2#comment-8430 /ht @elibud)</sup>

Would it make sense to remove the checkmark from the no-results screen?

**Comment by Ecarrion** [comment]
I think we could do that, agree @woocommerce/mobile-designers?

**Comment by Garance91540** [comment]
Yes I always thought that checkmark was weird, we can definitely remove it

**Comment by pmusolino** [comment]
Are we sure we want to remove the checkmark? I mean, maybe we can leave it, since it's useful functionality for big stores, and display an alert showing that they are marking all the reviews as read. In this way, we prevent a user from inadvertently pressing that button, and we explain to the user what action they are taking. What do you think? @Garance91540 @adamzelinski

**Comment by ghost** [comment]
Hey, @pmusolino @designsimply I'm happy to remove the checkmark too as it seems a little weird to me. However, I understand it could be good for bigger stores. One option I came up with is to just change the icon to our more icon '...' and when tapping that it will bring up a mark all orders as read option.

What do you think of something like this?

<img width="1669" alt="Screen Shot 2021-07-28 at 4 13 12 pm" src="https://user-images.githubusercontent.com/74938219/127273112-24fd269a-7d21-4ce5-a2ad-8c06d78b0d46.png">

**Comment by pmusolino** [comment]
It seems more clear to me! Thanks for working on this @adamzelinski 🙌

**Comment by pmusolino** [comment]
I noticed that the top right button is not present on Android. Is it a missing feature or we should align the iOS behavior?

**Comment by ghost** [comment]
> I noticed that the top right button is not present on Android. Is it a missing feature or we should align the iOS behavior?

Interesting.. it looks like the Android designs show it so maybe it was missed. I think we should align to the iOS behavior

**Comment by Garance91540** [comment]
pinging @anitaa1990 here to put that on the Android's team radar!

**Comment by anitaa1990** [comment]
Hey folks! Thanks for the ping! On android, we don't display the checkmark icon at the top right corner unless there is atleast one unread review in the list. But we want to change that now and display a menu bar all the time? And clicking on it will open a menu, asking the users to mark all the reviews as read? What happens if there are no reviews to mark as read? cc @adamzelinski @pmusolino ?

**Comment by pmusolino** [comment]
@anitaa1990 on iOS we disable the button if there are no reviews that should be marked as read. 👍

**Comment by ghost** [comment]
@anitaa1990 @pmusolino yes, I'd personally have the icon hidden unless there is at least one unread review in the list.

**Comment by itsmeichigo** [comment]
Holding this issue for the next trial.

**Comment by itsmeichigo** [comment]
Assigning this issue to @selanthiraiyan  for the trial.
