### ISSUE TITLE
Product Details: consider adding caching for the categories screen

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#4296]
Steps to reproduce:

1. Switch to a store that has many categories.
1. Open any product for editing.
1. Tap the Categories option and observe how long it takes to load.
1. Go back one screen.
1. Tap the Categories option again and observe how long it takes to load. 

**Result:** in my test, it took about 2 seconds to load both the categories and the tags screens while editing a product while on a 17Mbps connection. Note: I tested using a store with 42 categories and 16 tags. (<a href="https://user-images.githubusercontent.com/1119271/119736537-16374180-be3b-11eb-9f77-12fe840dda10.mp4">56s</a>)

Categories|Tags
---|---
<img src="https://user-images.githubusercontent.com/1119271/119736631-3ff06880-be3b-11eb-84b0-3621684fff1e.png" width="270" alt="image">|<img src="https://user-images.githubusercontent.com/1119271/119736698-5991b000-be3b-11eb-928c-a7f52a8629c4.png" width="270" alt="image">

<sup>Tested with WCiOS 6.7.0.0 TestFlight beta on iPhone 6S iOS 14.6.</sup>

<sup>(internal reference: p5T066-2iC-p2#comment-8430 /ht @elibud)</sup>

**Comment by Ecarrion** [comment]
Hi @designsimply. It's not a common pattern for our app to show cached content while a screen that needs from the latest content syncs.
 
Maybe we could check if the server HTTP cache is not working correctly because the request takes approx 2s each time.

**Comment by designsimply** [comment]
My vote would be to find any creative way to make this screen load faster, or feel faster. Checking HTTP cache could work! Another idea, load the N most-used or most-recent items with an option to tap to see more or to load a paginated list (for cases where users have hundreds or thousands of categories and/or tags). Think like a user—what do you want to see MOST on that screen and how quickly do you want to see it appear?

In terms of screens that need the latest content syncs, I would definitely put orders and products in that category but I wouldn't necessarily put categories and tags that way and, as a user, would be ok to have to refresh to get the latest info on categories and tags screens. 

Aside: I consider this a not-urgent request with a note that it did come up in beta testing and anything we can ever do to improve performance for our users is good to update when we have time for doing so. ❤️
