### ISSUE TITLE
[Mobile payments] [UI] Update instructions to connect to a reader

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#4361]
Brought up during the review of #4331. https://github.com/woocommerce/woocommerce-ios/pull/4331#issuecomment-853989884

<img width="712" alt="120666304-c38a0500-c48c-11eb-9981-8445eafb50c7" src="https://user-images.githubusercontent.com/2722505/120691447-77cb6180-c474-11eb-9b95-4ebcd1a2a7b4.png">

The comments in red would be what we should try really hard to get into beta 1. The rest can wait, but since we are at it...

**Comment by koke** [comment]
Putting this back in the To Do column, as the remaining items will be implemented better after #4449
