### ISSUE TITLE
Errors: Modal message for errors on site picker screen

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#4383]
**Context:** We should really reconsider our error states, providing more specific errors, an info button to help guide resolution on common errors, and provide easy direction to a support ticket

**Design:** Instead of the existing notice, we can display it in a modal:

![image](https://user-images.githubusercontent.com/8658164/121000725-72c32680-c782-11eb-8888-f2f21f17e0f3.png)

Whenever users select “Troubleshoot” in the error message, they’ll load a page on WC docs with a list of things they could try out before reaching out to support.

Internal ref: p91TBi-3Ao-p2#comment-2101

Task:
- [x] Build UI https://github.com/woocommerce/woocommerce-ios/pull/4993
- [x] Connect Troubleshoot https://github.com/woocommerce/woocommerce-ios/pull/4994
- [x] Connect Contact support https://github.com/woocommerce/woocommerce-ios/pull/4994
- [x] Present & dismiss Modal #5006 
- [x] Handle Accessibility and rotation #5009

**Comment by Ecarrion** [comment]
Hi @designsimply, do you know would be a good website to send the users once they press the "Troubleshooting Tips" button?

We currently have [this in the app](https://docs.woocommerce.com/document/android-ios-apps-troubleshooting-error-fetching-orders/) but it is related to fetching data once you have selected a store.
