### ISSUE TITLE
Errors: Offline mode banner

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#4384]
**Context:** We should really reconsider our error states, providing more specific errors, an info button to help guide resolution on common errors, and provide easy direction to a support ticket

**Design:** The “Unable to load content”/”Unable to fetch list” error message could also be triggered by the fact that the app isn’t connected to internet. In that case, we should clearly display that the device is offline, like we do on Android with the “Offline – using cached data” banner:

![image](https://user-images.githubusercontent.com/8658164/121001245-039a0200-c783-11eb-8066-5efcfd077a2f.png)

Internal ref: p91TBi-3Ao-p2#comment-2101

**Comment by itsmeichigo** [comment]
Task checklist:
- [ ] Add new service to check connectivity.
- [ ] Add new banner view for offline status.
- [ ] Extend UIViewController to reuse logic for connectivity check.
- [ ] Apply connectivity check for all screens that require network and contain cached data:
  - [ ] My Store
  - [ ] Order list
  - [ ] Order details
  - [ ] Shipping Label purchase flow
  - [ ] Product list
  - [ ] Product forms
  - [ ] Review list
  - [ ] Review details
