### ISSUE TITLE
[Mobile Payments] Test collecting payments as a shop manager and as a connected user that is NOT the primary jetpack user.

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#4399]
As mentioned in p91TBi-5ig-p2

**Comment by allendav** [comment]
Tested on my staging site. I created a new user, shop_manager_dave, with role Shop Manager and connected that user to a WordPress.com user that was NOT the primary Jetpack user/owner for the site.

I installed the app from today's develop on an iPhone and logged into WordPress.com as that user. I immediately saw my staging site as my only option in the app.

I used an incognito window to create a guest checkout of an item and was then able to collect the payment on the app.

<img src="https://user-images.githubusercontent.com/1595739/122124882-bbaf5680-cde4-11eb-8992-1dee59bc8de7.PNG" width=50% />
