### ISSUE TITLE
Order Details → Variations With Different Attributes are Combined Together 

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#4412]
**Describe the bug**
When a customer orders multiple items of a variable product but with different attributes, the app only displays that variation once in the Order Details.

This basically makes the merchant unable to fulfill the order properly. 

- Same Android issue: https://github.com/woocommerce/woocommerce-android/issues/3811
- PR in Android: https://github.com/woocommerce/woocommerce-android/pull/4193
- Android discussion: p1623648152420100-slack-C6H8C3G23

**To Reproduce**

1. Create a variable product. 
2. Add “Color” as an attribute with “Blue|Green|Yellow” as the values. 
3. Create a **single** variation of that variable product. Choose “Any” as the attribute option. 
4. Create a single order for the product. 
  - Add 1 Blue
  - Add 2 Green
  - Add 5 Yellow
5. Check out and submit the order. 
6. In the app, view the order. You'll notice that the order details only shows one line of the product, with `8` as the quantity. And the attribute looks like the first color that you picked (e.g. Blue). 

**Screenshots**

This is the order in WCAdmin: 

![image](https://user-images.githubusercontent.com/198826/121926934-ba562f00-ccfb-11eb-846f-87fe2c962f1f.png)

This is what is shown in the app (`develop` 431b134b8). 

<img src="https://user-images.githubusercontent.com/198826/121927172-fd180700-ccfb-11eb-8a4d-8bec4952a710.png" width="300">

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Simulator
- iOS version: 14.4
- WooCommerce iOS version: `develop` 431b134b8

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by Ecarrion** [comment]
Hi @shiki, thanks for reporting this. 

I'm tracking this issue in https://github.com/woocommerce/woocommerce-ios/issues/4126 but it is currently blocked until we separate the packages bought section from the items ordered section, which should be worked in the Shipping Label M4 milestone. p91TBi-566#comment-4510

@pmusolino could you confirm that this is still the plan?

**Comment by pmusolino** [comment]
I'm trying to prioritize that task into this sprint @Ecarrion 👍
