### ISSUE TITLE
[Mobile Payments] Only show collect payment button for orders with supported currencies

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4425]
Probably not needed for MVP, but as we expand to other countries, especially those used to processing payment from international buyers (I'm thinking businesses near borders, or in international airports, or conferences with international appeal perhaps?), we may run into this.

WooCommerce allows orders to have a different currency than the store itself.

We should be using the `PaymentGatewayAccount` `supportedCurrencies` array to determine whether or not to show the "Collect Payment" button on an order.

https://github.com/woocommerce/woocommerce-ios/blob/beaf197f6a326020cf83a747d53e989f2d862ae4/Networking/Networking/Model/PaymentGatewayAccount.swift#L25

This may be an extreme edge case. Not sure.

**Comment by ctarda** [comment]
This was solved a few weeks back.
