### ISSUE TITLE
[Mobile Payments] Connect to Reader hangs if live site is in test mode

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4428]
We shouldn't even allow the merchant to attempt to connect to a reader for live sites in test mode. Stripe doesn't support it.

I thought I had written this up before, but I can't find an issue for it. Feel free to close this issue if that's not the case.

cc @ctarda

**Comment by ctarda** [comment]
How can we prevent the merchant from connecting to a reader if the site is in test mode?

**Comment by allendav** [comment]
> How can we prevent the merchant from connecting to a reader if the site is in test mode?

We should be able to tell a site is live from the `is_live` boolean in the account response.

I wish we had `test_mode` in the account response, but it doesn't look like it. So... we have a few options:
1) Add test_mode to the account response
2) Extend the PaymentGateway model to parse `test_mode` (downside: most but not all gateways have the test mode concept and some may use a different key)
3) Fetch the connection token and then examine `test_mode` in its response

I am inclined to do the second option since it should be valuable down the road to have this data to work with for payment gateways besides than just WCPay

Edit: But for velocities sake we could do #3 faster and then do #2 later

Related: https://github.com/Automattic/woocommerce-payments/blob/80327e2c43aa838ca692b1c074d0e34348f198b2/includes/admin/class-wc-rest-payments-connection-tokens-controller.php#L45-L49

**Comment by ctarda** [comment]
The previous ticket referred to might be #4515

**Comment by allendav** [comment]
Looks like the backend may have the groundwork in place now. The wc/v3/payments/accounts endpoint returns is_live and test_mode with the expected values for my live and my test site as I toggle them in and out of test mode. Props @kalessil https://github.com/Automattic/woocommerce-payments/blame/6eaca4f05faa07acd0392a32ac1b1af051f93ca3/includes/admin/class-wc-rest-payments-accounts-controller.php#L73

In since 2.9.0 released on Aug 25
