### ISSUE TITLE
[Mobile Payments] No prompt to remove chip card after payment collected

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4430]
I was not prompted to remove my card after completing a card-present payment with a chip card. I expected to have been.

cc @ctarda

**Comment by designsimply** [comment]
In WCiOS 7.1 beta testing, the opposite problem was reported: 

> I started the payment flow for an open order, and at first it worked fine. But when the payment was collected I see the message “Please remove card,” which doesn’t make sense when the card was simply tapped on the reader rather than inserted into it.

<sup>(internal reference: p5T066-2uU-p2#comment-9160 /hat tip @nbradbury, tested with WCiOS 7.1.0.0 on an iPad running iPadOS 14.6)</sup>

I tested and confirmed:

<img height="420" alt="Screen Shot 2021-07-19 at Jul 19 2 29 32 PM" src="https://user-images.githubusercontent.com/1119271/126223496-e97b0e2e-fe1d-467e-ab6a-d462a9e086ed.png">
<sup>Tested with WCiOS 7.1.0.1 TestFlight beta on iPad Mini 4 (WiFi) (iPad5,1) iPadOS 14.6 logged in as testuser01121 with worthwhile-seahorse.jurassic.ninja selected and running WP 5.7.2 JP 9.9 WC 5.5.1 WCPay 2.7.0 WCS staging 1.0.</sup>

**Comment by koke** [comment]
Testing the 2.0 SDK feature branch, it seems a bit different but still not working right:
- When tapping, I see "Please remove card" until it starts processing the payment
- When inserting, I see "Please remove card" for a split second, then it goes back to "Reader is ready" until it starts processing payment

https://user-images.githubusercontent.com/8739/136402126-0c174532-d55b-4b30-b341-5880ea0fc75a.mov

**Comment by allendav** [comment]
Yup. I was looking at this in detail yesterday. For chip cards we need to listen for a card inserted reader event and then keep a "remove your card" dialog on the screen until the corresponding card removed reader event and THEN show the success (or failure) to collect payment.

Working on a fix now. Thankfully SDK2 makes this simpler with the single delegate

**Comment by allendav** [comment]
Closed by #5192
