### ISSUE TITLE
[Mobile Payments] Make it easier to distinguish live from test events in tracks

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4432]
Perhaps we could name the events differently? For example, right now both live and test payments end up under `woocommerceios_card_present_collect_payment_success`

cc @ctarda @astralbodies for ideas / how have we handled this for other things (like shipping labels)

**Comment by astralbodies** [comment]
We don't differentiate them at all right now. The volume is so low, comparatively, so for any reporting purposes, it's fine if they include events from developers.

**Comment by koke** [comment]
I think the main worry here is that, at least during the beta, the developer volume won't be low compared to the volume coming from the small number of merchants

**Comment by allendav** [comment]
> I think the main worry here is that, at least during the beta, the developer volume won't be low compared to the volume coming from the small number of merchants

My concern as well
