### ISSUE TITLE
[Mobile Payments] Show tax collected, if any, on receipts

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4437]
See also #4434

**Comment by shiki** [comment]
I ran into this today. I also noticed that the receipt does not include custom fees and shipping costs. 

This is the order in WC Admin: 

![image](https://user-images.githubusercontent.com/198826/124522358-3b12c300-ddb0-11eb-90a6-257acd8343b4.png)

And this is the receipt:

<img src="https://user-images.githubusercontent.com/198826/124522368-449c2b00-ddb0-11eb-8bac-1ccca5bdfee4.png" width="300">

The custom costs were not included so Amount paid looks _off_.

**Comment by allendav** [comment]
Yeah, I think we're going to need to take care of this sooner than later.
