### ISSUE TITLE
[Mobile Payments] Replace table view in Connect to Card Reader screen with a simpler solution

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#4449]
The remaining bits in #4361 seem hard to achieve while using a table view for layout:
- The height of the button is controlled by cell size, which is calculated automatically
- Padding between the button and the text below is hard to specify explicitly
- I don't see how to bottom-align the button and text while they are table view cells

Replacing the view with either SwiftUI or UIStackView will make these improvements easier, and will likely simplify the code overall.

**Comment by joshheald** [comment]
Relates to #4548 
Should probably be done together...

**Comment by ctarda** [comment]
I am going to close this one for now. We can reopen later if needed
