### ISSUE TITLE
Variations: Updates after generate variations.

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#4452]
When we select “Generate New Variation” on the Variation list, can we:
1. show a “Variation created” snackbar too?
2. display the newly created variation first on the list? (right now it gets added at the bottom of the list)

reported by @Garance91540

**Comment by shiki** [comment]
Android issues:

- https://github.com/woocommerce/woocommerce-android/issues/4259
- https://github.com/woocommerce/woocommerce-android/issues/4260
