### ISSUE TITLE
Variation: Changes on message while saving variations

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#4453]
On the variation product page, when we make a change (ie add price), the CTA display is “Save” (which is normal), but then the loading page says “Publishing your product”. Could we update with “Saving your variation”?

reported by @Garance91540

**Comment by Ecarrion** [comment]
@Garance91540 Should I change the behavior for simple products too? The reported problem affects all types of products. I'm assuming that the "Publishing your product” message is to indicate the user that the change is being published (aka product not a draft)

**Comment by Garance91540** [comment]
ah yes, let's have that updated for all products please!
