### ISSUE TITLE
Change `Order`s statuses order to match its lifecycle

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-ios#4457]
The order of statuses is different in iOS vs Android, which might be an inconvenience for the users who use both platforms.

The preferable order is `Order`'s lifecycle-based, which currently is implemented on Android.

| iOS | Android |
| ---- | ---- |
| <img width="766" alt="Screenshot 2021-06-21 at 10 59 57" src="https://user-images.githubusercontent.com/5845095/122736014-de77ba00-d27f-11eb-9763-b88ab4ed578f.png"> | <img width="632" alt="image" src="https://user-images.githubusercontent.com/5845095/122736078-ed5e6c80-d27f-11eb-8fb2-45491dfe8960.png"> |

p1624022953324400/1624022453.321700-slack-CGPNUU63E

**Comment by Patil2099** [comment]
I would like to pick this up. Can you guide me a little @wzieba

**Comment by shiki** [comment]
@Patil2099 Sure thing! I'll assign this task to you.

Do you have any specific questions? 

You can also take a look at the various documentation that we have to help you get started: https://github.com/woocommerce/woocommerce-ios#-documentation

**Comment by Ecarrion** [comment]
I'm assigning this to a trial candidate.
