### ISSUE TITLE
Info TopBannerView text is too light against background in dark mode

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#4465]
**Describe the bug**

In dark mode, a TopBannerView with `.info` type has white text against a light green background. This makes the text hard to read.

Right now, I think this is only used on the Shipping Label Carriers and Rates screen.

**To Reproduce**

1. Put your device in dark mode.
2. Launch the app in debug mode (because of the Shipping Labels feature flag).
3. Open an order detail that is eligible for the shipping label.
4. Tap the button "Create Shipping Label".
5. Complete all the fields until you get to the "Shipping Carrier and Rates" screen. Notice the banner background color and text.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/122916817-36ccbb80-d355-11eb-8502-d75365df2117.png" width="300px">

**Expected behavior**

I believe the background green color is supposed to be darker, which would make the text legible.

**Comment by pmusolino** [comment]
@woocommerce/mobile-designers  what color should we use in this case?

**Comment by Garance91540** [comment]
Hi @pmusolino!

<img width="340" alt="Screen Shot 2021-06-23 at 4 35 22 PM" src="https://user-images.githubusercontent.com/28450084/123116265-095d3c00-d441-11eb-8882-4d85d09f90cf.png">

The orange banner should use Orange 70 (accent color Orange 30) and the green Green 80 (accent color Green 50)
