### ISSUE TITLE
Shipping Labels: If API returns no rates or errors, the Carrier and Rates screen is blank

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#4481]
**Describe the bug**

When you open the Carrier and Rates section while creating a shipping label, the API may return no rates (but also no errors):

```
{
  "data" : {
    "success" : true,
    "rates" : {
      "default_box" : {
        "default" : {
          "rates" : [

          ],
          "errors" : [

          ]
        },
        "signature_required" : {
          "rates" : [

          ],
          "errors" : [

          ]
        },
        "adult_signature_required" : {
          "rates" : [

          ],
          "errors" : [

          ]
        }
      }
    }
  }
}
```

In that case, the Carrier and Rates screen is blank instead of showing an empty state ("No shipping rates available") screen.

**To Reproduce**

1. Go to Orders in the app and open an order that meets the criteria for shipping labels.
2. Tap the "Create Shipping Label" button.
3. Go through the form until you get to Package Details. There, select a package and weight that has no available rates. (While testing, I discovered this issue after selecting `DHL Express Box #2 Medium` with a total package weight of 2 kg.)
4. Continue to the Carrier and Rates screen and notice that it is blank.

**Screenshots**

Blank screen:

<img src="https://user-images.githubusercontent.com/8658164/123426369-3d5c6c80-d5bb-11eb-97e3-1c00a485f780.png" width="300px">

**Expected behavior**

I expect to see this empty state screen:

<img src="https://user-images.githubusercontent.com/8658164/123426380-40eff380-d5bb-11eb-8c81-d52b1397f647.png" width="300px">

**Comment by pmusolino** [comment]
This was fixed here https://github.com/woocommerce/woocommerce-ios/pull/4538
