### ISSUE TITLE
Shipping Labels: Carrier and rates empty state screen text issues

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#4482]
**Describe the bug**

In the shipping label creation flow, the Carrier and Rates section has an empty state screen with a couple text issues:

1. There is a missing space where it says "weightor"
2. The text can be cut off depending on the screen and text size. I noticed the issue with default text size on an iPhone 11 Pro.

**To Reproduce**

I got to the empty state screen when I saw the issue reported in https://github.com/woocommerce/woocommerce-ios/issues/4481, which has these steps:

1. Go to Orders in the app and open an order that meets the criteria for shipping labels.
2. Tap the "Create Shipping Label" button.
3. Go through the form until you get to Package Details. There, select a package and weight that has no available rates. (While testing, I discovered this issue after selecting `DHL Express Box Orders #2 Medium` with a total package weight of 2 kg.)
4. Continue to the Carrier and Rates screen and notice that it is blank.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/123427392-7812d480-d5bc-11eb-9c0a-b6eb6ddbe7c2.png" width="300px">

**Comment by pmusolino** [comment]
`There is a missing space where it says "weightor"` this issue was already solved in our of our previous PRs 👍

**Comment by pmusolino** [comment]
I tested it on an iPhone 11 Pro @rachelmcr but I wasn't able to replicate the second issue 🤔 

<img src="https://user-images.githubusercontent.com/495617/124455192-91b8d680-dd89-11eb-9eaf-2e6980a76f9b.png" width=300 />

**Comment by rachelmcr** [comment]
> I wasn't able to replicate the second issue

Oh huh, I can't replicate it now, either! Maybe it was a glitch caused by changing the text size while I was on that screen, in which case, no worries. (I am guessing that's what it is and I just forgot that's what caused it.) Thanks for checking!
