### ISSUE TITLE
Send Feedback: loading indicator visual appearance needs improvement

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#4501]
Steps to reproduce:

1. On the device, switch to dark mode.
1. In the app, log in and go to My store > Settings (gear icon top right) > Send Feedback.

**Result:** the loading indicator's visual appearance looks off.

> This loading indicator somehow seems visually off, not sure if it’s not properly vertically centered or something else:

<img src="https://user-images.githubusercontent.com/1119271/123888990-d1a73600-d911-11eb-891b-619e51e55ed3.png" width="270" alt="image">

<sup>(internal reference: p5T066-2rI-p2#comment-8963 /hat tip @elibud)</sup>

**Comment by Ecarrion** [comment]
Hey, @woocommerce/mobile-designers! This was reported, do you have any special requirements for this update?

**Comment by Garance91540** [comment]
Hi @adamzelinski could you take this one? thanks!

**Comment by ghost** [comment]
Hey @designsimply @Ecarrion, could we please center the text and loader within the square and also just make sure the loader color is set to WooCommerce Purple 30 for dark mode. Thanks

<img width="694" alt="Screen Shot 2021-07-02 at 4 56 23 pm" src="https://user-images.githubusercontent.com/74938219/124233860-a5c8c200-db56-11eb-96e6-209d563f4d5e.png">

**Comment by fernandofgfer** [comment]
Hi @designsimply @adamzelinski! I'm Fernando and I'm going to take this issue as one of my trial program.
I've done some modifications to see how it fits, could you take a look, please?
iPhone 11
![Simulator Screen Recording - iPhone 11 Pro - 2021-07-06 at 17 30 14](https://user-images.githubusercontent.com/11411847/124628602-eab76600-de80-11eb-9c42-b2ccccf2d7e0.gif)

iPhone SE
![Simulator Screen Recording - iPhone SE (2nd generation) - 2021-07-06 at 17 35 51](https://user-images.githubusercontent.com/11411847/124628642-f73bbe80-de80-11eb-80f0-0aae710b4b8d.gif)

Related to the color, I can confirm that the app is using WooCommerce Purple 30 for dark mode color.
Thanks :smiley:
