### ISSUE TITLE
Badge counts should be 99+ for values greater than 100

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#4502]
Steps to reproduce:

1. Have a site with 99+ unread orders, products, and reviews.
1. View the badge count for each area.

**Result:** the badge count display should be consistent for each area and should show 99+ for numbers greater than 100.

> When there are more than 99 orders the text doesn’t quite fit the label, I think we should be using 99+ since that would work nicely on all languages:

<img src="https://user-images.githubusercontent.com/1119271/123890989-6d867100-d915-11eb-963b-8e55427591e8.png" width="270" alt="image">

<sup>(internal reference: p5T066-2rI-p2#comment-8963 /hat tip @elibud)</sup>

**Note:** possibly a regression of https://github.com/woocommerce/woocommerce-ios/pull/1764.

**Comment by shiki** [comment]
This isn't a regression but a translation problem. Here is the translation in Spanish: 

https://github.com/woocommerce/woocommerce-ios/blob/fc83fa9638f013457ac653774c67581471deeadc/WooCommerce/Resources/es.lproj/Localizable.strings#L149-L150

**Comment by shiki** [comment]
Asked how we can solve this in a more future-proof manner. p1625777265302800-slack-CC7L49W13

Will respond back here if I find a solution.
