### ISSUE TITLE
[Mobile Payments] Do not allow merchant to attempt to collect payment or connect a card reader for live sites in test mode

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4515]
This is a recurring source of confusion. When a live site is placed in test mode, we are unable to obtain a reader connection token from Stripe. We should not allow the merchant to even attempt to connect their reader (or show the collect payment button on a order)

**Comment by malinajirka** [comment]
We might want to consider showing an error with a hint, something like "In-Person Payments is Not Available Right Now For Your Store… because the connected Stripe account is Live but WCPay is in dev mode".

**Comment by joshheald** [comment]
Seems like this relates to/is duplicated by #4835 ... unless that's the inverse situation? @allendav I'm not totally sure.

**Comment by ctarda** [comment]
Closing as duplicated
