### ISSUE TITLE
Products List → Sort and Filter buttons should be hidden if there are no products

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#4516]
**Describe the bug**

The Sort and Filter buttons are visible even if there are no products.

**To Reproduce**

Use a site with no products and navigate to the Products list.

<img src="https://user-images.githubusercontent.com/198826/124019373-38762f00-d9a6-11eb-935a-6b7550019c0a.png" width="300">

**Expected behavior**

They should be hidden.

**Comment by fernandofgfer** [comment]
Hi @shiki!

I'm going to take this issue like one of my trial program.
Could you help me with some doubts?
- Should we hide the buttons, or the entirely white view?
- If a user adds a product, should we show the buttons again?

Thanks :blush:

**Comment by shiki** [comment]
Hi @fernandofgfer! 

> Should we hide the buttons, or the entirely white view?

Yes, the entire white view. Only the empty state below it should be shown. 

> If a user adds a product, should we show the buttons again?

That's correct. 🙂 

Thank you for working on this!

**Comment by fernandofgfer** [comment]
Thanks @shiki for solving my doubts!
I'm going to work on it! :smiley:

**Comment by fernandofgfer** [comment]
Hi @shiki!
This is my solution:
_start with one product_
https://user-images.githubusercontent.com/11411847/124625749-5ea43f00-de7e-11eb-93ed-0100542ca815.mp4

_start with 0 products_
https://user-images.githubusercontent.com/11411847/124625821-6f54b500-de7e-11eb-95f0-7448979788a0.mp4

_delete last product_
https://user-images.githubusercontent.com/11411847/124625886-7d0a3a80-de7e-11eb-993b-700705d0c9b5.mp4

_add first product_
https://user-images.githubusercontent.com/11411847/124625970-8eebdd80-de7e-11eb-9a95-5de756e58fb6.mp4

Which are your thoughts? :smiley:

**Comment by shiki** [comment]
Thanks for sending videos! This is looking good. 

> delete last product
https://user-images.githubusercontent.com/11411847/124625886-7d0a3a80-de7e-11eb-993b-700705d0c9b5.mp4

I think the empty state should be shown here. 

> start with 0 products
https://user-images.githubusercontent.com/11411847/124625821-6f54b500-de7e-11eb-95f0-7448979788a0.mp4

I also don't see the empty state here. This part should still be visible: 

<img src="https://user-images.githubusercontent.com/198826/124632194-5974cf00-de41-11eb-836f-34e7a11576f1.png" width="300">

Unless I just missed them in the video. Let me know. 😅

**Comment by fernandofgfer** [comment]
Yep, sorry, it's a video problem :confused:

**Comment by shiki** [comment]
No worries. Feel free to share the fixed videos in the PR.
