### ISSUE TITLE
[Mobile Payments] Crash when connecting readers on landscape

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#4521]
**To Reproduce**

1. Launch the app in landscape orientation on iPhone (I can't reproduce on iPad)
2. Go to Settings > Manage Card Readers
3. Tap on Connect Card Reader
4. Turn on your reader, and connect to it when prompted
5. Tap on Disconnect
6. Go back to the settings screen and enter Manage Card Readers again
7. Tap on Connect Card Reader and connect when prompted
8. 💥 

```
2021-07-01 11:06:36.950064+0200 WooCommerce[25473:8541413] *** Assertion failure in -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:], UITableView.m:15065
2021-07-01 11:06:36.953494+0200 WooCommerce[25473:8541413] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UITableView dataSource is not set'
*** First throw call stack:
(0x19522e754 0x1a9cf57a8 0x1951303f8 0x196504714 0x197e4ae58 0x197e16890 0x197e16d44 0x197e34b8c 0x19815da0c 0x1985e4670 0x1985e4b54 0x1985f978c 0x19853b5e4 0x1985677f4 0x198568b20 0x1951a75e0 0x1951a1704 0x1951a1cb0 0x1951a1360 0x1ac7df734 0x197c1c584 0x197c21df4 0x10451e3f8 0x194e5dcf8)
libc++abi: terminating with uncaught exception of type NSException
```

This only seems to happen on iPhone in landscape mode.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 14.6
- WooCommerce iOS version: Reproduced on develop and 7.0 from TestFlight

**Comment by koke** [comment]
No solution yet, but this crash is an interesting mystery. Somehow the table view on `CardReaderSettingsUnknownViewController` is getting a `layoutSubviews` call that tries to read the data source, but `CardReaderSettingsUnknownViewController` has been deallocated already (a reader is connected), and because the `dataSource` property is weak, the table view is not retaining it. So its tries to read data from a nil data source and crashes.

I've verified that the `onViewModelsPriorityChange` method in `CardReaderSettingsPresentingViewController` is called before this, which should have removed that table view from the view hierarchy, but somehow it's still getting a callback.

The fact that this stack trace starts in a `__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__` and not a specific path in our code makes me think that maybe something is requesting an asynchronous update right before we switch the child controllers, and by the time the run loop gets to it, the data source is gone. If this is the case, it might be a UIKit bug?

I still have no idea how to debug what exactly is triggering this, or why would this only happen in landscape mode.

**Comment by allendav** [comment]
Does this only happen when reconnecting? Or when connecting (as the title says)? Does it happen everytime?

I use landscape on iPad frequently and have never seen this. Maybe just an iPhone problem?

**Comment by koke** [comment]
Yes, it only happens when you connect, disconnect, leave the screen, come back and connect again. It doesn't happen if you don't leave the screen, or on iPad, or on portrait.

**Comment by koke** [comment]
I think the key detail about landscape vs portrait is whether the full contents of the table view fit in the screen. If it doesn't, it looks like the table view is trying to do layout as it's being removed from the screen, but that doesn't happen if the full contents are visible.

Another issue I found that seemed related but it's not, is that we have an initial implementation of the "Connecting to reader" modal, but it's not being used because the `CardPresentModalFoundReader` modal will dismiss itself as soon as you tap the connect button, so any change in the modals view model won't be visible after that. We might want to look into restoring and completing that screen, or removing the code for it.

![Screen Shot 2021-07-02 at 09 53 32](https://user-images.githubusercontent.com/8739/124240792-64ff8780-db1b-11eb-9313-370f2db4f797.png)
