### ISSUE TITLE
Shipping Labels: Empty Table View for States for Orders with Empty "Ship to" Address

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4525]
Observed while testing #4523 

If you create an order in wp-admin and skip providing Bill To and Ship To addresses, i.e.:

<img width="1314" alt="Screen Shot 2021-07-01 at 3 37 26 PM" src="https://user-images.githubusercontent.com/1595739/124197115-aee85f00-da82-11eb-8863-4759d3d30a61.png">

When you enter the shipping label flow in the mobile app and attempt to set the state, the table view is empty:

![stateless](https://user-images.githubusercontent.com/1595739/124197733-0cc97680-da84-11eb-882b-f14bc50ecd09.gif)

**Comment by pmusolino** [comment]
I think that this issue can be moved to M4, since in M3, when we will remove the feature flag, it will not be possible to for a user to create a shipping label if the address doesn't contain `US` as a Country. So we will not allow empty countries for the moment.
