### ISSUE TITLE
Products List → First Created Product is not Shown in the List

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#4543]
Ref p91TBi-5oi-p2#comment-5224.

**Describe the bug**

When creating a product for the first time, the product is not shown in the list. The app just shows the empty state.

**To Reproduce**

1. Use a site that has no products. 
2. Navigate to Products. 
3. Tap on the big plus button. 
4. Edit some of the product's details. 
5. Tap on the Options menu at the top right. 
6. Save the product as a draft. 
7. Navigate back to the Products List. 
8. Notice that the new product is not there.

**Screenshots**

https://user-images.githubusercontent.com/198826/124498776-24517980-dd7a-11eb-97ed-2d8db1f58653.mov

**Expected behavior**

The empty state should be cleared and the new product should be displayed instead.

**Comment by Ecarrion** [comment]
Hey @shiki, this was fixed in https://github.com/woocommerce/woocommerce-ios/pull/4563#pullrequestreview-701477336 and released in `7.2`


https://user-images.githubusercontent.com/562080/129285226-dd562e51-5eae-481b-99f5-a98bade22519.mp4

**Comment by shiki** [comment]
Yay! Thanks for checking it out.
