### ISSUE TITLE
Add “Draft” Label When Editing a Draft Product

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#4544]
Ref p91TBi-5oi-p2#comment-5224.

When editing a draft product, Android shows a “Draft” label below the product image. We should do the same for iOS. 

![image](https://user-images.githubusercontent.com/198826/124500883-c9218600-dd7d-11eb-9874-353357c9ea85.png)

**Comment by singhbaidwan** [comment]
Hi @shiki , I want to take this issue .
can you please guide me from where to start

**Comment by shiki** [comment]
Hi @singhbaidwan! Thank you for contributing. 

We have intro docs here: https://github.com/woocommerce/woocommerce-ios#-documentation

And I believe this UI is in [`ProductFormViewController`](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/ViewRelated/Products/Edit%20Product/ProductFormViewController.xib). 

Let me know if you have specific questions!

**Comment by iamgabrielma** [comment]
As there has been no update on this one for a while I've assigned myself so I can give it a go.

> And I believe this UI is in [`ProductFormViewController`](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/ViewRelated/Products/Edit%20Product/ProductFormViewController.xib).

I've been checking a way to add the label via the Interface Builder to `ProductFormViewController.xib`, however in this case this seems to be just a table view and all the cell setup and data is generated directly with code, either via the data source and/or delegate protocols:

<img width="868" alt="Screenshot 2021-08-06 at 17 19 48" src="https://user-images.githubusercontent.com/3812076/128496209-19758bb6-c48d-4cf3-a4b6-849a7d419f22.png">

Following this, I'm trying to define new cells within `ProductFormTableViewDataSource.swift` instead, which seems to output the information in the right place, however still needs some tweaking:

<img width="327" alt="Screenshot 2021-08-06 at 19 04 47" src="https://user-images.githubusercontent.com/3812076/128507819-8fc39a61-2998-4ea7-8749-b7a1bb05c763.png">


I'll submit a draft PR shortly 👌
