### ISSUE TITLE
Add "Product saved" Confirmation Message After Saving a Product

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#4545]
Ref p91TBi-5oi-p2#comment-5224.

The app correctly presents “Saving your product...” when saving a draft product. However, there is no confirmation afterward if the product was successfully saved. 

<img src="https://user-images.githubusercontent.com/198826/124512091-d138f000-dd94-11eb-835b-ba75ce127a90.png" width="300">

## Steps

1. Edit a draft product. 
2. Make some changes. 
3. Press Save. 
4. There should be a Snackbar confirmation message saying “Product saved”.

---

Related: https://github.com/woocommerce/woocommerce-android/issues/4362

**Comment by iamgabrielma** [comment]
I've tried 2 different approaches for this notice:

- The 1st one shows in the middle of the screen
- The 2nd one is more similar to the Android's "toast/snackbar" notification.

These can be seen here at the same time:

![fix-4545-showing-2-options](https://user-images.githubusercontent.com/3812076/127732386-06ee386f-b2c5-48c1-b227-078502d4a255.gif)

<img width="306" alt="fix-4545-2-options" src="https://user-images.githubusercontent.com/3812076/127732418-d0a84a45-68c4-4fe1-8350-fe57c73bc6e7.png">

I understand that we prefer to move ahead with option 2 at the moment for consistency with the Android version, right? I'll go ahead and submit a draft shortly using that option :ok_hand:

**Comment by itsmeichigo** [comment]
@iamgabrielma Thanks for looking at this issue 👍  I agree that option 2 is what we'd like to have the notice - not just for inconsistency with Android but also with the rest of the app, i.e to show confirmation of something done while not blocking any UX.

**Comment by shiki** [comment]
Thank you for responding to the question, @itsmeichigo. And getting the PR merged, @Ecarrion and @iamgabrielma! 🥳
