### ISSUE TITLE
Payments: There is a Brief Flash of the Disconnect Button When Connecting a Reader

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#4546]
When connecting a reader from the Order Details screen, I notice a brief flash of the _Disconnect_ screen. You can see it between the 5 to 7 second mark of this video:

https://user-images.githubusercontent.com/198826/124522514-c429fa00-ddb0-11eb-96e4-b2bc6197b86f.mp4

**Comment by koke** [comment]
Confirmed. I've been seeing this one, and while it's not a critical issue, it looks poorly.

**Comment by allendav** [comment]
@ctarda @Garance91540  @adamzelinski - I just moved this to the Now column in the project

Right now, if the merchant begins the collect payment flow from within the order and they are not yet connected to their reader, we push the "Connect your card reader" view onto the stack and _then_ add the "Scanning for readers" modal on top of that. As the merchant completes connecting to their reader,  the "Connect your card reader" view is briefly replaced with the Connected Reader view (with the disconnect button). This is very busy and distracting:

![disco3](https://user-images.githubusercontent.com/1595739/126568079-9467bbe4-f2d5-4b10-b521-995fc395097e.gif)

To fix this, I'm going to remove the dependency on that intermediate view and allow the connection modals to appear directly on top of the order details view.  This will eliminate the "Connect your card reader" view and the "Connected reader/disconnect" views appearing in the context of the order.  It will look more like this:

<img width="1561" alt="new" src="https://user-images.githubusercontent.com/1595739/126568844-b9e4cf22-697e-4345-a65f-4f49776c540b.png">

@ctarda @koke - here's the changes needed - I see a short series of PRs

- PR 1 - Add CardReaderConnectionController, repurposing reader discovery state and code from our existing settings view models and change OrderDetailsViewController::connectToCardReader to use it if needs to connect to a reader
- PR 2 - Change CardReaderSettingsUnknownViewController to use CardReaderConnectionController to connect to a reader and get rid of updateModal and delete reader discovery state and code from CardReaderSettingsUnknownViewModel
- PR 3 - Change CardReaderSettingsKnownViewController to use CardReaderConnectionController to connect to a reader and get rid of updateModal and delete reader discovery state and code from CardReaderSettingsKnownViewModel

CardReaderConnectionController will be invoked by ViewControllers that need it using something like the following:

```
let readerController = CardReaderConnectionController(self)
connectionController.discoverAndConnect() {
   ...
}
```

where

```
func discoverAndConnect(onCompletion: (Result<Void, Error>) -> Void)
```

which will return .success if we are able to connect to a reader and .failure if we are not or the user cancels

CardReaderConnectionController will take the ViewController (e.g. OrderDetailsViewController) as an argument and passes that to the CardReaderSettingsAlerts it needs to create (as from:)

Thoughts?

**Comment by ghost** [comment]
That's a great idea @allendav thanks for doing this.
