### ISSUE TITLE
Connect Card Reader screen - UI updates

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-ios#4548]
Hi there, 

Can we make the following alignment updates to the Connect card reader screen? Thanks!
<img width="636" alt="Screen Shot 2021-07-06 at 9 47 57 AM" src="https://user-images.githubusercontent.com/28450084/124562561-75777100-de3f-11eb-9f0f-bebdd3ca8cb9.png">

**Comment by allendav** [comment]
I am worried about the height requiring scrolling on shorter iPhones, or if text size has been increased in accessibility. Most of our other settings views are scrollable (table views). Are you sure you want to change this? It will not be a trivial fix and will likely require multiple iterations to get right.

**Comment by Garance91540** [comment]
Hi @allendav , these were the original designs, but I hear your point. Instead of making the "Connect Reader" CTA pinned to bottom, can we keep it as you have and increase vertical padding by 40px above and below the bullet point list? It will make the screen more balance and won't mess with bigger fonts

**Comment by allendav** [comment]
Thanks @Garance91540 - I missed that this was the intention in the original designs. I've added a note to myself to look more carefully next time around :)

**Comment by joshheald** [comment]
Relates to #4449 
Should probably be done together...
