### ISSUE TITLE
Error modal - UI update

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-ios#4551]
Screenshot | Design
------------ | -------------

![IMG_1059](https://user-images.githubusercontent.com/28450084/124575117-67c7e880-de4b-11eb-932f-6b27132b26d2.png) | ![Frame 636](https://user-images.githubusercontent.com/28450084/124575164-71e9e700-de4b-11eb-8aec-b4c43789494b.png)

 - With the error message, the modal was too crowded. Can we remove the price to make room for more useful content on error modals?
 - Can we replace the "No thanks" text button with a "Back to Order" secondary button? 
 - Can we update the copy of the Primary button to "Try Collecting Again"? (All the buttons on iOS are Title case) 
 - Can we update the modal sizes to match designs? 

For this specific error message I highlighted above, can we make sure to display the image. I also find the error message a bit scary and not super helpful: could we update with the error message for unknown reasons "Sorry, this payment couldn’t be processed" ?

**Comment by designsimply** [comment]
Similar feedback was given during WCiOS 7.1 beta testing where a cryptic error message appeared on the "Payment failed" modal: 

> Payment failed
> The operation couldn't be completed. (Networking .DotcomError error 0.)
> Button: Try collecting payment again
> Button: No thanks

![Networking .DotcomError error 0.](https://user-images.githubusercontent.com/1119271/126220301-8b13d755-7b53-485c-841a-2bcded9c3a9d.png)
<sup>Tested with WCiOS 7.1.0.0 on an iPad running iPadOS 14.6.</sup>

> Then the payment failed (not a problem with the app but instead with my site), but the error message (“Networking DotCom error…”) is cryptic. And when I tapped to try again, I immediately saw a screen saying “The system experienced an unexpected internal error.”

<sup>(internal reference: p5T066-2uU-p2#comment-9160 /hat tip @nbradbury)</sup>
