### ISSUE TITLE
iPad modals - UI update

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-ios#4557]
Hi there, 

I realized there were no tablet designs for the CPP projects. I added them in Figma for reference. Similarly to the mobile modals, is it possible to update the modal sizes so they are consistent across the flow?

<img width="1016" alt="Screen Shot 2021-07-06 at 2 37 40 PM" src="https://user-images.githubusercontent.com/28450084/124601226-e2066600-de67-11eb-9a61-e9d8c9df527c.png">

**Comment by designsimply** [comment]
An issue came up in WCiOS 7.1 beta testing about the title getting truncated on the Connect Reader modal:

> When a card reader is discovered, the name of reader is clipped in the dialog title [iPad only]

<img src="https://user-images.githubusercontent.com/1119271/126206490-45970a6a-6e08-4fcd-a0a0-98bfe9cbab57.png" height="420" alt="image"> 
<sup>Image source: iPad running iPadOS 14.6 from @nbradbury.</sup>

<sup>(internal reference: p5T066-2uU-p2#comment-9160 /ht @nbradbury)</sup>

I tested and confirmed this only happens on iPad.

<img src="https://user-images.githubusercontent.com/1119271/126209526-87c70fa5-0218-441a-aac2-fd0797f3a069.PNG" height="420" alt="IMG_4338 iPhone 6S"> <img src="https://user-images.githubusercontent.com/1119271/126209536-85c6b2c9-0b1a-426c-bbad-609d27659eb5.png" height="420" alt="iPad">
<sup>Tested with WCiOS 7.1.0.1 TestFlight beta on iPhone 6S iOS 14.6 (Left) and on iPadOS 14.6 (Right) logged in as testuser01121 with worthwhile-seahorse.jurassic.ninja selected and running WP 5.7.2 JP 9.9 WC 5.5.1 WCPay 2.7.0 WCS staging 1.0.</sup>
