### ISSUE TITLE
[Mobile Payments] Update user-facing error messages

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#4558]
Reduce granularity of the user facing error messages, and present only three different messages:

![iOS Light (2)](https://user-images.githubusercontent.com/2722505/124605359-d13efb80-de39-11eb-8afc-1759de3d85fe.png)

**Comment by allendav** [comment]
Looking at this now

**Comment by allendav** [comment]
Next, I will be tackling properly handling and displaying when a chip card is inappropriately swiped
