### ISSUE TITLE
woocommerce iOS app: the analytics for this month shows 0 orders and total balance of 0, and my orders are not being updated in the homepage

### ISSUE THREAD

**Issue by ghost** [woocommerce/woocommerce-ios#4566]
I am using the latest official, in my personal phone, and a beta version of the app in another test phone
my shop shows correct visitors, and all stats normally in the app, but, the orders stuck at 0, and no sales... but in the website there were more than 10,000 in sales approved by payment method, and delivered correctly
the app shows no order since this month, and today, and no values tooo...
i did disconnected the jetpack and reconnected it, but, still with same error.
woocommerce apps should not require the jetpack bloat... automatic did a crappy job requiring it...
why do i need to use something, that i could do with auto generating API keys by a single authorization in my website, instead of this freaking jetpack.

why my orders stats are not syncing??

note: if a client does a purchase, i do receive a notification, and i am being able to check the orders and product tabs naturally, the bug stays only in the woocommerce homepage, in the stats, in the this month tab!

i need a fix for it!
thanks

**Comment by rachelmcr** [comment]
Hi there! Can you please submit a support request through the app by going to My Store > Settings (the gear icon in the top right corner) > Help & Support > Contact Support? Please share your site address with us there and our support team will follow up with you as soon as possible with some steps to try and resolve this.
