### ISSUE TITLE
Home Screen - Stick date view bellow date range selector

### ISSUE THREAD

**Issue by fernandofgfer** [woocommerce/woocommerce-ios#4571]
After the development of this issue #3959, @Garance91540 proposed to stick the date view below the range selector, out of the scroll. With that, users can be sure which time period they are looking at
![Simulator Screen Shot - iPhone 11 Pro - 2021-07-07 at 19 03 24](https://user-images.githubusercontent.com/11411847/124800836-6505ea00-df56-11eb-9192-6e5b50f89f7b.png)

**Comment by pmusolino** [comment]
@jaclync do you believe we can close this issue since it's obsolete now with the new dashboard?

**Comment by jaclync** [comment]
yes, the date range bar is no longer in the new design! Closing now.
