### ISSUE TITLE
Wrong product price in Order Detail if the price of the product is negative

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#4579]
From the web but also from mobile, we allow store owners to set a negative price for their products.

Unfortunately, the behavior within the detail of an order that contains a product with a negative price is not aligned.
The price of a product is always shown as positive, and this makes the order total seemingly incorrect.
The payment summary is correct and aligned to the web.

Related discussion on the web: https://github.com/woocommerce/woocommerce/issues/25037

<img src="https://user-images.githubusercontent.com/495617/124912022-be6d2800-dfed-11eb-89f9-8ad2b05e8ef4.png" width=300 />

**Comment by iamgabrielma** [comment]
I'll be giving this one a go so I self-assigned myself for the moment. Please feel free to take over at any time if needed :D
