### ISSUE TITLE
[Mobile Payments] Translated modal text can be truncated if it's too long

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#4581]
**Describe the bug**

On the payment modals, if the translated text is too long, it is truncated instead of appearing on multiple lines or otherwise made to fit the available space.

**To Reproduce**
1. Set your device or app language to Spanish.
2. Set up your store to accept payments for orders.
3. Open the order detail for a processing order.
4. Tap the "Recepción de pago" button.
5. Notice that when you get the prompt to collect payment, the text is truncated. On my iPhone 12 Mini, I only see "Acerca, inserta o desliza la tarjeta par..."

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/124967453-5b46ba00-e01c-11eb-835e-418ef3cb3fe2.PNG" width="300px">

**Comment by ctarda** [comment]
This has been fixed.

<a href="https://user-images.githubusercontent.com/2722505/137196978-f77e3e18-acc7-44cb-8833-efd52a2b4f9c.png" width="350"/>
