### ISSUE TITLE
[Mobile Payments] Order with partial refund is still charged full order amount instead of net amount

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#4583]
**Describe the bug**

If I have an order that is already partially refunded, and I try to collect payment for the remaining amount in the app, the card is charged for the **Order Total** amount (the full order amount before the refund) instead of the **Net Payment** amount (the remaining amount due after the refund).

In addition, all of the products are shown on the order receipt, including any refunded products.

**To Reproduce**
1. Make sure your store is set up to accept in-person payments.
2. Create a new order on your store with more than one product.
3. Partially refund the order, so there is still at least one product in the order.
4. In the app, open the order detail for that order.
5. Tap the "Collect payment" button.
6. Notice that the modal that appears shows more than the customer should have to pay for the remaining order.
7. Collect the payment, and notice that the app shows the **Net Payment** as the remaining amount on the order, but wp-admin shows the full amount was charged to the card.

**Screenshots**

Order with refund ($14 left to pay) | Collect payment ($32 charge) | Receipt (both products appear) | Order details after payment (Net Payment is $14)
-|-|-|-
![IMG_6800](https://user-images.githubusercontent.com/8658164/124976883-bb8f2900-e027-11eb-9e0f-79ccb276e619.PNG)|![IMG_6801](https://user-images.githubusercontent.com/8658164/124976890-bcc05600-e027-11eb-8656-3114aa592dfd.PNG)|![IMG_6802](https://user-images.githubusercontent.com/8658164/124976896-bd58ec80-e027-11eb-958e-fe06ee88d8ee.PNG)|![IMG_6803](https://user-images.githubusercontent.com/8658164/124976904-be8a1980-e027-11eb-9655-208ae72125ab.PNG)

Charge in wp-admin:
![Screen Shot 2021-07-08 at 7 59 01 PM](https://user-images.githubusercontent.com/8658164/124977120-05780f00-e028-11eb-9e5c-c95f111e6d16.png)

**Comment by malinajirka** [comment]
We tried to fix this on Android but it seems the `capture` endpoint doesn't support charging anything else but the total amount - issue submitted [here](https://github.com/Automattic/woocommerce-payments/issues/2390).
