### ISSUE TITLE
Feature flag for Shipping Labels M4

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#4595]
Since the Shipping Labels M4 will implement a lot of features that will be released in the future, we need to hide all the functionalities under different feature flags, that should be added in the codebase.

The M4 has four major parts. They are unrelated, and they will be released in this order:
1. International labels. https://github.com/woocommerce/woocommerce-ios/issues/4596
2. Add payment method. https://github.com/woocommerce/woocommerce-ios/issues/4598
3. Create packages. https://github.com/woocommerce/woocommerce-ios/issues/3909
4. Multiple packages. https://github.com/woocommerce/woocommerce-ios/issues/4599

So, we will follow the same approach used in Android, realizing every feature after they are done, without waiting for the whole milestone completion.

We need to start with international labels, which is the first feature that was released on Android.

More context here: p1624266823345400-slack-CGPNUU63E

**Comment by designsimply** [comment]
### Shipping Labels M4 Test Ideas

I audited results from testing shipping labels in the Andriod app and came up with the following gotchas, scenarios, and ideas.

From Android beta & PR testing

* Check that all expected values are present to avoid strange crashes. (<a href="https://github.com/woocommerce/woocommerce-android/issues/3299">3299</a>)
* Ensure that selecting additional options for a label will update the price accordingly. (<a href="https://github.com/woocommerce/woocommerce-android/issues/4188">4188</a>)
* You should not be able to reprint or refund expired shipping labels. (<a href="https://github.com/woocommerce/woocommerce-android/issues/3845">3845</a>)
* Allow purchasing additional shipping labels. (<a href="https://github.com/woocommerce/woocommerce-android/issues/3856">3856</a>)
* Stores with an empty packages list should still work. (<a href="https://github.com/woocommerce/woocommerce-android/issues/4000">4000</a>)
* Notes can get truncated in languages other than English. (<a href="https://github.com/woocommerce/woocommerce-android/issues/4072">4072</a>)
* Customs forms can be hard to find later—consider combining the shipping label and customs form into one printout if possible.
* Printouts should match the selected formatting (i.e. the paper size you selected was actually used). (<a href="https://github.com/woocommerce/woocommerce-android/pull/3316">3316</a>)
* Keep an eye out for typos, a few (not many though!) made it through to beta testing in Android.

General scenarios to keep in mind

* Order eligibility.
* Accurate pricing & refund amounts.
* Correctly formatted printouts.
* Expired labels.
* Reprinting the label.
* Purchase additional labels.
* Device rotation.
* Non-Englilsh languages.

Specific testing to consider before releasing each feature

* Make sure shipping label creation works when things like variations, add-ons, and decimal stock quantities are also in play. (<a href="https://github.com/woocommerce/woocommerce-android/issues/3174">3174</a>, <a href="https://github.com/woocommerce/woocommerce-android/pull/3283">3283</a>, <a href="https://github.com/woocommerce/woocommerce-android/issues/4094">4094</a>, <a href="https://github.com/woocommerce/woocommerce-android/pull/4267">4267</a>)
* Shipping label creation should only be offered if the order is eligible. (<a href="https://github.com/woocommerce/woocommerce-android/issues/3173">3173</a>, <a href="https://github.com/woocommerce/woocommerce-android/pull/4054">4054</a>)
* Verify pricing is correct, including additional options such as required signature.
* Verify shipping label refunds work and that the refund is for the correct amount each time.
* Verify a receipt is received by email when a shipping label is purchased. (<a href="https://github.com/woocommerce/woocommerce-android/issues/4050">4050</a>)
* Spot check the UI using a language other than English.
* Rotate the device back and forth during testing, including help screens such as the label format options.
* Consider testing with VoiceOver on.

<sup>(internal reference: requested at p1626285538003700-slack-C026HH75ECA /hat tip @rachelmcr)</sup>

**Comment by pmusolino** [comment]
This is gold @designsimply. Thank you so much! 🙌
