### ISSUE TITLE
Plugins: Recover plugins in plugin screen

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#4606]
Parent: #4278

- [ ] Move sync site plugin to plugin screen
- [ ] Sync System plugins in `DefaultStoresManager`

**Comment by Ecarrion** [comment]
Hey @fernandofgfer, I'm not sure what "Recover system plugins in plugin screen" means 😅

**Comment by fernandofgfer** [comment]
Hi @Ecarrion. If I'm not wrong, we talked by P2 that we should sync the new System plugins in the current Plugin screen, right? 😄

**Comment by Ecarrion** [comment]
No, We should sync the "new plugin work" where the "current plugins" are doing it. Then we should move the "current plugin" sync into the "current plugins" screen.

**Comment by fernandofgfer** [comment]
Ah, sorry, I misunderstand you. So we can change `Recover system plugins in plugin screen` by `Sync System plugins in `
DefaultStoresManager`.
