### ISSUE TITLE
Pre-filling phone number in the destination address in Shipping Labels

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#4639]
In Android, they added just recently the phone number pre-filling in the destination address. We can pre-fill the phone in the destination address by reading the order’s metadata, specifically the field: `_shipping_phone`.

**Comment by rachelmcr** [comment]
I confirmed that we already do this. We [initialize `ShippingLabelFormViewModel` using `order.shippingAddress`](https://github.com/woocommerce/woocommerce-ios/blob/e1c5bc12fa5ac25ae24c4263eeaf769c61afe514/WooCommerce/Classes/ViewRelated/Orders/Order%20Details/Shipping%20Labels/Create%20Shipping%20Label%20Form/ShippingLabelFormViewController.swift#L29), and when `destinationAddress` is initialized in the view model we [pre-fill the phone number using `address.phone`](https://github.com/woocommerce/woocommerce-ios/blob/e1c5bc12fa5ac25ae24c4263eeaf769c61afe514/WooCommerce/Classes/ViewRelated/Orders/Order%20Details/Shipping%20Labels/Create%20Shipping%20Label%20Form/ShippingLabelFormViewModel.swift#L451).

When my order has a shipping phone number, it is pre-filled in the destination address form:

<img src="https://user-images.githubusercontent.com/8658164/128388948-447b7346-a0de-4d60-b429-be552638e5e5.png" width="300px">
