### ISSUE TITLE
Shipping Labels: manage decimal quantities in Package Details

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#4640]
As stated [here](https://a8c.slack.com/archives/C6H8C3G23/p1624620001117600), when the order has decimal quantities, we should `ceil` the quantity to the nearest bigger integer. Instead, we are `flooring` it.

As said by @hichamboushaba, it's about quantity, and it will affect the prefilled weight, but it's a side effect.
If an order has 0.5 as quantity, the list of products in the package should show 1 product, and if it's 3.5, it should show 4, which is done by ceiling the quantity to the nearest bigger integer.

<img width="464" alt="Screen Shot 2021-06-25 at 12 19 33" src="https://user-images.githubusercontent.com/495617/126131259-09382578-90d4-488a-bcc7-a1490ab0f579.png">

**Comment by pmusolino** [comment]
Ref: p5T066-2uU#comment-9242

**Comment by rachelmcr** [comment]
This is fixed in #4656 for the 7.1 release.
