### ISSUE TITLE
[Mobile Payments] tapping Cancel on the Scanning for reader screen can result in a loop

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#4653]
Steps to reproduce:

1. Turn on reader.
1. Go to Settings > Manage Card Reader.
1. Allow the reader to be discovered.
1. Choose “Keep searching” when the reader is found.
1. Tap Cancel.

**Result:** 

> You’ll be returned to the Manage Reader screen, and a few seconds later the connection dialog will re-appear.

<sup>(internal reference: p5T066-2uU-p2#comment-9267 /hat tip @nbradbury)</sup>

Video: [1m7s](https://user-images.githubusercontent.com/1119271/126228497-1786ec57-f56b-4f48-997d-eef3bcc01e50.mp4)

<img src="https://user-images.githubusercontent.com/1119271/126231608-2017b178-2188-4862-8f6e-fa015fe84ac5.gif" width="360" alt="card-reader-discovery-loop-wcios-7 1 0 1">
<sup>Tested with WCiOS 7.1.0.1 TestFlight beta on iPad Mini 4 (WiFi) (iPad5,1) iPadOS 14.6 logged in as testuser01121 with worthwhile-seahorse.jurassic.ninja selected and running WP 5.7.2 JP 9.9 WC 5.5.1 WCPay 2.7.0 WCS staging 1.0.</sup>

**Comment by allendav** [comment]
I'm seeing this too. Will look into this right away. cc @ctarda
