### ISSUE TITLE
[Mobile Payments] Reader disconnect button failed to disconnect reader, advance UI during merchant interview

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#4661]
We saw, on a live session, the Disconnect button not work on an iPad on landscape.

**Comment by ctarda** [comment]
So far I haven't been able to reproduce

**Comment by ctarda** [comment]
I tested:
1. connecting, locking the iPad, unlocking and disconnecting
2. connecting, going to the background, bringing the app back into the foreground, and disconnecting
3. connecting, rotating, disconnecting
4. connecting, going to the background, rotating bringing the app into the foreground, and disconnecting

Maybe a couple more combinations of the above.

@allendav can you please try to reproduce this?

**Comment by allendav** [comment]
@ctarda - I have not been able to reproduce this either. I tested all the above as well as:

- waiting 20+ seconds after connecting before disconnecting (i.e. to get to the slow intermittent blue LED blink state on the reader)
- spamming the disconnect button
- locking, waiting 20+ seconds, and then unlocking the iPad while the reader was connected

Tested with today's develop branch on a iOS 14.6 on a 10.2" 8th Gen A2428 iPad

Edit: With a reader running software version 1.00.03.34-SZZZ_Generic_v37-300001 (2018)

I then deleted the app, downloaded version 7.0 from the App Store and repeated the testing - same result - I could not get disconnecting to hang like it did for the merchant.

**Comment by allendav** [comment]
Thought: We need to know what version of reader firmware his device is using. That could be a factor here. We should consider adding that to the UI sooner than later, i.e. perhaps alongside the battery level.

cc @Garance91540 @adamzelinski 

Edit: The software version strings are longish, btw - see https://stripe.com/docs/terminal/readers/bbpos-chipper2xbt#reader-software-releases

![software-version](https://user-images.githubusercontent.com/1595739/126405160-87203464-1082-4fe6-831f-91b5c4d9abe2.png)

**Comment by ghost** [comment]
Hey, @allendav that sounds like a good suggestion to me. We could do this
<img width="1095" alt="Screen Shot 2021-07-22 at 11 17 04 am" src="https://user-images.githubusercontent.com/74938219/126578479-b7eb3d13-431a-447b-8ad7-2e4f52e8526c.png">

**Comment by ghost** [comment]
The other option would to just put it underneath on a new line if you think the strings will be too long.

**Comment by allendav** [comment]
> We could do this

Yup!

> The other option would to just put it underneath on a new line if you think the strings will be too long.

That sounds like a good idea. The software version strings are long.

**Comment by Garance91540** [comment]
Hi there! 

Based on the comment above I updated the designs to display the firmer version as a new line 

<img width="231" alt="Screen Shot 2021-08-02 at 6 33 32 PM" src="https://user-images.githubusercontent.com/28450084/127894545-8a6b328a-f5dc-4e45-8cdc-291a87d351a3.png">

cc @malinajirka so we are sure to make that change on Android too!

**Comment by allendav** [comment]
#4985 may help with this as the spinner will at least let us know that disconnect has been initiated and the multiple-tap protection should avoid confusing the Stripe Terminal SDK with multiple back to back disconnect requests (assuming that might have been what happened here)

**Comment by ctarda** [comment]
We haven't been able to reproduce this and we haven't had any reports of this happening again, so I think it is safe to close for now
