### ISSUE TITLE
Shipping Labels: Use Combine to reduce duplicated code in ShippingLabelPackageDetailsViewModel

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#4666]
# Description
Currently in `ShippingLabelPackageDetailsViewModel`, I see there are repeated calls to `generateItemsRows` here and there. This can be a good case to use Combine's `combineLatest` to observe changes in 2 or more publishers and update variables.

# Suggested solution
If `products` and `productVariations` were updated to be `@Published` variables, they can be used to observe changes in their values and then  Combine's`combineLatest` can be used to update `itemRows` directly.

The same thing can be updated for calculating and updating package weight based on changes of product, variations and selected package ID.

**Comment by pmusolino** [comment]
nit: remember to always assign a Project to the issue ;) In this way, we do not risk missing it!

**Comment by itsmeichigo** [comment]
Thanks @pmusolino! I just updated the Project field 👍
