### ISSUE TITLE
Shipping Labels: allow re-creating a shipping label for all cases (refunded, existing, etc...)

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#4676]
As discussed [here](https://a8c.slack.com/archives/C026HH75ECA/p1627308002046400?thread_ts=1626460086.013600&cid=C026HH75ECA), we should allow re-creating shipping labels for all cases, even if we have non-refunded existing labels, the button to re-create the label will be shown in the overflow menu, presenting the bottom action sheet. It should be added in the action sheet where we already display the action to refund a shipping label.

Relevant discussion [here](https://a8c.slack.com/archives/CGPNUU63E/p1615913529004000?thread_ts=1615285371.106700&cid=CGPNUU63E).

<img src="https://user-images.githubusercontent.com/495617/127019099-9ced6acc-9e45-49da-8b7f-0490aa89161c.png" width=300 />

**Comment by itsmeichigo** [comment]
According to the updates in the aforementioned discussion, the option to create an additional shipping label is displayed in the overflow menu of the Product section instead. This is also how it is being handled on Android:

<img src="https://user-images.githubusercontent.com/5533851/138200502-76deede3-53a4-445b-b99d-2a9855a9c9f5.png" width=320 />

So I will go ahead and do the same thing on our side.
