### ISSUE TITLE
[Mobile Payments] Warn merchant if they haven't completed KYC yet

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4677]
Re: paJDYF-2ck-p2

An upcoming (this week) change in how we set up WCPay Express accounts on our server will result in WCPay accounts being returned by the account endpoint that may not have yet completed KYC.

Accounts that have not yet completed KYC may not be able to accept in-person payments, or may not be able to receive payouts, or both (or neither.)

We should consider adding a screen to the Manage Card Reader flow that encourages merchants to complete KYC if they haven't already.

Chances are an established WCPay merchant will have completed KYC by time they get their first card reader, but merchants participating in the beta are more likely to run into this.  For these reasons, I would give this a medium priority, since a workaround exists (asking the merchant to complete KYC)

Related: p91TBi-4Pv-p2

cc @ctarda @astralbodies @bmccotter 

Related Android issue: https://github.com/woocommerce/woocommerce-android/issues/4489

**Comment by allendav** [comment]
@dechov noted:

> Just checked up on this and tested it quickly – due to the updated check (in the backend), it actually still won’t have the account info until the initial KYC is completed. (I think those issues are referring to the account endpoint in the plugin, but it’s the same.)

> That said, it doesn’t seem farfetched that we will want to change this, and introduce awareness of incomplete onboarding states to the plugin at some point, possibly soon. So the issues are certainly still valid, but could perhaps (in coordination with similar changes in the plugin itself) await further guidance on how incomplete states will look to the API.

**Comment by ctarda** [comment]
Closing
