### ISSUE TITLE
Shipping Labels: Inconsistent error messages for invalid addresses

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#4693]
# Describe the bug
@designsimply found an inconsistent in the way error is presented for invalid addresses. With addresses that are slightly a bit different (but both unable to be validated), one was showing error in the address field, and one was showing top banner. 

# To Reproduce
1. Go to Orders tab and select an order with Processing status.
2. Select Create Shipping Label and configure origin address (same thing happens in destination address as well).
3. Update the address to "400 E 400 S", Salt Lake City and Utah for the city and state fields.
4. Tap Done and notice that an error shows in the address field saying "House number is valid".
5. Update the address to "4000 E 400 S" and tap Done - notice that top banner shows up this time saying the address cannot be verified.
6. Repeat the similar steps on the WooCommerce web app, notice that there's no difference in the error message of both addresses.

# Screenshots
<img width="655" alt="Different error messages for slightly different addresses" src="https://user-images.githubusercontent.com/5533851/127429223-4758f243-3db8-409a-95c9-f3fd9c5997b7.png">

# Expected behavior
It'd be better if we have more consistent error messages.

Ref: p5T066-2wJ-p2#comment-9333

**Comment by itsmeichigo** [comment]
@pmusolino this is an issue found from the beta 7.2 build so I'm not sure it's alright to set it as part of Shipping Labels M4. I suppose it's not a serious issue that needs to be fixed right away, WDYT?

**Comment by pmusolino** [comment]
I think that it's a bug that we can't solve at the moment unless we want to change the behaviors on how we manage errors. This happens because we receive two different errors from the backend: one error is specific on the address field, the other one is generic, and just for this case, we display the top banner.

**Comment by designsimply** [comment]
@pmusolino @itsmeichigo please feel free to close this with the won't fix label if you feel it's fine as is! I reported it in beta testing because I noticed the difference and am totally cool if you decide to accept what the back-end provides in this case. 🙂
