### ISSUE TITLE
Order Detail: when there are no contacts, the Billing Information screen display an empty section

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#4694]
From the Order Detail screen, opening the Billing Information screen, we display an empty section "Contact Details" if there are no email and phone numbers.

<img src="https://user-images.githubusercontent.com/495617/127466977-2a29749a-9789-4382-b33c-3ba1a7b29028.png" width=300 />

**Comment by Patil2099** [comment]
I would love to take this up

**Comment by giovannapezzini** [comment]
Hi @pmusolino, it's been over a month since the last reply so I took the liberty to create a PR fixing the issue. 🙂

**Comment by pmusolino** [comment]
Thank you @giovannapezzini. I'm going to review it right now.
