### ISSUE TITLE
Shipping Label creation: bug when the destination address is empty

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#4701]
When an order doesn't have a shipping address, when we try to create a shipping label the `Ship To` address will be empty (correct), but the screen will be pushed two times.

https://user-images.githubusercontent.com/495617/127638352-575c19c8-59b3-4569-a22b-c0d5d6f4a1ee.mp4

**Comment by shiki** [comment]
I ran into a similar thing today but on the "Continue" → Ship From step. 


https://user-images.githubusercontent.com/198826/129594576-d99289d3-4013-4c63-ae33-faf9ab4e592a.mp4
