### ISSUE TITLE
Measurement Price Calculator: Metadata that are not Variation Attributes are not shown in Order Details and Fulfillment screens

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#4708]
## Describe the bug

Reported by a merchant:  4182704-zd-woothemes
Discussed in: p1627660879010800-slack-C6H8C3G23

I'm only able to reproduce this using the [Measurement Price Calculator](https://woocommerce.com/products/measurement-price-calculator/) plugin. If using the plugin, the metadata is displayed in Order Details.

Android displays the metadata from the plugin as shown here:

<img src="https://user-images.githubusercontent.com/198826/127717002-0c558ffc-b92e-4540-9b46-52ecb3de4308.png" width="300">

But iOS does not display it:

<img src="https://user-images.githubusercontent.com/198826/127716971-c0a495e4-f1d0-4322-9b25-e1981b4e7939.png" width="300">

## To Reproduce

1. Install the Measure Price Calculator plugin. 
2. Set up a product so it has the "Calculated Price" and "Calculated Weight" checked. I'm not sure if having one field is enough but this is what I did when I tried to reproduce the problem. 
    <img src="https://user-images.githubusercontent.com/198826/127717156-a94df4bc-bb0c-45c2-afce-a6f1413ba7bf.png" width="500">
3. Create an order on the web. Enter a value in the Required Weight:
    <img src="https://user-images.githubusercontent.com/198826/127717229-0538992c-d287-4aa8-afce-2e495287c050.png" width="300">
4. Submit the order.
5. View the order in the app. 

## Expected behavior

Since Android is able to display this, there might be some differences in how we parse the metadata. We can try and follow how Android does the metadata parsing.

**Comment by Ecarrion** [comment]
> Since Android is able to display this, there might be some differences in how we parse the metadata. We can try and follow how Android does the metadata parsing.

Hi @shiki, as far as I remember we only display variations metadata. Do you think displaying all meta-data could be considered "unsafe" as we don't know what kind of information will be sent there?

**Comment by shiki** [comment]
Good point! It is indeed unsafe. 

My thinking on this last week was that maybe it's “easy” to detect if the metadata is from the Measurement Price Calculator plugin. If that's easy to do, then we can quickly add it. If not, then we should probably remove the Android. 

What I was worried about was removing the fulfillment capability from the merchant that reported this.

**Comment by Ecarrion** [comment]
Hey @shiki 

This is the response we are getting.
```
{
  "meta_data": [
    {
      "id": 3665,
      "key": "Required Weight (kg)",
      "value": "2.3",
      "display_key": "Required Weight (kg)",
      "display_value": "2.3"
    },
    {
      "id": 3666,
      "key": "_measurement_data",
      "value": {
        "weight": {
          "value": "2.3",
          "unit": "kg"
        },
        "_measurement_needed": 2.3,
        "_measurement_needed_unit": "kg"
      },
      "display_key": "_measurement_data",
      "display_value": {
        "weight": {
          "value": "2.3",
          "unit": "kg"
        },
        "_measurement_needed": 2.3,
        "_measurement_needed_unit": "kg"
      }
    }
  ]
}
```

I think what Android is doing is to show any meta-data that when the key does not start with `_`.
And Core seems to be doing the same.

At this point, I don't think we should try to support the `Measurement Price Calculator` but we should we showing all meta-data, like core.

If we mimic Android designs, once we have multiple meta-data entries, the information could become useless as the designs do not show the meta-data entry label.

What do you think?

**Comment by shiki** [comment]
Thank you for troubleshooting this further, @Ecarrion. Let me know if I misunderstood you. 

Yes, we shouldn't support the Measurement Price Calculator plugin directly. Instead, we can show the metadata whose keys do not start with `"_"`. It looks like that's how Android does it. See these lines in [`Order.kt`](https://github.com/woocommerce/woocommerce-android/blob/3c02b1d77ef994554d5c8f1a0d6295485b856683/WooCommerce/src/main/kotlin/com/woocommerce/android/model/Order.kt#L116-L124). Correct me if I'm wrong about that, @ThomazFB. 

> If we mimic Android designs, once we have multiple meta-data entries, the information could become useless as the designs do not show the meta-data entry label.

Since Android has had this behavior for a while, I guess it wouldn't be a problem. What do you think about trying this out for now? The last fix in Android for this was Nov 2020 (https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1768/).

And then we could probably open up a separate issue for the possible confusion.

**Comment by Ecarrion** [comment]
@shiki

> What do you think about trying this out for now?

That makes sense, thanks for the android links! They will be very useful!
