### ISSUE TITLE
Shipping Labels: update the customs form to accept multiple packages

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#4718]
Update the customs form step in shipping labels form to handle multiple packages

<img width="593" alt="Schermata 2021-08-03 alle 17 38 18" src="https://user-images.githubusercontent.com/495617/128044582-3a3d7d84-2dea-41f9-a847-81a3c7064916.png">

**Comment by pmusolino** [comment]
@itsmeichigo Since you are working on this screen for Internation Labels, it would be ideal to implement it with the multi-package support in mind ;)

**Comment by itsmeichigo** [comment]
Gotcha, thank you @pmusolino!
