### ISSUE TITLE
[Shipping Labels] "...from your phone" - should probably say "mobile device" since iPad is also an option, no?

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4746]
In several spots we have localized strings that reference "phone" - maybe that should say "mobile device" instead since some of our merchants will prefer to manage their stores, print labels, etc from an iPad

https://github.com/woocommerce/woocommerce-ios/blob/9756551209f392afae5cb3b2e8092f78965aca0b/WooCommerce/Classes/ViewModels/Order%20Details/OrderDetailsDataSource.swift#L1211

https://github.com/woocommerce/woocommerce-ios/blob/4fe952211777fad134084cbc19d4db229a37c8c9/WooCommerce/Classes/ViewRelated/Orders/Order%20Details/Shipping%20Labels/Create%20Shipping%20Label%20Info/ShippingLabelCreationInfoViewController.swift#L53

Possibly other places as well

**Comment by IkerOrtega** [comment]
I'll take it if it's okay

**Comment by shiki** [comment]
Added an issue for Android: https://github.com/woocommerce/woocommerce-android/issues/4643 for parity.
