### ISSUE TITLE
Order Editing: Release Feature

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#4786]
After all tasks are completed we can release the feature to the public

- [x] Do a quick run-through of the features to make sure we didn't miss anything and there are no critical bugs. If available, we can use Sheri's testing guide. Non-critical bugs don't need to block the release. They can be fixed later.
- [x] Remove feature flag
- [x] Update release notes
- [x] Notify testers

**Comment by shiki** [comment]
@Ecarrion @ealeksandrov I added this item **before** removing the feature flag: 

> Do a quick run-through of the features to make sure we didn't miss anything and there are no critical bugs. If available, we can use Sheri's testing guide. Non-critical bugs don't need to block the release. They can be fixed later.

Does it make sense? Do you agree?

My goal is for us to avoid disasters and stress during the beta process.
