### ISSUE TITLE
Order Fulfillment: Undoing does not work properly

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#4790]
# Description
As @designsimply found in beta build of 7.2, undoing fulfillment for order doesn't work consistently:

> When I tap the Undo button on the success notice after I’ve marked an order as complete, the button reappears briefly then disappears and does not appear again unless I pull-to-refresh or close and re-open the order.

![undo-for-mark-order-complete-wcios-7 2 0 0](https://user-images.githubusercontent.com/5533851/129134724-fa502cb0-828a-47cd-83e3-e5d56e7faf5c.gif)

My assumption is that the callback block for fulfillment is deallocated when the Order Review screen is dismissed, causing the `OrderFulfillmentUseCase` to not complete its job in time. This issue is worth a closer look though.

Internal reference: p5T066-2wJ-p2#comment-9364

**Comment by pmusolino** [comment]
I'm no more able to replicate this issue, probably it was fixed during one of our refactorings. Closing this for the moment.
