### ISSUE TITLE
Product search: can't search for words with accents without using them

### ISSUE THREAD

**Issue by eduardozulian** [woocommerce/woocommerce-ios#4801]
**Describe the bug**
Languages like Portuguese use a lot of accents. In the Woo app, however, it's not possible to search for products with accents unless you always use them when typing the word.

**To Reproduce**
1. Add a product with at least a word with accents. In my case, _ação_ or _catálogo_
2. Go to Products and tap on search
3. Type the words, partially or not. Examples: _aca_, _acao_, _catalogo_
4. You'll get no results

**Expected behavior**
To list the products despite of not using accents.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**

- Device: iPhone 7
- iOS version: 14.4
- WooCommerce iOS version: 7.1.0.2

**Comment by koke** [comment]
I've tried this in Spanish on both the iOS app and the web, and search seems to be working correctly with accents.

<img width="400" src="https://user-images.githubusercontent.com/8739/129331778-6849bceb-e74e-4f8c-a269-1cf3d06ceb54.jpeg">

![Screen Shot 2021-08-13 at 10 53 09](https://user-images.githubusercontent.com/8739/129331796-d2c4a63b-ec73-4606-bc87-562714de7411.png)

Can you verify if this works as expected on a web browser? Is there a chance you have an extension related to products or search that might be affecting this?

**Comment by eduardozulian** [comment]
@koke, things are good in the browser and disabling [Custom Order Status for WooCommerce](https://wordpress.org/plugins/custom-order-statuses-woocommerce/) partially fixed the issue with _catálogo_ but search is still inconsistent.

Word: _catálogo_

* _cata_: all results
* _catalogo_: no results
* _catal_: no results 
* _logo_: all results

A single letter after the one with the accute accent breaks search for me.

Words: _ação_, _canetão_, _produção_

* _caneta_: all results for _canetão_
* _canetao_: no results
* _tã_ or _tão_: all for _canetão_
* _ão_: all results for _ação_, _canetão_, _produção_
* _Ão_: no results
* _çã_: all results for _ação_, _canetão_, _produção_
* _Çã_: no results

Here's a video:

https://user-images.githubusercontent.com/1136160/129380353-bc487626-6e21-4d8b-99dd-b265a3819f8e.MP4

More info:

* Tested on WordPress.com, with cache flushed
* Active plugins at this point are: Jetpack, Woo, and Askismet
* Results are the same when testing the app with English, Portuguese, and Spanish
* I found a similar issue on https://github.com/woocommerce/woocommerce-android/issues/3550 but not sure if related

Let me know if there's anything else you think I can focus on.

**Comment by koke** [comment]
Confirmed the examples you provided in wp-admin as well

<img width="1144" alt="Screenshot 2021-08-19 at 13 20 22" src="https://user-images.githubusercontent.com/8739/130060265-fc17dc6d-dbba-42cd-a139-18d96e284829.png">
<img width="1137" alt="Screenshot 2021-08-19 at 13 20 36" src="https://user-images.githubusercontent.com/8739/130060274-ba016b8f-6870-466d-9ff0-5960df4bfc99.png">

I haven't been able to find yet what is causing this, but it doesn't look specific to the apps.

**Comment by koke** [comment]
Another detail, I can reproduce the same issue with Posts (not just products), but it works fine on another self-hosted site, so it might be WordPress.com-specific

**Comment by eduardozulian** [comment]
You're 100% right.

I tested _catálogo_ on WP.com on both simple and AT sites and had the same problem. I'll move this to https://github.com/Automattic/wp-calypso/ instead.

Let me close this one for now. I appreciate all the help, @koke!
