### ISSUE TITLE
Order Editing: Handle "copy address" button

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#4808]
<img width="283" alt="Screen Shot 2021-08-11 at 9 54 50 AM" src="https://user-images.githubusercontent.com/562080/129054686-04a7f429-db71-4fc3-bb3d-eae329e9b32f.png">

Tasks:
- [x] Add button to copy billing/shipping address
- [x] Make sure the order data model is properly populated before updating the order remotely.

**Comment by Ecarrion** [comment]
Hi @koke, I think you closed this issue by mistake.

Just pinging you so you can close the real issue!

**Comment by koke** [comment]
Oops, sorry about that, it was #4804 🤦🏽‍♂️
