### ISSUE TITLE
[CPP Onboarding] Handle site in test mode with live stripe account

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#4835]
Android implementation: https://github.com/woocommerce/woocommerce-android/pull/4603

Tasks:
- [ ] Extend `WCPayAccount` to include `is_live` and `test_mode` fields
- [ ] Write implementation for `CardPresentPaymentsOnboardingUseCase.isWCPayInTestModeWithLiveStripeAccount` to return `true` when both flags are `true`
- [ ] Implement new screen for the `wcpayInTestModeWithLiveStripeAccount` state

**Comment by ctarda** [comment]
Closing as it seems to be implemented in #5358
