### ISSUE TITLE
Products: add the variation number to the variations list and details

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#4846]
The variation number should be shown in the variations list and details screens.

Here's what I'm seeing in 7.3.0.0 (Testflight beta):

<img src="https://user-images.githubusercontent.com/1119271/130199007-06e287b0-08b9-425e-8206-ab0c8c8732a5.PNG" width="270" alt="IMG_4951">  <img src="https://user-images.githubusercontent.com/1119271/130199000-6c0496d3-0a5a-4af8-b94a-2994d8e55235.PNG" width="270" alt="IMG_4952">

Here's what the designs show:

<img src="https://user-images.githubusercontent.com/1119271/130199056-11521877-6674-4feb-b4b3-ca4e6df6d7e7.png" width="560" alt="screen-shot-2021-08-11-at-11 06 40-pm">

<sup>(internal reference: p5T066-2yX-p2#comment-9525 /hat tip @Garance91540)</sup>

**Comment by Ecarrion** [comment]
I'm assigning this to a trial candidate
