### ISSUE TITLE
Products: when saving a variation it should say "Saving your variation" not "Saving your product"

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#4847]
> Is it possible to update the text so it reads “Saving your variation” / “Please wait while we save your latest changes”. We know users get confused about watching their variations page vs their product page. So clarifying anywhere we can that they are looking at the Variations page when they are is a big help.

<img src="https://user-images.githubusercontent.com/1119271/130199642-4ff2290a-bb30-4920-afe1-dc57027de3fd.png" width="270" alt="image">

<sup>(internal reference: p5T066-2yX-p2#comment-9525 /hat tip @Garance91540)</sup>

**Comment by Ecarrion** [comment]
I'm assigning this to a trial candidate
