### ISSUE TITLE
Products: make the “Add price to your variations to make them visible…” banner clickable

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#4849]
> Can we make the “Add price to your variations to make them visible…” banner clickable? (same target as the “Variations” row, opening up the Variations List)

<img src="https://user-images.githubusercontent.com/1119271/130201085-2bfc0903-17c9-4745-bccf-bad80a01d04b.PNG" width="270" alt="IMG_4955">
<sup>Tested with WCiOS 7.3.0.0 TestFlight beta on iPhone 11 iOS 15.0 Beta 5 logged in as testuser01121 with hilarious-sea.jurassic.ninja selected and running WordPress 5.8, Jetpack 10.0, WooCommerce 5.6.0.</sup>

<sup>(internal reference: p5T066-2yX-p2#comment-9525 /hat tip @Garance91540)</sup>

**Comment by selanthiraiyan** [comment]
Hi 👋 
I will take a look into this issue.

**Comment by shiki** [comment]
Sounds good, @selanthiraiyan! Thanks for contributing! 🎉
