### ISSUE TITLE
Shipping Label creation: the image of FedEx courier does not respect the aspect ratio in Carrier and Rates

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#4888]
I found a small bug, where the image of FedEx courier does not respect the aspect ratio of the image in the Carrier and Rates screen in the Shipping Label creation flow.

<img src="https://user-images.githubusercontent.com/495617/131113026-3fc421be-b3e5-42c5-a7a2-819444ffead4.png" width=300 />

**Comment by itsmeichigo** [comment]
I notice that the image used on Android is different: 

<img src="https://user-images.githubusercontent.com/5533851/131277647-eb184a40-8303-412e-bb72-9d50da17d4e0.png" width=400 />
