### ISSUE TITLE
[Mobile Payments] [Card Reader Software Updates] Show progress bar while updating

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4889]
Reader software updates may benefit from a progress bar. The Android app has one.

For prioritization's sake, consider how SDK v2 reader software update changes may come into play, and also consider that although the Stripe SDK has ominous enums like `. betweenFiveAndFifteenMinutes` a recent update of a reader from `37 (1.00.03.34-SZZZ_Generic_v37-300001)` (November 2018 release) to the most recent release - `v45` - took just 54 seconds.

Needs design for iOS

Re pdfdoF-5J#comment-165

cc @ctarda @Garance91540 @adamzelinski  @kidinov

**Comment by Garance91540** [comment]
Agreed, I'm planning to P2 updates on the software update flow after convo with Andrei later today or tomorrow morning at the latest

**Comment by ctarda** [comment]
This is kind of solved by the new UI added to support the 2.x SDK. Closing!
