### ISSUE TITLE
🚀 Feature request: Refactor Storage, Yosemite & Networking as standalone Swift Packages.

### ISSUE THREAD

**Issue by p-larson** [woocommerce/woocommerce-ios#4892]
I beleive it would be beneficial to the WooCommerce iOS community if this project's targets were refactored into Swift Packages so they can be used outside of this project.

The project's targets already wraps WooCommerce's API, refactoring these Frameworks as a Swift Package would help distribute the already existing and incredible work ya'll have done and make it easily accessible to people outside the project. 

I beleive with Xcode 12 it now that it supports assets and resources like Core Data model files.

**Comment by pmusolino** [comment]
Hello there, and thank you for suggesting this. It's a great idea.
We have been planning to move these to SPM but it's a low priority task and we don't have a lot of resources at the moment. Plus, there isn't a lot of interest from the community. So we appreciate you sharing this need.

How would you use this? What's the most useful package for you? That might help with our prioritization.
We'll close this issue for now but it doesn't mean that we did not hear you. Moving to SPM is still in our long-term backlog. We just try to keep the GitHub board tidy and represent what we're aiming to fix in the short term.
