### ISSUE TITLE
Shipping Labels: Package Selected modal dismissed on device rotation

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#4913]
**Describe the bug**

As reported in https://github.com/woocommerce/woocommerce-ios/pull/4905#pullrequestreview-745152629:

In the shipping label package details screen, tapping Package Selected opens a modal view. Rotating the device from portrait to landscape dismisses the modal. (Rotating from landscape to portrait doesn't dismiss the modal.)

This also affects the feature-flagged Add New Package screen, which you can navigate to from the Package Selected screen if the app is run in debug mode.

Note: I can't reproduce this in a simulator, only on device (tested on iPhone 12 Mini, iOS 14.7.1 in WCiOS 7.4 beta).

**To Reproduce**

1. Make sure you have configured the WooCommerce WCShip plugin, and you have one or more packages set up in WP Admin under WooCommerce > Settings > Shipping > WooCommerce Shipping.
2. Launch the app in debug mode (so the feature flag is enabled).
3. Open an order detail that is eligible for the shipping label.
4. Tap the button "Create Shipping Label.”
5. Confirm "Ship From" and "Ship To.”
6. In the package details section, tap on “Package Selected.”
7. On the Package Selected screen, rotate the device and notice the modal closes so you're back on the Package Details screen.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/131887488-6013b942-9ba9-4029-a210-ac94c0fef33d.gif" width="300px">

**Comment by itsmeichigo** [comment]
@rachelmcr @pmusolino  I can't seem to reproduce this issue on the new Package Details screen, can we close it then?

**Comment by pmusolino** [comment]
If it's no more reproducible, yes, feel free to close it 🙌

**Comment by rachelmcr** [comment]
Yes, I was testing this quite a bit at the end of last week and couldn't reproduce it anymore, either. I'll go ahead and close it now 👍
