### ISSUE TITLE
[Mobile Payments] Disconnect Reader button fails silently

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#4922]
**Describe the bug**

When a reader is connected, tapping the Disconnect Reader button doesn't seem to work on the first attempt

**To Reproduce**
1. Go to Settings > In-Person Payments > Manage Card Reader
2. Tap on Connect Reader and connect to a reader
3. When the reader connects, tap on Disconnect Reader

I can see some error in Xcode's console:

```
2021-09-03 14:20:54.853302+0200 WooCommerce[3472:2018316] 🔵 Tracked card_reader_disconnect_tapped, properties: [AnyHashable("blog_id"): 191646963, AnyHashable("is_wpcom_store"): false]
2021-09-03 14:20:54.857371+0200 WooCommerce[3472:2018484] Unexpected error when disconnecting reader
```

**Comment by koke** [comment]
After some debugging, what seems to be happening is that we start a check for updates as soon as we connect, and that prevents disconnection with an error:

> Error Domain=com.stripe-terminal Code=1000 "Could not execute disconnectReader because the SDK is busy with another command: checkForUpdate." UserInfo={NSLocalizedDescription=Could not execute disconnectReader because the SDK is busy with another command: checkForUpdate., com.stripe-terminal:Message=Could not execute disconnectReader because the SDK is busy with another command: checkForUpdate.}

One option would be to store the cancelable when we check for updates, and cancel it when we try to disconnect. However, I wonder if the checking for updates would also block other functionality, and it might be better to keep the "Connecting..." modal until the update check is finished.

**Comment by allendav** [comment]
I think we could build on #4985 and address both this and #4856 by:

Disable the disconnect button until the update check comes back

and

The row at the top of the screen that appears when a software update is available should display something like "Checking for software updates" to help about re-layout re-juggling and explain why the disconnect button is disabled

and

Show the "update software button" but in a disabled state until the update check comes back (i.e. both the disconnect buttons and update software buttons will be initially visible and disabled)

and

Display a "Your reader is running the latest software" if the update check comes back and there is no update available. Leave the update software button on the screen and disabled in this case as well

Thoughts? It would 1) be more informative for the user 2) encourage updating out-of-date readers and 3) avoid the screen content jumping around

cc @adamzelinski  @Garance91540

**Comment by ghost** [comment]
Those suggestions sound good to me @allendav

**Comment by allendav** [comment]
Thanks @adamzelinski - cc @koke re https://github.com/woocommerce/woocommerce-ios/pull/4985#pullrequestreview-756357866
