### ISSUE TITLE
[Mobile Payments] Modal background flashes when auto-connecting from an order

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#4924]
**Describe the bug**
The dark background behind the modal disappears for a second when connecting from an order

**To Reproduce**
1. Make sure the reader is "known". If necessary, connect to it beforehand, then turn off the reader
2. Go to an order that can be paid and tap on Collect Payment
3. When the Searching for reader modal appears, turn on your reader

**Screenshots**

![cpp-modal-bg](https://user-images.githubusercontent.com/8739/132005822-ee3ceeba-bb9b-49bf-8a58-6c7a8055f8b7.gif)

**Comment by allendav** [comment]
Related: #4955

**Comment by ctarda** [comment]
Closing, as it seems to be
