### ISSUE TITLE
[Mobile Payments] Don't kick off automatic searches right after disconnecting from a reader

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4933]
Right now, if you've successfully connected to a reader (and never explicitly disconnected from it), then, on entering Manage Card Reader, the reader search will automatically begin.

This does beg one question - if we keep this feature - if I have successfully connected to say ReaderA in the past, and I'm connected to ReaderB right now, if I disconnect from ReaderB, we probably shouldn't kick off an automatic search for ReaderA - right afterwards - right? That would probably seem unexpected / confusing to users.

Thoughts? @woocommerce/mobile-designers  @ctarda

**Comment by ghost** [comment]
I would agree with that @allendav I don't think there should be an automatic search for ReaderA after disconnecting from another reader. The Merchant should just have to select the next reader to connect with.

**Comment by Garance91540** [comment]
> This does beg one question - if we keep this feature - if I have successfully connected to say ReaderA in the past, and I'm connected to ReaderB right now, if I disconnect from ReaderB, we probably shouldn't kick off an automatic search for ReaderA - right afterwards - right? That would probably seem unexpected / confusing to users.

Hi Allen, so after disconnecting from ReaderB, what do you think the behavior should be? reconnect to readerB?

**Comment by allendav** [comment]
I think that after disconnecting from ReaderB, the merchant should be returned to this screen without any automatic search being initiated:

<img width="347" alt="Screen Shot 2021-09-07 at 9 57 56 AM" src="https://user-images.githubusercontent.com/1595739/132383018-f0fa4963-a5dd-4732-b477-3d2c9ed4d586.png">

And then... if the merchant taps the "Connect Card Reader" button at this point then:

- if we see ReaderB first, we should ask the user if they'd like to connect to it (since we forget readers that merchants explicitly  disconnect from)
- if we see ReaderA first, we should automatically connect to it (since we've successfully connected to it in the past and - in this example - the merchant has NOT explicitly disconnected from ReaderA)

**Comment by Garance91540** [comment]
Hi Allen, I agree with the behavior you suggest. Thanks for flagging this
