### ISSUE TITLE
[Mobile Payments] Add a means to clear out the "known" reader cache

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4934]
See also #4933 

Right now we have no way to remove a "known" card reader from the cache without connecting to it and then disconnecting from it (other than uninstalling the app which is a non-starter)

This means that if a card reader were to, say, become damaged or otherwise unavailable, the merchant would always be immediately placed into search on entering Manage Card Reader and have no way to not be.

If we keep this feature (automatic search if at least one reader is "known") - we may want to consider adding a menu item to clear the known reader cache.

cc @woocommerce/mobile-designers  @ctarda 

Thoughts?

**Comment by malinajirka** [comment]
If I recall correctly Android "solves" this issue by remembering the last connected reader only - can you confirm @kidinov?

**Comment by kidinov** [comment]
@malinajirka Yes. So pretty much if the known reader is damaged, the user can connect to another one if it's found

**Comment by allendav** [comment]
> remembering the last connected reader only

This isn't a bad idea. For support's sake we should probably harmonize Android and iOS in this regard. @ctarda @Garance91540 - shall we limit iOS to one "known" reader as well?

The downside is if a merchant has multiple readers and doesn't take care to associate specific readers with phones - the first time the phone sees a reader in that situation there is a higher chance of the merchant being prompted to connect instead of it just connecting. Overall, I suspect most merchants will associate specific readers with specific phones (and leave spares in a box) so this small downside shouldn't be common/frequent.

**Comment by Garance91540** [comment]
> This isn't a bad idea. For support's sake we should probably harmonize Android and iOS in this regard. @ctarda @Garance91540 - shall we limit iOS to one "known" reader as well?

I think that would make most sense for most users, so I'd say yes!

**Comment by allendav** [comment]
See

https://github.com/woocommerce/woocommerce-ios/issues/4953
