### ISSUE TITLE
Merge `updateOrder` and `updateOrderStatus` actions.

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#4943]
For the order editing project, we introduced a new `updateOrder` action that lets the consumer choose which order field to update remotely.

The order screen uses an action named `updateOrderStatus` to update the order status.

## Tasks

- [ ] Merge `updateOrderStatus` action into `updateOrder` action.
- [ ] Tests that updating the order status doesn't break anything or generates UI glitches.

**Comment by talpert022** [comment]
I'll have a go at solving this issue!

**Comment by Ecarrion** [comment]
We have noticed that we need the current `updateOrderStatus` to maintain the optimistic update UX when updating user status.

I'm going to close this for now.
