### ISSUE TITLE
[Mobile Payments] Errors when connecting to a reader are not displayed

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#4947]
The `connect` method in StripeCardReaderService capture potential errors in the connection process. 

Those errors are supposed to be propagated via the Future returned by this method, but the errors are not presented on screen.

**Comment by koke** [comment]
This seems somewhat related to #4923 and #4924

**Comment by allendav** [comment]
Closing this. We'll track unfinished business in 

https://github.com/woocommerce/woocommerce-ios/issues/4991

and

#4924
