### ISSUE TITLE
[Mobile Payments] Card Reader Settings screen is cut off on iPad's split mode

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#4951]
**To Reproduce**
1. Go to Setting > In-Person Payments > Manage Card Reader
2. Drag another application from the dock to the side to enable split view

**Screenshots**
![Screen Shot 2021-09-08 at 16 13 27](https://user-images.githubusercontent.com/8739/132526066-06680dba-2d53-4523-890c-f4f58260f043.png)

**Comment by ctarda** [comment]
I can't reproduce on iPadOS 15. I assume we have already fixed this, maybe indirectly
