### ISSUE TITLE
[Mobile Payments] Break reader modal secondary copy across two lines for regular width size class

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4954]
Props @adamzelinski in https://github.com/woocommerce/woocommerce-ios/pull/4931#issuecomment-914939754

I think the secondary copy here should go across two lines if possible just so it's not right to the modal's edge.

<img width="809" alt="edge" src="https://user-images.githubusercontent.com/1595739/132556618-981c8f08-6a55-47aa-8477-cea72d7b84f4.png">

**Comment by koke** [comment]
This is likely going to get better in #4940, as iPads get bigger horizontal paddings.

**Comment by joshheald** [comment]
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-10-14 at 15 58 46](https://user-images.githubusercontent.com/2472348/137343843-141f150f-482c-4ac4-8701-fc0759bc05a0.png)

Seems to be resolved now
