### ISSUE TITLE
[Mobile Payments] Distribute content of modals more evenly

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4956]
Props @adamzelinski in https://github.com/woocommerce/woocommerce-ios/pull/4931#issuecomment-914939754

> Also, may we please vertically center this information within the bounds. it looks a little bottom-heavy.

<img width="804" alt="bottom-heavy" src="https://user-images.githubusercontent.com/1595739/132557239-55e94775-47a8-40bf-8f41-a31d65395677.png">

**Comment by koke** [comment]
This should all be handled correctly after #4919 and #4940
