### ISSUE TITLE
[CPP Onboarding] Wrong error when trying to manage In-Person Payments as Shop Manager

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#4960]
I logged in to my test store with a different account than usual that has the Shop Manager role. When I go to Settings > In-Person Payments, I see an error saying the WCPay plugin isn't installed:

![Simulator Screen Shot - iPhone 12 mini - 2021-09-09 at 10 53 54](https://user-images.githubusercontent.com/8739/132655485-ea7a1a7d-e466-47f0-9a2d-3148a967271f.png)

**Comment by allendav** [comment]
I see this as well. Started thread with proposed solution internally: paJDYF-2K2-p2

**Comment by allendav** [comment]
Resolved by #5259 and #5262
