### ISSUE TITLE
Shipping Labels: Address validation issues

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#4971]
Currently address validation on Edit Address screen is having several issues:
- Phone validation is checking for US phone number requirement regardless of the selected country. Other countries should not be applied the same check with US.
- Validation errors require tapping on action buttons to be cleared. Local validation should be handled on value changes instead.
- When switching country, state field is empty but the address's state is not actually updated. So when switching from US to Australia, new state is required but tapping on "Use Address as Entered" allows the address to keep the US state.

Internal reference: p5T066-2En-p2#comment-9902

**Comment by pmusolino** [comment]
I'm closing this issue since it was fixed in release 7.5.
