### ISSUE TITLE
Shipping Labels: custom package form input/validation issues with decimal values

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#4987]
For validating the values in the custom package form, we should convert internally all the commas , to dots `.`. The reason is that if you select a country (eg. Italy) where the separator for the floating-point numbers is the comma and not the dot, the validation will return false (and also the keyboard will show only the comma), so will be impossible to insert a floating-point number here. We can use the solution introduced by @itsmeichigo here https://github.com/woocommerce/woocommerce-ios/pull/4970#discussion_r707307287 for a similar issue.

<img src="https://user-images.githubusercontent.com/495617/133233190-0af1ef43-cfcd-4923-8b27-93fa3d494748.png" width=300 />

**Comment by itsmeichigo** [comment]
I think this is fixed in #5002, should we close this @pmusolino?

**Comment by pmusolino** [comment]
Yes right 👍
