### ISSUE TITLE
[Mobile Payments] Update SDK to pick up didUpdateDiscoveredReaders fix when it becomes available

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4991]
This will fix the problem where a reader that fails to connect cannot be immediately re-discovered for a re-attempt

See https://github.com/stripe/stripe-terminal-ios/issues/104 and https://github.com/woocommerce/woocommerce-ios/pull/4957

**Comment by ctarda** [comment]
Related to #5142

**Comment by allendav** [comment]
Confirmed fixed with https://github.com/woocommerce/woocommerce-ios/pull/5277#issuecomment-951327870
