### ISSUE TITLE
[Mobile Payments] Crash may occur on entering In-Person Payments

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4995]
Highly intermittent. Props @jaclync 

> I can’t reproduce it consistently but it happened twice on launches about half an hour apart, the first one right after updating the app from TestFlight. It looks like the crash is on a calculated localizable attributed string for onboarding (the Learn More string)

https://github.com/woocommerce/woocommerce-ios/blob/c6f4f07ba4d7d39d6ba5362b0d6e9f4350f2d6b8/WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person%20Payments/InPersonPaymentsLearnMore.swift#L39

Props @koke for analysis pointing the finger at the use of `NSAttributedString` which itself uses `htmlToAttributedString` which can evoke the crash if the asynchronous HTML parsing completes while the view itself is in the middle of updates. paNNhX-gK-p2

**Comment by joshheald** [comment]
I think that this mainly happens on devices which don't (/have never?) have/had a card reader connected to them. 

It happens pretty consistently on the simulator... sometimes feeling like 100%, but not quite.

**Comment by Ecarrion** [comment]
Sentry issue https://sentry.io/organizations/a8c/issues/2649675472/?project=1458804

**Comment by allendav** [comment]
Hopefully this is resolved thanks to #4996 above - which goes out in 7.6 (code freeze is today)
