### ISSUE TITLE
[Mobile Payments] Move update check management to the service layer

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#5024]
Instead of having view models each attempting to manage this state, have the card reader service layer initiate and manage update checks (to avoid attempting to ask the SDK to do two things at once - which results in an error). The service layer could also cache the most recent update check for a reader, perhaps for a day, to avoid re-fetching it frequently.

Props @koke https://github.com/woocommerce/woocommerce-ios/pull/5008#pullrequestreview-758361491

**Comment by koke** [comment]
Keep in mind that the 2.0 SDK will do this checks automatically when connecting, so we might not need to do worry about this for too long 😅

**Comment by ctarda** [comment]
Closing this for now. As mentioned, the SDK 2 fixes the problem for us
