### ISSUE TITLE
[Mobile Payments] Launch card present payments (remove beta check)

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#5028]
Needed for feature launch

Right now, for beta, we check the payment gateways for any with `isCardPresentEligible` - we should no longer have that as a requirement. **Once removed, exposing In Person Payments should depend on <del>the merchant being US based</del> on-boarding, not on the gateway `isCardPresentEligible` response.**

Changes will be needed in:

- [ ] `SettingsViewController`
- [ ] `HelpAndSupportViewController`
- [ ] `OrderDetailsDataSource`

An ideal implementation will NOT replace `isCardPresentEligible` code with multiple copies of available logic in those parts of the code. A single source of truth should be considered.

**Comment by ctarda** [comment]
We have to be careful about changes to isCardPresentEligible in OrderDetailsDataSource in particular. There is some overlap with shipping labels: https://wp.me/pdfdoF-6f

For OrderDetailsDataSiurce, I would only remove the logic that checks whether the store is gated. That is, references to PaymentGatewayAccount.isCardPresentEligible.
