### ISSUE TITLE
[Mobile Payments] [SDK 2] Handle error cases when installing updates

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#5036]
Right now, updates that fail to install will fail silently with the new 2.0 UI. We should address that and show an error.

Errors to address:

- [ ] Battery level is too low to do an update (see https://github.com/woocommerce/woocommerce-ios/issues/5036#issuecomment-933725244 below) - keep in mind that we have a specific design for when the update fails because of low battery
- [ ] Lost connection to reader during update
- [ ] ???

_Originally posted by @allendav in https://github.com/woocommerce/woocommerce-ios/pull/4974#discussion_r713303946_

**Comment by allendav** [comment]
I end up here after connecting when an update is detected but my battery is only at 33%:

![IMG_0172](https://user-images.githubusercontent.com/1595739/135901433-11fe4114-3e8b-4cea-9773-1248fd196dee.PNG)

We should instead display a too-low-battery message.

I expect closing this issue will need to be done iteratively, starting with the most likely failure scenarios (like too-low-battery) first

**Comment by koke** [comment]
Fixed in #5073 and #5109
