### ISSUE TITLE
[Mobile Payments] Rewrite Card Reader Settings Views in SwiftUI

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#5040]
Replace views in WooCommerce/Classes/ViewRelated/Dashboard/Settings/CardReadersV2 with SwiftUI equivalents to 1) match the use of SwiftUI in on-boarding including Combine integration and 2) improve development velocity (over Interface Builder), and 3) simplify code reviews (simpler diffs)

Don't panic. No planned sprint.

**Comment by ctarda** [comment]
I'll close this one for now as well. We can reopen later if we really need to modify any of these views.
