### ISSUE TITLE
Not able to set Digital/Downloadable products via the app

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#5063]
From 4327111-zen 

**Describe the bug**

The iOS app seems to miss the Downloadable file option for Digital Products type. This is how it looks in Android:
<img width="245" alt="Screenshot 2021-09-27 at 09 51 04" src="https://user-images.githubusercontent.com/3812076/134866622-88b0846e-0b00-4190-a406-b7254c63e476.png">

However in iOS the option does not appear, the last one is `Linked Products`

**To Reproduce**
1. Create a digital/downloadable product from the browser:
<img width="752" alt="Screenshot 2021-09-27 at 10 37 20" src="https://user-images.githubusercontent.com/3812076/134873878-6b532558-5d39-4488-9f13-57cf8d475c98.png">

2. In the app, go to the product and edit it.
3. Tap on "+ Add more details"
4. See how the option to add a downloadable file is not there.

**Comment by itsmeichigo** [comment]
There seems to be a difference between iOS and Android; on iOS, we need to go to Product Settings > toggle on Downloadable Product > Done to see the "Downloadable files" row on the product form. Tapping on this row will let us upload files for the product:

https://user-images.githubusercontent.com/5533851/156295659-904f05e2-ee31-4beb-945b-9f08fcf78340.mp4

@pmusolino & @Ecarrion - I see from a quick search on the project thread that you took care of this project. Any suggestions on why there's this difference between the two platforms?

cc @ThomazFB who worked on the Android side I think.

**Comment by Ecarrion** [comment]
I don't think I worked on that 🤔 

@pmusolino do you know anything about that difference?

**Comment by pmusolino** [comment]
I didn't know anything about this difference, but testing Android it seems that how the functionality is working right now is a little bit weird. Is basically possible to enable/disable a downlodable file from the settings of a product, but enabling a product to be downloadable doesn't show anything unless you add a downloadable product from the sheet. It seems unclear to me as a user.

**Comment by shiki** [comment]
Based on the discussion, it doesn't look like there is anything to fix here.
