### ISSUE TITLE
Digital/Downloadable products can only be images

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#5064]
Reported on 4327111-zen , related to https://github.com/woocommerce/woocommerce-ios/issues/5063

**Describe the bug**

When we try to attach a digital file to a Digital/Downloadable product via the app, the only available selectable option seems to be images (not other filetypes like .txt, .pdf, etc, .. )

**To Reproduce**
1. Edit a Digital/Downloadable product from the app. If you need to create one, this needs to be done via the browser ( #5063 )
2. Tap on "+ Add more details"
3. Tap on "Downloadable files"
4. Try to attach any non-image file from your device, media library, or URL. These are filtered down and do not show.

**Comment by itsmeichigo** [comment]
This is more like an enhancement request to me, updating the issue labels to reflect that.
