### ISSUE TITLE
Order Editing: Autofocus text field when editing order note

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#5110]
There is no simple way to autofocus a text field on iOS 14 with `SwiftUI`.

We need to investigate a workaround for it or only add autofocus for iOS 15+

ref: https://developer.apple.com/documentation/swiftui/menu/focused(_:)

**Comment by shiki** [comment]
I'd say we timebox the iOS 14 investigation and if we don't find a solution, then only implement for iOS 15.

**Comment by Ecarrion** [comment]
Make sense, but I "think" we can't use any iOS 15 only API until CI gets updated to use Xcode 13.

**Comment by pmusolino** [comment]
If I'm not wrong, @itsmeichigo found a solution to this while she was working on Shipping Labels. @itsmeichigo did you run into the same problem or am I wrong?

**Comment by pmusolino** [comment]
BTW, I opened the PR for updating our CI to Xcode 13 https://github.com/woocommerce/woocommerce-ios/pull/5311

**Comment by itsmeichigo** [comment]
Actually no, I didn't encounter this issue during Shipping Labels 😅. But speaking from my (very limited) experience, the easiest way to handle autofocus prior to iOS 15 is to use the [introspect hack](https://github.com/siteline/SwiftUI-Introspect). Or we can create a `UITextField` wrapper that allows option to trigger focusing.

**Comment by Ecarrion** [comment]
I'm assigning this to a trial candidate

**Comment by anas-p** [comment]
@Ecarrion 
PR for updating CI to Xcode 13 has been merged (#5311), so shall I do it this way https://developer.apple.com/documentation/swiftui/menu/focused(_:) for iOS 15?

**Comment by Ecarrion** [comment]
@anas-p, yes please 🙏
