### ISSUE TITLE
Order Editing: Show empty row for shipping address 

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#5114]
The iOS app does not show a row for empty shipping addresses, which removes the ability to the merchant to edit it.

@adamzelinski, should we add an empty row for it? How do you envision it?

### Current
<img width="415" alt="Screen Shot 2021-10-01 at 10 53 04 AM" src="https://user-images.githubusercontent.com/562080/135650986-5fe9623f-60a0-4714-9749-df3454aba38e.png">

**Comment by ghost** [comment]
If there is an empty shipping address we could just use the billing address as the shipping and then allow them to edit. Or we could just show action so the merchant can add one as the empty state.
Do you have any thoughts or concerns about either of these? @Ecarrion 
<img width="541" alt="Screen Shot 2021-10-05 at 6 36 55 pm" src="https://user-images.githubusercontent.com/74938219/135980812-ac62607b-0135-4f33-99ea-cc65d8ec761b.png">

**Comment by Ecarrion** [comment]
@adamzelinski I like that design where there is an action to add the address! 
Thanks.

**Comment by ghost** [comment]
Perfect let's go with that then :) @Ecarrion
