### ISSUE TITLE
[Mobile Payments] Show items at full price on receipts

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#5141]
Found during #5127

## Description
Discounts are pre-applied to each item, both in the receipt and the order view. The order view has a "Product total" line, after which the discount line is subtracted, and the taxes/shipping included below that too, which makes sense, though the products themselves won't add up to the product total.

Order|Receipt
-|-
![Screen Shot 2021-10-05 at 11 50 08](https://user-images.githubusercontent.com/8739/136001442-79ff7db9-ccd0-41e0-a7e0-d779f67d1510.png)|![Screen Shot 2021-10-05 at 11 50 13](https://user-images.githubusercontent.com/8739/136001454-29d2a136-592d-4004-93c6-707a16be4ac3.png)

Web|Email
-|-
![Screen Shot 2021-10-05 at 11 51 18](https://user-images.githubusercontent.com/8739/136001492-029fd8cc-c3c7-484f-adc0-b0f1510f9655.png)|![Screen Shot 2021-10-05 at 11 52 29](https://user-images.githubusercontent.com/8739/136001498-e2369281-151f-4262-bd75-dca4dd52dd6a.png)

The web and email approach seems better: display the products at full price, subtotal them, then subtract the discount and add fees/tax/shipping to give the grand total.

**Comment by joshheald** [comment]
@woocommerce/mobile-designers What do you think about moving receipts and Order Details to mirror the web/app re: prices and totals above?

**Comment by joshheald** [comment]
@koke Added this as you called out 😊

**Comment by Garance91540** [comment]
Hi! Aligning with core sounds good to me!
