### ISSUE TITLE
[Order Editing] "Use as {Billing|Shipping} address" toggle changes can't be saved alone

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#5148]
**Describe the bug**
When editing an address in Order Details, changes to the `Use as {Billing|Shipping} address` toggle do not enable the `Done` button, so can't be saved unless other changes are made as well.

**To Reproduce**
1. Go to Orders tab
2. Open a processing order with different Billing and Shipping addresses
3. Tap the pencil icon next to Shipping address
4. Set the toggle to on
5. Note that the `Done` button is unavailable
6. Cancel and check the other address anyway
7. Note that it has not been updated to match.

**Screenshots**

https://user-images.githubusercontent.com/2472348/136225911-125d91fc-af2b-4b15-8cca-7e278c781331.mp4

**Expected behavior**
Changing the toggle alone should enable the `Done` button and allow the address to be saved across to its alternate.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13 Pro
- iOS version: iOS 15
- WooCommerce iOS version: 7.7.0

**Comment by selanthiraiyan** [comment]
Hello 👋 
I would like to take a look. Please assign this to me. 
Thanks!
