### ISSUE TITLE
[Shipping Labels] Editing international Ship To address uses numeric keypad on Postcode field

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#5157]
**Describe the bug**
The edit address screen in the Shipping Label purchase flow shows the numeric keyboard when editing `Postcode`. The numeric keyboard does not allow entry of alphabetical characters, which are part of many international postcodes. This means that the postcode cannot be corrected without leaving the Shipping Label purchase flow

**To Reproduce**
1. Go to Orders
2. Open an international order, e.g. to the UK, with an incorrect address
3. Tap `Continue` through the `Ship from` screen, making any required corrections to progress
4. On the `Ship to` screen, tap in the postcode field
5. Try to enter or edit letters – this is not possible.

**Screenshots**

https://user-images.githubusercontent.com/2472348/136404649-3a333d91-bfa9-4e9a-8da8-df291c10a001.mp4

**Expected behavior**
An alpha-numeric keyboard should be shown, so that the full postcode can be edited.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 7 Plus
- iOS version: iOS 14.8
- WooCommerce iOS version: 7.7

**Comment by itsmeichigo** [comment]
Thanks for reporting @joshheald! We clearly missed this case for international orders!
