### ISSUE TITLE
Provisioning profile "Woocommerce Development" doesn't include the com.apple.developer.passkit.pass-presentation-suppression entitlement

### ISSUE THREAD

**Issue by iammarsaeed** [woocommerce/woocommerce-ios#5198]
Provisioning profile "Woocommerce App Provisioning Profile" doesn't include the com.apple.developer.passkit.pass-presentation-suppression entitlement

**Comment by shiki** [comment]
@AliSoftware or @jkmassel Can you please help me triage this issue? 😅

**Comment by shiki** [comment]
Hi, @ammar97s! Would you mind sharing more details about what you were trying to do and how you got this error? Some screenshots would be helpful too if possible! TIA!

**Comment by shiki** [comment]
Will close this for now as it has gone stale. We can always reopen if we have more info.
