### ISSUE TITLE
[Mobile Payments] Link to BBPOS User Manual from In-Person Payments Settings

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#5199]
A link to the BBPOS user manual that must be available for users within three taps from the app’s “home” screen for compliance with FCC Part 15 rules

pdfdoF-cg-p2

<img width="361" alt="Screen Shot 2021-10-12 at 11 53 10 AM" src="https://user-images.githubusercontent.com/1595739/137012801-2f3644cb-4ef2-4330-9680-cc4bfe9fcb74.png">

**Comment by ctarda** [comment]
Closing as done. Not sure why it didn't get closed automatically
