### ISSUE TITLE
Shipping Labels: Package Type options disappear in landscape

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#5200]
## Describe the Bug

The Package Type options are not visible when in landscape mode.

## To Reproduce

I mainly followed the initial steps in https://github.com/woocommerce/woocommerce-ios/pull/4976. 

1. Open an order detail that is eligible for a shipping label.
2. Tap the button "Create Shipping Label.”
3. Confirm "Ship From" and "Ship To.”
4. In the package details section, tap on “Package Selected.”
5. Tap Create new package.
6. Tap Package Type
7. Switch to landscape mode.

## Screenshots

https://user-images.githubusercontent.com/198826/137015447-b1ed5243-d3e8-47dc-9806-6932d1db5142.mp4

## Expected Behavior

The options should be visible.

## Isolating the Problem 

- [x] I can reproduce this bug consistently using the steps above.

## Mobile Environment

- Device: iPhone 8 Plus
- iOS version: 14.8
- WooCommerce iOS version: 7.7

---

cc @pmusolino @rachelmcr @itsmeichigo

**Comment by pmusolino** [comment]
@shiki I tried to replicate it, but I wasn't able. Can I ask you to test it with the latest version on `develop`?

https://user-images.githubusercontent.com/495617/137109205-494c3d73-e7c7-4b81-b61c-0226c69b8093.mp4

**Comment by itsmeichigo** [comment]
I can reproduce this on my iPad. It seems to be an interesting case when embedding a ScrollView inside a NavigationView, I'll see what I can find 😄

**Comment by pmusolino** [comment]
@itsmeichigo what version of iOS are you running on your iPad?

**Comment by itsmeichigo** [comment]
It's iOS 14.8. I haven't tried with iOS 15 - this seems like the default navigation view style on iPad is `ColumnNavigationViewStyle`, which without proper setup is messed up.

**Comment by itsmeichigo** [comment]
Confirmed that this happens on iOS 15 too, for devices with regular width for horizontal size class.
