### ISSUE TITLE
Shipping Labels: ITN dialog is presented twice

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#5202]
## Describe the Bug

After dismissing the dialog about ITN, a similar dialog is presented again but dismissed right away.

## To Reproduce

1. Create a shipping label for an order with an international address.
2. In the Customs step, tap Continue. 
3. Enter a random invalid number in the ITN field. 
4. Tap on Learn more below it.

## Screenshots

https://user-images.githubusercontent.com/198826/137017359-0fc0d668-e027-4532-ba13-14714213fd60.mp4

## Expected Behavior

No other dialog should be shown.

## Isolating the Problem 

- [x] I can reproduce this bug consistently using the steps above.

## Mobile Environment

- Device: iPhone 8 Plus
- iOS version: 14.3
- WooCommerce iOS version: 7.7

**Comment by itsmeichigo** [comment]
Closing this because the issue was fixed in #5207.
