### ISSUE TITLE
Notifications: Mark as Seen

### ISSUE THREAD

**Issue by jleandroperez** [woocommerce/woocommerce-ios#521]
### Details:
As of Release 0.13 / MVLP, we've disabled the `mark as seen` service call, because all of the potential buggy interactions with other WordPress Client.

Whenever the backend is enhanced, and we actually have proper "Buckets" support, let's re-enable the Mark as Seen Endpoint call.

**Comment by mindgraffiti** [comment]
iirc, we are still receiving bug reports from users because this isn't implemented.

**Comment by shiki** [comment]
I'm closing this for now until we have more improvements on the backend.
