### ISSUE TITLE
[Mobile Payments] Updating Chipper with v2 SDK loops when battery low

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#5213]
**Describe the bug**
Updating the reader using the [`feature/stripe-sdk-2` branch](https://github.com/woocommerce/woocommerce-ios/tree/feature/stripe-sdk-2), and a reader with low battery, results in a failure loop.

**To Reproduce**
1. Turn on and connect to a reader with a low battery
2. Go to `⚙️ > In-Person Payments > Manage card reader` 
3. `Connecting to reader` screen is shown (0:03-0:07)
4. Wait, and you'll see an update screen which only gets to 1% (0:08-0:13)
5. The `Please charge reader` screen is shown, tap `Cancel` (0:13-0:15)
6. The `Connecting to reader` screen is shown, repeating steps 3-5 (0:16-0:32)
7. The way to get out of the loop is to turn off the reader or (maybe) cancel before the `Please charge reader` is shown

**Screenshots**

https://user-images.githubusercontent.com/2472348/137152787-346de63b-5419-46f6-ac4f-6cc042726c75.mp4

**Expected behavior**
After cancelling on the `Please charge reader` screen, the update/connection flow should stop and the user should be able to interact with the app.

**Mobile Environment**
Please include:
- Device: iPhone 7 Plus
- iOS version: 14.8
- WooCommerce iOS version: `feature/stripe-sdk-2`

**Comment by allendav** [comment]
To reproduce this loop, one must have successfully connected to the reader successfully before it gets into the low battery + needs update state. This results in the reader becoming stored as the "known reader." And when there is a known reader, the connection flow triggers automatically (hence creating this loop.)
