### ISSUE TITLE
[Mobile Payments] [SDK 2] Are we distinguishing mandatory from required card reader updates?

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#5216]
> we should make sure we are getting a “required” flag on these and permitting them to be skipped

**Comment by ctarda** [comment]
From the docs:
https://stripe.com/docs/terminal/sdk-migration-guide#bluetooth-reader-updates

> Mandatory updates will be dispatched and automatically installed by the Terminal SDK when the reader is connected; that reader will be unable to take payments until the update is complete. We expect mandatory updates to be dispatched infrequently: when there is a security or compliance issue, or when a reader crosses a country border.
> All other reader updates are optional, and won’t block payments. You can defer optional updates, but they become required updates if you don’t install them by a certain date

https://stripe.com/docs/terminal/readers/bbpos-chipper2xbt#updating-reader-software

**Comment by ctarda** [comment]
Also: https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPTerminal.html#/c:objc(cs)SCPTerminal(im)installAvailableUpdate

**Comment by allendav** [comment]
This has already been fixed in #5126 and especially #5027
