### ISSUE TITLE
In-Person Payments: minimum plugin version warning

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#5218]
The app should display an error if the active store has an outdated WooCommerce Payments plugin but we received a report that no such error is provided and sometimes another error is displayed.

Reported at internal link p5T066-2I5-p2#comment-10386 the following error was shown after trying to collect a payment on a store with WCPay 2.6.1:

> Payment failed
> The operation couldn't be completed.
> (Networking.DotcomError error 0.)

<img src="https://user-images.githubusercontent.com/1119271/137217289-00e551fa-e6ed-4243-bbb8-52b418e121bd.png" width="270" alt="image">

Possibly related: https://github.com/woocommerce/woocommerce-ios/issues/5077

**Comment by designsimply** [comment]
@allendav @ctarda I tried testing this a few times but have been getting different results. Please see internal reference p5T066-2I5-p2#comment-10386 for additional details. I still think it's worth a look to see if you'd like to make any update for this for the 7.7 release even though it's late in the code freeze. Please let me know if I can do anything else to help!

**Comment by ctarda** [comment]
Thanks @designsimply . We'll move this to the top of the queue

**Comment by designsimply** [comment]
Thank you! I think it's too late now to make any updates to the 7.7 release and I would recommend either targeting 7.8 if you want to make any changes right away or working with @jkmassel if you want to make a hotfix to 7.7 (which is typically built on the last Friday of the release I believe—and that's today!). fwiw, I was only able to replicate the bug from the original report in p5T066-2I5-p2#comment-10386 if I switched to that test site (my own test site didn't show the bug) and with that in mind I would recommend targeting 7.8 with a note we should keep a close eye on it and move it up in priority if we get user reports about it. What I am hoping is that people won't run into the problem of having an outdated WooCommerce Payments plugin if they are early adopters in the first two weeks this feature is out 😁 (and also really new users will need to have time to have a card reader shipped as well, which gives extra space).

**Comment by allendav** [comment]
Right now, `develop` only requires 2.5 or higher:
https://github.com/woocommerce/woocommerce-ios/blob/9d35a579e780087e68f3267db34f237e8789ab04/WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person%20Payments/CardPresentPaymentsOnboardingUseCase.swift#L242

On `feature/stripe-sdk-2` we bumped to 3.1 already: https://github.com/woocommerce/woocommerce-ios/pull/5166 but that was because we needed the reader locations API added recently to the WCPay plugin

I successfully tested connecting to a reader in settings and in collect-payments flows and collecting a payment with WCPay 2.6.1 and `develop.` I have seen the Networking.DotcomError error 0 at other times - it seems to be a highly intermittent glitch with one of my test sites as well.

**Comment by allendav** [comment]
Another case of Networking.DotcomError error 0:

https://github.com/woocommerce/woocommerce-ios/issues/4551#issuecomment-882842417

**Comment by allendav** [comment]
I haven't been able to trigger a DotcomError error 0 this way, but did run into this today while looking into this:

https://github.com/woocommerce/woocommerce-ios/issues/4960

See also paJDYF-2K2-p2

**Comment by allendav** [comment]
I can create a DotcomError 5 (noRestRoute) if I attempt to collect payment as a Shop Manager with a store running WooCommerce Payments 2.3.3

It is failing on the request to create a customer for the order `payments/orders/{orderID}/create_customer` which was added in 2.4.0 (three months ago)

Edit: Related: https://github.com/woocommerce/woocommerce-ios/issues/4960

**Comment by allendav** [comment]
Update: It is possible that the fix for #4960 in https://github.com/woocommerce/woocommerce-ios/pull/5259 may address this issue as well.

**Comment by allendav** [comment]
#5259 should be sufficient for this - recommend opening a fresh issue if a problem resurfaces
