### ISSUE TITLE
[Mobile Payments] Add unit tests for StripeCardReaderService

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#5232]
Props @joshheald for [noticing](https://github.com/woocommerce/woocommerce-ios/pull/5192#discussion_r728271103)

**Comment by ctarda** [comment]
There are things we can test, some other we still can not. 

I did a quick run of this, and apparently, we still need to provide a token, even if the SDK is in test mode. p91TBi-4Es-p2 for reference.

I am going to close this one for now, happy to reopen if I'm wrong and testing a bit more is actually possible
