### ISSUE TITLE
Increase refresh timeouts for Stats throttling

### ISSUE THREAD

**Issue by ealeksandrov** [woocommerce/woocommerce-ios#5237]
We keep getting connection/performance reports. Stats tab is contributing since it triggers many concurrent requests at once (even if we throttle them with minimal refresh timeout). We should apply small patches to sync/throttling logic to cut load down.

From suggestion in p4a5px-2LT-p2#comment-12407:
> 12 requests as often as every 30 seconds still seems like a lot. Could we limit weekly and monthly stats requests to every 1 hour and yearly requests to every 12-24 hours? Can we make the requests in the background instead of when you switch to that tab?

Tasks list is a draft, some maybe too complex to implement now, especially since we plan to reorganize Stats page.

- [x] increase default (daily) refresh limit
- [x] limit weekly/monthly/yearly timeouts separately
- [x] delay weekly/monthly/yearly data requests until that tab is open https://github.com/woocommerce/woocommerce-ios/pull/6890
- [x] refresh currently opened tab (instead of default/minimal daily) https://github.com/woocommerce/woocommerce-ios/pull/6890
- [ ] look into possible background or notification refresh, instead of `viewDidAppear`

**Comment by shiki** [comment]
@ealeksandrov Do you have any updates on this task? 🙂

**Comment by ealeksandrov** [comment]
@shiki yes! I have first 2 tasks done from the list above, will prepare PR on this week.

**Comment by thabotswana** [comment]
There's a similar report in 4464744-zen

>Doesn't let me connect from iPhone while Android does.
I select the shop, I press the process button but then it stays there

App version: 7.9.0.1

Also seeing this error in the app log:

`2021/11/17 22:39:06:374  <> Mapping Error: keyNotFound(CodingKeys(stringValue: "id", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"id\", intValue: nil) (\"id\").", underlyingError: nil))`

**Comment by thabotswana** [comment]
@ealeksandrov We've encountered another report which looks similar in 4466209-zen

>The data says can not load.

>On android phone it works but will not work on iPhone.

App version: 7.9.0.1

**Comment by reginabally** [comment]
@thabotswana I noticed some issues with the Jetpack connections for the two cases you reported here so I sent them some troubleshooting steps. While the iOS app needs some performance improvements, the sites will still need healthy Jetpack connections to communicate with the app.

**Comment by ealeksandrov** [comment]
@reginabally yep, getting 503,403 or broken mapping won't be solved by performance improvements. I'll keep an eye on tickets above.

**Comment by reginabally** [comment]
Thank you for verifying my approach @ealeksandrov. However, I wasn't sure what is causing the broken mapping as shared in [this comment](https://github.com/woocommerce/woocommerce-ios/issues/5237#issuecomment-972809245). Would it also relate to a broken Jetpack connection?

**Comment by ealeksandrov** [comment]
> I wasn't sure what is causing the broken mapping as shared in this comment. Would it also relate to a broken Jetpack connection?

The message is about missing `id` property on top level. Likely it's completely empty/errored response - so broken/buggy Jetpack connection can be the reason.

**Comment by ealeksandrov** [comment]
Closing as most improvements were implemented in https://github.com/woocommerce/woocommerce-ios/pull/6890
