### ISSUE TITLE
[Mobile Payments] [SDK 2] Optional updates message / button out of sync

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#5238]
Observed on feature/stripe-sdk-2 today when running against simulated readers

![IMG_0198](https://user-images.githubusercontent.com/1595739/137802264-cce34482-b875-453d-beee-df2dfe5c3296.PNG)

**Comment by ctarda** [comment]
Closing. It is supposed to be fixed in #5240
