### ISSUE TITLE
Set receipt_email on PaymentIntents to trigger automatic email action on Stripe's backened

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-ios#5283]
The app currently sets `customer_email` field on PaymentIntent which is used by WCPay backend. The goal of this task is to also set receipt_email which will be used by Stripe's backend to automatically send receipts to customers.

More info pdjVC1-5Z-p2

cc @ctarda @allendav @joshheald

**Comment by joshheald** [comment]
I've confirmed that `receipt_email` is sent to Stripe when we create the payment intent, and that they include it in the response to the `https://api.stripe.com/v1/payment_intents/{id}/confirm` request that the SDK makes, so this is already in place 💪
