### ISSUE TITLE
[Mobile Payments] Very first reader connection, if done through the order flow, fails

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#5285]
Allowing Bluetooth and trying again succeeds.

Observed on a branch off of today's `develop` (SDK 1.4 based)

To reproduce:
- completely uninstall the app
- install the app and sign in
- proceed to orders and tap on collect payment within a qualified order
- note the failure dialog that appears behind the system bluetooth prompt
- note that trying to collect payment again succeeds

NOTE: At least we should update "Generic bluetooth error" as something more like "Unable to initialize Bluetooth. Ensure Bluetooth is enabled and try again."

<img width="321" alt="Screen Shot 2021-10-26 at 12 28 55 PM" src="https://user-images.githubusercontent.com/1595739/138948133-5e4edb84-abc5-445e-beed-126f6908f53a.png">

<img width="320" alt="Screen Shot 2021-10-26 at 12 32 18 PM" src="https://user-images.githubusercontent.com/1595739/138948362-5e4343c7-c31d-49b9-913a-af126184f810.png">

https://user-images.githubusercontent.com/1595739/138948149-de3a1e6f-3e33-4593-aeec-1e4aa4b31455.mp4

**Comment by allendav** [comment]
@ctarda this does not appear to be a problem on the SDK 2 branch. We we merge SDK 2 to `develop` we can reconfirm, so I suggest we park this for until after the SDK 2 merge planned for this sprint

![1](https://user-images.githubusercontent.com/1595739/139709514-ea68776b-2836-4c0f-bc59-7cae490c48ba.PNG)
![2](https://user-images.githubusercontent.com/1595739/139709525-ca4bbd3b-0e49-4664-952b-ea34d308dbdd.PNG)
![3](https://user-images.githubusercontent.com/1595739/139709527-00129b37-e689-43f1-95cb-cb16aa2ebab1.PNG)
![4](https://user-images.githubusercontent.com/1595739/139709534-2b9adad7-294b-424e-880f-2c34d33b3983.PNG)

**Comment by ctarda** [comment]
Sounds good! I'll close it 😊
