### ISSUE TITLE
iPhone Tab Bar appears in Dark Mode when rest of app and iPhone are in Light Mode when built with Xcode 13

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#5286]
Observed on an iPhone 12 Pro Max with a branch off of today's develop built with Xcode 13. Note that although the iPhone was set for Light Appearance, the Tab Bar appears Dark and the active icon (in this case, Orders) is not visible at all:

<img width="462" alt="Screen Shot 2021-10-26 at 12 49 16 PM" src="https://user-images.githubusercontent.com/1595739/138950572-25560cf3-a047-4037-af72-c54a39cf7d07.png">

Also observed several, possibly related AttributedText warnings during the build:

<img width="1154" alt="Screen Shot 2021-10-26 at 12 55 39 PM" src="https://user-images.githubusercontent.com/1595739/138951478-fbf964a8-b151-48d0-84bd-210e9daa72ed.png">

Does not appear to be a problem on iPad (8th gen)

**Comment by pmusolino** [comment]
I'm going to close this issue since there was another one already opened and with a solution in it 👍  https://github.com/woocommerce/woocommerce-ios/issues/5018
