### ISSUE TITLE
[Mobile Payments] [SDK 2] Bump minimum version in doc from 2.9 to 3.2.1

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#5307]
SDK 2 requires the WCPay location REST API which means we will need an update to https://docs.woocommerce.com/document/payments/getting-started-with-in-person-payments-with-woocommerce-payments/ to change the minimum version from 2.9 to 3.2.1

See:

https://github.com/woocommerce/woocommerce-ios/blob/feature/stripe-sdk-2/WooCommerce/WooCommerceTests/ViewRelated/CardPresentPayments/CardPresentPaymentsOnboardingUseCaseTests.swift#L374-L375

SDK 2 is expected to merge to develop on Nov 1, targeting release 8.0 which is expected to release Nov 28.

Related #5295

**Comment by ctarda** [comment]
Doc updated. Closing
