### ISSUE TITLE
Handle tapping in-app notices from remote notifications (new order and review)

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#5330]
Right now, when the app receives a remote notification in the foreground, an in-app notice is shown at the bottom about the notification. Tapping on the notice just dismisses it. It might be a good idea to handle the notice tap action the same way when tapping on a push notification from the Notification Center (switching to the store of the notification and showing order/review details).

### Decision ([Adam's comment](https://github.com/woocommerce/woocommerce-ios/issues/5330#issuecomment-982294245))

> I definitely agree that we should have the action so the merchant can decide if they want to actually swap screens / stores. I think for now I would just use the term 'view' for both types as switch store to view is a pretty long string.

- [x] Let's also track the event when the user taps on the "View" CTA to view notification details: `view_in_app_push_notification_pressed`

<img src="https://user-images.githubusercontent.com/1945542/143820808-472d2263-091b-40e4-87ff-3551cbf9af77.jpg" width="300" />

---

### Original discussion

Is this an intuitive behavior, tapping to switch store and view notification details? As a user, I might be in the middle of a task (like adding/editing a product) when seeing this in-app notice. In this case, I might just want to "tap to dismiss." Some other time, I might be curious about the notice and want to "tap to view details." What's a good way to handle this 🤔 does it make sense to show an alert or action sheet with two actions to dismiss or view details? 

<img src="https://user-images.githubusercontent.com/1945542/140020065-12e7d552-05f0-4e02-a856-ff0a1a83d525.jpg" width="300" />

**Comment by shiki** [comment]
@astralbodies Do you remember how this was supposed to work? 

@anitaa1990 @jaclync This doesn't seem to exist in Android based on my possibly incorrect testing. Though the main difference is that Android will still display the push notification in the status bar even if the app is in the foreground.

**Comment by anitaa1990** [comment]
> @anitaa1990 @jaclync This doesn't seem to exist in Android based on my possibly incorrect testing. Though the main difference is that Android will still display the push notification in the status bar even if the app is in the foreground.

We have never had that functionality in the android side, although I remember seeing this on iOS. I'm not sure why this behaviour is different though on both platforms 😅 

There are a bunch of different SnackBars that can be displayed at the bottom of the screen though on android, like the offline notification and now with Jetpack CP project, we would display an Install Jetpack banner as well. So it would be good to keep the behaviour the same on android.

On iOS though, I don't think we have a visible notification bar at the top of the screen so it makes sense to display a notification in the app maybe 🤷‍♀️

**Comment by jaclync** [comment]
This issue was raised in the call for testing (p5T066-2Q1-p2 and https://github.com/woocommerce/woocommerce-ios/pull/5299#issuecomment-979646583) twice - maybe we can add an action to the notice for users who want to switch stores and view the notification details?

notification from a different store | notification from the same store
-- | --
<img src="https://user-images.githubusercontent.com/1945542/143820359-1a1ce916-b032-41fb-aae9-05d01a3dbfd5.jpg" width="300" /> | <img src="https://user-images.githubusercontent.com/1945542/143820808-472d2263-091b-40e4-87ff-3551cbf9af77.jpg" width="300" />


Confirming with @adamzelinski, feel free to suggest a better copy!

**Comment by ghost** [comment]
Hey there, @jaclync I definitely agree that we should have the action so the merchant can decide if they want to actually swap screens / stores. I think for now I would just use the term 'view' for both types as switch store to view is a pretty long string. 

CC @anitaa1990

**Comment by jaclync** [comment]
Hi @woocommerce/mobile-designers! What do you think of showing the in-app notices vs. iOS push notifications (they stay in the Notification Center if not acted immediately) while the app is in the foreground?

In-app notices | iOS push notification
-- | --
![IMG_3426](https://user-images.githubusercontent.com/1945542/149687156-82b9b265-7dcd-4de5-9964-92bcaa4befa8.PNG) | ![IMG_3424](https://user-images.githubusercontent.com/1945542/149687151-05832e4a-d243-40b6-8732-4f9439a17317.PNG)

**Comment by ghost** [comment]
Hey, @jaclync I think we should just stick with the iOS push notifications here as we already have quite a few bottom banners which could make things a little messy. If a merchant has notifications turned off they'll still receive the in-app badges anyway so they won't miss out.

**Comment by jaclync** [comment]
The update to show iOS push notifications based on the decision above is in a separate issue https://github.com/woocommerce/woocommerce-ios/issues/5990 now. Closing this issue!
