### ISSUE TITLE
[Mobile Payments] Reported reader battery level does not update

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#5333]
I found this while testing #5322, and needed to get the card reader to below 50% battery.

## Repro

This was done with a Chipper reader, I don't have an M2 to check with.

1. Navigate to `⚙️ > In-Person Payments > Manage Card Reader`
2. Connect to a card reader and note the battery percentage
3. Use the reader for some time, maybe half an hour (I suggest starting a chip payment, and leaving the card in so the payment does not complete and the reader stays awake. The beeping can be a bit annoying though!)
4. Return to `⚙️ > In-Person Payments > Manage Card Reader`
5. **Observe that the reported battery percentage has not updated since step 2**
6. Disconnect and reconnect the reader
7. **Observe that the battery percentage has reduced**

## Expectation

The reader's battery percentage should be updated at least when re-entering the card reader screen. Not updating it could give merchants who are using the reader all day and checking their battery a false sense of security.

**Comment by allendav** [comment]
This is a problem actually with the SDK and/or Chipper

**Comment by joshheald** [comment]
That's annoying. Does it affect M2 as well?

**Comment by allendav** [comment]
There is a path forward with a bit of a workaround: https://github.com/stripe/stripe-terminal-ios/issues/121#issuecomment-966589886
