### ISSUE TITLE
[Mobile Payments] Replace "Order reader" url with a generic one

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-ios#5367]
Goal of this task is to replace "Order Card Reader" url `https://woocommerce.com/products/bbpos-chipper2xbt-card-reader` with `https://woocommerce.com/in-person-payments/`. We plan to add support for M2 readers and the generic url will allow us to update the webpage without the need to release a new version of the app.

More info pdfdoF-ea-p2

**Comment by joshheald** [comment]
Closed by #5381
