### ISSUE TITLE
Jetpack CP: add a row to install Jetpack in Settings

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#5369]
From Settings, let's add a row "Install Jetpack" for JCP sites under a feature flag:

<img width="306" alt="Screen Shot 2021-11-08 at 9 17 33 AM" src="https://user-images.githubusercontent.com/1945542/140680212-57faaa33-ce90-4fc7-a4aa-7d4c11907b58.png">

The integration will be in a separate issue.

**Comment by jaclync** [comment]
Let's start on this after Sharma's PR https://github.com/woocommerce/woocommerce-ios/pull/5393

**Comment by selanthiraiyan** [comment]
@jaclync Now that my PR has been merged, I would like to work on this if you think that I can do this without blocking/delaying your work.
`jetpackConnectionPackageSupport` is this the featureFlag?

**Comment by jaclync** [comment]
@selanthiraiyan For sure, your help is very much appreciated 😄 and yes, `jetpackConnectionPackageSupport` is the feature flag to show the new row for this issue. In a future issue https://github.com/woocommerce/woocommerce-ios/issues/5371, we will be showing the new row when the selected site's `isJetpackCPConnected` is `true`. All sites currently have `isJetpackCPConnected == false` for now.

Thanks again for contributing! 💟

**Comment by selanthiraiyan** [comment]
Thanks @jaclync !
I understand. I will work on this.
