### ISSUE TITLE
`ProductListViewController` is inside the wrong storyboard

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#5387]
While I was doing some work on Order List, I discovered that we put the `ProductListViewController` inside the `Orders` storyboard. It would be great to move the `ProductListViewController` out of this storyboard, because they are not related.

<img width="855" alt="Schermata 2021-11-10 alle 10 20 19" src="https://user-images.githubusercontent.com/495617/141086271-52c7b012-6d9a-4a42-bc24-5d7d63f9f4b5.png">

**Comment by shiki** [comment]
Or get rid of the storyboard altogether. 😁

**Comment by talpert022** [comment]
I'll look at this!
