### ISSUE TITLE
Notifications List: Update text in comment cell

### ISSUE THREAD

**Issue by bummytime** [woocommerce/woocommerce-ios#539]
From @kyleaparker's design review:

> Review product item (Review for Fallen Angel Candelabra) should be on it’s own line like in the MVLP design
>
> ![image_preview2](https://user-images.githubusercontent.com/154014/50229063-1039fe00-036f-11e9-8fae-d39f74f8e155.png)

We do this:

<img width="364" alt="screen shot 2018-12-19 at 9 21 31 am" src="https://user-images.githubusercontent.com/154014/50229258-83437480-036f-11e9-832b-0536f4134e44.png">

**Comment by mindgraffiti** [comment]
Ref p99K0U-1vW-p2

Per the redesign of Reviews i3, this is no longer an issue. Thanks @kyleaparker !
