### ISSUE TITLE
[Mobile Payments] Single source of update truth for Card Reader Settings View Models 

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#5417]
With the changes for SDK2, a card reader update can not just happen after connecting to a reader, but also before a reader is fully connected. #5416 includes a fix to address where this an update error was captured by the connected view model subscriber but wasn't cleared because handling (and clearing) that error was handled by the searching (pre-connecting) view model.

Net net: Both the connected view model and searching view model could use a single source of truth for updates (and perhaps a single internally self consistent source of truth for all the data they depend on.)

See also https://github.com/woocommerce/woocommerce-ios/issues/4449 - if we did this combined with reactive programming we could re-realize the views with SwiftUI and probably greatly reduce complexity (and reduce the challenge of responding to whatever future SDK changes might bring.)

**Comment by joshheald** [comment]
See related discussion in pdfdoF-gH-p2

**Comment by ctarda** [comment]
Closing for now
