### ISSUE TITLE
Product search returned no result

### ISSUE THREAD

**Issue by reginabally** [woocommerce/woocommerce-ios#5432]
**Describe the bug**
It was reported in 4452196-zd-woothemes that the product search wasn't working in the app, even when searching with a keyword in the product title. I was only able to reproduce this when I SSP to the account, this issue doesn't happen on my test site.

**To Reproduce**
1. SSP to the user's account
2. Go to the Products tab in the app
3. Search for "Baterija" and notice the app does not return a result.
4. Scroll through the product list and see that there are a few products with the same keyword in the product titles.

**Screen recording (recorded in SSP)**

https://user-images.githubusercontent.com/40906847/141883743-103d4081-ae00-453e-8994-25669cfc72cf.mp4

Another video recording shared by the user: https://www.youtube.com/shorts/j4GP_ZlHlHQ

**Expected behavior**
I would expect the app would return search results with keywords that exist in the product title.

**Mobile Environment**
Please include:
- Device: iPhone SE
- iOS version: 14.8
- WooCommerce iOS version: 7.9.0.0

Note: I'm requesting the user to perform a plugin conflict test and we will request SSR from the user and add the list of active plugins to the report.

**Comment by pmusolino** [comment]
In the current version of the app (8.6) I wasn't able to reproduce the issue using the SSP.
I'm able to search for a keyword and to see all the products with that keyword in the title:

<img src="https://user-images.githubusercontent.com/495617/156003711-36c113f8-f874-4852-a41a-8439051a658f.png" width=300 />

Closing the issue for the moment 👍
