### ISSUE TITLE
Jetpack CP: display empty view for visitor stats

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#5450]
Dependencies:
- Empty view UI https://github.com/woocommerce/woocommerce-ios/issues/5361
- JCP site detection https://github.com/woocommerce/woocommerce-ios/issues/5364

After the UI and backend are implemented, we can display the Jetpack CP empty visitor stats UI when:
- JCP feature flag is on
- Currently selected `Site`'s `isJetpackCPConnected` is `true`

**Comment by itsmeichigo** [comment]
Closing this in favor of #5451.
