### ISSUE TITLE
Simple Payments: Hide taxes

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#5484]
A nice to have would be to hide the taxes toggle if the store does not have taxes configured or properly set.

**Comment by shiki** [comment]
The current behavior is this right? → If they don't have taxes configured, then they would only see 0% and $0 in the tax field. 

I think I would rather prefer the visible 0% rather than the tax toggle disappearing.

**Comment by Ecarrion** [comment]
@shiki Yes, that is the current behavior 

![image](https://user-images.githubusercontent.com/562080/145622217-c1c1bc8b-95c5-41ba-ac7d-2c818e9c74e0.jpeg) 

Feel free to close the issue if you don't feel this is necessary 😅

**Comment by shiki** [comment]
Yeah, I think we don't need to do this. The 0% is much clearer IMO. Thanks for the screenshot!
