### ISSUE TITLE
Order Filters: add custom statuses

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#5498]
@jaclync suggested to implement a way to filter orders also by custom statuses. Custom statuses should be fetched from the web, and presented inside the order statuses filter list. We should be able to store them, but to replace them if deleted from the web.
Currently, we list just the default statuses of WooCommerce.

**Comment by JorgeMucientes** [comment]
To be aware of before implementing this: p91TBi-6Nv-p2

**Comment by mdrockwell** [comment]
User in 4619251-zd-woothemes would like to see this feature added.

**Comment by erricgunawan** [comment]
4633483-zen:

> I can change the order status to my custom ones, it’s just this new filter order status that doesn’t show my custom statuses. 

Some screenshots were included in the original report.

**Comment by solstudioim** [comment]
4783769-Zen

**Comment by pmusolino** [comment]
I'll take care of this during the next Hack Week.
