### ISSUE TITLE
Order Filters: show the order statuses instead of a number in the initial screen

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#5499]
Maybe we can show the order statuses instead of a number in the initial filters screen? It feels a bit odd seeing "2" here.

<img src="https://user-images.githubusercontent.com/1945542/142959916-1ae05d00-9c6b-4d6f-ba6b-84ce78238eb2.png" width="300" />

**Comment by itsmeichigo** [comment]
We're already displaying the status name when there's one status selected. It makes sense to just display the number if multiple are selected, and this matches Android's behavior as well. I'm closing this issue for now.
