### ISSUE TITLE
[Mobile Payments] Support for Dynamic Type in Software update modal

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#5522]
Outcome of #4348

Support for Dynamic Type in the the modal present4ed while updating the firmware

| Text 310% |
| ---- |
| <img src="https://user-images.githubusercontent.com/2722505/143486999-4ce511b2-ee97-4302-a832-b6d18a8a98e5.PNG" width="350"/> |

pdfdoF-hD-p2

**Comment by AnalyticsFreestyle** [comment]
[> ](https://github.com/woocommerce/commercial/projects/30#card-78781953)

**Comment by kidinov** [comment]
It seems to be relatively ok now
<img width="362" alt="image" src="https://user-images.githubusercontent.com/4923871/169286230-8f92acc8-3e8a-4edd-b7ae-ef329c73afcc.png">
