### ISSUE TITLE
[Mobile Payments] Add Stripe Extension /account endpoint

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-ios#5530]
Add support for Stripe Extension account endpoint - the app currently supports only WCPay version of the endpoint.

~Note: The endpoint is not in the released version of the plugin yet (as of 12/2/2021). You'll need to build it locally or ping me and I can send you the zip.~ Version 5.9.0 contains the endpoints so there is no need to manually build the zip.

**Comment by allendav** [comment]
Starting on this now
