### ISSUE TITLE
[Mobile Payments] Show "Setup not completed" when Stripe Extension installed but isn't connected to Stripe

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-ios#5532]
- [ ] Check that Stripe Extension setup is completed
- [ ] Add a new "Stripe Extension not setup" or modify the existing "WCPay not setup" screen (designs tbd)

**Comment by AnirudhBhat** [comment]
Just wanted to give a heads up that for Android we are using `stripe_extension_not_setup` as the event name for analytics in this scenario.

**Comment by allendav** [comment]
Resolved by https://github.com/woocommerce/woocommerce-ios/pull/5958
