### ISSUE TITLE
[Mobile Payments] Update the app to use /payments/connection_tokens endpoint of the active plugin (WCPay vs Stripe Extension)

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-ios#5536]
Update the app to use /payments/connection_tokens endpoint of the active plugin (WCPay vs Stripe Extension).

Depends on #5535

**Comment by ctarda** [comment]
Already implemented

**Comment by allendav** [comment]
This issue is to leverage the work done in #5535 - reopening.
