### ISSUE TITLE
[Mobile Payments] NSException setValue:forUndefinedKey ... not key value coding-compliant ... isPrimary

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#5595]
**Describe the bug**
The following exception occurs when presenting various in-person payments modals. It does NOT cause any end-user facing behavior that I can ascertain.

Exception	NSException *	"[<UIButton 0x10a6e87c0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key isPrimary."	0x0000000282f3ad00

**To Reproduce**
1. Go to a order which qualifies for in-person payments
2. Click on Collect Payment
3. See error

**Screenshots**
N/A

**Expected behavior**
I expect no exception.

**Isolating the problem (mark completed items with an [x]):**
- [n/a] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [n/a] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPad 
- iOS version: 15 
- WooCommerce iOS version: N/A

**WordPress Environment**
N/A

**Comment by ctarda** [comment]
I do not see this one happening anymore, so closing for now
