### ISSUE TITLE
Order Editing: Enable optimistic update for customer note

### ISSUE THREAD

**Issue by anas-p** [woocommerce/woocommerce-ios#5609]
Subtask of #5339: Order Editing: Enable optimistic updates for order editing actions.

## Description
Implement optimistic updates to edit order customer note to improve the experience within the Order details flow.

## Existing

https://user-images.githubusercontent.com/19687299/144554803-b4af81b7-4ba5-4152-92a0-ad8da1de6272.MP4

## Expected

https://user-images.githubusercontent.com/19687299/144555567-cd2ead7a-38a6-4b85-be45-8fb88615def5.mov

## To Reproduce:
Steps to reproduce the behaviour:

1. Open the Orders tab
2. Tap on any order
3. Tap edit button in Customer Provided note (or) Tap "Add Customer Note"
4. Update customer note 
5. Tap "Done"

**Comment by Juanpe** [comment]
Depends on #6674

**Comment by Juanpe** [comment]
Hi @itsmeichigo, I think this issue could be closed, couldn't it? 🤔 

Thanks!
