### ISSUE TITLE
[Mobile Payments]: Wrong path for payments setup for some stores

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#5616]
While I was looking at some details in our codebase of WCiOS, I discovered that we hardcoded a path for payments setup here: https://git.io/JMD7l I believe that if the user has set a custom path for `wp-admin`, the payments setup would not work. It would be ideal, in my opinion, to substitute the initial wp-admin path with the new `adminURL` introduced by @itsmeichigo here https://github.com/woocommerce/woocommerce-ios/pull/5611

**Comment by ctarda** [comment]
This affects the modal display in the onboarding flow when we detect that WCPay is not setup.

I would consider this non-critical at this point, but I'm moving it to Now so that we can get to it as soon as anyone has the capacity to tackle it
