### ISSUE TITLE
Simple Payments: Unresponsive next button

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#5639]
From @shiki: 

> For 8.1, I experienced a weird behavior earlier where I couldn’t tap the Done button. It seemed to be disabled for some reason. I could still enter the amount. I had to force close the app to make it work again. Just sharing in case you’ve experienced this too.

From @shiki. Update: Dec 7, 2021
> I experienced this again when running from `develop`. It's really weird.

**Comment by shiki** [comment]
This happened again. I took a screenshot of the UI layers. Not sure if this is helpful. 

![image](https://user-images.githubusercontent.com/198826/145128703-48e20513-88e9-4e31-a7bd-2bb337a72764.png)

And then after I continued running the app, it seemed to be tappable again. 🤷 

One clue is that if the Next button is not tappable, I also could not swipe down to dismiss the Simple Payments screen. Maybe there's an invisible UI on top?

**Comment by shiki** [comment]
@Ecarrion I wonder if this is another one of those Swift UI issues with iOS 14. We don't need to block the release though. 

Maybe later we can ask other folks with iOS 14 devices if they experience this?

**Comment by Ecarrion** [comment]
@shiki It's likely! I've been testing with on iOS 14.5 simulator and it's not occurring for me tho.

That button does use a `SwiftUI` feature called "PrimitiveButtonStyle" which allows us to reuse that style(primary with loading indicator) across all of our views.

https://github.com/woocommerce/woocommerce-ios/blob/7cc6ca839857d350070e48c6ba124f0dcccf4037/WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI%20Components/ButtonStyles.swift#L34-L73

If this continues to be a problem for us, we could turn that into a regular view, the downside being that the button can't be customized anymore as a regular button at the consumer site.

**Comment by Ecarrion** [comment]
I think we don't show this view anymore so the issue should no be longer relevant.

Btw @malinajirka should we remove this code from the codebase? I see that `SimplePaymentsSummary` is still there 😅

**Comment by malinajirka** [comment]
Hmm, Simple Payments removal was handled by Corvid, so I don't have too much context either. @bozidarsevo @kidinov Do you have some context if the SimplePayments code is still needed - perhaps for Try TTP?

**Comment by kidinov** [comment]
@malinajirka @Ecarrion Yes, at least on Android Simple Payments still used for showcasing TTP
