### ISSUE TITLE
Products List: "variants" should be "variations"

### ISSUE THREAD

**Issue by thehenrybyrd** [woocommerce/woocommerce-ios#5644]
**Describe the bug**
I believe variable products contain "variations", and I don't see the term "variants" anywhere in the WooCommerce [variable products documentation](https://woocommerce.com/document/variable-product/). 
However, in the Products List, variable products note how many "variants" they contain, rather than how many "variations".

**To Reproduce**
1. Tap Products to open the Products List
2. Be sure you have at least one variable product with multiple variations set up
3. Scroll to find one of your variable products
4. Note that it mentions the number of "variants" rather than "variations"

**Screenshots**
<img src="https://user-images.githubusercontent.com/15107387/145314739-f5fcf393-ae5c-4de9-bfa9-519e6d8f0828.png" width="70%">

**Expected behavior**
I expected "variations" rather than "variants"

**Mobile Environment**
Please include:
Device: iPhone 12 mini
iOS version: 14.8.1
WooCommerce iOS version: 8.1.0.1

**Comment by itsmeichigo** [comment]
Holding this issue for the next trial.
