### ISSUE TITLE
Orders List filter: Custom range is limited once a start/end date is selected

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#5647]
**Describe the bug**
When selecting a custom date range, once a start/end date is selected, the range can't be changed to an earlier/later date. Looks like only way for now is to clear the filter and restart the selection.

**To Reproduce**
1. Go to Orders screen
2. Tap on Filter and select Date Range > Custom Range
3. Select a date as start date - see that all dates before that is now greyed out (repeat the same for end date)
4. Once the start/end dates are selected, everything else before/after is greyed out and can't be re-selected until after filter is cleared.

**Screenshots**

https://user-images.githubusercontent.com/17252150/145337042-c86c6be7-fed6-4081-8c55-7ad6b0f2c9de.MP4

**Expected behavior**
Should be able to update custom range without having to clear filter

**Isolating the problem (mark completed items with an [x]):**
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13 Mini
- iOS version: 15.0
- WooCommerce iOS version: 8.1

**Comment by pmusolino** [comment]
Closing this issue in favour of this https://github.com/woocommerce/woocommerce-ios/issues/6089
