### ISSUE TITLE
Cannot build with Release configuration due to error `Missing argument for parameter 'from' in call [to Product()]`

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#5708]
**Describe the bug**
When building the app with the Release configuration, the build fails with the error `Missing argument for parameter 'from' in call [to Product()]` in a [function which makes sample ghost content](https://github.com/woocommerce/woocommerce-ios/blob/8d4327771049fb5ad336c5ad1a6b0f572015a37d/WooCommerce/Classes/ViewRelated/Orders/Order%20Creation/ProductsSection/AddProductToOrderViewModel.swift#L203). The fixit suggestion is to insert `from`, which would use the decoder version of the init.

This does not happen with a debug build, but does for local release builds and when building installable builds on CI.

**To Reproduce**
1. Go to `Edit Scheme` in Xcode and set the `Run` Build Configuration to `Release`.
2. Run the app
3. Observe the above error.

**Expected behavior**
The build should succeed.

**Isolating the problem (mark completed items with an [x]):**
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13 mini simulator
- iOS version: iOS 15.1
- WooCommerce iOS version: latest develop

**Comment by joshheald** [comment]
Xcode's `Jump to definition` on the offending `Product()` call takes us to [`Product+SwiftUIPreviewHelpers.swift`](https://github.com/woocommerce/woocommerce-ios/blob/8d4327771049fb5ad336c5ad1a6b0f572015a37d/WooCommerce/Classes/Extensions/Product%2BSwiftUIPreviewHelpers.swift#L7) where we can see that the contents of the file are wrapped in an `#if [...] DEBUG` conditional compilation directive, so that explains why they're unavailable for release builds and causing an error.

@rachelmcr tagging you for info as the issue was introduced [here](https://github.com/woocommerce/woocommerce-ios/commit/7ddaee1ad0437cd21b7c7da46b49bc8a50d801a2), according to git bisect, but I'm looking at a fix now 😊

**Comment by joshheald** [comment]
The extension is named for SwiftUI Previews, but is currently used in various tests of non-SwiftUI code, as well as a few previews.

**Comment by rachelmcr** [comment]
Oh argh, I didn't realize that was using an extension meant for previews. Thanks for the ping! Please let me know if you'd like me to take care of the fix.

**Comment by joshheald** [comment]
No worries, it's not obvious at the call site and it's a bit of a horrible one to spot! I'm glad I found it, because it was just by chance, and saves it coming up during the release process 😊

**Comment by Ecarrion** [comment]
That is one reason why I don't like non-View code in our `SwiftUI` views and `Previews` 🙈
