### ISSUE TITLE
Order Creation: Release M1 (Products and Customers)

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#5719]
- [x] Remove the `.orderCreation` feature flag from the Order Creation experimental features toggle. This will release the M1 (Products and Customers) features to everyone who enables the toggle.
- [x] Ensure that any parts of Order Creation still under development are now behind the `.orderCreation` feature flag.
- [x] Ping @thehenrybyrd in Slack to let her know about the release so she can coordinate the beta call for testing.

Milestone 1 includes support for order creation with the ability to:

- Change the order status.
- Add existing products to the order.
- Add billing/shipping information to the order.
- View basic payment details (product total and order total).

We can perform a full test of the Milestone 1 features using this test plan: pdcxQM-hH-p2

**Comment by shiki** [comment]
@rachelmcr I would like to recommend that we set the flag to `true` to enable it instead of removing it from the code. In that way, if something terrible happens, we can easily remove it from production.

**Comment by rachelmcr** [comment]
Couldn't we just revert the commit if we need to? I was planning to keep using the same feature flag for the next milestone, and just remove the check for it on the experimental feature toggle.

**Comment by shiki** [comment]
Ah, gotcha. Reverting the commit makes sense if we're not adding other things in the PR. Lol ignore me.
