### ISSUE TITLE
Add/Edit Product: product title changes are reset after adding a new product image

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#5739]
**Describe the bug**

When creating or editing a product, product title changes are reset after adding a product image for the first time (either taken from the camera or selected from the device library).

**To Reproduce**

- Go to the products tab
- Tap on an editable product or tap "+" in the navigation bar to add a product of any type
- Edit the product title
- Tap on the "+" cell or any image cell in the images header to edit product images
- Tap "Add Photos"
- Tap "Choose from device" or "Take a photo" to upload a photo --> after going back to the product form, notice that the product title changes are reset

**Screenshots**

https://user-images.githubusercontent.com/1945542/147209976-ebcaaac6-a307-4e6d-9bd9-41569f77c1bb.mov

**Expected behavior**
The product title changes should not be reset after adding a new image.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: any
- WooCommerce iOS version: 8.2

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by itsmeichigo** [comment]
Holding this issue for the next trial.
