### ISSUE TITLE
Settings: Sync Tracks Opt Out setting

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#574]
WPiOS issue Ref. https://github.com/wordpress-mobile/WordPress-iOS/issues/8933, implementation Ref. https://github.com/wordpress-mobile/WordPress-iOS/pull/9275.
 
## Sync global opt-out preference
As part of the GDPR efforts, WordPress.com recently introduced a new setting to opt-out. We want to sync the opt-out in the apps with that value whenever the user is signed in.

The setting is stored as tracks_opt_out in me/settings.

The toggle would still be in app settings. It would show the value for the primary account if there’s one, otherwise the local per-app setting. When the user changes the setting, it would change the local value and for all the WordPress.com accounts in the app.

**Comment by astralbodies** [comment]
Whoops, nice catch @mindgraffiti reopening this!
