### ISSUE TITLE
Issue when installing the app

### ISSUE THREAD

**Issue by lawrencecph** [woocommerce/woocommerce-ios#5752]
After running: "bundle install && bundle exec rake dependencies", i get this error:

An error occurred while installing fastlane-plugin-wpmreleasetoolkit
(2.3.0), and Bundler cannot continue.

My bundler is version 2.2.27, and Ruby is the correct version aswell 2.7.4.

**Comment by Ecarrion** [comment]
Hi @lawrencecph, could you share the full log to look for any hint?

**Comment by lawrencecph** [comment]
`Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/.........
Using rake 12.3.3
Using rexml 3.2.5
Using concurrent-ruby 1.1.9
Using minitest 5.15.0
Using thread_safe 0.3.6
Using public_suffix 4.0.6
Using httpclient 2.8.3
Using json 2.6.1
Using artifactory 3.0.15
Using atomos 0.1.3
Using aws-eventstream 1.2.0
Using aws-partitions 1.541.0
Using jmespath 1.4.0
Using fourflusher 2.3.1
Using gh_inspector 1.1.3
Using molinillo 0.8.0
Using bundler 2.2.27
Using ruby-macho 2.5.1
Using nanaimo 0.3.0
Using colored 1.2
Using colorize 0.8.1
Using highline 2.0.3
Using declarative 0.0.20
Using diffy 3.4.0
Using digest-crc 0.6.4
Using unf_ext 0.0.8
Using dotenv 2.7.6
Using emoji_regex 3.2.3
Using excon 0.89.0
Using faraday-em_http 1.0.0
Using faraday-em_synchrony 1.0.0
Using faraday-excon 1.1.0
Using fuzzy_match 2.0.4
Using faraday-net_http_persistent 1.2.0
Using netrc 0.11.0
Using nap 1.1.0
Using faraday-patron 1.0.0
Using faraday-rack 1.0.0
Using multipart-post 2.0.0
Using ruby2_keywords 0.0.5
Using fastimage 2.2.5
Using jwt 2.3.0
Using memoist 0.16.2
Using multi_json 1.15.0
Using os 1.1.4
Using uber 0.1.0
Using chroma 0.2.0
Using retriable 3.1.2
Using webrick 1.7.0
Using google-cloud-errors 1.2.0
Using mini_magick 4.11.0
Using naturally 2.2.1
Using optparse 0.1.1
Using plist 3.6.0
Using rubyzip 2.3.2
Using security 0.1.3
Using terminal-notifier 2.0.0
Using unicode-display_width 1.8.0
Using tty-screen 0.8.1
Using tty-cursor 0.7.1
Using word_wrap 1.0.0
Using rouge 2.0.7
Using fastlane-plugin-appcenter 1.11.1
Using fastlane-plugin-sentry 1.11.0
Using xctest_list 1.2.1
Using rchardet 1.8.0
Using oj 3.13.10
Using optimist 3.0.1
Using parallel 1.21.0
Using racc 1.6.0
Using rake-compiler 1.1.6
Using ffi 1.15.4
Using i18n 1.8.11
Using trailblazer-option 0.1.2
Using mini_mime 1.1.2
Using algoliasearch 1.27.5
Using cocoapods-search 1.0.1
Using commander 4.6.0
Using colored2 3.1.2
Using cocoapods-plugins 1.0.0
Using babosa 1.0.4
Using escape 0.0.4
Using faraday-httpclient 1.0.1
Using cocoapods-trunk 1.6.0
Using terminal-table 1.8.0
Using tty-spinner 0.9.3
Using xcpretty 0.3.0
Using git 1.9.1
Using representable 3.1.1
Using tzinfo 1.2.9
Using addressable 2.8.0
Using aws-sigv4 1.4.0
Using activesupport 5.2.6
Using unf 0.1.4
Using jsonlint 0.3.0
Using domain_name 0.5.20190701
Using bigdecimal 1.4.4
Using nokogiri 1.12.5 (x86_64-darwin)
Using http-cookie 1.0.4
Using options 2.3.2
Using faraday-net_http 1.0.1
Using progress_bar 1.3.3
Using cocoapods-deintegrate 1.0.5
Using faraday 1.8.0
Using xcpretty-travis-formatter 1.0.1
Using cocoapods-try 1.2.0
Using aws-sdk-core 3.124.0
Using ethon 0.15.0
Using claide 1.0.3
Using CFPropertyList 3.0.5
Using cocoapods-downloader 1.5.1
Using xcodeproj 1.21.0
Using faraday-cookie_jar 0.0.7
Using signet 0.16.0
Using google-cloud-env 1.5.0
Using sawyer 0.8.2
Using google-cloud-core 1.6.0
Using typhoeus 1.4.0
Using simctl 1.6.8
Using faraday_middleware 1.2.0
Using googleauth 1.1.0
Using aws-sdk-kms 1.52.0
Using google-apis-core 0.4.1
Using octokit 4.21.0
Using cocoapods-core 1.11.2
Using aws-sdk-s3 1.109.0
Fetching fastlane-plugin-wpmreleasetoolkit 2.3.0
Using google-apis-androidpublisher_v3 0.14.0
Using google-apis-playcustomapp_v1 0.6.0
Using google-apis-iamcredentials_v1 0.9.0
Using google-apis-storage_v1 0.10.0
Using cocoapods 1.11.2
Using google-cloud-storage 1.35.0
Using fastlane 2.199.0
Using trainer 0.9.1
Using xcode-install 2.8.0
Using fastlane-plugin-test_center 3.15.3
Using fastlane-plugin-trainer 0.4.1
Installing fastlane-plugin-wpmreleasetoolkit 2.3.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/carlhave/Lawrence/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-wpmreleasetoolkit-2.3.0/ext/drawText
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r
./siteconf20211223-50506-ybs6st.rb extconf.rb
checking for swift... yes
checking for xcodebuild... yes
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer
directory '/Library/Developer/CommandLineTools' is a command line tools instance
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1385:in
`initialize': No such file or directory @ rb_sysopen -
/Users/carlhave/Lawrence/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-wpmreleasetoolkit-2.3.0/ext/drawText/Build/Products/Release/drawText
(Errno::ENOENT)
from
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1385:in
`open'
from
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1385:in
`copy_file'
from
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:492:in
`copy_file'
from
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:419:in
`block in cp'
from
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1557:in
`block in fu_each_src_dest'
from
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1573:in
`fu_each_src_dest0'
from
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1555:in
`fu_each_src_dest'
from
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:418:in
`cp'
	from extconf.rb:32:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/Users/carlhave/Lawrence/ios/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-20/2.6.0/fastlane-plugin-wpmreleasetoolkit-2.3.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/Users/carlhave/Lawrence/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-wpmreleasetoolkit-2.3.0
for inspection.
Results logged to
/Users/carlhave/Lawrence/ios/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-20/2.6.0/fastlane-plugin-wpmreleasetoolkit-2.3.0/gem_make.out

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:99:in
`run'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:47:in
`block in build'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in
`open'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:29:in
`build'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:185:in
`block in build_extension'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/monitor.rb:230:in
`mon_synchronize'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:181:in
`build_extension'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:229:in
`block in build_extensions'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:226:in
`each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:226:in
`build_extensions'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/installer.rb:830:in
`build_extensions'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/rubygems_gem_installer.rb:66:in
`build_extensions'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/rubygems_gem_installer.rb:26:in
`install'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/source/rubygems.rb:199:in
`install'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/installer/gem_installer.rb:54:in
`install'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/worker.rb:62:in
`apply_func'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/worker.rb:57:in
`block in process_queue'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/worker.rb:54:in
`loop'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/worker.rb:54:in
`process_queue'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/worker.rb:91:in
`block (2 levels) in create_threads'

An error occurred while installing fastlane-plugin-wpmreleasetoolkit
(2.3.0), and Bundler cannot continue.

`

**Comment by lawrencecph** [comment]
Is there a specific file with all the full log? There is no other errors than this.

**Comment by lawrencecph** [comment]
[Uploading error.rtf…]()
Here is the error.

**Comment by lawrencecph** [comment]
Fetching gem metadata from https://rubygems.org/.........
Using rake 12.3.3
Using rexml 3.2.5
Using concurrent-ruby 1.1.9
Using minitest 5.15.0
Using thread_safe 0.3.6
Using public_suffix 4.0.6
Using httpclient 2.8.3
Using json 2.6.1
Using artifactory 3.0.15
Using atomos 0.1.3
Using aws-eventstream 1.2.0
Using aws-partitions 1.541.0
Using jmespath 1.4.0
Using fourflusher 2.3.1
Using gh_inspector 1.1.3
Using molinillo 0.8.0
Using bundler 2.2.27
Using ruby-macho 2.5.1
Using nanaimo 0.3.0
Using colored 1.2
Using colorize 0.8.1
Using highline 2.0.3
Using declarative 0.0.20
Using diffy 3.4.0
Using digest-crc 0.6.4
Using unf_ext 0.0.8
Using dotenv 2.7.6
Using emoji_regex 3.2.3
Using excon 0.89.0
Using faraday-em_http 1.0.0
Using faraday-em_synchrony 1.0.0
Using faraday-excon 1.1.0
Using fuzzy_match 2.0.4
Using faraday-net_http_persistent 1.2.0
Using netrc 0.11.0
Using nap 1.1.0
Using faraday-patron 1.0.0
Using faraday-rack 1.0.0
Using multipart-post 2.0.0
Using ruby2_keywords 0.0.5
Using fastimage 2.2.5
Using jwt 2.3.0
Using memoist 0.16.2
Using multi_json 1.15.0
Using os 1.1.4
Using uber 0.1.0
Using chroma 0.2.0
Using retriable 3.1.2
Using webrick 1.7.0
Using google-cloud-errors 1.2.0
Using mini_magick 4.11.0
Using naturally 2.2.1
Using optparse 0.1.1
Using plist 3.6.0
Using rubyzip 2.3.2
Using security 0.1.3
Using terminal-notifier 2.0.0
Using unicode-display_width 1.8.0
Using tty-screen 0.8.1
Using tty-cursor 0.7.1
Using word_wrap 1.0.0
Using rouge 2.0.7
Using fastlane-plugin-appcenter 1.11.1
Using fastlane-plugin-sentry 1.11.0
Using xctest_list 1.2.1
Using rchardet 1.8.0
Using oj 3.13.10
Using optimist 3.0.1
Using parallel 1.21.0
Using racc 1.6.0
Using rake-compiler 1.1.6
Using ffi 1.15.4
Using i18n 1.8.11
Using trailblazer-option 0.1.2
Using mini_mime 1.1.2
Using algoliasearch 1.27.5
Using cocoapods-search 1.0.1
Using commander 4.6.0
Using colored2 3.1.2
Using cocoapods-plugins 1.0.0
Using babosa 1.0.4
Using escape 0.0.4
Using faraday-httpclient 1.0.1
Using cocoapods-trunk 1.6.0
Using terminal-table 1.8.0
Using tty-spinner 0.9.3
Using xcpretty 0.3.0
Using git 1.9.1
Using representable 3.1.1
Using tzinfo 1.2.9
Using addressable 2.8.0
Using aws-sigv4 1.4.0
Using activesupport 5.2.6
Using unf 0.1.4
Using jsonlint 0.3.0
Using domain_name 0.5.20190701
Using bigdecimal 1.4.4
Using nokogiri 1.12.5 (x86_64-darwin)
Using http-cookie 1.0.4
Using options 2.3.2
Using faraday-net_http 1.0.1
Using progress_bar 1.3.3
Using cocoapods-deintegrate 1.0.5
Using faraday 1.8.0
Using xcpretty-travis-formatter 1.0.1
Using cocoapods-try 1.2.0
Using aws-sdk-core 3.124.0
Using ethon 0.15.0
Using claide 1.0.3
Using CFPropertyList 3.0.5
Using cocoapods-downloader 1.5.1
Using xcodeproj 1.21.0
Using faraday-cookie_jar 0.0.7
Using signet 0.16.0
Using google-cloud-env 1.5.0
Using sawyer 0.8.2
Using google-cloud-core 1.6.0
Using typhoeus 1.4.0
Using simctl 1.6.8
Using faraday_middleware 1.2.0
Using googleauth 1.1.0
Using aws-sdk-kms 1.52.0
Using google-apis-core 0.4.1
Using octokit 4.21.0
Using cocoapods-core 1.11.2
Using aws-sdk-s3 1.109.0
Fetching fastlane-plugin-wpmreleasetoolkit 2.3.0
Using google-apis-androidpublisher_v3 0.14.0
Using google-apis-playcustomapp_v1 0.6.0
Using google-apis-iamcredentials_v1 0.9.0
Using google-apis-storage_v1 0.10.0
Using cocoapods 1.11.2
Using google-cloud-storage 1.35.0
Using fastlane 2.199.0
Using trainer 0.9.1
Using xcode-install 2.8.0
Using fastlane-plugin-test_center 3.15.3
Using fastlane-plugin-trainer 0.4.1
Installing fastlane-plugin-wpmreleasetoolkit 2.3.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/user100/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-wpmreleasetoolkit-2.3.0/ext/drawText
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r
./siteconf20211223-50506-ybs6st.rb extconf.rb
checking for swift... yes
checking for xcodebuild... yes
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer
directory '/Library/Developer/CommandLineTools' is a command line tools instance
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1385:in
`initialize': No such file or directory @ rb_sysopen -
/Users/user100/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-wpmreleasetoolkit-2.3.0/ext/drawText/Build/Products/Release/drawText
(Errno::ENOENT)
from
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1385:in
`open'
from
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1385:in
`copy_file'
from
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:492:in
`copy_file'
from
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:419:in
`block in cp'
from
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1557:in
`block in fu_each_src_dest'
from
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1573:in
`fu_each_src_dest0'
from
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1555:in
`fu_each_src_dest'
from
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:418:in
`cp'
	from extconf.rb:32:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/Users/user100/ios/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-20/2.6.0/fastlane-plugin-wpmreleasetoolkit-2.3.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/Users/user100/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-wpmreleasetoolkit-2.3.0
for inspection.
Results logged to
/Users/user100/ios/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-20/2.6.0/fastlane-plugin-wpmreleasetoolkit-2.3.0/gem_make.out

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:99:in
`run'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:47:in
`block in build'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in
`open'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:29:in
`build'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:185:in
`block in build_extension'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/monitor.rb:230:in
`mon_synchronize'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:181:in
`build_extension'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:229:in
`block in build_extensions'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:226:in
`each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:226:in
`build_extensions'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/installer.rb:830:in
`build_extensions'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/rubygems_gem_installer.rb:66:in
`build_extensions'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/rubygems_gem_installer.rb:26:in
`install'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/source/rubygems.rb:199:in
`install'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/installer/gem_installer.rb:54:in
`install'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/worker.rb:62:in
`apply_func'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/worker.rb:57:in
`block in process_queue'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/worker.rb:54:in
`loop'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/worker.rb:54:in
`process_queue'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.27/lib/bundler/worker.rb:91:in
`block (2 levels) in create_threads'

An error occurred while installing fastlane-plugin-wpmreleasetoolkit
(2.3.0), and Bundler cannot continue.

In Gemfile:
  fastlane-plugin-wpmreleasetoolkit

**Comment by lawrencecph** [comment]
Look in the comment above for the full log.

**Comment by Ecarrion** [comment]
@lawrencecph form

> xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer
directory '/Library/Developer/CommandLineTools' is a command line tools instance

It seems like you don't have Xcode properly set.

You need to.

- Download Xcode
- Download Xcode command line tools
- Set it with `sudo xcode-select -s {path_to_xcode}`

**Comment by lawrencecph** [comment]
Thank you that solved it!

**Comment by lawrencecph** [comment]
After i build i then get this error now:

https://user-images.githubusercontent.com/74384811/147357226-92dab8b6-90f6-4510-84d9-4d93cf7991c9.png
