### ISSUE TITLE
Order Creation: Name and Email entries disappear when keyboard is dismissed or is the keyboard type is changed

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#5808]
Using dcd3bb619. 

This seems like inconsistent behavior. Not sure if it's a high priority or not. The entries seem to disappear whenever the keyboard is shown or dismissed. It's also weird because when I'm typing while the keyboard is shown, it's suddenly dismissed. I remember this didn't use to be like this. 🤷 

https://user-images.githubusercontent.com/198826/148128314-4a5392d4-8de8-47a9-874d-66595c9eb28d.mov

**Comment by rachelmcr** [comment]
Just a note that I came across this bug during a PR review and it's much more consistent/problematic if you're using the software keyboard rather than a hardware keyboard. Given that, I think it's high priority since I'd expect most people to be using their device's software keyboard.
