### ISSUE TITLE
`ReviewsView` observer not updating `rightBarButtonItem` of `ReviewsViewController`

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#5830]
### Problem
<img width="843" alt="Screenshot 2022-01-06 at 10 27 11 AM" src="https://user-images.githubusercontent.com/524475/148403029-c6fa52ae-d9b8-494f-bc26-9786a65680de.png">

The observer used inside `ReviewsView.swift` works well when `rightBarButtonItem` is enabled/disabled in `ReviewsViewController`. But, for some reason, that observer isn’t updating the SwiftUI’s ViewController properly when the `rightBarButtonItem` property itself is set again.

### Details
More details about this issue can be found at p91TBi-74J-p2

### What next?
Investigate on why the observer is only updating `rightBarButtonItem` after switching between view controllers. Should we be updating the view controller in `func updateUIViewController(_ uiViewController: ReviewsViewController, context: Context)`  ?

**Comment by itsmeichigo** [comment]
@pmusolino I'm thinking about adding another observer for the right bar button item in the `ReviewsView`, that way we can update the navigation item for the parent when the item is updated on the UIKit side. Does that sound like a good enough solution or a bit hacky?

**Comment by pmusolino** [comment]
@itsmeichigo it's a little bit hacky, but not necessarily a bad solution. If it doesn't take too long, feel free to open a PR with your proposal and give me the review 🙌
