### ISSUE TITLE
Product Add photos: Unable to view photos from device in iOS 15.2 (Xcode 13.2.1)

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#5838]
**Problem**

While running the app using Xcode 13.2.1 trying to add a photo to a product from a simulator running iOS 15.2,

<img src="https://user-images.githubusercontent.com/524475/148620154-672b4730-605a-4177-8670-b8bee6968c11.png" width="350">

1. Tapping on “Choose from device” has no response for a few seconds.
1. The permission alert appears after that.
1. Tapping on “Allow Access to All Photos” dismisses the alert but I can’t see any photos

**More info**

I have tested in 14.1 simulator and things are working as expected there. (I can see the photos)

I have raised a PR at https://github.com/wordpress-mobile/MediaPicker-iOS/pull/376 with a possible fix. More details at p91TBi-79a-p2

**Expected behavior**

I should be able to access photos in a simulator running iOS 15.2

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
iOS 15.2 simulator
Xcode 13.2.1

**Comment by selanthiraiyan** [comment]
**Update**

The [PR with the fix](https://github.com/wordpress-mobile/MediaPicker-iOS/pull/376) has been accepted and `WPMediaPicker 1.8.1` was released with a fix for this issue.

Our repo's `trunk` is already using the new version. We can test this issue in Xcode 13.2.1 or higher (when we eventually start using that version) and close this issue.

**Comment by pmusolino** [comment]
Tested `trunk` with `WPMediaPicker 1.8.1` on Xcode 13.2.1 and the issues was fixed 👍
