### ISSUE TITLE
Order Details: State is shown incorrectly - code instead of a name.

### ISSUE THREAD

**Issue by ealeksandrov** [woocommerce/woocommerce-ios#5851]
Android issue: https://github.com/woocommerce/woocommerce-android/issues/5604.

## Description

E.g. state Hokkaido in Japan is shown as JP01 which is location code for this state in WooCommerce Core.

## Details

We're using this Address extension for pretty address formatting:
https://github.com/woocommerce/woocommerce-ios/blob/81ed7b18078c58d3337f53a91d0f09c802bf3c3f/WooCommerce/Classes/Model/Address%2BWoo.swift#L38-L40

`postalAddress` is created from Address fields (strings) without any references to WC Country:
https://github.com/woocommerce/woocommerce-ios/blob/81ed7b18078c58d3337f53a91d0f09c802bf3c3f/WooCommerce/Classes/Model/ShippingLabelAddress%2BWoo.swift#L61-L71

## Testing

1. Create order in wc-admin.
2. Add billing address: "Country: Japan, State: Hokkaido".
3. Open created order in iOS app, tap "View Billing Information".

## Screenshots

wp-admin|iOS app
--|--
<img width="300" src="https://user-images.githubusercontent.com/3132438/148821039-156bca87-53ce-42db-a5c0-9dda645943e9.png">|<img width="300" src="https://user-images.githubusercontent.com/3132438/148820942-f869c445-8e05-4640-b49b-2c028da7dd22.png">

**Comment by shiki** [comment]
I believe this is the same as https://github.com/woocommerce/woocommerce-android/issues/5604 and we should follow p91TBi-8lv-p2 as the solution. Is that correct, @wzieba?

**Comment by wzieba** [comment]
That's all correct @shiki - @ealeksandrov linked this issue in the description, we synced on that IIRC. Also, we should follow with the post you shared but for now I deprioritized it due to Order Creation/Editing Unify project.

I think the best will be to follow up on this after Order Creation/Editing Unify is finished as it'll be much easier from UI/UX perspective.

**Comment by shiki** [comment]
Thanks!

I'll change the priority of this to “Someday“. ^_^x

**Comment by thabotswana** [comment]
A user reported this in 5604632-zen


![AttachmentE775675E-7D52-4536-B571-28E531A152AB](https://user-images.githubusercontent.com/35628116/194052560-9b83a922-36cc-4d47-aff4-025afa1a5ec1.jpeg)

**Comment by reginabally** [comment]
Hi @ealeksandrov @shiki @wzieba, just want to know if this issue is still a low priority. The user who reported the issue was asking for an update because they'd been waiting for a year for a fix. Thanks!

**Comment by wzieba** [comment]
@reginabally thank you for the ping! We started discussion about this issue internally (p1669280373187189-slack-C02KUCFCSFP). I'll let you know here about our plans for resolving this.

**Comment by wzieba** [comment]
Internal post: peaMlT-2W-p2

**Comment by reginabally** [comment]
Sorry for the late reply, @wzieba. I was away for two weeks. Thank you so much for taking care of this! 🙇‍♀️
