### ISSUE TITLE
Ghost "Hub Menu" label appears in the tab bar after navigating back to the Menu tab

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#5860]
**Describe the bug**

When the `hubMenu` feature flag is on and the Menu tab replaces the previous Reviews tab, a "Hub Menu" appears in the tab bar after navigating to a screen from the Menu tab and then back to the root view. This only happens in iOS 14 simulators/devices.

**To Reproduce**

Please make sure the `hubMenu` feature flag is enabled (default in `trunk`).
- Tap the Menu tab
- Tap the Reviews or Coupons item
- Tap the Menu tab again to go back to the root view --> a “Hub Menu” label appears in the bottom left of the tab bar

**Screenshots**

<img src="https://user-images.githubusercontent.com/1945542/148896479-7973a702-35e6-4b18-9175-76e6c66172c1.PNG" width="300" />

**Expected behavior**

There should not be a label appearing in the bottom left of the tab bar.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: iOS 14
- WooCommerce iOS version: 8.2

**Comment by pmusolino** [comment]
Thank you @jaclync for opening this issue. This is an issue that we discussed also here https://github.com/woocommerce/woocommerce-ios/issues/3995 on Shipping Labels, and that Apple was able to fix only recently. I saw that you were able to fix a similar issue here https://github.com/woocommerce/woocommerce-ios/pull/5859, so I'm wondering if it's possible to fix the problem by following the same approach. I'll look at it today. 👍

**Comment by jaclync** [comment]
Ooh I didn't know we had investigated the same issue with Shipping Labels before! I tested in Xcode 13.2.1 today and this is still an issue in iOS 14 😞

However, is there any reason we need to set the navigation bar title in `HubMenuViewController` since the HUB menu doesn't have a navigation bar? I tried removing this line and it seems to fix the issue 😄 

https://github.com/woocommerce/woocommerce-ios/blob/bf6413a942dee0ce06f91da3a5d43963c517777e/WooCommerce/Classes/ViewRelated/Hub%20Menu/HubMenuViewController.swift#L10

> I saw that you were able to fix a similar issue here #5859, so I'm wondering if it's possible to fix the problem by following the same approach.

[#5959](https://github.com/woocommerce/woocommerce-ios/pull/5859) is a bit different because `ReviewsViewController` is not using SwiftUI and can be fixed by setting the navbar title with `navigationItem.title`. `HubMenuViewController` already sets `navigationItem.title` 😐

**Comment by pmusolino** [comment]
> However, is there any reason we need to set the navigation bar title in HubMenuViewController since the HUB menu doesn't have a navigation bar? I tried removing this line and it seems to fix the issue

Uhm I think it is a code leftover from the initial implementation when there was no precise idea of ​​the internal view! I have tried and it actually works like this. I am opening a PR to solve the problem. Good catch in discovering and fixing it 💯
