### ISSUE TITLE
[Mobile Payments] Add unit tests to cover Stripe plugin specific logic

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#5866]
Context: https://github.com/woocommerce/woocommerce-ios/pull/5734#discussion_r781730161

## Tests to add

- [x] `.pluginUnsupportedVersion(plugin: .stripe)`
- [x] no `PaymentGatewayAccount`
- [x] `.completed` when successful
- [x] `CardPresentPaymentAction.use(paymentGatewayAccount:)` is sent when successful

The remaining cases covered in [`accountChecks`](https://github.com/woocommerce/woocommerce-ios/blob/fabd33983faf501861faaaba4d3c8dc94cb478cb/WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person%20Payments/CardPresentPaymentsOnboardingUseCase.swift#L202) seem like they would be best addressed once we have made a generic replacement for [`WCPayAccountStatusEnum`](https://github.com/woocommerce/woocommerce-ios/blob/fabd33983faf501861faaaba4d3c8dc94cb478cb/Networking/Networking/Model/StripeAccount.swift#L11)

**Comment by joshheald** [comment]
Both active logic is already tested: [test_onboarding_returns_select_plugin_when_both_stripe_and_wcpay_plugins_are_active](https://github.com/woocommerce/woocommerce-ios/blob/595dad4d86391da2a65204985317f06c383b5cf4/WooCommerce/WooCommerceTests/ViewRelated/CardPresentPayments/CardPresentPaymentsOnboardingUseCaseTests.swift#L106)

[Code review comment](https://github.com/woocommerce/woocommerce-ios/pull/5734#discussion_r781730161) is related to plugin specific tests. These are in place for `.wcPay`, but not for the `.stripe` plugin.

Correcting this ticket to cover the Stripe plugin specific tests.
