### ISSUE TITLE
[Mobile Payments] M2 reader with a low battery fails to connect without a clear error.

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#5888]
**Describe the bug**

I was trying to connect my M2 reader, and I kept getting a generic error screen that prompted my to try again. 
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

With the Xcode debugger, I was able to see that the error returned on connection was:

```
Error Domain=com.stripe-terminal Code=3230 "Bluetooth device disconnected." UserInfo={NSLocalizedDescription=Bluetooth device disconnected., com.stripe-terminal:Message=Bluetooth device disconnected.}
```

Eventually I decided to plug the reader to charge and see if it maybe had a low battery, and indeed the first attempt to connect succeeded and showed a 17% battery. This increased to 24% in about a minute of charging, so it seems credible that it was close to 0% initially.

Neither the API or the reader lights made it clear that it was low on battery.

**Comment by ctarda** [comment]
Implemented in #5998
