### ISSUE TITLE
[Simple Payments] Order status after collecting a Simple Payment is "Pending payment"

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#5892]
**Describe the bug**
The order status after collecting a Simple Payment is "Pending payment", unless the Order list is refreshed.

**To Reproduce**
1. Go to Order List
2. Tap the + button
3. Enter an amount
4. Tap Next
5. Tap Take Payment
6. Tap Card
7. Collect the Payment.

After the payment capture is completed, and all the modals are dismissed, the order lists shows the order as Payment payment.
A refresh of the order list (i.e. taking the app into the background and back into the foreground or navigating into the order details) refreshes the status to completed

**Screenshots**
<img src="https://user-images.githubusercontent.com/2722505/149347982-ee9dea81-6b31-46c5-bab9-4cf12498dbd2.jpeg" width="350"/>

**Expected behavior**
The order status should be displayed as "Completed"

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 11 Pro Max
- iOS version: 15.2
- WooCommerce iOS version: trunk branch

**Comment by joshheald** [comment]
I can't repro this as described, and I've not noticed it happening recently either. 

The order status is `Pending payment` when you get back to the order list, but quickly updates to `Completed` without the pull to refresh or navigation described in the issue. 

Perhaps it would be better if we marked it as completed locally when the simple payment completes?

@ctarda what do you think?

**Comment by ctarda** [comment]
We should probably let core own the responsibility of managing the state machine of order statuses. There is a lot of logic in the backend to handle those statuses, and adding a layer of logic on the clients might be a bit risky, even though it would make the UI definitely more responsive. 

I don't have very strong feelings about this though

**Comment by Ecarrion** [comment]
Yes, also depending on the users custom statuses, it may not go to "Completed" but "User Custom Completed"

**Comment by joshheald** [comment]
Agreed. I would only think we should do it if we kept the refresh in place and revert to the backend status as soon as it comes in... as per #6818, we could update it to `Processing` as a temporary state which prevents it being collected again...

**Comment by jaclync** [comment]
@joshheald what do you think of updating the order (`OrderAaction.retrieveOrder`) after IPP success in Simple Payments so that the status can be updated? Similar to what we do for IPP in order details:

https://github.com/woocommerce/woocommerce-ios/blob/c384062e439f246a2ed6f70de7d9b1852ec5b3bb/WooCommerce/Classes/ViewRelated/Orders/Order%20Details/OrderDetailsViewController.swift#L731-L735

This way, we don't have to assume the `Completed` order status in case the merchant uses custom order statuses like @Ecarrion mentioned above. Then I'll close https://github.com/woocommerce/woocommerce-ios/pull/6866 and make another PR 🙂
