### ISSUE TITLE
[Mobile Payments] Remove hardcoded isTest and isLive from StripeAccount (and update tests)

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#5921]
https://github.com/woocommerce/woocommerce-ios/pull/5915#discussion_r786318933

**Comment by allendav** [comment]
Looks like this is on track for the next release of the plugin (6.1.0): https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/changelog.txt#L7
