### ISSUE TITLE
[SwiftUI] `SimplePaymentsSummary` - `AttributeGraph: cycle detected through attribute` warnings

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#5937]
**Describe the bug**
`AttributeGraph: cycle detected through attribute` warnings appear in Xcode log, while navigating to `SimplePaymentsSummary` SwiftUI view.

**To Reproduce**
1. Navigate to `Settings` and make sure that `Order creation` is turned on under `Experimental Features`
1. Navigate to `Orders` tab.
1. Tap on `+` button on top right and select `Simple payment` from the action sheet.
1. Clear logs in Xcode.
1. Enter an amount and tap `Next`.
1. Observe that a bunch of `AttributeGraph: cycle detected through attribute` warnings appear in the Xcode log.

**Screenshots**
<img width="500" alt="Screenshot 2022-01-21 at 8 15 54 AM" src="https://user-images.githubusercontent.com/524475/150457016-24f3419e-8118-4297-8385-863e7a647fa8.png">

**Expected behavior**
No warnings in Xcode log.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
iOS 15.2 simulator
Xcode 13.2.1

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by selanthiraiyan** [comment]
Apparently, these warnings appear because we are navigating away from the `SimplePaymentsAmount`SwiftUI view to the `SimplePaymentsSummary` SwiftUI view without dismissing the keyboard of `BindableTextfield`.

**Comment by iamgabrielma** [comment]
Closing this one, Simple Payments has been migrated to order creation and this issue no longer appears when using Custom Amounts for these sort of one-off payments. The summary view is still used in the Tap To Pay trial flow, but it doesn't allow for bindable input as it always tests with a preset amount based on the country.
