### ISSUE TITLE
Update WordPressAuthenticator-iOS pod to version 1.2.0-beta.1

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#594]
In https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/42/, there are changes to the login flow. The alert message appears and is dismiss-able but doesn't present the new username / password login VC. It's possibly because we have the self-hosted flow turned off. (Also investigate `restrictToWPCom`).

Internal ref p1547234802205800-slack-C02Q9GACF

Make sure the flow works before committing to the new authenticator update.

### March 20, 2019 Update
https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/62 (aka WordPressAuthenticator-iOS pod to version 1.2.0-beta.1) adds a breaking change for WooCommerce if we switched to the new version of the pod.

**Comment by mindgraffiti** [comment]
The WordPressAuthenticator pod should work correctly in this flow after the Site URL Login is implemented.

**Comment by bummytime** [comment]
Closing this as it was fixed in #804
