### ISSUE TITLE
Magic Link workflow: Blue illustration seems out of place

### ISSUE THREAD

**Issue by bummytime** [woocommerce/woocommerce-ios#596]
While walking through the magic link workflow, I noticed this illustration seems a little out of place in our purple + grey world:

![magic_3](https://user-images.githubusercontent.com/154014/51130056-b99ad500-17f1-11e9-91e9-0d9963159254.png)

...but maybe not. I'll let @kyleaparker weigh in. 😄

**Comment by shiki** [comment]
The Login UI has been changed just recently and this is no longer valid.
