### ISSUE TITLE
[Mobile Payments] Include card details in refund UI

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#5976]
Interac payments must be refunded in the same card that was used for payment. To avoid confusion, we should show the last 4 digits and card type in the refunds UI. This already exists in the designs but it seems it was never implemented

![ios-orders-refund-confirm](https://user-images.githubusercontent.com/8739/151143363-f6adea3d-d564-471a-9ca4-1a26429686f9.png)

## Components

- [x] Add `charge_id` to `Order` (`data.meta_data[key].value where key == "_charge_id"`)
- [x] Networking code to fetch `Charge`
- [x] Storage for `Charge`
- [x] Yosemite for `Charge`
- [x] Get Charge on refund screen and display `brand` and `last4` when present
- [x] #6180
- [ ] #6181

**Comment by joshheald** [comment]
Side task: I noticed that the existing `Refund via` row can be selected, but doesn't do anything. This row should not be selectable
