### ISSUE TITLE
[Mobile Payments] Link to manual for WisePad 3

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#5980]
We need to add a link to the WisePad 3 card reader manual in In-Person Payment Settings.

There is one at this URL, but we should confirm if this is what we want to use:
https://stripe.com/files/docs/terminal/wp3_product_sheet.pdf

**Comment by koke** [comment]
@ctarda can you confirm if that looks like the right URL to use?

**Comment by ctarda** [comment]
@koke Yes, that is the one 😄
