### ISSUE TITLE
[Mobile Payments] Interac refunds UI & logic

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#5983]
Interac payments require that refunds are done in person using the same card that was used for payment.

> In-person refunds are mandatory for Interac transactions in Canada. You can’t create refunds in the API or in the Dashboard for these payments; you must use the client-side methods. In this flow, the reader prompts the cardholder to present the card used in the original charge. After the card details are read successfully, your application processes the refund. Similar to server-side refunds, you can perform partial refunds by passing in an amount less than the transaction value.
> 
> The currency and the card used for refund processing must be the same used for the original charge, otherwise the request fails with an error.

Instead of showing a generic modal with progress, the UI now has to prompt the customer to tap/insert the same card that was used to pay for the order. This new flow will also have to consider that the reader might not be connected and prompt the user to connect to a reader if needed. This flow would be similar to collecting a payment, except it will refund instead of charge.

The app will now initiate a refund as a two-step process. First, it calls collectRefundPaymentMethod to collect the card details, then processRefund creates the actual refund through Stripe’s API.

We’ll still have to call the WooCommerce API to communicate that a refund happened, but prevent it from trying to initiate another refund through Stripe. I initially thought we’d need changes to the backend, but it seems setting api_refund=false in the API call should be enough. However, I believe in that case the order won’t get any notes saying that the refund was handled via WCPay. That said, we could [create a note](https://href.li/?https://woocommerce.github.io/woocommerce-rest-api-docs/#create-an-order-note) from the app as well.

Internal discussion pdfdoF-mm-p2

- [x] #6437
- [x] #6445
- [x] #6471
- [x] In-person refund flow UI with card reader connection https://github.com/woocommerce/woocommerce-ios/pull/6602
- [x] #6461
- [x] Add unit tests for refund use case and orchestrator https://github.com/woocommerce/woocommerce-ios/pull/6639
- [x] Look into why there are no "Remove card" and "Processing" messages from the reader service https://github.com/woocommerce/woocommerce-ios/pull/6621
- [x] Update copy from payments to refunds https://github.com/woocommerce/woocommerce-ios/pull/6621
- [x] Handle refund payment cancellation: `CardPresentModalReaderIsReady.didTapSecondaryButton` currently calls `CardPresentPaymentAction.cancelPayment` by default https://github.com/woocommerce/woocommerce-ios/pull/6621
- [x] #6643
- [x] Update analytics to make sure card reader connection and software update events are logged correctly

Related issues:
- #6656
- #6658
- Handle when both Stripe extension and WCPay are active - let's show the onboarding flow when in-person refund is required as in https://github.com/woocommerce/woocommerce-ios/issues/6607

**Comment by jaclync** [comment]
Reopening this issue since there are still pending subtasks, I don't think it was closed intentionally 😄

**Comment by jaclync** [comment]
Since the related/remaining subtasks are now in separate issues, closing this issue for now!
