### ISSUE TITLE
[Mobile Payments] Add analytics for Canada Payments

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#5984]
Ref: pdfdoF-vx-p2
Android issue: https://github.com/woocommerce/woocommerce-android/issues/5713

## Updates to existing events

- [x] Add `country` property to all the existing IPP events + new ones:
  - [x] `*_card_reader_discovery_failed` https://github.com/woocommerce/woocommerce-ios/pull/6478
  - [x] `*_card_reader_connection_failed` https://github.com/woocommerce/woocommerce-ios/pull/6478
  - [x] `*_card_reader_connection_success` https://github.com/woocommerce/woocommerce-ios/pull/6478
  - [x] `*_card_reader_disconnect_tapped` https://github.com/woocommerce/woocommerce-ios/pull/6478
  - [x] `*_card_reader_software_update_started` https://github.com/woocommerce/woocommerce-ios/pull/6478
  - [x] `*_card_reader_software_update_success` https://github.com/woocommerce/woocommerce-ios/pull/6478
  - [x] `*_card_reader_software_update_failed` https://github.com/woocommerce/woocommerce-ios/pull/6478
  - [x] `*_card_reader_software_update_tapped` https://github.com/woocommerce/woocommerce-ios/pull/6478
  - [x] `*_card_reader_software_update_cancel_tapped` https://github.com/woocommerce/woocommerce-ios/pull/6478
  - [x] `*_card_reader_software_update_canceled` https://github.com/woocommerce/woocommerce-ios/pull/6478
  - [x] `*_card_present_collect_payment_tapped` https://github.com/woocommerce/woocommerce-ios/pull/6478
  - [x] `*_card_present_collect_payment_canceled` https://github.com/woocommerce/woocommerce-ios/pull/6478
  - [x] `*_card_present_collect_payment_failed` https://github.com/woocommerce/woocommerce-ios/pull/6478
  - [x] `*_card_present_collect_payment_success` https://github.com/woocommerce/woocommerce-ios/pull/6478
  - [x] `*_receipt_view_tapped` https://github.com/woocommerce/woocommerce-ios/pull/6545
  - [x] `*_receipt_email_tapped` https://github.com/woocommerce/woocommerce-ios/pull/6545
  - [x] `*_receipt_email_failed` https://github.com/woocommerce/woocommerce-ios/pull/6545
  - [x] `*_receipt_email_canceled` https://github.com/woocommerce/woocommerce-ios/pull/6545
  - [x] `*_receipt_email_success` https://github.com/woocommerce/woocommerce-ios/pull/6545
  - [x] `*_receipt_print_tapped` https://github.com/woocommerce/woocommerce-ios/pull/6545
  - [x] `*_receipt_print_failed` https://github.com/woocommerce/woocommerce-ios/pull/6545
  - [x] `*_receipt_print_canceled` https://github.com/woocommerce/woocommerce-ios/pull/6545
  - [x] `*_receipt_print_success` https://github.com/woocommerce/woocommerce-ios/pull/6545
  - [x] `*_card_present_onboarding_learn_more_tapped` https://github.com/woocommerce/woocommerce-ios/pull/6517
  - [x] `*_card_present_onboarding_not_completed` https://github.com/woocommerce/woocommerce-ios/pull/6517
- [ ] Add `card_reader_model` property to all the existing IPP events + new ones:
  - [x] `*_card_reader_discovery_failed` - not applicable
  - [x] `*_card_reader_connection_failed` https://github.com/woocommerce/woocommerce-ios/pull/6552
  - [x] `*_card_reader_connection_success` https://github.com/woocommerce/woocommerce-ios/pull/6552
  - [x] `*_card_reader_disconnect_tapped` https://github.com/woocommerce/woocommerce-ios/pull/6552
  - [x] `*_card_reader_software_update_started` https://github.com/woocommerce/woocommerce-ios/pull/6584
  - [x] `*_card_reader_software_update_success` https://github.com/woocommerce/woocommerce-ios/pull/6584
  - [x] `*_card_reader_software_update_failed` https://github.com/woocommerce/woocommerce-ios/pull/6584
  - [x] `*_card_reader_software_update_tapped` https://github.com/woocommerce/woocommerce-ios/pull/6584
  - [x] `*_card_reader_software_update_cancel_tapped` https://github.com/woocommerce/woocommerce-ios/pull/6584
  - [x] `*_card_reader_software_update_canceled` https://github.com/woocommerce/woocommerce-ios/pull/6584
  - [x] `*_card_present_collect_payment_tapped` https://github.com/woocommerce/woocommerce-ios/pull/6552
  - [x] `*_card_present_collect_payment_canceled` https://github.com/woocommerce/woocommerce-ios/pull/6552
  - [x] `*_card_present_collect_payment_failed` https://github.com/woocommerce/woocommerce-ios/pull/6552
  - [x] `*_card_present_collect_payment_success` https://github.com/woocommerce/woocommerce-ios/pull/6552
  - [ ] `*_receipt_view_tapped` - not applicable
  - [x] `*_receipt_email_tapped` https://github.com/woocommerce/woocommerce-ios/pull/6771
  - [x] `*_receipt_email_failed` https://github.com/woocommerce/woocommerce-ios/pull/6771
  - [x] `*_receipt_email_canceled` https://github.com/woocommerce/woocommerce-ios/pull/6771
  - [x] `*_receipt_email_success` https://github.com/woocommerce/woocommerce-ios/pull/6771
  - [x] `*_receipt_print_tapped` https://github.com/woocommerce/woocommerce-ios/pull/6771
  - [x] `*_receipt_print_failed` https://github.com/woocommerce/woocommerce-ios/pull/6771
  - [x] `*_receipt_print_canceled` https://github.com/woocommerce/woocommerce-ios/pull/6771
  - [x] `*_receipt_print_success` https://github.com/woocommerce/woocommerce-ios/pull/6771
  - [ ] `*_card_present_onboarding_learn_more_tapped` - not applicable
  - [ ] `*_card_present_onboarding_not_completed` - not applicable
- [x] Update `card_present_collect_payment_canceled` event tracking in `CardPresentModalReaderIsReady` to call `WooAnalyticsEvent.InPersonPayments` (ref https://github.com/woocommerce/woocommerce-ios/pull/6478#pullrequestreview-917491921) https://github.com/woocommerce/woocommerce-ios/pull/6517
- [x] Add the `payment_method_type` property to the card payment success and failed events: `card_present_collect_payment_success` https://github.com/woocommerce/woocommerce-ios/pull/6495
 
## New events

_Moved to #6655_

Also, these events haven't been tracked in iOS and we can add them here:

Event | Properties | Trigger
-- | -- | --
*_card_reader_location_success | Location was fetched successfully from the backend while connecting to the reader |   |  
*_card_reader_location_failure | Location fetching failed while connecting to the reader | Failure reason | We want to know how often location failure occurs and for what reason
*_card_reader_location_missing_tapped | User tapped the "Enter Address" button which is shown while connecting to the reader if the user's store does not have any default address associated with it |   |  

These events are defined in the codebase but not currently tracked, let's add them if Android implements them:
* `*_card_reader_discovery_reader_discovered`
* `*_card_reader_discovery_tapped`
* `*_card_reader_connection_tapped`

---
Evaluate what we want to track differently here. Some initial suggestions:

- Include store country, currency, and reader model as properties in related events
- Track success/errors when communicating payment/refunds to the store
- New screens in the card-present refund

**Comment by joshheald** [comment]
I think these events are the highest priority for doing pre-launch, so I think we should break them out of this ticket to make prioritisation clearer...

## New events

Event | Properties | Trigger
-- | -- | --
*_CARD_INTERAC_COLLECT_PAYMENT_SUCCESS | | Tracked right after processing succeeds.
*_interac_refund_success | | Tracked when an Interac in-person refund succeeds on the client side.
*_interac_refund_failed | error | Tracked when an Interac in-person refund fails on the client side.
