### ISSUE TITLE
Order Creation: When picking a country, I am forcefully navigated back to the main Order Creation UI

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#5997]
@ealeksandrov Not sure if this is something we're already aware of or is still WIP. Just logging it just in case. 

https://user-images.githubusercontent.com/198826/151428380-c3dc36d3-330a-487a-b8f6-dc489e90750e.mp4

**Comment by ealeksandrov** [comment]
@shiki, is that iOS 14.5? That's a known bug that slipped through during refactoring. Thanks for noticing!

Fix pushed in https://github.com/woocommerce/woocommerce-ios/pull/6012/commits/1931974cbd4861a5e0814eed769511fa6b7c4176.

**Comment by shiki** [comment]
Thanks for fixing it! It's iOS 14.8 iPhone Xs.
