### ISSUE TITLE
[Mobile Payment] Update UX to reflect latest designs when Stripe AND WCPay gateways are active

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#6010]
Per @adamzelinski 

> new iteration which is just an error screen which tells the Merchant they can't have 2 active and will need to disable one to continue.
> If the merchant is an administration we can link them out to the plugin admin in a mobile webview. If they're a store owner we can just hide the button and tell them to contact a site admin to make this change.
> as for the contact support action, it should pass along the context that the merchant got this error about two plugins enabled (and also route to wcpay support, not the main queue)

Full design in Figma

<img width="1782" alt="Screen Shot 2022-01-28 at 1 15 58 pm" src="https://user-images.githubusercontent.com/1595739/151592795-a20f0f6a-0aac-44a5-a047-1166ca0999ff.png">

**Comment by malinajirka** [comment]
The "Refresh after updating" button was added to the designs so they stay consistent with the other onboarding screens
<img width="1048" alt="Screenshot 2022-01-31 at 9 13 57" src="https://user-images.githubusercontent.com/2261188/151759518-449270e5-d73c-4878-92ec-92ebadd026f8.png">
cc @allendav

**Comment by allendav** [comment]
@adamzelinski @malinajirka - I'm applying these changes now and I have some suggested wording changes:

Figma: Multiple payment providers detected
Proposal: Conflicting payment plugins detected
Rationale: The term "payment providers" doesn't exist in WooCommerce. We want them to deactivate a plugin, so let's use plugin. (I appreciate WooCommerce may refer to these as extensions, but I don't think we use that term in the apps either.) Also, multiple isn't the problem (they can have PayPal and WCPay for example) - so I'd say "Conflicting" instead of "Multiple"

Figma: In-Person Payments will only work with one provider activated. Please contact a site administrator to deactivate one of these to continue.
Proposal: In-Person Payments will only work with one of following plugins activated. Please contact a site administrator to deactivate one of these plugins to continue.
Rationale: Replace provider with what we really want them to think about in this context - a plugin. Replace "these" again with what we specifically need them to deal with - a plugin. This is what they need to ask the administrator to deactivate.

Figma: In-Person Payments will only work with one provider activated. Please deactivate one of these to continue.
Proposal: In-Person Payments will only work with one of following plugins activated. Please deactivate one of these plugins to continue.
Rationale: Same as above

Figma: Learn more about multiple payment providers and in-person payments.
Proposal: Learn more about payment plugins and in-person payments.
Rationale: Same as above. Also, is there a page ready to link to?

Figma: Go to Plugin Admin
Proposal: Manage Plugins
Rationale: Plugin Admin is a new term (I think), and an abbreviation too. Best not to introduce new terms and ones that might be hard to localize.

Thoughts?

fyi @ctarda

**Comment by malinajirka** [comment]
Thanks so much for the suggestions! I agree with everything you said.

> Figma: Learn more about multiple payment providers and in-person payments.
> Proposal: Learn more about payment plugins and in-person payments.
> Rationale: Same as above. Also, is there a page ready to link to?

Tbh I didn't even notice this change and I'd vote for keeping the learn more link identical to the other screens ->
"Learn more about accepting payments with your mobile device and ordering card readers".

**Comment by ghost** [comment]
@allendav @malinajirka these suggestions sound good to me thanks. I've updated the Figma designs to match as well.
