### ISSUE TITLE
Order Creation: Spaces initially do not appear when typing in Customer Details

### ISSUE THREAD

**Issue by thehenrybyrd** [woocommerce/woocommerce-ios#6018]
**Describe the bug**
When adding or editing Customer Details, spaces do not appear until another character is typed after the space. @ealeksandrov I know this area is still WIP, not sure if you're aware of this issue.

**To Reproduce**
1. From Orders, tap "+" and choose "Create Order".
2. Tap "Add customer"
3. Type in some customer details. As you do, add some spaces. This is most noticeable when typing an address.
4. Note that, when you type a space, you do not see the space appear. When type the next character, you'll see the space and the new character.

**Video**

https://user-images.githubusercontent.com/15107387/151795303-f6a9446e-a1f1-4935-a293-6f4a64801f45.MP4

**Expected behavior**
I expected to see spaces immediately when typing in customer details.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**

- Device: iPhone 12 mini
- iOS version: 14.8.1
- WooCommerce iOS version: 8.4 (33012)

**Tested on Pressable w/Jetpack and on a WordPress.com Atomic site.**

**Comment by ealeksandrov** [comment]
This will be resolved if we align fields as in the design (discussed in https://github.com/woocommerce/woocommerce-ios/issues/5084).

**Comment by Ecarrion** [comment]
@ealeksandrov should we close this issue then?

**Comment by thehenrybyrd** [comment]
I can still reproduce this in 8.9; I see that https://github.com/woocommerce/woocommerce-ios/issues/5084 hasn't been addressed yet though.
This isn't blocking any functionality, but it really does feel unpolished. I think it likely users will notice this when they enter a real address.
