### ISSUE TITLE
Order Creation: Create/update a draft order when data is added or changed (lazy draft creation)

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#6023]
Currently, we do not create a new order remotely until the "Create" button is tapped.

We need to implement lazy draft creation, to be able to display payment details from the API:

> After some discussions about how we can approach the order prices calculation, especially taxes, it was decided that we will create a draft order, and keep updating it when any changes occur on the device to get the backend to calculate the prices for us, and to make sure we don’t show any non-accurate prices during the creation process.

**Our goals:**

- Use a draft order as a way to have the backend to calculate the payment data (prices, taxes, etc.). The order will have the status `auto-draft` (if the store has a version of Core that supports it) or the status `pending` for older versions of Core.
- When the merchant does any changes to things that would impact the order prices, we need to update the order draft, to get new totals. (This includes changes to products and their quantity, billing/shipping addresses, shipping costs, fees.)
- We need to show a non-blocking loading indicator while creating or updating the order.
- If an error occurs while updating the order, we need to show a persistent error indicator, and disallow creating the order on this status.
- It would be nice to have a debouncing logic for the changes to reduce the number of API requests.

**API considerations:**

- To make the backend recalculate the `subtotal_tax` and `total`, when a product quantity changes we need to calculate the the `subtotal` and `total` (without taxes) locally on the client side, and send them along the API request; changing the `quantity` alone won’t update any pricing of the item. This means that for any quantity change, we need to send the following:
```
{
    "id": {item_id},
    "product_id": {product_id},
    "variation_id": {variation_id}, // if applicable
    "quantity": {quantity},
    "subtotal": {subtotal}, // Calculated on client side
    "total": {total} // Same value as subtotal
}
```
- To ensure the product price and tax is calculated correctly (e.g. when "Prices entered with tax" is enabled on the store), we need to make sure any new items in the Order are added without specifying the subtotal and total, meaning adding only this part for new items:
```
{
            "product_id": {id},
            "quantity": 1
}
```
- To delete an item from an order, we need to update the quantity to `0`, deleting it from the list means that the backend won’t make any changes to this given item.

More discussion: p91TBi-7hZ-p2

**Comment by Ecarrion** [comment]
Closing this in favor of:
 
- https://github.com/woocommerce/woocommerce-ios/issues/6127
- https://github.com/woocommerce/woocommerce-ios/issues/6128
- https://github.com/woocommerce/woocommerce-ios/issues/6129
- https://github.com/woocommerce/woocommerce-ios/issues/6132
- https://github.com/woocommerce/woocommerce-ios/issues/6133
- https://github.com/woocommerce/woocommerce-ios/issues/6134
- https://github.com/woocommerce/woocommerce-ios/issues/6135
- https://github.com/woocommerce/woocommerce-ios/issues/6142
- https://github.com/woocommerce/woocommerce-ios/issues/6136
- https://github.com/woocommerce/woocommerce-ios/issues/6137
- https://github.com/woocommerce/woocommerce-ios/issues/6138
- https://github.com/woocommerce/woocommerce-ios/issues/6139
- https://github.com/woocommerce/woocommerce-ios/issues/6140
- https://github.com/woocommerce/woocommerce-ios/issues/6141
- https://github.com/woocommerce/woocommerce-ios/issues/6143
