### ISSUE TITLE
Order Creation: Display selected variation attributes

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#6031]
When adding a variation, the attributes are not displayed in the products list. 

Order Creation (Missing Attributes) | Order Details (Correct)
--------|-------
![IMG_8744](https://user-images.githubusercontent.com/198826/151844450-a863ec10-5608-4269-8548-c25ed615654e.PNG)        |      ![image](https://user-images.githubusercontent.com/198826/151844599-a5dae2b5-e60f-4bab-a1cf-ba6a001a4389.png)

**Comment by shiki** [comment]
@ThomazFB  @rachelmcr @thehenrybyrd This happens for both iOS and Android. I suppose this is something we can do after M1?

**Comment by ThomazFB** [comment]
@shiki We can include that on M2 for sure, but I think it should be set as a low priority. Do you agree?

**Comment by shiki** [comment]
The side effect that I see is that this will decrease our merchant's confidence in using the app. If they add a variation, they're not sure if they _picked_ the correct product. It gets more troublesome if they have lots of variations with the same picture. This will cost time too since they'll have to double-check. 

Given that, I think this is a higher priority than the rest of M2.

**Comment by ThomazFB** [comment]
Fair point @shiki, I didn't think about this perspective, thanks for clarifying it. I agree with you on this, I'll create this improvement on the Android side and make sure it will be delivered ASAP.

**Comment by rachelmcr** [comment]
Do we want to show the variation attributes _in addition_ to the other details we're already showing (including stock status, which we don't show in Order Details)? Or do we want to exactly match the details we show in Order Details, i.e. show the variation attributes but _not_ the stock status?

**Comment by shiki** [comment]
Summoning @adamzelinski for this. 😁 Do you have some input on Rachel's question, Adam? 🙂

**Comment by ghost** [comment]
Hi, @rachelmcr let's just show the variation attributes but not the stock status for this. Thanks!
