### ISSUE TITLE
Order Details: Note type seems to be inconsistent

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-ios#604]
**Describe the bug**
Comparing an order between iOS and Android I'm seeing some differences when a note is being displayed. More often the app is showing something as a system status message when in fact it's a private note or a note to the customer.

**To Reproduce**
I can't reliably reproduce the behavior but I can provide order numbers on a test site if you contact me directly. Screenshot is from @juliaamosova's test site.

**Screenshots**
![img_6403](https://user-images.githubusercontent.com/373903/51138535-f02f1a80-1806-11e9-8e97-a8dfc0ea5ba2.png)

**Expected behavior**
Notes should show expected type text and matching icon.

**Mobile Environment**
Please include:
- Device: iPhone X
- iOS version: 12.1.2
- WooCommerce iOS version: 1.0

**Comment by bummytime** [comment]
Looks like we have some faulty logic to clean up [here](https://github.com/woocommerce/woocommerce-ios/blob/issue/604-order-note/WooCommerce/Classes/ViewRelated/Orders/Cells/OrderNoteTableViewCell.swift#L82-L93). Should be an easy fix...PR incoming.
