### ISSUE TITLE
Notifications: Truncated text should show trailing ellipsis

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-ios#605]
**Describe the bug**
The notifications table doesn't indicate if there is more text than what is displayed for a product review.

**To Reproduce**
1. Place a product review with several sentences of text.
2. Wait for the notification to come through.
3. View the notifications screen. See the text is truncated.

**Screenshots**
![img_6404](https://user-images.githubusercontent.com/373903/51138869-ed80f500-1807-11e9-999e-407945e5b7b9.png)

**Expected behavior**
If the text is truncated then show an ellipsis (…) to indicate such.

**Mobile Environment**
Please include:
- Device: iPhone X
- iOS version: 12.1.2
- WooCommerce iOS version: 1.0

**Comment by mindgraffiti** [comment]
This bug goes deep into the `StringFormatter` code. I think what will have to happen is the `StringFormatter` will need to replace the last character (in the review body) and append the ellipsis character.
