### ISSUE TITLE
Order Creation: Hit area of products list does not cover the whole row

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#6061]
It looks like the hit area is limited only to the label portion. I cannot tap on the empty space to select a product.

<img src="https://user-images.githubusercontent.com/198826/152398363-a36e4726-ee29-4152-80d3-a7088a962d39.png" width="300">

Using iPhone Xs iOS 14.

**Comment by rachelmcr** [comment]
Oh, good catch! We can fix that in SwiftUI by adding `.contentShape(Rectangle())` to the row. It's probably worth adding it to `ProductRow` so it applies everywhere that component is used, but we should check to make sure that the tap works as expected when the stepper is visible (i.e. when a product is added to a new order, tapping on the stepper should change the quantity but tapping elsewhere on the row should open the product detail view).
