### ISSUE TITLE
Order Creation: Last text field is selected after picking Country

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#6063]
This applies to both Order Creation and Order Editing.

## Steps

1. Add Customer
2. Tap on Postal Code
3. Enter a postal code
4. Scroll down 
5. Tap Country
6. Pick a country
7. Go back

The postal code text field will still be selected. I think this will cause some confusion when filling in the fields. In this case, the Country will be hidden from view. 

I'm guessing this also applies to State. 

## Video

https://user-images.githubusercontent.com/198826/152416360-4c5efaa7-f91d-4264-882f-caa9aa0c7524.MP4

## Device

Tested on iPhone Xs iOS 14

**Comment by pmusolino** [comment]
I tested this on iOS 15 and the issue doesn't happen anymore. @shiki are you able to re-tested it on iOS 14?

**Comment by shiki** [comment]
@pmusolino I just checked and this still happens on iOS 14. Do you think this is worth it to fix?

**Comment by pmusolino** [comment]
@shiki we should find a workaround just for iOS 14. Probably it's a minor bug and we can left it? I believe that in around 1 year we will drop iOS 14 if the numbers are low.

**Comment by shiki** [comment]
Okay. In that case, I think we can just close this for now. 

cc @rachelmcr
