### ISSUE TITLE
Order Creation: Accessibility → Loading indicator row should not be accessible

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#6070]
This should probably not be accessible via VoiceOver. Or should this be hidden too when the loading has completed? Or maybe have "loading" as the label? 🤷 

<img src="https://user-images.githubusercontent.com/198826/152431983-41d7d292-56df-4d4c-8d1e-88525c5baf33.png" width="300">

**Comment by rachelmcr** [comment]
I think "loading" as a label makes sense here, in case you reach the end of the list and more content is loading. (I have trouble doing that with VoiceOver, but if I simulate a very slow network connection I can get there and it seems like a good general label for infinite scroll lists.)

The row isn't accessible to me when there isn't more content loading, so I think we're good in that case.
