### ISSUE TITLE
Order Creation: Accessibility → Address announcement can be improved

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#6076]
When navigating to the Shipping or Billing Address using VoiceOver, I noticed that VoiceOver does not pause at all. This makes it difficult to hear which part is the street address, city, etc. 

I'm not sure if this can be fixed. Let me know if it can't! 

The label (e.g. Shipping Address) can also be grouped together with the address to reduce the number of accessible elements. This is always a plus when using VoiceOver. 

<img src="https://user-images.githubusercontent.com/198826/152436793-669d4fee-8ffc-41f6-8df2-8253296a3209.png" width="300">

**Comment by rachelmcr** [comment]
> When navigating to the Shipping or Billing Address using VoiceOver, I noticed that VoiceOver does not pause at all. This makes it difficult to hear which part is the street address, city, etc.

We're using Apple's `CNPostalAddressFormatter` to construct this formatted address, and this behavior matches how VoiceOver reads addresses in the Contacts app, so I think this is acceptable behavior.

**Comment by shiki** [comment]
Oof. Okay. Good to know!

**Comment by shiki** [comment]
I closed this too soon. Let me know if this should/can be fixed too, @rachelmcr. 

> The label (e.g. Shipping Address) can also be grouped together with the address to reduce the number of accessible elements. This is always a plus when using VoiceOver.

**Comment by rachelmcr** [comment]
Oh yes, I agree we should still do that grouping! I'll have a PR up with that and some other improvements soon.
