### ISSUE TITLE
Can not select any date in custom range selection for the orders filters

### ISSUE THREAD

**Issue by chrisKns** [woocommerce/woocommerce-ios#6089]
**Describe the bug**
In the custom range selection for the orders filters if you select the custom start/end dates in a particular order and then try to select again the start or end date it will have all the dates not available for selection.   

*Details*
The same datepicker is reused for the start and end date so each will set a maximum and a minimum date and then (since  they are never cleared in the prepareforReuse) no dates not available for selection.

**To Reproduce**
1. Go to `Orders`
2. Tap on 'Filters'
3. Tap on 'Date Range'
4. Tap on 'Custom Range'
5.  Tap on 'Start Range'
6. Tap on 'End Range'
7. Tap on 'Start Range' again
8. All the dates are not available for selection

**Screenshots**

https://user-images.githubusercontent.com/96764631/152687584-9c1a4ea5-8e6c-446e-8c14-a2221accfd7b.mp4

**Expected behavior**

In the custom start date of the date range picker all dates until the end date should be available for selection.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Any
- iOS version:  Any
- WooCommerce iOS version: Any

**WordPress Environment**
Not relevant

**Comment by pmusolino** [comment]
Duplicated issue: https://github.com/woocommerce/woocommerce-ios/issues/5647
