### ISSUE TITLE
Order Details: Add payment link to pending orders

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#6101]
Ref p91TBi-72H-p2#comment-8149

Add the ability to share a payment link when the order has a pending status.

Let's wait until https://github.com/woocommerce/woocommerce-ios/issues/6087 is fixed and https://github.com/woocommerce/woocommerce/pull/31826 is released to production.

### Design 

![share-payment-link](https://user-images.githubusercontent.com/562080/152855914-77d265ea-07a7-4c5c-9fa5-e611cd9523f6.png)

Let's also add a Tracks event for this.

- [x] woocommerceios_order_detail_payment_link_shared

--- 

Related: https://github.com/woocommerce/woocommerce-android/issues/5924

**Comment by shiki** [comment]
@Ecarrion Would it be possible to do an `if` statement for generating the payment link? 

```
if payment_url is available
    then use payment_url
else
    then use the old buggy way
```

I'm just looking for tasks that Renan may be able to do. 😁 

Not everyone would also be updating to the recent WooCommerce version right away.

**Comment by shiki** [comment]
On second thought, we can't ask them to upgrade if WC 6.4 is not even released yet. So yeah, not a good idea. 🤷

**Comment by Ecarrion** [comment]
Exactly, can't really begin to work on this until WC 6.4 beta is released.
