### ISSUE TITLE
Notifications: Order notification pushed through twice

### ISSUE THREAD

**Issue by kyleaparker** [woocommerce/woocommerce-ios#611]
**Describe the bug**
I'm noticing the order notification is coming through twice for a single order. Once when the order is place and then again when the order is marked as fulfilled. 

**To Reproduce**
1. Place an Order
2. Go to the order and mark the order as complete
3. Wait on the screen for a couple of seconds
4. Notice the push notification comes through a second time

**Screenshots**

**Expected behavior**
Only one push notification for each order

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: 
- iOS version: 
- WooCommerce iOS version: 

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by bummytime** [comment]
@kyleaparker I am not able to repro this issue, so some additional questions for you:

1. What version of the app is this happening on?
2. Is this behavior isolated to a single store or multiple stores?
3. What WC version?

**Comment by bummytime** [comment]
@kyleaparker disregard the previous. 😄 

p90Yrv-Vs-p2

**Comment by bummytime** [comment]
Fixed via server-side updates! 

/cc @astralbodies
