### ISSUE TITLE
Order Creation - Product Sync: Update UI with taxes loading indicator

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#6133]
While the order is being created or updated, we need to show a non-blocking loading indicator in the main order creation screen.

### To Define
- Designs

**Comment by rachelmcr** [comment]
For the design, we can display a loading (activity) indicator on the same line as the Payment section heading (internal ref: p91TBi-7hZ-p2#comment-8228). Here's how that looks in Android:

![Screen Shot 2022-02-17 at 5 23 12 PM](https://user-images.githubusercontent.com/8658164/154536758-37b8f117-2df4-40d6-ad13-f2f8fbd2b9e6.png)
