### ISSUE TITLE
Order Creation  - Product Sync:  Disable order button on error

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#6135]
If there is an error while creating/syncing an order we should disable the `Create` button until the request succeeds.

### Questions:
- Should we disable the create button while the order is being synced?

**Comment by rachelmcr** [comment]
> Should we disable the create button while the order is being synced?

Are there any risks that the order data in the created order will be inaccurate if it hasn't finished syncing before the order is created? Or is the only problem that the totals displayed in the Payment section won't be accurate? If it's only a display issue, I don't think we should block the order from being created, even if the sync hasn't finished. The loading indicator in the Payment section should be sufficient for communicating to the merchant that the totals they see may not be final/accurate yet.

**Comment by Ecarrion** [comment]
I'm thinking that now that we have a permanent sync error notice we don't need to block the "create" button at all.
We should just leave the merchant tap "create" if they want.

@rachelmcr feel free to re-open if you consider otherwise.
