### ISSUE TITLE
Notifications: cha-ching sound is not playing for new orders

### ISSUE THREAD

**Issue by bummytime** [woocommerce/woocommerce-ios#614]
**Describe the bug**
When recieving a new order notification, the default iOS notification sound is playing instead of the cha-ching sound.

**To Reproduce**
1. Place a new order on the web
2. Wait for the push notification
3. Recoil in horror as you hear the default notification sound

**Expected behavior**
New Order notifications play the cha-ching sound

**Mobile Environment**
Please include:
- Device: iPhone Xs
- iOS version: 12.1.2
- WooCommerce iOS version: 1.0.0.1 (App Store)

Ref:
p1547581621488000-slack-C6H8C3G23

**Comment by astralbodies** [comment]
Resolved with a backend fix.

**Comment by designsimply** [comment]
This still comes up from time to time from users, including in app reviews such as this one: 

> My cha-ching is gone
> May 23, 2021 - Version 6.6 - Croatia
> My cha-ching sound stopped with new orders, not getting any notifications. Notification settings seem ok on my iphone, what should i do?

I tested today using WooCommerce 6.6 on an iPhone 11 iOS 14.6 and the cha-ching sound worked in my test for a new order notification and I just wanted to note that I did test it and that it is working as expected. 🙂

<img src="https://user-images.githubusercontent.com/1119271/119420921-b6b22800-bcba-11eb-950e-ff514d8f37bc.PNG" width="270" alt="IMG_4844"> <img src="https://user-images.githubusercontent.com/1119271/119420923-b9148200-bcba-11eb-918a-8034ddbc7a1a.PNG" width="270" alt="IMG_4843">

Recommended troubleshooting steps: 

1. Ask the user to please double check to make sure notifications on for the WooCommerce app and that sounds are allowed.
1. Ask the user to please double check that their [iPhone is set to Ring mode](https://support.apple.com/en-us/HT208353) not Silent mode.
