### ISSUE TITLE
[Mobile Payments] Multiple InPersonPaymentsViewModels and VCs are retained after repeatedly entering/exiting IPP in settings

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#6154]
**Describe the bug**
- Entering settings menu items, like Help and Support for example, show an instance of the HelpAndSupportViewController in Xcode's memory graph while on that page that is then removed when navigating back to the settings list. Unfortunately, each time you navigate into In-Person Payments on that same settings page, you get a InPersonPaymentsViewModel and InPersonPaymentsViewController that are retained on navigating back to settings.

**What's the Impact?**
- This is worrisome not just because it is a leak but moreso because lower level IPP ViewModels are very active in terms of managing card readers. We should expect some odd behavior if this retention at the highest level leads us to have multiple instances of `CardReaderSettingsConnectedViewModel` or `CardReaderSettingsSearchingViewModel` active when managing readers.

**To Reproduce**
1. Set your Run Scheme options to enable memory logging for live allocations and start the app
2. Tap on Menu, then Settings (gear)
3. Tap on Help and Support
4. Click on the memory graph icon in Xcode - this pauses app execution
5. Note the WooCommerce > WooCommerce > HelpandSupportViewController single instance
6. Resume the app
7. Navigate back out of help and support to the settings list
8. Click on the memory graph icon in Xcode - this pauses app execution
5. Note that there is now NO HelpandSupportViewController instance in WooCommerce > WooCommerce
6. Resume the app
7. Tap on In Person Payments
8. Navigate back out of IPP to the settings list
9. Do this several times
10. Click on the memory graph icon in Xcode - this pauses app execution
11. Note the many, many instances of WooCommerce > WooCommerce > InPersonPaymentsViewController and InPersonPaymentsViewModel
12. You should also notice memory usage increasing a bit each time  

**Screenshots**

Setting your run scheme options to enable memory logging:
<img width="1066" alt="0-scheme" src="https://user-images.githubusercontent.com/1595739/153665837-192ad535-30ac-472b-a91a-59ffa0ee5572.png">

To pause execution and open the memory graph, click this icon:
<img width="640" alt="2-memory-graph-control" src="https://user-images.githubusercontent.com/1595739/153666133-29ca6300-f3c8-489c-9912-19cc76f25d8c.png">

Example of what the graph looks like when Help & Support (which is working properly) is open
<img width="960" alt="1-memory-graph-help-and-support-open" src="https://user-images.githubusercontent.com/1595739/153665872-1a415b08-a653-44a1-aae3-9e919ed69b78.png">

<img width="1153" alt="1a-memory-graph-help-and-support-open-one-instance" src="https://user-images.githubusercontent.com/1595739/153665932-22221cde-83f5-495f-b50f-ae5d0c907f78.png">

Resume execution the usual way:
<img width="641" alt="3-continue-execution" src="https://user-images.githubusercontent.com/1595739/153666041-8d035aec-ec39-40bb-aeb7-43aca984cbe0.png">

Pause again after closing Help & Support. Note that after closing Help & Support, the entry is no longer in the list. This is the correct behavior:
<img width="989" alt="1b-memory-graph-help-and-support-closed" src="https://user-images.githubusercontent.com/1595739/153665959-46ad995f-aba5-48af-97d2-667983022b8c.png">

But if you repeat this process for the IPP menu item, you get multiple VMs (and VCs):
<img width="612" alt="4-multiple-ipp-vm" src="https://user-images.githubusercontent.com/1595739/153666280-29e08632-7ed2-4073-b791-66db89f68887.png">

**Expected behavior**
- After exiting IPP back to the root of settings, the IPP VM and VCs should no longer be retained

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: 
- iOS version: 
- WooCommerce iOS version: 

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by allendav** [comment]
Noteworthy: Commenting out the view controller (and then repeatedly tapping on the menu item) shows no retained view models. This points at the VC being the troublemaker.

```
    func inPersonPaymentsWasPressed() {
        let viewModel = InPersonPaymentsViewModel()
        //let viewController = InPersonPaymentsViewController(viewModel: viewModel)
        //show(viewController, sender: self)
    }
```

**Comment by ctarda** [comment]
@allendav  The leak seems to be in the closures passed in the initialization of InPersonPaymentsViewController.

Looking at the memory graph, I see what looks like a strong reference to self InPersonPaymentsViewController:

<img width="350" alt="Screen Shot 2022-02-11 at 4 53 23 PM" src="https://user-images.githubusercontent.com/2722505/153675599-90c92e98-1cba-4d3d-8532-5d1596991d9d.png">

Then I looked at the way the closures passed to rootView.showSupport and rootView.showURL are declared. There seems to be a strong reference to self 

So, to confirm my hunch, this is what I have done:

First, to confirm the leak, a bit of caveperson / old style debugging, overriding deinit in InPersonPaymentsViewController:
```
final class InPersonPaymentsViewController: UIHostingController<InPersonPaymentsView> {
    init(viewModel: InPersonPaymentsViewModel) {
        super.init(rootView: InPersonPaymentsView(viewModel: viewModel))
        rootView.showSupport = {
            ZendeskProvider.shared.showNewWCPayRequestIfPossible(from: self)
        }
        rootView.showURL = { url in
            WebviewHelper.launch(url, with: self)
        }
    }

    @objc required dynamic init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    deinit {
        print("===== deiniting InPersonPaymentsViewController")
    }
}
```

Navigating in and out of the In-Person Payments confirms that deinit is not hit. InPersonPaymentsViewController is not deallocated. 

Then I weakified the reference to self in the closures passed to rootView.showSupport and rootView.showURL:
```
final class InPersonPaymentsViewController: UIHostingController<InPersonPaymentsView> {
    init(viewModel: InPersonPaymentsViewModel) {
        super.init(rootView: InPersonPaymentsView(viewModel: viewModel))
        rootView.showSupport = { [weak self] in
            guard let self = self else { return }
            ZendeskProvider.shared.showNewWCPayRequestIfPossible(from: self)
        }
        rootView.showURL = { [weak self] url in
            guard let self = self else { return }
            WebviewHelper.launch(url, with: self)
        }
    }

    @objc required dynamic init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    deinit {
        print("===== deiniting InPersonPaymentsViewController")
    }
}
```

Now I see deinit being hit.

I also run the app through the leaks Instrument, and I do not see any leak specific to this View Controller.

Hope that helps! 😄
