### ISSUE TITLE
Handle survey type differently

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#6173]
Ref p6q6po-b6x-p2#comment-91746
Design confirmation: p1645771532573489-slack-C02N7N92DEV

left: before submission; right: after submission
<img width="640" alt="Screen Shot 2022-03-02 at 5 13 17 PM" src="https://user-images.githubusercontent.com/1945542/156331271-847f3ebf-c8d9-40a3-8a61-a4f5339851e7.png">

**Comment by pmusolino** [comment]
Waiting for feedback from the design team before starting the implementation.
