### ISSUE TITLE
Order Creation: Update the feedback banner to mention Order Creation + Simple Payments

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#6177]
When releasing Order Creation, we should also update the banner so it mentions both Order Creation and Simple Payments. 

Here is the suggested copy:

<img src="https://user-images.githubusercontent.com/198826/154102709-e72fc0ca-e769-44d6-a1ba-89c5bfcab97d.png" width="300">

I think we can use the same survey URL. But let's discuss this first. 

---

p1644885330517869-slack-C02KUCFCSFP

https://github.com/woocommerce/woocommerce-android/issues/5861

**Comment by Ecarrion** [comment]
@shiki should we update the survey format? If not, I think it could be troublesome to differentiate feedback from one feature of another.

**Comment by shiki** [comment]
@Ecarrion I'm not sure what you mean by survey format. 🙃 Can you tell me more, please?

**Comment by Ecarrion** [comment]
The survey screen, triggered by pressing the "Give Feedback" button, only receives a text input. I think we could have problems identifying which feedback corresponds to a specific feature.

![image](https://user-images.githubusercontent.com/562080/154274377-c1161b00-6969-4784-9528-ed95bf110819.jpeg)

**Comment by shiki** [comment]
Oh, that's a good reminder! 

Should we do something like this? 

<img src="https://user-images.githubusercontent.com/198826/154280518-987b7594-64f2-4a9c-bff1-5a37db5d780a.png" width="300">

I remember we also wanted to respond to them but couldn't. So, asking for the email address (optional) would also be nice.
