### ISSUE TITLE
Order Creation: Country List not translated

### ISSUE THREAD

**Issue by thehenrybyrd** [woocommerce/woocommerce-ios#6192]
**Describe the bug**
When entering (or editing) billing/shipping details, the Country List invariably appears in English. This is the case whether the app settings are set to another language, or the whole phone.

**To Reproduce**
1. Head to Menu >  ⚙️  > Open Device Settings
2. From the Woo settings, select language preferences and change languages. 
3. Head back into the app, and either create a new order or edit an existing order.
4. Open Customer Details and tap "Country".
5. Note that the names of the countries are all in English, regardless of the language you selected.

Alternatively:
1. Open the Settings app and head to General > Language and Region.
2. Change iPhone Language to another language. 
3. Head back into the app, and either create a new order or edit an existing order.
4. Open Customer Details and tap "Country".
5. Note that the names of the countries are all in English, regardless of the language you selected.

**Screenshots - Spanish, Arabic, Korean**
![countrylistios](https://user-images.githubusercontent.com/15107387/154227193-9bced9de-f2fa-4397-960b-36ac2f2c202c.png)

**Expected behavior**
I expected the country list to be in the language I am using the app in.

**Isolating the problem:**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 12 mini
- iOS version: 15.3.1
- WooCommerce iOS version: 8.5.0.0

**Comment by thehenrybyrd** [comment]
The same issue exists on Android: https://github.com/woocommerce/woocommerce-android/issues/5866

**Comment by rachelmcr** [comment]
As mentioned in Slack, the country list comes from the REST API and is localized based on the store's language setting. It seems most likely that the store's language setting and the device language will be the same, and in cases where they differ it should be ok, so we'll leave this as-is. (This is the same way we handle order statuses, which also come from the backend.)

Internal ref: p1645016570927779-slack-C02KUCFCSFP
