### ISSUE TITLE
[Mobile Payments] Redirect to Order Reader flow depending on active plugin

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-ios#6218]
When the user presses "Settings -> In Person Payments -> Order Card Reader" the app should navigate to
- https://woocommerce.com/products/m2-card-reader/ for WCPay
- https://stripe.com/terminal/stripe-reader for Stripe

cc @allendav

**Comment by allendav** [comment]
Can do. Working on this now. There will be an eventual intersection with Canada too, so ccing @koke and @ctarda so they are aware this is coming

Edit: I see you're already aware of it:

> private static func purchaseCardReaderUrl(for countryCode: String) -> URL

**Comment by allendav** [comment]
Based on pdfdoF-su-p2 I take it that the URLs should actually be

https://woocommerce.com/products/hardware/$COUNTRY_CODE when the WCPay plugin is active on the store

and

https://stripe.com/terminal/stripe-reader when the Stripe plugin is active on the store

**Comment by malinajirka** [comment]
My understanding is that `https://woocommerce.com/products/hardware/$COUNTRY_CODE` should be used when Canada IPP feature flag is enabled. I don't know what is the state on iOS but on Android the flag is still disabled.
