### ISSUE TITLE
Order Creation: Review test coverage

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#6220]
Related p91TBi-7v0-p2.

- Do we have sufficient coverage? 
- What else should we include?

**Comment by rachelmcr** [comment]
I enabled Code Coverage in Xcode and ran our unit tests to review what is or isn't covered. I don't think we need to aim for 100% coverage, but the coverage results could help us at least spot gaps in what is being tested. Here's a look at our coverage for the view models and helpers specifically for order creation:

* NewOrderViewModel: 89.9%
* Synchronizer:
   * OrderSynchronizer: 100%
   * RemoteOrderSynchronizer: 99.1%
   * NewOrderInitialStatusResolver: 100%
   * ShippingInputTransformer: 100%
   * FeesInputTransformer: 100%
   * ProductInputTransformer: 98.7%
   * OrderTotalsCalculator: 100%
* FlowCoordinator:
   * AddOrderCoordinator: 60.6%
   * BottomSheetOrderType: 93.8%
* PaymentSection:
   * ShippingLineDetailsViewModel: 100%
   * FeeLineDetailsViewModel: 91.5%
* ProductsSection:
   * AddProductToOrderViewModel: 82%
   * AddProductVariationToOrderViewModel: 77.3%
   * ProductRowViewModel: 94.2%
   * ProductInOrderViewModel: 44.4%
* CustomerSection:
   * CreateOrderAddressFormViewModel: 59.4%
* CustomerNoteSection:
   * NewOrderCustomerNoteViewModel: 61.5%

After looking through the coverage results, here are some suggestions for areas we could add coverage for:

* NewOrderViewModel:
- [ ] Adding a product variation to an order updates the view model (to complement existing tests for adding products to an order)
- [ ] Decreasing an order item quantity when the quantity is 1 selects the order item.
- [ ] `createSelectedProductViewModel` returns the expected `ProductInOrderViewModel`.
- [ ] `trackCustomerDetailsAdded` provides the correct value for the property `has_different_shipping_details` when only a billing address is entered.
* AddProductToOrderViewModel:
- [ ] `getVariationsViewModel` returns the expected `AddProductVariationToOrderViewModel` for variable products.
- [ ] `selectProduct` calls the provided `onProductSelected` closure (already integrated in a NewOrderViewModel test, but could be tested separately).
* AddProductVariationToOrderViewModel:
- [ ] `selectVariation` calls the provided `onVariationSelected` closure (would be integrated in a NewOrderViewModel test that covers adding a product variation to an order, but could be tested separately).
* ProductRowViewModel:
- [ ] `productAccessibilityLabel` combines the provided labels as expected.
* ProductInOrderViewModel:
- [ ] There is a convenience init that has no coverage but also doesn't seem to be used, which could be removed.
* CreateOrderAddressFormViewModel:
- [ ] Most of the computed properties have no coverage; a test could check that they have the expected values when the view model is initialized.
* NewOrderCustomerNoteViewModel:
- [ ] `updateNote` replaces the original note with the new note content.
- [ ] `userDidCancelFlow` retains the original note content.

We have a separate issue for UI testing so I didn't consider that in this review.

**Comment by rachelmcr** [comment]
Following up from the discussion on these coverage results (internal ref: p91TBi-7WN-p2), here are the results for the Networking and Yosemite layers. (The comment above only includes results from the UI layer.)

The coverage gaps are mostly for areas like errors or unexpected scenarios, or for parts of the code that pre-date the order creation project, but there are still areas for improvement:

**Networking**

- OrdersRemote: 97.1%
- Models:
   - Order: 98.7%
   - OrderFeeLine: 100%
   - OrderFeeTaxStatus: 50%
      - [ ] No coverage for `.none` tax status or status `description` property.
   - OrderItem: 95.9%
   - OrderItemAttribute: 100%
   - OrderItemTax: 68.2%
      - [ ] No coverage for `encode` method.
   - OrderNote: 100%
   - OrderStatus: 88.9%
   - OrderStatusEnum: 100%
   - OrderTaxLine: 100%
- Mappers:
   - OrderMapper: 100%
   - OrderNoteMapper: 100%
   - OrderNotesMapper: 100%

**Yosemite**

- OrderFactory: 94.7%
   - [ ] No coverage for `deletedShippingLine` property.
- OrderStore: 95.8%
- OrderNoteStore: 75.6%
   - [ ] No coverage for `addOrderNote` method.
- OrderStatusStore: 96.3%

**Comment by rachelmcr** [comment]
This review is complete (aside from any followup based on the internal discussion). I've opened separate issues for the suggested improvements, so I'll go ahead and close this issue now.
