### ISSUE TITLE
[Mobile Payments] Handle "statement_descriptor":null in Stripe extension account REST API endpoint response

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#6243]
Further change from https://github.com/woocommerce/woocommerce-ios/pull/6041 where we handled empty string. It is possible for the Stripe extension REST API endpoint for account to now return null for the statement_descriptor (as of extension version 6.2.0)

See https://github.com/woocommerce/woocommerce-ios/pull/6224#issuecomment-1044313938

Props @koke for catching this

**Comment by oguzkocer** [comment]
It looks like the milestone for this one was bumped a few times. I'm going to remove it now instead of bumping it.

**Comment by toupper** [comment]
Closing this issue as it is tested and merged in https://github.com/woocommerce/woocommerce-ios/pull/6224
