### ISSUE TITLE
Scrolling on no search results screen causes screen to "shake"

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#6302]
**Describe the bug**
When on the no search results screen (tested it's the same behavior for orders, products, coupons screens), attempts to scroll on the screen will cause screen to shake (apologies if I'm using the incorrect term)

**To Reproduce**
1. Go to either Orders/Products/Coupons screen
2. Tap on the search icon
3. Search for a random term that will not return a result
4. No search results screen is displayed
5. Attempt to scroll on the screen
6. See that screen is shaking

**Screenshots**

https://user-images.githubusercontent.com/17252150/155482372-0e0ea5bb-41fa-4db5-9d4b-349fc0cd60a6.MP4

**Expected behavior**
The no search results screen shouldn't shake

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13 mini
- iOS version: 15.3.1
- WooCommerce iOS version: 8.6 (current beta) and 8.5 (current production)

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by rachelmcr** [comment]
I tested this with an iPhone 12 mini, iOS 18 beta, WooCommerce iOS 20.0 beta and can no longer reproduce the issue as described. I'll close this as resolved but please reopen if it's still an issue!
