### ISSUE TITLE
Order Creation: Fees screen misbehaving when order is created

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#6306]
**Steps to Reproduce:**

1. Enter a shipping line and tap Done.
2. Notice a request is made to create the new order remotely.
3. Tap on "Add Fees" and enter a fee amount. While on that screen, the first response is received and the entered data disappears.

https://user-images.githubusercontent.com/8658164/155539212-434e5b8b-c294-4618-9d56-7c691e7454c7.mp4

The UI also becomes unresponsive after that. I'm not entirely sure but I'm guessing it's related to how we handle the view models when the order changes.

**Comment by shiki** [comment]
@ealeksandrov Are you still working on this? Or would you like to unassign yourself for now? 

Also, considering that this bug can lead to an unresponsive UI, do you think we should increase the priority? It's currently low. cc @Ecarrion @rachelmcr

**Comment by Ecarrion** [comment]
@shiki  I just tested this again, and steps have changed a little since we now block input while creating the first local(shipping or fee) line.

This still happens after following the following steps.

- Add a new shipping line
- Modify the shipping line
- Before the previous request ends open the "add fee" screen
- See the keyboard being unresponsive.

The whole UI is not unresponsive tho, user can still cancel the "Add Fee" screen and open it again. I think of this as more of an edge case for faster stores, but I can see how slower ones could experience it more frecuently.

**Comment by shiki** [comment]
Got it. I'll place it as Medium instead of Low then. 😁

**Comment by ealeksandrov** [comment]
I have a draft with a possible fix that worked unreliably. Will revisit it on this week!

**Comment by Ecarrion** [comment]
Tested this again and it doesn't seem to happen on the latest version (20.3)
