### ISSUE TITLE
Order details: Show tax line(s) even if $0.00

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-ios#633]
**Describe the bug**
The tax lines in order details and on the item lines should be shown even if $0.00. 

**To Reproduce**
1. View an order with no tax on it.
2. See $0.00 line is not present on the totals section.
3. Also check the line items on the fulfillment screen to see $0.00 tax on each line missing.

**Expected behavior**
Tax amounts, even if $0.00, should show according to the designs.

**Mobile Environment**
Please include:
- Device: iPhone X
- iOS version: 12.1.2
- WooCommerce iOS version: 1.0

cc: @kyleaparker

**Comment by mindgraffiti** [comment]
Okay, I figured out where the confusion came from. I left myself a [misleading comment](https://github.com/woocommerce/woocommerce-ios/pull/569/commits/868f0acce55fc752529f524956b0d10919ad4fe6#diff-30d378c3c76d138343080e8df335a2fdR48) about taxes and then proceeded to "fix" the perceived bug. Thanks for catching this @astralbodies. Restoring zero-amount taxes to display shortly!
