### ISSUE TITLE
Cannot refresh lists when an empty view is present

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#6356]
# Description
For most of the lists I've found in the app: Orders, Products, Reviews, Plugins, Coupons - when an empty view is present, it's not possible to pull down the view to trigger refreshing data. For Orders and Products, this is more problematic because there's no other way to fetch data other than killing and relaunching the app.

# Steps to reproduce
- Login to the app with a valid account
- Turn off the internet connection
- Switch to the Orders or Products tab. Without internet connection, no data can be fetched, so empty views will be presented shortly afterward.
- Turn on the internet connection. Notice that there's no way to reload order and product lists. 

# Expectation
We should be able to pull down to refresh the lists even with the empty views in place.

**Comment by rachelmcr** [comment]
Noting that @jostnes raised this in beta testing, after creating a new order in the app on a store with no previous orders:

> There is no pull to refresh on an Empty Orders screen, not sure how long before it gets updated with the first order (I waited ~15 seconds before killing the app) or if it can without exiting/killing the app

Internal ref: p5T066-3a4-p2#comment-12074

**Comment by itsmeichigo** [comment]
Since we've migrated all empty views to [`GhostableViewController`](https://github.com/woocommerce/woocommerce-ios/blob/trunk/WooCommerce/Classes/ViewRelated/ReusableViews/GhostableViewController.swift), we should update this controller to enable pulling to refresh.

**Comment by joshheald** [comment]
Prioritization:
Severity – Medium: bug with a workaround
Impact – Low: estimated 0-5% of users.
Rationale: because most people will add products or have an order before they use the app, and most people will have a working internet connection when they first open the products tab.
= low

**Comment by selanthiraiyan** [comment]
Breakdown
- [ ] Add pull to refresh ability to `EmptyStateViewController`. - https://github.com/woocommerce/woocommerce-ios/pull/7010
- [ ] Add pull to refresh to empty state view in `OrderListViewController`. - https://github.com/woocommerce/woocommerce-ios/pull/7023
- [ ] Add pull to refresh to empty state view in `ProductsViewController`.
