### ISSUE TITLE
Inform user about automatically send receipts 

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-ios#6358]
Hide "Send receipt" and display "A receipt has been emailed to [test@test.com](mailto:test@test.com)" when billingEmail is not empty.

This is the current look of the screen.
<img src="https://user-images.githubusercontent.com/2261188/156298631-fd0caaa1-54b0-46c3-a26d-a7c5ac255e27.jpg" width="150px" />

These are the designs ([figma](https://www.figma.com/file/vaw3DvewbUwuQnPXpdNGGH/Orders---Card-Present-Payments?node-id=2801%3A234067))
<img src="https://user-images.githubusercontent.com/2261188/156503870-9956ff6b-5e6b-4371-96bf-4e33194a86fa.png" width="700px"/>

**Comment by staskus** [comment]
@malinajirka This is two years old, but I assume it is likely a good and quick solution for success/failure receipts on iOS.

- When billingEmail is not empty, hide "Send receipt" and display "A receipt has been emailed to [test@test.com](mailto:test@test.com)"
- When billingEmail is empty, show "Send receipt" and allow add customer details to send the receipt

**Comment by malinajirka** [comment]
Yeah, I agree @staskus. Btw this task is implemented on Android. There is a chance this is implemented on iOS as well, we just forgot to close this issue.

**Comment by staskus** [comment]
@malinajirka yes, I tested Android and it works as described here. I haven't seen it implemented on iOS though.

**Comment by malinajirka** [comment]
I see, in that case I think it'd be a good improvement that is worth adding to our backlog - if it makes sense to include it as part of the TTP project, go for it of course. Thanks!
