### ISSUE TITLE
"UpSell" In Person Payments on Order Detail screen

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-ios#6380]
It seems there is an inconsistency between Android and iOS. 

iOS checks if hasCardPresentEligiblePaymentGatewayAccount ([here](https://github.com/woocommerce/woocommerce-ios/blob/734d240d6046011143c003c9ee671c99d341cc6a/WooCommerce/Classes/ViewModels/Order%20Details/OrderDetailsDataSource.swift#L47-L54)) before showing "Collect Payment" button on the Order Detail screen. ~This means that unless the user has entered In Person Payments in app settings they won't see the "Collect Payment" button.~ (Update: As Cesar [pointed out here](https://github.com/woocommerce/woocommerce-ios/issues/6380#issuecomment-1061103155), the user doesn't need to enter the settings in order to see the collect payment button)

The Android app instead shows the "Collect Payment" button no matter Store's eligibility (kind of an upsell) and redirects the user to the Onboarding flow. You can look at the videos in [this comment](https://github.com/woocommerce/woomobile-private/issues/187#issuecomment-1060144385) which show the behavior.

cc @ctarda Might be worth planning this as it might not be an easy fix, I'm not sure. Wdyt?

**Comment by ctarda** [comment]
> This means that unless the user has entered In Person Payments in app settings they won't see the "Collect Payment" button.

I don't think that's completely accurate? I can see the Collect Payment button on orders even if I don't go to Settings. 

Anyway, in theory, if we removed that check and presented the button anyway, the onboarding should get triggered. I will run a quick test

**Comment by ctarda** [comment]
Well, it doesn't. If we remove the check for hasCardPresentEligiblePaymentGatewayAccount, the onboarding is not triggered, and the app fails silently, logging an error on the console.

I am thinking this could be a good onboarding project into payments for the new folks joining the team soon. If it is more urgent, we can figure out a way to implement it right away.

@malinajirka please let me know what you think

**Comment by malinajirka** [comment]
> I don't think that's completely accurate? I can see the Collect Payment button on orders even if I don't go to Settings.

Ahh, you are right. I based it on a discussion on Slack. I should have tested it. 

> I am thinking this could be a good onboarding project into payments for the new folks joining the team soon. If it is more urgent, we can figure out a way to implement it right away.

Sounds good to me! The only case in which it might be better to implement it sooner is if we wanted to implemented [this](https://github.com/woocommerce/woomobile-private/issues/187) sooner as these two seem related. But I personally think it's not urgent. Wdyt?

**Comment by joshheald** [comment]
This is resolved in 9.6 with the completion of the Ducks in a Row project
