### ISSUE TITLE
[Mobile Payments] App gets stuck in Remove Card screen after retrying payment

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#6392]
**Describe the bug**

If a payment fails and the customer hasn't removed the card from the reader before attempting the payment again, the app will stay stuck in the "Remove card" screen.

**To Reproduce**

1. From the orders list, tap `+` to collect a simple payment
2. Add a test amount that would cause the payment to fail (e.g. 12.05)
3. Attempt to collect payment with card. Connect to the M2 reader if needed.
4. When prompted, insert (not tap or swipe) the card. **Do not remove the card yet**. The payment should be declined.
5. Tap "Try again" to attempt the payment a second time.
6. The app shows a "Remove card" modal. Removing the card has no effect.

**Comment by jaclync** [comment]
I can still reproduce this issue in the latest `trunk`, maybe it's from one of the latest changes 🤔 taking on this bug!

**Comment by jaclync** [comment]
And then after stepping through some breakpoints, I suddenly can't reproduce this bug anymore after a few tries with Stripe M2 reader 😅 @koke would you like to close this issue if this is also fixed on your end?

**Comment by koke** [comment]
Tested again with `trunk` and I couldn't reproduce the issue 🎉
