### ISSUE TITLE
Discrepancy when closing an edited order on edit order screen

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#6449]
**Describe the bug**
The behavior when a merchant closes an edited order using the `Close` button vs swipe down to close is currently different. Using the `Close` button, the merchant will exit the screen without any warning. When swiping down to close, there is a warning asking merchant if they are sure to discard the changes.

**To Reproduce**
1. Go to orders screen
2. Click on an existing order
3. Scroll down to Shipping Details and update shipping details
4. Click `Close` on top left of the screen to close screen - No warning
5. Repeat step 2 and 3 and swipe down to close the screen - There is a warning asking if sure to discard changes

**Screenshots**

https://user-images.githubusercontent.com/17252150/158780999-f66838e7-8338-4bb1-b31e-9fe228eb55f4.MP4

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13
- iOS version: 15.3.1
- WooCommerce iOS version: 8.7.0.2 and 8.6

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by rachelmcr** [comment]
@Ecarrion @ealeksandrov Do you know if this discrepancy is intentional? I'm not sure if it's only on the swipe action because we think the "Close" action is more deliberate and we only want to protect against cases where someone accidentally swipes the modal closed, or if we should ideally have it in both places.

**Comment by Ecarrion** [comment]
> it's only on the swipe action because we think the "Close" action is more deliberate and we only want to protect against cases where someone accidentally swipes the modal closed,

Hi @rachelmcr & @jostnes, is exactly that.

**Comment by rachelmcr** [comment]
Thanks for confirming! I'll go ahead and close this issue, since it's working as expected, but it seems like this would be a nice enhancement for the customer details modal in order creation, too. I'll open an enhancement issue for that.
