### ISSUE TITLE
Order Creation: Add "discard changes" prompt to customer details screen

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#6454]
Order editing includes a "discard changes" prompt when you swipe to close the customer details modal on an existing order (see https://github.com/woocommerce/woocommerce-ios/issues/6449). This protects against losing data you've entered if you accidentally swipe to close the modal view.

I think this would be a nice enhancement to the customer details modal in order creation, too. It would be frustrating to enter data there and then lose it if you accidentally swipe it closed while you navigate around the form.

**Comment by rachelmcr** [comment]
A couple notes about this:

* The existing "discard changes" prompt (as seen in order editing) is part of `EditOrderAddressHostingController`. This prompt isn't available in order creation because we're using the SwiftUI view `EditOrderAddressForm` directly.
* I have seen some examples using the iOS 15+ modifier `.interactiveDismissDisabled()` to either just block the swipe gesture or to add a prompt like this in SwiftUI directly, but so far haven't come up with an approach that will work with SwiftUI for the swipe gesture in iOS <15.

We may be able to add this prompt with a `UIHostingController` wrapped in a `UIViewControllerRepresentable`, but even if everything works that way (including some challenges I'm seeing getting the navigation bar to work as expected) the complexity it adds doesn't seem worth it for a small enhancement like this.

@Ecarrion @ealeksandrov Do you have ideas about other ways to implement this, or opinions about whether it's worth wrapping the view twice like that to get this functionality?

**Comment by Ecarrion** [comment]
Hi @rachelmcr,

> We may be able to add this prompt with a UIHostingController wrapped in a UIViewControllerRepresentable

We could try building a generic wrapper(If this works properly) because I see ourselves needed from this pattern a lot of the future.

> Do you have ideas about other ways to implement this, or opinions about whether it's worth wrapping the view twice like that to get this functionality?

Thinking about the initial problem: "Avoiding the user to lose data" We could make the `CustomerDetails screen` cover the whole screen with the `.fullScreenCover` modifier, forcing the user to tap close to dismiss the screen.

https://user-images.githubusercontent.com/562080/160206672-ae23160a-8f2e-4f6e-8ccf-b8ea48e6e161.mov

**Comment by rachelmcr** [comment]
Thank you for that perspective, @Ecarrion! After a bit more work on this I've come up with a working (generic) wrapper in #6534, so if that looks good I think we'll be able to reuse this for other SwiftUI modal views as long as we need it. 🎉
