### ISSUE TITLE
[Mobile Payments] Refund UI: require charge to be fetched before `Issue Refund` is made available

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#6471]
If there is a charge available to fetch, we need to fetch it before refunds are allowed. The charge contains key information about how to refund the purchase, in particular for 🇨🇦, whether it was an interac payment or not.

Interac payments should be refunded using a client-side refund flow, onto the original payment card. The charge is used to show the `brand` and `last4` to help identify the original payment card, and also is required by Stripe to create `RefundParameters`.

This work will update the Next button on the Issue Refund screen to be a `FancyAnimatedButton`, which contains an activity spinner (as used on the Switch Store screen). The spinner will continue while the charge is being fetched, and only allow the merchant to continue to the Refund confirmation screen once the charge has been fetched.
![refund-screen](https://user-images.githubusercontent.com/2472348/159281675-48249708-3890-4bba-8316-ad189d57f75d.jpg)

**Comment by joshheald** [comment]
@woocommerce/mobile-designers Please could you let me know what you think of this change? There's an extra fetch which we currently do on this screen, for WCPay payments only, and we need the merchant to wait for it before moving ahead with the refund.

**Comment by ghost** [comment]
That interaction sounds good thanks @joshheald
