### ISSUE TITLE
Order Creation: Add UI test for creating an order

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#6524]
If there's time before release let's add a UI test for order creation. We can focus on a functional UI test (the ability to navigate through the UI to create an order) rather than data verification. Depending on time, we can make the test more or less detailed:

1. Create an empty order.
2. Create an order with a product and customer details.
3. Create an order with a product, shipping, fee, customer details, and a customer note.

Depending on time we can also go into more less depth with assertions:

1. Only assert that navigation from screen to screen works (using the assertions built into the screen objects) through the entire order creation flow.
2. As things are added to the order, assert that the New Order screen UI updates as expected.

### Progress

Create a new order:

- [x]  With a selected order status
- [x]  With a product
- [x]  With customer details
- [x]  With shipping
- [x]  With a fee
- [x]  With a customer note

**Comment by rachelmcr** [comment]
@thehenrybyrd I've assigned you to this issue since you're planning to continue work on this UI test next sprint, to add customer details.

Once that's done, the test will cover all of the Milestone 1 features. It won't yet cover the Milestone 2 features: shipping, fees, and customer note. Adding that coverage will become more important if our upcoming work on Order Editing touches on those features in a way that risks changing the UI behavior. (For example, if we reuse those views with changes for the editing flows.) In that case, we can consider adding that coverage before making significant UI changes for Order Editing.

**Comment by thehenrybyrd** [comment]
I've finished up adding the customer details step to this test, in https://github.com/woocommerce/woocommerce-ios/pull/6814.

A couple things to think about for the future, coming out of conversations in that PR:
1. What pieces of documentation do you find most useful as developers?
2. Do we want to assert that data is displayed on the Order Details screen after the order is created?

I think the answer to #2 depends somewhat on current unit testing around the Order Details screen, but checking the UI there for a few items may be useful here.

**Comment by rachelmcr** [comment]
Thanks @thehenrybyrd! I'll remove your assignment from this issue, and we'll keep it open to track the remaining proposed parts of the UI test.

> Do we want to assert that data is displayed on the Order Details screen after the order is created?

My understanding is that we already cover this in the existing `testOrdersScreenLoads()` test, with the data-related assertions for the order detail screen in `verifySingleOrder(order: orders[0])`. Are there assertions that aren't covered in that test that should be checked in this one?
