### ISSUE TITLE
Unit Tests: `test_sale_price_description_when_all_products_have_same_price()` fails Locally in Trunk

### ISSUE THREAD

**Issue by thehenrybyrd** [woocommerce/woocommerce-ios#6533]
**Describe the bug**
In Trunk, Locally, `test_sale_price_description_when_all_products_have_same_price()` fails when `BulkUpdateViewModelTests` is run as a group (or WooCommerceTests as a whole is run).
It does not fail when run via Circle CI or BuildKite.
It does not fail when run by itself.

**To Reproduce**
1. Open Xcode on branch Trunk.
2. Open `BulkUpdateViewModelTests` and run the whole class of tests.
3. Note that `test_sale_price_description_when_all_products_have_same_price()` fails in  ` XCTAssertEqual(regularPriceViewModel.detailText, "$1.00")` with error `"XCTAssertEqual failed: ("£1,00") is not equal to ("$1.00")"`
4. Run `test_sale_price_description_when_all_products_have_same_price()` by itself, and note that it passes.

**Troubleshooting**
- Commented out other tests in the file, then un-commented one by one.
- Test passes when all other tests are commented out (leaving the private extension at the end un-commented).
- Test starts failing when:
  - `test_sale_price_description_when_all_products_have_no_price()`
  or
  - `test_number_of_sections_and_title_when_in_synch_state()`
  are active.

- Test still passes if `test_sale_price_description_when_all_products_have_no_price()` *and*  lines 136-138 are commented out:
```  
waitUntil {
            viewModel.syncState.sections()?.isNotEmpty ?? false
        } 
```
- Also passes if the `waitUntil` section of both `test_sale_price_description_when_all_products_have_no_price()` and `test_number_of_sections_and_title_when_in_synch_state()` are commented out (136-138 *and* 231-233).

So, somehow, although the product is set up with $USD by default, when the syncState from the previous test is allowed to run, it ends up as £.
By adding `print(currencySettings.currencyCode)` on lines 76 and 84 of `BulkUpdateViewModel` we can confirm that's what's happening, but it is very difficult to tell why.

**Comment by thehenrybyrd** [comment]
This only occurs for me locally, and I wasn't able to figure out why after significant time troubleshooting. 
I'm leaving this issue here for posterity, in case someone else runs into it later, but will close it as it's not something to be fixed and is not effecting CI.

**Comment by selanthiraiyan** [comment]
Reopening this in order to take a look at the root cause and fix it.
