### ISSUE TITLE
Order Details: Shipping method title/Local Pickup Plus compatibility

### ISSUE THREAD

**Issue by IanMisnerThough** [woocommerce/woocommerce-ios#655]
We've received a user report that shipping details are "inaccurate" while using [Local Pickup Plus](https://woocommerce.com/products/local-pickup-plus). 

The order details provide a "Shipping address" and show no indication that the order is to be picked up. 

Ideally, this area would display the pickup location along with indication that the order is intended for pickup. Here's [how it's handled in wp-admin by Local Pickup Plus](https://github.com/woocommerce/woocommerce-shipping-local-pickup-plus/blob/master/templates/orders/order-pickup-details.php). 

Alternatively, displaying the shipping method title in the shipping details would provide the minimum amount of useful information. 

[Related Android issue
](https://github.com/woocommerce/woocommerce-android/issues/741)

**Comment by zwiesman31** [comment]
Related ticket: 1808492-zen

**Comment by mindgraffiti** [comment]
Update: Order Details - shipping method was recently added as a feature: https://github.com/woocommerce/woocommerce-ios/issues/1362

This ticket needs prioritized and reviewed for compatibility with Local Pickup Plus. @pmusolino please verify this one?

**Comment by pmusolino** [comment]
I checked, and at the moment we show that the order will be retired from the client, but we don't show other details (like the pickup location).

The description of the shipping method is in Italian, with the website in English, and I wasn't able to change it (maybe cache since I changed the website language 10 minutes before).
![Simulator Screen Shot - iPhone 11 Pro - 2020-01-10 at 11 46 41](https://user-images.githubusercontent.com/495617/72147574-1b5b3400-339f-11ea-8390-0240abff0ee8.png)

**Comment by mindgraffiti** [comment]
@kyleaparker @astralbodies can you prioritize this one? @pmusolino confirmed that this task is still relevant and needed.

Not sure where in Monday.com this should be added (next sprint? roadmap? etc.)

**Comment by joxmar** [comment]
I would love to see this happen, We are currently using the app but then having to open the email on a separate window just to figure out the location where it will be picked up.

**Comment by shiki** [comment]
The related Android issue (https://github.com/woocommerce/woocommerce-android/issues/741) has been closed with this reason: 

> Closing this ticket as a new one will be created when the designs are finished and approved, and the project is ready to be developed on. Added to feature backlog.
