### ISSUE TITLE
Order Details: Images for Bundles do not load until after navigating to Product details

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#6560]
**Describe the bug**
When browsing an order that contains a Product Bundle, the Product Images are not loading. 

**To Reproduce**
1. Create a Product Bundle in wp-admin using the [Product Bundles Extension](https://woocommerce.com/products/product-bundles/). 
2. Assign an image to the Product Bundle. Make sure the Products in the Bundle also have images assigned
3. Complete an order containing the Product Bundle
4. Navigate to Orders > The order containing the Product Bundle. 
5. The images are not loading.
6. Navigate to Products > The Bundled Product.
7. Navigate back to Orders > the order containing the Product Bundle. Images are loading now.

**Screenshots**
First, navigate to the order:

<img src="https://user-images.githubusercontent.com/2722505/161591960-85efeef0-5366-4ba9-95ed-cd73feee8ea9.PNG" width="350"/>

After navigating to the Product details, and then back to the order:

<img src="https://user-images.githubusercontent.com/2722505/161592060-f1eb0550-b279-4ae9-8d6d-40932b436034.jpeg" width="350"/>

**Expected behavior**
Product images should load without having to navigate to the Product Details screen

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13 Pro
- iOS version: 15.4.1
- WooCommerce iOS version: 8.8.0.0

</details>

**Comment by ctarda** [comment]
This might be related to #3733

**Comment by Ecarrion** [comment]
Just tested this and doesn't seem to be a problem anymore.
<img width="455" alt="Screenshot 2023-01-16 at 5 33 30 PM" src="https://user-images.githubusercontent.com/562080/212774995-92c7d136-2a81-41d8-a772-699916c4ae3d.png">
