### ISSUE TITLE
Handling potential bug related to receipt email

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-ios#6570]
Context - pdfdoF-Cx-p2

We should not set an email only if we use WCPay 4.0.0 or higher and should set it otherwise

**Comment by kidinov** [comment]
Context for external readers - this issue fixes a bug mentioned https://github.com/woocommerce/woocommerce-android/pull/6123#pullrequestreview-928505189.

**Comment by ctarda** [comment]
I think we can close this, now that #6585 is merged
