### ISSUE TITLE
Order Creation: Add offline banner to new order screen

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#6587]
From @joashrajin on the CFT:

> It might be a good idea to add a message related to an unstable internet connection should the connection be cut off. That should help prevent people from blaming the app or Woo Site for being slow when it is actually their internet.

Internal ref: p91TBi-7ZR-p2#comment-9291

**Comment by shiki** [comment]
@rachelmcr Do you think this is more like an _idea_ that we should prioritize separately and not a maintenance issue? I'm not really sure if this is something we should tackle right now. But I wanna keep it in mind for the future.

**Comment by rachelmcr** [comment]
Definitely more like an enhancement idea than a maintenance issue.

We could also prioritize this based on how often merchants run into connection-related sync errors during order creation. (Which we'll know more about once https://github.com/woocommerce/woocommerce-ios/pull/6829 has been in production for a while.)

**Comment by shiki** [comment]
Thanks! I added a priority named “Someday“ so it's still on the board. I hope that clarifies that we shouldn't be working on this yet. ^_^x

**Comment by shiki** [comment]
I'm gonna close this for now since the team's strategies have changed.
