### ISSUE TITLE
Dynamic Type Not Supported On Store Tab

### ISSUE THREAD

**Issue by JB184351** [woocommerce/woocommerce-ios#6597]
Dynamic Type for My Store Page are not supported

![image](https://user-images.githubusercontent.com/36495451/162244565-1fa8b12b-cb8c-40a8-907d-a052b90fd12c.png)

**Comment by rachelmcr** [comment]
Thanks for the report! Most of this screen supports Dynamic Type, although we have a couple open issues about specific parts of the screen that don't:

* https://github.com/woocommerce/woocommerce-ios/issues/896
* https://github.com/woocommerce/woocommerce-ios/issues/894

Are there other issues besides those two that you've observed?

**Comment by rachelmcr** [comment]
I'll go ahead and close this since I think the specific issues on this screen are being tracked separately, but please let me know if I'm mistaken about that!
