### ISSUE TITLE
[Mobile Payments] Update minimum WCPay version once all the required API changes are released

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#6601]
After @joshheald's API support for Interac refunds in WCPay is merged and shipped, we will update the minimum WCPay version ideally only for CA merchants.

https://github.com/Automattic/woocommerce-payments/pull/4041
1864-gh-Automattic/woocommerce-payments-server

**Comment by jaclync** [comment]
let's address this when Josh is back! https://github.com/woocommerce/woocommerce-ios/pull/6657#issuecomment-1104848110

> @joshheald One question that came up to me today: do we also want to remove the temporary manual refund logic?

https://github.com/woocommerce/woocommerce-ios/blob/a0b20cf1fc90f0ced98bab42f20b5ca116d95b65/WooCommerce/Classes/ViewRelated/Orders/Order%20Details/Issue%20Refunds/RefundConfirmationViewModel.swift#L76-L85

**Comment by joshheald** [comment]
Moved remaining question to new issue
