### ISSUE TITLE
Order Creation: No on click feedback while selecting `Create order`

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-ios#6613]
### Issue

When selecting `Create order` or `Simple payment` from the `+` sign on the Orders list, no visual feedback confirms what's selected.

### Reproduce

1. Click on `+` on the Orders list
2. Long click on any item
3. Assert that there's no visual feedback for selection

**Comment by joshheald** [comment]
N.B. this bug also affects the BottomSheet shown from the `+` button on Products, but it doesn't affect the one from `Products > {downloadable product} > Downloadable files > Add File`
