### ISSUE TITLE
Order Creation: Customer details fields don't have hints (placeholders)

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-ios#6615]
### Description

- [x] ~Fields in `Customer Details` edit are edited from the right with the prompt always aligned to the right.~ Duplicate: #6018 
- [x] Fields don't have grey hints as on designs.
- [ ] ~I think it'd be great if `return` button on the keyboard could move a user to the next field instead of closing the keyboard~ Duplicate: #6580 

This all was a little confusing and before understanding what's the design here, I was tapping on e.g. `First name` label trying to start editing.

### iOS

https://user-images.githubusercontent.com/5845095/162749285-f6fb3786-d829-4469-9235-341545b303b0.mov

#### iOS Design
<img width="271" alt="image" src="https://user-images.githubusercontent.com/5845095/162749679-d917d252-83e5-4165-a5ed-da555f1f9ccc.png">

### Android

https://user-images.githubusercontent.com/5845095/162749382-47c59a67-b42b-4570-bb24-c4e26f35a92b.mov

**Comment by rachelmcr** [comment]
Thanks for reporting these! A couple of them are captured in other open issues:

> Fields in Customer Details edit are edited from the right with the prompt always aligned to the right.

This was also reported in https://github.com/woocommerce/woocommerce-ios/issues/6018 and should be fixed when https://github.com/woocommerce/woocommerce-ios/pull/6625 is merged.

> I think it'd be great if return button on the keyboard could move a user to the next field instead of closing the keyboard

Definitely! We are tracking that in https://github.com/woocommerce/woocommerce-ios/issues/6580.

**Comment by wzieba** [comment]
Awesome, thanks!

WDYT about "Fields don't have grey hints as on designs."? Is it something that we would like to add?

**Comment by rachelmcr** [comment]
Yeah, I think since it was part of the designs it's worth adding. I'll update this issue title to reflect that pending improvement!
