### ISSUE TITLE
Order Creation: Use decimal-based keyboard for decimal fields

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-ios#6616]
### Description

While adding the amount for shipping, a user can see the keyboard with symbols that are not accepted by input field.

### Proposal

Maybe we can use a keyboard with numbers only?

### Current behaviour

https://user-images.githubusercontent.com/5845095/162750633-38cd2578-8c03-4b8c-af79-11ccb820f81f.mov

### Android

<img width="300" alt="image" src="https://user-images.githubusercontent.com/5845095/162750710-de96a434-ceea-43c2-9743-1483d570c0a3.png">

**Comment by rachelmcr** [comment]
Related, from https://github.com/woocommerce/woocommerce-ios/pull/6382:

> iOS doesn't provide a number pad with negative input option. The current solution is to use `.numbersAndPunctuation` keyboard (see screenshots below). We can improve it by adding "+/-" button in `inputAccessoryView` above the numpad. It'll require a change in our nested UIKit component (`BindableTextfield`).

**Comment by shiki** [comment]
I will close this since we're not fixing this! At least not in the near future.
