### ISSUE TITLE
Order Creation: Labels capital letters differ from designs

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-ios#6617]
### Description
Labels for `+ Add (...)` labels have a start with every word with a capital letter. 

### Screenshots

| iOS | Android | Designs |
| --- | --- | --- |
| <img width="620" alt="Screenshot 2022-04-11 at 15 36 58" src="https://user-images.githubusercontent.com/5845095/162751485-81620ab5-e7c6-4f5a-9e43-d5900f1fb242.png"> | <img width="573" alt="image" src="https://user-images.githubusercontent.com/5845095/162751682-12a66fc8-3acc-4f86-a409-9b6dc6deffad.png"> | <img width="360" alt="image" src="https://user-images.githubusercontent.com/5845095/162751803-845c284e-6fd5-4eaa-80a9-1495fe69a453.png"> |

**Comment by rachelmcr** [comment]
Thanks for the report! This was an intentional change to match our iOS design guidelines:

> We generally use sentence case (first letter of the sentence is uppercase), except for all titles on iOS which use title case (every word’s first letter is uppercase). This follows the [HIG standard for buttons](https://developer.apple.com/design/human-interface-guidelines/ios/controls/buttons/).

(internal ref: P9MsLS-p-p2, p1644861614618929-slack-C02KUCFCSFP)

**Comment by wzieba** [comment]
Thanks @rachelmcr, TIL! That's interesting, I use iOS daily, and I never spotted that!
