### ISSUE TITLE
API: Account for non-integer quantities when syncing orders

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-ios#662]
**Describe the bug**
When an order contains a non-integer quantity, the app cannot sync orders.

**To Reproduce**
1. Install a plugin that allows you to use non-integer quantities or edit the data.
2. Add an order with a line item quantity of something like 1.5.
3. Try syncing orders.
4. See error similar to:

```
2019-02-05 19:37:34.167538-0600 WooCommerce[18821:393260] ⛔️ Error synchronizing orders: dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 2", intValue: 2), CodingKeys(stringValue: "line_items", intValue: nil), _JSONKey(stringValue: "Index 2", intValue: 2), CodingKeys(stringValue: "quantity", intValue: nil)], debugDescription: "Parsed JSON number <1.5> does not fit in Int.", underlyingError: nil))
```

**Screenshots**
![simulator screen shot - iphone xr - 2019-02-05 at 19 37 35](https://user-images.githubusercontent.com/373903/52315711-c5576280-297d-11e9-875b-9ecbb2e2c239.png)

**Expected behavior**
I guess I'm not sure what's expected. We could nil out the quantity and show some placeholder maybe? Not sure what to do here.

Whatever change we make lets coordinate with Android too so we're consistent. 😄 

**Mobile Environment**
Please include:
- Device: Simulator
- iOS version: 12
- WooCommerce iOS version: develop (1.2)

1758607-zen

**Comment by astralbodies** [comment]
Looks like we'll want to treat quantity as a decimal to support extensions like [Measurement Price Calculator](https://woocommerce.com/products/measurement-price-calculator/). I'll open a companion issue on Android.

**Comment by bummytime** [comment]
Just a heads up, since this update will require a attribute type change in CoreData, therefore we cannot use a lightweight migration here.

Also, ref: #125 just in case.
