### ISSUE TITLE
[Simple Payment] Incomplete Simple Payment amount is included in Stats revenue amount

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#6626]
**Describe the bug**
When a merchant starts a simple payment flow but stops after the `Take Payment` screen, the amount entered in `Take Payment` screen will be included as revenue amount on Stats charts. Because of this, the total amount on the Orders screen does not match what's displayed on Stats.

**To Reproduce**
1. Go to Orders > Tap + > Tap Simple payment
2. Enter an amount (to make it easier to see the issue, enter 100 or 10) and tap Next
3. On the next screen, close the modal – Order is canceled, not recorded on Orders screen
4. Go to stats and wait for it to refresh
5. See that it now includes the amount from the canceled order.

**Screenshots**
Number of orders: 4, on Stats: 8. Total on Orders: $1,331.25, on Stats: $1,503.25.
![stats today](https://user-images.githubusercontent.com/17252150/163085249-8103d8c9-cd2a-4928-a21a-8b4a19ad320b.PNG)

![orders today](https://user-images.githubusercontent.com/17252150/163085262-927e2f0e-856c-48f3-9548-25e7ce5b61a5.PNG)

**Expected behavior**
A canceled/incomplete simple payment order should not be counted as revenue and the amount on Stats should match the amount on Orders.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13
- iOS version: 15.3.1
- WooCommerce iOS version: v8.9 (also reproducible in current App Store build, v8.8)

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by rachelmcr** [comment]
@Ecarrion Do you have any ideas about what would cause this? I was wondering if maybe orders with the `auto-draft` status  are still counted in analytics — which I think should probably be addressed in core but we could also do some additional work in the app to remotely delete any discarded auto-draft orders.

**Comment by Ecarrion** [comment]
Hi @rachelmcr and @jostnes! I took a look at this and while I think we can mitigate it in the apps by auto-deleting draft orders, I think this primary should be fixed it on core, because:

- `auto-draft` orders created on the website are not taken into account for analytics/reports but the ones created in apps are. We should unify that behavior. Could this be because `auto-drafts` orders on web do not have a "creation date" set?

- Even if we auto-delete draft orders on the apps, there is the possibility for users to "kill" the app rather than dismiss the order, in those cases the draft order won't be deleted and the revenue stats will still be inconsistent.

Do you have any opinion here @joshbetz? 
cc @coreymckrill

**Comment by shiki** [comment]
Does this also affect Order Creation?

**Comment by rachelmcr** [comment]
> Does this also affect Order Creation?

In most cases it won't because we delete the auto-draft orders when exiting Order Creation, but as noted above there's still a possibility that users will kill the app, in which case it results in the same issue.

**Comment by joshbetz** [comment]
Are we sure the status is really `auto-draft`? It looks like in this case it is `pending`.

I suspect this might be fixed by https://github.com/woocommerce/woocommerce/pull/32571.

**Comment by Ecarrion** [comment]
> Are we sure the status is really `auto-draft`? It looks like in this case it is `pending`.

@joshbetz Yup, I duplicated the issue and made sure the status was `auto-draft`. The only difference that I found was that `auto-draft` orders created on the website do not have a `date_created_gmt` field set.

**Comment by joshbetz** [comment]
@Ecarrion I have opened a PR to exclude auto-draft orders from reports. I think we should also change the status to `cancelled` when you back out of a quick order like this.

**Comment by joshbetz** [comment]
Noting that I merged the core PR, which closed this issue. Do we want to reopen this pending the change to set statuses to `cancelled`?
