### ISSUE TITLE
Order Creation: Improve Navigation Items consistency

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#6631]
It was reported that the navigation items in the different Order Creation modals behave differently.

> If you tap to change the order status, you select the new status then click Apply at the top right

> If you tap to add customer details and choose to select a state or country, you make a selection and than tap the upper left arrow (there is no Apply button)

> If you tap to add a customer note, you enter the note then tap Done at the top right (similarly with order fees and shipping)

> If you tap to add a product, the product is added as soon as you select it

Let's speak with @woocommerce/mobile-designers in order to make such behavior more consistent!

**Comment by joe-keenan** [comment]
I completely agree, @Ecarrion! The back arrow doesn’t feel too bad to me, since it’s in a sub-menu inside a sheet, so it can afford to behave slightly differently (otherwise it would open in another sheet on top of the customer details one – which I’m open to exploring). The rest of them should definitely be brought into line with each other though!

**Comment by rachelmcr** [comment]
I just realized that this is very similar to https://github.com/woocommerce/woocommerce-ios/issues/6651, which is resolved. We now have two different kinds of navigation:

* If you select from a list (order status, product, or the state or country in customer details) you are navigated back automatically.
* If you enter data (customer note, fees, shipping) you can tap the Done button to save your changes.

I think this offers the consistency we need so I'll go ahead and close this issue, but please feel free to reopen if you think we need to adjust this further!
