### ISSUE TITLE
Order Creation: Percentage Fee Changes Automatically When Editing

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#6641]
In the Order Creation screen, after I add a percentage fee, then return to edit it, the percentage fee changes automatically (initially was 4%, then 3.9721%). Video below:

https://user-images.githubusercontent.com/266376/163326431-073e2c7c-595d-4e89-9a6b-ef3cb5a2a9e9.MP4

**Comment by rachelmcr** [comment]
This behavior with percentage-based fees is how core WooCommerce does it, so we’re matching the web behavior in the app. It should accurately calculate the fee amount based on the current order total when you add that percentage fee, and add that amount to the order. (It won’t automatically adjust the fee after that point.) If you notice any difference between how this works on the web and in the app, please reopen the issue and we'll take a look!
