### ISSUE TITLE
Order creation: Spaces not shown in Customer Detail form's input field.

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#6642]
When I add space into an input field in the Customer Details form, the space is not shown and makes me unsure whether I’ve added them or not.

https://user-images.githubusercontent.com/266376/163326697-dde27966-d3a6-4874-97d6-d7b7332809d0.MP4

**Comment by rachelmcr** [comment]
Thanks! This was also reported in https://github.com/woocommerce/woocommerce-ios/issues/6018 and should be fixed once https://github.com/woocommerce/woocommerce-ios/pull/6625 is merged.
