### ISSUE TITLE
[Mobile Payments] New Interac analytic events for Canada IPP launch

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#6655]
These events are the highest priority to be done pre-launch, so I've broken them out of this ticket to make prioritisation clearer...

## New events

Event | Properties | Trigger | PR
-- | -- | -- | --
*_card_interac_collect_payment_success | `plugin_slug`, `card_reader_model`, `country` | Tracked right after processing succeeds. | https://github.com/woocommerce/woocommerce-ios/pull/6665
*_interac_refund_success | `plugin_slug`, `card_reader_model`, `country` | Tracked when an Interac in-person refund succeeds on the client side. | https://github.com/woocommerce/woocommerce-ios/pull/6665
*_interac_refund_failed | `error`, `plugin_slug`, `card_reader_model`, `country` | Tracked when an Interac in-person refund fails on the client side. | https://github.com/woocommerce/woocommerce-ios/pull/6665
*_interac_refund_cancelled | `plugin_slug`, `card_reader_model`, `country` | Tracked when the user cancels an Interac in-person refund before it's complete.

_Originally posted by @joshheald in https://github.com/woocommerce/woocommerce-ios/issues/5984#issuecomment-1099969660_

**Comment by jaclync** [comment]
We're adding a new event for in-person refunds (ref pdfdoF-vx-p2#comment-1404):
`*_interac_refund_cancelled`

**Comment by jaclync** [comment]
Closed by https://github.com/woocommerce/woocommerce-ios/pull/6747 (the PR targeted another merged PR instead of this issue)
