### ISSUE TITLE
UI Testing: Update UI test methods to use snake case 

### ISSUE THREAD

**Issue by thehenrybyrd** [woocommerce/woocommerce-ios#6722]
@rachelmcr brought this up in https://github.com/woocommerce/woocommerce-ios/pull/6685#discussion_r856138774:

> I think we should update the other UI test methods to use snake case (rather than switch these to camel case) to match the project's [naming conventions for test methods](https://github.com/woocommerce/woocommerce-ios/blob/trunk/docs/naming-conventions.md#test-methods).

This would help us standardize our naming conventions and make them clear for future contributors.

**Comment by jostnes** [comment]
Closing this, done via https://github.com/woocommerce/woocommerce-ios/pull/7108
