### ISSUE TITLE
Tests fail on development machines set to a Region that does not use a dot as separator for large numbers

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#674]
**Describe the bug**
Unit tests fail when running on a development machine set up in a Region that does not use a `.` as separator for large numbers, like for example, Hong Kong.

So, tests will fail when running in a machine setup like this:
<img width="780" alt="screenshot 2019-02-12 at 10 52 31 am" src="https://user-images.githubusercontent.com/2722505/52609269-a85beb80-2eb7-11e9-889b-1e2444f2297f.png">

The tests failing are on `NSDecimalNumberWooTests`.

**To Reproduce**
1. In your development machine, go to System Preferences > Language and Region
2. Select Hong Kong (China) as Region
3. Go back to Xcode
4. Run the test suite (command + u to run all the tests, or just run the tests for `NSDecimalNumberWooTests`)
4. See tests fail

**Expected behavior**
Tests should run and pass, regardless of the development machine locale

**Comment by bummytime** [comment]
Thanks for catching this @ctarda !!!!!
