### ISSUE TITLE
Large numbers abbreviated as Billion might not match the user locale

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#676]
**Describe the bug**
In most countries of Western Europe, a billion equals 10^12, not 10^9.

Currently, large numbers like 1.000.000.000  (1 thousand millions) will be abbreviated as 1.0b, which for the aforementioned languages will be interpreted by users as 1.000.000.000.000 (1 million millions) instead.

**To Reproduce**
1. Generate enough sales to reach revenue of one thousand millions
2. Go to My store
3. Notice how the number is abbreviated as 1.0b

**Expected behavior**
Large numbers should be abbreviated having in mind that different countries might use different scales

**Comment by bummytime** [comment]
Looks like our numeric abbreviations are turning out to be problematic. 😏 Thanks for pointing this out @ctarda

**Comment by bummytime** [comment]
Related comment that applies here: https://github.com/woocommerce/woocommerce-ios/issues/584#issuecomment-462808329

**Comment by mindgraffiti** [comment]
Closing in favor of #584.
