### ISSUE TITLE
Large numbers in several asian languages are not broken down in powers of 1000

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#677]
**Describe the bug**
In English, and most western languages, large numbers are abbreviated in a scale of powers of 1000 (a thousand, a million, a billion...)

However in Chinese and Japanese, big numbers are broken down differently, based on tens of thousands instead of thousands.

https://resources.allsetlearning.com/chinese/grammar/Big_numbers_in_Chinese
https://www.trussel.com/jnumbers.htm

This would make abbreviations like 1.0b feel very foreign to native speakers of these languages

**Comment by bummytime** [comment]
Nice catch @ctarda! We had a pretty good hunch this was a problem and have an existing issue for it — #584. I'll close this issue but link to your comment above ☝️ in the other one.

**Comment by bummytime** [comment]
It's also worth mentioning we need to consider how changing this abbreviation logic would work given the way we formatting currency based on the WC settings. 

Example: user is physically localted in Western Europe, but their WC site is setup using US settings:

<img width="684" alt="screen shot 2019-02-12 at 9 32 55 am" src="https://user-images.githubusercontent.com/154014/52647102-b0ad2a00-2ea9-11e9-9ff5-68fecce148be.png">

How do we resolve this?
