### ISSUE TITLE
[Mobile Payments] Extract Order CPP eligibility logic from Order Details and reuse on Payment Method screen

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#6778]
Currently, we only show the `Card` Payment Method option in Simple Payments if the merchant has completed onboarding. 

With recent work, the Payment Method screen is capable of showing onboarding issues to the merchant, to help them complete or correct their store set up so they can take card payments:

- #6774 

We still check for an onboarding status `.complete` before showing the card payment row. This often results in a delay before the Card option is shown.

By extracting the logic for when an order is card-payment eligible from the Order Details screen, we can reuse it here to show the Card option whenever it's appropriate for the merchant/order, even if there are onboarding steps for them to complete.

- [x] Extract logic for when an order is card-payment eligible
- [x] Apply it to the Payment Method screen
- [x] Remove check for `.complete` onboarding status on Payment Method screen

**Comment by toupper** [comment]
Blocked as https://github.com/woocommerce/woocommerce-ios/issues/6782, pending design and behavior agreement. See also https://github.com/woocommerce/woocommerce-ios/pull/6805#issuecomment-1121349511
