### ISSUE TITLE
[Mobile Payments] Prevent flickering of the Collect Payment button on Order Details

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#6780]
The Collect Payment button on Order Details often flickers in and out as various endpoints return results, when first showing the screen.

By removing the reliance on `/payments/accounts` to determine Order CPP eligibility, and whether the button should show, we could reduce or eliminate the wait for this button to settle on whether it's displayed or not.

The [current implementation uses the following checks](https://github.com/woocommerce/woocommerce-ios/blob/a1c5e888934fd98d4a196b709f4c7eecdd2b4001/WooCommerce/Classes/ViewModels/Order%20Details/OrderDetailsDataSource.swift#L47):

```
    var isEligibleForCardPresentPayment: Bool {
        return isOrderAmountEligibleForCardPayment() &&
            isOrderCurrencyEligibleForCardPayment() &&
            isOrderStatusEligibleForCardPayment() &&
            isOrderPaymentMethodEligibleForCardPayment() &&
            hasCardPresentEligiblePaymentGatewayAccount() &&
            !orderContainsAnySubscription()
    }
```

`hasCardPresentEligiblePaymentGatewayAccount()` is the only one of those which is fetched separately, and removing it makes it much more stable in whether the button is displayed or not.

**Comment by jaclync** [comment]
@joshheald just wanted to confirm, this issue is different from the flickering in https://github.com/woocommerce/woocommerce-ios/issues/6583?

**Comment by joshheald** [comment]
> @joshheald just wanted to confirm, this issue is different from the flickering in #6583?

@jaclync Same flickering... but this issue implies a different fix.

**Comment by joshheald** [comment]
Design has been confirmed now. This button should show for any unpaid orders, because in #7003 it will change behaviour to open the payment method selection screen. The remaining eligibility checks will be applied on the payment method screen, and the onboarding flow will take care of the payment gateway account check.

For this ticket, we will remove the payment gateway account check from Order Details without otherwise changing the button behaviour
