### ISSUE TITLE
[Mobile Payments] Make Payment Methods screen reusable outside the Simple Payments flow

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#6782]
See pdfdoF-Hq-p2 for context and discussion.

![Simple Payments Payment Method Selection](https://user-images.githubusercontent.com/2472348/166963986-1159846d-cad3-44a9-bc31-c7b1b5257b7f.jpg)

This screen will be reused from Order Details and could be used anywhere else that merchants need to accept payments, not just the Simple Payments flow.

This will make Cash and Payment Link more accessible in other parts of the app, and mean we can always allow merchants to take payment in some way, even if there is an issue with Card Present Payments.

- [ ] Ensure Analytics are logged correctly relating to the payment flow in use (i.e. from Simple Payments vs from Order Details. Possibly also Order Creation, though that may not need to be differentiated from Order Details.)

**Comment by joshheald** [comment]
> Ensure Analytics are logged correctly relating to the payment flow in use (i.e. from Simple Payments vs from Order Details. Possibly also Order Creation, though that may not need to be differentiated from Order Details.)

This was identified by @kidinov on Android https://github.com/woocommerce/woocommerce-android/issues/6695. We should co-ordinate on naming the events, if we are adding any new ones.

**Comment by kidinov** [comment]
As per the following discussion pdfdoF-TT-p2:

We rename current Simple payments events to PAYMENTS_ and add property inside to reflect the flow:

* PAYMENTS_FLOW_COLLECT
* PAYMENTS_FLOW_COMPLETED
* PAYMENTS_FLOW_FAILED

And add params:

* flow -> simple_payment 
* flow -> order_payment
