### ISSUE TITLE
Quick Site Select: Misc. Tasks

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#679]
**1.** Add a fancy alert to let the user know about our new store switcher. Show the alert on app launch, once:

<img width="421" alt="screen shot 2019-02-13 at 2 01 58 pm" src="https://user-images.githubusercontent.com/3903757/52736843-dd8c3a80-2f98-11e9-86e5-cc0975ac0112.png">

**2.** For the title of the view controller in the My store tab: use the store name:

<img width="240" alt="napkin 117 02-13-19 2 12 48 pm" src="https://user-images.githubusercontent.com/154014/52740821-89ce2100-2f99-11e9-9cd1-2a3ed0f4cb3f.png">

**Comment by bummytime** [comment]
Just dropping by to offer up the android counterpart issues:
* Store name update → https://github.com/woocommerce/woocommerce-android/pull/790
* Tooltip announcement → https://github.com/woocommerce/woocommerce-android/pull/761

----

@kyleaparker Do you have an idea of what the announcement should look like? On Android it's currently:

`You can now tap to switch stores`

Obviously we are going to need something a tad different if we are opening this announcement on launch. As a reminder, WCiOS' "fancy alert" looks like this:

<img width="541" alt="screen shot 2019-02-12 at 3 27 19 pm" src="https://user-images.githubusercontent.com/154014/52669098-e6b6d200-2eda-11e9-8a3c-e390a28822dc.png">

where we have a title, body, and link. Additionally, we can also have an image or additional buttons if you would want (e.g. a button that navigates the user to settings):

<img width="272" alt="screen shot 2019-02-12 at 3 29 56 pm" src="https://user-images.githubusercontent.com/154014/52669234-27aee680-2edb-11e9-9012-b17edf04bce0.png">

:-)

**Comment by kyleaparker** [comment]
Let's follow the same design pattern as WP. For the wording I'd suggest:
 
Title: Switch between stores
Body:  You can now easily switch between stores by tapping on the selected store in Settings. 

Link Secondary: Got It
Link primary: Try It Now

**Comment by bummytime** [comment]
Announcement card issue on Android → https://github.com/woocommerce/woocommerce-android/issues/796

**Comment by ctarda** [comment]
@mindgraffiti @kyleaparker  One question about changing the title of the My Store view controller: as a side effect, that would also change the title of the leftmost item in the bottom tab bar:

![simulator screen shot - iphone x - 2019-02-14 at 14 44 09](https://user-images.githubusercontent.com/2722505/52768024-29a5b080-3067-11e9-860f-5002c3071d3d.png)

Is that ok?

**Comment by kyleaparker** [comment]
Is it possible to keep the **My Store** tab the same and only change the title up the top? The tab shouldn't change.
