### ISSUE TITLE
Order Creation: Cannot sync/create new order with empty customer email on older versions of Woo Core

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#6791]
**Describe the bug**

On older versions of Woo Core (<5.9), if you try to create a new order and enter customer details without a billing email address, the order sync/creation fails with this error returned by the API: `Dotcom Error: [rest_invalid_param] Invalid parameter(s): billing`

Related API improvement in the 5.9.0 release: https://github.com/woocommerce/woocommerce/pull/30850

This accounts for 2/3 of the order creation failures over the past week (53/81 failures).

**To Reproduce**

1. Start with a store running WooCommerce 5.8 or earlier.
2. Go to the Orders tab and create a new order.
3. Select "Add Customer Details."
4. Enter customer details but leave the Email field on the billing address blank.
5. Notice that after you save the new customer details, the order syncs remotely but returns an error.
6. Tap "Create" to try to create the order, and notice another error appears.

**Screenshots**

Customer details without billing email|Failed order sync|Failed order creation
-|-|-
![IMG_9476](https://user-images.githubusercontent.com/8658164/167161176-3cb87ef3-7a10-428b-a9f8-f3a63c8fb5e8.PNG)|![IMG_9477](https://user-images.githubusercontent.com/8658164/167161170-893b43dd-0204-4446-8663-7004ed7c602b.PNG)|![IMG_9478](https://user-images.githubusercontent.com/8658164/167161160-a5e246be-639a-493c-bea4-278d3747bff1.PNG)

**Expected behavior**

You should be able to save customer details without a billing email address. We work around this when editing existing orders but don't have a similar workaround for order creation:

https://github.com/woocommerce/woocommerce-ios/blob/456e4cd2407c0c91ccbf2d6d1cff9610f4305558/WooCommerce/Classes/ViewRelated/Orders/Order%20Details/Address%20Edit/EditOrderAddressFormViewModel.swift#L209-L217

**Comment by Ecarrion** [comment]
@rachelmcr I was getting confused about this and turns out that we never supported having empty emails on addresses on older stores for Order Edit. We tell them to update the store version.

<img width="429" alt="Screen Shot 2022-05-09 at 6 13 40 PM" src="https://user-images.githubusercontent.com/562080/167513526-42af9bc0-22b1-4f14-a84a-613de7d76a48.png">

Given the number of failures that we have had because of this, do you think it's worth it to spend time crafting a solution to handle empty emails based on the store version? Or should we just show a better error message as we do on order details?

cc @shiki @bummytime

**Comment by rachelmcr** [comment]
> I was getting confused about this and turns out that we never supported having empty emails on addresses on older stores for Order Edit. We tell them to update the store version.

Ah, I was confused about this and must have tested it wrong. Thanks for clarifying the current behavior!

> Given the number of failures that we have had because of this, do you think it's worth it to spend time crafting a solution to handle empty emails based on the store version? Or should we just show a better error message as we do on order details?

I think a better error message would be hugely beneficial, but I also doubt that a merchant would pause creating a new order to update WooCommerce on their store, so this error is probably a blocker for order creation.

I think at minimum we should have an error message that specifically mentions the empty email address (so the merchant can make the choice to enter an email to get past the error in that moment) but it's probably worth spending time to find a solution for this scenario if we can come up with a reasonable way to handle those empty emails on older versions.

**Comment by rachelmcr** [comment]
I thought about this a bit more and I think it might make sense to do two things:

1. Show a better error message now. (If possible, it might be good to make this a fix in the current beta so that it's in production by the time the Order Creation marketing campaign launches.)
2. Keep an eye on the failure events for a couple sprints and then decide if it's still worth crafting a complete solution.

What do you think?

**Comment by shiki** [comment]
I agree with what @rachelmcr said above (https://github.com/woocommerce/woocommerce-ios/issues/6791#issuecomment-1122392083).
