### ISSUE TITLE
[Mobile Payments] "Stripe is not supported in Canada" in IPP onboarding when both WCPay and Stripe are active.

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#6802]
Found in: 
- #6789 

In Canada, when a merchant has both WCPay and Stripe installed and activated, IPP onboarding tells them that Stripe is not supported in Canada.

## Reproduction
Using a Canada WCPay store with the Stripe plugin also installed:

In your browser, activate the Stripe plugin so that both plugins are active
Go to `Menu > ⚙️ > In-Person Payments`
Observe that you see the "Stripe is not supported for IPP in Canada" onboarding screen

In this case, I think we should prioritise the "Multiple Conflicting Plugins", as the resolution is not (necessarily) to remove Stripe, it's to deactivate it again. However, the multiple conflicting plugins onboarding step does suggest that either is an equally valid choice, which isn't true in Canada, so it could lead to frustration

Alternatively, since we don't support Stripe in Canada but do support WCPay, we could ignore the fact that both are installed and continue with WCPay regardless, so avoid showing an onboarding failure. I don't think that would be a good idea with our current design, since we are likely to support either (but not both) one day soon, so a merchant who keeps both plugins for international markets may order a reader now, and find it unusable in a few months time.

See pdfdoF-FO-p2 for relevant discussion

![stripe-not-supported-CA](https://user-images.githubusercontent.com/2472348/167425689-b43ee570-4f9c-49e8-b6ea-da21c39eec1d.jpg)

@joe-keenan what do you think?

**Comment by joe-keenan** [comment]
For now, I agree with you that we should prompt people to deactivate Stripe, using the “conflicting plugins” error as a template.

I’m hoping that [César’s recent proposal to allow simultaneous payment plugins](https://taptopayp2.wordpress.com/2022/04/21/ipp-with-stripe-extension-and-wcpay-installed-and-activated/) causes this to be (mostly) a non-issue, though.

**Comment by toupper** [comment]
Hi @joe-keenan @joshheald I implemented the onboarding screens to prompt people to deactivate Stripe depending on the role (admin-shop manager). It looks like this now:

### Admin
<img src="https://user-images.githubusercontent.com/1864060/168257696-f6c184f2-8992-4f1f-8aee-4aed17fe050b.png" width="375">

### Shop Manager
<img src="https://user-images.githubusercontent.com/1864060/168257843-6a5e1320-1cd7-45a8-84fb-c191bf7962ba.png" width="375">

What do you think? :)

**Comment by joshheald** [comment]
> Hi @joe-keenan @joshheald I implemented the onboarding screens to prompt people to deactivate Stripe depending on the role (admin-shop manager). It looks like this now:
> 
> What do you think? :)

Thanks @toupper, the screens look good, but I think the message is a little hard to read. How about:

```
In-Person Payments are processed through WooCommerce Payments. \n
\n
Please {ask an administrator to} deactivate WooCommerce Stripe Gateway to collect payments.
``` 

Still quite long though! It might be clearer to make the title  "In-Person Payments are processed through WooCommerce Payments.", and the message just the suggested resolution.

I think merging this is better than what we have at the moment, but if @joe-keenan can suggest any clearer wording that'd be cool. No stress though!

**Comment by joe-keenan** [comment]
Hey, late to the party here, but I think Josh’s text is good. I’d change one small thing: Make the second line read 
`To collect payments, please {ask an administrator to} deactivate WooCommerce Stripe Gateway.`
This cleans up the slight awkwardness of the two “to”s in the middle of the sentence and makes the plugin’s name stand out more by putting it at the end. 

Geez, it’s confusing that they all have to have “WooCommerce” at the start of their names.

Hope that helps!

**Comment by toupper** [comment]
Indeed it helps @joe-keenan , thanks for the feedback! 🚀
