### ISSUE TITLE
Order Creation: Add Tracks event when new order fails to sync remotely

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#6824]
The following analytics event should be added:

Event Name|Properties|Trigger
-|-|-
`order_sync_failed`|error_context: $initiated-classname<br />error_type: $errorType<br />error_description: $errorDescription|When a remote sync fails on the New Order screen.

This will help us better understand why some merchants don't finish creating a new order. Internal ref: p91TBi-8Ag-p2

**Comment by shiki** [comment]
Closed by #6829
