### ISSUE TITLE
[Coupons] - Coupon code are uppercase only on edit coupon screen

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#6834]
**Describe the bug**
Currently, coupon codes are displayed as all uppercase when on the edit coupon screen, on other screens they are displayed as all lowercase.

**To Reproduce**
1. Turn on Coupon Management experimental feature
2. Go to hub menu > Coupons > Coupons list/detail - notice that all coupons are in lowercase
3. Edit one coupon - notice that on edit coupon, it's displayed as uppercase

**Screenshots**
On Edit Coupon:
![edit coupon](https://user-images.githubusercontent.com/17252150/168032005-73489ec0-b889-477f-9ecc-f2062c5027ba.PNG)

On Coupon Detail:
![coupon detail](https://user-images.githubusercontent.com/17252150/168032029-5c172241-44ad-4c2d-bed1-9a8c4d26a9f8.PNG)

On Coupon List:
![coupon list](https://user-images.githubusercontent.com/17252150/168032055-c33127d9-9ee8-4935-849c-ce8820114a47.PNG)

**Expected behavior**
It would be nice if the case are the same across screens.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13
- iOS version: 15.3.1
- WooCommerce iOS version: AppCenter build `pr6809-84ae456`

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by ThomazFB** [comment]
@joe-keenan @itsmeichigo do we have something discussed on this issue in the past? Looking at the Figma designs, there's no screen enforcing the name to be fully uppercase, maybe we should remove this uppercase rule from the Edit coupon view? Or am I missing some context?

**Comment by joe-keenan** [comment]
I’m not aware of anything that should stop us from allowing lowercase coupon names. They seem to be allowed on desktop, so if we allowed it, we’d match that.

The one argument for forcing everything to uppercase is that it subtly states that coupons are not case-sensitive. I think this is probably a known fact at this point, so maybe isn’t necessary.
