### ISSUE TITLE
[Coupons] - Header is not updated after editing coupon

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#6835]
**Describe the bug**
After editing coupon code, the header on coupon detail screen is not updated with the new value.

**To Reproduce**
1. Turn on Coupon Management experimental feature
2. Select a coupon 
3. Edit the coupon code and save 
4. Notice on coupon detail, the header is not updated with the new coupon code but the content is

**Screenshots**

https://user-images.githubusercontent.com/17252150/168033797-5b0ce289-60d8-4352-8031-93f6eff5daa5.MP4

**Expected behavior**
Once a coupon is updated, both the header and the content on coupon detail screen should show the updated coupon code.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13
- iOS version: 15.3.1
- WooCommerce iOS version: AppCenter build pr6809-84ae456

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by itsmeichigo** [comment]
Closing as this was fixed in #6857  (this was not closed automatically since I changed the base branch to the release branch).
