### ISSUE TITLE
[Coupons] - Can't remove expiration date when coupon is expired

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#6841]
**Describe the bug**
When a coupon is expired, there is an option to remove the expiration date. However, it looks like it doesn't work. Saving it works but the coupon is still expired. 

**To Reproduce**
1. Turn on Coupon Management experimental feature
2. Select a coupon that's expired
3. Edit Coupon > Coupon Expiry Date > Delete expiration date
4. Save the changes - Looks like save is successful, no error displayed
5. Go back to Coupon detail/list and see that Coupon is still expired 

**Screenshots**

https://user-images.githubusercontent.com/17252150/168045058-d9a14363-aa13-44a4-940b-508f223849e1.MP4

**Expected behavior**
We should be able to remove the expiration date of a coupon and make it active using the `Delete expiration date` option

**Mobile Environment**
Device: iPhone 13
iOS version: 15.3.1
WooCommerce iOS version: AppCenter build pr6809-84ae456

**Comment by itsmeichigo** [comment]
Closing this because it was fixed in #6848.
