### ISSUE TITLE
[Coupons] - Cancel doesn't discard the changes made on edit coupon

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#6844]
**Describe the bug**
Canceling an edit currently doesn't discard the changes. The changes looks to only be discarded after visiting the Coupons list screen.

**To Reproduce**
1. Turn on Coupon Management experimental feature
2. Select a coupon
3. Edit multiple fields on edit coupon screen
4. Click cancel to discard the changes - redirected back to coupon detail screen
5. Click to Edit Coupon again - see that previous changes were not discarded

**Screenshots**

https://user-images.githubusercontent.com/17252150/168050895-e75c2081-afb5-4f47-a809-4e251afc50a1.MP4

**Expected behavior**
Changes on the edit coupon screen should be discarded immediately after cancelling it. 

**Mobile Environment**
Device: iPhone 13
iOS version: 15.3.1
WooCommerce iOS version: AppCenter build pr6809-84ae456

**Comment by itsmeichigo** [comment]
Closing as this was fixed in #6857 (this was not closed automatically since I changed the base branch to the release branch).
