### ISSUE TITLE
[Coupons] - Can't select today's date as expiration date without selecting another date first

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#6851]
**Describe the bug**
Currently, we can't select today's date if it's the first date that is selected. If another date is selected first, then it can be selected.

**To Reproduce**
1. Turn on Coupon Management experimental feature
2. Select a coupon that doesn't have an expiration date
3. Edit Coupon > Coupon Expiry Date 
4. Select today's date - it's already the selected date, nothing happen on another tap
5. Go back - see that expiration date is still empty
6. Select another date before selecting today's date
7. See that expiration date is set to today

**Screenshots**

https://user-images.githubusercontent.com/17252150/168197086-d913e242-c5f5-4403-8ad4-83326ec51e00.MP4

**Expected behavior**
Should be able to select today's date as the expiration date

**Mobile Environment**
Device: iPhone 13
iOS version: 15.3.1
WooCommerce iOS version: AppCenter build pr6809-84ae456

**Comment by itsmeichigo** [comment]
With the enhancements proposed in #6918, this behavior should be expected since we'll require tapping the Done button to actually select any date. @jostnes - please feel free to close this issue in favor of #6918 if you think it makes sense.

**Comment by jostnes** [comment]
Sounds good! I'll close this as the date picker will be updated as part of https://github.com/woocommerce/woocommerce-ios/issues/6918
