### ISSUE TITLE
Update to Buildkite Xcode 13.3.1 image 

### ISSUE THREAD

**Issue by toupper** [woocommerce/woocommerce-ios#6877]
Now that the migration to Buildkite is done, we want to update the Buildkite Xcode image to 13.2 so we can start using the features available from that release point.

- This consists of updating the IMAGE_ID entry in each *.yml pipeline found [in the ](https://github.com/woocommerce/woocommerce-ios/tree/trunk/.buildkite).buildkite[ folder](https://github.com/woocommerce/woocommerce-ios/tree/trunk/.buildkite), especially [this line](https://github.com/woocommerce/woocommerce-ios/blob/trunk/.buildkite/pipeline.yml#L11) and [that one](https://github.com/woocommerce/woocommerce-ios/blob/trunk/.buildkite/release-builds.yml#L13)
- To find which new value to use, you can look at the list of available images [here](https://github.com/Automattic/buildkite-ci/tree/trunk/src/macos-vms/manifests) and use one of the basenames of those json files as the value for IMAGE_ID (e.g. xcode-13.2.1… though at this stage you might as well jump directly to xcode-13.3.1?)

**Comment by pmusolino** [comment]
Today Xcode 13.4 was released, so probably it's worth trying to update to 13.4 directly when will be available in Buildkite.

**Comment by toupper** [comment]
@pmusolino I created a [PR](https://github.com/woocommerce/woocommerce-ios/pull/6884) to update it to 13.3.1, so we can start using these functionalities from now on (e.g `async/await`) When we all migrate locally to 13.4 and the image for 13.4 becomes available in Buildkite we can update it again. What do you think? :)

**Comment by pmusolino** [comment]
@toupper sounds great to me! 🚀
