### ISSUE TITLE
[Mobile Payments] After payment, change "Back to Order" to "Save Receipt and Continue"

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#6905]
> ![Image](https://user-images.githubusercontent.com/2472348/169260609-65fccacd-f2d3-467b-899e-740f07941665.png)
> Context: p91TBi-8P0-p2#cpp-inconsistencies

- [ ] After collecting a payment, change _Back to Order_ to _Save receipt and continue_ on iOS.

**Comment by toupper** [comment]
I also included the case when the user does not have an email account on their device and thus there is no email receipt button:

<img src="https://user-images.githubusercontent.com/1864060/169838203-0160b827-ffb0-4971-9d8e-209a99965eb3.png" width="375">
