### ISSUE TITLE
[Products] Cannot refresh list when empty state is displayed

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#6923]
## Description
When there is an empty state on the Products list, the pull-to-refresh control is not available. The list does not automatically refresh itself. 

This can lead to a state where the app believes there are no products, but there are, and they will only display if 
1. A search is performed and finds results
2. A new product is added on the phone.

## Repro
1. Delete the app from your device if it is installed
2. Build or install and run the app
3. Log in and select your site
4. Turn on Airplane mode
5. Switch to the Products tab – observe that the empty state is shown
6. Turn off Airplane mode
7. Pull to refresh – observe that it is not possible
8. Switch tabs, close and open the app – observe that the products list is still not updated9. 

At that point, if you search for a product name you know, any search results will be added to the products list when you close search. Once they are added, you can pull-to-refresh to get a full list of results.

Also note that the Orders list refreshes when you open that tab, so does not face this issue.

## Video

https://user-images.githubusercontent.com/2472348/169846489-2d8fdd71-90a7-42ab-bb8e-87746737525b.mp4

**Comment by rachelmcr** [comment]
This should be covered by https://github.com/woocommerce/woocommerce-ios/issues/6356, which has a proposed fix for all empty views.

**Comment by joshheald** [comment]
Prioritization:
Severity – Medium: bug with a workaround
Impact – Low: estimated 0-5% of users.
Rationale: because most people will add products before they use the app, and most people will have a working internet connection when they first open the products tab.
= low

**Comment by joshheald** [comment]
> This should be covered by #6356, which has a proposed fix for all empty views.

Oh thanks! Should have checked. Will close this one now...
