### ISSUE TITLE
[Reviews] After opening review from notification, back button goes to Hub not Review list

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#6929]
[After following a notification] The review details is presented in a nav control with the back button taking the user to the Hub menu. It seems like this should go back to the Reviews list as previously...?

_Originally posted by @joshheald in https://github.com/woocommerce/woocommerce-ios/issues/3584#issuecomment-1135849753_

Repro:
1. With the app in any state: open, closed, or backgrounded.
2. Add a review on the web.
3. Tap the notification or view button
4. Observe that you're shown the review details screen
5. Tap back
6. Observe that you're taken to the hub menu

Expected:
You should be taken to the reviews list, then another back button tap would go to the hub menu.

**Comment by joshheald** [comment]
Prioritization:
Severity – low: navigation issue with workaround
Impact – medium: estimated 6%+ users affected
 = low

**Comment by itsmeichigo** [comment]
Closing this since it seems to have been fixed by #6963.
