### ISSUE TITLE
Only refresh My Store stats data when a new order is placed for the site

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-ios#6966]
We fetch site stats every time we open My Store tab. To reduce the number of requests done to the `analytics` endpoint, while keeping the data fresh, we can: 

- ✅ Save cached data whenever we fetch stats from the API --> already done in iOS
- ✅ Add an expiration date to the data, to expire the cached data even if no order is placed for the site --> already done in iOS https://github.com/woocommerce/woocommerce-ios/pull/5497
---
Tasks
- [x] Reset the last sync timestamp whenever a new order is placed https://github.com/woocommerce/woocommerce-ios/pull/7665
~~- [ ] Visitor stats are not included as part of this caching/invalidating policy. Visitor stats should always be refreshed.~~
Update: the app has been using the last sync timestamp for a while for visitor stats and I think it's okay to keep it for now

**Comment by jaclync** [comment]
Closing this now that the main task was done.
