### ISSUE TITLE
[Mobile Payments] Add tracking for payment gateway selection

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#6994]
Add new tracking for events related to payment gateway selection:

- When user taps on "Payment Provider" new row from In-Person Payments settings (`settings_card_present_select_payment_gateway_tapped`) https://github.com/woocommerce/woocommerce-android/issues/6632
- When payment gateway selection is presented (`card_present_select_payment_gateway_show`) https://github.com/woocommerce/woocommerce-android/issues/6630
- When a payment gateway is selected (`card_present_payment_gateway_selected`, properties: `"payment_gateway"`: `"WooCommerce Payments"|"WooCommerce Stripe Gateway"`) https://github.com/woocommerce/woocommerce-android/issues/6631

The exact event names are yet to be decided, but make sure they match on Android

**Comment by toupper** [comment]
@rossanafmenezes @AnirudhBhat  I updated the tracking strings, please take a look so we can synchronize them on both platforms. Please note that I remove the word onboarding from the strings in comparison with what we have on android tickets, as this screen can be also shown in settings outside of the onboarding context.
