### ISSUE TITLE
Dashboard: Arrow to view pending orders is backwards for RTL languages

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#703]
**Describe the bug**

When my device UI is an RTL language, the arrow to open the pending orders section is backwards.

**To Reproduce**
1. Change your device UI language to an RTL language (e.g. Arabic).
2. Open the My store dashboard.
3. Scroll down to the pending orders section.
4. Note the direction of the arrow to open that section.

**Screenshots**

Arrow pointed to the right in LTR languages:

![2019-02-20 11 21 54](https://user-images.githubusercontent.com/8658164/53089149-a7543b00-3503-11e9-9f68-117191438347.png)

Arrow still (incorrectly) pointed to the right in RTL languages:

![2019-02-20 11 20 33](https://user-images.githubusercontent.com/8658164/53089158-af13df80-3503-11e9-8d33-723e1bdf4f1d.png)

**Expected behavior**

The arrow should be pointed to the left.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 12.1.4
- WooCommerce iOS version: 1.2.0.0 (beta)

**Comment by bummytime** [comment]
Thank you for catching this @rachelmcr!
