### ISSUE TITLE
Order Creation: Should we sanitize percentage value for fee?

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#7072]
**Describe the bug**
We're currently not sanitizing the percentage value for the fee when creating orders. This leads to the possibility that we have a really high fee that is unlikely to be realistic.

**To Reproduce**
1. Go to Orders > Create a new order.
2. Add a product to the order.
3. Select Fee, switch to Percentage, and enter a value larger than 100.
4. Save the fee, notice that the calculated fee is really high.

**Screenshots**

https://user-images.githubusercontent.com/5533851/173044898-ecbcf790-f10a-4dba-9e16-3f975e147b37.mov

**Expected behavior**
Maybe make sure that the value doesn't exceed 100? We can do something similar to the discussion in #7036.

**Comment by rachelmcr** [comment]
That's an interesting point. I checked wp-admin and confirmed I can enter a very high percentage fee there:

![Screen Shot 2022-06-13 at 11 35 08 AM](https://user-images.githubusercontent.com/8658164/173335998-397a2eb7-eed0-42ef-83cd-6b05605ec5d3.png)

That doesn't mean we couldn't/shouldn't add a limit, but it makes me think about the reasoning behind it. It makes more sense to limit coupons, which by their nature shouldn't exceed the order total. But there's no reason why a fee couldn't, in theory, be greater than the order total. For example, an order for a very cheap item may have a larger processing fee. That kind of higher fee probably makes more sense as a fixed-priced fee than a percentage-based fee, but even so I don't see any danger or logical problem with allowing high percentage fees.

What do you think?

**Comment by itsmeichigo** [comment]
Thanks for the response @rachelmcr! It seems that I don't have a full understanding of the use case for orders - it makes sense that the fee is higher than the price, as you said. And since the value isn't limited on the web, we should probably follow the behavior so that merchants get the same experiences on the platforms. 

I'll go ahead and close this issue for now.
