### ISSUE TITLE
[Unified Order Editing] Add Done Button

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#7076]
# Description

As discussed in p91TBi-91L-p2, in order to overcome some limitations identified for the cancel functionality, we are going to provide just a **Done** button to allow the merchant to exist the flow.

The **Done** button won't perform any network request when editing an order so we need to make sure all changes are already commited to the remote order.

# Task

- [x] Add a **Done** button to the top right of the navigation/app bar. This button should only be visible for the edit flow and should close/dismiss the edit view.

**Comment by ealeksandrov** [comment]
@Ecarrion looks like this is done as well? Single navbar button, no network requests.

**Comment by Ecarrion** [comment]
I think so, closing!
