### ISSUE TITLE
Hub Menu: White space on top of the view on iOS 16 (built with Xcode 14 beta)

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#7091]
**Describe the bug**
When building the app with Xcode 14 beta into an iOS 16 simulator, I found that the menu tab has additional space on top of the view where a navigation bar could be.

**To Reproduce**
1. Download Xcode 14 beta if you haven't already.
2. Build the app to an iOS 14 simulator.
3. Switch to the Menu tab.
4. Notice that there's an additional space on top of the view.

**Screenshots**
<img src="https://user-images.githubusercontent.com/5533851/173798312-73768287-e5bf-483e-9652-adc9971904ae.png" width=320 />

**Expected behavior**
No additional space should be present.

**Comment by pmusolino** [comment]
Good catch! 👍
