### ISSUE TITLE
[Mobile Payments] Ensure refunds go through the gateway used for payment when there are multiple

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#7098]
When `IssueRefundViewModel` attempts a refund, it will choose the gateway to use by picking the first one (`paymentGatewayAccounts.first`).

This might have worked when the app forced users to only have one active payment gateway extension, but won't work well with more than one

**Comment by toupper** [comment]
This is implemented and tested via https://github.com/woocommerce/woocommerce-ios/pull/7153
