### ISSUE TITLE
Remove productsVariationsFeedback from Surveys

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#7139]
Depends on https://github.com/woocommerce/woocommerce-ios/pull/7129

If we remove the product variations banner from the Products tab on https://github.com/woocommerce/woocommerce-ios/pull/7129 , do we want to clear `case productsVariationsFeedback` as well  from `SurveyViewController`? 

This seems to involve configuring and tracking survey completions for these features. I understand we do not need it anymore for product variations, but I wanted to double-check first as involves tracking and analytics.

**Comment by rachelmcr** [comment]
I haven't reviewed everything around this code, but given that it's used for displaying/tracking the product variations feedback survey and once we remove the banner we won't be soliciting that feedback anymore, it seems very reasonable to remove it now.
