### ISSUE TITLE
Crash on log out

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#715]
**Describe the bug**
Threading issue. An issue with threading was exposed after #702 was introduced, where the app gets logged out, the sessionManager is reset, but the `defaultAccountWasUpdated` in the DashboardVC attempted to access the sessionManager after it was reset. `defaultAccountWasUpdated` resets the Dashboard before logging out is finished.

**To Reproduce**
1. Check out the 1.3 branch
2. Run the branch on your simulator
3. Log out of your current store
4. See crash

**Screenshots**
N/A

**Expected behavior**
The app does not crash upon logout.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: all
- iOS version: any
- WooCommerce iOS version: 1.3

**WordPress Environment**
N/A

**Comment by bummytime** [comment]
Great catch here @mindgraffiti ! 🎣

**Comment by mindgraffiti** [comment]
Fixed in PR #716.
