### ISSUE TITLE
[Coupons] - Add coupon cut off on first view

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#7201]
**Describe the bug**
On first load, the Create Coupon screen is slightly cut off at the bottom of the screen

**To Reproduce**
1. Turn on Coupon Management experimental feature
2. Go to Menu > Coupon > Add Coupon
3. See that Create Coupon is slightly cut off 

**Screenshots**
![coupon cut off ios](https://user-images.githubusercontent.com/17252150/177128791-661623ae-f48d-421a-81f7-2131e09d5dd5.PNG)

**Expected behavior**
Create coupon shouldn't be cut off

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13 mini
- iOS version: 15.5
- WooCommerce iOS version: Alpha build pr7158-ea5e009

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by pmusolino** [comment]
I'm currently experimenting the same issue 👍
