### ISSUE TITLE
[Order Details] Do not show Mark Order Complete for unpaid orders

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#7207]
Unpaid orders in the Processing status currently show the `Mark Order Complete` button prominently as the first and main call to action. They also show `Collect Payment`, as there's no `date_paid` set for the order.

If the merchant taps that, the side effect is that the order gets marked as paid, but a better primary CTA is to use the `Collect Payment` button to show the payment options.

The merchant can still perform the mark complete action by using the pencil icon next to the status.

- [ ] Do not show the `Mark Order Complete` button for unpaid orders
- [ ] Show the `Mark Order Complete` as a secondary CTA for paid orders, when the `Create Shipping Label` button is available.

**Comment by iamgabrielma** [comment]
> Unpaid orders in the Processing status 

In theory, this shouldn't be possible, as the processing status means that the Order has already been paid but is waiting for fulfillment from the merchant's end. This could be derived from a naming confusion [here](https://github.com/woocommerce/woocommerce-ios/blob/5015c2b525fa85cbdd5dfc67f5ec8c50ab1a1fd3/WooCommerce/Classes/ViewModels/Order%20Details/OrderDetailsDataSource.swift#L1004), as we use this logic later on in the `OrderDetailsDataSource` for showing the "Mark as Complete" row. 

Perhaps we could rewrite these, from:

```
    /// Is this order processing?
    ///
    private var isProcessingPayment: Bool {
        return order.status == OrderStatusEnum.processing
    }
```

To:

```
    /// Is this order processing? Payment received (paid), the stock has been reduced, and the order is awaiting fulfillment.
    ///
    private var isProcessing: Bool {
        return order.status == OrderStatusEnum.processing
    }

    /// Is this order pending payment? Awaiting payment (unpaid).
    ///
    private var isPendingPayment: Bool {
        return order.status == OrderStatusEnum.pending
    }
```
From here only `.completed` (paid) and `.processing` (paid) should have a non-nil `date_paid` param:

```
# Marked as processing:

(lldb) po order.datePaid
▿ Optional<Date>
  ▿ some : 2022-07-12 07:18:34 +0000

## Marked as completed:

(lldb) po order.datePaid
▿ Optional<Date>
  ▿ some : 2022-07-12 07:13:33 +0000

## Marked as on-hold:

(lldb) po order.datePaid
nil

## Marked as pending:

(lldb)  po order.datePaid
nil

## Marked as failed:

(lldb) po order.datePaid
nil
```
