### ISSUE TITLE
build not completed

### ISSUE THREAD

**Issue by tecziq-vikas** [woocommerce/woocommerce-ios#7224]
when i build , after some time it stop & not giving any issue, only show building 2- 3 hours continuously, 
<img width="1440" alt="Screenshot 2022-07-06 at 3 34 39 PM" src="https://user-images.githubusercontent.com/87491705/177527278-7940369e-3a84-4deb-9333-3f44c8695671.png">

**Comment by tecziq-vikas** [comment]
when i run app in device its not completed , only show building

**Comment by itsmeichigo** [comment]
Hi @tecziq-vikas - if you are still having problems building the app, could you provide more information: the version of Xcode and the machine that you are using to build and the log of the build process (on the Report Navigator on the left sidebar). These will be helpful for us to help you.
