### ISSUE TITLE
[Order Meta Data] Add UI to display a list of order metadata in Order Details screen

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#7241]
We need to add the UI to display a list of order metadata in the Order Details screen. We can use existing design patterns to add the UI as follows:

* Because order metadata can be quite large, our order detail UI will have a button which shows a separate screen containing the metadata.
* The metadata will be displayed with the section/screen titled "Custom Fields" and a read-only list of field names (keys) and values.

This will be similar to the Custom Fields section in wp-admin (only read-only for now):

![Image](https://user-images.githubusercontent.com/8658164/177376909-54642721-2d14-419c-8844-b92d0a497858.png)

**Comment by ThomazFB** [comment]
@rachelmcr I was thinking of leaving the changes to the Order Details to access the metadata list under development in https://github.com/woocommerce/woocommerce-ios/pull/7257 behind a feature flag, so we can keep adjusting the view in multiple tasks/PR without problems, does it makes sense?

**Comment by rachelmcr** [comment]
Yeah, that sounds reasonable to me! 👍
