### ISSUE TITLE
In-person Payments: Missing currency on the collect payment alert

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#7263]
**Describe the bug**
The amount on the Collect Payment alert is missing currency.

**To Reproduce**
1. Make sure your store is eligible for in-person payment
2. Select an order that is pending for payment.
3. Select Collect Payment > select Card payment method > complete the onboarding steps if needed.
4. When the Collect Payment alert is displayed, notice that the amount is formatted without currency.

**Screenshots**
<img src="https://user-images.githubusercontent.com/5533851/178026283-9bc2735c-38d5-42eb-826a-0e5b920a1f3b.png" width=320 />

**Expected behavior**
The currency should be present on the alert.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by jaclync** [comment]
In addition to the alert screen, the title on the payment method selector screen is also missing a currency symbol:

<img src="https://user-images.githubusercontent.com/1945542/178041535-e3d80757-c966-4757-a389-394056cd2d10.png" width="300" />
