### ISSUE TITLE
Order details: Failure message doesn't appear on screen when adding a note to an order fails

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#728]
**Describe the bug**

When adding a note to an order fails, I expect to see a message on screen with a retry button, as shown in https://github.com/woocommerce/woocommerce-ios/pull/687.

However, my keyboard covers the bottom part of the screen and so no message appears.

**To Reproduce**
1. Go to the Orders tab.
2. Select an order to see its details.
3. Scroll down to the Order Notes and tap Add a note.
4. Disconnect from the network (e.g. enable airplane mode).
5. Type out a note and tap Add to add it.

Result: I feel the haptic feedback that tells me I should see a message, but nothing appears on screen.

**Screenshots**

![2019-02-28 11 53 26](https://user-images.githubusercontent.com/8658164/53564717-8ae17f80-3b4f-11e9-951b-360b0bd77029.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS (no external keyboard)
- iOS version: 12.1.4
- WooCommerce iOS version: 1.3.0.1 TestFlight beta

**Comment by ctarda** [comment]
@rachelmcr I have been using the exact testing steps in this PR: #726  that were used here to reproduce the bug. I think this might be addressed indirectly by #726 but will double check
