### ISSUE TITLE
[Orders] - Extra spacing on Customer section on Order screen

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#7288]
**Describe the bug**
When the customer provided note section is empty, there seems to be too much space between the header and the Add Customer Note link.

**To Reproduce**
1. Go to Orders
2. Scroll down to "Customer Provided Note" section
4. See that the spacing between the header and the link is too much when there's no note added

**Screenshots**
Without Customer Note:
![IMG_0109](https://user-images.githubusercontent.com/17252150/178925188-e31ceff9-7b8e-4a58-b070-0ea3a5e0202d.PNG)

With Customer Note:
![IMG_0110](https://user-images.githubusercontent.com/17252150/178925209-02fab140-a5c8-42ff-8218-114542216dbc.PNG)

**Expected behavior**
It should be similar to other fields on the screen, example like Shipping Details

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13 mini
- iOS version: 15.5
- WooCommerce iOS version: 19.6 (also reproducible in current App Store version, 19.5)

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by Ecarrion** [comment]
Thanks for reporting this @jostnes, this screen will change once the UOE project is released. When an order does not has a customer note, that section will be hidden.

No Note | New Note
---- | ----
<img width="437" alt="no" src="https://user-images.githubusercontent.com/562080/179024169-f0705bd1-6221-4b08-8569-930f3b83ba5e.png"> | <img width="435" alt="yes" src="https://user-images.githubusercontent.com/562080/179024173-b203d4b3-9095-4b73-b034-f66347d75a2d.png">
