### ISSUE TITLE
"Discard changes" appearing when tapping on the left side of certain screens

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#7289]
**Describe the bug**
"Discard changes" appears when attempting to click on links on the left side of the screen. So far, looks to be happening on Add Order and Add/Edit Products screens. 

**To Reproduce**
1. Go to Add Order screen
2. Make some changes on the screen so that there are changes to discard
3. Tap on the very left side of `+ Add Shipping` or `+ Add Fee` 
4. See that sometimes the Discard changes is displayed 
5. Gesture left-to-right and it will also appear almost consistently

**Screenshots**

https://user-images.githubusercontent.com/17252150/178940428-28bde10e-255b-460c-afc7-95777899ec43.MP4

**Expected behavior**
Discard changes should only be displayed when attempting to leave the screen before saving

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13 mini
- iOS version: 15.5
- WooCommerce iOS version: v19.6 (also reproducible on v19.5)

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by rachelmcr** [comment]
This happens because the "swipe to dismiss" gesture is being triggered, which brings up that prompt.

This has come up in a couple past issues for both products and orders (https://github.com/woocommerce/woocommerce-ios/issues/2249 and https://github.com/woocommerce/woocommerce-ios/issues/6624) and the conclusion was that we don't really have a good solution for this as long as we want to support that gesture.

Given that context, I'm inclined to accept this behavior. What do you think?

**Comment by jostnes** [comment]
Thanks for the explanation and linking the two issues. Yeah given that there's not a good solution to fix this now, I think it's okay to close this. Though the one concern I have is that the previous issue was opened in April and then this one, which is quite close in timing, is there a possibility that it's easier to reproduce now?

I'll close this for now, we can monitor if this gets reported again in the near future.

**Comment by rachelmcr** [comment]
> Though the one concern I have is that the previous issue was opened in April and then this one, which is quite close in timing, is there a possibility that it's easier to reproduce now?

The previous issue in April was reported during pre-release testing for Order Creation. That's when the screen with that "Discard Changes" prompt was introduced in Orders, so I'm not too worried — it's just being used in more parts of the app now.

Thanks for raising the issue!
