### ISSUE TITLE
Store switch notification messaging

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-ios#729]
Orignally posted - p5T066-Mu-p2/#comment-2494

Now that we have store switching, it isn't clear that when a store owner switches from Site A to Site B, they won't keep on receiving pings from Site A. 

**Describe the solution you'd like**

Account wide notifications are in the pipeline for some point but for now, I feel a message around "Now you have switched to Store B, you will only receive notifications related to this store".

**Comment by bummytime** [comment]
Good idea @dougaitken — thanks! @kyleaparker any thoughts on this?

**Comment by kyleaparker** [comment]
👍 makes sense to me, either a notice after switching or something on the accounts screen
