### ISSUE TITLE
Search for products by SKU in Mobile App

### ISSUE THREAD

**Issue by imodouglas** [woocommerce/woocommerce-ios#7303]
Currently, users cannot search for products in the mobile app by SKU.

I have a user who complained about that here: https://woothemes.zendesk.com/agent/tickets/5396331

I also noticed that it was in the ideas board as stated by Paulina in this ticket: https://woothemes.zendesk.com/agent/tickets/5279597

Due to the discontinuance of the ideas board, there is no way for users to drop ideas on the site except by using the feedback button in the app or reaching out by ticket.

**Comment by rachelmcr** [comment]
Thanks! We're tracking this feature request in https://github.com/woocommerce/woocommerce-ios/issues/3157.
