### ISSUE TITLE
Background image upload: the discard changes alert is not shown when navigating away from product details

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#7313]
Ref: p5T066-3ok-p2#comment-12987

**Describe the bug**

After uploading an image in product details and then navigating away, the discard changes alert is not shown if the images are the only changes. Other changes like product name trigger the alert.

**To Reproduce**

- Go to the Products tab
- Tap on an editable product
- Tap on the images header to the product images screen
- Upload an image
- After the upload, quickly navigate away from product details while the image is still uploading by tapping the "<" button or swipe back gesture --> the "discard changes" alert is not shown

**Screenshots**

Screencast in p5T066-3ok-p2#comment-12987

**Expected behavior**

A discard changes alert should be shown when navigating away from product details while an image is pending upload.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: any 
- WooCommerce iOS version: 9.6

**Comment by rachelmcr** [comment]
I tested this again on `trunk` and confirmed that the discard changes alert is now always shown, even while the image is pending upload.
