### ISSUE TITLE
Cannot load order details

### ISSUE THREAD

**Issue by csvke** [woocommerce/woocommerce-ios#733]
After installing the iOS app and logging in via JetPack, I am unable to get the orders displayed in the app. It says unable to refresh list.
However, I can still receive Notifications. And when I tap onto the notification of 'You have a new order!', it can take me to the order with details.

Here is the Application Log from the iOS app:

> error synchronizing orders: Dotcom Error: [no response _body] server could not read response

- Device: iPhone X / iPad Pro 12.9" 
- iOS version: 12.1.4
- WooCommerce iOS version: 3.5.5

`
### WordPress Environment ###

Home URL: https://www.lantau-grocer.com
Site URL: https://www.lantau-grocer.com
WC Version: 3.5.5
Log Directory Writable: ✔
WP Version: 5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2
PHP Version: 7.1.9 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.29.0
NSS/3.21 Basic ECC

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.0.32-MariaDB
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 10.93MB
Database Data Size: 8.50MB
Database Index Size: 2.43MB
wp_woocommerce_sessions: Data: 0.17MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.08MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.31MB + Index: 0.28MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_alm: Data: 0.02MB + Index: 0.00MB
wp_aryo_activity_log: Data: 0.20MB + Index: 0.00MB
wp_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_atum_order_items: Data: 0.02MB + Index: 0.02MB
wp_atum_product_data: Data: 0.02MB + Index: 0.03MB
wp_aws_cache: Data: 0.02MB + Index: 0.00MB
wp_aws_index: Data: 0.48MB + Index: 0.00MB
wp_berocket_termmeta: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.13MB + Index: 0.09MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_masterslider_options: Data: 0.02MB + Index: 0.02MB
wp_masterslider_sliders: Data: 0.02MB + Index: 0.02MB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB
wp_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB
wp_nextend2_section_storage: Data: 0.02MB + Index: 0.03MB
wp_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB
wp_nextend2_smartslider3_sliders: Data: 0.02MB + Index: 0.00MB
wp_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.00MB
wp_nextend2_smartslider3_slides: Data: 0.05MB + Index: 0.00MB
wp_nm_personalized: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 2.44MB + Index: 0.17MB
wp_postmeta: Data: 2.52MB + Index: 0.70MB
wp_posts: Data: 0.45MB + Index: 0.16MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_rm_fields: Data: 0.02MB + Index: 0.00MB
wp_rm_forms: Data: 0.02MB + Index: 0.00MB
wp_rm_front_users: Data: 0.02MB + Index: 0.00MB
wp_rm_login: Data: 0.02MB + Index: 0.00MB
wp_rm_login_log: Data: 0.02MB + Index: 0.00MB
wp_rm_notes: Data: 0.02MB + Index: 0.00MB
wp_rm_paypal_fields: Data: 0.02MB + Index: 0.00MB
wp_rm_paypal_logs: Data: 0.02MB + Index: 0.00MB
wp_rm_rules: Data: 0.02MB + Index: 0.00MB
wp_rm_sent_mails: Data: 0.02MB + Index: 0.00MB
wp_rm_sessions: Data: 0.02MB + Index: 0.00MB
wp_rm_stats: Data: 0.02MB + Index: 0.00MB
wp_rm_submissions: Data: 0.02MB + Index: 0.00MB
wp_rm_submission_fields: Data: 0.02MB + Index: 0.00MB
wp_rm_tasks: Data: 0.02MB + Index: 0.00MB
wp_rm_task_exe_log: Data: 0.02MB + Index: 0.00MB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wp_snippets: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.08MB + Index: 0.06MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_UPCP_Catalogues: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Catalogue_Items: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Categories: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Custom_Fields: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Fields_Meta: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Items: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Item_Images: Data: 0.02MB + Index: 0.00MB
wp_UPCP_SubCategories: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Tagged_Items: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Tags: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Tag_Groups: Data: 0.02MB + Index: 0.00MB
wp_UPCP_Videos: Data: 0.02MB + Index: 0.00MB
wp_usermeta: Data: 0.09MB + Index: 0.11MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_user_registration_sessions: Data: 0.02MB + Index: 0.02MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.08MB + Index: 0.02MB
wp_woocommerce_exported_xml_items: Data: 0.02MB + Index: 0.02MB
wp_woo_wallet_transactions: Data: 0.02MB + Index: 0.02MB
wp_woo_wallet_transaction_meta: Data: 0.02MB + Index: 0.03MB
wp_ywcdd_calendar: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

advgb_profiles: 1
attachment: 282
br_filters_group: 1
br_labels: 2
custom_css: 1
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
ml-slide: 4
ml-slider: 1
nav_menu_item: 10
page: 18
post: 2
product: 212
scheduled-action: 74
shop_order: 62
user_registration: 2
wp_block: 2
yith_proc_method: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (36) ###

Query Monitor: by John Blackbourn – 3.3.1
Advanced Gutenberg Blocks: by maximebj – 1.8.5
Advanced Gutenberg: by JoomUnited – 1.10.4
WooCommerce Advanced Product Labels: by BeRocket – 1.1.12
Advanced Woo Search: by ILLID – 1.62
BackWPup: by Inpsyde GmbH – 3.6.8
Code Snippets: by Shea Bunge – 2.13.2
WooCommerce Continue Shopping: by HappyKite – 1.3.1 – Not tested with the active version of WooCommerce
Flexible Checkout Fields: by WP Desk – 1.9.0
Hide Featured Image: by shahpranaf – 1.3.1
States, Cities, and Places in dropdown for Woocommerce for Tung Chung and South Lantau: by Kingsley Ochu – 1.1.1 – Not tested with the active version of WooCommerce
Jetpack by WordPress.com: by Automattic – 7.0.1
WooCommerce Load More Products: by BeRocket – 1.1.5.3
Max Mega Menu - Pro Addon: by megamenu.com – 1.7.1
Max Mega Menu - StoreFront Integration: by Tom Hemsley – 1.0.2
Max Mega Menu: by megamenu.com – 2.5.3.2
Order Delivery Date Pro for WooCommerce: by Tyche Softwares – 9.3
WooCommerce PDF Invoices, Packing Slips, Delivery Notes & Shipping Labels(Basic): by WebToffee – 2.4.6
Quantity Field on Shop Page for WooCommerce: by Wooassist – 1.1.0 – Not tested with the active version of WooCommerce
Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.1.3

Repeat Order for Woocommerce: by polyres – 1.1.0
WordPress Version Info: by alpipego – 1.1.4
W3 Total Cache: by Frederick Townes – 0.9.7.2
Wish List for WooCommerce: by Algoritmika Ltd – 1.5.2 – Not tested with the active version of WooCommerce
WooCommerce Blocks: by Automattic – 1.4.0
Advanced Order Export For WooCommerce: by AlgolPlus – 2.1.1
WooCommerce Wallet: by Subrata Mal – 1.3.2
Advanced AJAX Product Filters for WooCommerce: by BeRocket – 1.3.0.2
WooCommerce Customer/Order XML Export Suite: by SkyVerge – 2.4.3 – 2.5.0 is available
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.9
WooCommerce Stripe Gateway: by WooCommerce – 4.1.14
WooCommerce Hide Checkout Shipping Address: by Web Whales – 1.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.5.5
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.2.12

Smush: by WPMU DEV – 3.1.1
WPFront Scroll Top: by Syam Mohan – 2.0.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: HKD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.4.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Customer/Order XML Export Suite ###

Order Export Format: default
Customer Export Format: default
Automatically Export Orders: disabled
Automatically Export Customers: disabled

**Comment by csvke** [comment]
An error occured while fetching API info for siteID xxxxxxxxx: Optional(Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={_kCFStreamErrorCodeKey=57, NSUnderlyingError=0x2832b9a10 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={_kCFStreamErrorCodeKey=57, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <2BFCE1F5-6515-445A-B19E-298925CE8AA1>.<21>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <2BFCE1F5-6515-445A-B19E-298925CE8AA1>.<21>"
), NSLocalizedDescription=The network connection was lost., NSErrorFailingURLStringKey=https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/xxxxxxxxx/rest-api/?_method=get&json=true&path=/, NSErrorFailingURLKey=https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/xxxxxxxxx/rest-api/?_method=get&json=true&path=/, _kCFStreamErrorDomainKey=1})

**Comment by bummytime** [comment]
Thanks for reporting this @csvke! It appears you started a support ticket already. I am going to close this issue here and let you continue working with our support team — that will be the best way to get this issue resolved.
