### ISSUE TITLE
[Xcode 14] Navigation bar doesn't display on "Inbox" and "Reviews" page

### ISSUE THREAD

**Issue by crazytonyli** [woocommerce/woocommerce-ios#7393]
Please note, this is an issue on Xcode 14 beta 4(not sure about previous betas), I'll update this issue once new beta is out.

(Update: still an issue on Xcode 14 beta 6)

**Describe the bug**
When app is launched from Xcode 14 beta 4, the "Inbox" and "Reviews" page (maybe other pages in hub menu page too) don't have a navigation bar.

**To Reproduce**
1. Launch the app using Xcode 14 beta 4.
1. Sign in to a site.
1. Go to 'Menu'.
1. Click on 'Inbox', or 'Reviews'.
1. Navigation bar doesn't display on the Inbox (or Reviews) screen.

**Screenshots**
|Inbox|Reviews|
|-----|-------|
|![inbox](https://user-images.githubusercontent.com/1101828/182263009-a57726d2-c259-4d7e-a98f-d8897dbb55cb.png)|![reviews](https://user-images.githubusercontent.com/1101828/182263040-b72847d2-8a2e-45b7-aef5-79ef8105293e.png)|

**Expected behavior**
Navigation bar displays on 'Inbox' and 'Reviews' screen.

**Isolating the problem (mark completed items with an [x]):**
~- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.~
~- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).~
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iOS Simulator
- iOS version: 16.0
- WooCommerce iOS version: `trunk` branch.

**WordPress Environment**
<details>
I don't think the WP environment is relevant for this issue, please let me know if you think it is and I'll update this issue.
</details>

**Comment by crazytonyli** [comment]
Hi @iamgabrielma and @jaclync , I thought I'll let you all know about this issue, since you both worked on this screen recently. This might just be an issue in Xcode beta, I'm not sure, but I'll re-visit this issue once next beta is out.

**Comment by itsmeichigo** [comment]
This no longer happens when built with the official Xcode 14 build.

**Comment by crazytonyli** [comment]
@itsmeichigo I just checked on the trunk branch, this Xcode 14 issue still happens on an iOS 16 simulator. But with [this workaround for iOS 16](https://github.com/woocommerce/woocommerce-ios/pull/7371/commits/30df0bb4b78318f6df1c6e75ebed1a2a7ac26040), this issue no longer happens. Not sure if I missed anything.

**Comment by itsmeichigo** [comment]
Yup I was testing on your branch xcode-14-workaround which includes the fix for the navigation bar in the hub menu.
