### ISSUE TITLE
[Reviews] Product name not displayed on reviews on first load

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#7402]
**Describe the bug**
Product name is not displayed on review screen the first time user lands on the screen. This looks to be a regression of this issue https://github.com/woocommerce/woocommerce-ios/issues/1907

**To Reproduce**
1. Get fresh install of the app
2. Send a review from web
3. Once received on the app, go to Menu > Reviews
4. See that the product name is not displayed on the review list screen
5. Go back to the previous page and return
6. See that product name is now displayed on the review list

**Screenshots**

https://user-images.githubusercontent.com/17252150/182511563-75065d47-6614-4ccb-aad8-b184604bef2b.MP4

**Expected behavior**
Product name should be displayed on the review on the first load.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13 Mini
- iOS version: 15.5
- WooCommerce iOS version: 9.6 (9.6.0.2)

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by hafizrahman** [comment]
Tried this on release version 17.0 and not seeing the issue anymore. Closing for now.


https://github.com/woocommerce/woocommerce-ios/assets/266376/b8fba527-b55b-4684-8a25-a23ef8bbaeb1
