### ISSUE TITLE
Product Filters corrupts the product storage

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#7464]
# Description

While looking at a [bug](https://github.com/woocommerce/woocommerce-ios/issues/7448), I noticed that we recently introduced some changes on how we treat product searches. Specifically, we delete all other products when we start a product search. 

https://github.com/woocommerce/woocommerce-ios/blob/7c3d2d7a8e686e00a7d67a1c013db0820802123c/Yosemite/Yosemite/Stores/ProductStore.swift#L143-L150

I'm not totally aware on why the change is needed, but this caused some problems on order creation. And also is causing some problems on the main product list.

# Steps

- Open product list 
- Search for a product
- Dismiss Search form without clearing the search
- See the incorrect products in the product list.

# Demo

https://user-images.githubusercontent.com/562080/184453489-b9f86c75-534f-4744-9eda-46ac0b016864.mov

# Next 

@itsmeichigo @pmusolino Do you think it is worth rethinking how are we handling those filters? I'm not sure how other bugs we may cause by deleting the whole product db with each search.

**Comment by itsmeichigo** [comment]
Commented in #7463.

**Comment by Ecarrion** [comment]
Hi @itsmeichigo, let keeps the discussion in here to not deviate from the PR intention.

In general, I think that deleting the stored products is a unsafe thing to do as it can mess with any module that uses products, here is another corrupted state that deleting products has.

- Load all products in the products list screen (there are like 4 pages in the video)
- Go to coupons and filter some products
- Dismiss the coupons flows
- Go back to the products screen and only see one page of products available.

https://user-images.githubusercontent.com/562080/184878519-9fbc9f2b-7b5b-4c91-b0ca-4073a5561e76.MP4

I'm not sure how viable is this, but I'm thinking that doing the filtering and searching in memory could be safer than doing it in the DB layer. 

What do you think?

**Comment by itsmeichigo** [comment]
I'm afraid that searching and filtering in memory will mess up pagination since the actual number of items may not match the expected number of items per page.

We could also return search results immediately without saving them to the local storage, but that means we'll have to handle two ways of displaying data on the product selector screen, and I'm not sure if other issues can happen.

**Comment by itsmeichigo** [comment]
How about querying `ProductSearchResults` for search results instead of `Product` entities? If so, we'll need to add filters to this entity because currently, it has only one property `keyword`.

**Comment by Ecarrion** [comment]
> How about querying ProductSearchResults for search results instead of Product entities? If so, we'll need to add filters to this entity because currently, it has only one property keyword.

That seems like the safest strategy to me!

**Comment by itsmeichigo** [comment]
Turns out this issue can be quickly fixed on the UI layer by combining filters and the search query appropriately. I added the fix in #7528.
