### ISSUE TITLE
Display product images on Product List and Fulfillment screens

### ISSUE THREAD

**Issue by bummytime** [woocommerce/woocommerce-ios#747]
Inspired by the work in https://github.com/woocommerce/woocommerce-android/pull/875 I realized that we only display product images in the Dashboard→Top Performers VC:

![top_perf copy 2](https://user-images.githubusercontent.com/154014/53996006-893e2b80-40fc-11e9-9af6-1a0bbeb88978.png)

However in `ProductListViewController`  and `FulfillViewController` we have product placeholders:

<img width="519" alt="napkin 124 03-07-19 5 16 59 pm" src="https://user-images.githubusercontent.com/154014/53996101-dde1a680-40fc-11e9-9846-860d124eb8d1.png">

Let's see if we can lazily load the images on these 2 screens just like we do on top performers. 😄

**Comment by mindgraffiti** [comment]
This task requires backend work done before images can be displayed. Putting it back in favor of #764.

**Comment by bummytime** [comment]
Just a quick reminder that we will need #818 in place before we can address this issue. 😄
