### ISSUE TITLE
[Mobile Payments] - Greyed out link clickable on Payments

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#7486]
**Describe the bug**
When user doesn't have IPP setup, the `Manage Card Reader` option is greyed out on the Payments icon but it is clickable. Tapping on the `Connect Card Reader` button on `Manage Card Reader` screen currently doesn't do anything (tap on it and nothing happens).

**To Reproduce**
1. Login with a store where IPP is not supported
2. Go to Menu > Payments
3. See that `Manage Card Reader` is greyed out
4. Tap on `Manage Card Reader` - user is redirected to `Manage Card Reader` screen

**Screenshots**

https://user-images.githubusercontent.com/17252150/184797502-635aa35d-bb07-45f4-a834-414d27d095dd.MP4

**Expected behavior**
User shouldn't be able to click on greyed out links

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone Mini 13
- iOS version: 15.5
- WooCommerce iOS version: Alpha version pr7473-ff6d916

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by toupper** [comment]
This fixed with https://github.com/woocommerce/woocommerce-ios/pull/7493
