### ISSUE TITLE
[Mobile Payments] - Typo on error message

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#7487]
**Describe the bug**
There is a small typo on the error message displayed after the onboarding check. It currently reads `In-Person Payments in incomplete`, it should read `In-Person Payments is incomplete`. 

Also not sure if it's just me, but it looks like the "information" icon is a little out of place. I'm using an iPhone 13 mini for testing. @joe-keenan @annchichi can one of you help validate if that's the right position for the icon, screenshot attached below

**To Reproduce**
1. Login with a store where IPP is not supported
2. Go to Menu > Payments
3. See that there is a typo on the error message

**Screenshots**

![typo in message](https://user-images.githubusercontent.com/17252150/184798249-68b10576-0fa0-430f-af6b-89d7b0ce0d2f.PNG)

**Expected behavior**
There shouldn't be a typo on the message.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13 mini
- iOS version: 15.5
- WooCommerce iOS version: Alpha version pr7473-ff6d916

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by toupper** [comment]
Typo fixed on 5f8a119eb208c8e87279bc26f949569f00f034a2 of project prepare for release [branch](https://github.com/woocommerce/woocommerce-ios/pull/7473)
