### ISSUE TITLE
[Mobile Payments] - Card reader manuals screen empty for stores in countries without IPP

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#7488]
**Describe the bug**
Card reader manual link is clickable on Payments menu but is empty for stores in countries without IPP

**To Reproduce**
1. Login with a store where IPP is not supported
2. Go to Menu > Payments
3. Tap on Card Reader Manuals
4. See that screen is empty

**Screenshots**

https://user-images.githubusercontent.com/17252150/184799521-69e20943-a51e-4cb0-b854-de7a962aef9a.MP4

**Expected behavior**
~~Card reader manuals should be displayed since the link is active for the user.~~
After some deliberation, we decided to disable the Card Reader Manual cell on iOS if the country is not supported by IPP. If the country is supported it is enabled, even if they didn’t finish the onboarding. That way the user won't see an empty list.
More info: https://github.com/woocommerce/woocommerce-ios/pull/7501

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13 mini
- iOS version: 15.5
- WooCommerce iOS version: Alpha version pr7473-ff6d916

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by iamgabrielma** [comment]
Removing the priority tag as this does not happen on production, is a side-effect of this project https://github.com/woocommerce/woocommerce-ios/pull/7473

Ref: pdfdoF-1aF-p2
