### ISSUE TITLE
Orders list navigates to the first order after store switch

### ISSUE THREAD

**Issue by ealeksandrov** [woocommerce/woocommerce-ios#7495]
## Description
When a filter applied on the orders list, switching stores triggers navigation to the first order from that filtered list.

## Video
https://user-images.githubusercontent.com/3132438/184934915-2a164654-0555-4d69-906d-3ef7e8f0b619.mp4

**Comment by itsmeichigo** [comment]
Added the split view tag because this is probably related.

**Comment by hafizrahman** [comment]
This is not happening anymore in my test. I'm closing for now, we can reopen if there's new reports.

My test:

https://github.com/woocommerce/woocommerce-ios/assets/266376/efe7d637-606b-414b-a79e-11e59bb527de
