### ISSUE TITLE
Custom Status Extension: Deleting a status on the web can cause issues in-app

### ISSUE THREAD

**Issue by bummytime** [woocommerce/woocommerce-ios#752]
_This may not be a high priority but I wanted to note it here._ 

If the WC store has the [custom status extension](https://wordpress.org/plugins/custom-order-statuses-woocommerce/) installed and the user delete's a status on the web (without a fallback): 

<img width="744" alt="Napkin 126 03-08-19, 2 11 02 PM" src="https://user-images.githubusercontent.com/154014/54053168-0ecce480-41ac-11e9-9b51-81c98a2a496e.png">

we see that the orders with that status disappear from the web orders screen but still appear in the mobile app:

<img width="838" alt="Napkin 125 03-08-19, 1 52 45 PM" src="https://user-images.githubusercontent.com/154014/54052290-aaa92100-41a9-11e9-97fd-73e611b809a8.png">

The reason for this is that `/orders` endpoint still sends back "deleted" orders (also with the removed order status). Interestingly Calypso also displays the orders much like the mobile app (which makes sense given it uses the same API we do):

<img width="744" alt="Napkin 127 03-08-19, 2 18 24 PM" src="https://user-images.githubusercontent.com/154014/54053516-1d67cb80-41ad-11e9-9791-c49225263a39.png">

It's also worth noting that the affected orders are not in the web's trash either.

Setting aside the limbo state of these orders, we can see an immediate impact in the app when trying to load these phantom orders:

![whats_up_status](https://user-images.githubusercontent.com/154014/54053678-a7b02f80-41ad-11e9-8c87-8d471fb18315.gif)

**We should consider what to do in these situations** → perhaps have a default `Status doesn't exist` fallback if we cannot match an specific order's status to the current master list of statii. @kyleaparker @astralbodies @mindgraffiti any thoughts on this?

FWIW there are other [WC status management extensions](https://woocommerce.com/products/woocommerce-order-status-manager/) to potentially investigate with all this.

Also pinging @AmandaRiu because I am assuming this affects WooAndroid as well. 😄

**Comment by bummytime** [comment]
One more note: the deleted statuses are defaulting to `Processing` visually. The good news is that they are **not** included in the Dashboard's pending order count or `Processing` filter on the order details screen:

<img width="790" alt="Napkin 128 03-08-19, 2 46 13 PM" src="https://user-images.githubusercontent.com/154014/54054964-3a9e9900-41b1-11e9-8c1c-2b12bae6d88d.png">

**Comment by bummytime** [comment]
**Update:** @mindgraffiti  addressed the "defaulting to processing status" ☝️ issue in #755. We now display the status' slug (from the order) if we can't find the friendly name in the site's current status list.

**Comment by kyleaparker** [comment]
If the order status is removed, can we exclude them from the list? Other than a deleted order, what other scenarios could cause an order status to not exist?

**Comment by bummytime** [comment]
@kyleaparker  

> If the order status is removed, can we exclude them from the list? 

We can consider doing that...but my gut tells me it would mostly require a lot of a lot of hacks to make it work properly across the app. Additionally, while the app would match wp-admin, it would also differ with what Calypso is displaying.

I think there is a more fundamental issue here → the mobile apps' source of truth is the API and we cannot trust it (in this situation) because of specific extensions. 

> Other than a deleted order, what other scenarios could cause an order status to not exist?

At this point I am not sure — we would have to research it more.

**Comment by mindgraffiti** [comment]
Possibly related issue: https://github.com/woocommerce/woocommerce-ios/issues/291

**Comment by pmusolino** [comment]
This is no more an issue. If a status is deleted, now the status of the orders will be updated correctly.
