### ISSUE TITLE
[Mobile Payments] Show new `Retry` notice after `Retry` tap, if COD activation failed again.

### ISSUE THREAD

**Issue by pachlava** [woocommerce/woocommerce-ios#7559]
From #7556, [this comment](https://github.com/woocommerce/woocommerce-ios/pull/7556#issuecomment-1225538247):

> I was testing on a real device not connected to Charles/Proxyman, and noticed one thing: once I get to the COD screen, and switch to airplane mode, and try to enable COD, I see the notice with Retry button. But after tapping Retry, it visually looks like nothing happens - is this because the new notice won't be shown instead of the old one, if the old one is still there? (if yes - do you think it makes sense to show a new notice instead of the old one, to let the merchant know that there was an attempt, but it did not succeed?)

> Thanks @pachlava. Yes, that sounds like exactly the reason. I'll have a play with removing the notice when the user taps retry.
>
> I think that iteration 1 could ship without a fix for this: do you agree? If so, I'll do it once everything else for iteration 1 is done.

**Comment by joshheald** [comment]
@pachlava I've done a bit of a check on this. 

Tapping the action button on any notice already dismisses the notice, so we already do that. We also start the spinner up again, which would have been stopped when the failure notice was shown, so there's two things feeding back to the user that stuff is happening.

I think that with Airplane mode on, the attempt to display a new notice collides with the old notice not having finished dismissing. That means that the noticePresenter rejects it, for having the same content as the outgoing notice, but continues dismissing the original notice. 

Here's what it looks like for a more realistic network error, which takes a little time to come back:

https://user-images.githubusercontent.com/2472348/186656253-71b9a212-77f5-4969-927f-b2223ebd0291.mp4

So I don't think there's any need to make changes to that.

For contrast, here it is using Airplane mode:

https://user-images.githubusercontent.com/2472348/186657353-69c57d6b-49e0-45a3-b624-8035fdcf2765.mp4

Given that the airplane mode messaging is taken care of by the offline notice that you get at the start of onboarding, and probably prevent the user even getting to this screen, I don't think we need to polish it any further.

Closing this issue, but do re-open if you disagree or if I'm missing something 😊

**Comment by pachlava** [comment]
> Closing this issue, but do re-open if you disagree or if I'm missing something 😊

Thank you for spending time exploring the situation @joshheald 🙂 
I agree that it's fine to keep it in the current state.
