### ISSUE TITLE
Order Details: Order status label loses it's border when pulling-to-refresh

### ISSUE THREAD

**Issue by bummytime** [woocommerce/woocommerce-ios#756]
Just a minor visual nit I noticed while testing out the order details screen:

![order_status](https://user-images.githubusercontent.com/154014/54058917-ec8f9280-41bc-11e9-8840-8747db2b2c96.gif)

During the first load of order details, the status view renders correctly. However, when refreshing the order details screen the status view loses it's border and becomes rectangular. This issue occurs with any status (custom or default) anywhere the order details screen is displayed (via order list, order search, or notifications).

**Comment by mindgraffiti** [comment]
Yes! This bug has been plaguing me. I know precisely where it happens, but I'm not sure what to do with it. If you remove the clear border in `prepareForReuse`, then the border acts normally in that scenario posted above. The down side is, if I don't remove the border in `prepareForReuse`, then the animated skeleton class will give spoilers and show the color border for the payment status labels.
