### ISSUE TITLE
[Sign in with store credentials] Stuck after entering credentials for account not connected to Jetpack

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#7629]
**Describe the bug**

This issue occurs in the following situation:

1. I have a WooCommerce store with an admin that installed and connected Jetpack.
2. There are other accounts on the store that are **not** connected to Jetpack.

If I try to use the store credentials to log in to one of the non-Jetpack-connected accounts, I get stuck with an endless spinner and no way to cancel the login attempt.

**To Reproduce**
1. Start with a store that is connected to Jetpack.
4. Add a new admin or shop manager account to the store (at `/wp-admin/user-new.php`), but don't connect that account to Jetpack.
5. In the app, while logged out, select "Enter your store address".
6. Enter your store address and tap "Continue."
7. Select "Sign in with store credentials."
8. Enter the store credentials for the new account that is not connected to Jetpack.
9. Notice a spinner appears but it never finishes, and there is no back button. The other links on the screen ("Help" and "Reset your password") work but don't offer any way to go back or start over.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/187891257-2a1e925c-1875-4efa-82f1-c54ab7541b20.PNG" width="300px">

**Expected behavior**

If I enter store credentials for an account that isn't connected to Jetpack, I expect to see some kind of error or message explaining how to connect Jetpack for that account.

**Comment by rachelmcr** [comment]
@selanthiraiyan FYI it looks like this is a case that wasn't identified when Sign in with Store Credentials was added in https://github.com/woocommerce/woocommerce-ios/issues/7298.

**Comment by selanthiraiyan** [comment]
> @selanthiraiyan FYI it looks like this is a case that wasn't identified when Sign in with Store Credentials was added in #7298.

I will take look. Thanks for logging this issue, @rachelmcr . 🙏

**Comment by selanthiraiyan** [comment]
To test this, I created a JN site and added a new `otherdemo` user and didn't connect Jetpack for `otherdemo`

<img width="1000" alt="OtherDemoJPConnection" src="https://user-images.githubusercontent.com/524475/188045621-415eea42-fdc7-4cb9-8f6c-f4bdc853210e.png">

Please observe that the highlighted Jetpack icon appears only for `demo` account. It means that JP isn't connected for `otherdemo`


For the above scenario, in version 10.0 (current version from AppStore) we show an error as demonstrated in the following screen recording. 

https://user-images.githubusercontent.com/524475/188045308-30ec11e6-6a68-4ac3-85c7-df2827d48cc0.mp4

@itsmeichigo is working on further improving this experience in https://github.com/woocommerce/woocommerce-ios/issues/7597

@rachelmcr  I believe that this is fixed and the issue can be closed. Please correct me if I didn't follow the testing instructions properly. 🙇

**Comment by rachelmcr** [comment]
Huh, yep, I'm seeing the same thing when I test now; it must have been a glitch with my connection yesterday. Sorry about that!

**Comment by selanthiraiyan** [comment]
Thank you for confirming and closing the issue. 🙏
