### ISSUE TITLE
Order Creation: Apply coupon code

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#7684]
## Description
As a user, I want to be able to apply coupons when creating orders in the app.

## Expectation
- We can add a new row in the order creation form for Coupons underneath the Products section
- When tapping "Apply coupon(s)", the coupon list should be displayed and the user can tap on one or more coupons to apply to the order.

| Order creation form | Coupon list | 
| ----- | ----- |
| <img src="https://user-images.githubusercontent.com/5533851/189032804-8e97451b-9ffa-4109-8a21-b32b0cd8839b.png" width=320 /> | <img src="https://user-images.githubusercontent.com/5533851/189032794-121e84eb-309f-4c4b-9309-32e4578030a6.png" width=320 /> |

Internal ref: p91TBi-8ma-p2

**Comment by ezebecke** [comment]
+1 5597843-zd-woothemes

**Comment by itsmeichigo** [comment]
This was done by #6732.
