### ISSUE TITLE
Enable suspect commits in Sentry

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#7711]
Now that [Sentry SDK in the Tracks library](https://github.com/Automattic/Automattic-Tracks-iOS/pull/224) has been updated to version 7.24.1 we are planning to attempt enabling suspect commits feature in Sentry. 

Enabling suspect commits will help us debug crashes from Sentry. 

https://docs.sentry.io/product/releases/setup/?_ga=2.134957809.1685047512.1656295001-1536868212.1649292338#3-enable-suspect-commits

- [x] Update WC iOS to Tracks '0.12.1-beta.2' release to get Sentry `7.24.1`. https://github.com/woocommerce/woocommerce-ios/pull/7712
- [ ] Follow [Sentry documentation](https://docs.sentry.io/product/integrations/source-code-mgmt/github/) and configure Sentry and Github Enterprise Integration to enable suspect commits.

**Comment by selanthiraiyan** [comment]
After[ updating the Tracks library to the latest version](https://github.com/woocommerce/woocommerce-ios/pull/7712), which also updated the Sentry SDK, I checked the next steps to enable suspect commits.
I noticed that we already have Github integration installed and configured in Sentry. (Ref screenshot below)

<img width="1121" alt="GitHub configured" src="https://user-images.githubusercontent.com/524475/190070414-64fc51c0-2eb7-493e-941a-e1c08f08a945.png">

1. We already have "GitHub Integration" installed and configured. (I believe that GitHub enterprise isn't applicable for this repo)
2. We don't have to make any changes to release management scripts as the above "GitHub Integration" will automatically take care of that process.

As per [this Sentry documentation](https://docs.sentry.io/product/releases/setup/?_ga=2.134957809.1685047512.1656295001-1536868212.1649292338#3-enable-suspect-commits), I believe that I don't have to make any other configuration changes to enable suspect commits.

@mokagio Could you kindly help me confirm the above? Thank you!

**Comment by mokagio** [comment]
@selanthiraiyan from what I understand of the docs, I agree with your assessment.

I also double checked that Sentry is connected with the WooCommerce iOS repo:

![image](https://user-images.githubusercontent.com/1218433/190316734-043aff08-b321-405f-b271-81dda82c292a.png)

**Comment by mokagio** [comment]
I'd wait to close this issue till we see the suspected commits in Sentry.

**Comment by selanthiraiyan** [comment]
>My best guess, is that, despite it being advised as something that works automatically, we have to do it manually instead, via the [sentry_set_commits](https://href.li/?https://github.com/getsentry/sentry-fastlane-plugin/blob/d9a921da05902a35d05cdd78d88e633769926143/lib/fastlane/plugin/sentry/actions/sentry_set_commits.rb) action form the [Sentry plugin for Fastlane](https://href.li/?https://github.com/getsentry/sentry-fastlane-plugin/).

The above is from @mokagio is P2 post - pdnsEh-Id-p2

**Comment by selanthiraiyan** [comment]
Closing this as changes have to be made from the release automation side in order to enable suspect commits in sentry. pdnsEh-Id-p2

This is nothing to be changed from the iOS side.
