### ISSUE TITLE
Login Prologue: feature carousel is still shown after onboarding

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#7758]
The opposite bug of https://github.com/woocommerce/woocommerce-ios/issues/7384

Thanks to @joe-keenan for discovering from the planning meeting!

**Describe the bug**

After introducing conditional login onboarding in https://github.com/woocommerce/woocommerce-ios/pull/7307, the feature carousel should only be shown when launching the logged-out state without the onboarding. After completing or dismissing the onboarding, the prologue screen still shows the feature carousel.

**To Reproduce**
- Reinstall the app if needed in order to see the onboarding
- Skip or complete the onboarding --> notice that the prologue screen still shows the feature carousel

**Screenshots**

<img src="https://user-images.githubusercontent.com/1945542/191854866-3f520dcd-cfd2-46d8-907b-7a0f23b12422.png" width="300" />

**Expected behavior**

The feature carousel should not be shown right after navigating from the onboarding.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: any
- WooCommerce iOS version: 10.4

**Comment by joe-keenan** [comment]
Haha, I didn't realise this was a bug! Thanks for creating an issue for it!
