### ISSUE TITLE
WordPress.com login screen looks off when localized to Spanish

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#7770]
**Describe the bug**

The "What is WordPress.com" string seems to have some leftover formatting and the sign in button looks off.

**To Reproduce**
1. Install the app with your phone language set to Spanish
2. Enter your site address
3. See the screen where the app prompts you to log in with WordPress.com

**Screenshots**
English|Spanish
-|-
![login-en](https://user-images.githubusercontent.com/8739/192261845-53240269-1cf7-4fb1-a8a2-c9020a38061f.jpeg)|![login-es](https://user-images.githubusercontent.com/8739/192261854-b9487557-a69f-4dfa-8daa-e083b0719818.jpeg)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 12 mini
- iOS version: 16
- WooCommerce iOS version: 10.3

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by iamgabrielma** [comment]
I just happened to experience the same:

<img width=450 src="https://user-images.githubusercontent.com/3812076/193156121-052b0e9e-75a7-4840-9c60-69c6144acd45.png">

This comes directly from the Translation project:

<img width="935" alt="Screenshot 2022-09-30 at 07 58 21" src="https://user-images.githubusercontent.com/3812076/193156685-bf1f98af-4bb1-448d-8666-b95af3b700b4.png">

I changed the translation by removing the extra `_` and I believe it should be fine in the next release. Keeping the issue open for the time being so we can double-check it.

**Comment by rachelmcr** [comment]
I just ran across this and noticed the underlines are there in all translated strings. It looks like the translations weren't updated after [this change](https://github.com/woocommerce/woocommerce-ios/commit/ab5ba8bc6d1b95f2067b4c1549edc2bddf83d761).

I just updated [all the translations for this string](https://translate.wordpress.com/projects/woocommerce/woocommerce-ios/-all-translations/836195/) to remove the underline.

The other issue with the button is being tracked in https://github.com/woocommerce/woocommerce-ios/issues/8360.
