### ISSUE TITLE
Error synchronizing orders (Swift.DecodingError) on shipping lines > taxes > ID

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#7842]
**Describe the bug**
Reported in 5619256-zd-woothemes
The app wasn't able to load orders because of the following error:

```
<> Mapping Error: typeMismatch(Swift.Int64, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 4", intValue: 4), CodingKeys(stringValue: "shipping_lines", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "taxes", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "id", intValue: nil)], debugDescription: "Expected to decode Int64 but found a string/data instead.", underlyingError: nil))
```

The order's `shipping lines > taxes > id` is expected to be an int, but an empty string is returned instead.

**Mobile Environment**
Please include:
- WooCommerce iOS version: 10.5.0.1

**List of active plugins**

Requested SSR if the plugin conflict testing doesn't work.
<details>
```
  | Terms & Conditions Connector of IT-Recht Kanzlei |   |   | ✖️️
  | Contact Form 7 |   |   | ✖️️
  | CookieYes \| GDPR Cookie Consent |   |   | ✖️️
  | Disable Comments |   |   | ✖️️
  | Facebook for WooCommerce |   |   | ✖️️
  | FameTheme Demo Importer |   |   | ✖️️
  | Jetpack |   |   | ✖️️
  | Klarna Payments for WooCommerce |   |   | ✖️️
  | OnePress Plus |   |   | ✖️️
  | Page Builder by SiteOrigin |   |   | ✖️️
  | German Market |   |   | ✖️️
  | WooCommerce PayPal Payments |   |   | ✖️️
  | WooCommerce Product Stock Alert |   |   | ✖️️
  | WooCommerce Shipping & Tax |   |   | ✖️️
  | WooCommerce

```
</details>

**Comment by kean** [comment]
The same issue was reported in 6304204-zd-woothemes. The user has 43 installed plugins.

It may be worth adding some defensive code and supporting both Int and String as the ID. It's not uncommon for large integers to be encoded using numbers. The user is reporting that the orders _are_ loading on Android, so presumably they support strings as IDs. 

```swift
public struct ShippingLineTax: Decodable, Hashable, GeneratedFakeable {

    /// Tax ID for shipping item
    ///
    public let taxID: Int64
```

**Comment by rachelmcr** [comment]
Closing as this should be handled by the changes in https://github.com/woocommerce/woocommerce-ios/pull/9844.
