### ISSUE TITLE
Settings: Cells on Settings screen can pick up wrong styles (red, centered)

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#785]
**Describe the bug**

This is a relatively minor, inconsistent visual bug:

While navigating between the app Settings and Privacy Settings sections, it's possible for cells on the Settings screen to pick up the wrong styles. Instead of being left-aligned with black text, they become center-aligned with red text like the "Log Out" cell.

**To Reproduce**
I haven't come up with completely consistent steps to reproduce, but this general sequence of steps should reproduce the behavior:
1. On the My store tab, tap the gear icon to open Settings.
2. Scroll down on the settings screen.
3. Open the Privacy Settings section repeatedly (Settings > Privacy Settings > Back to Settings > Privacy Settings, etc.).
4. Eventually, some or all of the cells will pick up the wrong formatting.
5. Go back to the My store tab and reopen Settings. The cells will revert to the correct formatting.

**Screenshots**

Screencast: https://cloudup.com/cT_Qwc6aAiD

![2019-03-13 18 15 37](https://user-images.githubusercontent.com/8658164/54434607-97a4cc80-4726-11e9-9871-9146caf767d9.png)

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 12.1.4
- WooCommerce iOS version: 1.4.0.0 (TestFlight beta)

**Comment by rachelmcr** [comment]
I'm adding this to Groundskeeping since it feels like more of a maintenance issue, but also cc @mindgraffiti @bummytime since I see you've both worked on the Settings view controller and might have ideas on this.

**Comment by mindgraffiti** [comment]
@rachelmcr that would be my bug. Looks like styles aren't properly resetting on text inside of a re-used cell.
