### ISSUE TITLE
Settings: text on the licenses screen is not localized

### ISSUE THREAD

**Issue by bummytime** [woocommerce/woocommerce-ios#786]
The [copy on the licenses screen](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Resources/HTML/licenses.html) isn’t localized, so it’s always in English:

![Simulator Screen Shot - iPhone XS - 2019-03-15 at 10 39 04](https://user-images.githubusercontent.com/154014/54443414-910a5b00-470e-11e9-9a82-7d2182da2090.png)

Since this is a HTML file, we may have to rethink how to render this screen.

/cc @rachelmcr

**Comment by mindgraffiti** [comment]
Closing as the majority of licenses are plain text or markdown, and none are translated.

Ref:
[WPiOS](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/LICENSE) | [Calypso](https://github.com/Automattic/wp-calypso/blob/master/LICENSE.md) | [WooCommerce Core](https://github.com/woocommerce/woocommerce/blob/master/license.txt)
