### ISSUE TITLE
iOS 15 deprecation warnings: UIApplication.windows

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#7882]
After merging https://github.com/woocommerce/woocommerce-ios/pull/7851, which drops support for iOS 14, there are a few new warnings related to us trying to access `UIApplication.windows`.

This is mostly used on a reimplementation of `currentKeyWindow`, which was deprecated in iOS 13. We'll need to eventually invest some time in adapting the existing hacks to window scenes, or removing them altogether.

**Comment by mokagio** [comment]
#8327 provides an attempt to silence the warning by updating the re-implementationt.

> We'll need to eventually invest some time in adapting the existing hacks to window scenes, or removing them altogether.

Good point. @crazytonyli made a [similar remark](https://github.com/woocommerce/woocommerce-ios/pull/8327#discussion_r1041648552). 

> Maybe it's time to stop relying on the no longer true concept that there is one "key window" across the whole application?

I had a quick look at online and on the docs and found the following, which might be useful to start the work:

- So far, [only iPadOS and macOS support multiple windows](https://developer.apple.com/documentation/uikit/uiscenedelegate/supporting_multiple_windows_on_ipad)
- The concept of key window is still pretty much valid, as proved by the `[keyWindow](https://developer.apple.com/documentation/uikit/uiwindow/1621612-keywindow?language=swift)` property and `[makeKeyAndVisible()](https://developer.apple.com/documentation/uikit/uiwindow/1621601-makekeyandvisible?language=swift)` method on `UIWindow`. From the docs, "In iOS 15 and later, the value of this property is YES when the window is the key window of its scene. [...] Only one window at a time may be the key window." `UIScene` also has a [`keyWindow`](https://developer.apple.com/documentation/uikit/uiwindowscene/3750932-keywindow?language=swift) property.
- As [this article](https://teng.pub/technical/2021/11/9/uiapplication-key-window-replacement) points, accessing the `first` ([or `last`](https://www.reddit.com/r/iOSProgramming/comments/euu5v7/comment/fgfwfw8/?utm_source=share&utm_medium=web2x&context=3)) element cannot be trusted to give deterministic results
