### ISSUE TITLE
Widgets: Prevent clipping of long numbers

### ISSUE THREAD

**Issue by ealeksandrov** [woocommerce/woocommerce-ios#7887]
## Description
Make sure long numbers don't get clipped. One option is to use [`formatHumanReadableAmount`](https://github.com/woocommerce/woocommerce-ios/blob/45431cd6bdf1c9a84b955b2b60f811df040cdb19/WooFoundation/WooFoundation/Currency/CurrencyFormatter.swift#L193) already used in lock screen widgets.

## Screenshot
<img width="368" alt="Screen Shot 2022-10-19 at 4 52 51 PM" src="https://user-images.githubusercontent.com/562080/196812119-2034c000-9840-4745-b9e6-7e358f2ba87f.png">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
