### ISSUE TITLE
Simplified Login: New unrecognized email address

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#7903]
For the first iteration of the Simplified Login flow, we need to add some changes to the unrecognized email address screen:
- Show this screen when user enters incorrect email address (instead of  the screen about sign up link) 
- The Create an account button should be under a feature flag.
- Add "What is [WordPress.com?](http://wordpress.com/?)" link style button
- Separator lines above and below link-style buttons

<img width="258" alt="Screen Shot 2022-10-24 at 10 30 51" src="https://user-images.githubusercontent.com/5533851/197443300-6a34a700-0d45-4e0c-b45e-01142f959dd4.png">

**Comment by selanthiraiyan** [comment]
**Task breakup**
- [x] UI and flow related changes https://github.com/woocommerce/woocommerce-ios/pull/7954
- [ ] Navigate to store creation flow & Add analytics events https://github.com/woocommerce/woocommerce-ios/pull/7956
