### ISSUE TITLE
Products Onboarding: Template WC-Admin check

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#7922]
The endpoint used for the template product feature is under the `wc-admin` namespace. Such an endpoint can be disabled by blocking WC-Admin with a 3rd party plugin.

We need to make sure we can access that endpoint/namespace before presenting the option to the user to create template products.

**Comment by rachelmcr** [comment]
@Ecarrion I did some additional testing around this and realized that the one plugin I know that blocks WC-Admin ([Disable Bloat for WordPress & WooCommerce](https://wordpress.org/plugins/disable-dashboard-for-woocommerce/)) doesn't actually disable the `wc-admin` namespace. So even with that plugin disabling WC-Admin on the web, we can use the expected endpoint to load template products.

Do you think it's still worth adding this check? It should be fairly straightforward to implement (we can add a check in [`RequirementsChecker`](https://github.com/woocommerce/woocommerce-ios/blob/491104c539cd845db218732b12402aadaa2392ab/WooCommerce/Classes/Tools/RequirementsChecker.swift), similar to the existing telemetry check there) but maybe it isn't really needed.

**Comment by Ecarrion** [comment]
@rachelmcr those are great news! I don't think it is worth adding the check right now if we don't know of a way to consistently block the wc-admin endpoint.

We can always add it later if we identify multiple are experiencing this issue.
