### ISSUE TITLE
Fix SwiftUI issue in `AttributedText`: Publishing changes from within view updates is not allowed

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#7930]
**Describe the bug**

In Xcode 14, a SwiftUI issue surfaced about `AttributedText`:

```
Publishing changes from within view updates is not allowed, this will cause undefined behavior.
```

On this line:

https://github.com/woocommerce/woocommerce-ios/blob/1f4293597bc534b279505c1e6f0aac56ddbb6f3a/WooCommerce/Classes/ViewRelated/ReusableViews/SwiftUI%20Components/AttributedText.swift#L87

This is a known issue in the repo where we adapted the code from: https://github.com/gonzalezreal/AttributedText/issues/23

**To Reproduce**

- Launch the app
- Go to a screen that uses SwiftUI `AttributedText` (e.g. account creation from login prologue, IPP learn more) --> in Xcode 14, notice the issue marked in purple

**Expected behavior**
No SwiftUI issues should appear on every screen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: iOS 16
- WooCommerce iOS version: 10.9

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by kaylanx** [comment]
I fixed the issue on the original library: https://github.com/gonzalezreal/AttributedText/pull/25 it's only a small change if you want, you can apply that change to your code too :)

**Comment by jaclync** [comment]
Thanks a lot for letting us know about the fix @kaylanx! I applied similar changes to our app in https://github.com/woocommerce/woocommerce-ios/pull/7955 🙂

**Comment by kaylanx** [comment]
> Thanks a lot for letting us know about the fix @kaylanx! I applied similar changes to our app in #7955 🙂

@jaclync You're welcome :)  We have modified it for our project too which is how I found the fix, so I thought I'd contribute it back to the repo and saw your comment on it.

I found the solution by watching this video if you're interested: https://www.youtube.com/watch?v=3a7tuhVpoTQ
