### ISSUE TITLE
Product Preview: "Save Draft" Alert

### ISSUE THREAD

**Issue by ealeksandrov** [woocommerce/woocommerce-ios#7945]
## Description

When the new/draft product has unsaved changes, alert the merchant that the product will be saved first.

![board-image](https://user-images.githubusercontent.com/3132438/198082205-027610f5-d088-44f1-8fc6-1b02859f2ea2.png)

Internal ref: pe5pgL-14N-p2

**Comment by Ecarrion** [comment]
We have decided to not do this for now.
