### ISSUE TITLE
Customer Search: Search non-registered Customers

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#7951]
At the moment the Search Customers https://github.com/woocommerce/woocommerce-ios/issues/7741 does not show non-registered Customers when searching ( `/wc/v3/customers/0` will always fail, so we skip mapping the Customer).

We could set some sort of check, where, if the customer is non-registered, perform an alternative fetch via a `searchBy` alternative: https://github.com/woocommerce/woocommerce-ios/issues/7953

Update: Related, changes in the API when customer_id=0 https://github.com/woocommerce/woocommerce/pull/36216

**Comment by iamgabrielma** [comment]
Related, changes in the API when `customer_id=0`:

https://github.com/woocommerce/woocommerce/pull/36216

**Comment by jaclync** [comment]
Non-registered customers show up in the search results in the latest production version 16.6, closing this issue.
