### ISSUE TITLE
[Shipping Label] "Email Customer" button does nothing

### ISSUE THREAD

**Issue by pachlava** [woocommerce/woocommerce-ios#7983]
Reported by @nbradbury during CfT testing.

**Describe the bug**
If the customer address can't be verified during shipping label creation, the app will propose to contact the customer via email / message / call. Tapping on Email option does nothing (also notice that there's no animation when `Contact Customer` is tapped, same for `Open Map`):

https://user-images.githubusercontent.com/73365754/198884786-c47099d0-6db8-45c5-880c-f44c408d9255.MOV

**To Reproduce**
1. Create an order and collect the payment
2. Tap `Create Shipping Label` and fill the `Ship from` data (first screen)
3. Fill the data for `Ship to` screen with semantically valid but non-existing address and tap `Done`
4. Once the `We were unable to verify shippig address...` alert is shown, tap `Contact Customer` and the tap `Email` ~> nothing will happen.

Using `Message` and `Call` works, though.

**Comment by itsmeichigo** [comment]
It seems that we are only navigating users to the Email or Message apps if the device is configured to do either of them. But we are displaying the CTA without that check. 

This can be fixed by checking those conditions before showing the CTAs.

**Comment by reginabally** [comment]
I want to tackle this one!

**Comment by reginabally** [comment]
Hi @pachlava! 👋 

Re: `notice that there's no animation when Contact Customer is tapped, same for Open Map)`. Do you mind clarifying your expectations when tapping the buttons?

If you expect some form of feedback/animation when the buttons are tapped, can you please show a video where we show animation when a button is tapped? Thank you!

**Comment by pachlava** [comment]
Hey @reginabally 👋 🙂 

> Do you mind clarifying your expectations when tapping the buttons?

In the video above, when I'm tapping `Contact Customer` somewhere between seconds 2 and 3, there's no button response to this event, which might make the merchant hesitant is they've really tapped it. My expectation would be seeing something like what's taking place in the same video, a second later, when I'm tapping `Email` button (even though this button does not work, it's still very clear that the tap is taking place) - this button background turning slightly lighter for the moment of tap:

<img width="432" alt="Screenshot 2023-03-01 at 15 07 24" src="https://user-images.githubusercontent.com/73365754/222148161-fc768f4e-cd31-4628-92cc-f42bc4c7f057.png">

Please let me know if this example is sufficient, I'll come up with more if needed 🙂

**Comment by reginabally** [comment]
Thanks for clarifying, @pachlava!

Hi @rachelmcr, referring to [this discussion](https://github.com/woocommerce/woocommerce-ios/pull/8982#issuecomment-1448582675), I didn't see any implementation in the `TopBannerViewModel` to change a button's background color when tapped like the screenshot shown above. Do we have similar handling in the code somewhere that I can refer to?

**Comment by rachelmcr** [comment]
@reginabally You might check out how it's done for buttons like the "Continue" button on the store selector (Menu tab > Switch Store). I know that button has some animation, including changing the button's background color when tapped. (I believe there's similar animation for the buttons throughout the login flow; this styling might come from the shared `WordPressUI` pod.) I can't think of other examples off the top of my head. 🤔 

You can also check out the documentation about how to [configure button states](https://developer.apple.com/documentation/uikit/uibutton#1656634) for `UIButton`, if you aren't familiar with how that works.

But it might also be worth handling this animation as a separate issue. As you noted, we rely on `TopBannerView` for this banner. That view is used in a variety of different places in the app and if we change the button behavior we'll probably want to check that the change works well in various places where it's used.

**Comment by reginabally** [comment]
Thank you, @rachelmcr!

> But it might also be worth handling this animation as a separate issue. As you noted, we rely on TopBannerView for this banner. That view is used in a variety of different places in the app and if we change the button behavior we'll probably want to check that the change works well in various places where it's used.

Yes, I agree this should be handled separately as it may require more thorough testing. I filed an issue here: https://github.com/woocommerce/woocommerce-ios/issues/9032
