### ISSUE TITLE
Notifications: Identify approved vs. unapproved reviews

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#799]
**Is your feature request related to a problem? Please describe.**

When I view my notifications, there’s no indication which of the reviews have been approved and which are not approved.

Could there be a way to distinguish between the two, so that when I’m scanning through my notifications I know which ones I need to take action on?

**Describe the solution you'd like**

In the WordPress app, I also get notifications for new reviews (and comments) and they have a subtle color difference for approved and unapproved reviews/comments. Ideally the WooCommerce app would match the WordPress app in how it communicates approved vs. unapproved status.

**Additional context**

Current view of approved and unapproved reviews in WooCommerce:

![2019-03-19 11 51 50](https://user-images.githubusercontent.com/8658164/54604319-5ec66980-4a3e-11e9-9e3d-4a7d0ab00f78.png)

Same approved and unapproved reviews in WordPress:

![2019-03-19 11 52 19](https://user-images.githubusercontent.com/8658164/54604323-6423b400-4a3e-11e9-96ce-3c092a88e9a3.png)

Matching Android issue: https://github.com/woocommerce/woocommerce-android/issues/912

**Comment by mindgraffiti** [comment]
Moving to current Sprint. Looks work that is related to the Reviews tab

**Comment by mindgraffiti** [comment]
Addressed in PR https://href.li/?https://github.com/woocommerce/woocommerce-ios/pull/1413 for build v.3.1 

New design implemented:
<img src="https://user-images.githubusercontent.com/1062444/72096359-ac6ad600-32df-11ea-9668-f350832d0382.PNG" width="350" />

Example of a review waiting for moderation:
<img src="https://user-images.githubusercontent.com/1062444/72096376-b42a7a80-32df-11ea-9508-bfe933ab2121.PNG" width="350" />

Example of a review that has already been approved:
<img src="https://user-images.githubusercontent.com/1062444/72096385-bab8f200-32df-11ea-9f69-a738ceea0a5b.PNG" width="350" />
