### ISSUE TITLE
[iPad] "Add Product Details" popover briefly jumps when shown

### ISSUE THREAD

**Issue by pachlava** [woocommerce/woocommerce-ios#7990]
h/t @nbradbury for spotting

**Describe the bug**
When `+ Add more details` is tapped in Product Details screen (_on iPad only_), the popover briefly jumps down and then goes back (it's more evident in landscape mode):

https://user-images.githubusercontent.com/73365754/199047267-7e95f9bd-c1a5-4558-8c81-32d040596c6f.mov

**To Reproduce**
1. Use iPad
2. Open Product Details
3. Tap `+ Add more details`

**Expected behavior**
The popup does not jump. Also, its height is just a few pixels shy from not needing to have a scrollbar, so this could be improved as well.

**Mobile Environment**
Please include:
- Device: iPad 9 Gen Sim
- iOS version: 16.0
- WooCommerce iOS version: 11.0.0.0

**Comment by itsmeichigo** [comment]
Closed by #11695
