### ISSUE TITLE
Convert `await -> Result<T, Error>` functions to `await throws -> T`

### ISSUE THREAD

**Issue by mokagio** [woocommerce/woocommerce-ios#8104]
I recently submitted a PR to [address a warning](https://github.com/woocommerce/woocommerce-ios/pull/8099). @jkmassel spotted the method I operated in has signature `await -> Result<Void, Error>`, at which he [commented](https://github.com/woocommerce/woocommerce-ios/pull/8099#pullrequestreview-1177924580) "the use of async -> Result is unfortunate here".

I think what Jeremy is hinting at is that, while evidently compiling correctly, `async` and `Result` are somewhat clashing from a functionality point of view.

## Background on `Result` and asycn/await

Prior to async/await, it was useful to use `Result` in asynchronous method to have a single callback that safely encapsulated both success and failure outcomes:

```swift
func someAsyncComputation(_ onCompletion: Result<Int, Error>)
```

With async/await, we have an alternative pattern available

```swift
func someComputation() async throws -> Int
```

Of course, the option used in the codebase also compiles, but it feels a bit stuck in the middle.

```swift
func someComputation() async -> Result<Int, Error>
```

Here's the difference at call site:

```swift
// Result in closure
someAsyncComputation { result in 
  switch result {
  case .success(let value): ...
  case .failure(let error): ...
  }
}

// async throws
do {
  let value = try await someComputation()
  // ...
} catch {
  // ...
}

// async throws in a function that itself throws to bubble up the error
let value = try await someComputation

// async Result
let result = await someComputation()
switch result  {
  case .success(let value): ...
  case .failure(let error): ...
}
```

Personally, I am a big fan of `Result` and I love seeing it in use. But I think it works best when chaining functional programming style transformations in [railway oriented programming](https://fsharpforfunandprofit.com/rop/):

```swift
result
  .map { ... }
  .flatMap { ... }
  .mapError { ... }
  // etc
```

## Where to go from here

At the time of writing, there are 24 matches for `async -> Result` in the codebase. 

<img alt="image" src="https://user-images.githubusercontent.com/1218433/201458970-e64bc7af-cc5a-43b3-95d2-097a0120c459.png" width=300/>

I sampled them and I don't see us leveraging `Result` in a railway oriented programming way. Example see `loadUsernameSuggestions(from:)` defined as

https://github.com/woocommerce/woocommerce-ios/blob/d0a66f4e85ec7eaf54258f7ac6b22247adb6d2d5/Networking/Networking/Remote/AccountRemote.swift#L16

and used as

https://github.com/woocommerce/woocommerce-ios/blob/d0a66f4e85ec7eaf54258f7ac6b22247adb6d2d5/Yosemite/Yosemite/Stores/AccountCreationStore.swift#L80-L85

We could rewrite this to something like

```swift
return try? await remote.loadUsernameSuggestions(from: base)?.first
```

It's also possible we'll find some calls that ought to remain callback-based and could benefit with `Result` without `async`. 

---

I'd love to hear your thoughts on this. Thanks 😄

**Comment by jkmassel** [comment]
>I think what Jeremy is hinting at is that, while evidently compiling correctly, async and Result are somewhat clashing from a functionality point of view.

Ah yep, sorry 😅

> ```swift
> return try? await remote.loadUsernameSuggestions(from: base)?.first
> ```

My only nit: can we avoid `try?`, instead passing the error to the caller to provide additional information?

**Comment by crazytonyli** [comment]
I'm leaning towards using `throw` here. I do like the error type being part of the function signature, but at the same time it feels more "nature" to me to write a throwing function.

**Comment by koke** [comment]
+1 for async throws. I wanted Result for a long time and was happy when it came to swift, but mostly because we had to rely so much on completion blocks and you couldn’t throw there. It has served its role well, and it will for a while until we replace all completion blocks with async code, but async throws feels like the right way of doing things now

**Comment by mokagio** [comment]
@jkmassel 

> My only nit: can we avoid `try?`, instead passing the error to the caller to provide additional information?

For sure! The original code swallowed the error and I kept the pattern in my example. But the systematic migration from `async -> Result` to `async throws` would be a great occasion to up our game in terms of error handling.

@crazytonyli 

>  I do like the error type being part of the function signature

Yeah, me too. Even though, since `Result` started allowing using the generic `Error`, I've noticed less precision in the type of error used within it.

I found [this discussion regarding "typed throws"](https://forums.swift.org/t/typed-throws/39660/187) but it looks stale 😞

**Comment by mokagio** [comment]
I updated the title from a question to a command, to reflect the decision that has been taken.
