### ISSUE TITLE
[Analytics Hub] Integrate UI and Yosemite layers to fetch real order stats data

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#8189]
We should make two stats requests for Analytics data: one for the current selected period and the previous selected period.

We have Yosemite support with `StatsActionV4.retrieveStats` to sync the `OrderStatsV4` data used for both the Revenue and Orders cards. This needs to be integrated with the Analytics Hub in the UI layer.

**Comment by ealeksandrov** [comment]
Subtasks:
- [x] Add networking actions
- [ ] Use selected time period as an input+trigger for the data fetch
- [x] Bind the UI of orders and revenue cards to the fetched stats data
