### ISSUE TITLE
XCode 10.2 and Swift 5 support

### ISSUE THREAD

**Issue by bummytime** [woocommerce/woocommerce-ios#819]
XCode 10.2/Swift 5 was released! 🎉 WCiOS blows chunks when building it now. 💥 💣 👎 

![Screen Shot 2019-03-26 at 11 02 30 AM](https://user-images.githubusercontent.com/154014/55013621-77db9700-4fb7-11e9-933b-2ad1334ae548.png)

There are a few of things we need to do in order to support Swift 5/XCode 10.2:
- [x] Address the errors in WordPressShared
- [ ] Address the errors in WordPressKit (a dependency from another WP pod...but we don't really use it for any networking stuff)
- [ ] Address errors in GridIcons
- [x] Address the myriad of warnings
- [x] Verify our toolchain will still work (Hound, circleci, peril, etc) /cc @loremattei

**Comment by astralbodies** [comment]
Zendesk is a blocker too at the moment 😢

**Comment by bummytime** [comment]
> Zendesk is a blocker

very familiar with that phrase at this point @astralbodies 😆

**Comment by loremattei** [comment]
@bummytime as far as I know, the version of Cocoapods that we are using now (1.5.2) doesn't work with XCode 10.2. We need to update it in order to be able to migrate. 
Everything else should be fine (CircleCI already has a XCode 10.2 image and the other tools shouldn't be affected).

**Comment by astralbodies** [comment]
So I went through the Swift 5 conversion today and I don't think we HAVE to update the pods to be able to get the project to compile. I selected the frameworks we have in the workspace only and was able to convert it without an issue (except for the myriad of warnings). I'll get a PR working with this option. cc: @mindgraffiti

**Comment by mindgraffiti** [comment]
Thank you @astralbodies! It didn't even occur to me to try and run the migrator with the pods un-checked. It worked without any errors (lots of warnings though)! I sent a PR and requested you as a reviewer.
