### ISSUE TITLE
[Analytics Hub] Add Top Performers list to Products Analytics card

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-ios#8199]
Depends on #8198 

## Summary
The Product analytics card should now be able to display the Top Performers product list for that period. The list must be displayed right below the main stats card info, displaying for each row the Product icon, name, respective total items sold, and net sales for that period. 

We should use the same data source and endpoints from the Top Performers in the My Store view.

## Designs
![Image](https://user-images.githubusercontent.com/5920403/203630154-05a5c7c5-a782-47f6-84a4-0d7e47c5cdb0.png)

**Comment by ealeksandrov** [comment]
- [x] UI
- [x] data integration
- [x] loading state
- [x] empty/error state
