### ISSUE TITLE
[Analytics Hub] Add Charts support to Orders and Revenue cards

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-ios#8201]
Depends on #8148

## Summary
The Orders and Revenue cards should display a chart showing the respective stat progression through the select date range. This will require us to implement two different tasks:

1. Parse the interval data contained inside the Analytics Hub stats response. Each interval contains subtotal info that should compose a list of values for the Chart and must follow the currently selected date range.
2. Render a chart on the end side of each delta percentage badge. The chart should be rendered following a list of numbers, describing the values of that specific stat through the selected date range span.

## Designs

![Image](https://user-images.githubusercontent.com/5920403/202557935-a87706b1-4424-4ea3-abcc-4247659118a3.png)

**Comment by rachelmcr** [comment]
Accessibility improvements (as suggested in https://github.com/woocommerce/woocommerce-ios/pull/8231#pullrequestreview-1196657622):

- [x] make chart leading aligned on accessible sizes
- [x] allow the chart height to be dependent on the text scale factor

<img src="https://user-images.githubusercontent.com/562080/204397060-79e5f895-c4da-4748-bf49-c7c9a333d8fc.png" width="300px">
