### ISSUE TITLE
Dashboard: Shop Manager has persistent "Unable to load content" error from site stats

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#823]
**Describe the bug**

When I’m logged in to the app as a user with the Shop Manager (not admin) role, on the “My store” tab I see the notice “Unable to load content.” It looks like this is related to the store stats not loading, which shows up in the app logs and with the Visitors data not loading in the stats chart.

Errors in the logs:

```
2019/03/28 12:06:24:673  ⛔️ Dashboard (Site Stats) — Error synchronizing site visit stats: Dotcom Missing Token
2019/03/28 12:06:24:674  ⛔️ Error synchronizing visitor stats: Dotcom Missing Token
```

**To Reproduce**
1. Add a user to your store with the [Shop Manager role](https://docs.woocommerce.com/document/roles-capabilities/#section-2).
1. Log in as that user in a web browser and connect to Jetpack.
1. Log in as that user in the app. Note that there are no warnings or anything to prevent you from logging in to the app with this role.
1. Select the store where you have the Shop Manager role.
1. Visit the "My store" tab. Note that Visitors doesn't load in the chart and you get an error notice.
1. Navigate around the app and confirm that other features work as expected, but the error notice recurs each time you open the My store tab again.

**Screenshots**

![image](https://user-images.githubusercontent.com/8658164/55228290-b076ad00-5211-11e9-89f3-643c51704ece.png)

**Expected behavior**

I expect the app to exclude features that I don't have permissions to use when I log in as a Shop Manager.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 12.1.4
- WooCommerce iOS version: 1.5.0.0 (TestFlight beta)

**Comment by bummytime** [comment]
@rachelmcr Could you try navigating to `https://your.testsiteurl.com/wp-admin/admin.php?page=jetpack&configure=stats` and turning on the following setting:

<img width="758" alt="Screen Shot 2019-04-04 at 2 23 01 PM" src="https://user-images.githubusercontent.com/154014/55582468-36e53000-56e5-11e9-91ab-402870fa20e2.png">

And then test the app to see if that addresses the issue?

**Comment by rachelmcr** [comment]
@bummytime Unfortunately that didn't fully resolve it. I'm no longer getting the errors in the logs about synchronizing stats, but I'm getting a different token error:

`⛔️ Error loading dashboard: Dotcom Missing Token`

And I still see the same symptoms in the UI (visitors count doesn't load and "unable to load content" notice appears).

**Comment by rachelmcr** [comment]
It's possible there's a Jetpack issue at play here. When I save the settings change at `/wp-admin/admin.php?page=jetpack&configure=stats` I can see it's saved there, and I see the change saved in the site's traffic settings at `https://wordpress.com/settings/traffic`.

However, the Stats section under `/wp-admin/admin.php?page=jetpack#/traffic` doesn't reflect that change and it seems to silently fail if I try to change the "Report visibility" settings there. I'm not sure which of these settings pages is the source of truth.

**Comment by aforcier** [comment]
I've opened a patch that should resolve this problem as long as stats are enabled for the Shop Manager in the Jetpack stats screen as indicated above. (The issue was that on WP.com the permissions check didn't support custom roles like Shop Manager.)

The patch is D27500 (currently needs review).

We'll still want to deal with the error notice which is perhaps a bit excessive (this same case just fails silently on WooAndroid, you just see a question mark where the visitors stats number should be) - users will still get an error if stats haven't been enabled for Shop Managers. We might even consider some sort of warning that this is necessary for Shop Managers. But at least with the patch merged we can direct people on what to do to get it working.

**Comment by aforcier** [comment]
`D27500` has been deployed, this should work now once stats access has been enabled for Shop Managers in the Jetpack stats screen.
