### ISSUE TITLE
Create logged in and logged out context A/A tests

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#8235]
We made a recent change to the ExPlat implementation in [this commit](https://github.com/woocommerce/woocommerce-ios/pull/8170/commits/a90b9e5cec8c12d2cb8935ec4bd95dfbe6958af7).

We have to create two A/A tests to check that there is no bias in both logged-in and logged-out contexts.

- [ ] A/A test for logged-in context
  - [ ] Code change - https://github.com/woocommerce/woocommerce-ios/pull/8236
  - [ ] Abacus - 20923-explat-experiment 
- [ ] A/A test for logged-out context
  - [ ] Code change - https://github.com/woocommerce/woocommerce-ios/pull/8237
  - [ ] Abacus - 20924-explat-experiment

**Comment by selanthiraiyan** [comment]
Closing as we decided to reuse the existing experiment proposals.

**Comment by jaclync** [comment]
There's no way to reuse the experiment name, so reopened the issue for 2 new A/A tests.
