### ISSUE TITLE
Pass `customer_id` when creating new orders

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#8257]
Ref: p91TBi-431-p2

At the moment, as we're not associating these, newly created Orders will present the Customer as a Guest, which is not correct if the Customer already exists in the store.

<img width=500 src="https://user-images.githubusercontent.com/5845095/204530435-81fe9e85-4915-411d-a5d7-411451e448fa.png">

When creating an order for a predefined customer, we should pass `customer_id` in the request. This will assert the correct association between the customer and the order.

**Comment by jaclync** [comment]
Hi @iamgabrielma 👋 are you working on this issue? If not, I might take a look at this since it can help with store analytics/marketing on customers.
