### ISSUE TITLE
[Mobile Payments] "You have a new order" toast in Tap on Mobile IPP flow

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#8274]
> 4. On existing WCiOS, there is another toast that appears before Order Completed, but I don't see it on this build anymore (Screenshot from WCiOS v11.3): 
> <img src="https://user-images.githubusercontent.com/17252150/203918535-c470f461-f1f7-4a45-9cf8-6715e44e231c.PNG" width="380" height="800">

_Originally posted by @jostnes in https://github.com/woocommerce/woocommerce-ios/issues/8196#issuecomment-1327088371_
      

We should add this toast back when the payments refactor is done.

**Comment by joshheald** [comment]
@jostnes This appears to have been fixed by other changes. The video below shows various combinations of TTPoI and Bluetooth readers taking Create Order payments and Simple Payments.

I'm closing this, but if you have time to double check that would be appreciated 😊 


https://user-images.githubusercontent.com/2472348/211013572-f7fb1bc5-388a-46e3-a99e-a10dfa5f930e.mp4

**Comment by jostnes** [comment]
Thanks for the ping @joshheald! I tested this out on trunk but was still able to reproduce it, but I saw that your video has the new designs, so I tried it out on this https://github.com/woocommerce/woocommerce-ios/pull/8358 PR and I can confirm that it's fixed on that PR so should be good once that's merged 👍
