### ISSUE TITLE
[Analytics Hub] View overflows with accessibility fonts

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#8279]
Something has changed in the `AnalyticsHubView` that is making the view to overflow when using the biggest accessibility size.

SC1 | SC2 | SC3
--- | --- | ---
![Image](https://user-images.githubusercontent.com/562080/205075801-d7d9b607-90af-4891-8460-4db715cc1876.png) | ![Image](https://user-images.githubusercontent.com/562080/205075802-e3be2e2b-ed80-44bb-8930-c90a8f2e9a3e.png) | ![Image](https://user-images.githubusercontent.com/562080/205075800-9d983bc1-ff60-4c0c-881b-4ebcc5029e28.png)

**Comment by rachelmcr** [comment]
I bet this is related to the line chart scaling. Right now it scales with a fixed width and height, and the width probably needs to be limited to avoid scaling above the device width.
