### ISSUE TITLE
[Mobile Payments] Cancellation in refactored payment flow announces "order complete"

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#8288]
> 1. "Order completed!" notification appears when transaction is cancelled.
> 
> Steps: 
> - Menu > Payments > Collect Payment
> - Select Tap to Pay on iPhone
> - From the Apple screen, tap X to cancel.
> - If you go to the Orders screen, appropriately shows as "pending payment"

_Originally posted by @lmischner in https://github.com/woocommerce/woocommerce-ios/issues/8273#issuecomment-1334499322_

**Comment by lmischner** [comment]
Another workflow to check when addressing this. I'm not sure if it would need a separate fix.

1. Menu > Payments > Collect Payment
2. Enter value less than $0.50
3. Take Payment > Card
5. See error about value being too small to process
6. Then seen notification that order is complete

**Comment by joshheald** [comment]
@lmischner I believe that this is fixed now, for both sets of repro steps. It was most likely fixed in #8369. If you have time to double check, that would be appreciated....

https://user-images.githubusercontent.com/2472348/211026055-4a3c1404-587f-4c65-abe7-e77a9aeaa434.mp4

**Comment by lmischner** [comment]
Confirmed both workflows are no longer showing an erroneous "order completed" notification. 👍  Thanks, @joshheald !
