### ISSUE TITLE
[Analytics Hub] Track date selection failures

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#8350]
As discussed here: https://github.com/woocommerce/woocommerce-ios/pull/8325#pullrequestreview-1207317761

We should track when date range selection fails, to detect and better understand problems with specific calendars, time zones, and dates. Suggested new event:

* `analytics_hub_date_range_selection_failed` with custom properties:
   * `calendar` prop with the device calendar (`Locale.current.calendar`)
   * `timezone` prop with the device time zone (`TimeZone.current`)
   * `option` prop with the selected date range option (untranslated)

If the date range selection fails, that should give us the information we need to understand why it failed so we can address the issue.

**Comment by rachelmcr** [comment]
@ThomazFB Does this suggested Tracks event look right to you? And just to confirm, this isn't needed on Android because the way dates are handled there means the selection can't fail like this, right?

**Comment by ThomazFB** [comment]
>Does this suggested Tracks event look right to you?

Looks great @rachelmcr! Thanks for moving this forward! Just one question: should we also log the date we're trying to modify with the quarter functions? This could be useful information to reproduce the failure. WDYT? Or is this information contained inside the `selection` parameter already?

>Android because the way dates are handled there means the selection can't fail like this, right?

Actually, it can. The Android Hub is also operating the quarter manually on top of the Calendar API. I think it's at least worth investigating if this can lead to issues there too.

**Comment by rachelmcr** [comment]
> should we also log the date we're trying to modify with the quarter functions?

Tracks events log the date/time of the event as a default event prop, which should be sufficient!

**Comment by rachelmcr** [comment]
One small adjustment: I'll make the custom prop for the selected date range `option` instead of `selection` (for consistency with the `analytics_hub_date_range_option_selected` event).
