### ISSUE TITLE
Change FAQ support link to docs.woocommerce.com page

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-ios#836]
Change the FAQ link in support to point at the iOS documentation at https://docs.woocommerce.com/document/woocommerce-ios/.

@kyleaparker Should we update the copy for that row to not specifically say "FAQ" since this support page isn't a FAQ?

Android issue: https://github.com/woocommerce/woocommerce-android/issues/964

**Comment by AmandaRiu** [comment]
NOTE that in Android we labeled this button **Help Center** and we changed to use the **SUPPORT_HELP_CENTER_VIEWED** tracks event which is what would be used if eventually Help Center pointed to the Zendesk help center. The android PR is [here](https://github.com/woocommerce/woocommerce-android/pull/974)
