### ISSUE TITLE
Shipment tracking: animate in the tracking section smoothly

### ISSUE THREAD

**Issue by bummytime** [woocommerce/woocommerce-ios#837]
On the order details screen, after the shipment tracking data becomes available the entire section pops into view at once:

![shipment_tracking_load](https://user-images.githubusercontent.com/154014/55514671-52d9ca80-562e-11e9-8e56-06c581b7952d.gif)

It would be less jarring if we could smoothly animate in this section.

**Comment by mindgraffiti** [comment]
Closing in favor of #979
