### ISSUE TITLE
Dashboard: Handle JP site stats module being turned off

### ISSUE THREAD

**Issue by bummytime** [woocommerce/woocommerce-ios#838]
JP sites have the ability to turn on and off various JP modules. One of these modules is `Site Stats` which is needed to populate the `Visitors` field on the Dashboard UI. If the module is turned off, the user will see the following error on screen (and the `Visitors` field **could** be blank depending whether we have cached data or not):

![Simulator Screen Shot - iPhone XS - 2019-04-04 at 13 22 38 copy 2](https://user-images.githubusercontent.com/154014/55584175-3ea6d380-56e9-11e9-9c36-d727102b16ea.png)

And on the console, you will see the following:

```bash
2019-04-04 13:22:34.348972-0500 WooCommerce[24105:6167403] ⛔️ Error loading dashboard: Dotcom Error: [invalid_blog] This blog does not have the Stats module enabled
```
At the network-level, the app is making a `GET` request to `/rest/v1.1/sites/133101777/stats/visits/?unit=day&date=2019-04-04&quantity=12&stat_fields=visitors` and receiving a `404` back with the following in the body:

```json
{"error":"invalid_blog","message":"This blog does not have the Stats module enabled"}
```

**Please Note: Order stats is not affected by this issue.**

Finally, one could argue if this is truly a bug or not. Nevertheless I am creating this issue to track it and to gather feedback. At the very least we may want to consider updating the error notice to provide better information to the user.

/cc @astralbodies @AmandaRiu @kyleaparker 

Ref: https://github.com/woocommerce/woocommerce-ios/issues/823#issuecomment-480030540

## To Repro
1. On a JP-enabled site, go to the following URL → `http://your.site.url/wp-admin/admin.php?page=jetpack_modules`

2. Disable the `Site Stats` module:
<img width="561" alt="Screen Shot 2019-04-04 at 2 05 13 PM" src="https://user-images.githubusercontent.com/154014/55585075-6eef7180-56eb-11e9-98ad-125eaf25a1f7.png">

3. Run the app and witness the error in all it's glory:
<img width="778" alt="Screen Shot 2019-04-04 at 3 08 45 PM" src="https://user-images.githubusercontent.com/154014/55585124-8fb7c700-56eb-11e9-8ad1-955dbe533739.png">

**Comment by kyleaparker** [comment]
It might be nice to append a dismissible notification under the stats table letting them know that Visitors is not loading because the stats module is turned off, then they can decide if they want to switch it on or keep it turned off. 

Should we remove the reference to Visitors in the case they choose to leave it deactivated?

**Comment by bummytime** [comment]
@kyleaparker →

> It might be nice to append a dismissible notification under the stats table letting them know that Visitors is not loading because the stats module is turned off, then they can decide if they want to switch it on or keep it turned off.

Seems reasonable to me.

> Should we remove the reference to Visitors in the case they choose to leave it deactivated?

 I guess it depends on what you mean. 😄 Are you talking about something like this:

![3 copy](https://user-images.githubusercontent.com/154014/55747181-4d4efc80-5a01-11e9-8c47-2afa053e4801.png)

**Comment by kyleaparker** [comment]
>I guess it depends on what you mean. 😄 Are you talking about something like this:

Yup exactly!

**Comment by ctarda** [comment]
> It might be nice to append a dismissible notification under the stats table letting them know that Visitors is not loading because the stats module is turned off
@kyleaparker is this an inline notification or the regular toast-like overlay we present at the bottom of the screen? In case it is the toast like overlay at the Botton, should it remain on screen until the user taps it?

**Comment by kyleaparker** [comment]
>@kyleaparker is this an inline notification or the regular toast-like overlay we present at the bottom of the screen? In case it is the toast like overlay at the Botton, should it remain on screen until the user taps it?

This hasn't been designed - I'm not sure if this will be relevant with future stats updates but will add it to the backlog as a design task for now

**Comment by ctarda** [comment]
Thanks @kyleaparker I will move this issue to the TO DO column again.

**Comment by jaclync** [comment]
hey @kyleaparker I'm working on this UI change now hiding the visitor stats field (as in [this screenshot](https://github.com/woocommerce/woocommerce-ios/issues/838#issuecomment-480947715)), and wondering if we do want to show some messaging in the bottom toast to let the user know why the visitor stats is not shown?

**Comment by kyleaparker** [comment]
>I'm working on this UI change now hiding the visitor stats field (as in this screenshot), and wondering if we do want to show some messaging in the bottom toast to let the user know why the visitor stats is not shown?

**Comment by jaclync** [comment]
> Would the toast be dismissible?

Yep I believe we can make a toast dismissible!

> Potentially, although I'm not sure it's necessary as the user would have explicitly disabled the visitor stats in Jetpack.

Yea actually since the site stats module is on by default, and the user has to intentionally disable it, it's pretty obvious that the user is aware of the Jetpack setting.
