### ISSUE TITLE
Stats: Refactor how we store and fetch stats data

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#8441]
# Context

Currently we have two ways of storing and displaying data for stats within our app.

## Dashboard

-  Fetches data from:
    - `StatsActionV4.retrieveStats` 
    - `StatsActionV4.retrieveSiteVisitStats` 
    - `StatsActionV4.retrieveSiteSummaryStats`
    - `StatsActionV4.retrieveTopEarnerStats`

- Stores Data in Core Data

- Shows data from Results Controller

## Analytics Hub

- Fetches data from:
    - `StatsActionV4.retrieveCustomStats`
    - `StatsActionV4.retrieveTopEarnerStats`
    - `StatsActionV4.retrieveSiteSummaryStats` 

- Does not stores data in any storage layer

- Shows data directly from the completion block.

# Problems

- We could have small differences in the duplicated logic that could affect the data available to render.
- `Analytics Hub` does not follow the storage patterns of the app.
- We have duplicated entities to refer to the same stats concepts like `weekly, montly, daily` ranges etc
- We are requesting data each time on the analytics Hub, we could be more more smart and show cached content.

# Potential Solution

- Ideally we would like to have a central hub to request and dispatch data to any consumer.

**Comment by shiki** [comment]
@Ecarrion Would you say this is still valid?

**Comment by Ecarrion** [comment]
@shiki  The problems expressed here are still valid! I think the issue is still relevant if we want to scale or improve the hub further!

**Comment by Ecarrion** [comment]
@toupper I think this issue is still valid but probably "out of our responsibilities" for now. Unless we want to not do anything about it(close it), removing it from our backlog could make it disappear into the void tho! How would you want to treat these kind of issues?

**Comment by toupper** [comment]
@Ecarrion thanks for pinging me here! After some clarification, it's still our responsibility (at least partially). I did some research pe5pgL-5lY-p2 and concluded that we won't be doing that soon, so I will close it for now. We can re-open when we tackle the new Analytics initiative into mobile.
