### ISSUE TITLE
My store tab: a gap between the title and store name in dark mode

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#8499]
**Describe the bug**

This is an issue only in dark mode. When using dark mode, there is a gap between the large title `My store` and the store name. Sometimes it gets truncated, like when the offline banner is shown. When the "add product" banner is shown, it also feels like there could be more spacing between the banner and store name.

**To Reproduce**
- Switch the device/simulator to dark mode if needed
- Log in if needed --> in the My store tab, there is a gap between the title and store name

**Screenshots**

gap | slightly truncated when offline banner is shown | when Add Product banner is shown (maybe more spacing between the store name and banner?)
-- | -- | --
![Simulator Screen Shot - iPhone 14 Pro - 2022-12-28 at 10 32 45](https://user-images.githubusercontent.com/1945542/209891613-5f8ba3f7-085f-4e67-94d6-9e2ab6067ca6.png) | ![Simulator Screen Shot - iPhone 14 Pro - 2022-12-29 at 08 58 03](https://user-images.githubusercontent.com/1945542/209891612-c07cf65f-a1c1-4cc2-b3ee-9c7f5237a842.png) | ![Simulator Screen Shot - iPhone 14 Pro - 2022-12-29 at 08 57 48](https://user-images.githubusercontent.com/1945542/209891605-2c0eedf3-164c-4d54-b400-c6a5b3af07f0.png)

**Expected behavior**

There should not be a gap, probably just need to update the dark mode color at where the gap is.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 14 sim
- iOS version:  iOS 16
- WooCommerce iOS version: 11.8

**Comment by selanthiraiyan** [comment]
This issue is not reproducible anymore. I think this is fixed as part of https://github.com/woocommerce/woocommerce-ios/pull/9254
