### ISSUE TITLE
Order Fulfillment: Allow the user to search and filter shipment providers

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#850]
Add search and filtering to the list of shipment providers

<img width="273" alt="Screenshot 2019-04-09 at 3 44 20 PM" src="https://user-images.githubusercontent.com/2722505/55782211-5f529d00-5ade-11e9-9a01-d9543a5f1a17.png">

**Comment by mindgraffiti** [comment]
Completed in v 1.7
