### ISSUE TITLE
Order Fulfillment: Allow the user to delete package tracking details

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#851]
Allow users to delete shipment trackings
<img width="287" alt="Screenshot 2019-04-09 at 3 45 26 PM" src="https://user-images.githubusercontent.com/2722505/55782289-83ae7980-5ade-11e9-860a-c308a8b705a8.png">

**Comment by mindgraffiti** [comment]
Completed in v 1.7
