### ISSUE TITLE
Duplicate Products: variation properties are not kept

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-ios#8611]
**Describe the bug**
While duplicating variable products, only `attributes` and `regular price` are kept. Other properties like `description`, `image` or `sale price` are not kept. 

**To Reproduce**
1. Have a product with variations and a description under a random variation.
2. Duplicate a product
3. See that description is not present in duplicated product's variation

**Screenshots**
In this reproduction video please look at the attached images. After duplication is finished, all variations use the default, image of a blue shirt.

https://user-images.githubusercontent.com/5845095/211854091-d8d6ef2d-7d66-450b-bfbe-cb3909eae78c.mp4

**Expected behavior**
All fields of variations should be kept in a duplicated product.

**Comment by reginabally** [comment]
👋 I'd like to work on this one.
