### ISSUE TITLE
REST API: Add A/B experiment for logging in with application password

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#8679]
- [x] Update prologue screen to display only entry point to site address login https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/725
- [x] Redirect to WPCom login if detect WPCom site, otherwise show site credential login #8684
- [x] Add new error screen for application password disabled #8684
- [x] Design experiment and post a proposal P2. pbxNRc-2i4-p2
- [x] Track which variant the user is assigned to (pe5sF9-13h-p2) https://github.com/woocommerce/woocommerce-ios/pull/8753
- [x] Replace feature flag `applicationPasswordAuthenticationForSiteCredentialLogin` with the check for the A/B experiment. https://github.com/woocommerce/woocommerce-ios/pull/8744

**Comment by selanthiraiyan** [comment]
A/B test proposal, Abacus and PR work done.
