### ISSUE TITLE
[Variable Product] - Sentence does not reflect what's on the keyboard button

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#8694]
**Describe the bug**
Small nitpicky issue related to a sentence on the "Add options" screen. The sentence reads: `Add each option and press enter` on iOS the `enter` button is `return`

**To Reproduce**
1. Go to Product > Add Product > Add variation > Add attribute > Add option name
2. See that the sentence on the bottom of the Option name field reads `Add each option and press enter`
3. On iOS the `enter` button is `return`

**Screenshots**
<img src="https://user-images.githubusercontent.com/17252150/213348591-399f5d2a-abb6-4a45-becb-629a48b78103.PNG" width="50%" height="50%" />

**Expected behavior**
The text should instead read `Add each option and press return`

**Mobile Environment**
- Device: iPhone 13 mini
- iOS version: 15.7.2
- WooCommerce iOS version: v11.8

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by reginabally** [comment]
👋 I will work on this one.

**Comment by shiki** [comment]
@reginabally I assume this should be closed too because of https://github.com/woocommerce/woocommerce-ios/pull/8783. Thank you!

**Comment by reginabally** [comment]
> @reginabally I assume this should be closed too because of https://github.com/woocommerce/woocommerce-ios/pull/8783. Thank you! 

Thanks for closing this, @shiki! Didn't know I have to manually closing this issue. I learned something new with every PR! 😍
