### ISSUE TITLE
[Variable Product] - Variation list changes every time after refresh

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#8695]
**Describe the bug**
The list of variations changes every time after a pull to refresh. 

**To Reproduce**
1. Go to Products and create a variable product with at least 10 variations
2. Go back to products list and tap to view product > variations
3. Refresh the screen a few times by pulling to refresh
4. See that the list changes on every refresh

**Screenshots**

https://user-images.githubusercontent.com/17252150/213349417-f789bcbe-4873-420b-99b4-1de95c3880f1.MP4

**Expected behavior**
The list should not change after a refresh. 

**Mobile Environment**
- Device: iPhone 13 mini
- iOS version: 15.7.2
- WooCommerce iOS version: v11.8

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by rachelmcr** [comment]
We could update the behavior to match order creation (https://github.com/woocommerce/woocommerce-ios/pull/6427) which sorts first by the `menu_order` property and then by variation ID (in case `menu_order` is the same for all variations).

**Comment by reginabally** [comment]
👋 I'd like to try fixing this issue. Thanks, @rachelmcr for the pointers!
