### ISSUE TITLE
REST API: Migrate all product-related endpoints

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#8715]
For product-related features to work properly with application password authentication, we need to enable REST API for the related endpoints and update related mappers to parse contents without the data envelope:

- [x] ProductAttributesRemote, ProductVariationsRemote, ProductAttributeTermRemote #8736 
- [x] ProductCategoriesRemote #8717
- [x] ProductReviewsRemote #8716 
- [x] ProductTagsRemote #8737
- [x] ProductShippingClassRemote #8739  
- [x] TaxClassRemote #8741

**Comment by selanthiraiyan** [comment]
All product-related migrations are completed.
