### ISSUE TITLE
Track if linked products have been attached

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-ios#8735]
### Description

Currently, we track if the user edited 9 of 10 properties of Product settings (list: pe5pgL-1Ge-p2). The only property left is "Linked products."

Android issue: https://github.com/woocommerce/woocommerce-android/issues/8240

#### The task

Please add a new Tracks event to measure how often the merchant adds linked products. It should follow the same convention as other similar events:
- it should contain `has_changed_data` boolean property
- it should be named `woocommerceios_product_linked_products_done_button_tapped` (or similar)

**Comment by rachelmcr** [comment]
@wzieba I am reviewing this change in https://github.com/woocommerce/woocommerce-ios/pull/8900 and just want to double-check that we need this new event.

Right now, we have the event `woocommerceios_linked_products`. It is fired with the custom property `action: done` when a user taps the "Done" button on the Linked Products screen and there is changed data. (There is a matching event `woocommerceandroid_linked_products` on Android, as well.)

The only differences here seem to be the new event name and also tracking when there isn't saved data. Just to confirm, do we still want this new event or is the existing event sufficient?

**Comment by wzieba** [comment]
hi @rachelmcr , thanks for looking at this. When I reported this issue, I didn't find those two events you mentioned. I'm fine with using them - AFAIK we don't need to track the "no saved data" event. I'll close this issue as "not planned", as well as Android one.

Thanks again for a watchful eye :)
