### ISSUE TITLE
Bulk Editing: Optimistic update

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-ios#8777]
## Description

Copy of https://github.com/woocommerce/woocommerce-android/issues/8270

As soon as the user requests a bulk update on products, we should update the local state (and UI) immediately and optimistically assume that this operation will succeed on the backend.

This approach already works with updates of orders and improves the perception of app performance.

**Comment by Ecarrion** [comment]
Closing this as it doesn't appear to be something we want to work on right now.
