### ISSUE TITLE
[Support Requests] Add support for FAQ suggestions network request

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#8798]
We need to add Network and Yosemite support to the following API for requesting FAQ suggestions.

```
https://public-api.wordpress.com/rest/v1.1/help/qanda?site=woocommerce.com&query=subscriptions
```

**Comment by shiki** [comment]
Same for https://github.com/woocommerce/woocommerce-ios/issues/8799#issuecomment-1516930494. Closing for now.
