### ISSUE TITLE
[Support Requests] Update UI to support FAQ suggestions

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#8799]
This task is still on research phase but the idea is to include a FAQ suggestion list inside the new support form.

![Image](https://user-images.githubusercontent.com/562080/216211234-ce6b7cc6-c806-4a86-9d24-4133a748cdfb.png)

**Comment by shiki** [comment]
This feels like a separate project that needs some consideration. I'm gonna take it out of our scope for now. We can discuss it if it comes up again. Please let me know if I missed some context.
