### ISSUE TITLE
SPE: Present new product screen modally

### ISSUE THREAD

**Issue by ealeksandrov** [woocommerce/woocommerce-ios#8837]
- [ ] add Cancel and Save buttons
- [ ] Save closes the modal and navigates to created product details

<img width=350 src="https://user-images.githubusercontent.com/3132438/218071394-ce0efcb1-5bb4-404b-8f0a-7c2010a6e7ee.png">

**Comment by rachelmcr** [comment]
Brief notes about this implementation:

* `ProductFormViewModel` contains the logic about which action buttons to display in the navigation bar, and what to do when the product is saved remotely, so we can add checks for the feature flag to show only the save button and have it perform the correct action.
* We'll need to make sure the navigation bar is displayed when this view is presented modally, and add the cancel button in that case.
