### ISSUE TITLE
SPE: Move "Product type" option to product settings

### ISSUE THREAD

**Issue by ealeksandrov** [woocommerce/woocommerce-ios#8838]
- [x] Add the product type row to product settings
- [x] The new product type row opens a list selector to select a new product type
- [x] Remove the product type row from product details

product details|product settings
--|--
![Image](https://user-images.githubusercontent.com/3132438/218071777-7c38ff18-6480-401e-a5c4-610d27652da5.png)|![Image](https://user-images.githubusercontent.com/3132438/218071776-edea4a08-976f-4f4a-b3f0-f3d9690c211c.png)

**Comment by rachelmcr** [comment]
* The new product type row can be added in `ProductSettingsRows` and `ProductSettingsSections`, and we can configure whether to show it in `ProductSettingsViewModel.configureSections` based on the feature flag.
* The sections and rows in the product details view are managed by `ProductFormActionsFactory`. This conforms to `ProductFormActionsFactoryProtocol`, so we can add a new actions factory conforming to that protocol to add/remove rows from this view (for this and subsequent tasks). We can define which factory to use, depending on the feature flag, in `ProductFormViewModel`.
