### ISSUE TITLE
Bar charts ordering issue under specific conditions

### ISSUE THREAD

**Issue by jeanregisser** [woocommerce/woocommerce-ios#887]
**Describe the bug**

With the changes done for the custom date range in https://github.com/woocommerce/woocommerce-ios/pull/870 I came across a bug in the way stats items are handled.
What happens is the bar charts are displayed in an incorrect order under specific conditions.

**To Reproduce**

1. Go to the custom tab
2. Edit the range to be 1 year
3. See the stats displayed in the correct order (left oldest, right newest)
4. Edit the range to be 2 years (keeping the same end date)
5. See the stats displayed in an correct order (left newest, right oldest)

**Screenshots**

Incorrect order:

![image (1)](https://user-images.githubusercontent.com/57791/56375103-f2898200-6204-11e9-80db-0433d3c579cc.png)

**Expected behavior**

The stats should always be displayed in the correct order (left oldest, right newest).

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone X
- iOS version: 12.2
- WooCommerce iOS version: (development version)

**Additional info**

Clearing the CoreData store fixes the ordering issue (until you follow similar steps).
I've investigated this to be caused by `handleOrderStatsItems` https://github.com/woocommerce/woocommerce-ios/blob/e554ef9e587fe8ec5ed1b7cbd5bcf9be21d6ab83/Yosemite/Yosemite/Stores/StatsStore.swift#L242-L271

When there's existing data the upsert can cause the original order to be lost.

**Comment by bummytime** [comment]
Ref #842

**Comment by jeanregisser** [comment]
Following the discussion we had on Slack, though it's not the nicest fix, I think I'll apply the same logic done in `handleVisitsStatsItems` https://github.com/woocommerce/woocommerce-ios/blob/e554ef9e587fe8ec5ed1b7cbd5bcf9be21d6ab83/Yosemite/Yosemite/Stores/StatsStore.swift#L209-L225 as it's simple and shouldn't have any unexpected side effect.

**Comment by jeanregisser** [comment]
Adding more context here:

@bummytime suggested using `sort()` at the UI level. I agreed this would be a conceptually better place to fix this. 
However after looking into it, it's more involved than fixing it at the Storage level and hence wanted to favor the simpler fix explained above.

@bummytime also confirmed for this specific part, there would probably be no downside deleting all items first before inserting them.

>> Is there a downside to deleting all items first before inserting? like it’s done for the visits stats?

> For order stats specifically _probably_ not. We have seen issues in the past where removing everything first and then re-adding entities would cause a rendering glitches in FRC-backed tableviews.

**Comment by ctarda** [comment]
Won't fix. This issue is obsolete now, as #934 was closed.
