### ISSUE TITLE
Order fulfillment: Pre-populate custom provider name with search term

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#890]
As pointed out [during the review](https://github.com/woocommerce/woocommerce-ios/pull/885#issuecomment-484661953) of PR #885, the name of the custom shipment tracking provider can be pre-populated with the name of the search term entered by the user when filtering the shipment provider list.

**Comment by mindgraffiti** [comment]
Completed in v 1.9
