### ISSUE TITLE
Dashboard: Support Dynamic Type in Date range picker

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#894]
The horizontal scroller containing the date ranges for the chart does not support Dynamic Type. The font size is fixed.

![Simulator Screen Shot - iPhone 8 - 2019-04-23 at 08 32 05](https://user-images.githubusercontent.com/2722505/56543027-cf632780-65a2-11e9-879f-a15811686bde.png)

**Comment by rachelmcr** [comment]
Confirmed this is still an issue as of version 8.9.0.0:

Default font size|Large font size
-|-
![IMG_9159](https://user-images.githubusercontent.com/8658164/161776939-96e91f74-609b-4315-a862-f32f09f6d834.PNG)|![IMG_9160](https://user-images.githubusercontent.com/8658164/161777015-f37ada72-87e0-4383-90fe-38b203d449ab.PNG)

**Comment by hafizrahman** [comment]
I looked at this issue today and the font size looks dynamic now:

<img src="https://github.com/woocommerce/woocommerce-ios/assets/266376/f629940b-1d2e-44ef-a9ab-e753bc30c454" width="42%"/>

Closing the issue.
