### ISSUE TITLE
[WooCommerce Subscriptions] Display subscription details in the order detail screen

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-ios#8950]
Display Subscription information in the Order Detail Screen. We can use wp-admin design as a reference

![Image](https://user-images.githubusercontent.com/18119390/220819224-10c625eb-de1d-46fc-9716-9619aafb4e7a.png)

**Comment by rachelmcr** [comment]
Android UI, for reference:

Portrait|Landscape
-|-
![Image](https://user-images.githubusercontent.com/8658164/233647236-e7f5bd34-b02b-4330-a7c2-ba50d81092f0.png)|![Image](https://user-images.githubusercontent.com/8658164/233647253-6949c58f-3d7f-464c-aa99-bbab9975d342.png)
