### ISSUE TITLE
[Product Bundles] Display product bundle information in the product detail screen

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-ios#8954]
Display product bundle information on the product detail screen. We can use wp-admin design as a reference

![Image](https://user-images.githubusercontent.com/18119390/221003655-d8745668-bfcd-4832-b6ce-0fd3a574377b.png)

**Comment by rachelmcr** [comment]
A couple notes:

1. We should display the "Virtual" setting in product settings (bundles can be virtual).
2. The bundled products should display whether they are out of stock. Example of an out-of-stock bundled product in wp-admin:

![Image](https://user-images.githubusercontent.com/8658164/222425544-1062fc09-8abe-41f7-8206-b5e5eccac4a6.png)

**Comment by rachelmcr** [comment]
Edit: Right now the Inventory section is not editable for product bundles, and it can't be opened to view its settings. We don't need to make any changes to the UI for now.

~We also need to update the Inventory > Sold Individually setting. For simple products this setting is either enabled or disabled:~

wp-admin|app
-|-
![Image](https://user-images.githubusercontent.com/8658164/222426920-3d0316e9-751c-48ed-821b-e0b18d67af12.png)|<img src="https://user-images.githubusercontent.com/8658164/222426955-fc01528d-b8ad-4cb1-a604-a3ed6864d32b.PNG" width="300px">



~Bundles have several options:~



![Image](https://user-images.githubusercontent.com/8658164/222426504-e7deebc9-6732-4c07-9b3c-091993a9f755.png)
