### ISSUE TITLE
[Composite Products] Display composite product information in the product detail screen

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-ios#8956]
Display composite product information on the product detail screen. We can use wp-admin design as a reference

![Image](https://user-images.githubusercontent.com/18119390/221009366-7a5b6611-7b9e-465a-9d42-d14e632faea1.png)

**Comment by rachelmcr** [comment]
Notes about the UI:

* I'm planning to use a similar approach to Product Bundles, leaving out the setting details and focusing on a list of the components.
* Each component has a title and image we can show in the Components list.
* Each component has component options, which are products or categories offered for the component. We could make the Components list tappable and show a list of its product or category options. We might also show which of those options is set as the default option.

I'll work up a prototype for the UI with those ideas in mind.

Individual component in wp-admin:

![Image](https://user-images.githubusercontent.com/8658164/225941928-a89b0fd3-99fe-482e-a792-098a1f860f16.png)

**Comment by rachelmcr** [comment]
I haven't prototyped anything for this yet, but I noticed that Composite Products also have a [Scenarios](https://woocommerce.com/document/composite-products-advanced-configuration/#scenarios) section in wp-admin:



![Image](https://user-images.githubusercontent.com/8658164/226327676-798cbab9-55be-4abd-aeb6-af1c97307fdb.png)
