### ISSUE TITLE
[Gift Cards] Display gift cards information when applied/redeemed to an order

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-ios#8958]
Display gift cards information when applied/redeemed to an order. We can use wp-admin design as a reference

![Image](https://user-images.githubusercontent.com/18119390/220970704-717ae959-2fe3-4a95-b613-efb0e0655d65.png)

* We should take into account gift cards in the Payment section

**Comment by rachelmcr** [comment]
Android UI, for reference:

| Light mode | Dark mode | Gift card + Subscription
| ------------- | ------------- | - |
| <img width="300" src="https://user-images.githubusercontent.com/18119390/228694703-37188ec3-5324-44fa-8cd1-29912851fd59.png" />  | <img width="300" src="https://user-images.githubusercontent.com/18119390/228694867-cfbad4f4-79fd-4fb4-a392-16439e50d689.png" />  | <img src="https://user-images.githubusercontent.com/8658164/234274561-c663588c-9510-4920-bce7-3fd986a89fd2.png" width="300px"> |

https://user-images.githubusercontent.com/18119390/229206427-eee36529-b7e4-4796-9e5d-1f425b59a04b.mp4
