### ISSUE TITLE
[Min/Max Quantities] Display product min/max settings in product details

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-ios#8960]
Display product min/max settings in product details. We can use wp-admin design as a reference

![Image](https://user-images.githubusercontent.com/18119390/220997658-23dc1286-f725-4ee4-9b66-2d74b0c66bc3.png)

**Comment by rachelmcr** [comment]
Android UI, for reference:

Simple product details|Quantity rules
-|-
![Image](https://user-images.githubusercontent.com/8658164/234809021-8d7857f1-2326-477c-bdf4-2a9c1413d5dd.png)|![Image](https://user-images.githubusercontent.com/8658164/234809035-bfd765c0-ff0b-479b-a9fd-9fd6afbb294b.png)

Variable product details|Product quantity rules|Variation details|Variation quantity rules
-|-|-|-
![Image](https://user-images.githubusercontent.com/8658164/234809178-394328fa-149d-450b-aea3-926e7d09feb0.png)|![Image](https://user-images.githubusercontent.com/8658164/234809560-357403c5-224d-4acf-b8f8-39f2a12af00c.png)|![Image](https://user-images.githubusercontent.com/8658164/234809241-bf8b4793-f470-4d65-9387-976f4e0909da.png)|![Image](https://user-images.githubusercontent.com/8658164/234809575-ef8de09e-d0ee-4cab-84d5-72fcca8b0c61.png)
