### ISSUE TITLE
Dashboard: Add support for Dynamic Type to horizontal scroller for date ranges in top performers section

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#898]
The font size does not change when users select a different font size in the system preferences

![Simulator Screen Shot - iPhone 8 - 2019-04-23 at 08 32 31](https://user-images.githubusercontent.com/2722505/56543518-464cf000-65a4-11e9-953f-91854f571f75.png)

**Comment by rachelmcr** [comment]
The "Top Performers" section no longer has a separate date range scroller. There is still an issue with the date range picker at the top of the screen, which is captured in https://github.com/woocommerce/woocommerce-ios/issues/894.
