### ISSUE TITLE
Scroll behaviour in "My Store" after adding onboarding list

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#9003]
After adding the onboarding list to the "My Store" tab the scroll doesn't work as before.
- At times we cannot scroll at all. 
- We should also check the pull-to-refresh behaviour.

**Comment by jaclync** [comment]
Hi @selanthiraiyan, from the description it feels like what I'm trying to do in https://github.com/woocommerce/woocommerce-ios/issues/8911 to make all the vertical components scrollable including the header view like onboarding or other upsells. The refresh control will be moved to the top of the dashboard view, and propagates to refresh the visible time range tab. Do you think this sounds like the issue I linked? Let me know if there is anything in this issue that isn't covered in the linked issue, and I can add to that one.

**Comment by selanthiraiyan** [comment]
Thanks for the info, Jaclyn! 
This is the same as #8911 . You have covered all the cases in it and I will close this issue now. 👍
