### ISSUE TITLE
[Mobile payments] Cancel button on TTP setup screen not visible with larger font

### ISSUE THREAD

**Issue by lmischner** [woocommerce/woocommerce-ios#9052]
**Describe the bug**
When the system font size is anything larger than the default, the user can't see or interact with the cancel button the TTP setup screen.

**To Reproduce**
1. Update display settings so that system font size is one notch larger than default
2. Go to Settings > Payments > Set up Tap to Pay on iPhone
3. Note you cannot see Cancel button
4. Either rotate to landscape orientation or swipe up on portrait orientation to confirm cancel is indeed there 

**Screenshots**

https://user-images.githubusercontent.com/103850310/223172663-ef60defe-2c9c-4d36-965e-82bf962322ae.MP4

**Expected behavior**
Regardless of font size, I expect to see the cancel button.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS 
- iOS version: 16.0
- WooCommerce iOS version: built from trunk

**Comment by joshheald** [comment]
N.B. this is very sensitive to screen size... and once you hit `.accessibilityMedium` as the type size, the content of this view gets put in a scroll view. I can't fully reproduce it on an iPhone 13 Pro, whereas an iPhone SE will hit this issue even at the default type size.

I'll fix it by putting it in a scrollview at all sizes.
