### ISSUE TITLE
[Free Trial] Add "Subscription" section in settings

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#9056]
# UI 

![Image](https://user-images.githubusercontent.com/5845095/223984377-667e8196-edfc-4609-9460-6112a88b4df0.png)

# Tasks

- [x] Add a new "Plans" section on the menu screen
- [x] Only show it for WPCom sites.

**Comment by wzieba** [comment]
@Ecarrion there's a change regarding this task. We should add a tile in Menu screen. Please see the description of updated Android task: https://github.com/woocommerce/woocommerce-android/issues/8450 and this p2 comment: pe5pgL-2mT-p2#comment-1956
