### ISSUE TITLE
[Free Trial] Fetch subscription state

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#9060]
# Task

- [x] Confirm how and when to fetch the current plan state paYKcK-2JP-p2
- [x] Implement ☝

**Comment by wzieba** [comment]
This comment can be useful p1677596640044849/1677048031.391339-slack-C045CUK1Y3U as well as this PR https://github.com/woocommerce/woocommerce-android/pull/8379
