### ISSUE TITLE
Products: Decoding error loading product variations

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#9070]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

We're seeing a decoding error that causes product variations not to be loaded (tracked by `woocommerceios_product_variants_load_error`):

```
Swift.DecodingError.typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "permalink", intValue: nil)], debugDescription: "Expected to decode String but found a number instead.", underlyingError: nil))
```

In recent weeks we've seen this error affect up to 7 users per day.

This is likely caused by a plugin changing the `permalink` response for product variations.

**Expected behavior**

Rather than failing to decode and load the product variations, we could make the permalink optional or set it to an empty string if we can't decode it, and not show the link to view it in that case.

**Comment by reginabally** [comment]
👋 I'd like to work on this one.
