### ISSUE TITLE
Notifications: Share Store button is clipped

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#909]
The `Share Store` button part of the overlay presented when there are no notifications is clipped

![Simulator Screen Shot - iPhone 8 - 2019-04-23 at 09 25 25](https://user-images.githubusercontent.com/2722505/56545329-db061c80-65a9-11e9-9d50-f03017d07bc1.png)

**Comment by jaclync** [comment]
In cases like this where text is clipped in a button, do we allow multiple lines or let iOS [automatically adjust font size](https://developer.apple.com/documentation/uikit/uilabel/1620546-adjustsfontsizetofitwidth) with [minimum scale factor](https://developer.apple.com/documentation/uikit/uilabel/1620544-minimumscalefactor)?

**Comment by ctarda** [comment]
In cases like this I think we'd go for multiple lines, but @kyleaparker has the final word 😄

**Comment by kyleaparker** [comment]
Yea I would say multiple lines for this, can we get a screenshot of what that would look like?

**Comment by jaclync** [comment]
@kyleaparker yup here are the screenshots with different text alignment:

default (left align) | center align
--- | ---
![Simulator Screen Shot - iPhone SE - 2019-06-19 at 17 33 00](https://user-images.githubusercontent.com/1945542/59809764-0f5b3800-92d0-11e9-8984-e246f2e6810b.png) | ![Simulator Screen Shot - iPhone SE - 2019-06-19 at 17 33 55](https://user-images.githubusercontent.com/1945542/59809765-0ff3ce80-92d0-11e9-8d7c-a67f4fe83767.png)

center align seems a bit more comfortable? also, do you think there could be some horizontal padding around the button?

**Comment by kyleaparker** [comment]
Agreed, let's go with the center aligned version and a little more padding 👍
