### ISSUE TITLE
Coupons: updating filters in product selector have no effect before changing the search query

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#9098]
**Describe the bug**

When updating the filters in the product selector in the coupon form (either adding products or in coupon restrictions), the product results stay the same and don't match the latest filters. After changing the search query, the filters start working. I set the priority as low since coupon management is still behind the feature switch and the filters still work after changing the search query.

🗒️ After taking a look in the code, the issue is from the use of `@Published var` for the filters. In the view model, it observes the combination of the query and `$filters`, but [`self.filters` is used for the product search API request](https://github.com/woocommerce/woocommerce-ios/blob/55fccba12ffe252479c8007cfe138221a2521925/WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModel.swift#L292-L300) after `syncingCoordinator.resynchronize()` is called. For `@Published var`, when the value changes the latest value in `sink` is in `willSet` and access to `self.filters` is getting the old values (better explained in [this blog post](https://www.avanderlee.com/swiftui/published-property-wrapper/#the-importance-of-understanding-the-willset-trigger)). It's a tricky case since the sync callback is separate in the delegate, maybe we can use a subject instead of `@Published var` here.

https://github.com/woocommerce/woocommerce-ios/blob/55fccba12ffe252479c8007cfe138221a2521925/WooCommerce/Classes/ViewRelated/Products/ProductSelector/ProductSelectorViewModel.swift#L467-L473

**To Reproduce**

Prerequisites: the site has at least one product for the filters to work

- Log in if needed
- Go to the Menu tab
- Tap Settings > Experimental Features, enable `Coupon Management`
- Go back to the root of the Menu tab
- Tap `Coupons`
- Tap `+` to add a coupon and select a type
- Tap `All Products` --> the product selector is shown with all products shown
- Tap `Filters`, and add some filters that can change the current results (changing product type is probably the easiest)

What happened: the product results didn't change at all

**Screenshots**

https://user-images.githubusercontent.com/1945542/224257396-13c9f532-e8e2-43fe-95c8-dac0ca9e08d1.mov

**Expected behavior**
The filters should be applied to the product results.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: any
- WooCommerce iOS version: 12.4

**Comment by iamgabrielma** [comment]
Removing the `priority:low` tag as we're reusing this implementation for Product Multi-Selection as well at the moment.
