### ISSUE TITLE
Settings: `Made with Love by Automattic` is covered by the tab bar for large font sizes

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#910]
![Simulator Screen Shot - iPhone 8 - 2019-04-23 at 09 27 33](https://user-images.githubusercontent.com/2722505/56545442-2b7d7a00-65aa-11e9-9ce8-d6f4d9510713.png)

**Comment by jaclync** [comment]
a related potential improvement: perhaps the heart icon above the text could be [a symbol](https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/) that supports dynamic type after the app is iOS 13+ (we can create custom symbols for different sizes)
