### ISSUE TITLE
HACK week: Add coupon to Order

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#9111]
This is a list of pending work and improvements from the hack week project "Add coupon to Order"

Previous PRs
https://github.com/woocommerce/woocommerce-ios/pull/9089
https://github.com/woocommerce/woocommerce-ios/pull/9090

- [ ] It would be nice to allow users to add more than one coupon code.
- [ ] In the coupon adding screen, could we show a list of coupons that they can select from instead of entering coupon codes manually?
- [ ] When an invalid/expired/ineligible coupon code is applied, the order form displays a generic error notice saying the order cannot be updated. We should validate the coupon code beforehand and display more specific errors.
- [ ] It is not safe to assume that an order’s `discountTotal` will match the total of coupon line’s `discount`s. We should compare the coupon codes between the local order and the remote one instead. [Code](https://github.com/woocommerce/woocommerce-ios/pull/9090/files#diff-0667e76ef83e3a4ed8c121e825fa2a1fcc649011939b3755888c8216d1fa8c0eR450-R456) Internal discussion - p1678280360582379/1678264651.362909-slack-C03L1NF1EA3

**Comment by reginabally** [comment]
We have a request in 6088732-zd-woothemes to want to add a coupon to an existing order.

**Comment by toupper** [comment]
Thanks for your great work here @selanthiraiyan! It was very helpful for our Orders with Coupons [project](https://github.com/orgs/woocommerce/projects/155/views/1)

As we have now the project mentioned above, I will go and close this issue to avoid confusion and duplicated work. Let me know if you want to keep it open for other reasons though.

**Comment by selanthiraiyan** [comment]
Thanks for the ping, @toupper! Yes, it makes sense to close this issue. 👍
