### ISSUE TITLE
Unable to refresh list message in "Orders" section on iOS 1.5.0.1 - orders are not loaded

### ISSUE THREAD

**Issue by grigorijurasov** [woocommerce/woocommerce-ios#916]
**Describe the bug**

`Unable to refresh list` message in "Orders" section on iOS 1.5.0.1 - orders are not loaded.

When connecting to the same site via Android app the orders are loaded.

Reported in:

1966949 zen
1980428 zen

**To Reproduce**

1. Get the details from the ticket.
2. SSP via iOS app either on a simulator or on an actual device.
3. Head to "Orders" section

**Screenshots**

![IMG_2134](https://user-images.githubusercontent.com/13084901/56590089-1ecf4500-65ef-11e9-9d54-515177e3b71c.PNG)

**Expected behavior**
I'd expect the orders to be loaded

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone SE
- iOS version: 1.5.0.1
- WooCommerce iOS version: 3.6.1

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by grigorijurasov** [comment]
This isn't happening with iOS app 1.5.0.1 and my own test site though, orders are loaded.

**Comment by melindahelt** [comment]
1986686-zen

**Comment by grigorijurasov** [comment]
1989504 zen

**Comment by grigorijurasov** [comment]
One more: 1987084 zen

**Comment by mindgraffiti** [comment]
I spent some time researching this one.

**The API request used to get orders:** 
https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/{{site_id}}/rest-api/?_method=get&json=true&path=/wc/v3/orders

Can confirm 1987084-zen receives this error:
```
⛔️ Error synchronizing orders: Dotcom Error: [no_response_body] Server could not read response.
⛔️ Order List — Error synchronizing order statuses: Dotcom Error: [rest_invalid_signature] The request is not signed correctly.
```

What's confusing is that 1987084-zen should have been blocked from continuing the login process, because the site ID check shows an error:
```
⛔️ An error occured while fetching API info for siteID {site_id}: Optional(Dotcom Error: [rest_invalid_signature] The request is not signed correctly.)
```

**Comment by mindgraffiti** [comment]
Relevant API request that WCAndroid uses:

https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/fa8ef8b4fb08ce7ee7fc1d95bc5d9b44f1e63083/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderRestClient.kt#L66

**Comment by grigorijurasov** [comment]
1998685 zen - one more

**Comment by mindgraffiti** [comment]
2012067-zen

This has continued to trend. I'm going to inquire if we can create a patch for 1.7.
