### ISSUE TITLE
Store onboarding: reload tasks after dismissing a modal from an onboarding action

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#9172]
Steps to reproduce:

- Log in to a store with pending onboarding tasks that present a modal (e.g. Launch store, Get paid, Customize domain tasks)
- In the My store tab, tap on a pending task that presents a modal
- Complete the task in the modal
- Dismiss the modal

What happened: the onboarding tasks aren't refreshed so that the task is still shown as incomplete until we pull down to refresh or go to another tab then back
Expected: the onboarding tasks should be refreshed after dismissing a modal from an onboarding action

**Comment by selanthiraiyan** [comment]
Reload the task list when the tasks get completed

- [x] Add product - https://github.com/woocommerce/woocommerce-ios/pull/9249
- [x] Customize domains - https://github.com/woocommerce/woocommerce-ios/pull/9249
- [x] Launch store - https://github.com/woocommerce/woocommerce-ios/pull/9249
- [ ] Get paid - ⚠️  This isn't feasible as we are using a web view
