### ISSUE TITLE
Share Store Button doesn't work

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-ios#925]
**Describe the bug**
Tapping on the "Share your Store" button doesn't do anything for me.

**To Reproduce**
1. Go to notifications
2. Tap on "Share your Store"
3. The button registers as tapped, but nothing happens

**Screenshots**
![RPReplay_Final1556225972 MP4](https://user-images.githubusercontent.com/1123407/56768221-01bf8100-676b-11e9-97e6-2c3f3634be27.gif)

**Expected behavior**
I'd expect _something_ to happen?

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone Xs
- iOS version: 12.2
- WooCommerce iOS version: 1.6.0.1

**Comment by ctarda** [comment]
@jkmassel I just tested this on develop and it seems to be working fine. Could you please give it another try with our latest and greatest?

**Comment by jkmassel** [comment]
This seems to work. Not sure how I got into a state where it wasn't.

Closing, thanks @ctarda!
