### ISSUE TITLE
UI does not reflect Product filtering correctly during Order or Coupon creation

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#9256]
The Filter implementation used on `ProductSelectorView` (used currently in Coupons and Product Multi-Selection) doesn't seem to update the UI correctly.

**To Reproduce**

Case 1:
1. Enable Coupons in Experimental features
2. Tap on "Filter" > Make some selection > Tap "Complete"
3. See how the modal view is dismissed but doesn't show filtered items
4. Tap on the search bar, write something, and remove the text
5. See how the Filter is now applied

![Simulator Screen Recording - iPhone Xs - 2023-03-22 at 11 25 27](https://user-images.githubusercontent.com/3812076/226860048-c31a8774-3a6a-45aa-8b03-f169797676c6.gif)

Case 2: 
1. Enable Coupons in Experimental features
2. Tap on "Filter" > Make some selection > Tap "Complete"
3. See how the modal view show filtered items
4. Tap in Filter again and clear it > Tap "Complete"
5. See how items are still filtered despite the filter not being applied anymore

https://user-images.githubusercontent.com/3812076/226871108-1d6edb5a-3c98-4101-9fcd-c23e85adde4a.mp4

**Comment by rachelmcr** [comment]
Is this a duplicate of https://github.com/woocommerce/woocommerce-ios/issues/9098?

**Comment by iamgabrielma** [comment]
> Is this a duplicate of #9098?

That seems to be the case, thanks for the link @rachelmcr . Closing this one.
