### ISSUE TITLE
[Free Trial] Subscriptions title dissapears

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#9281]
The subscriptions title tend to disappear if we change the font size while the app is running.

https://user-images.githubusercontent.com/562080/227375827-09cdf779-4006-41e7-b920-e1a88f8f0f20.mov

**Comment by Ecarrion** [comment]
I tested this with the latest test flight and the latest trunk and couldn't reproduce it.

https://user-images.githubusercontent.com/562080/232652952-953ca345-51f7-4150-9d9a-6ee73a1fe383.MP4

Since changing the font size in the middle of an app run is quite an edge case I'm gonna close this for now.

@rachelmcr If you have time, could you give this a quick test and reopen it if you manage to reproduce it? Thanks in advance!

**Comment by rachelmcr** [comment]
I did a couple quick tests and can't reproduce it!
