### ISSUE TITLE
Store onboarding. Store setup card does not refresh after dismissing popover

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#9302]
**Describe the bug**
When dismissing a popover launched from the Store setup card, the contents of the card do not update, and a pull to refresh is needed.

**To Reproduce**
1. Go to "My store"
<img src="https://user-images.githubusercontent.com/2722505/227807228-72e68f39-dd63-4205-a868-607034464eec.png" width="350"/>

2. Tap any of the items in the card (for example, _tell us more about your store_) 
<img src="https://user-images.githubusercontent.com/2722505/227807318-b906d7a7-cc08-48e9-a289-286618adee5a.png" width="350"/>

3. Fill the forms. In this case, I completed the address, countries shipping to, and added a first product. 
4. Tap Done
5. Notice the card is still showing 0/5 tasks completed
<img src="https://user-images.githubusercontent.com/2722505/227807403-2f026a04-f6ce-4fdd-98f4-98b9df2b4d60.png" width="350"/>

6. Pull to refresh:
<img src="https://user-images.githubusercontent.com/2722505/227807421-c8435252-f28a-499b-8858-488484b51995.png" width="350"/>

7. The task count and the content of the card are updated

**Expected behavior**
The card should update after the popover is dismissed

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by selanthiraiyan** [comment]
Thanks for taking the time to report and log this issue, @ctarda ! :bow_s:

Our strategy is to reload the task when a user finishes it.

* But, for the “Tell us more about your store” and “Get paid” tasks, we use a web view. It is not straightforward to know when these get completed in a web view. 
* For other tasks with native views, we reload the task list when the users finish a task. 

As a workaround, I will try to always reload the task list for these web view tasks.
