### ISSUE TITLE
[Free Trial] Update Site Creation Flow when profiler is enabled.

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#9326]
Profiler questions are currently disabled.

We should make sure the free trial flow keeps working when they get enabled again in the future.

**Comment by wzieba** [comment]
If profiler will be enabled we have to make sure to send profiler answers with the `/ecommerce-trial/add/` endpoint. More internal context: paYKcK-2Pw-p2#comment-2066
