### ISSUE TITLE
Log in with Site URL: Change the sign-in field from username to email

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#935]
Design Feedback: 

> Can we change “WordPress.com username” to “WordPress.com email”? And update any other reference of a username to email? It feels like asking for a username adds to the confusion that this is supposed to be self-hosted credentials.

cc: @kyleaparker 

### To Do
- [ ] On the Site URL sign-in view controller, change the username field to email
- [ ] Find and replace any error message references from username to email
- [ ] Find and replace any UI references from username to email
- [ ] Alternatively, see if we can use WPiOS flow, with the WP.com login view controller that uses email addresses to sign in.

**Comment by shiki** [comment]
This was done a while ago during the UL&S project.
