### ISSUE TITLE
[Free Trial] Release 2nd iteration

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#9389]
We should adjust the feature flags to enable the store creation flow with Free Trial. We need to guarantee that:

- Free Trial flag is set to activate
- Domain picker is not active
- Store Profiler is not active

The Free Trial creation flow should be only:
1. Store Name Picker
2. Summary
3. Creation loading
4. Landing in My Store

**Comment by shiki** [comment]
I attempted to do this. But it looks like there are many decisions involved, like whether we should keep `showDomainSelector`. I would just be blocking everyone, especially since I'll also be AFK tomorrow. So, I'll just let you handle this, @ThomazFB . 😁

**Comment by ThomazFB** [comment]
@shiki Just for context and documentation, we need to guarantee that:

- Free Trial flag is set to true
- Domain picker is not activate
- Store Profiler is not active

The Free Trial creation flow should be only:
1. Store Name Picker
2. Summary
3. Creation loading
4. Landing in My Store

**Comment by shiki** [comment]
Yep. My concern was with what to do with the code itself. That's why I thought it's better if you took care of it. 😅
