### ISSUE TITLE
Networking: Invalid Token Handler

### ISSUE THREAD

**Issue by jleandroperez** [woocommerce/woocommerce-ios#94]
Update the the Networking layer so that any Authentication Error is properly parsed, and relayed thru a common channel.

**Comment by shiki** [comment]
I'll close this for now and we can reopen if we see reports of unclear login errors.

**Comment by jleandroperez** [comment]
Quick note on this one sir!

The goal of this ticket was to handle the "Token Invalidated" scenario (not standard login errors).

**Comment by jleandroperez** [comment]
(That being said, it's been open for 2 years without activity, definitely good to close!!!)
