### ISSUE TITLE
Flaky unit test `ProductStoreTests.test_retrieveRecentlySoldCachedProducts_when_there_are_several_sold_products_returns_them_sorted`

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#9406]
When checking the merge commit in `trunk`, I noticed a [unit test failure on `ProductStoreTests.test_retrieveRecentlySoldCachedProducts_when_there_are_several_sold_products_returns_them_sorted`](https://buildkite.com/automattic/woocommerce-ios/builds/12396#018769bb-d5bc-4866-a41d-8a130aaacb92). This test was updated recently on April 4.

I couldn't reproduce the test failure when running the test class or the test suite locally. But if I added the following code to run `ProductStoreTests` 20 times in the YosemiteTests test suite, it crashed consistently locally.

```swift
override func invokeTest() {
    for _ in 0...20 {
        super.invokeTest()
    }
}
```

Crash stack trace:
```
Thread 10 Queue : NSManagedObjectContext 0x60000a2e81a0 (serial)
#0	0x000000018002ec14 in objc_msgSend ()
#1	0x000000018451b7b8 in -[NSManagedObjectContext _dispose:] ()
#2	0x000000018451b3c8 in -[NSManagedObjectContext _dealloc__] ()
#3	0x0000000184534500 in __internalBlockToDeallocNSManagedObjectContext_block_invoke ()
#4	0x0000000184527f34 in developerSubmittedBlockToNSManagedObjectContextPerform ()
#5	0x0000000180135768 in _dispatch_client_callout ()
#6	0x000000018013d7f8 in _dispatch_lane_serial_drain ()
#7	0x000000018013e43c in _dispatch_lane_invoke ()
#8	0x000000018014a624 in _dispatch_workloop_worker_thread ()
#9	0x00000001af2568fc in _pthread_wqthread ()
```

It looks like it's crashing when trying to deallocate the Core Data context.

**Comment by jaclync** [comment]
I briefly tried tearing down the variables in the test class, the crash didn't happen for the first run but continued to happen in subsequent runs:

```swift
override func tearDown() {
        network = nil
        storageManager = nil
        dispatcher = nil
        super.tearDown()
}
```

(this is when overriding `invokeTest` to run `ProductStoreTests` 20 times)

**Comment by toupper** [comment]
Thanks for the investigation @jaclync 

For now, I created a [PR](https://github.com/woocommerce/woocommerce-ios/pull/9408) disabling it until I have time to find the root issue causing the problem 👍

**Comment by Ecarrion** [comment]
@toupper should we close this issue?

**Comment by toupper** [comment]
@Ecarrion Yes let's close this one as it's not applicable anymore.
