### ISSUE TITLE
Order Fulfillment: Store locally custom tracking providers entered by the user.

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#945]
At the moment, when a user adds a custom shipment tracking, the name and url of the custom shipment tracking are not stored neither on the backend nor the app.

This matches the behaviour on web.

However, for a user in a country that is not included in the list of shipment tracking provided by the plugin API (i.e. Hong Kong) adding shipment trackings will require entering the name and url of their favourite provider again and again, order after order.

We could explore storing that information locally and pre-populating the form used to enter custom trackings with those values:
![Simulator Screen Shot - iPhone 8 - 2019-05-09 at 14 19 18](https://user-images.githubusercontent.com/2722505/57431471-80d1b080-7265-11e9-80c8-b72fc2ded007.png)

**Comment by mindgraffiti** [comment]
Completed in v 1.9
