### ISSUE TITLE
Dashboard: Dates on weekly charts can be confusing due to using Sunday as the start of the week

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#948]
**Is your feature request related to a problem? Please describe.**

Currently, in weekly charts the week begins on Sunday, because in the [DateFormatter helper](https://href.li/?https://github.com/woocommerce/woocommerce-ios/blob/02ab02fc6b9c8c76086f488c69944d6cd999e378/WooCommerce/Classes/Extensions/Date%2BHelpers.swift) we’re setting these charts to always use a US locale (which starts the week on Sunday). However, not all locales use Sunday as the start of the week, which can cause confusion when looking at the weekly chart.

For example, with locales that begin the week on Monday, the last date on the chart (a Sunday) looks like the end of the previous week. This makes it seem like the chart is missing the current week's data.

![2019-05-10 14 55 50](https://user-images.githubusercontent.com/8658164/57532626-e7250480-7333-11e9-876f-db3c5e59c624.png)

**Describe the solution you'd like**

Instead of hard-coding the US locale for the date formatter, we could use the device locale or the user's country from their Site Settings to determine when the week starts for weekly stats.

**Describe alternatives you've considered**

Another option, if possible, could be to get the "Week starts on" setting from the site (set in WordPress under Settings > General) and use that.

**Additional context**

This confusion was raised during beta testing for WCiOS 1.8. h/t @poojashetty18 for the original report.

**Comment by mindgraffiti** [comment]
@jaclync can you confirm this bug is fixed in StatsV4?

**Comment by jaclync** [comment]
Right now, we show Sunday as the first day of week on "This week" chart for stats v4. I just checked on WC admin for sites in the US (week starting on Sunday) and in Taiwan (week starting on Monday), and both sites show "Week to date" chart starting Monday of the week. Does it make sense to update the app to show Monday as the beginning of week, if more businesses operate from Monday regardless of the first weekday (would it work for businesses that operate on weekends like restaurants/workshops)?

I also did some research on how to get the first weekday per device, and we can get the first day of the week from the calendar locale on the device by [`Calendar.firstWeekday`](https://developer.apple.com/documentation/foundation/calendar/2293656-firstweekday). This seems like a good alternative?

**Comment by mindgraffiti** [comment]
> Does it make sense to update the app to show Monday as the beginning of week, if more businesses operate from Monday regardless of the first weekday (would it work for businesses that operate on weekends like restaurants/workshops)?

I'm not sure this is true for WooCommerce shops. Online orders can arrive any day of the week, and starting the calendar on Monday assumes that the user's business is closed on Sunday. It would confuse US users because it's not consistent with every other calendar app / paper calendar they view.

> we can get the first day of the week from the calendar locale on the device by Calendar.firstWeekday. This seems like a good alternative?

That would be great! Does the API let you specify which day of the week or which date to start the stats on?

**Comment by jaclync** [comment]
> That would be great! Does the API let you specify which day of the week or which date to start the stats on?

`calendar.firstWeekday` seems mutable so we could potentially specify the first day of the week, if we want to add a setting for this

**Comment by jaclync** [comment]
Just checked `develop`, and it looks like it's already getting the device region's first day of the week:

US | UK
-- | --
![Simulator Screen Shot - iPhone Xs - 2019-09-19 at 10 22 25](https://user-images.githubusercontent.com/1945542/65266359-c0d45a00-dac7-11e9-8d75-1cc3189c1749.png) | ![Simulator Screen Shot - iPhone Xs - 2019-09-19 at 10 21 59](https://user-images.githubusercontent.com/1945542/65266384-cfbb0c80-dac7-11e9-8247-e1da56edbc36.png)

**Comment by mindgraffiti** [comment]
@jaclync awesome. Want to do the honors and close this issue?
