### ISSUE TITLE
Order List Redesign

### ISSUE THREAD

**Issue by kyleaparker** [woocommerce/woocommerce-ios#956]
### I want to see my processing orders as well as easily be able to filter by other order types  

Ref. p99K0U-1vW-p2
Ref. p99K0U-1X8-p2
Ref. p99K0U-2ax-p2#comment-4428

Follow Android's Master List as a guide. https://github.com/woocommerce/woocommerce-android/issues/1398

**This redesign includes but isn't limited to:**
- [x] Adding dates to each table cell
- [x] Changing the order total amount to be the unfurled ($1,298.67) instead of an abbreviated string ($1.3k)
- [x] Adding a new control at the top that separates Processing orders and All orders
- [x] Add handling for future orders
- [x] Add new search UI
- [x] Refresh Order Details table data upon receiving a push notification for the new order #927 

New control design:
<img width="364" alt="Screen Shot 2020-01-06 at 4 37 24 PM" src="https://user-images.githubusercontent.com/1062444/71854130-e1d6b000-30a2-11ea-96a4-6526cf1f9b50.png">

---- 

**Is your feature request related to a problem? Please describe.**

When trying to find an order from a specific date it can be difficult to scan through right now, as we group things into an "older than a month" category.  

**Describe the solution you'd like**

Add the date to the top of each order cell: 

![iOS-order-cell](https://user-images.githubusercontent.com/712873/57557467-41c85b80-7348-11e9-9939-e13d6e237c1d.png)

Corresponding [Android issue](https://github.com/woocommerce/woocommerce-android/issues/1057)

**Comment by nbradbury** [comment]
Note: as per a discussion with @kyleaparker, we can leave off the year if it's the current one, and three-character month names are fine.
