### ISSUE TITLE
[Products/Order Creation] - "Limit one per order" toggle not respected in order

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#9688]
**Describe the bug**
When creating a product with the inventory "Limit one per order" feature turned on, the merchant could still create an order that contains two or more of that same product.

**To Reproduce**
1. Go to Products
2. Create a product and set the inventory "Limit one per order" toggle on
3. Create order and add the product from step 2
4. Set quantity to more than 1, and complete the order
5. See that order can be completed (also tried adding other products to the same order and the order can be completed)

**Screenshots**

https://github.com/woocommerce/woocommerce-ios/assets/17252150/ae579618-9c73-4f9f-9792-38df9c15e210

**Expected behavior**
Since that toggle is turned on, I would expect that only 1 of the product can be added to an order

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13 Pro
- iOS version: 16.4.1
- WooCommerce iOS version: v13.4 (current production) and v13.5 (current beta)

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by rachelmcr** [comment]
@jostnes The app behavior matches wp-admin here, which also allows merchants to manually create orders that disregard the per-order limit for products. I think that's expected for manually created orders like this, and that setting is meant for orders created on the front of the store. What do you think?

**Comment by jostnes** [comment]
> I think that's expected for manually created orders like this, and that setting is meant for orders created on the front of the store. What do you think?

Since it's the same behavior as wp-admin and is not meant for manually created orders (thanks for sharing and pointing that out @rachelmcr, I didn't think of that), I'll close this as won't fix. Thanks!
