### ISSUE TITLE
[Shipping Labels] Shipping label package details screen includes refunded products

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#9709]
**Describe the bug**

When creating a shipping label, the Package Details screen includes refunded products, which shouldn't be included in what's shipped.

**To Reproduce**
1. Create an order with items to ship.
2. Refund at least one shippable item.
3. In the app, open the order and select Create Shipping Label.
4. Go to the Package Details screen and notice the refunded item is listed.

**Screenshots**

Order details|Refunded products|Shipping label package details
-|-|-
![Simulator Screenshot - iPhone 14 Pro - 2023-05-12 at 12 28 56](https://github.com/woocommerce/woocommerce-ios/assets/8658164/fb3dd929-bb67-47d5-9222-d893846ada66)|![Simulator Screenshot - iPhone 14 Pro - 2023-05-12 at 12 29 00](https://github.com/woocommerce/woocommerce-ios/assets/8658164/638f3881-f4d3-4ca8-8ae9-8d7acba8c59a)|![Simulator Screenshot - iPhone 14 Pro - 2023-05-12 at 12 29 16](https://github.com/woocommerce/woocommerce-ios/assets/8658164/ce61e991-ed9e-46f5-8712-9fad504cd7f7)

**Expected behavior**

I expect the Package Details screen to only show non-refunded items, as in wp-admin:

![Screenshot 2023-05-12 at 12 30 40](https://github.com/woocommerce/woocommerce-ios/assets/8658164/563a3012-7825-4e45-b274-7be0c3232f9c)

**Comment by Ecarrion** [comment]
@rachelmcr since we are working on revamping Shiping Labels, would you agree that this is no longer needed? 
Maybe it is useful to add this test case to the test plan.

I'm going to close the issue but feel free to open it if you think its worth it.
