### ISSUE TITLE
Sign in improvements: Prologue. Remove references to Jetpack

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#977]
Remove all references to Jetpack from the `LoginPrologueViewController`.

Upon first inspection, that would be:
- [ ] Jetpack logo
- [ ] Reference to Jetpack in the copy

For more context, please see [this p2 thread](https://wp.me/p99K0U-1ff-p2)

**Comment by shiki** [comment]
A new project will be started which overlaps this issue. I will close this for now. Ref p91TBi-2F7-p2.
