### ISSUE TITLE
[SKU Scanner] Add fallback when product is found successfully but cannot be found locally

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#9771]
Related to https://github.com/woocommerce/woocommerce-ios/issues/9808

The current approach to circumvent this issue is to check the stored products and perform a check for variations with `Product.isProductVariation() -> ProductVariation?`, or check in both products/productvariation `ResultsController<T>` to find a match, then deal with each type appropriately, which can cause bugs and/or unexpected behaviour when the product or variation is not in local storage.

An example could be when scanning a variation, but we have not persisted the parent product, we may not have access to the variation attributes as this depends on the parent to generate some of them, which causes UI glitches like not displaying the variation image when creating the product rows.

**Comment by toupper** [comment]
@iamgabrielma I think this is solved in https://github.com/woocommerce/woocommerce-ios/pull/9969, as we pass the scanned product so we don't have to rely on what we have stored locally. Is that so?

**Comment by iamgabrielma** [comment]
I think so, yes! Closing!
