### ISSUE TITLE
Order Details: handling the shipment tracking plugin UX

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#979]
Previous PR discussion: https://github.com/woocommerce/woocommerce-ios/pull/969.

The Order Details screen looks like this:

<img src="https://user-images.githubusercontent.com/2722505/57823299-89783880-77c9-11e9-9a21-3b87f4a79957.gif" width="350" />

If a user has the Shipment Tracking plugin, the "Add tracking" row pops into place after the rest of the screen has loaded. I propose we:

1. Send an async request to detect the Shipment Tracking plugin. Possibly in the same place where we request Site Settings. Store if the plugin exists as part of the User Defaults or create a User Preferences .plist and store something like true / false / unknown.
2. If the setting is unknown, display the Loader VC and make a request that detects the shipment tracking plugin. 
3. If the setting is known, then pass a boolean to the Order Details screen so it can render the row at the same time as the other table rows. (Or not show the row, if the user doesn't have the plugin)

The Loader VC looks like this:

<img src="https://user-images.githubusercontent.com/1062444/57870435-b4b05700-77cc-11e9-9aa5-6ef0f9b07a16.gif" width="350" />

cc: @kyleaparker

**Comment by shiki** [comment]
A recent discussion has been done related to this: p91TBi-5f1-p2. And @pmusolino implemented the agreed solution in https://github.com/woocommerce/woocommerce-ios/pull/4396. 

With that, I'll close this for now. 🙂
