### ISSUE TITLE
Orders & Notifications: Odd placeholder data appears on bad network connections

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#983]
**Describe the bug**

When opening the app on a bad network connection, odd placeholder data loads on the Orders and Notifications tabs.

**To Reproduce**
1. Enable the Network Link Conditioner, and set it to 100% packet loss.
2. Launch the app.
3. Switch to the Orders tab and wait a few seconds. The flashing placeholder is replaced with odd data.
4. Switch to the Notifications tab and wait a few seconds. The flashing placeholder is replaced with odd data.

**Screenshots**
![2019-05-22 14 24 28](https://user-images.githubusercontent.com/8658164/58179198-9d2b0f80-7c9f-11e9-8ca5-3e85537069c7.png)
![2019-05-22 14 24 25](https://user-images.githubusercontent.com/8658164/58179201-9e5c3c80-7c9f-11e9-97c1-44d64769dfa9.png)

**Expected behavior**
I expected the flashing placeholders to remain as long as the app couldn't load the real data from my store.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 12.2
- WooCommerce iOS version: 1.9-rc-1

**Comment by mindgraffiti** [comment]
2413570-zen possibly experiencing this issue. It's hard to tell which platform the bug is happening on.

**Comment by mindgraffiti** [comment]
This was last seen on v 1.9, before we had empty states implemented. Ghosting looks correct and no placeholder text appears in the Orders tab after failing to load data. Here's what this screen looks like after the ghosting removes:

<img src="https://user-images.githubusercontent.com/1062444/70467234-6fb28180-1a8a-11ea-9c35-9118939deed5.png" width="350" />

@jaclync I see you're assigned to this one, so I'm not going to close it in case you saw something different while testing.

**Comment by mindgraffiti** [comment]
This is fixed. Ghosting cells appear, then after a long wait, the empty state appears:

<img src="https://user-images.githubusercontent.com/1062444/72105001-3de34380-32f2-11ea-91eb-82e422297b2c.png" width="350" />
