### ISSUE TITLE
Shipment Tracking: Shipping provider search results are hard to see when device keyboard is on screen

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#984]
**Describe the bug**

When fulfilling an order, under Add Tracking > Shipping Provider, I noticed that the shipping providers for my store's countries appear at the top of the list. That's really useful.

However, when I search for a provider that section doesn't change at all. That's confusing, especially because when my keyboard is on screen I can't see past the end of that list (where the search results appear) so it looks like the search isn't working.

**To Reproduce**

0. Start on a store with the Shipment Tracking extension.
1. Go to Orders.
2. Select an order with the Processing status.
3. Select Fulfill order.
4. Select "Add Tracking."
5. Select "Shipping provider." Note that on the Shipping Providers screen, "Custom" is at the top of the list, then providers from your store's country, and then an alphabetical list of countries with their providers.
6. Search for a known provider, e.g. USPS or Royal Mail. Note that the top two sections (custom and your store's country) don't change, and the search results appear below them (off screen on a small device when the store's country has a long list).

**Screenshots**

![shippingproviders-wcios](https://user-images.githubusercontent.com/8658164/58187443-ad96b680-7cae-11e9-9fb0-f16bef9287e2.gif)

**Expected behavior**

I expected the search results to appear at or near the top of the screen. I didn't expect the entire section of my country's shipping providers to remain as-is while I performed the search, especially with providers duplicated in the search results below it.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 12.2
- WooCommerce iOS version: 1.9-rc-1

**Comment by ctarda** [comment]
Closing. Implemented in #985
