### ISSUE TITLE
Order Details: Center "Show billing" button 

### ISSUE THREAD

**Issue by kyleaparker** [woocommerce/woocommerce-ios#989]
**Describe the bug**
On the Order Detail screen, the "Show Billing" button is currently centred to the text only, rather than the text + chevron: 

<img width="429" alt="IMG_2103 PNG 2019-05-27 12-50-17" src="https://user-images.githubusercontent.com/712873/58431962-1c448d00-807e-11e9-8bf3-6857e8839e8a.png">

**Expected behavior**
Center the text + icon so the left/right spacing is even

**Comment by mindgraffiti** [comment]
Thank you @kyleaparker!
