### ISSUE TITLE
Products added back to order after being removed

### ISSUE THREAD

**Issue by lmischner** [woocommerce/woocommerce-ios#9956]
**Describe the bug**
There can be a mismatch between what's shown in the product list in the order and product selection.
This can be as minimal as the checkmark not being sync'd and as bad as adding in products that the user intentionally removed.

**To Reproduce**
Setup: Variation subscription where a specific variation has a SKU defined

Steps to reproduce the behavior (these might be overly specific, but how I had luck reliably reproducing):
1. Create new order > Add products
2. In product search, search by SKU to add the variation subscription
3. Add product to order
4. Add another product
5. Quickly increment the quantity of the variable subscription
6. Quickly decrease the quantity until you've removed the variable subscription completely
7. Quickly tap Add product again
8. Note the variable subscription is still selected
9. Don't make changes, but close product selection
10. note that variable subscription is added back 

**Screenshots**

https://github.com/woocommerce/woocommerce-ios/assets/103850310/5dce9f1d-1b0b-4a74-8481-3f6275c1b6b3

https://github.com/woocommerce/woocommerce-ios/assets/103850310/4b678019-dd14-40a4-8f18-8716a0b9f6d3

**Expected behavior**
If a product is removed, it says removed
Products in order should match product selection

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 16.5
- WooCommerce iOS version: 14.0 (pr9955-5d6212c)

Might be a duplicate of [this comment](https://github.com/woocommerce/woocommerce-ios/pull/8943#issuecomment-1471855269), but couldn't find a separate issue describing it.

**Comment by Ecarrion** [comment]
This seems to be fixed as there is now a dedicated "Remove product from order" button.
